var globals_vars =
[
    [ "a", "pages/globals_vars.html", null ],
    [ "b", "pages/globals_vars_b.html", null ],
    [ "c", "pages/globals_vars_c.html", null ],
    [ "d", "pages/globals_vars_d.html", null ],
    [ "e", "pages/globals_vars_e.html", null ],
    [ "f", "pages/globals_vars_f.html", null ],
    [ "g", "pages/globals_vars_g.html", null ],
    [ "h", "pages/globals_vars_h.html", null ],
    [ "i", "pages/globals_vars_i.html", null ],
    [ "k", "pages/globals_vars_k.html", null ],
    [ "l", "pages/globals_vars_l.html", null ],
    [ "m", "pages/globals_vars_m.html", null ],
    [ "n", "pages/globals_vars_n.html", null ],
    [ "o", "pages/globals_vars_o.html", null ],
    [ "p", "pages/globals_vars_p.html", null ],
    [ "q", "pages/globals_vars_q.html", null ],
    [ "r", "pages/globals_vars_r.html", null ],
    [ "s", "pages/globals_vars_s.html", null ],
    [ "t", "pages/globals_vars_t.html", null ],
    [ "u", "pages/globals_vars_u.html", null ],
    [ "v", "pages/globals_vars_v.html", null ],
    [ "w", "pages/globals_vars_w.html", null ]
];