/*
 @licstart  The following is the entire license notice for the JavaScript code in this file.

 The MIT License (MIT)

 Copyright (C) 1997-2020 by Dimitri van Heesch

 Permission is hereby granted, free of charge, to any person obtaining a copy of this software
 and associated documentation files (the "Software"), to deal in the Software without restriction,
 including without limitation the rights to use, copy, modify, merge, publish, distribute,
 sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in all copies or
 substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
 BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
 DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

 @licend  The above is the entire license notice for the JavaScript code in this file
*/
var menudata={children:[
{text:"Main Page",url:"index.html"},
{text:"Related Pages",url:"pages/pages.html"},
{text:"Namespaces",url:"pages/namespaces.html",children:[
{text:"Namespace List",url:"pages/namespaces.html"},
{text:"Namespace Members",url:"pages/namespacemembers.html",children:[
{text:"All",url:"pages/namespacemembers.html",children:[
{text:"a",url:"pages/namespacemembers.html#index_a"},
{text:"b",url:"pages/namespacemembers_b.html#index_b"},
{text:"c",url:"pages/namespacemembers_c.html#index_c"},
{text:"d",url:"pages/namespacemembers_d.html#index_d"},
{text:"e",url:"pages/namespacemembers_e.html#index_e"},
{text:"f",url:"pages/namespacemembers_f.html#index_f"},
{text:"g",url:"pages/namespacemembers_g.html#index_g"},
{text:"h",url:"pages/namespacemembers_h.html#index_h"},
{text:"i",url:"pages/namespacemembers_i.html#index_i"},
{text:"k",url:"pages/namespacemembers_k.html#index_k"},
{text:"l",url:"pages/namespacemembers_l.html#index_l"},
{text:"m",url:"pages/namespacemembers_m.html#index_m"},
{text:"n",url:"pages/namespacemembers_n.html#index_n"},
{text:"o",url:"pages/namespacemembers_o.html#index_o"},
{text:"p",url:"pages/namespacemembers_p.html#index_p"},
{text:"r",url:"pages/namespacemembers_r.html#index_r"},
{text:"s",url:"pages/namespacemembers_s.html#index_s"},
{text:"t",url:"pages/namespacemembers_t.html#index_t"},
{text:"w",url:"pages/namespacemembers_w.html#index_w"},
{text:"z",url:"pages/namespacemembers_z.html#index_z"}]},
{text:"Functions",url:"pages/namespacemembers_func.html",children:[
{text:"a",url:"pages/namespacemembers_func.html#index_a"},
{text:"b",url:"pages/namespacemembers_func_b.html#index_b"},
{text:"c",url:"pages/namespacemembers_func_c.html#index_c"},
{text:"d",url:"pages/namespacemembers_func_d.html#index_d"},
{text:"e",url:"pages/namespacemembers_func_e.html#index_e"},
{text:"f",url:"pages/namespacemembers_func_f.html#index_f"},
{text:"g",url:"pages/namespacemembers_func_g.html#index_g"},
{text:"h",url:"pages/namespacemembers_func_h.html#index_h"},
{text:"i",url:"pages/namespacemembers_func_i.html#index_i"},
{text:"l",url:"pages/namespacemembers_func_l.html#index_l"},
{text:"m",url:"pages/namespacemembers_func_m.html#index_m"},
{text:"n",url:"pages/namespacemembers_func_n.html#index_n"},
{text:"o",url:"pages/namespacemembers_func_o.html#index_o"},
{text:"p",url:"pages/namespacemembers_func_p.html#index_p"},
{text:"r",url:"pages/namespacemembers_func_r.html#index_r"},
{text:"s",url:"pages/namespacemembers_func_s.html#index_s"},
{text:"t",url:"pages/namespacemembers_func_t.html#index_t"},
{text:"w",url:"pages/namespacemembers_func_w.html#index_w"}]},
{text:"Variables",url:"pages/namespacemembers_vars.html",children:[
{text:"c",url:"pages/namespacemembers_vars.html#index_c"},
{text:"g",url:"pages/namespacemembers_vars.html#index_g"},
{text:"k",url:"pages/namespacemembers_vars.html#index_k"},
{text:"m",url:"pages/namespacemembers_vars.html#index_m"},
{text:"p",url:"pages/namespacemembers_vars.html#index_p"},
{text:"w",url:"pages/namespacemembers_vars.html#index_w"}]},
{text:"Typedefs",url:"pages/namespacemembers_type.html"},
{text:"Enumerations",url:"pages/namespacemembers_enum.html"},
{text:"Enumerator",url:"pages/namespacemembers_eval.html"}]}]},
{text:"Classes",url:"pages/annotated.html",children:[
{text:"Class List",url:"pages/annotated.html"},
{text:"Class Index",url:"pages/classes.html"},
{text:"Class Hierarchy",url:"pages/inherits.html"},
{text:"Class Members",url:"pages/functions.html",children:[
{text:"All",url:"pages/functions.html",children:[
{text:"_",url:"pages/functions.html#index__5F"},
{text:"a",url:"pages/functions_a.html#index_a"},
{text:"b",url:"pages/functions_b.html#index_b"},
{text:"c",url:"pages/functions_c.html#index_c"},
{text:"d",url:"pages/functions_d.html#index_d"},
{text:"e",url:"pages/functions_e.html#index_e"},
{text:"f",url:"pages/functions_f.html#index_f"},
{text:"g",url:"pages/functions_g.html#index_g"},
{text:"h",url:"pages/functions_h.html#index_h"},
{text:"i",url:"pages/functions_i.html#index_i"},
{text:"j",url:"pages/functions_j.html#index_j"},
{text:"k",url:"pages/functions_k.html#index_k"},
{text:"l",url:"pages/functions_l.html#index_l"},
{text:"m",url:"pages/functions_m.html#index_m"},
{text:"n",url:"pages/functions_n.html#index_n"},
{text:"o",url:"pages/functions_o.html#index_o"},
{text:"p",url:"pages/functions_p.html#index_p"},
{text:"q",url:"pages/functions_q.html#index_q"},
{text:"r",url:"pages/functions_r.html#index_r"},
{text:"s",url:"pages/functions_s.html#index_s"},
{text:"t",url:"pages/functions_t.html#index_t"},
{text:"u",url:"pages/functions_u.html#index_u"},
{text:"v",url:"pages/functions_v.html#index_v"},
{text:"w",url:"pages/functions_w.html#index_w"},
{text:"x",url:"pages/functions_x.html#index_x"},
{text:"y",url:"pages/functions_y.html#index_y"},
{text:"z",url:"pages/functions_z.html#index_z"},
{text:"~",url:"pages/functions_~.html#index__7E"}]},
{text:"Functions",url:"pages/functions_func.html",children:[
{text:"a",url:"pages/functions_func.html#index_a"},
{text:"b",url:"pages/functions_func_b.html#index_b"},
{text:"c",url:"pages/functions_func_c.html#index_c"},
{text:"d",url:"pages/functions_func_d.html#index_d"},
{text:"e",url:"pages/functions_func_e.html#index_e"},
{text:"f",url:"pages/functions_func_f.html#index_f"},
{text:"g",url:"pages/functions_func_g.html#index_g"},
{text:"h",url:"pages/functions_func_h.html#index_h"},
{text:"i",url:"pages/functions_func_i.html#index_i"},
{text:"k",url:"pages/functions_func_k.html#index_k"},
{text:"l",url:"pages/functions_func_l.html#index_l"},
{text:"m",url:"pages/functions_func_m.html#index_m"},
{text:"n",url:"pages/functions_func_n.html#index_n"},
{text:"o",url:"pages/functions_func_o.html#index_o"},
{text:"p",url:"pages/functions_func_p.html#index_p"},
{text:"q",url:"pages/functions_func_q.html#index_q"},
{text:"r",url:"pages/functions_func_r.html#index_r"},
{text:"s",url:"pages/functions_func_s.html#index_s"},
{text:"t",url:"pages/functions_func_t.html#index_t"},
{text:"u",url:"pages/functions_func_u.html#index_u"},
{text:"v",url:"pages/functions_func_v.html#index_v"},
{text:"w",url:"pages/functions_func_w.html#index_w"},
{text:"x",url:"pages/functions_func_x.html#index_x"},
{text:"y",url:"pages/functions_func_y.html#index_y"},
{text:"z",url:"pages/functions_func_z.html#index_z"},
{text:"~",url:"pages/functions_func_~.html#index__7E"}]},
{text:"Variables",url:"pages/functions_vars.html",children:[
{text:"_",url:"pages/functions_vars.html#index__5F"},
{text:"a",url:"pages/functions_vars_a.html#index_a"},
{text:"b",url:"pages/functions_vars_b.html#index_b"},
{text:"c",url:"pages/functions_vars_c.html#index_c"},
{text:"d",url:"pages/functions_vars_d.html#index_d"},
{text:"e",url:"pages/functions_vars_e.html#index_e"},
{text:"f",url:"pages/functions_vars_f.html#index_f"},
{text:"g",url:"pages/functions_vars_g.html#index_g"},
{text:"h",url:"pages/functions_vars_h.html#index_h"},
{text:"i",url:"pages/functions_vars_i.html#index_i"},
{text:"j",url:"pages/functions_vars_j.html#index_j"},
{text:"k",url:"pages/functions_vars_k.html#index_k"},
{text:"l",url:"pages/functions_vars_l.html#index_l"},
{text:"m",url:"pages/functions_vars_m.html#index_m"},
{text:"n",url:"pages/functions_vars_n.html#index_n"},
{text:"o",url:"pages/functions_vars_o.html#index_o"},
{text:"p",url:"pages/functions_vars_p.html#index_p"},
{text:"q",url:"pages/functions_vars_q.html#index_q"},
{text:"r",url:"pages/functions_vars_r.html#index_r"},
{text:"s",url:"pages/functions_vars_s.html#index_s"},
{text:"t",url:"pages/functions_vars_t.html#index_t"},
{text:"u",url:"pages/functions_vars_u.html#index_u"},
{text:"v",url:"pages/functions_vars_v.html#index_v"},
{text:"w",url:"pages/functions_vars_w.html#index_w"}]},
{text:"Typedefs",url:"pages/functions_type.html",children:[
{text:"b",url:"pages/functions_type.html#index_b"},
{text:"c",url:"pages/functions_type.html#index_c"},
{text:"d",url:"pages/functions_type.html#index_d"},
{text:"f",url:"pages/functions_type.html#index_f"},
{text:"i",url:"pages/functions_type.html#index_i"},
{text:"l",url:"pages/functions_type.html#index_l"},
{text:"m",url:"pages/functions_type.html#index_m"},
{text:"o",url:"pages/functions_type.html#index_o"},
{text:"p",url:"pages/functions_type.html#index_p"},
{text:"r",url:"pages/functions_type.html#index_r"},
{text:"s",url:"pages/functions_type.html#index_s"},
{text:"t",url:"pages/functions_type.html#index_t"},
{text:"u",url:"pages/functions_type.html#index_u"},
{text:"v",url:"pages/functions_type.html#index_v"},
{text:"w",url:"pages/functions_type.html#index_w"}]},
{text:"Enumerations",url:"pages/functions_enum.html"},
{text:"Enumerator",url:"pages/functions_eval.html"},
{text:"Related Symbols",url:"pages/functions_rela.html",children:[
{text:"e",url:"pages/functions_rela.html#index_e"},
{text:"h",url:"pages/functions_rela.html#index_h"},
{text:"i",url:"pages/functions_rela.html#index_i"},
{text:"l",url:"pages/functions_rela.html#index_l"},
{text:"n",url:"pages/functions_rela.html#index_n"},
{text:"o",url:"pages/functions_rela.html#index_o"},
{text:"p",url:"pages/functions_rela.html#index_p"},
{text:"r",url:"pages/functions_rela.html#index_r"},
{text:"s",url:"pages/functions_rela.html#index_s"},
{text:"t",url:"pages/functions_rela.html#index_t"},
{text:"v",url:"pages/functions_rela.html#index_v"}]}]}]},
{text:"Files",url:"pages/files.html",children:[
{text:"File List",url:"pages/files.html"},
{text:"File Members",url:"pages/globals.html",children:[
{text:"All",url:"pages/globals.html",children:[
{text:"a",url:"pages/globals.html#index_a"},
{text:"b",url:"pages/globals_b.html#index_b"},
{text:"c",url:"pages/globals_c.html#index_c"},
{text:"d",url:"pages/globals_d.html#index_d"},
{text:"e",url:"pages/globals_e.html#index_e"},
{text:"f",url:"pages/globals_f.html#index_f"},
{text:"g",url:"pages/globals_g.html#index_g"},
{text:"h",url:"pages/globals_h.html#index_h"},
{text:"i",url:"pages/globals_i.html#index_i"},
{text:"k",url:"pages/globals_k.html#index_k"},
{text:"l",url:"pages/globals_l.html#index_l"},
{text:"m",url:"pages/globals_m.html#index_m"},
{text:"n",url:"pages/globals_n.html#index_n"},
{text:"o",url:"pages/globals_o.html#index_o"},
{text:"p",url:"pages/globals_p.html#index_p"},
{text:"q",url:"pages/globals_q.html#index_q"},
{text:"r",url:"pages/globals_r.html#index_r"},
{text:"s",url:"pages/globals_s.html#index_s"},
{text:"t",url:"pages/globals_t.html#index_t"},
{text:"u",url:"pages/globals_u.html#index_u"},
{text:"v",url:"pages/globals_v.html#index_v"},
{text:"w",url:"pages/globals_w.html#index_w"}]},
{text:"Functions",url:"pages/globals_func.html"},
{text:"Variables",url:"pages/globals_vars.html",children:[
{text:"a",url:"pages/globals_vars.html#index_a"},
{text:"b",url:"pages/globals_vars_b.html#index_b"},
{text:"c",url:"pages/globals_vars_c.html#index_c"},
{text:"d",url:"pages/globals_vars_d.html#index_d"},
{text:"e",url:"pages/globals_vars_e.html#index_e"},
{text:"f",url:"pages/globals_vars_f.html#index_f"},
{text:"g",url:"pages/globals_vars_g.html#index_g"},
{text:"h",url:"pages/globals_vars_h.html#index_h"},
{text:"i",url:"pages/globals_vars_i.html#index_i"},
{text:"k",url:"pages/globals_vars_k.html#index_k"},
{text:"l",url:"pages/globals_vars_l.html#index_l"},
{text:"m",url:"pages/globals_vars_m.html#index_m"},
{text:"n",url:"pages/globals_vars_n.html#index_n"},
{text:"o",url:"pages/globals_vars_o.html#index_o"},
{text:"p",url:"pages/globals_vars_p.html#index_p"},
{text:"q",url:"pages/globals_vars_q.html#index_q"},
{text:"r",url:"pages/globals_vars_r.html#index_r"},
{text:"s",url:"pages/globals_vars_s.html#index_s"},
{text:"t",url:"pages/globals_vars_t.html#index_t"},
{text:"u",url:"pages/globals_vars_u.html#index_u"},
{text:"v",url:"pages/globals_vars_v.html#index_v"},
{text:"w",url:"pages/globals_vars_w.html#index_w"}]},
{text:"Typedefs",url:"pages/globals_type.html"},
{text:"Macros",url:"pages/globals_defs.html",children:[
{text:"a",url:"pages/globals_defs.html#index_a"},
{text:"b",url:"pages/globals_defs.html#index_b"},
{text:"c",url:"pages/globals_defs.html#index_c"},
{text:"d",url:"pages/globals_defs.html#index_d"},
{text:"e",url:"pages/globals_defs.html#index_e"},
{text:"f",url:"pages/globals_defs.html#index_f"},
{text:"g",url:"pages/globals_defs.html#index_g"},
{text:"i",url:"pages/globals_defs.html#index_i"},
{text:"k",url:"pages/globals_defs.html#index_k"},
{text:"l",url:"pages/globals_defs.html#index_l"},
{text:"m",url:"pages/globals_defs.html#index_m"},
{text:"n",url:"pages/globals_defs.html#index_n"},
{text:"p",url:"pages/globals_defs.html#index_p"},
{text:"r",url:"pages/globals_defs.html#index_r"},
{text:"s",url:"pages/globals_defs.html#index_s"},
{text:"t",url:"pages/globals_defs.html#index_t"},
{text:"u",url:"pages/globals_defs.html#index_u"}]}]}]}]}
