Leela Chess Zero: lczero::PjrtExecutable Class Reference
lczero::PjrtExecutable Class Reference
#include <pjrt.h>
Public Member Functions
PjrtExecutable (const PJRT_Api *api, PJRT_LoadedExecutable *executable)
~PjrtExecutable ()
std::vector< std::unique_ptr< PjrtDeviceBuffer > > ExecuteBlocking (const std::vector< PjrtDeviceBuffer * > &inputs)
size_t GetNumOutputs () const
Private Attributes
PJRT_LoadedExecutable * executable_
size_t num_outputs_
Additional Inherited Members
Protected Member Functions inherited from lczero::PjrtCommon
PjrtCommon (const PJRT_Api *api)
virtual ~PjrtCommon ()=default
std::string GetErrorMessage (PJRT_Error *error) const
void DestroyErrorMessage (PJRT_Error *error) const
void CheckError (PJRT_Error *error) const
Protected Attributes inherited from lczero::PjrtCommon
const PJRT_Api * api_
Detailed Description
Definition at line 192 of file pjrt.h.
Constructor & Destructor Documentation
PjrtExecutable()
lczero::PjrtExecutable::PjrtExecutable (const PJRT_Api * api, PJRT_LoadedExecutable * executable)
Definition at line 129 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), executable_, and num_outputs_.
~PjrtExecutable()
lczero::PjrtExecutable::~PjrtExecutable ()
Definition at line 142 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), and executable_.
Member Function Documentation
ExecuteBlocking()
std::vector< std::unique_ptr< PjrtDeviceBuffer > > lczero::PjrtExecutable::ExecuteBlocking (const std::vector< PjrtDeviceBuffer * > & inputs)
Definition at line 150 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), executable_, and num_outputs_.
GetNumOutputs()
size_t lczero::PjrtExecutable::GetNumOutputs () const
Definition at line 148 of file pjrt.cc.
References num_outputs_.
Member Data Documentation
executable_
PJRT_LoadedExecutable* lczero::PjrtExecutable::executable_ private
Definition at line 203 of file pjrt.h.
Referenced by ExecuteBlocking(), PjrtExecutable(), and ~PjrtExecutable().
num_outputs_
size_t lczero::PjrtExecutable::num_outputs_ private
Definition at line 204 of file pjrt.h.
Referenced by ExecuteBlocking(), GetNumOutputs(), and PjrtExecutable().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/xla/pjrt.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/xla/pjrt.cc