Leela Chess Zero: lczero::Pjrt Class Reference
lczero::Pjrt Class Reference
#include <pjrt.h>
Public Member Functions
Pjrt (const char *library_path)
std::vector< PjrtKeyValue > GetAttributes () const
std::unique_ptr< PjrtClient > CreateClient ()
std::pair< int, int > ApiVersion () const
Private Member Functions
void Initialize ()
Additional Inherited Members
Protected Member Functions inherited from lczero::PjrtCommon
PjrtCommon (const PJRT_Api *api)
virtual ~PjrtCommon ()=default
std::string GetErrorMessage (PJRT_Error *error) const
void DestroyErrorMessage (PJRT_Error *error) const
void CheckError (PJRT_Error *error) const
Protected Attributes inherited from lczero::PjrtCommon
const PJRT_Api * api_
Detailed Description
Definition at line 241 of file pjrt.h.
Constructor & Destructor Documentation
Pjrt()
lczero::Pjrt::Pjrt (const char * library_path)
Definition at line 342 of file pjrt.cc.
References lczero::PjrtCommon::api_, ApiVersion(), Initialize(), and lczero::INVALID_ARGUMENT.
Member Function Documentation
ApiVersion()
std::pair< int, int > lczero::Pjrt::ApiVersion () const
Definition at line 393 of file pjrt.cc.
References lczero::PjrtCommon::api_.
Referenced by Pjrt().
CreateClient()
std::unique_ptr< PjrtClient > lczero::Pjrt::CreateClient ()
Definition at line 387 of file pjrt.cc.
References lczero::PjrtCommon::api_, and lczero::PjrtCommon::CheckError().
GetAttributes()
std::vector< PjrtKeyValue > lczero::Pjrt::GetAttributes () const
Definition at line 376 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), lczero::MakeKeyValue(), and result.
Initialize()
void lczero::Pjrt::Initialize () private
Definition at line 398 of file pjrt.cc.
References lczero::PjrtCommon::api_, and lczero::PjrtCommon::CheckError().
Referenced by Pjrt().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/xla/pjrt.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/xla/pjrt.cc