Leela Chess Zero: lczero::cudnn_backend::SELayer< DataType > Class Template Reference
lczero::cudnn_backend::SELayer< DataType > Class Template Reference
#include <layers.h>
Public Member Functions
SELayer (BaseLayer< DataType > *ip, int numFc1Out, bool addPrevLayerBias, ActivationFunction activation)
~SELayer ()
void LoadWeights (float *w1, float *b1, float *w2, float *b2, float *prevLayerBias, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType ***=nullptr) override
void LoadWeights (float *w1, float *b1, float *w2, float *b2, float *prevLayerBias, void *)
void LoadWeights (float *w1, float *b1, float *w2, float *b2, float *prevLayerBias, void *scratch)
void Eval (int N, float *output, const float *input, const float *, void *scratch, size_t scratch_size, cudnnHandle_t, cublasHandle_t cublas, cudaStream_t stream, float ***)
void Eval (int N, half *output, const half *input, const half *input2, void *scratch, size_t scratch_size, cudnnHandle_t, cublasHandle_t cublas, cudaStream_t stream, half ***)
Public Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, bool use_gemm_ex)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
DataType * w1_ = nullptr
DataType * w1_t_ = nullptr
DataType * b1_ = nullptr
DataType * w2_ = nullptr
DataType * w2_t_ = nullptr
DataType * b2_ = nullptr
DataType * bPrev_ = nullptr
int numFc1Out_
bool addPrevLayerBias_
const ActivationFunction act_
Additional Inherited Members
Protected Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const half *A, const half *B, half *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
Protected Attributes inherited from lczero::cudnn_backend::BaseLayer< DataType >
BaseLayer * input_
int C
int H
int W
bool nhwc_
const bool use_gemm_ex_
Detailed Description
template<typename DataType>
class lczero::cudnn_backend::SELayer< DataType >
Definition at line 182 of file layers.h.
Constructor & Destructor Documentation
SELayer()
template<typename DataType > lczero::cudnn_backend::SELayer< DataType >::SELayer (BaseLayer< DataType > * ip, int numFc1Out, bool addPrevLayerBias, ActivationFunction activation)
Definition at line 370 of file layers.cc.
References lczero::cudnn_backend::SELayer< DataType >::b1_, lczero::cudnn_backend::SELayer< DataType >::b2_, lczero::cudnn_backend::SELayer< DataType >::bPrev_, lczero::cudnn_backend::BaseLayer< DataType >::C, lczero::cudnn_backend::kUseFusedSELayer, lczero::cudnn_backend::BaseLayer< DataType >::nhwc_, lczero::cudnn_backend::SELayer< DataType >::numFc1Out_, ReportCUDAErrors, lczero::cudnn_backend::SELayer< DataType >::w1_, lczero::cudnn_backend::SELayer< DataType >::w1_t_, lczero::cudnn_backend::SELayer< DataType >::w2_, and lczero::cudnn_backend::SELayer< DataType >::w2_t_.
~SELayer()
template<typename DataType > lczero::cudnn_backend::SELayer< DataType >::~SELayer ()
Definition at line 391 of file layers.cc.
References ReportCUDAErrors.
Member Function Documentation
Eval() [1/3]
template<typename DataType > void lczero::cudnn_backend::SELayer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType *** = nullptr) override virtual
Implements lczero::cudnn_backend::BaseLayer< DataType >.
Eval() [2/3]
void lczero::cudnn_backend::SELayer< float >::Eval (int N, float * output, const float * input, const float * , void * scratch, size_t scratch_size, cudnnHandle_t , cublasHandle_t cublas, cudaStream_t stream, float ***)
Definition at line 487 of file layers.cc.
References lczero::ACTIVATION_NONE, lczero::cudnn_backend::addVectors(), C, lczero::cudnn_backend::globalAvgPool(), lczero::cudnn_backend::globalScale(), input, output, and ReportCUBLASErrors.
Eval() [3/3]
void lczero::cudnn_backend::SELayer< half >::Eval (int N, half * output, const half * input, const half * input2, void * scratch, size_t scratch_size, cudnnHandle_t , cublasHandle_t cublas, cudaStream_t stream, half ***)
Definition at line 521 of file layers.cc.
References lczero::ACTIVATION_NONE, lczero::cudnn_backend::addVectors(), C, lczero::cudnn_backend::globalAvgPool(), lczero::cudnn_backend::globalScale(), input, lczero::cudnn_backend::kUseFusedSELayer, output, ReportCUBLASErrors, and lczero::cudnn_backend::Se_Fp16_NHWC().
LoadWeights() [1/3]
void lczero::cudnn_backend::SELayer< float >::LoadWeights (float * w1, float * b1, float * w2, float * b2, float * prevLayerBias, void *)
Definition at line 400 of file layers.cc.
References C, and ReportCUDAErrors.
LoadWeights() [2/3]
void lczero::cudnn_backend::SELayer< half >::LoadWeights (float * w1, float * b1, float * w2, float * b2, float * prevLayerBias, void * scratch)
Definition at line 434 of file layers.cc.
References C, lczero::cudnn_backend::copyTypeConverted(), lczero::cudnn_backend::cpuTranspose(), lczero::cudnn_backend::kUseFusedSELayer, and ReportCUDAErrors.
LoadWeights() [3/3]
template<typename DataType > void lczero::cudnn_backend::SELayer< DataType >::LoadWeights (float * w1, float * b1, float * w2, float * b2, float * prevLayerBias, void * scratch)
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::cudnn_backend::SELayer< DataType >::act_ private
Definition at line 209 of file layers.h.
addPrevLayerBias_
template<typename DataType > bool lczero::cudnn_backend::SELayer< DataType >::addPrevLayerBias_ private
Definition at line 208 of file layers.h.
b1_
template<typename DataType > DataType* lczero::cudnn_backend::SELayer< DataType >::b1_ = nullptr private
Definition at line 202 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
b2_
template<typename DataType > DataType* lczero::cudnn_backend::SELayer< DataType >::b2_ = nullptr private
Definition at line 205 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
bPrev_
template<typename DataType > DataType* lczero::cudnn_backend::SELayer< DataType >::bPrev_ = nullptr private
Definition at line 206 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
numFc1Out_
template<typename DataType > int lczero::cudnn_backend::SELayer< DataType >::numFc1Out_ private
Definition at line 207 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
w1_
template<typename DataType > DataType* lczero::cudnn_backend::SELayer< DataType >::w1_ = nullptr private
Definition at line 200 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
w1_t_
template<typename DataType > DataType* lczero::cudnn_backend::SELayer< DataType >::w1_t_ = nullptr private
Definition at line 201 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
w2_
template<typename DataType > DataType* lczero::cudnn_backend::SELayer< DataType >::w2_ = nullptr private
Definition at line 203 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
w2_t_
template<typename DataType > DataType* lczero::cudnn_backend::SELayer< DataType >::w2_t_ = nullptr private
Definition at line 204 of file layers.h.
Referenced by lczero::cudnn_backend::SELayer< DataType >::SELayer().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/cuda/layers.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/cuda/layers.cc