Leela Chess Zero: lczero::Backend Class Reference
lczero::Backend Class Reference abstract
#include <backend.h>
Public Types
enum UpdateConfigurationResult { UPDATE_OK = 0 , NEED_RESTART = 1 }
Public Member Functions
virtual ~Backend ()=default
virtual BackendAttributes GetAttributes () const =0
virtual std::unique_ptr< BackendComputation > CreateComputation ()=0
virtual std::vector< EvalResult > EvaluateBatch (std::span< const EvalPosition > positions)
virtual std::optional< EvalResult > GetCachedEvaluation (const EvalPosition &)
virtual UpdateConfigurationResult UpdateConfiguration (const OptionsDict &opts)
virtual bool IsSameConfiguration (const OptionsDict &opts) const
Private Member Functions
virtual uint64_t ConfigurationHash (const OptionsDict &) const
Private Attributes
uint64_t current_config_hash_
Detailed Description
Definition at line 89 of file backend.h.
Member Enumeration Documentation
UpdateConfigurationResult
enum lczero::Backend::UpdateConfigurationResult
Enumerator
UPDATE_OK
NEED_RESTART
Definition at line 106 of file backend.h.
Constructor & Destructor Documentation
~Backend()
virtual lczero::Backend::~Backend () virtual default
Member Function Documentation
ConfigurationHash()
uint64_t lczero::Backend::ConfigurationHash (const OptionsDict & options) const private virtual
Definition at line 54 of file backend.cc.
References lczero::OptionsDict::Get(), lczero::HashCat(), lczero::SharedBackendParams::kBackendId, lczero::SharedBackendParams::kBackendOptionsId, lczero::SharedBackendParams::kHistoryFill, lczero::SharedBackendParams::kPolicySoftmaxTemp, and lczero::SharedBackendParams::kWeightsId.
Referenced by IsSameConfiguration(), and UpdateConfiguration().
CreateComputation()
virtual std::unique_ptr< BackendComputation > lczero::Backend::CreateComputation () pure virtual
Referenced by EvaluateBatch(), lczero::classic::SearchWorker::InitializeIteration(), lczero::dag_classic::SearchWorker::InitializeIteration(), lczero::PolicyEvaluator::Reset(), and lczero::ValueEvaluator::Reset().
EvaluateBatch()
std::vector< EvalResult > lczero::Backend::EvaluateBatch (std::span< const EvalPosition > positions) virtual
Definition at line 37 of file backend.cc.
References CreateComputation(), lczero::EvalResult::p, lczero::EvalResultPtr::q, and result.
GetAttributes()
virtual BackendAttributes lczero::Backend::GetAttributes () const pure virtual
GetCachedEvaluation()
virtual std::optional< EvalResult > lczero::Backend::GetCachedEvaluation (const EvalPosition &) inline virtual
Definition at line 100 of file backend.h.
Referenced by lczero::classic::Search::GetVerboseStats(), lczero::dag_classic::Search::GetVerboseStats(), lczero::SelfPlayGame::Play(), and lczero::classic::SearchWorker::PrefetchIntoCache().
IsSameConfiguration()
virtual bool lczero::Backend::IsSameConfiguration (const OptionsDict & opts) const inline virtual
Definition at line 116 of file backend.h.
References ConfigurationHash(), and current_config_hash_.
UpdateConfiguration()
virtual UpdateConfigurationResult lczero::Backend::UpdateConfiguration (const OptionsDict & opts) inline virtual
Definition at line 110 of file backend.h.
References ConfigurationHash(), current_config_hash_, and UPDATE_OK.
Member Data Documentation
current_config_hash_
uint64_t lczero::Backend::current_config_hash_ private
Definition at line 124 of file backend.h.
Referenced by IsSameConfiguration(), and UpdateConfiguration().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backend.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backend.cc