Leela Chess Zero: lczero::UciLoop Class Reference
lczero::UciLoop Class Reference
#include <uciloop.h>
Public Member Functions
UciLoop (StringUciResponder *uci_responder, OptionsParser *options, EngineControllerBase *engine)
virtual ~UciLoop ()
bool ProcessLine (const std::string &line)
Protected Member Functions
bool DispatchCommand (const std::string &command, const std::unordered_map< std::string, std::string > &params)
Protected Attributes
StringUciResponder * uci_responder_
OptionsParser * options_
EngineControllerBase * engine_
Detailed Description
Definition at line 103 of file uciloop.h.
Constructor & Destructor Documentation
UciLoop()
lczero::UciLoop::UciLoop (StringUciResponder * uci_responder, OptionsParser * options, EngineControllerBase * engine)
Definition at line 171 of file uciloop.cc.
References engine_, lczero::EngineControllerBase::RegisterUciResponder(), and uci_responder_.
~UciLoop()
lczero::UciLoop::~UciLoop () virtual
Definition at line 177 of file uciloop.cc.
References engine_, uci_responder_, and lczero::EngineControllerBase::UnregisterUciResponder().
Member Function Documentation
DispatchCommand()
bool lczero::UciLoop::DispatchCommand (const std::string & command, const std::unordered_map< std::string, std::string > & params) protected
Definition at line 179 of file uciloop.cc.
References engine_, lczero::EngineControllerBase::EnsureReady(), fen, lczero::EngineControllerBase::Go(), lczero::GoParams::infinite, lczero::ChessBoard::kStartposFen, lczero::OptionsParser::ListOptionsUci(), moves, lczero::EngineControllerBase::NewGame(), options_, lczero::GoParams::ponder, lczero::EngineControllerBase::PonderHit(), lczero::GoParams::searchmoves, lczero::StringUciResponder::SendId(), lczero::StringUciResponder::SendRawResponse(), lczero::EngineControllerBase::SetPosition(), lczero::OptionsParser::SetUciOption(), lczero::EngineControllerBase::Stop(), lczero::StrSplitAtWhitespace(), uci_responder_, UCIGOOPTION, and lczero::EngineControllerBase::Wait().
Referenced by ProcessLine().
ProcessLine()
bool lczero::UciLoop::ProcessLine (const std::string & line)
Definition at line 257 of file uciloop.cc.
References DispatchCommand().
Referenced by lczero::RunEngine().
Member Data Documentation
engine_
EngineControllerBase* lczero::UciLoop::engine_ protected
Definition at line 119 of file uciloop.h.
Referenced by DispatchCommand(), UciLoop(), and ~UciLoop().
options_
OptionsParser* lczero::UciLoop::options_ protected
Definition at line 118 of file uciloop.h.
Referenced by DispatchCommand().
uci_responder_
StringUciResponder* lczero::UciLoop::uci_responder_ protected
Definition at line 117 of file uciloop.h.
Referenced by DispatchCommand(), UciLoop(), and ~UciLoop().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/chess/uciloop.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/chess/uciloop.cc