Leela Chess Zero: lczero::CudnnNetworkComputation< DataType > Class Template Reference
lczero::CudnnNetworkComputation< DataType > Class Template Reference
Public Member Functions
CudnnNetworkComputation (CudnnNetwork< DataType > *network, bool wdl, bool moves_left)
~CudnnNetworkComputation ()
void AddInput (InputPlanes &&input) override
void ComputeBlocking () override
void CaptureGraph (std::unique_lock< std::mutex > &&lock={})
int GetBatchSize () const override
float GetQVal (int sample) const override
float GetDVal (int sample) const override
float GetPVal (int sample, int move_id) const override
float GetMVal (int sample) const override
Public Member Functions inherited from lczero::NetworkComputation
virtual ~NetworkComputation ()=default
Private Attributes
std::unique_ptr< InputsOutputs< DataType > > inputs_outputs_
int batch_size_
bool wdl_
bool moves_left_
CudnnNetwork< DataType > * network_
Detailed Description
template<typename DataType>
class lczero::CudnnNetworkComputation< DataType >
Definition at line 89 of file network_cudnn.cc.
Constructor & Destructor Documentation
CudnnNetworkComputation()
template<typename DataType > lczero::CudnnNetworkComputation< DataType >::CudnnNetworkComputation (CudnnNetwork< DataType > * network, bool wdl, bool moves_left)
Definition at line 1151 of file network_cudnn.cc.
References lczero::CudnnNetworkComputation< DataType >::batch_size_, lczero::CudnnNetworkComputation< DataType >::inputs_outputs_, and lczero::CudnnNetworkComputation< DataType >::network_.
~CudnnNetworkComputation()
template<typename DataType > lczero::CudnnNetworkComputation< DataType >::~CudnnNetworkComputation ()
Definition at line 1159 of file network_cudnn.cc.
References network_.
Member Function Documentation
AddInput()
template<typename DataType > void lczero::CudnnNetworkComputation< DataType >::AddInput (InputPlanes && input) inline override virtual
Implements lczero::NetworkComputation.
Definition at line 95 of file network_cudnn.cc.
References lczero::CudnnNetworkComputation< DataType >::batch_size_, input, lczero::CudnnNetworkComputation< DataType >::inputs_outputs_, lczero::kInputPlanes, and lczero::cudnn_backend::ToType().
Referenced by lczero::CudnnNetwork< DataType >::CudnnNetwork().
CaptureGraph()
template<typename DataType > void lczero::CudnnNetworkComputation< DataType >::CaptureGraph (std::unique_lock< std::mutex > && lock = {})
Definition at line 1164 of file network_cudnn.cc.
References CERR, lczero::cudnn_backend::CudaGraphCapture< DataType >::EndCapture(), and network_.
Referenced by lczero::CudnnNetwork< DataType >::CudnnNetwork().
ComputeBlocking()
template<typename DataType > void lczero::CudnnNetworkComputation< DataType >::ComputeBlocking () override virtual
Implements lczero::NetworkComputation.
Definition at line 1182 of file network_cudnn.cc.
References network_.
Referenced by lczero::CudnnNetwork< DataType >::CudnnNetwork().
GetBatchSize()
template<typename DataType > int lczero::CudnnNetworkComputation< DataType >::GetBatchSize () const inline override virtual
Implements lczero::NetworkComputation.
Definition at line 114 of file network_cudnn.cc.
References lczero::CudnnNetworkComputation< DataType >::batch_size_.
GetDVal()
template<typename DataType > float lczero::CudnnNetworkComputation< DataType >::GetDVal (int sample) const inline override virtual
Implements lczero::NetworkComputation.
Definition at line 127 of file network_cudnn.cc.
References lczero::CudnnNetworkComputation< DataType >::inputs_outputs_, and lczero::CudnnNetworkComputation< DataType >::wdl_.
GetMVal()
template<typename DataType > float lczero::CudnnNetworkComputation< DataType >::GetMVal (int sample) const inline override virtual
Implements lczero::NetworkComputation.
Definition at line 143 of file network_cudnn.cc.
References lczero::cudnn_backend::FromType(), lczero::CudnnNetworkComputation< DataType >::inputs_outputs_, and lczero::CudnnNetworkComputation< DataType >::moves_left_.
GetPVal()
template<typename DataType > float lczero::CudnnNetworkComputation< DataType >::GetPVal (int sample, int move_id) const inline override virtual
Implements lczero::NetworkComputation.
Definition at line 138 of file network_cudnn.cc.
References lczero::cudnn_backend::FromType(), lczero::CudnnNetworkComputation< DataType >::inputs_outputs_, and lczero::cudnn_backend::kNumOutputPolicy.
GetQVal()
template<typename DataType > float lczero::CudnnNetworkComputation< DataType >::GetQVal (int sample) const inline override virtual
Implements lczero::NetworkComputation.
Definition at line 116 of file network_cudnn.cc.
References lczero::cudnn_backend::FromType(), lczero::CudnnNetworkComputation< DataType >::inputs_outputs_, and lczero::CudnnNetworkComputation< DataType >::wdl_.
Member Data Documentation
batch_size_
template<typename DataType > int lczero::CudnnNetworkComputation< DataType >::batch_size_ private
Definition at line 153 of file network_cudnn.cc.
Referenced by lczero::CudnnNetworkComputation< DataType >::AddInput(), lczero::CudnnNetworkComputation< DataType >::CudnnNetworkComputation(), and lczero::CudnnNetworkComputation< DataType >::GetBatchSize().
inputs_outputs_
template<typename DataType > std::unique_ptr<InputsOutputs<DataType> > lczero::CudnnNetworkComputation< DataType >::inputs_outputs_ private
Definition at line 152 of file network_cudnn.cc.
Referenced by lczero::CudnnNetworkComputation< DataType >::AddInput(), lczero::CudnnNetworkComputation< DataType >::CudnnNetworkComputation(), lczero::CudnnNetworkComputation< DataType >::GetDVal(), lczero::CudnnNetworkComputation< DataType >::GetMVal(), lczero::CudnnNetworkComputation< DataType >::GetPVal(), and lczero::CudnnNetworkComputation< DataType >::GetQVal().
moves_left_
template<typename DataType > bool lczero::CudnnNetworkComputation< DataType >::moves_left_ private
Definition at line 155 of file network_cudnn.cc.
Referenced by lczero::CudnnNetworkComputation< DataType >::GetMVal().
network_
template<typename DataType > CudnnNetwork<DataType>* lczero::CudnnNetworkComputation< DataType >::network_ private
Definition at line 157 of file network_cudnn.cc.
Referenced by lczero::CudnnNetworkComputation< DataType >::CudnnNetworkComputation().
wdl_
template<typename DataType > bool lczero::CudnnNetworkComputation< DataType >::wdl_ private
Definition at line 154 of file network_cudnn.cc.
Referenced by lczero::CudnnNetworkComputation< DataType >::GetDVal(), and lczero::CudnnNetworkComputation< DataType >::GetQVal().
The documentation for this class was generated from the following file:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/cuda/network_cudnn.cc