Leela Chess Zero: lczero::Engine Class Reference
lczero::Engine Class Reference
#include <engine.h>
Classes
class UciPonderForwarder
Public Member Functions
Engine (const SearchFactory &, const OptionsDict &)
~Engine () override
void EnsureReady () override
void NewGame () override
void SetPosition (const std::string &fen, const std::vector< std::string > &moves) override
void Go (const GoParams &params) override
void PonderHit () override
void Wait () override
void Stop () override
void RegisterUciResponder (UciResponder *) override
void UnregisterUciResponder (UciResponder *) override
Public Member Functions inherited from lczero::EngineControllerBase
virtual ~EngineControllerBase ()=default
Static Public Member Functions
static void PopulateOptions (OptionsParser *)
Private Member Functions
void UpdateBackendConfig ()
void EnsureSearchStopped ()
void EnsureSyzygyTablebasesLoaded ()
void InitializeSearchPosition (bool for_ponder)
Private Attributes
std::unique_ptr< UciPonderForwarder > uci_forwarder_
const OptionsDict & options_
std::unique_ptr< SearchBase > search_
std::string backend_name_
std::unique_ptr< CachingBackend > backend_
std::string previous_tb_paths_
std::unique_ptr< SyzygyTablebase > syzygy_tb_
bool ponder_enabled_ = false
bool strict_uci_timing_ = true
bool isready_seen_ = true
std::optional< GameState > last_position_ = std::nullopt
std::optional< GoParams > last_go_params_ = std::nullopt
Detailed Description
Definition at line 40 of file engine.h.
Constructor & Destructor Documentation
Engine()
lczero::Engine::Engine (const SearchFactory & factory, const OptionsDict & opts)
Definition at line 147 of file engine.cc.
References EnsureSyzygyTablebasesLoaded(), lczero::OptionsDict::Get(), options_, and UpdateBackendConfig().
~Engine()
lczero::Engine::~Engine () override
Definition at line 157 of file engine.cc.
References EnsureSearchStopped().
Member Function Documentation
EnsureReady()
void lczero::Engine::EnsureReady () override virtual
Implements lczero::EngineControllerBase.
Definition at line 252 of file engine.cc.
References isready_seen_.
EnsureSearchStopped()
void lczero::Engine::EnsureSearchStopped () private
Definition at line 159 of file engine.cc.
References search_.
Referenced by PonderHit(), SetPosition(), and ~Engine().
EnsureSyzygyTablebasesLoaded()
void lczero::Engine::EnsureSyzygyTablebasesLoaded () private
Definition at line 180 of file engine.cc.
References CERR, lczero::OptionsDict::Get(), LOGFILE, options_, previous_tb_paths_, search_, and syzygy_tb_.
Referenced by Engine(), and SetPosition().
Go()
void lczero::Engine::Go (const GoParams & params) override virtual
Implements lczero::EngineControllerBase.
Definition at line 237 of file engine.cc.
References lczero::GoParams::btime, InitializeSearchPosition(), isready_seen_, last_go_params_, last_position_, NewGame(), lczero::GoParams::ponder, ponder_enabled_, search_, strict_uci_timing_, and lczero::GoParams::wtime.
InitializeSearchPosition()
void lczero::Engine::InitializeSearchPosition (bool for_ponder) private
Definition at line 202 of file engine.cc.
References last_position_, LOGFILE, lczero::GameState::moves, and search_.
Referenced by Go(), PonderHit(), and SetPosition().
NewGame()
void lczero::Engine::NewGame () override virtual
Implements lczero::EngineControllerBase.
Definition at line 231 of file engine.cc.
References backend_, lczero::ChessBoard::kStartposFen, search_, and SetPosition().
Referenced by Go().
PonderHit()
void lczero::Engine::PonderHit () override virtual
Implements lczero::EngineControllerBase.
Definition at line 258 of file engine.cc.
References EnsureSearchStopped(), InitializeSearchPosition(), last_go_params_, and search_.
PopulateOptions()
void lczero::Engine::PopulateOptions (OptionsParser * options) static
Definition at line 67 of file engine.cc.
References lczero::OptionsParser::Add().
Referenced by lczero::RunEngine().
RegisterUciResponder()
void lczero::Engine::RegisterUciResponder (UciResponder * responder) override virtual
Implements lczero::EngineControllerBase.
Definition at line 269 of file engine.cc.
References uci_forwarder_.
SetPosition()
void lczero::Engine::SetPosition (const std::string & fen, const std::vector< std::string > & moves) override virtual
Implements lczero::EngineControllerBase.
Definition at line 218 of file engine.cc.
References EnsureSearchStopped(), EnsureSyzygyTablebasesLoaded(), fen, lczero::OptionsDict::Get(), InitializeSearchPosition(), isready_seen_, last_position_, moves, options_, ponder_enabled_, search_, strict_uci_timing_, and UpdateBackendConfig().
Referenced by NewGame().
Stop()
void lczero::Engine::Stop () override virtual
Implements lczero::EngineControllerBase.
Definition at line 256 of file engine.cc.
References search_.
UnregisterUciResponder()
void lczero::Engine::UnregisterUciResponder (UciResponder * responder) override virtual
Implements lczero::EngineControllerBase.
Definition at line 273 of file engine.cc.
References uci_forwarder_.
UpdateBackendConfig()
void lczero::Engine::UpdateBackendConfig () private
Definition at line 164 of file engine.cc.
References backend_, backend_name_, lczero::CreateMemCache(), lczero::BackendManager::Get(), lczero::OptionsDict::Get(), lczero::SharedBackendParams::kBackendId, lczero::SharedBackendParams::kNNCacheSizeId, LOGFILE, lczero::Backend::NEED_RESTART, options_, and search_.
Referenced by Engine(), and SetPosition().
Wait()
void lczero::Engine::Wait () override virtual
Implements lczero::EngineControllerBase.
Definition at line 254 of file engine.cc.
References search_.
Member Data Documentation
backend_
std::unique_ptr<CachingBackend> lczero::Engine::backend_ private
Definition at line 70 of file engine.h.
Referenced by NewGame(), and UpdateBackendConfig().
backend_name_
std::string lczero::Engine::backend_name_ private
Definition at line 69 of file engine.h.
Referenced by UpdateBackendConfig().
isready_seen_
bool lczero::Engine::isready_seen_ = true private
Definition at line 80 of file engine.h.
Referenced by EnsureReady(), Go(), and SetPosition().
last_go_params_
std::optional<GoParams> lczero::Engine::last_go_params_ = std::nullopt private
Definition at line 87 of file engine.h.
Referenced by Go(), lczero::Engine::UciPonderForwarder::OutputThinkingInfo(), and PonderHit().
last_position_
std::optional<GameState> lczero::Engine::last_position_ = std::nullopt private
Definition at line 85 of file engine.h.
Referenced by Go(), InitializeSearchPosition(), lczero::Engine::UciPonderForwarder::OutputThinkingInfo(), and SetPosition().
options_
const OptionsDict& lczero::Engine::options_ private
Definition at line 67 of file engine.h.
Referenced by Engine(), EnsureSyzygyTablebasesLoaded(), SetPosition(), and UpdateBackendConfig().
ponder_enabled_
bool lczero::Engine::ponder_enabled_ = false private
Definition at line 78 of file engine.h.
Referenced by Go(), and SetPosition().
previous_tb_paths_
std::string lczero::Engine::previous_tb_paths_ private
Definition at line 73 of file engine.h.
Referenced by EnsureSyzygyTablebasesLoaded().
search_
std::unique_ptr<SearchBase> lczero::Engine::search_ private
Definition at line 68 of file engine.h.
Referenced by EnsureSearchStopped(), EnsureSyzygyTablebasesLoaded(), Go(), InitializeSearchPosition(), NewGame(), PonderHit(), SetPosition(), Stop(), UpdateBackendConfig(), and Wait().
strict_uci_timing_
bool lczero::Engine::strict_uci_timing_ = true private
Definition at line 79 of file engine.h.
Referenced by Go(), and SetPosition().
syzygy_tb_
std::unique_ptr<SyzygyTablebase> lczero::Engine::syzygy_tb_ private
Definition at line 74 of file engine.h.
Referenced by EnsureSyzygyTablebasesLoaded().
uci_forwarder_
std::unique_ptr<UciPonderForwarder> lczero::Engine::uci_forwarder_ private
Definition at line 66 of file engine.h.
Referenced by RegisterUciResponder(), and UnregisterUciResponder().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/engine.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/engine.cc