Leela Chess Zero: lczero::StringUciResponder Class Reference
lczero::StringUciResponder Class Reference abstract
#include <uciloop.h>
Public Member Functions
void PopulateParams (OptionsParser *options)
void SendId ()
void OutputBestMove (BestMoveInfo *info) override
void OutputThinkingInfo (std::vector< ThinkingInfo > *infos) override
void SendRawResponse (const std::string &response)
virtual void SendRawResponses (const std::vector< std::string > &responses)=0
Public Member Functions inherited from lczero::UciResponder
virtual ~UciResponder ()=default
Private Member Functions
bool IsChess960 () const
Private Attributes
const OptionsDict * options_ = nullptr
Detailed Description
Definition at line 57 of file uciloop.h.
Member Function Documentation
IsChess960()
bool lczero::StringUciResponder::IsChess960 () const private
Definition at line 272 of file uciloop.cc.
References lczero::OptionsDict::Get(), and options_.
Referenced by OutputBestMove(), and OutputThinkingInfo().
OutputBestMove()
void lczero::StringUciResponder::OutputBestMove (BestMoveInfo * info) override virtual
Implements lczero::UciResponder.
Definition at line 285 of file uciloop.cc.
References lczero::BestMoveInfo::bestmove, lczero::BestMoveInfo::game_id, lczero::BestMoveInfo::is_black, lczero::Move::is_null(), IsChess960(), lczero::BestMoveInfo::player, lczero::BestMoveInfo::ponder, SendRawResponse(), and lczero::Move::ToString().
OutputThinkingInfo()
void lczero::StringUciResponder::OutputThinkingInfo (std::vector< ThinkingInfo > * infos) override virtual
Implements lczero::UciResponder.
Definition at line 296 of file uciloop.cc.
References lczero::OptionsDict::Get(), IsChess960(), options_, and SendRawResponses().
PopulateParams()
void lczero::StringUciResponder::PopulateParams (OptionsParser * options)
Definition at line 264 of file uciloop.cc.
References lczero::OptionsParser::Add(), lczero::OptionsParser::GetOptionsDict(), and options_.
Referenced by lczero::RunEngine(), and lczero::SelfPlayLoop::SelfPlayLoop().
SendId()
void lczero::StringUciResponder::SendId ()
Definition at line 280 of file uciloop.cc.
References GetVersionStr(), and SendRawResponse().
Referenced by lczero::UciLoop::DispatchCommand(), and lczero::SelfPlayLoop::Run().
SendRawResponse()
void lczero::StringUciResponder::SendRawResponse (const std::string & response)
Definition at line 276 of file uciloop.cc.
References SendRawResponses().
Referenced by lczero::UciLoop::DispatchCommand(), OutputBestMove(), lczero::RunEngine(), SendId(), and lczero::SelfPlayLoop::SendTournament().
SendRawResponses()
virtual void lczero::StringUciResponder::SendRawResponses (const std::vector< std::string > & responses) pure virtual
Implemented in lczero::StdoutUciResponder.
Referenced by OutputThinkingInfo(), lczero::SelfPlayLoop::SendGameInfo(), and SendRawResponse().
Member Data Documentation
options_
const OptionsDict* lczero::StringUciResponder::options_ = nullptr private
Definition at line 73 of file uciloop.h.
Referenced by IsChess960(), OutputThinkingInfo(), and PopulateParams().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/chess/uciloop.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/chess/uciloop.cc