Leela Chess Zero: lczero::cudnn_backend::ResidualBlock< DataType > Class Template Reference
lczero::cudnn_backend::ResidualBlock< DataType > Class Template Reference
#include <layers.h>
Public Member Functions
ResidualBlock (BaseLayer< DataType > *ip, int C, bool se, int se_k, bool use_gemm_ex, bool first, bool last, ActivationFunction activation, int shared_mem_size)
~ResidualBlock ()
void LoadWeights0 (float *pfilter, float *pBias, void *scratch)
void LoadWeights1 (float *pfilter, float *pBias, void *scratch)
void LoadSEWeights (float *w1, float *b1, float *w2, float *b2, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType ***=nullptr) override
Public Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, bool use_gemm_ex)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
const bool has_se_
const int se_k_
const int c_input_
const bool first_block_
const bool last_block_
const int shared_mem_size_
const ActivationFunction act_
DataType * biases0_ = nullptr
DataType * biases1_ = nullptr
DataType * transformed_weights0_ = nullptr
DataType * transformed_weights1_ = nullptr
DataType * w1_
DataType * w2_
DataType * b1_
DataType * b2_
Additional Inherited Members
Protected Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const half *A, const half *B, half *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
Protected Attributes inherited from lczero::cudnn_backend::BaseLayer< DataType >
BaseLayer * input_
int C
int H
int W
bool nhwc_
const bool use_gemm_ex_
Detailed Description
template<typename DataType>
class lczero::cudnn_backend::ResidualBlock< DataType >
Definition at line 293 of file layers.h.
Constructor & Destructor Documentation
ResidualBlock()
template<typename DataType > lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock (BaseLayer< DataType > * ip, int C, bool se, int se_k, bool use_gemm_ex, bool first, bool last, ActivationFunction activation, int shared_mem_size)
Definition at line 1134 of file layers.cc.
References lczero::cudnn_backend::ResidualBlock< DataType >::act_, lczero::ACTIVATION_MISH, lczero::ACTIVATION_RELU, lczero::cudnn_backend::ResidualBlock< DataType >::b1_, lczero::cudnn_backend::ResidualBlock< DataType >::b2_, lczero::cudnn_backend::ResidualBlock< DataType >::biases0_, lczero::cudnn_backend::ResidualBlock< DataType >::biases1_, lczero::cudnn_backend::BaseLayer< DataType >::C, lczero::cudnn_backend::ResidualBlock< DataType >::has_se_, ReportCUDAErrors, lczero::cudnn_backend::ResidualBlock< DataType >::se_k_, lczero::cudnn_backend::ResidualBlock< DataType >::transformed_weights0_, lczero::cudnn_backend::ResidualBlock< DataType >::transformed_weights1_, lczero::cudnn_backend::ResidualBlock< DataType >::w1_, and lczero::cudnn_backend::ResidualBlock< DataType >::w2_.
~ResidualBlock()
template<typename DataType > lczero::cudnn_backend::ResidualBlock< DataType >::~ResidualBlock ()
Definition at line 1392 of file layers.cc.
References ReportCUDAErrors.
Member Function Documentation
Eval()
template<typename DataType > void lczero::cudnn_backend::ResidualBlock< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType *** = nullptr) override virtual
Implements lczero::cudnn_backend::BaseLayer< DataType >.
Definition at line 1265 of file layers.cc.
References lczero::ACTIVATION_MISH, lczero::ACTIVATION_RELU, C, lczero::cudnn_backend::BaseLayer< DataType >::cublasRowMajorMatrixMul(), input, lczero::cudnn_backend::kMaxResBlockFusingChannels, lczero::cudnn_backend::kMaxResBlockFusingSeFp16AmpereSmem, lczero::cudnn_backend::kMaxResBlockFusingSeKFp16Ampere, output, and lczero::cudnn_backend::OutputTransform().
LoadSEWeights()
template<typename DataType > void lczero::cudnn_backend::ResidualBlock< DataType >::LoadSEWeights (float * w1, float * b1, float * w2, float * b2, void * scratch)
Definition at line 1233 of file layers.cc.
References C, lczero::cudnn_backend::copyTypeConverted(), lczero::cudnn_backend::CpuTranspose(), and ReportCUDAErrors.
LoadWeights0()
template<typename DataType > void lczero::cudnn_backend::ResidualBlock< DataType >::LoadWeights0 (float * pfilter, float * pBias, void * scratch)
Definition at line 1180 of file layers.cc.
References C, lczero::cudnn_backend::copyTypeConverted(), lczero::cudnn_backend::FilterTransform(), and ReportCUDAErrors.
LoadWeights1()
template<typename DataType > void lczero::cudnn_backend::ResidualBlock< DataType >::LoadWeights1 (float * pfilter, float * pBias, void * scratch)
Definition at line 1207 of file layers.cc.
References C, lczero::cudnn_backend::copyTypeConverted(), lczero::cudnn_backend::FilterTransform(), and ReportCUDAErrors.
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::cudnn_backend::ResidualBlock< DataType >::act_ private
Definition at line 323 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
b1_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::b1_ private
Definition at line 333 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
b2_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::b2_ private
Definition at line 334 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
biases0_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::biases0_ = nullptr private
Definition at line 325 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
biases1_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::biases1_ = nullptr private
Definition at line 326 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
c_input_
template<typename DataType > const int lczero::cudnn_backend::ResidualBlock< DataType >::c_input_ private
Definition at line 319 of file layers.h.
first_block_
template<typename DataType > const bool lczero::cudnn_backend::ResidualBlock< DataType >::first_block_ private
Definition at line 320 of file layers.h.
has_se_
template<typename DataType > const bool lczero::cudnn_backend::ResidualBlock< DataType >::has_se_ private
Definition at line 317 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
last_block_
template<typename DataType > const bool lczero::cudnn_backend::ResidualBlock< DataType >::last_block_ private
Definition at line 321 of file layers.h.
se_k_
template<typename DataType > const int lczero::cudnn_backend::ResidualBlock< DataType >::se_k_ private
Definition at line 318 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
shared_mem_size_
template<typename DataType > const int lczero::cudnn_backend::ResidualBlock< DataType >::shared_mem_size_ private
Definition at line 322 of file layers.h.
transformed_weights0_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::transformed_weights0_ = nullptr private
Definition at line 327 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
transformed_weights1_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::transformed_weights1_ = nullptr private
Definition at line 328 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
w1_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::w1_ private
Definition at line 331 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
w2_
template<typename DataType > DataType* lczero::cudnn_backend::ResidualBlock< DataType >::w2_ private
Definition at line 332 of file layers.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::ResidualBlock().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/cuda/layers.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/cuda/layers.cc