Leela Chess Zero: lczero::OnnxConst Class Reference
lczero::OnnxConst Class Reference abstract
#include <builder.h>
Public Member Functions
virtual ~OnnxConst ()=default
virtual pblczero::TensorProto::DataType GetDataType () const =0
virtual std::vector< int > GetDimensions () const =0
virtual std::string GetRawData () const =0
Detailed Description
Definition at line 37 of file builder.h.
Constructor & Destructor Documentation
~OnnxConst()
virtual lczero::OnnxConst::~OnnxConst () virtual default
Member Function Documentation
GetDataType()
virtual pblczero::TensorProto::DataType lczero::OnnxConst::GetDataType () const pure virtual
Implemented in lczero::FloatOnnxWeightsAdapter, lczero::Float16OnnxWeightsAdapter, lczero::BFloat16OnnxWeightsAdapter, lczero::Float8E5M2OnnxWeightsAdapter, lczero::Int32OnnxConst, lczero::Int64OnnxConst, lczero::FloatOnnxConst, lczero::Float16OnnxConst, lczero::BFloat16OnnxConst, and lczero::Float8E5M2OnnxConst.
Referenced by lczero::OnnxBuilder::AddInitializer().
GetDimensions()
virtual std::vector< int > lczero::OnnxConst::GetDimensions () const pure virtual
Implemented in lczero::FloatOnnxWeightsAdapter, lczero::GenericOnnxConst< T >, lczero::GenericOnnxConst< float >, lczero::GenericOnnxConst< int32_t >, lczero::GenericOnnxConst< int64_t >, lczero::GenericOnnxConst< uint16_t >, and lczero::GenericOnnxConst< uint8_t >.
Referenced by lczero::OnnxBuilder::AddInitializer(), and lczero::OnnxBuilder::Conv().
GetRawData()
virtual std::string lczero::OnnxConst::GetRawData () const pure virtual
Implemented in lczero::FloatOnnxWeightsAdapter, lczero::Float16OnnxWeightsAdapter, lczero::BFloat16OnnxWeightsAdapter, lczero::Float8E5M2OnnxWeightsAdapter, lczero::GenericOnnxConst< T >, lczero::GenericOnnxConst< float >, lczero::GenericOnnxConst< int32_t >, lczero::GenericOnnxConst< int64_t >, lczero::GenericOnnxConst< uint16_t >, and lczero::GenericOnnxConst< uint8_t >.
Referenced by lczero::OnnxBuilder::AddInitializer().
The documentation for this class was generated from the following file:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/onnx/builder.h