Leela Chess Zero: OpenCL_Network Class Reference
OpenCL_Network Class Reference
#include <OpenCL.h>
Public Member Functions
OpenCL_Network (OpenCL &opencl)
std::unique_ptr< OpenCLBuffers > acquire_buffers () const
void release_buffers (std::unique_ptr< OpenCLBuffers >) const
OpenCL & getOpenCL () const
size_t getMaxMatchSize () const
void setMaxMatchSize (size_t new_value)
void push_input_convolution (unsigned int filter_size, unsigned int channels, unsigned int outputs, const std::vector< float > &weights, const std::vector< float > &biases)
void push_residual (unsigned int filter_size, unsigned int channels, unsigned int outputs, const std::vector< float > &weights_1, const std::vector< float > &biases_1, const std::vector< float > &weights_2, const std::vector< float > &biases_2)
void push_se (unsigned int channels, unsigned int se_fc_outputs, const std::vector< float > &weights_1, const std::vector< float > &biases_1, const std::vector< float > &weights_2, const std::vector< float > &biases_2)
void push_policy (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > &weights, const std::vector< float > &biases, const std::vector< float > &fc_w, const std::vector< float > &fc_b)
void push_conv_policy (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > &weights_1, const std::vector< float > &biases_1, const std::vector< float > &weights_2, const std::vector< float > &biases_2, const std::vector< short > &indices)
void push_value (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > &weights, const std::vector< float > &biases, const std::vector< float > &fc_w, const std::vector< float > &fc_b)
void push_moves_left (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > &weights, const std::vector< float > &biases, const std::vector< float > &fc_w, const std::vector< float > &fc_b)
size_t get_layer_count () const
Private Member Functions
void push_weights (size_t layer, const std::vector< float > &weights)
void add_weights (size_t layer, size_t size, const float *weights)
void push_weights_short (size_t layer, const std::vector< short > &weights)
void add_weights_short (size_t layer, size_t size, const short *weights)
Private Attributes
OpenCL & m_opencl
size_t m_max_batch_size
std::vector< Layer > m_layers
std::mutex m_pool_mutex
std::vector< std::unique_ptr< OpenCLBuffers > > m_buffers_pool
Friends
class OpenCLBuffers
Detailed Description
Definition at line 82 of file OpenCL.h.
Constructor & Destructor Documentation
OpenCL_Network()
OpenCL_Network::OpenCL_Network (OpenCL & opencl) inline
Definition at line 86 of file OpenCL.h.
Member Function Documentation
acquire_buffers()
std::unique_ptr< OpenCLBuffers > OpenCL_Network::acquire_buffers () const
Definition at line 387 of file OpenCL.cc.
References m_buffers_pool, m_pool_mutex, and result.
add_weights()
void OpenCL_Network::add_weights (size_t layer, size_t size, const float * weights) private
Definition at line 94 of file OpenCL.cc.
References OpenCL::m_context, m_layers, and m_opencl.
Referenced by push_weights().
add_weights_short()
void OpenCL_Network::add_weights_short (size_t layer, size_t size, const short * weights) private
Definition at line 111 of file OpenCL.cc.
References OpenCL::m_context, m_layers, and m_opencl.
Referenced by push_weights_short().
get_layer_count()
size_t OpenCL_Network::get_layer_count () const inline
Definition at line 216 of file OpenCL.h.
References m_layers.
Referenced by push_conv_policy(), push_input_convolution(), push_moves_left(), push_policy(), push_residual(), push_se(), and push_value().
getMaxMatchSize()
size_t OpenCL_Network::getMaxMatchSize () const inline
Definition at line 93 of file OpenCL.h.
References m_max_batch_size.
Referenced by OpenCLBuffers::OpenCLBuffers().
getOpenCL()
OpenCL & OpenCL_Network::getOpenCL () const inline
Definition at line 91 of file OpenCL.h.
References m_opencl.
push_conv_policy()
void OpenCL_Network::push_conv_policy (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > & weights_1, const std::vector< float > & biases_1, const std::vector< float > & weights_2, const std::vector< float > & biases_2, const std::vector< short > & indices) inline
Definition at line 160 of file OpenCL.h.
References get_layer_count(), m_layers, push_weights(), and push_weights_short().
push_input_convolution()
void OpenCL_Network::push_input_convolution (unsigned int filter_size, unsigned int channels, unsigned int outputs, const std::vector< float > & weights, const std::vector< float > & biases) inline
Definition at line 97 of file OpenCL.h.
References get_layer_count(), m_layers, and push_weights().
push_moves_left()
void OpenCL_Network::push_moves_left (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > & weights, const std::vector< float > & biases, const std::vector< float > & fc_w, const std::vector< float > & fc_b) inline
Definition at line 198 of file OpenCL.h.
References get_layer_count(), m_layers, and push_weights().
push_policy()
void OpenCL_Network::push_policy (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > & weights, const std::vector< float > & biases, const std::vector< float > & fc_w, const std::vector< float > & fc_b) inline
Definition at line 142 of file OpenCL.h.
References get_layer_count(), m_layers, and push_weights().
push_residual()
void OpenCL_Network::push_residual (unsigned int filter_size, unsigned int channels, unsigned int outputs, const std::vector< float > & weights_1, const std::vector< float > & biases_1, const std::vector< float > & weights_2, const std::vector< float > & biases_2) inline
Definition at line 110 of file OpenCL.h.
References get_layer_count(), m_layers, and push_weights().
push_se()
void OpenCL_Network::push_se (unsigned int channels, unsigned int se_fc_outputs, const std::vector< float > & weights_1, const std::vector< float > & biases_1, const std::vector< float > & weights_2, const std::vector< float > & biases_2) inline
Definition at line 126 of file OpenCL.h.
References get_layer_count(), m_layers, and push_weights().
push_value()
void OpenCL_Network::push_value (unsigned int channels, unsigned int outputs, unsigned int ip_in, unsigned int ip_out, const std::vector< float > & weights, const std::vector< float > & biases, const std::vector< float > & fc_w, const std::vector< float > & fc_b) inline
Definition at line 180 of file OpenCL.h.
References get_layer_count(), m_layers, and push_weights().
push_weights()
void OpenCL_Network::push_weights (size_t layer, const std::vector< float > & weights) inline private
Definition at line 219 of file OpenCL.h.
References add_weights().
Referenced by push_conv_policy(), push_input_convolution(), push_moves_left(), push_policy(), push_residual(), push_se(), and push_value().
push_weights_short()
void OpenCL_Network::push_weights_short (size_t layer, const std::vector< short > & weights) inline private
Definition at line 224 of file OpenCL.h.
References add_weights_short().
Referenced by push_conv_policy().
release_buffers()
void OpenCL_Network::release_buffers (std::unique_ptr< OpenCLBuffers > buffers) const
Definition at line 395 of file OpenCL.cc.
References m_buffers_pool, and m_pool_mutex.
setMaxMatchSize()
void OpenCL_Network::setMaxMatchSize (size_t new_value) inline
Definition at line 95 of file OpenCL.h.
References m_max_batch_size.
Friends And Related Symbol Documentation
OpenCLBuffers
friend class OpenCLBuffers friend
Definition at line 83 of file OpenCL.h.
Member Data Documentation
m_buffers_pool
std::vector<std::unique_ptr<OpenCLBuffers> > OpenCL_Network::m_buffers_pool mutable private
Definition at line 235 of file OpenCL.h.
Referenced by acquire_buffers(), and release_buffers().
m_layers
std::vector<Layer> OpenCL_Network::m_layers private
Definition at line 232 of file OpenCL.h.
Referenced by add_weights(), add_weights_short(), OpenCLBuffers::forward(), get_layer_count(), OpenCLBuffers::OpenCLBuffers(), push_conv_policy(), push_input_convolution(), push_moves_left(), push_policy(), push_residual(), push_se(), and push_value().
m_max_batch_size
size_t OpenCL_Network::m_max_batch_size private
Definition at line 230 of file OpenCL.h.
Referenced by getMaxMatchSize(), and setMaxMatchSize().
m_opencl
OpenCL& OpenCL_Network::m_opencl private
Definition at line 229 of file OpenCL.h.
Referenced by add_weights(), add_weights_short(), and getOpenCL().
m_pool_mutex
std::mutex OpenCL_Network::m_pool_mutex mutable private
Definition at line 234 of file OpenCL.h.
Referenced by acquire_buffers(), and release_buffers().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/opencl/OpenCL.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/opencl/OpenCL.cc