Leela Chess Zero: lczero::PjrtClient Class Reference
lczero::PjrtClient Class Reference
#include <pjrt.h>
Public Member Functions
PjrtClient (const PJRT_Api *api, PJRT_Client *client)
~PjrtClient ()
std::unique_ptr< PjrtExecutable > CompileHlo (std::string_view hlo, std::string_view config)
std::vector< std::unique_ptr< PjrtDevice > > GetDevices ()
std::unique_ptr< PjrtHostToDeviceTransfer > HostToDevice (std::string_view buffer, PjrtType type, const std::vector< int64_t > &dims, const PjrtDevice *device)
Private Attributes
PJRT_Client * client_
Additional Inherited Members
Protected Member Functions inherited from lczero::PjrtCommon
PjrtCommon (const PJRT_Api *api)
virtual ~PjrtCommon ()=default
std::string GetErrorMessage (PJRT_Error *error) const
void DestroyErrorMessage (PJRT_Error *error) const
void CheckError (PJRT_Error *error) const
Protected Attributes inherited from lczero::PjrtCommon
const PJRT_Api * api_
Detailed Description
Definition at line 226 of file pjrt.h.
Constructor & Destructor Documentation
PjrtClient()
lczero::PjrtClient::PjrtClient (const PJRT_Api * api, PJRT_Client * client)
Definition at line 203 of file pjrt.cc.
~PjrtClient()
lczero::PjrtClient::~PjrtClient ()
Definition at line 206 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), and client_.
Member Function Documentation
CompileHlo()
std::unique_ptr< PjrtExecutable > lczero::PjrtClient::CompileHlo (std::string_view hlo, std::string_view config)
Definition at line 212 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), and client_.
GetDevices()
std::vector< std::unique_ptr< PjrtDevice > > lczero::PjrtClient::GetDevices ()
Definition at line 230 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), client_, and result.
HostToDevice()
std::unique_ptr< PjrtHostToDeviceTransfer > lczero::PjrtClient::HostToDevice (std::string_view buffer, PjrtType type, const std::vector< int64_t > & dims, const PjrtDevice * device)
Definition at line 324 of file pjrt.cc.
References lczero::PjrtCommon::api_, lczero::PjrtCommon::CheckError(), client_, lczero::PjrtDevice::device_, and type.
Member Data Documentation
client_
PJRT_Client* lczero::PjrtClient::client_ private
Definition at line 238 of file pjrt.h.
Referenced by CompileHlo(), GetDevices(), HostToDevice(), and ~PjrtClient().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/xla/pjrt.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/xla/pjrt.cc