Leela Chess Zero: lczero::sycldnn_backend::Conv1Layer< DataType > Class Template Reference
lczero::sycldnn_backend::Conv1Layer< DataType > Class Template Reference
#include <layers.h>
Public Member Functions
Conv1Layer (BaseLayer< DataType > *ip, int C, int H, int W, int Cin, ActivationFunction activation, bool bias, sycl::queue &sycl_queue)
~Conv1Layer ()
void LoadWeights (float *pfilter, float *pBias, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, sycl::queue &sycl_queue, DataType ***=nullptr) override
Public Member Functions inherited from lczero::sycldnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
sycl::queue GetSycl_Queue ()
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip, sycl::queue &sycl_queue)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, sycl::queue &sycl_queue)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Member Functions
void cublasSpecialMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasSpecialMatrixMul (const sycl::half *A, const sycl::half *B, sycl::half *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasSpecialMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
Private Attributes
const int c_input_
const ActivationFunction act_
const bool use_bias_
DataType * biases_ = nullptr
DataType * weights_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from lczero::sycldnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasRowMajorMatrixMul (const sycl::half *A, const sycl::half *B, sycl::half *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
Protected Attributes inherited from lczero::sycldnn_backend::BaseLayer< DataType >
BaseLayer * input_
sycl::queue & sycl_queue_
int C
int H
int W
bool nhwc_
Detailed Description
template<typename DataType>
class lczero::sycldnn_backend::Conv1Layer< DataType >
Definition at line 208 of file layers.h.
Constructor & Destructor Documentation
Conv1Layer()
template<typename DataType > lczero::sycldnn_backend::Conv1Layer< DataType >::Conv1Layer (BaseLayer< DataType > * ip, int C, int H, int W, int Cin, ActivationFunction activation, bool bias, sycl::queue & sycl_queue)
Definition at line 1100 of file layers.cc.dp.cpp.
References lczero::sycldnn_backend::Conv1Layer< DataType >::biases_, lczero::sycldnn_backend::BaseLayer< DataType >::C, lczero::sycldnn_backend::Conv1Layer< DataType >::c_input_, lczero::sycldnn_backend::BaseLayer< DataType >::sycl_queue_, lczero::sycldnn_backend::Conv1Layer< DataType >::use_bias_, and lczero::sycldnn_backend::Conv1Layer< DataType >::weights_.
~Conv1Layer()
template<typename DataType > lczero::sycldnn_backend::Conv1Layer< DataType >::~Conv1Layer ()
Definition at line 1286 of file layers.cc.dp.cpp.
References weights_.
Member Function Documentation
cublasSpecialMatrixMul() [1/3]
template<typename DataType > void lczero::sycldnn_backend::Conv1Layer< DataType >::cublasSpecialMatrixMul (const DataType * A, const DataType * B, DataType * Out, int M, int N, int K, int batchSize, sycl::queue & sycl_queue) private
cublasSpecialMatrixMul() [2/3]
void lczero::sycldnn_backend::Conv1Layer< float >::cublasSpecialMatrixMul (const float * A, const float * B, float * Out, int M, int N, int K, int batchSize, sycl::queue & sycl_queue) private
Definition at line 1203 of file layers.cc.dp.cpp.
References ReportCUBLASErrors, and transpose_type_notranspose.
cublasSpecialMatrixMul() [3/3]
void lczero::sycldnn_backend::Conv1Layer< sycl::half >::cublasSpecialMatrixMul (const sycl::half * A, const sycl::half * B, sycl::half * Out, int M, int N, int K, int batchSize, sycl::queue & sycl_queue) private
Definition at line 1136 of file layers.cc.dp.cpp.
References ReportCUBLASErrors, and transpose_type_notranspose.
Eval()
template<typename DataType > void lczero::sycldnn_backend::Conv1Layer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, sycl::queue & sycl_queue, DataType *** = nullptr) override virtual
Implements lczero::sycldnn_backend::BaseLayer< DataType >.
Definition at line 1266 of file layers.cc.dp.cpp.
References lczero::ACTIVATION_NONE, lczero::sycldnn_backend::addBias_NCHW(), lczero::sycldnn_backend::addVectors(), C, input, output, and weights_.
LoadWeights()
template<typename DataType > void lczero::sycldnn_backend::Conv1Layer< DataType >::LoadWeights (float * pfilter, float * pBias, void * scratch)
Definition at line 1119 of file layers.cc.dp.cpp.
References C, lczero::sycldnn_backend::copyTypeConverted(), and weights_.
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::sycldnn_backend::Conv1Layer< DataType >::act_ private
Definition at line 230 of file layers.h.
biases_
template<typename DataType > DataType* lczero::sycldnn_backend::Conv1Layer< DataType >::biases_ = nullptr private
Definition at line 233 of file layers.h.
Referenced by lczero::sycldnn_backend::Conv1Layer< DataType >::Conv1Layer().
c_input_
template<typename DataType > const int lczero::sycldnn_backend::Conv1Layer< DataType >::c_input_ private
Definition at line 229 of file layers.h.
Referenced by lczero::sycldnn_backend::Conv1Layer< DataType >::Conv1Layer().
use_bias_
template<typename DataType > const bool lczero::sycldnn_backend::Conv1Layer< DataType >::use_bias_ private
Definition at line 231 of file layers.h.
Referenced by lczero::sycldnn_backend::Conv1Layer< DataType >::Conv1Layer().
weights_
template<typename DataType > DataType* lczero::sycldnn_backend::Conv1Layer< DataType >::weights_ = nullptr private
Definition at line 234 of file layers.h.
Referenced by lczero::sycldnn_backend::Conv1Layer< DataType >::Conv1Layer().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/sycl/layers.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/sycl/layers.cc.dp.cpp