Leela Chess Zero: lczero::BackendManager Class Reference
lczero::BackendManager Class Reference
#include <register.h>
Classes
struct Register
Public Member Functions
void AddBackend (std::unique_ptr< BackendFactory > factory)
void RemoveBackend (const BackendFactory *factory)
std::vector< std::string > GetBackendNames () const
std::unique_ptr< Backend > CreateFromParams (const OptionsDict &options) const
std::unique_ptr< Backend > CreateFromName (std::string_view name, const OptionsDict &options) const
BackendFactory * GetFactoryByName (std::string_view name) const
Static Public Member Functions
static BackendManager * Get ()
Private Member Functions
BackendManager ()=default
Private Attributes
std::vector< std::unique_ptr< BackendFactory > > algorithms_
Detailed Description
Definition at line 37 of file register.h.
Constructor & Destructor Documentation
BackendManager()
lczero::BackendManager::BackendManager () private default
Member Function Documentation
AddBackend()
void lczero::BackendManager::AddBackend (std::unique_ptr< BackendFactory > factory) inline
Definition at line 40 of file register.h.
References algorithms_.
Referenced by lczero::BackendManager::Register::Register().
CreateFromName()
std::unique_ptr< Backend > lczero::BackendManager::CreateFromName (std::string_view name, const OptionsDict & options) const
Definition at line 81 of file register.cc.
References lczero::BackendFactory::Create(), GetFactoryByName(), and name.
Referenced by CreateFromParams().
CreateFromParams()
std::unique_ptr< Backend > lczero::BackendManager::CreateFromParams (const OptionsDict & options) const
Definition at line 74 of file register.cc.
References CreateFromName(), lczero::OptionsDict::Get(), and lczero::SharedBackendParams::kBackendId.
Referenced by lczero::BackendBenchmark::Run().
Get()
BackendManager * lczero::BackendManager::Get () static
Definition at line 37 of file register.cc.
Referenced by lczero::SharedBackendParams::Populate(), lczero::BackendManager::Register::Register(), lczero::BackendBenchmark::Run(), lczero::Benchmark::Run(), and lczero::Engine::UpdateBackendConfig().
GetBackendNames()
std::vector< std::string > lczero::BackendManager::GetBackendNames () const
Definition at line 42 of file register.cc.
References algorithms_, name, p, and result.
Referenced by lczero::SharedBackendParams::Populate().
GetFactoryByName()
BackendFactory * lczero::BackendManager::GetFactoryByName (std::string_view name) const
Definition at line 65 of file register.cc.
References algorithms_, and name.
Referenced by CreateFromName().
RemoveBackend()
void lczero::BackendManager::RemoveBackend (const BackendFactory * factory)
Definition at line 88 of file register.cc.
References algorithms_.
Member Data Documentation
algorithms_
std::vector<std::unique_ptr<BackendFactory> > lczero::BackendManager::algorithms_ private
Definition at line 71 of file register.h.
Referenced by AddBackend(), GetBackendNames(), GetFactoryByName(), and RemoveBackend().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/register.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/register.cc