Leela Chess Zero: /home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/main.cc File Reference
main.cc File Reference
#include "chess/board.h"
#include "default_search.h"
#include "engine.h"
#include "search/register.h"
#include "selfplay/loop.h"
#include "tools/backendbench.h"
#include "tools/benchmark.h"
#include "tools/describenet.h"
#include "tools/leela2onnx.h"
#include "tools/onnx2leela.h"
#include "utils/commandline.h"
#include "utils/esc_codes.h"
#include "utils/logging.h"
#include "utils/trace.h"
#include "version.h"
Namespaces
namespace lczero
Functions
void lczero::ChooseAndRunEngine ()
int main (int argc, const char **argv)
Function Documentation
main()
int main (int argc, const char ** argv)
Definition at line 79 of file main.cc.
References CERR, lczero::ChooseAndRunEngine(), lczero::ConvertLeelaToOnnx(), lczero::ConvertOnnxToLeela(), lczero::DescribeNetworkCmd(), GetVersionStr(), LCTRACE_INITIALIZE, LOGFILE, lczero::SelfPlayLoop::Run(), lczero::BackendBenchmark::Run(), and lczero::Benchmark::Run().