Leela Chess Zero: lczero::dx_backend Namespace Reference
lczero::dx_backend Namespace Reference
Classes
class BaseLayer
class ConvLayer
class ConvMetaCommand
struct DXAlloc
class DxContext
class DxNetwork
class DxNetworkComputation
class FCLayer
class GemmMetaCommand
struct InputsOutputsDx
class PolicyMapLayer
class ShaderWrapper
Typedefs
typedef uint16_t dx_half
Functions
void DxError (HRESULT status, const char *file, const int &line)
int DivUp (int a, int b)
std::unique_ptr< Network > MakeDxNetwork (const std::optional< WeightsFile > &w, const OptionsDict &options)
Variables
constexpr int kMaxSupportedBatchSize = 256
static constexpr int kNumOutputPolicy = 1858
static constexpr int kNumOutputPolicyPadded8
static constexpr int kNumOutputValuePadded8 = 8
static constexpr int kNumOutputMovesLeftPadded8 = 8
Typedef Documentation
dx_half
typedef uint16_t lczero::dx_backend::dx_half
Definition at line 71 of file dx_common.h.
Function Documentation
DivUp()
int lczero::dx_backend::DivUp (int a, int b) inline
Definition at line 73 of file dx_common.h.
Referenced by lczero::dx_backend::ShaderWrapper::AddVectors(), lczero::dx_backend::DxContext::CreateAlloc(), lczero::dx_backend::FCLayer::Eval(), lczero::dx_backend::ShaderWrapper::ExpandPlanes(), lczero::dx_backend::ShaderWrapper::InputTransform(), lczero::dx_backend::ShaderWrapper::MatrixMultiply(), lczero::dx_backend::ShaderWrapper::OutputTransform(), lczero::dx_backend::ConvMetaCommand::PerformConv(), lczero::dx_backend::GemmMetaCommand::PerformGemm(), and lczero::dx_backend::ShaderWrapper::PolicyMap().
DxError()
void lczero::dx_backend::DxError (HRESULT status, const char * file, const int & line)
Definition at line 743 of file layers_dx.cc.
MakeDxNetwork()
std::unique_ptr< Network > lczero::dx_backend::MakeDxNetwork (const std::optional< WeightsFile > & w, const OptionsDict & options)
Definition at line 1071 of file network_dx.cc.
Variable Documentation
kMaxSupportedBatchSize
constexpr int lczero::dx_backend::kMaxSupportedBatchSize = 256 constexpr
Definition at line 40 of file layers_dx.h.
Referenced by lczero::dx_backend::DxNetwork::DxNetwork(), and lczero::dx_backend::DxNetwork::Eval().
kNumOutputMovesLeftPadded8
constexpr int lczero::dx_backend::kNumOutputMovesLeftPadded8 = 8 static constexpr
Definition at line 52 of file network_dx.h.
Referenced by lczero::dx_backend::DxNetwork::DxNetwork(), lczero::dx_backend::DxNetwork::Eval(), and lczero::dx_backend::InputsOutputsDx::InputsOutputsDx().
kNumOutputPolicy
constexpr int lczero::dx_backend::kNumOutputPolicy = 1858 static constexpr
Definition at line 42 of file network_dx.h.
Referenced by lczero::dx_backend::DxNetwork::DxNetwork(), lczero::dx_backend::DxNetwork::Eval(), lczero::dx_backend::DxNetworkComputation::GetPVal(), and lczero::dx_backend::InputsOutputsDx::InputsOutputsDx().
kNumOutputPolicyPadded8
constexpr int lczero::dx_backend::kNumOutputPolicyPadded8 static constexpr
Initial value:
=
    ((kNumOutputPolicy - 1) / 8 + 1) * 8
Definition at line 46 of file network_dx.h.
Referenced by lczero::dx_backend::DxNetwork::DxNetwork(), lczero::dx_backend::DxNetwork::Eval(), and lczero::dx_backend::InputsOutputsDx::InputsOutputsDx().
kNumOutputValuePadded8
constexpr int lczero::dx_backend::kNumOutputValuePadded8 = 8 static constexpr
Definition at line 50 of file network_dx.h.
Referenced by lczero::dx_backend::DxNetwork::DxNetwork(), lczero::dx_backend::DxNetwork::Eval(), and lczero::dx_backend::InputsOutputsDx::InputsOutputsDx().