Leela Chess Zero: /home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/opencl/OpenCLTuner.cc File Reference
OpenCLTuner.cc File Reference
#include "neural/backends/opencl/OpenCLTuner.h"
#include <array>
#include <cassert>
#include <cmath>
#include <fstream>
#include <iomanip>
#include <map>
#include <random>
#include <sstream>
#include <string>
#include "neural/backends/opencl/OpenCL.h"
#include "neural/backends/opencl/OpenCLParams.h"
#include "utils/logging.h"
Functions
static void sgemmBatched_ref (const std::vector< float > &a, const std::vector< float > &b, std::vector< float > &c, const int m, const int n, const int k, const int batch_size)
static bool IsMultiple (const size_t a, const size_t b)
static size_t next_power_of_two (const size_t x)
static void sgemm_generate_data (std::vector< float > &x, const int m, const int n, const int batch_size, const int m_ceil, const int n_ceil)
static float compare_ref (std::vector< float > &x, std::vector< float > &ref, const int m, const int n, const int batch_size, const int m_ceil, const int n_ceil)
Variables
constexpr auto MAX_ERROR = 1e-4f
Function Documentation
compare_ref()
static float compare_ref (std::vector< float > & x, std::vector< float > & ref, const int m, const int n, const int batch_size, const int m_ceil, const int n_ceil) static
Definition at line 165 of file OpenCLTuner.cc.
References m.
Referenced by Tuner::tune_sgemm().
IsMultiple()
static bool IsMultiple (const size_t a, const size_t b) static
Definition at line 63 of file OpenCLTuner.cc.
Referenced by Tuner::valid_config_sgemm().
next_power_of_two()
static size_t next_power_of_two (const size_t x) static
Definition at line 139 of file OpenCLTuner.cc.
Referenced by Tuner::tune_sgemm().
sgemm_generate_data()
static void sgemm_generate_data (std::vector< float > & x, const int m, const int n, const int batch_size, const int m_ceil, const int n_ceil) static
Definition at line 143 of file OpenCLTuner.cc.
References m.
Referenced by Tuner::tune_sgemm().
sgemmBatched_ref()
static void sgemmBatched_ref (const std::vector< float > & a, const std::vector< float > & b, std::vector< float > & c, const int m, const int n, const int k, const int batch_size) static
Definition at line 40 of file OpenCLTuner.cc.
References m.
Referenced by Tuner::tune_sgemm().
Variable Documentation
MAX_ERROR
constexpr auto MAX_ERROR = 1e-4f constexpr
Definition at line 38 of file OpenCLTuner.cc.
Referenced by Tuner::tune_sgemm().