Leela Chess Zero: lczero::File Struct Reference
lczero::File Struct Reference
#include <types.h>
Public Member Functions
File ()
constexpr bool IsValid () const
std::string ToString (bool uppercase=false) const
void Flop ()
auto operator<=> (const File &other) const =default
void operator++ ()
void operator-- ()
void operator+= (int delta)
File operator+ (int delta) const
File operator- (int delta) const
Static Public Member Functions
static constexpr File FromIdx (uint8_t idx)
static constexpr File Parse (char c)
Public Attributes
uint8_t idx
Private Member Functions
constexpr File (uint8_t idx)
Detailed Description
Definition at line 59 of file types.h.
Constructor & Destructor Documentation
File() [1/2]
lczero::File::File () inline
Definition at line 61 of file types.h.
Referenced by operator+(), operator-(), and Parse().
File() [2/2]
constexpr lczero::File::File (uint8_t idx) inline explicit constexpr private
Definition at line 77 of file types.h.
Member Function Documentation
Flop()
void lczero::File::Flop () inline
Definition at line 68 of file types.h.
References idx.
FromIdx()
static constexpr File lczero::File::FromIdx (uint8_t idx) inline static constexpr
Definition at line 63 of file types.h.
References idx.
Referenced by lczero::BitBoard::DebugString(), lczero::Square::file(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::PopulateBoard(), lczero::PgnReader::SanToMove(), and lczero::ChessBoard::SetFromFen().
IsValid()
constexpr bool lczero::File::IsValid () const inline constexpr
Definition at line 62 of file types.h.
References idx.
Referenced by lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
operator+()
File lczero::File::operator+ (int delta) const inline
Definition at line 73 of file types.h.
References File(), and idx.
operator++()
void lczero::File::operator++ () inline
Definition at line 70 of file types.h.
References idx.
operator+=()
void lczero::File::operator+= (int delta) inline
Definition at line 72 of file types.h.
References idx.
operator-()
File lczero::File::operator- (int delta) const inline
Definition at line 74 of file types.h.
References File(), and idx.
operator--()
void lczero::File::operator-- () inline
Definition at line 71 of file types.h.
References idx.
operator<=>()
auto lczero::File::operator<=> (const File & other) const default
Parse()
static constexpr File lczero::File::Parse (char c) inline static constexpr
Definition at line 64 of file types.h.
References File().
Referenced by lczero::Square::Parse(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
ToString()
std::string lczero::File::ToString (bool uppercase = false) const inline
Definition at line 65 of file types.h.
References idx.
Referenced by lczero::ChessBoard::Castlings::as_string(), lczero::ChessBoard::Castlings::DebugString(), and lczero::Square::ToString().
Member Data Documentation
idx
uint8_t lczero::File::idx
Definition at line 60 of file types.h.
Referenced by Flop(), FromIdx(), lczero::ChessBoard::GenerateKingAttackInfo(), IsValid(), operator+(), operator++(), operator+=(), lczero::operator-(), operator-(), operator--(), lczero::PopulateBoard(), ToString(), and lczero::Move::WhiteCastling().
The documentation for this struct was generated from the following file:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/chess/types.h