Leela Chess Zero: /home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/version.h File Reference
version.h File Reference
#include <cstdint>
#include <string>
#include "version.inc"
#include "build_id.h"
Functions
std::uint32_t GetVersionInt (int major=0, int minor=33, int patch=0)
std::string GetVersionStr (int major=0, int minor=33, int patch=0, const std::string &postfix="dev", const std::string &build_id=BUILD_IDENTIFIER)
Function Documentation
GetVersionInt()
std::uint32_t GetVersionInt (int major = 0, int minor = 33, int patch = 0)
Definition at line 29 of file version.cc.
GetVersionStr()
std::string GetVersionStr (int major = 0, int minor = 33, int patch = 0, const std::string & postfix = "dev", const std::string & build_id = BUILD_IDENTIFIER)
Definition at line 33 of file version.cc.
Referenced by main(), lczero::OnnxBuilder::OnnxBuilder(), and lczero::StringUciResponder::SendId().