Leela Chess Zero: lczero::PositionHistory Class Reference
lczero::PositionHistory Class Reference
Maintains a history of chess positions in a game.
#include <position.h>
Public Member Functions
PositionHistory ()=default
Default constructor for an empty position history.
PositionHistory (const PositionHistory &other)=default
Copy constructor to duplicate a position history.
PositionHistory (PositionHistory &&other)=default
Move constructor for efficient transfer of position history.
PositionHistory (std::span< const Position > positions)
Constructor that initializes the history from a span of positions.
PositionHistory & operator= (const PositionHistory &other)=default
Assignment operator for copying position history.
PositionHistory & operator= (PositionHistory &&other)=default
Move assignment operator for efficient transfer of position history.
const Position & Starting () const
Gets the first position of the game (or the FEN from which it was initialized).
const Position & Last () const
Gets the latest position of the game.
const Position & GetPositionAt (int idx) const
Gets the n-th position of the game (0-indexed).
void Trim (int size)
Trims the position history to a given size.
void Reserve (int size)
Reserves capacity to reduce allocation costs during move sequences.
int GetLength () const
Gets the number of positions currently in the history.
void Reset (const ChessBoard &board, int rule50_ply, int game_ply)
Resets the history to a given state from a chess board.
void Reset (const Position &pos)
Resets the history to a given state from a position.
void Append (Move m)
Appends a new position to the history by applying a move.
void Pop ()
Removes the last move from the history.
GameResult ComputeGameResult () const
Computes the endgame state (win/lose/draw/nothing) for the last position.
bool IsBlackToMove () const
Checks if the next move in the history should be black's.
uint64_t HashLast (int positions) const
Builds a hash from the last X positions in the history.
bool DidRepeatSinceLastZeroingMove () const
Checks for any repetitions since the last time the 50-move rule was reset.
std::span< const Position > GetPositions () const
Gets a span view of all positions in the history.
Private Member Functions
int ComputeLastMoveRepetitions (int *cycle_length) const
Computes the number of repetitions for the last move.
Private Attributes
std::vector< Position > positions_
Vector storing the sequence of positions in the game.
Detailed Description
Maintains a history of chess positions in a game.
This class stores the sequence of positions from the beginning of the game up to the current position, allowing for repetition detection, game result computation, and move history tracking. It's essential for implementing chess rules like threefold repetition and the 50-move rule.
Definition at line 143 of file position.h.
Constructor & Destructor Documentation
PositionHistory() [1/4]
lczero::PositionHistory::PositionHistory () default
Default constructor for an empty position history.
PositionHistory() [2/4]
lczero::PositionHistory::PositionHistory (const PositionHistory & other) default
Copy constructor to duplicate a position history.
Parameters
other The other position history to copy from.
PositionHistory() [3/4]
lczero::PositionHistory::PositionHistory (PositionHistory && other) default
Move constructor for efficient transfer of position history.
Parameters
other The other position history to move from.
PositionHistory() [4/4]
lczero::PositionHistory::PositionHistory (std::span< const Position > positions) inline
Constructor that initializes the history from a span of positions.
Parameters
positions Span of positions to initialize the history with.
Definition at line 158 of file position.h.
Member Function Documentation
Append()
void lczero::PositionHistory::Append (Move m)
Appends a new position to the history by applying a move.
Parameters
m The move to apply and append to the history.
Definition at line 105 of file position.cc.
References ComputeLastMoveRepetitions(), Last(), m, and positions_.
Referenced by lczero::classic::SearchWorker::ExtendNode(), lczero::python::GameState::GameState(), lczero::ValueEvaluator::Gather(), lczero::classic::Search::GetPositionHistoryAtNode(), lczero::classic::NodeTree::MakeMove(), lczero::SelfPlayGame::Play(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
ComputeGameResult()
GameResult lczero::PositionHistory::ComputeGameResult () const
Computes the endgame state (win/lose/draw/nothing) for the last position.
Returns
The game result based on the current position and rules.
Definition at line 75 of file position.cc.
References lczero::BLACK_WON, lczero::DRAW, lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), IsBlackToMove(), Last(), legal_moves, lczero::UNDECIDED, and lczero::WHITE_WON.
Referenced by lczero::ValueEvaluator::Gather(), and lczero::SelfPlayGame::Play().
ComputeLastMoveRepetitions()
int lczero::PositionHistory::ComputeLastMoveRepetitions (int * cycle_length) const private
Computes the number of repetitions for the last move.
Parameters
[out] cycle_length Pointer to store the cycle length if repetitions are found.
Returns
The number of repetitions for the last move.
Definition at line 115 of file position.cc.
References idx, and positions_.
Referenced by Append().
DidRepeatSinceLastZeroingMove()
bool lczero::PositionHistory::DidRepeatSinceLastZeroingMove () const
Checks for any repetitions since the last time the 50-move rule was reset.
This detects if the same position has occurred multiple times since the last capture or pawn move that would reset the 50-move counter.
Returns
True if a repetition has occurred since the last zeroing move, false otherwise.
Definition at line 132 of file position.cc.
References positions_.
Referenced by lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
GetLength()
int lczero::PositionHistory::GetLength () const inline
Gets the number of positions currently in the history.
Returns
The count of positions in the history.
Definition at line 198 of file position.h.
References positions_.
Referenced by lczero::TEST(), and lczero::TEST().
GetPositionAt()
const Position & lczero::PositionHistory::GetPositionAt (int idx) const inline
Gets the n-th position of the game (0-indexed).
Parameters
idx Index of the position to retrieve (0-based).
Returns
Constant reference to the position at the specified index.
Definition at line 182 of file position.h.
References idx, and positions_.
Referenced by lczero::TEST(), and lczero::TEST().
GetPositions()
std::span< const Position > lczero::PositionHistory::GetPositions () const inline
Gets a span view of all positions in the history.
Returns
A span containing constant references to all positions in the history.
Definition at line 239 of file position.h.
References positions_.
Referenced by lczero::EncodePositionForNN(), lczero::dag_classic::SearchWorker::ExtendNode(), and lczero::ValueEvaluator::Gather().
HashLast()
uint64_t lczero::PositionHistory::HashLast (int positions) const
Builds a hash from the last X positions in the history.
Parameters
positions Number of recent positions to include in the hash.
Returns
Combined hash of the specified number of recent positions.
Definition at line 141 of file position.cc.
References lczero::HashCat(), Last(), and positions_.
Referenced by lczero::dag_classic::SearchWorker::ExtendNode().
IsBlackToMove()
bool lczero::PositionHistory::IsBlackToMove () const inline
Checks if the next move in the history should be black's.
Returns
True if the next move should be black's, false if white's.
Definition at line 224 of file position.h.
References lczero::Position::IsBlackToMove(), and Last().
Referenced by lczero::python::GameState::as_string(), ComputeGameResult(), lczero::classic::Search::EnsureBestMoveKnown(), lczero::dag_classic::SearchWorker::FetchSingleNodeResult(), lczero::classic::Search::GetBestEval(), lczero::classic::Search::GetDrawScore(), lczero::classic::Search::GetVerboseStats(), lczero::python::GameState::moves(), lczero::classic::Search::Search(), lczero::classic::Search::SendMovesStats(), and lczero::classic::Search::SendUciInfo().
Last()
const Position & lczero::PositionHistory::Last () const inline
Gets the latest position of the game.
Returns
Constant reference to the last position in the history.
Definition at line 177 of file position.h.
References positions_.
Referenced by lczero::V6TrainingDataArray::Add(), Append(), lczero::python::GameState::as_string(), ComputeGameResult(), lczero::classic::Search::EnsureBestMoveKnown(), lczero::classic::SearchWorker::ExtendNode(), lczero::dag_classic::SearchWorker::ExtendNode(), lczero::python::GameState::GameState(), HashLast(), lczero::classic::NodeTree::HeadPosition(), lczero::dag_classic::NodeTree::HeadPosition(), IsBlackToMove(), lczero::python::GameState::moves(), lczero::python::GameState::policy_indices(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TestValidExpectation(), and lczero::TransformForPosition().
operator=() [1/2]
PositionHistory & lczero::PositionHistory::operator= (const PositionHistory & other) default
Assignment operator for copying position history.
Parameters
other The other position history to assign from.
Returns
Reference to this position history after assignment.
operator=() [2/2]
PositionHistory & lczero::PositionHistory::operator= (PositionHistory && other) default
Move assignment operator for efficient transfer of position history.
Parameters
other The other position history to move from.
Returns
Reference to this position history after assignment.
Pop()
void lczero::PositionHistory::Pop () inline
Removes the last move from the history.
This pops the last position from the history, effectively undoing the move.
Definition at line 216 of file position.h.
References positions_.
Referenced by lczero::ValueEvaluator::Gather().
Reserve()
void lczero::PositionHistory::Reserve (int size) inline
Reserves capacity to reduce allocation costs during move sequences.
This can be used to pre-allocate space when performing a sequence of moves in succession, reducing the number of memory allocations needed.
Parameters
size The capacity to reserve.
Definition at line 194 of file position.h.
References positions_.
Referenced by lczero::classic::SearchWorker::TaskWorkspace::TaskWorkspace().
Reset() [1/2]
void lczero::PositionHistory::Reset (const ChessBoard & board, int rule50_ply, int game_ply)
Resets the history to a given state from a chess board.
Parameters
board The chess board state to initialize from.
rule50_ply Number of half-moves since the last capture or pawn move.
game_ply Total number of half-moves since the start of the game.
Definition at line 94 of file position.cc.
References positions_.
Referenced by lczero::python::GameState::GameState(), lczero::classic::NodeTree::ResetToPosition(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TestValidExpectation().
Reset() [2/2]
void lczero::PositionHistory::Reset (const Position & pos)
Resets the history to a given state from a position.
Parameters
pos The position to initialize from.
Definition at line 100 of file position.cc.
References positions_.
Starting()
const Position & lczero::PositionHistory::Starting () const inline
Gets the first position of the game (or the FEN from which it was initialized).
Returns
Constant reference to the starting position.
Definition at line 173 of file position.h.
References positions_.
Referenced by lczero::classic::NodeTree::ResetToPosition().
Trim()
void lczero::PositionHistory::Trim (int size) inline
Trims the position history to a given size.
Parameters
size The new size to trim the history to.
Definition at line 186 of file position.h.
References positions_.
Referenced by lczero::classic::SearchWorker::ExtendNode().
Member Data Documentation
positions_
std::vector<Position> lczero::PositionHistory::positions_ private
Vector storing the sequence of positions in the game.
Definition at line 248 of file position.h.
Referenced by Append(), ComputeLastMoveRepetitions(), DidRepeatSinceLastZeroingMove(), GetLength(), GetPositionAt(), GetPositions(), HashLast(), Last(), Pop(), Reserve(), Reset(), Reset(), Starting(), and Trim().
The documentation for this class was generated from the following files:
chess/position.h
chess/position.cc