Leela Chess Zero: lczero::TransformingUciResponder Class Reference
lczero::TransformingUciResponder Class Reference
#include <callbacks.h>
Public Member Functions
TransformingUciResponder (std::unique_ptr< UciResponder > parent)
virtual void TransformBestMove (BestMoveInfo *)
virtual void TransformThinkingInfo (std::vector< ThinkingInfo > *)
Public Member Functions inherited from lczero::UciResponder
virtual ~UciResponder ()=default
Private Member Functions
virtual void OutputBestMove (BestMoveInfo *info)
virtual void OutputThinkingInfo (std::vector< ThinkingInfo > *infos)
Private Attributes
std::unique_ptr< UciResponder > parent_
Detailed Description
Definition at line 216 of file callbacks.h.
Constructor & Destructor Documentation
TransformingUciResponder()
lczero::TransformingUciResponder::TransformingUciResponder (std::unique_ptr< UciResponder > parent) inline
Definition at line 218 of file callbacks.h.
Member Function Documentation
OutputBestMove()
virtual void lczero::TransformingUciResponder::OutputBestMove (BestMoveInfo * info) inline private virtual
Implements lczero::UciResponder.
Definition at line 225 of file callbacks.h.
References parent_, and TransformBestMove().
OutputThinkingInfo()
virtual void lczero::TransformingUciResponder::OutputThinkingInfo (std::vector< ThinkingInfo > * infos) inline private virtual
Implements lczero::UciResponder.
Definition at line 229 of file callbacks.h.
References parent_, and TransformThinkingInfo().
TransformBestMove()
virtual void lczero::TransformingUciResponder::TransformBestMove (BestMoveInfo *) inline virtual
Definition at line 221 of file callbacks.h.
Referenced by OutputBestMove().
TransformThinkingInfo()
virtual void lczero::TransformingUciResponder::TransformThinkingInfo (std::vector< ThinkingInfo > *) inline virtual
Definition at line 222 of file callbacks.h.
Referenced by OutputThinkingInfo().
Member Data Documentation
parent_
std::unique_ptr<UciResponder> lczero::TransformingUciResponder::parent_ private
Definition at line 233 of file callbacks.h.
Referenced by OutputBestMove(), and OutputThinkingInfo().
The documentation for this class was generated from the following file:
src/chess/callbacks.h