Leela Chess Zero: lczero::PgnReader Class Reference
lczero::PgnReader Class Reference
#include <pgn.h>
Public Member Functions
void AddPgnFile (const std::string &filepath)
std::vector< Opening > GetGames () const
std::vector< Opening > && ReleaseGames ()
Private Member Functions
void Flush ()
Move SanToMove (const std::string &san, const ChessBoard &board)
Static Private Member Functions
static std::optional< PieceType > PieceToPieceType (int p)
Private Attributes
ChessBoard cur_board_ {ChessBoard::kStartposFen}
MoveList cur_game_
std::string cur_startpos_ = ChessBoard::kStartposFen
std::vector< Opening > games_
Detailed Description
Definition at line 66 of file pgn.h.
Member Function Documentation
AddPgnFile()
void lczero::PgnReader::AddPgnFile (const std::string & filepath) inline
Definition at line 68 of file pgn.h.
References lczero::ChessBoard::ApplyMove(), cur_board_, cur_game_, cur_startpos_, Flush(), lczero::GzGetLine(), idx, lczero::ChessBoard::Mirror(), SanToMove(), and lczero::ChessBoard::SetFromFen().
Flush()
void lczero::PgnReader::Flush () inline private
Definition at line 168 of file pgn.h.
References cur_board_, cur_game_, cur_startpos_, games_, lczero::ChessBoard::kStartposFen, and lczero::ChessBoard::SetFromFen().
Referenced by AddPgnFile().
GetGames()
std::vector< Opening > lczero::PgnReader::GetGames () const inline
Definition at line 164 of file pgn.h.
References games_.
PieceToPieceType()
static std::optional< PieceType > lczero::PgnReader::PieceToPieceType (int p) inline static private
Definition at line 175 of file pgn.h.
References CERR, lczero::kBishop, lczero::kKnight, lczero::kQueen, lczero::kRook, and p.
Referenced by SanToMove().
ReleaseGames()
std::vector< Opening > && lczero::PgnReader::ReleaseGames () inline
Definition at line 165 of file pgn.h.
References games_.
SanToMove()
Move lczero::PgnReader::SanToMove (const std::string & san, const ChessBoard & board) inline private
Definition at line 195 of file pgn.h.
References lczero::BitBoard::begin(), lczero::ChessBoard::bishops(), lczero::ChessBoard::castlings(), CERR, lczero::BitBoard::empty(), lczero::ChessBoard::en_passant(), lczero::Square::file(), lczero::ChessBoard::flipped(), lczero::File::FromIdx(), lczero::Rank::FromIdx(), lczero::ChessBoard::GenerateLegalMoves(), lczero::GetLowestBit(), idx, lczero::ChessBoard::kings(), lczero::ChessBoard::knights(), lczero::kRank1, lczero::kRank3, lczero::kRank6, m, lczero::ChessBoard::Castlings::our_kingside_rook, lczero::ChessBoard::Castlings::our_queenside_rook, lczero::ChessBoard::ours(), p, lczero::ChessBoard::pawns(), PieceToPieceType(), lczero::ChessBoard::queens(), lczero::ChessBoard::rooks(), lczero::Move::White(), lczero::Move::WhiteCastling(), lczero::Move::WhiteEnPassant(), and lczero::Move::WhitePromotion().
Referenced by AddPgnFile().
Member Data Documentation
cur_board_
ChessBoard lczero::PgnReader::cur_board_ {ChessBoard::kStartposFen} private
Definition at line 333 of file pgn.h.
Referenced by AddPgnFile(), and Flush().
cur_game_
MoveList lczero::PgnReader::cur_game_ private
Definition at line 334 of file pgn.h.
Referenced by AddPgnFile(), and Flush().
cur_startpos_
std::string lczero::PgnReader::cur_startpos_ = ChessBoard::kStartposFen private
Definition at line 335 of file pgn.h.
Referenced by AddPgnFile(), and Flush().
games_
std::vector<Opening> lczero::PgnReader::games_ private
Definition at line 336 of file pgn.h.
Referenced by Flush(), GetGames(), and ReleaseGames().
The documentation for this class was generated from the following file:
src/chess/pgn.h