Leela Chess Zero: lczero::NetworkAsBackendFactory Class Reference
lczero::NetworkAsBackendFactory Class Reference
#include <wrapper.h>
Public Types
using FactoryFunc = std::function< std::unique_ptr< Network >(const std::optional< WeightsFile > &, const OptionsDict &)>
Public Member Functions
NetworkAsBackendFactory (const std::string &name, FactoryFunc factory, int priority=0)
int GetPriority () const override
Gets the priority of this backend (higher is better).
std::string_view GetName () const override
Gets the name of the backend.
std::unique_ptr< Backend > Create (const OptionsDict &) override
Creates a new Backend instance with the given options.
Public Member Functions inherited from lczero::BackendFactory
virtual ~BackendFactory ()=default
Private Attributes
std::string name_
FactoryFunc factory_
int priority_
Detailed Description
Definition at line 38 of file wrapper.h.
Member Typedef Documentation
FactoryFunc
using lczero::NetworkAsBackendFactory::FactoryFunc = std::function<std::unique_ptr<Network>(const std::optional<WeightsFile>&, const OptionsDict&)>
Definition at line 40 of file wrapper.h.
Constructor & Destructor Documentation
NetworkAsBackendFactory()
lczero::NetworkAsBackendFactory::NetworkAsBackendFactory (const std::string & name, FactoryFunc factory, int priority = 0)
Definition at line 177 of file wrapper.cc.
Member Function Documentation
Create()
std::unique_ptr< Backend > lczero::NetworkAsBackendFactory::Create (const OptionsDict &) override virtual
Creates a new Backend instance with the given options.
Implements lczero::BackendFactory.
Definition at line 182 of file wrapper.cc.
References lczero::OptionsDict::AddSubdictFromString(), factory_, lczero::OptionsDict::Get(), lczero::SharedBackendParams::kBackendOptionsId, lczero::SharedBackendParams::kWeightsId, lczero::LoadWeights(), and name_.
GetName()
std::string_view lczero::NetworkAsBackendFactory::GetName () const inline override virtual
Gets the name of the backend.
Implements lczero::BackendFactory.
Definition at line 47 of file wrapper.h.
References name_.
GetPriority()
int lczero::NetworkAsBackendFactory::GetPriority () const inline override virtual
Gets the priority of this backend (higher is better).
Implements lczero::BackendFactory.
Definition at line 46 of file wrapper.h.
References priority_.
Member Data Documentation
factory_
FactoryFunc lczero::NetworkAsBackendFactory::factory_ private
Definition at line 52 of file wrapper.h.
Referenced by Create().
name_
std::string lczero::NetworkAsBackendFactory::name_ private
Definition at line 51 of file wrapper.h.
Referenced by Create(), and GetName().
priority_
int lczero::NetworkAsBackendFactory::priority_ private
Definition at line 53 of file wrapper.h.
Referenced by GetPriority().
The documentation for this class was generated from the following files:
src/neural/wrapper.h
src/neural/wrapper.cc