Leela Chess Zero: lczero::dag_classic::EdgeAndNode Class Reference
lczero::dag_classic::EdgeAndNode Class Reference
Contains Edge and Node pair and set of proxy functions.
#include <node.h>
Public Member Functions
EdgeAndNode ()=default
EdgeAndNode (Edge *edge, Node *node)
void Reset ()
operator bool () const
bool operator== (const EdgeAndNode &other) const
bool operator!= (const EdgeAndNode &other) const
bool HasNode () const
Edge * edge () const
Node * node () const
float GetQ (float default_q, float draw_score) const
float GetWL (float default_wl) const
float GetD (float default_d) const
float GetM (float default_m) const
uint32_t GetN () const
int GetNStarted () const
uint32_t GetNInFlight () const
bool IsTerminal () const
bool IsTbTerminal () const
Bounds GetBounds () const
float GetP () const
Move GetMove (bool flip=false) const
float GetU (float numerator) const
Returns U = numerator * p / (N + 1).
std::string DebugString () const
Protected Attributes
Edge * edge_ = nullptr
Node * node_ = nullptr
Detailed Description
Contains Edge and Node pair and set of proxy functions.
Simplifies access to combined edge/node properties.
Definition at line 769 of file node.h.
Constructor & Destructor Documentation
EdgeAndNode() [1/2]
lczero::dag_classic::EdgeAndNode::EdgeAndNode () default
EdgeAndNode() [2/2]
lczero::dag_classic::EdgeAndNode::EdgeAndNode (Edge * edge, Node * node) inline
Definition at line 772 of file node.h.
Member Function Documentation
DebugString()
std::string lczero::dag_classic::EdgeAndNode::DebugString () const
Definition at line 657 of file node.cc.
References lczero::dag_classic::Edge::DebugString(), and lczero::dag_classic::Node::edge_.
edge()
Edge * lczero::dag_classic::EdgeAndNode::edge () const inline
Definition at line 782 of file node.h.
References edge_.
GetBounds()
Bounds lczero::dag_classic::EdgeAndNode::GetBounds () const inline
Definition at line 806 of file node.h.
References lczero::BLACK_WON, lczero::dag_classic::Node::GetBounds(), node_, and lczero::WHITE_WON.
GetD()
float lczero::dag_classic::EdgeAndNode::GetD (float default_d) const inline
Definition at line 792 of file node.h.
References lczero::dag_classic::Node::GetD(), lczero::dag_classic::Node::GetN(), and node_.
Referenced by lczero::dag_classic::Search::GetBestEval().
GetM()
float lczero::dag_classic::EdgeAndNode::GetM (float default_m) const inline
Definition at line 795 of file node.h.
References lczero::dag_classic::Node::GetM(), lczero::dag_classic::Node::GetN(), and node_.
Referenced by lczero::dag_classic::Search::GetBestEval().
GetMove()
Move lczero::dag_classic::EdgeAndNode::GetMove (bool flip = false) const inline
Definition at line 815 of file node.h.
References edge_, and lczero::dag_classic::Edge::GetMove().
Referenced by lczero::dag_classic::Search::EnsureBestMoveKnown(), lczero::dag_classic::Search::GetBestEval(), and lczero::dag_classic::SearchWorker::PickNodesToExtendTask().
GetN()
uint32_t lczero::dag_classic::EdgeAndNode::GetN () const inline
Definition at line 799 of file node.h.
References lczero::dag_classic::Node::GetN(), and node_.
GetNInFlight()
uint32_t lczero::dag_classic::EdgeAndNode::GetNInFlight () const inline
Definition at line 801 of file node.h.
References lczero::dag_classic::Node::GetNInFlight(), and node_.
GetNStarted()
int lczero::dag_classic::EdgeAndNode::GetNStarted () const inline
Definition at line 800 of file node.h.
References lczero::dag_classic::Node::GetNStarted(), and node_.
Referenced by GetU().
GetP()
float lczero::dag_classic::EdgeAndNode::GetP () const inline
Definition at line 812 of file node.h.
References edge_, lczero::dag_classic::Edge::GetP(), lczero::dag_classic::Node::GetP(), and node_.
Referenced by GetU().
GetQ()
float lczero::dag_classic::EdgeAndNode::GetQ (float default_q, float draw_score) const inline
Definition at line 786 of file node.h.
References lczero::dag_classic::Node::GetN(), lczero::dag_classic::Node::GetQ(), and node_.
GetU()
float lczero::dag_classic::EdgeAndNode::GetU (float numerator) const inline
Returns U = numerator * p / (N + 1).
Used for PUCT calculation.
Parameters
numerator Expected to be (cpuct * sqrt(N[parent])).
Definition at line 822 of file node.h.
References GetNStarted(), and GetP().
GetWL()
float lczero::dag_classic::EdgeAndNode::GetWL (float default_wl) const inline
Definition at line 789 of file node.h.
References lczero::dag_classic::Node::GetN(), lczero::dag_classic::Node::GetWL(), and node_.
Referenced by lczero::dag_classic::Search::GetBestEval().
HasNode()
bool lczero::dag_classic::EdgeAndNode::HasNode () const inline
Definition at line 781 of file node.h.
References node_.
IsTbTerminal()
bool lczero::dag_classic::EdgeAndNode::IsTbTerminal () const inline
Definition at line 805 of file node.h.
References lczero::dag_classic::Node::IsTbTerminal(), and node_.
IsTerminal()
bool lczero::dag_classic::EdgeAndNode::IsTerminal () const inline
Definition at line 804 of file node.h.
References lczero::dag_classic::Node::IsTerminal(), and node_.
Referenced by lczero::dag_classic::Search::GetBestEval().
node()
Node * lczero::dag_classic::EdgeAndNode::node () const inline
Definition at line 783 of file node.h.
References node_.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), and lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode().
operator bool()
lczero::dag_classic::EdgeAndNode::operator bool () const inline explicit
Definition at line 774 of file node.h.
References edge_.
operator!=()
bool lczero::dag_classic::EdgeAndNode::operator!= (const EdgeAndNode & other) const inline
Definition at line 778 of file node.h.
References edge_.
operator==()
bool lczero::dag_classic::EdgeAndNode::operator== (const EdgeAndNode & other) const inline
Definition at line 775 of file node.h.
References edge_.
Reset()
void lczero::dag_classic::EdgeAndNode::Reset () inline
Definition at line 773 of file node.h.
References edge_.
Referenced by lczero::dag_classic::SearchWorker::PickNodesToExtendTask().
Member Data Documentation
edge_
Edge* lczero::dag_classic::EdgeAndNode::edge_ = nullptr protected
Definition at line 831 of file node.h.
Referenced by edge(), lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator(), GetMove(), GetP(), operator bool(), operator!=(), lczero::dag_classic::Edge_Iterator< is_const >::operator++(), operator==(), and Reset().
node_
Node* lczero::dag_classic::EdgeAndNode::node_ = nullptr protected
Definition at line 833 of file node.h.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), GetBounds(), GetD(), GetM(), GetN(), GetNInFlight(), GetNStarted(), lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode(), GetP(), GetQ(), GetWL(), HasNode(), IsTbTerminal(), IsTerminal(), and node().
The documentation for this class was generated from the following files:
src/search/dag_classic/node.h
src/search/dag_classic/node.cc