Leela Chess Zero: lczero::StringOption Class Reference
lczero::StringOption Class Reference
#include <optionsparser.h>
Public Types
using ValueType = std::string
Public Member Functions
StringOption (const OptionId &id)
void SetValue (const std::string &value, OptionsDict *dict) override
Public Member Functions inherited from lczero::OptionsParser::Option
Option (const OptionId &id)
virtual ~Option ()
Private Member Functions
std::string GetOptionString (const OptionsDict &dict) const override
bool ProcessLongFlag (const std::string &flag, const std::string &value, OptionsDict *dict) override
std::string GetHelp (const OptionsDict &dict) const override
bool ProcessShortFlagWithValue (char flag, const std::string &value, OptionsDict *dict) override
ValueType GetVal (const OptionsDict &) const
void SetVal (OptionsDict *dict, const ValueType &val) const
Additional Inherited Members
Protected Member Functions inherited from lczero::OptionsParser::Option
const OptionId & GetId () const
std::string GetUciOption () const
std::string GetHelpText () const
std::string GetLongFlag () const
char GetShortFlag () const
Detailed Description
Definition at line 132 of file optionsparser.h.
Member Typedef Documentation
ValueType
using lczero::StringOption::ValueType = std::string
Definition at line 134 of file optionsparser.h.
Constructor & Destructor Documentation
StringOption()
lczero::StringOption::StringOption (const OptionId & id)
Definition at line 291 of file optionsparser.cc.
Member Function Documentation
GetHelp()
std::string lczero::StringOption::GetHelp (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 317 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetHelpText(), lczero::OptionsParser::Option::GetLongFlag(), lczero::OptionsParser::Option::GetShortFlag(), lczero::OptionsParser::Option::GetUciOption(), and GetVal().
GetOptionString()
std::string lczero::StringOption::GetOptionString (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 326 of file optionsparser.cc.
References GetVal().
GetVal()
std::string lczero::StringOption::GetVal (const OptionsDict & dict) const private
Definition at line 330 of file optionsparser.cc.
References lczero::OptionsDict::Get(), and lczero::OptionsParser::Option::GetId().
Referenced by GetHelp(), and GetOptionString().
ProcessLongFlag()
bool lczero::StringOption::ProcessLongFlag (const std::string & flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 297 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag(), SetVal(), and value.
ProcessShortFlagWithValue()
bool lczero::StringOption::ProcessShortFlagWithValue (char flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 307 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetShortFlag(), SetVal(), and value.
SetVal()
void lczero::StringOption::SetVal (OptionsDict * dict, const ValueType & val) const private
Definition at line 334 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetId(), and lczero::OptionsDict::Set().
Referenced by ProcessLongFlag(), ProcessShortFlagWithValue(), and SetValue().
SetValue()
void lczero::StringOption::SetValue (const std::string & value, OptionsDict * dict) override virtual
Implements lczero::OptionsParser::Option.
Definition at line 293 of file optionsparser.cc.
References SetVal(), and value.
The documentation for this class was generated from the following files:
utils/optionsparser.h
utils/optionsparser.cc