Leela Chess Zero: lczero::OptionId Class Reference
lczero::OptionId Class Reference
#include <optionsdict.h>
Classes
struct OptionsParams
Public Types
enum VisibilityMode { kSimpleMode = 1 << 0 , kNormalMode = 1 << 1 , kProMode = 1 << 2 }
enum VisibilityMask { kSimpleOnly = kSimpleMode , kDefaultVisibility = kNormalMode | kProMode , kProOnly = kProMode , kAlwaysVisible = kSimpleMode | kNormalMode | kProMode }
Public Member Functions
OptionId (const OptionsParams &params)
OptionId (const char *long_flag, const char *uci_option, const char *help_text, const char short_flag='\0')
OptionId (const OptionId &other)=delete
bool operator== (const OptionId &other) const
const char * long_flag () const
const char * uci_option () const
const char * help_text () const
char short_flag () const
uint64_t visibility_mask () const
Private Attributes
const char *const long_flag_
const char *const uci_option_
const char *const help_text_
const char short_flag_
uint64_t visibility_mask_ = kDefaultVisibility
Detailed Description
Definition at line 95 of file optionsdict.h.
Member Enumeration Documentation
VisibilityMask
enum lczero::OptionId::VisibilityMask
Enumerator
kSimpleOnly
kDefaultVisibility
kProOnly
kAlwaysVisible
Definition at line 103 of file optionsdict.h.
VisibilityMode
enum lczero::OptionId::VisibilityMode
Enumerator
kSimpleMode
kNormalMode
kProMode
Definition at line 97 of file optionsdict.h.
Constructor & Destructor Documentation
OptionId() [1/3]
lczero::OptionId::OptionId (const OptionsParams & params) inline
Definition at line 118 of file optionsdict.h.
OptionId() [2/3]
lczero::OptionId::OptionId (const char * long_flag, const char * uci_option, const char * help_text, const char short_flag = '\0') inline
Definition at line 125 of file optionsdict.h.
OptionId() [3/3]
lczero::OptionId::OptionId (const OptionId & other) delete
Member Function Documentation
help_text()
const char * lczero::OptionId::help_text () const inline
Definition at line 137 of file optionsdict.h.
References help_text_.
Referenced by lczero::OptionsParser::Option::GetHelpText().
long_flag()
const char * lczero::OptionId::long_flag () const inline
Definition at line 135 of file optionsdict.h.
References long_flag_.
Referenced by lczero::OptionsDict::EnsureExists(), and lczero::OptionsParser::Option::GetLongFlag().
operator==()
bool lczero::OptionId::operator== (const OptionId & other) const inline
Definition at line 133 of file optionsdict.h.
short_flag()
char lczero::OptionId::short_flag () const inline
Definition at line 138 of file optionsdict.h.
References short_flag_.
Referenced by lczero::OptionsParser::Option::GetShortFlag().
uci_option()
const char * lczero::OptionId::uci_option () const inline
Definition at line 136 of file optionsdict.h.
References uci_option_.
Referenced by lczero::OptionsParser::Option::GetUciOption().
visibility_mask()
uint64_t lczero::OptionId::visibility_mask () const inline
Definition at line 139 of file optionsdict.h.
References visibility_mask_.
Member Data Documentation
help_text_
const char* const lczero::OptionId::help_text_ private
Definition at line 144 of file optionsdict.h.
Referenced by help_text().
long_flag_
const char* const lczero::OptionId::long_flag_ private
Definition at line 142 of file optionsdict.h.
Referenced by long_flag().
short_flag_
const char lczero::OptionId::short_flag_ private
Definition at line 145 of file optionsdict.h.
Referenced by short_flag().
uci_option_
const char* const lczero::OptionId::uci_option_ private
Definition at line 143 of file optionsdict.h.
Referenced by uci_option().
visibility_mask_
uint64_t lczero::OptionId::visibility_mask_ = kDefaultVisibility private
Definition at line 146 of file optionsdict.h.
Referenced by visibility_mask().
The documentation for this class was generated from the following file:
src/utils/optionsdict.h