Leela Chess Zero: lczero::dag_classic::Edge Class Reference
lczero::dag_classic::Edge Class Reference
Represents a single edge in the search graph (a move).
#include <node.h>
Public Member Functions
Move GetMove (bool as_opponent=false) const
Returns move from the point of view of the player making it.
float GetP () const
Returns value of Move policy prior.
void SetP (float val)
Sets value of Move policy prior.
std::string DebugString () const
Static Public Member Functions
static std::unique_ptr< Edge[]> FromMovelist (const MoveList &moves)
Creates array of edges from the list of moves.
static void SortEdges (Edge *edges, int num_edges)
Sorts edges by policy probability (descending).
Private Attributes
Move move_
uint16_t p_ = 0
Friends
class Node
Detailed Description
Represents a single edge in the search graph (a move).
Stores the move itself and its prior probability from the network.
Definition at line 181 of file node.h.
Member Function Documentation
DebugString()
std::string lczero::dag_classic::Edge::DebugString () const
Definition at line 109 of file node.cc.
References GetP(), move_, p_, and lczero::Move::ToString().
Referenced by lczero::dag_classic::EdgeAndNode::DebugString().
FromMovelist()
std::unique_ptr< Edge[]> lczero::dag_classic::Edge::FromMovelist (const MoveList & moves) static
Creates array of edges from the list of moves.
Definition at line 116 of file node.cc.
References move_, and moves.
Referenced by lczero::dag_classic::LowNode::LowNode(), and lczero::dag_classic::LowNode::LowNode().
GetMove()
Move lczero::dag_classic::Edge::GetMove (bool as_opponent = false) const
Returns move from the point of view of the player making it.
Parameters
as_opponent If true, returns the move as seen by the opponent.
Definition at line 53 of file node.cc.
References lczero::Move::Flip(), m, and move_.
Referenced by lczero::dag_classic::Node::GetMove(), and lczero::dag_classic::EdgeAndNode::GetMove().
GetP()
float lczero::dag_classic::Edge::GetP () const
Returns value of Move policy prior.
Must be in [0,1].
Definition at line 101 of file node.cc.
References p_.
Referenced by DebugString(), lczero::dag_classic::Node::GetP(), and lczero::dag_classic::EdgeAndNode::GetP().
SetP()
void lczero::dag_classic::Edge::SetP (float p)
Sets value of Move policy prior.
Sets policy prior from 32-bit float.
Parameters
val Value in [0,1].
Converts to compressed 16-bit format.
Definition at line 92 of file node.cc.
References p, and p_.
Referenced by lczero::dag_classic::Node::SetP().
SortEdges()
void lczero::dag_classic::Edge::SortEdges (Edge * edges, int num_edges) static
Sorts edges by policy probability (descending).
Definition at line 208 of file node.cc.
References p_.
Referenced by lczero::dag_classic::LowNode::SortEdges().
Friends And Related Symbol Documentation
Node
friend class Node friend
Definition at line 212 of file node.h.
Member Data Documentation
move_
Move lczero::dag_classic::Edge::move_ private
Definition at line 207 of file node.h.
Referenced by DebugString(), FromMovelist(), and GetMove().
p_
uint16_t lczero::dag_classic::Edge::p_ = 0 private
Definition at line 211 of file node.h.
Referenced by DebugString(), GetP(), SetP(), and SortEdges().
The documentation for this class was generated from the following files:
search/dag_classic/node.h
search/dag_classic/node.cc