Leela Chess Zero: lczero::classic::EdgeAndNode Class Reference
lczero::classic::EdgeAndNode Class Reference
#include <node.h>
Public Member Functions
EdgeAndNode ()=default
EdgeAndNode (Edge *edge, Node *node)
void Reset ()
operator bool () const
bool operator== (const EdgeAndNode &other) const
bool operator!= (const EdgeAndNode &other) const
bool HasNode () const
Edge * edge () const
Node * node () const
float GetQ (float default_q, float draw_score) const
float GetWL (float default_wl) const
float GetD (float default_d) const
float GetM (float default_m) const
uint32_t GetN () const
int GetNStarted () const
uint32_t GetNInFlight () const
bool IsTerminal () const
bool IsTbTerminal () const
Node::Bounds GetBounds () const
float GetP () const
Move GetMove (bool flip=false) const
float GetU (float numerator) const
std::string DebugString () const
Protected Attributes
Edge * edge_ = nullptr
Node * node_ = nullptr
Detailed Description
Definition at line 358 of file node.h.
Constructor & Destructor Documentation
EdgeAndNode() [1/2]
lczero::classic::EdgeAndNode::EdgeAndNode () default
EdgeAndNode() [2/2]
lczero::classic::EdgeAndNode::EdgeAndNode (Edge * edge, Node * node) inline
Definition at line 361 of file node.h.
Member Function Documentation
DebugString()
std::string lczero::classic::EdgeAndNode::DebugString () const
Definition at line 455 of file node.cc.
References lczero::classic::Edge::DebugString(), lczero::classic::Node::DebugString(), edge_, and node_.
edge()
Edge * lczero::classic::EdgeAndNode::edge () const inline
Definition at line 371 of file node.h.
References edge_.
GetBounds()
Node::Bounds lczero::classic::EdgeAndNode::GetBounds () const inline
Definition at line 395 of file node.h.
References lczero::BLACK_WON, lczero::classic::Node::GetBounds(), node_, and lczero::WHITE_WON.
GetD()
float lczero::classic::EdgeAndNode::GetD (float default_d) const inline
Definition at line 381 of file node.h.
References lczero::classic::Node::GetD(), lczero::classic::Node::GetN(), and node_.
Referenced by lczero::classic::Search::GetBestEval().
GetM()
float lczero::classic::EdgeAndNode::GetM (float default_m) const inline
Definition at line 384 of file node.h.
References lczero::classic::Node::GetM(), lczero::classic::Node::GetN(), and node_.
Referenced by lczero::classic::Search::GetBestEval().
GetMove()
Move lczero::classic::EdgeAndNode::GetMove (bool flip = false) const inline
Definition at line 402 of file node.h.
References edge_, and lczero::classic::Edge::GetMove().
Referenced by lczero::classic::Search::EnsureBestMoveKnown(), lczero::classic::Search::GetBestEval(), and lczero::classic::SearchWorker::PickNodesToExtendTask().
GetN()
uint32_t lczero::classic::EdgeAndNode::GetN () const inline
Definition at line 388 of file node.h.
References lczero::classic::Node::GetN(), and node_.
GetNInFlight()
uint32_t lczero::classic::EdgeAndNode::GetNInFlight () const inline
Definition at line 390 of file node.h.
References lczero::classic::Node::GetNInFlight(), and node_.
GetNStarted()
int lczero::classic::EdgeAndNode::GetNStarted () const inline
Definition at line 389 of file node.h.
References lczero::classic::Node::GetNStarted(), and node_.
Referenced by GetU().
GetP()
float lczero::classic::EdgeAndNode::GetP () const inline
Definition at line 401 of file node.h.
References edge_, and lczero::classic::Edge::GetP().
Referenced by GetU().
GetQ()
float lczero::classic::EdgeAndNode::GetQ (float default_q, float draw_score) const inline
Definition at line 375 of file node.h.
References lczero::classic::Node::GetN(), lczero::classic::Node::GetQ(), and node_.
GetU()
float lczero::classic::EdgeAndNode::GetU (float numerator) const inline
Definition at line 408 of file node.h.
References GetNStarted(), and GetP().
GetWL()
float lczero::classic::EdgeAndNode::GetWL (float default_wl) const inline
Definition at line 378 of file node.h.
References lczero::classic::Node::GetN(), lczero::classic::Node::GetWL(), and node_.
Referenced by lczero::classic::Search::GetBestEval().
HasNode()
bool lczero::classic::EdgeAndNode::HasNode () const inline
Definition at line 370 of file node.h.
References node_.
IsTbTerminal()
bool lczero::classic::EdgeAndNode::IsTbTerminal () const inline
Definition at line 394 of file node.h.
References lczero::classic::Node::IsTbTerminal(), and node_.
IsTerminal()
bool lczero::classic::EdgeAndNode::IsTerminal () const inline
Definition at line 393 of file node.h.
References lczero::classic::Node::IsTerminal(), and node_.
Referenced by lczero::classic::Search::GetBestEval().
node()
Node * lczero::classic::EdgeAndNode::node () const inline
Definition at line 372 of file node.h.
References node_.
operator bool()
lczero::classic::EdgeAndNode::operator bool () const inline explicit
Definition at line 363 of file node.h.
References edge_.
operator!=()
bool lczero::classic::EdgeAndNode::operator!= (const EdgeAndNode & other) const inline
Definition at line 367 of file node.h.
References edge_.
operator==()
bool lczero::classic::EdgeAndNode::operator== (const EdgeAndNode & other) const inline
Definition at line 364 of file node.h.
References edge_.
Reset()
void lczero::classic::EdgeAndNode::Reset () inline
Definition at line 362 of file node.h.
References edge_.
Referenced by lczero::classic::SearchWorker::PickNodesToExtendTask().
Member Data Documentation
edge_
Edge* lczero::classic::EdgeAndNode::edge_ = nullptr protected
Definition at line 417 of file node.h.
Referenced by DebugString(), edge(), lczero::classic::Edge_Iterator< is_const >::Edge_Iterator(), GetMove(), GetP(), operator bool(), operator!=(), lczero::classic::Edge_Iterator< is_const >::operator++(), operator==(), and Reset().
node_
Node* lczero::classic::EdgeAndNode::node_ = nullptr protected
Definition at line 419 of file node.h.
Referenced by lczero::classic::Edge_Iterator< is_const >::Actualize(), DebugString(), lczero::classic::Edge_Iterator< is_const >::Edge_Iterator(), GetBounds(), GetD(), GetM(), GetN(), GetNInFlight(), GetNStarted(), lczero::classic::Edge_Iterator< is_const >::GetOrSpawnNode(), GetQ(), GetWL(), HasNode(), IsTbTerminal(), IsTerminal(), node(), and lczero::classic::Edge_Iterator< is_const >::operator++().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/classic/node.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/classic/node.cc