Leela Chess Zero: lczero::dag_classic::NodeGarbageCollector Class Reference
lczero::dag_classic::NodeGarbageCollector Class Reference
Garbage collector for nodes in the DAG.
#include <node.h>
Public Types
enum State { Running , GoToSleep , Sleeping , Exit }
Public Member Functions
template<typename UniquePtr >
void AddToGcQueue (UniquePtr &node)
Delays node destruction until GC thread activates.
void Start ()
Starts the GC thread.
void Stop ()
Stops the GC thread.
State Wait () const
Waits for current GC cycle.
void Abort ()
Aborts GC.
void NotifyThreadGoingSleep ()
Moves thread local GC queue to the shared queue.
Static Public Member Functions
static NodeGarbageCollector & Instance ()
Access to the singleton instance.
Private Member Functions
NodeGarbageCollector ()
~NodeGarbageCollector ()
bool SetState (State &old, State desired)
bool IsActive () const
bool ShouldQueue (std::unique_ptr< Node > &node) const
void GCThread ()
Main function for the GC thread.
std::deque< std::vector< std::unique_ptr< Node > > > released_nodes_ GUARDED_BY (mutex_)
Static Private Member Functions
static ReleaseNodesWork & LocalWork (bool gc_thread=false)
Private Attributes
std::atomic< State > state_ = {Sleeping}
Mutex state_mutex_
std::condition_variable state_signal_
std::thread gc_thread_
SpinMutex mutex_
Friends
class ReleaseNodesWork
Detailed Description
Garbage collector for nodes in the DAG.
Deferring deletion of nodes prevents race conditions with other threads that might be reading from them during tree reuse or transposition. The collector runs in a separate thread and wakes up periodically or when the queue is full to delete nodes that are no longer reachable. It uses a double-buffering scheme with thread-local queues and a shared queue to minimize contention.
Definition at line 1214 of file node.h.
Member Enumeration Documentation
State
enum lczero::dag_classic::NodeGarbageCollector::State
Enumerator
Running
GoToSleep
Sleeping
Exit
Definition at line 1219 of file node.h.
Constructor & Destructor Documentation
NodeGarbageCollector()
lczero::dag_classic::NodeGarbageCollector::NodeGarbageCollector () private
Definition at line 756 of file node.cc.
References GCThread().
~NodeGarbageCollector()
lczero::dag_classic::NodeGarbageCollector::~NodeGarbageCollector () private
Definition at line 767 of file node.cc.
References gc_thread_.
Member Function Documentation
Abort()
void lczero::dag_classic::NodeGarbageCollector::Abort ()
Aborts GC.
Definition at line 809 of file node.cc.
AddToGcQueue()
template<typename UniquePtr > void lczero::dag_classic::NodeGarbageCollector::AddToGcQueue (UniquePtr & node)
Delays node destruction until GC thread activates.
Definition at line 760 of file node.cc.
Referenced by lczero::dag_classic::NodeTree::DeallocateTree(), lczero::dag_classic::LowNode::ReleaseChildren(), lczero::dag_classic::LowNode::~LowNode(), and lczero::dag_classic::Node::~Node().
GCThread()
void lczero::dag_classic::NodeGarbageCollector::GCThread () private
Main function for the GC thread.
Definition at line 855 of file node.cc.
References LOGFILE, mutex_, and lczero::dag_classic::ReleaseNodesWork::swap().
Referenced by NodeGarbageCollector().
GUARDED_BY()
std::deque< std::vector< std::unique_ptr< Node > > > released_nodes_ lczero::dag_classic::NodeGarbageCollector::GUARDED_BY (mutex_) private
Instance()
static NodeGarbageCollector & lczero::dag_classic::NodeGarbageCollector::Instance () inline static
Access to the singleton instance.
Definition at line 1227 of file node.h.
Referenced by lczero::dag_classic::NodeTree::DeallocateTree(), lczero::dag_classic::LowNode::ReleaseChildren(), lczero::dag_classic::LowNode::ReleaseChildrenExceptOne(), lczero::dag_classic::NodeTree::ResetToPosition(), lczero::dag_classic::ReleaseNodesWork::Submit(), lczero::dag_classic::NodeTree::TrimTreeAtHead(), lczero::dag_classic::LowNode::~LowNode(), lczero::dag_classic::Node::~Node(), and lczero::dag_classic::NodeTree::~NodeTree().
IsActive()
bool lczero::dag_classic::NodeGarbageCollector::IsActive () const private
Definition at line 833 of file node.cc.
LocalWork()
static ReleaseNodesWork & lczero::dag_classic::NodeGarbageCollector::LocalWork (bool gc_thread = false) inline static private
Definition at line 1260 of file node.h.
NotifyThreadGoingSleep()
void lczero::dag_classic::NodeGarbageCollector::NotifyThreadGoingSleep ()
Moves thread local GC queue to the shared queue.
Definition at line 825 of file node.cc.
References lczero::dag_classic::ReleaseNodesWork::swap().
Referenced by lczero::dag_classic::NodeTree::ResetToPosition(), and lczero::dag_classic::NodeTree::TrimTreeAtHead().
SetState()
bool lczero::dag_classic::NodeGarbageCollector::SetState (State & old, State desired) private
Definition at line 780 of file node.cc.
ShouldQueue()
bool lczero::dag_classic::NodeGarbageCollector::ShouldQueue (std::unique_ptr< Node > & node) const private
Definition at line 837 of file node.cc.
Start()
void lczero::dag_classic::NodeGarbageCollector::Start ()
Starts the GC thread.
Starts the GC thread if it's not already running.
Definition at line 795 of file node.cc.
Stop()
void lczero::dag_classic::NodeGarbageCollector::Stop ()
Stops the GC thread.
Stops the GC thread (requests sleep).
Definition at line 804 of file node.cc.
Wait()
NodeGarbageCollector::State lczero::dag_classic::NodeGarbageCollector::Wait () const
Waits for current GC cycle.
Definition at line 811 of file node.cc.
Friends And Related Symbol Documentation
ReleaseNodesWork
friend class ReleaseNodesWork friend
Definition at line 1277 of file node.h.
Member Data Documentation
gc_thread_
std::thread lczero::dag_classic::NodeGarbageCollector::gc_thread_ private
Definition at line 1272 of file node.h.
mutex_
SpinMutex lczero::dag_classic::NodeGarbageCollector::mutex_ private
Definition at line 1273 of file node.h.
state_
std::atomic<State> lczero::dag_classic::NodeGarbageCollector::state_ = {Sleeping} private
Definition at line 1265 of file node.h.
state_mutex_
Mutex lczero::dag_classic::NodeGarbageCollector::state_mutex_ mutable private
Definition at line 1269 of file node.h.
state_signal_
std::condition_variable lczero::dag_classic::NodeGarbageCollector::state_signal_ mutable private
Definition at line 1270 of file node.h.
The documentation for this class was generated from the following files:
search/dag_classic/node.h
search/dag_classic/node.cc