Leela Chess Zero: lczero::BitBoard Class Reference
lczero::BitBoard Class Reference
#include <bitboard.h>
Classes
struct Uin64ToSquare
Public Types
using Iterator = BitIterator< Square, Uin64ToSquare >
Public Member Functions
constexpr BitBoard (std::uint64_t board)
BitBoard ()=default
std::uint64_t as_int () const
void clear ()
int count () const
int count_few () const
void set_if (Square square, bool cond)
void set (Square square)
void reset (Square square)
bool get (Square square) const
bool empty () const
bool intersects (const BitBoard &other) const
void Mirror ()
bool operator== (const BitBoard &other) const =default
bool operator!= (const BitBoard &other) const =default
Iterator begin () const
Iterator end () const
std::string DebugString () const
BitBoard & operator&= (const BitBoard &a)
Static Public Member Functions
static constexpr BitBoard FromSquare (Square square)
Private Attributes
std::uint64_t board_ = 0
Friends
void swap (BitBoard &a, BitBoard &b)
BitBoard operator| (const BitBoard &a, const BitBoard &b)
BitBoard operator& (const BitBoard &a, const BitBoard &b)
BitBoard operator- (const BitBoard &a, const Square &b)
BitBoard operator- (const BitBoard &a, const BitBoard &b)
Detailed Description
Definition at line 43 of file bitboard.h.
Member Typedef Documentation
Iterator
using lczero::BitBoard::Iterator = BitIterator<Square, Uin64ToSquare>
Definition at line 115 of file bitboard.h.
Constructor & Destructor Documentation
BitBoard() [1/2]
constexpr lczero::BitBoard::BitBoard (std::uint64_t board) inline constexpr
Definition at line 45 of file bitboard.h.
BitBoard() [2/2]
lczero::BitBoard::BitBoard () default
Referenced by FromSquare().
Member Function Documentation
as_int()
std::uint64_t lczero::BitBoard::as_int () const inline
Definition at line 51 of file bitboard.h.
References board_.
Referenced by lczero::EncodePositionForNN(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::ChessBoard::Hash(), and lczero::KingAttackInfo::in_check().
begin()
Iterator lczero::BitBoard::begin () const inline
Definition at line 116 of file bitboard.h.
References board_.
Referenced by lczero::BoardToFen(), and lczero::PgnReader::SanToMove().
clear()
void lczero::BitBoard::clear () inline
Definition at line 52 of file bitboard.h.
References board_.
count()
int lczero::BitBoard::count () const inline
Definition at line 55 of file bitboard.h.
References board_.
Referenced by count_few(), and lczero::Numa::Init().
count_few()
int lczero::BitBoard::count_few () const inline
Definition at line 74 of file bitboard.h.
References board_, and count().
DebugString()
std::string lczero::BitBoard::DebugString () const inline
Definition at line 119 of file bitboard.h.
References lczero::File::FromIdx(), lczero::Rank::FromIdx(), and get().
empty()
bool lczero::BitBoard::empty () const inline
Definition at line 101 of file bitboard.h.
References board_.
Referenced by lczero::BoardToFen(), lczero::EncodePositionForNN(), lczero::ChessBoard::HasMatingMaterial(), lczero::PgnReader::SanToMove(), and lczero::TEST().
end()
Iterator lczero::BitBoard::end () const inline
Definition at line 117 of file bitboard.h.
FromSquare()
static constexpr BitBoard lczero::BitBoard::FromSquare (Square square) inline static constexpr
Definition at line 47 of file bitboard.h.
References lczero::Square::as_idx(), and BitBoard().
Referenced by lczero::ChessBoard::ApplyMove(), lczero::EncodePositionForNN(), and lczero::ChessBoard::kings().
get()
bool lczero::BitBoard::get (Square square) const inline
Definition at line 98 of file bitboard.h.
References lczero::Square::as_idx(), and board_.
Referenced by lczero::ChessBoard::ApplyMove(), DebugString(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::KingAttackInfo::is_on_attack_line(), lczero::KingAttackInfo::is_pinned(), lczero::ChessBoard::ParseMove(), lczero::SyzygyTablebase::search(), and lczero::ChessBoard::SetFromFen().
intersects()
bool lczero::BitBoard::intersects (const BitBoard & other) const inline
Definition at line 104 of file bitboard.h.
References board_.
Referenced by lczero::ChessBoard::ApplyMove(), and lczero::ChessBoard::HasMatingMaterial().
Mirror()
void lczero::BitBoard::Mirror () inline
Definition at line 107 of file bitboard.h.
References board_, and lczero::ReverseBytesInBytes().
Referenced by lczero::ChessBoard::Mirror().
operator!=()
bool lczero::BitBoard::operator!= (const BitBoard & other) const default
operator&=()
BitBoard & lczero::BitBoard::operator&= (const BitBoard & a) inline
Definition at line 130 of file bitboard.h.
References board_.
operator==()
bool lczero::BitBoard::operator== (const BitBoard & other) const default
reset()
void lczero::BitBoard::reset (Square square) inline
Definition at line 96 of file bitboard.h.
References lczero::Square::as_idx(), and board_.
Referenced by lczero::ChessBoard::ApplyMove().
set()
void lczero::BitBoard::set (Square square) inline
Definition at line 94 of file bitboard.h.
References lczero::Square::as_idx(), and board_.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::ChessBoard::PutPiece(), and lczero::ChessBoard::SetFromFen().
set_if()
void lczero::BitBoard::set_if (Square square, bool cond) inline
Definition at line 90 of file bitboard.h.
References lczero::Square::as_idx(), and board_.
Referenced by lczero::ChessBoard::ApplyMove().
Friends And Related Symbol Documentation
operator&
BitBoard operator& (const BitBoard & a, const BitBoard & b) friend
Definition at line 146 of file bitboard.h.
operator- [1/2]
BitBoard operator- (const BitBoard & a, const BitBoard & b) friend
Definition at line 156 of file bitboard.h.
operator- [2/2]
BitBoard operator- (const BitBoard & a, const Square & b) friend
Definition at line 151 of file bitboard.h.
operator|
BitBoard operator| (const BitBoard & a, const BitBoard & b) friend
Definition at line 141 of file bitboard.h.
swap
void swap (BitBoard & a, BitBoard & b) friend
Definition at line 135 of file bitboard.h.
Member Data Documentation
board_
std::uint64_t lczero::BitBoard::board_ = 0 private
Definition at line 161 of file bitboard.h.
Referenced by as_int(), begin(), clear(), count(), count_few(), empty(), get(), intersects(), Mirror(), operator&=(), reset(), set(), and set_if().
The documentation for this class was generated from the following file:
src/chess/bitboard.h