Leela Chess Zero: lczero::SyzygyTablebase Class Reference
lczero::SyzygyTablebase Class Reference
Interface for loading and probing Syzygy endgame tablebases.
#include <syzygy.h>
Public Member Functions
SyzygyTablebase ()
virtual ~SyzygyTablebase ()
int max_cardinality ()
Returns the maximum number of pieces for which tablebases are available.
bool init (const std::string &paths)
Initializes tablebases from the specified paths.
WDLScore probe_wdl (const Position &pos, ProbeState *result)
Probes WDL tables for the given position.
int probe_dtz (const Position &pos, ProbeState *result)
Probes DTZ tables to determine distance to zeroing move.
bool root_probe (const Position &pos, bool has_repeated, bool win_only, std::vector< Move > *safe_moves)
Probes DTZ tables to determine safe moves on the optimal path.
bool root_probe_wdl (const Position &pos, std::vector< Move > *safe_moves)
Probes WDL tables to determine potentially optimal moves.
Private Member Functions
template<bool CheckZeroingMoves = false>
WDLScore search (const Position &pos, ProbeState *result)
Internal search function for WDL probing.
Private Attributes
std::string paths_
int max_cardinality_
Cached maximum cardinality for performance.
std::unique_ptr< SyzygyTablebaseImpl > impl_
Implementation details (PIMPL pattern).
Detailed Description
Interface for loading and probing Syzygy endgame tablebases.
Provides methods to initialize tablebases from disk and probe them for WDL/DTZ information. All probe methods are thread-safe once init() has completed; however, init() itself is not thread-safe and must not be called concurrently with any other method.
Usage:
SyzygyTablebase tb;
if (tb.init("/path/to/tablebases")) {
  if (tb.max_cardinality() >= position.piece_count()) {
    ProbeState result;
    WDLScore wdl = tb.probe_wdl(position, &result);
    if (result == ProbeState::OK) {
      // Use wdl result
    }
  }
}
Definition at line 94 of file syzygy.h.
Constructor & Destructor Documentation
SyzygyTablebase()
lczero::SyzygyTablebase::SyzygyTablebase ()
Definition at line 1501 of file syzygy.cc.
~SyzygyTablebase()
lczero::SyzygyTablebase::~SyzygyTablebase () virtual default
Member Function Documentation
init()
bool lczero::SyzygyTablebase::init (const std::string & paths)
Initializes tablebases from the specified paths.
Parameters
paths Semicolon-separated (Windows) or colon-separated (Unix) list of directories containing tablebase files.
Returns
True if tablebase files were found.
Warning
Not thread-safe. Must not be called concurrently with any other method. All subsequent calls must be strictly ordered after this.
Definition at line 1505 of file syzygy.cc.
References impl_, max_cardinality_, and paths_.
Referenced by lczero::RunRescorer(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
max_cardinality()
int lczero::SyzygyTablebase::max_cardinality () inline
Returns the maximum number of pieces for which tablebases are available.
Returns
Maximum piece count that can be probed (0 if not initialized).
Note
Thread-safe.
Definition at line 103 of file syzygy.h.
References max_cardinality_.
Referenced by lczero::classic::SearchWorker::ExtendNode(), lczero::dag_classic::SearchWorker::ExtendNode(), lczero::RunRescorer(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
probe_dtz()
int lczero::SyzygyTablebase::probe_dtz (const Position & pos, ProbeState * result)
Probes DTZ tables to determine distance to zeroing move.
Parameters
pos The position to probe.
[out] result Probe state (OK if successful, FAIL otherwise).
Returns
Number of plies until a pawn move or capture under optimal play.
Note
Thread-safe.
Definition at line 1616 of file syzygy.cc.
References lczero::CHANGE_STM, lczero::FAIL, lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), lczero::Position::GetRule50Ply(), impl_, lczero::ChessBoard::IsUnderCheck(), lczero::OK, probe_dtz(), result, search(), lczero::WDL_BLESSED_LOSS, lczero::WDL_CURSED_WIN, lczero::WDL_DRAW, and lczero::ZEROING_BEST_MOVE.
Referenced by probe_dtz(), root_probe(), and lczero::TestValidExpectation().
probe_wdl()
WDLScore lczero::SyzygyTablebase::probe_wdl (const Position & pos, ProbeState * result)
Probes WDL tables for the given position.
Parameters
pos The position to probe.
[out] result Probe state (OK if successful, FAIL otherwise).
Returns
WDL score for the position. Only strictly valid when the 50-move counter is 0.
Note
Thread-safe.
Definition at line 1586 of file syzygy.cc.
References lczero::OK, result, and search().
Referenced by lczero::classic::SearchWorker::ExtendNode(), lczero::dag_classic::SearchWorker::ExtendNode(), root_probe(), root_probe_wdl(), and lczero::TestValidExpectation().
root_probe()
bool lczero::SyzygyTablebase::root_probe (const Position & pos, bool has_repeated, bool win_only, std::vector< Move > * safe_moves)
Probes DTZ tables to determine safe moves on the optimal path.
Parameters
pos The position to probe.
has_repeated Whether there have been repetitions since the last 50-move counter reset.
win_only If true, only return winning moves.
[out] safe_moves Vector to receive optimal moves.
Returns
True if the position was found in the tablebase.
Note
Thread-safe. Assumes optimal play since last 50-move counter reset.
Definition at line 1665 of file syzygy.cc.
References lczero::FAIL, lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), lczero::Position::GetRule50Ply(), lczero::ChessBoard::IsUnderCheck(), m, probe_dtz(), probe_wdl(), and result.
root_probe_wdl()
bool lczero::SyzygyTablebase::root_probe_wdl (const Position & pos, std::vector< Move > * safe_moves)
Probes WDL tables to determine potentially optimal moves.
Parameters
pos The position to probe.
[out] safe_moves Vector to receive potentially optimal moves.
Returns
True if the position was found in the tablebase.
Note
Thread-safe. With non-zero 50-move counter, some "winning" moves may actually result in draws.
Definition at line 1720 of file syzygy.cc.
References lczero::FAIL, lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), m, probe_wdl(), and result.
search()
template<bool CheckZeroingMoves> WDLScore lczero::SyzygyTablebase::search (const Position & pos, ProbeState * result) private
Internal search function for WDL probing.
Definition at line 1530 of file syzygy.cc.
References lczero::FAIL, lczero::ChessBoard::GenerateLegalMoves(), lczero::BitBoard::get(), lczero::Position::GetBoard(), impl_, lczero::OK, lczero::ChessBoard::pawns(), result, search(), value, lczero::WDL_DRAW, lczero::WDL_LOSS, lczero::WDL_WIN, and lczero::ZEROING_BEST_MOVE.
Referenced by probe_dtz(), probe_wdl(), and search().
Member Data Documentation
impl_
std::unique_ptr<SyzygyTablebaseImpl> lczero::SyzygyTablebase::impl_ private
Implementation details (PIMPL pattern).
Definition at line 156 of file syzygy.h.
Referenced by init(), probe_dtz(), and search().
max_cardinality_
int lczero::SyzygyTablebase::max_cardinality_ private
Cached maximum cardinality for performance.
Definition at line 154 of file syzygy.h.
Referenced by init(), and max_cardinality().
paths_
std::string lczero::SyzygyTablebase::paths_ private
Definition at line 152 of file syzygy.h.
Referenced by init().
The documentation for this class was generated from the following files:
src/syzygy/syzygy.h
src/syzygy/syzygy.cc