Leela Chess Zero: lczero::ProtoMessage Class Reference
lczero::ProtoMessage Class Reference abstract
#include <protomessage.h>
Public Member Functions
virtual ~ProtoMessage ()
virtual void Clear ()=0
void ParseFromString (std::string_view)
void MergeFromString (std::string_view)
virtual std::string OutputAsString () const =0
virtual std::string OutputAsJson () const =0
Static Protected Member Functions
template<class To , class From >
static To bit_cast (From from)
static void AppendVarInt (int field_id, std::uint64_t value, std::string *out)
static void AppendInt64 (int field_id, std::uint64_t value, std::string *out)
static void AppendInt32 (int field_id, std::uint32_t value, std::string *out)
static void AppendString (int field_id, std::string_view value, std::string *out)
template<typename T >
static void AppendJsonRepeatedField (const std::string &name, const std::vector< T > &val, bool *is_first, std::string *out)
template<typename T >
static void AppendJsonField (const std::string &name, const T &val, bool *is_first, std::string *out)
Private Member Functions
virtual void SetVarInt (int, uint64_t)
virtual void SetInt64 (int, uint64_t)
virtual void SetInt32 (int, uint32_t)
virtual void SetString (int, std::string_view)
Static Private Member Functions
static void AppendJsonFieldPrefix (const std::string &name, bool *is_first, std::string *out)
static void AppendJsonValue (const std::string &val, std::string *out)
static void AppendJsonValue (bool val, std::string *out)
static void AppendJsonValue (double val, std::string *out)
static void AppendJsonValue (uint64_t val, std::string *out)
static void AppendJsonValue (int64_t val, std::string *out)
static void AppendJsonValue (uint32_t val, std::string *out)
static void AppendJsonValue (int32_t val, std::string *out)
static void AppendJsonValue (const ProtoMessage &val, std::string *out)
Detailed Description
Definition at line 22 of file protomessage.h.
Constructor & Destructor Documentation
~ProtoMessage()
virtual lczero::ProtoMessage::~ProtoMessage () inline virtual
Definition at line 24 of file protomessage.h.
Member Function Documentation
AppendInt32()
void lczero::ProtoMessage::AppendInt32 (int field_id, std::uint32_t value, std::string * out) static protected
Definition at line 112 of file protomessage.cc.
References value.
AppendInt64()
void lczero::ProtoMessage::AppendInt64 (int field_id, std::uint64_t value, std::string * out) static protected
Definition at line 107 of file protomessage.cc.
References value.
AppendJsonField()
template<typename T > static void lczero::ProtoMessage::AppendJsonField (const std::string & name, const T & val, bool * is_first, std::string * out) inline static protected
Definition at line 62 of file protomessage.h.
References AppendJsonFieldPrefix(), AppendJsonValue(), and name.
AppendJsonFieldPrefix()
void lczero::ProtoMessage::AppendJsonFieldPrefix (const std::string & name, bool * is_first, std::string * out) static private
Definition at line 125 of file protomessage.cc.
References AppendJsonValue(), and name.
Referenced by AppendJsonField(), and AppendJsonRepeatedField().
AppendJsonRepeatedField()
template<typename T > static void lczero::ProtoMessage::AppendJsonRepeatedField (const std::string & name, const std::vector< T > & val, bool * is_first, std::string * out) inline static protected
Definition at line 50 of file protomessage.h.
References AppendJsonFieldPrefix(), AppendJsonValue(), and name.
AppendJsonValue() [1/8]
void lczero::ProtoMessage::AppendJsonValue (bool val, std::string * out) static private
Definition at line 161 of file protomessage.cc.
AppendJsonValue() [2/8]
void lczero::ProtoMessage::AppendJsonValue (const ProtoMessage & val, std::string * out) static private
Definition at line 179 of file protomessage.cc.
References OutputAsJson().
AppendJsonValue() [3/8]
void lczero::ProtoMessage::AppendJsonValue (const std::string & val, std::string * out) static private
Definition at line 156 of file protomessage.cc.
Referenced by AppendJsonField(), AppendJsonFieldPrefix(), and AppendJsonRepeatedField().
AppendJsonValue() [4/8]
void lczero::ProtoMessage::AppendJsonValue (double val, std::string * out) static private
Definition at line 164 of file protomessage.cc.
AppendJsonValue() [5/8]
void lczero::ProtoMessage::AppendJsonValue (int32_t val, std::string * out) static private
Definition at line 176 of file protomessage.cc.
AppendJsonValue() [6/8]
void lczero::ProtoMessage::AppendJsonValue (int64_t val, std::string * out) static private
Definition at line 170 of file protomessage.cc.
AppendJsonValue() [7/8]
void lczero::ProtoMessage::AppendJsonValue (uint32_t val, std::string * out) static private
Definition at line 173 of file protomessage.cc.
AppendJsonValue() [8/8]
void lczero::ProtoMessage::AppendJsonValue (uint64_t val, std::string * out) static private
Definition at line 167 of file protomessage.cc.
AppendString()
void lczero::ProtoMessage::AppendString (int field_id, std::string_view value, std::string * out) static protected
Definition at line 118 of file protomessage.cc.
References value.
AppendVarInt()
void lczero::ProtoMessage::AppendVarInt (int field_id, std::uint64_t value, std::string * out) static protected
Definition at line 102 of file protomessage.cc.
References value.
bit_cast()
template<class To , class From > static To lczero::ProtoMessage::bit_cast (From from) inline static protected
Definition at line 34 of file protomessage.h.
Clear()
virtual void lczero::ProtoMessage::Clear () pure virtual
Referenced by ParseFromString().
MergeFromString()
void lczero::ProtoMessage::MergeFromString (std::string_view str)
Definition at line 68 of file protomessage.cc.
References SetInt32(), SetInt64(), SetString(), and SetVarInt().
Referenced by ParseFromString().
OutputAsJson()
virtual std::string lczero::ProtoMessage::OutputAsJson () const pure virtual
Referenced by AppendJsonValue().
OutputAsString()
virtual std::string lczero::ProtoMessage::OutputAsString () const pure virtual
ParseFromString()
void lczero::ProtoMessage::ParseFromString (std::string_view str)
Definition at line 63 of file protomessage.cc.
References Clear(), and MergeFromString().
SetInt32()
virtual void lczero::ProtoMessage::SetInt32 (int , uint32_t) inline private virtual
Definition at line 71 of file protomessage.h.
Referenced by MergeFromString().
SetInt64()
virtual void lczero::ProtoMessage::SetInt64 (int , uint64_t) inline private virtual
Definition at line 70 of file protomessage.h.
Referenced by MergeFromString().
SetString()
virtual void lczero::ProtoMessage::SetString (int , std::string_view) inline private virtual
Definition at line 72 of file protomessage.h.
Referenced by MergeFromString().
SetVarInt()
virtual void lczero::ProtoMessage::SetVarInt (int , uint64_t) inline private virtual
Definition at line 69 of file protomessage.h.
Referenced by MergeFromString().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/protomessage.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/protomessage.cc