Leela Chess Zero: lczero::HloBuilder Class Reference
lczero::HloBuilder Class Reference
#include <hlo_builder.h>
Public Member Functions
HloFlow Parameter (const HloType &shape)
HloFlow Constant (const pblczero::XlaLiteralProto &literal)
HloFlow Convert (HloFlow input, const pblczero::XlaShapeProto::Type type)
HloFlow Convolution (HloFlow input, HloFlow filter, const pblczero::XlaWindow &window, const pblczero::XlaConvolutionDimensionNumbers &dimension_numbers)
HloFlow Broadcast (HloFlow input, const HloTensorType &target_shape, const std::vector< int64_t > &broadcast_dimensions)
HloFlow Add (HloFlow lhs, HloFlow rhs)
HloFlow Subtract (HloFlow lhs, HloFlow rhs)
HloFlow Multiply (HloFlow lhs, HloFlow rhs)
HloFlow Divide (HloFlow lhs, HloFlow rhs)
HloFlow Maximum (HloFlow lhs, HloFlow rhs)
HloFlow Reshape (HloFlow input, const HloTensorType &new_shape)
HloFlow Dot (HloFlow lhs, HloFlow rhs, const pblczero::XlaDotDimensionNumbers &dimension_numbers)
HloFlow Slice (HloFlow input, const std::vector< pblczero::HloInstructionProto::SliceDimensions > &slice)
HloFlow Concatenate (const std::vector< HloFlow > &inputs, int64_t dimension)
HloFlow Tanh (HloFlow input)
HloFlow LogPlusOne (HloFlow input)
HloFlow ExponentialMinusOne (HloFlow input)
HloFlow Negate (HloFlow input)
HloFlow Exponential (HloFlow input)
HloFlow Sqrt (HloFlow input)
HloFlow Rsqrt (HloFlow input)
HloFlow Tuple (const std::vector< HloFlow > &elements)
HloFlow Reduce (HloFlow input, HloFlow initial, HloComputation function, const std::vector< int64_t > &reduction_dimensions)
HloFlow Transpose (HloFlow input, const std::vector< int64_t > &permutation)
HloFlow Gather (HloFlow input, HloFlow indices, size_t index_vector_dim, const std::vector< int64_t > &offset_dims, const std::vector< int64_t > &slice_sizes, const std::vector< int64_t > &collapsed_slice_dims, const std::vector< int64_t > &start_index_map, bool indices_are_sorted, bool unique_indicies)
HloFlow Compare (HloFlow lhs, HloFlow rhs, std::string_view direction)
HloFlow Select (HloFlow condition, HloFlow on_true, HloFlow on_false)
HloComputation AddComputation (std::string_view name, const HloBuilder &builder)
std::optional< HloComputation > GetComputationId (std::string_view name) const
pblczero::HloModuleProto BuildModule (std::string_view name)
Private Member Functions
pblczero::HloInstructionProto * MakeInstruction (std::string_view opcode, const pblczero::XlaShapeProto &shape, const std::vector< const pblczero::HloInstructionProto * > operands)
pblczero::HloInstructionProto * MakeElementwiseInstruction (std::string_view opcode, HloFlow lhs, HloFlow rhs)
void AssignInstructionNames ()
pblczero::HloComputationProto ReassignInstructionIds (pblczero::HloComputationProto computation)
Private Attributes
size_t next_instruction_id_ = 0
InstructionList entry_computation_
std::unordered_map< std::string, size_t > computation_names_
std::vector< pblczero::HloComputationProto > dependent_computations_
pblczero::XlaOpMetadata metadata_
Friends
class HloContext
Detailed Description
Definition at line 100 of file hlo_builder.h.
Member Function Documentation
Add()
HloFlow lczero::HloBuilder::Add (HloFlow lhs, HloFlow rhs)
Definition at line 210 of file hlo_builder.cc.
References MakeElementwiseInstruction().
AddComputation()
HloComputation lczero::HloBuilder::AddComputation (std::string_view name, const HloBuilder & builder)
Definition at line 536 of file hlo_builder.cc.
References computation_names_, dependent_computations_, entry_computation_, name, and ReassignInstructionIds().
AssignInstructionNames()
void lczero::HloBuilder::AssignInstructionNames () private
Definition at line 515 of file hlo_builder.cc.
References dependent_computations_, entry_computation_, and idx.
Referenced by BuildModule().
Broadcast()
HloFlow lczero::HloBuilder::Broadcast (HloFlow input, const HloTensorType & target_shape, const std::vector< int64_t > & broadcast_dimensions)
Definition at line 157 of file hlo_builder.cc.
References flow, lczero::HloTensorType::GetDimension(), input, MakeInstruction(), lczero::HloTensorType::ToProto(), and lczero::HloTensorType::ToString().
BuildModule()
pblczero::HloModuleProto lczero::HloBuilder::BuildModule (std::string_view name)
Definition at line 601 of file hlo_builder.cc.
References AssignInstructionNames(), and dependent_computations_.
Compare()
HloFlow lczero::HloBuilder::Compare (HloFlow lhs, HloFlow rhs, std::string_view direction)
Definition at line 367 of file hlo_builder.cc.
References flow, MakeInstruction(), lczero::HloTensorType::SetElementType(), and lczero::HloTensorType::ToProto().
Concatenate()
HloFlow lczero::HloBuilder::Concatenate (const std::vector< HloFlow > & inputs, int64_t dimension)
Definition at line 414 of file hlo_builder.cc.
References flow, lczero::HloTensorType::GetDimension(), lczero::HloTensorType::GetElementType(), input, MakeInstruction(), lczero::HloTensorType::Rank(), lczero::HloTensorType::SetDimension(), lczero::HloTensorType::ToProto(), and lczero::HloTensorType::ToString().
Constant()
HloFlow lczero::HloBuilder::Constant (const pblczero::XlaLiteralProto & literal)
Definition at line 125 of file hlo_builder.cc.
References flow, and MakeInstruction().
Convert()
HloFlow lczero::HloBuilder::Convert (HloFlow input, const pblczero::XlaShapeProto::Type type)
Definition at line 117 of file hlo_builder.cc.
References input, MakeInstruction(), and type.
Convolution()
HloFlow lczero::HloBuilder::Convolution (HloFlow input, HloFlow filter, const pblczero::XlaWindow & window, const pblczero::XlaConvolutionDimensionNumbers & dimension_numbers)
Definition at line 131 of file hlo_builder.cc.
References flow, input, and MakeInstruction().
Divide()
HloFlow lczero::HloBuilder::Divide (HloFlow lhs, HloFlow rhs)
Definition at line 222 of file hlo_builder.cc.
References MakeElementwiseInstruction().
Dot()
HloFlow lczero::HloBuilder::Dot (HloFlow lhs, HloFlow rhs, const pblczero::XlaDotDimensionNumbers & dimension_numbers)
Definition at line 292 of file hlo_builder.cc.
References lczero::HloTensorType::AddDimension(), flow, lczero::HloTensorType::GetDimension(), lczero::HloTensorType::GetElementType(), MakeInstruction(), and lczero::HloTensorType::ToProto().
Exponential()
HloFlow lczero::HloBuilder::Exponential (HloFlow input)
Definition at line 401 of file hlo_builder.cc.
References input, and MakeInstruction().
ExponentialMinusOne()
HloFlow lczero::HloBuilder::ExponentialMinusOne (HloFlow input)
Definition at line 364 of file hlo_builder.cc.
References input, and MakeInstruction().
Gather()
HloFlow lczero::HloBuilder::Gather (HloFlow input, HloFlow indices, size_t index_vector_dim, const std::vector< int64_t > & offset_dims, const std::vector< int64_t > & slice_sizes, const std::vector< int64_t > & collapsed_slice_dims, const std::vector< int64_t > & start_index_map, bool indices_are_sorted, bool unique_indicies)
Definition at line 242 of file hlo_builder.cc.
References lczero::HloTensorType::AddDimension(), flow, lczero::HloTensorType::GetDimension(), lczero::HloTensorType::GetElementType(), input, MakeInstruction(), lczero::HloTensorType::Rank(), and lczero::HloTensorType::ToProto().
GetComputationId()
std::optional< HloComputation > lczero::HloBuilder::GetComputationId (std::string_view name) const
Definition at line 529 of file hlo_builder.cc.
References computation_names_, and name.
LogPlusOne()
HloFlow lczero::HloBuilder::LogPlusOne (HloFlow input)
Definition at line 360 of file hlo_builder.cc.
References input, and MakeInstruction().
MakeElementwiseInstruction()
pblczero::HloInstructionProto * lczero::HloBuilder::MakeElementwiseInstruction (std::string_view opcode, HloFlow lhs, HloFlow rhs) private
Definition at line 100 of file hlo_builder.cc.
References MakeInstruction().
Referenced by Add(), Divide(), Maximum(), Multiply(), and Subtract().
MakeInstruction()
pblczero::HloInstructionProto * lczero::HloBuilder::MakeInstruction (std::string_view opcode, const pblczero::XlaShapeProto & shape, const std::vector< const pblczero::HloInstructionProto * > operands) private
Definition at line 80 of file hlo_builder.cc.
References entry_computation_, metadata_, and next_instruction_id_.
Referenced by Broadcast(), Compare(), Concatenate(), Constant(), Convert(), Convolution(), Dot(), Exponential(), ExponentialMinusOne(), Gather(), LogPlusOne(), MakeElementwiseInstruction(), Negate(), Parameter(), Reduce(), Reshape(), Rsqrt(), Select(), Slice(), Sqrt(), Tanh(), Transpose(), and Tuple().
Maximum()
HloFlow lczero::HloBuilder::Maximum (HloFlow lhs, HloFlow rhs)
Definition at line 226 of file hlo_builder.cc.
References MakeElementwiseInstruction().
Multiply()
HloFlow lczero::HloBuilder::Multiply (HloFlow lhs, HloFlow rhs)
Definition at line 218 of file hlo_builder.cc.
References MakeElementwiseInstruction().
Negate()
HloFlow lczero::HloBuilder::Negate (HloFlow input)
Definition at line 397 of file hlo_builder.cc.
References input, and MakeInstruction().
Parameter()
HloFlow lczero::HloBuilder::Parameter (const HloType & shape)
Definition at line 112 of file hlo_builder.cc.
References MakeInstruction(), and lczero::HloType::ToProto().
ReassignInstructionIds()
pblczero::HloComputationProto lczero::HloBuilder::ReassignInstructionIds (pblczero::HloComputationProto computation) private
Definition at line 585 of file hlo_builder.cc.
References next_instruction_id_.
Referenced by AddComputation().
Reduce()
HloFlow lczero::HloBuilder::Reduce (HloFlow input, HloFlow initial, HloComputation function, const std::vector< int64_t > & reduction_dimensions)
Definition at line 181 of file hlo_builder.cc.
References lczero::HloTensorType::AddDimension(), flow, lczero::HloComputation::idx(), input, MakeInstruction(), and lczero::HloTensorType::ToProto().
Reshape()
HloFlow lczero::HloBuilder::Reshape (HloFlow input, const HloTensorType & new_shape)
Definition at line 230 of file hlo_builder.cc.
References lczero::HloTensorType::GetElementType(), input, MakeInstruction(), lczero::HloTensorType::NumElements(), lczero::HloTensorType::ToProto(), and lczero::HloTensorType::ToString().
Rsqrt()
HloFlow lczero::HloBuilder::Rsqrt (HloFlow input)
Definition at line 356 of file hlo_builder.cc.
References input, and MakeInstruction().
Select()
HloFlow lczero::HloBuilder::Select (HloFlow condition, HloFlow on_true, HloFlow on_false)
Definition at line 379 of file hlo_builder.cc.
References MakeInstruction().
Slice()
HloFlow lczero::HloBuilder::Slice (HloFlow input, const std::vector< pblczero::HloInstructionProto::SliceDimensions > & slice)
Definition at line 446 of file hlo_builder.cc.
References lczero::HloTensorType::AddDimension(), flow, lczero::HloTensorType::GetDimension(), lczero::HloTensorType::GetElementType(), input, MakeInstruction(), lczero::HloTensorType::Rank(), lczero::HloTensorType::ToProto(), and lczero::HloTensorType::ToString().
Sqrt()
HloFlow lczero::HloBuilder::Sqrt (HloFlow input)
Definition at line 352 of file hlo_builder.cc.
References input, and MakeInstruction().
Subtract()
HloFlow lczero::HloBuilder::Subtract (HloFlow lhs, HloFlow rhs)
Definition at line 214 of file hlo_builder.cc.
References MakeElementwiseInstruction().
Tanh()
HloFlow lczero::HloBuilder::Tanh (HloFlow input)
Definition at line 348 of file hlo_builder.cc.
References input, and MakeInstruction().
Transpose()
HloFlow lczero::HloBuilder::Transpose (HloFlow input, const std::vector< int64_t > & permutation)
Definition at line 199 of file hlo_builder.cc.
References lczero::HloTensorType::AddDimension(), flow, input, MakeInstruction(), and lczero::HloTensorType::ToProto().
Tuple()
HloFlow lczero::HloBuilder::Tuple (const std::vector< HloFlow > & elements)
Definition at line 405 of file hlo_builder.cc.
References MakeInstruction().
Friends And Related Symbol Documentation
HloContext
friend class HloContext friend
Definition at line 166 of file hlo_builder.h.
Member Data Documentation
computation_names_
std::unordered_map<std::string, size_t> lczero::HloBuilder::computation_names_ private
Definition at line 163 of file hlo_builder.h.
Referenced by AddComputation(), and GetComputationId().
dependent_computations_
std::vector<pblczero::HloComputationProto> lczero::HloBuilder::dependent_computations_ private
Definition at line 164 of file hlo_builder.h.
Referenced by AddComputation(), AssignInstructionNames(), and BuildModule().
entry_computation_
InstructionList lczero::HloBuilder::entry_computation_ private
Definition at line 162 of file hlo_builder.h.
Referenced by AddComputation(), AssignInstructionNames(), and MakeInstruction().
metadata_
pblczero::XlaOpMetadata lczero::HloBuilder::metadata_ private
Definition at line 165 of file hlo_builder.h.
Referenced by MakeInstruction(), lczero::HloContext::SetOpName(), lczero::HloContext::SetOpType(), and lczero::HloContext::~HloContext().
next_instruction_id_
size_t lczero::HloBuilder::next_instruction_id_ = 0 private
Definition at line 161 of file hlo_builder.h.
Referenced by MakeInstruction(), and ReassignInstructionIds().
The documentation for this class was generated from the following files:
src/neural/xla/hlo_builder.h
src/neural/xla/hlo_builder.cc