Leela Chess Zero: lczero::Benchmark Class Reference
lczero::Benchmark Class Reference
#include <benchmark.h>
Public Member Functions
Benchmark ()=default
void Run (bool run_shorter_benchmark=false)
void OnBestMove (const BestMoveInfo &move)
void OnInfo (const std::vector< ThinkingInfo > &infos)
Public Attributes
std::vector< std::string > positions
Detailed Description
Definition at line 36 of file benchmark.h.
Constructor & Destructor Documentation
Benchmark()
lczero::Benchmark::Benchmark () default
Member Function Documentation
OnBestMove()
void lczero::Benchmark::OnBestMove (const BestMoveInfo & move)
Definition at line 149 of file benchmark.cc.
References lczero::BestMoveInfo::bestmove, and lczero::Move::ToString().
Referenced by Run().
OnInfo()
void lczero::Benchmark::OnInfo (const std::vector< ThinkingInfo > & infos)
Definition at line 153 of file benchmark.cc.
Referenced by Run().
Run()
void lczero::Benchmark::Run (bool run_shorter_benchmark = false)
Definition at line 53 of file benchmark.cc.
References lczero::OptionsParser::Add(), lczero::CreateMemCache(), fen, lczero::BackendManager::Get(), lczero::OptionsParser::GetMutableDefaultsOptions(), lczero::OptionsParser::GetOptionsDict(), lczero::SharedBackendParams::kNNCacheSizeId, moves, OnBestMove(), OnInfo(), lczero::SharedBackendParams::Populate(), lczero::classic::SearchParams::Populate(), positions, lczero::OptionsParser::ProcessAllFlags(), lczero::classic::NodeTree::ResetToPosition(), lczero::OptionsDict::Set(), and lczero::StrSplitAtWhitespace().
Referenced by main().
Member Data Documentation
positions
std::vector<std::string> lczero::Benchmark::positions
Definition at line 41 of file benchmark.h.
Referenced by Run().
The documentation for this class was generated from the following files:
src/tools/benchmark.h
src/tools/benchmark.cc