Leela Chess Zero: lczero::Logging Class Reference
lczero::Logging Class Reference
#include <logging.h>
Public Member Functions
void SetFilename (const std::string &filename)
Static Public Member Functions
static Logging & Get ()
Private Member Functions
void WriteLineRaw (const std::string &line)
std::string filename_ GUARDED_BY (mutex_)
std::ofstream file_ GUARDED_BY (mutex_)
std::deque< std::string > buffer_ GUARDED_BY (mutex_)
Logging ()=default
Private Attributes
Mutex mutex_
Friends
class LogMessage
Detailed Description
Definition at line 41 of file logging.h.
Constructor & Destructor Documentation
Logging()
lczero::Logging::Logging () private default
Member Function Documentation
Get()
Logging & lczero::Logging::Get () static
Definition at line 41 of file logging.cc.
Referenced by lczero::SelfPlayLoop::Run(), lczero::RunEngine(), and lczero::LogMessage::~LogMessage().
GUARDED_BY() [1/3]
std::string filename_ lczero::Logging::GUARDED_BY (mutex_) private
GUARDED_BY() [2/3]
std::ofstream file_ lczero::Logging::GUARDED_BY (mutex_) private
GUARDED_BY() [3/3]
std::deque< std::string > buffer_ lczero::Logging::GUARDED_BY (mutex_) private
SetFilename()
void lczero::Logging::SetFilename (const std::string & filename)
Definition at line 57 of file logging.cc.
References mutex_.
Referenced by lczero::SelfPlayLoop::Run(), and lczero::RunEngine().
WriteLineRaw()
void lczero::Logging::WriteLineRaw (const std::string & line) private
Definition at line 46 of file logging.cc.
References mutex_.
Referenced by lczero::LogMessage::~LogMessage().
Friends And Related Symbol Documentation
LogMessage
friend class LogMessage friend
Definition at line 58 of file logging.h.
Member Data Documentation
mutex_
Mutex lczero::Logging::mutex_ private
Definition at line 52 of file logging.h.
Referenced by SetFilename(), and WriteLineRaw().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/logging.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/logging.cc