Leela Chess Zero: lczero::cudnn_backend::Conv1Layer< DataType > Class Template Reference
lczero::cudnn_backend::Conv1Layer< DataType > Class Template Reference
#include <layers.h>
Public Member Functions
Conv1Layer (BaseLayer< DataType > *ip, int C, int H, int W, int Cin, ActivationFunction activation, bool bias, bool use_gemm_ex)
~Conv1Layer ()
void LoadWeights (float *pfilter, float *pBias, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType ***=nullptr) override
Public Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, bool use_gemm_ex)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Member Functions
void cublasSpecialMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasSpecialMatrixMul (const half *A, const half *B, half *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasSpecialMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
Private Attributes
const int c_input_
const ActivationFunction act_
const bool use_bias_
DataType * biases_ = nullptr
DataType * weights_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const half *A, const half *B, half *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
Protected Attributes inherited from lczero::cudnn_backend::BaseLayer< DataType >
BaseLayer * input_
int C
int H
int W
bool nhwc_
const bool use_gemm_ex_
Detailed Description
template<typename DataType>
class lczero::cudnn_backend::Conv1Layer< DataType >
Definition at line 257 of file layers.h.
Constructor & Destructor Documentation
Conv1Layer()
template<typename DataType > lczero::cudnn_backend::Conv1Layer< DataType >::Conv1Layer (BaseLayer< DataType > * ip, int C, int H, int W, int Cin, ActivationFunction activation, bool bias, bool use_gemm_ex)
Definition at line 1028 of file layers.cc.
References lczero::cudnn_backend::Conv1Layer< DataType >::biases_, lczero::cudnn_backend::BaseLayer< DataType >::C, lczero::cudnn_backend::Conv1Layer< DataType >::c_input_, ReportCUDAErrors, lczero::cudnn_backend::Conv1Layer< DataType >::use_bias_, and lczero::cudnn_backend::Conv1Layer< DataType >::weights_.
~Conv1Layer()
template<typename DataType > lczero::cudnn_backend::Conv1Layer< DataType >::~Conv1Layer ()
Definition at line 1128 of file layers.cc.
References ReportCUDAErrors, and weights_.
Member Function Documentation
cublasSpecialMatrixMul() [1/3]
template<typename DataType > void lczero::cudnn_backend::Conv1Layer< DataType >::cublasSpecialMatrixMul (const DataType * A, const DataType * B, DataType * Out, int M, int N, int K, int batchSize, cublasHandle_t cublas) private
cublasSpecialMatrixMul() [2/3]
void lczero::cudnn_backend::Conv1Layer< float >::cublasSpecialMatrixMul (const float * A, const float * B, float * Out, int M, int N, int K, int batchSize, cublasHandle_t cublas) private
Definition at line 1091 of file layers.cc.
References ReportCUBLASErrors.
cublasSpecialMatrixMul() [3/3]
void lczero::cudnn_backend::Conv1Layer< half >::cublasSpecialMatrixMul (const half * A, const half * B, half * Out, int M, int N, int K, int batchSize, cublasHandle_t cublas) private
Definition at line 1066 of file layers.cc.
References ReportCUBLASErrors.
Eval()
template<typename DataType > void lczero::cudnn_backend::Conv1Layer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType *** = nullptr) override virtual
Implements lczero::cudnn_backend::BaseLayer< DataType >.
Definition at line 1112 of file layers.cc.
References lczero::ACTIVATION_NONE, lczero::cudnn_backend::addBias_NCHW(), lczero::cudnn_backend::addVectors(), C, input, output, and weights_.
LoadWeights()
template<typename DataType > void lczero::cudnn_backend::Conv1Layer< DataType >::LoadWeights (float * pfilter, float * pBias, void * scratch)
Definition at line 1046 of file layers.cc.
References C, lczero::cudnn_backend::copyTypeConverted(), ReportCUDAErrors, and weights_.
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::cudnn_backend::Conv1Layer< DataType >::act_ private
Definition at line 279 of file layers.h.
biases_
template<typename DataType > DataType* lczero::cudnn_backend::Conv1Layer< DataType >::biases_ = nullptr private
Definition at line 282 of file layers.h.
Referenced by lczero::cudnn_backend::Conv1Layer< DataType >::Conv1Layer().
c_input_
template<typename DataType > const int lczero::cudnn_backend::Conv1Layer< DataType >::c_input_ private
Definition at line 278 of file layers.h.
Referenced by lczero::cudnn_backend::Conv1Layer< DataType >::Conv1Layer().
use_bias_
template<typename DataType > const bool lczero::cudnn_backend::Conv1Layer< DataType >::use_bias_ private
Definition at line 280 of file layers.h.
Referenced by lczero::cudnn_backend::Conv1Layer< DataType >::Conv1Layer().
weights_
template<typename DataType > DataType* lczero::cudnn_backend::Conv1Layer< DataType >::weights_ = nullptr private
Definition at line 283 of file layers.h.
Referenced by lczero::cudnn_backend::Conv1Layer< DataType >::Conv1Layer().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/cuda/layers.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/cuda/layers.cc