Leela Chess Zero: lczero::UciResponder Class Reference
lczero::UciResponder Class Reference abstract
#include <callbacks.h>
Public Member Functions
virtual ~UciResponder ()=default
virtual void OutputBestMove (BestMoveInfo *info)=0
virtual void OutputThinkingInfo (std::vector< ThinkingInfo > *infos)=0
Detailed Description
Definition at line 143 of file callbacks.h.
Constructor & Destructor Documentation
~UciResponder()
virtual lczero::UciResponder::~UciResponder () virtual default
Member Function Documentation
OutputBestMove()
virtual void lczero::UciResponder::OutputBestMove (BestMoveInfo * info) pure virtual
Implemented in lczero::CallbackUciResponder, lczero::NonOwningUciRespondForwarder, lczero::TransformingUciResponder, lczero::UciResponderForwarder, lczero::StringUciResponder, and lczero::Engine::UciPonderForwarder.
Referenced by lczero::NonOwningUciRespondForwarder::OutputBestMove(), lczero::UciResponderForwarder::OutputBestMove(), and lczero::Engine::UciPonderForwarder::OutputBestMove().
OutputThinkingInfo()
virtual void lczero::UciResponder::OutputThinkingInfo (std::vector< ThinkingInfo > * infos) pure virtual
Implemented in lczero::CallbackUciResponder, lczero::NonOwningUciRespondForwarder, lczero::TransformingUciResponder, lczero::UciResponderForwarder, lczero::StringUciResponder, and lczero::Engine::UciPonderForwarder.
Referenced by lczero::NonOwningUciRespondForwarder::OutputThinkingInfo(), lczero::UciResponderForwarder::OutputThinkingInfo(), and lczero::Engine::UciPonderForwarder::OutputThinkingInfo().
The documentation for this class was generated from the following file:
src/chess/callbacks.h