Leela Chess Zero: lczero::dag_classic::LowNode Class Reference
lczero::dag_classic::LowNode Class Reference
Represents a unique position in the game DAG.
#include <node.h>
Public Member Functions
LowNode ()
LowNode (const LowNode &p)
Copy constructor for NNEval purposes only.
LowNode (const MoveList &moves)
Initializes from a list of moves with 0 policy.
LowNode (const MoveList &moves, uint16_t index)
Initializes from moves and creates one child immediately.
~LowNode ()
void SetNNEval (const EvalResult *eval)
Populates the node with neural network evaluation results.
atomic_unique_ptr< Node > * GetChild ()
Gets the first child node.
bool HasChildren () const
Returns whether the node has expanded children.
uint32_t GetN () const
Returns the visit count of this position.
uint32_t GetChildrenVisits () const
Returns visits that went into children (n - 1 for root usually).
float GetWL () const
Returns average Win-Loss score.
float GetD () const
Returns average Draw probability.
float GetM () const
Returns estimated moves remaining.
bool IsTerminal () const
Returns whether the node is terminal.
Bounds GetBounds () const
Returns min/max bounds.
Terminal GetTerminalType () const
Returns the specific terminal type.
uint8_t GetNumEdges () const
Returns number of legal moves (edges).
Edge * GetEdges () const
Returns raw pointer to the edge array.
void MakeTerminal (GameResult result, float plies_left=0.0f, Terminal type=Terminal::EndOfGame)
Marks the node as terminal with a specific result.
void MakeNotTerminal (const Node *node)
Reverts terminal status using information from a node.
void SetBounds (GameResult lower, GameResult upper)
Sets value bounds.
void CancelScoreUpdate (uint32_t multivisit)
Decrements n-in-flight back.
void FinalizeScoreUpdate (float v, float d, float m, uint32_t multivisit)
Updates the node with newly computed value v.
void AdjustForTerminal (float v, float d, float m, uint32_t multivisit)
Updates statistics for terminal node encounters.
void ReleaseChildren ()
Deletes all children.
void ReleaseChildrenExceptOne (Node *node_to_save)
Deletes all children except one.
const Edge & GetEdgeAt (uint16_t index) const
Return move policy for edge/node at @index.
std::string DebugString () const
Debug information about the node.
void DotNodeString (std::ofstream &file) const
Return string describing this node in the Graphviz dot format.
void SortEdges ()
Sorts edges by policy/value.
void AddParent ()
Add new parent with @n_in_flight visits.
void RemoveParent ()
Remove parent and its first visit.
bool IsTransposition () const
Returns true if this node is reached via multiple paths.
bool WLDMInvariantsHold () const
bool Visit (Node::VisitorId::type id)
Marks the node as visited by a specific visitor ID.
Private Attributes
double wl_ = 0.0f
double d_ = 0.0f
std::unique_ptr< Edge[]> edges_
atomic_unique_ptr< Node > child_
float m_ = 0.0f
uint32_t n_ = 0
std::atomic< uint16_t > num_parents_ = {}
uint8_t num_edges_ = 0
Terminal terminal_type_: 2
GameResult lower_bound_: 2
GameResult upper_bound_: 2
Node::VisitorId::storage visitor_id_ = {}
Detailed Description
Represents a unique position in the game DAG.
LowNode contains the legal moves (edges) and position-level statistics. It is shared by multiple Nodes if transpositions occur.
Definition at line 546 of file node.h.
Constructor & Destructor Documentation
LowNode() [1/4]
lczero::dag_classic::LowNode::LowNode () inline
Definition at line 548 of file node.h.
LowNode() [2/4]
lczero::dag_classic::LowNode::LowNode (const LowNode & p) inline
Copy constructor for NNEval purposes only.
Copies evaluation but not the children/edges structure deep.
Definition at line 555 of file node.h.
References edges_, num_edges_, and p.
LowNode() [3/4]
lczero::dag_classic::LowNode::LowNode (const MoveList & moves) inline
Initializes from a list of moves with 0 policy.
Definition at line 568 of file node.h.
References edges_, lczero::dag_classic::Edge::FromMovelist(), and moves.
LowNode() [4/4]
lczero::dag_classic::LowNode::LowNode (const MoveList & moves, uint16_t index) inline
Initializes from moves and creates one child immediately.
Parameters
moves List of legal moves.
index Index of the child to create.
Definition at line 579 of file node.h.
References child_, edges_, lczero::dag_classic::Edge::FromMovelist(), and moves.
~LowNode()
lczero::dag_classic::LowNode::~LowNode ()
Definition at line 149 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::AddToGcQueue(), child_, and lczero::dag_classic::NodeGarbageCollector::Instance().
Member Function Documentation
AddParent()
void lczero::dag_classic::LowNode::AddParent () inline
Add new parent with @n_in_flight visits.
Used to track transpositions.
Definition at line 693 of file node.h.
References num_parents_.
AdjustForTerminal()
void lczero::dag_classic::LowNode::AdjustForTerminal (float v, float d, float m, uint32_t multivisit)
Updates statistics for terminal node encounters.
Definition at line 370 of file node.cc.
References d, d_, m, m_, n_, wl_, and WLDMInvariantsHold().
CancelScoreUpdate()
void lczero::dag_classic::LowNode::CancelScoreUpdate (uint32_t multivisit)
Decrements n-in-flight back.
DebugString()
std::string lczero::dag_classic::LowNode::DebugString () const
Debug information about the node.
Definition at line 195 of file node.cc.
References child_, d_, edges_, lower_bound_, m_, n_, num_edges_, num_parents_, terminal_type_, upper_bound_, and wl_.
DotNodeString()
void lczero::dag_classic::LowNode::DotNodeString (std::ofstream & file) const
Return string describing this node in the Graphviz dot format.
Definition at line 522 of file node.cc.
References lczero::dag_classic::Node::d_, lczero::dag_classic::Node::lower_bound_, lczero::dag_classic::Node::m_, lczero::dag_classic::Node::n_, lczero::dag_classic::PtrToNodeName(), lczero::dag_classic::Node::terminal_type_, lczero::dag_classic::Node::upper_bound_, and lczero::dag_classic::Node::wl_.
Referenced by lczero::dag_classic::Node::DotGraphString().
FinalizeScoreUpdate()
void lczero::dag_classic::LowNode::FinalizeScoreUpdate (float v, float d, float m, uint32_t multivisit)
Updates the node with newly computed value v.
Updates Q (weighted average), N (+=multivisit), and N-in-flight (-=multivisit).
Parameters
v Value.
d Draw probability.
m Moves estimate.
multivisit Visits to add.
Definition at line 355 of file node.cc.
References d, d_, edges_, m, m_, n_, wl_, and WLDMInvariantsHold().
GetBounds()
Bounds lczero::dag_classic::LowNode::GetBounds () const inline
Returns min/max bounds.
Definition at line 632 of file node.h.
References lower_bound_, and upper_bound_.
GetChild()
atomic_unique_ptr< Node > * lczero::dag_classic::LowNode::GetChild () inline
Gets the first child node.
Definition at line 608 of file node.h.
References child_.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator(), and lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
GetChildrenVisits()
uint32_t lczero::dag_classic::LowNode::GetChildrenVisits () const inline
Returns visits that went into children (n - 1 for root usually).
Definition at line 617 of file node.h.
References n_.
GetD()
float lczero::dag_classic::LowNode::GetD () const inline
Returns average Draw probability.
Definition at line 623 of file node.h.
References d_.
GetEdgeAt()
const Edge & lczero::dag_classic::LowNode::GetEdgeAt (uint16_t index) const
Return move policy for edge/node at @index.
Definition at line 181 of file node.cc.
References edges_.
GetEdges()
Edge * lczero::dag_classic::LowNode::GetEdges () const inline
Returns raw pointer to the edge array.
Definition at line 641 of file node.h.
References edges_.
GetM()
float lczero::dag_classic::LowNode::GetM () const inline
Returns estimated moves remaining.
Definition at line 626 of file node.h.
References m_.
GetN()
uint32_t lczero::dag_classic::LowNode::GetN () const inline
Returns the visit count of this position.
Definition at line 614 of file node.h.
References n_.
GetNumEdges()
uint8_t lczero::dag_classic::LowNode::GetNumEdges () const inline
Returns number of legal moves (edges).
Definition at line 638 of file node.h.
References num_edges_.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator(), and lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
GetTerminalType()
Terminal lczero::dag_classic::LowNode::GetTerminalType () const inline
Returns the specific terminal type.
Definition at line 635 of file node.h.
References terminal_type_.
GetWL()
float lczero::dag_classic::LowNode::GetWL () const inline
Returns average Win-Loss score.
Definition at line 620 of file node.h.
References wl_.
HasChildren()
bool lczero::dag_classic::LowNode::HasChildren () const inline
Returns whether the node has expanded children.
Definition at line 611 of file node.h.
References num_edges_.
IsTerminal()
bool lczero::dag_classic::LowNode::IsTerminal () const inline
Returns whether the node is terminal.
Definition at line 629 of file node.h.
References lczero::dag_classic::NonTerminal, and terminal_type_.
Referenced by MakeNotTerminal().
IsTransposition()
bool lczero::dag_classic::LowNode::IsTransposition () const inline
Returns true if this node is reached via multiple paths.
Definition at line 706 of file node.h.
References num_parents_.
MakeNotTerminal()
void lczero::dag_classic::LowNode::MakeNotTerminal (const Node * node)
Reverts terminal status using information from a node.
Reverts terminal status and recomputes stats from children.
Definition at line 234 of file node.cc.
References lczero::BLACK_WON, d_, lczero::dag_classic::Node::Edges(), edges_, lczero::dag_classic::Node::GetNumEdges(), IsTerminal(), lower_bound_, m_, n_, lczero::dag_classic::NonTerminal, terminal_type_, upper_bound_, lczero::WHITE_WON, wl_, and WLDMInvariantsHold().
MakeTerminal()
void lczero::dag_classic::LowNode::MakeTerminal (GameResult result, float plies_left = 0.0f, Terminal type = Terminal::EndOfGame)
Marks the node as terminal with a specific result.
Definition at line 215 of file node.cc.
References lczero::BLACK_WON, d_, lczero::DRAW, m_, result, SetBounds(), terminal_type_, type, lczero::WHITE_WON, wl_, and WLDMInvariantsHold().
ReleaseChildren()
void lczero::dag_classic::LowNode::ReleaseChildren ()
Deletes all children.
Definition at line 416 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::AddToGcQueue(), child_, and lczero::dag_classic::NodeGarbageCollector::Instance().
ReleaseChildrenExceptOne()
void lczero::dag_classic::LowNode::ReleaseChildrenExceptOne (Node * node_to_save)
Deletes all children except one.
Parameters
node_to_save Child to preserve.
Definition at line 421 of file node.cc.
References child_, and lczero::dag_classic::NodeGarbageCollector::Instance().
RemoveParent()
void lczero::dag_classic::LowNode::RemoveParent () inline
Remove parent and its first visit.
Definition at line 700 of file node.h.
References num_parents_.
SetBounds()
void lczero::dag_classic::LowNode::SetBounds (GameResult lower, GameResult upper)
Sets value bounds.
Definition at line 269 of file node.cc.
References lower_bound_, and upper_bound_.
Referenced by MakeTerminal().
SetNNEval()
void lczero::dag_classic::LowNode::SetNNEval (const EvalResult * eval) inline
Populates the node with neural network evaluation results.
Sets policy priors, Q-value, draw probability, and moves remaining.
Definition at line 592 of file node.h.
References child_, lczero::EvalResult::d, d_, edges_, idx, lczero::EvalResult::m, m_, n_, num_edges_, lczero::EvalResult::p, lczero::EvalResult::q, wl_, and WLDMInvariantsHold().
SortEdges()
void lczero::dag_classic::LowNode::SortEdges () inline
Sorts edges by policy/value.
Definition at line 685 of file node.h.
References child_, edges_, num_edges_, and lczero::dag_classic::Edge::SortEdges().
Visit()
bool lczero::dag_classic::LowNode::Visit (Node::VisitorId::type id)
Marks the node as visited by a specific visitor ID.
Definition at line 474 of file node.cc.
WLDMInvariantsHold()
bool lczero::dag_classic::LowNode::WLDMInvariantsHold () const
Definition at line 645 of file node.cc.
References lczero::dag_classic::Node::DebugString(), lczero::dag_classic::Node::GetD(), lczero::dag_classic::Node::GetM(), lczero::dag_classic::Node::GetWL(), and lczero::dag_classic::WLDMInvariantsHold().
Referenced by AdjustForTerminal(), FinalizeScoreUpdate(), MakeNotTerminal(), MakeTerminal(), and SetNNEval().
Member Data Documentation
child_
atomic_unique_ptr<Node> lczero::dag_classic::LowNode::child_ private
Definition at line 736 of file node.h.
Referenced by DebugString(), GetChild(), LowNode(), ReleaseChildren(), ReleaseChildrenExceptOne(), SetNNEval(), SortEdges(), and ~LowNode().
d_
double lczero::dag_classic::LowNode::d_ = 0.0f private
Definition at line 730 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), FinalizeScoreUpdate(), GetD(), MakeNotTerminal(), MakeTerminal(), and SetNNEval().
edges_
std::unique_ptr<Edge[]> lczero::dag_classic::LowNode::edges_ private
Definition at line 734 of file node.h.
Referenced by DebugString(), FinalizeScoreUpdate(), GetEdgeAt(), GetEdges(), LowNode(), LowNode(), LowNode(), MakeNotTerminal(), SetNNEval(), and SortEdges().
lower_bound_
GameResult lczero::dag_classic::LowNode::lower_bound_ private
Definition at line 755 of file node.h.
Referenced by DebugString(), GetBounds(), MakeNotTerminal(), and SetBounds().
m_
float lczero::dag_classic::LowNode::m_ = 0.0f private
Definition at line 740 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), FinalizeScoreUpdate(), GetM(), MakeNotTerminal(), MakeTerminal(), and SetNNEval().
n_
uint32_t lczero::dag_classic::LowNode::n_ = 0 private
Definition at line 742 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), FinalizeScoreUpdate(), GetChildrenVisits(), GetN(), MakeNotTerminal(), and SetNNEval().
num_edges_
uint8_t lczero::dag_classic::LowNode::num_edges_ = 0 private
Definition at line 750 of file node.h.
Referenced by DebugString(), GetNumEdges(), HasChildren(), LowNode(), SetNNEval(), and SortEdges().
num_parents_
std::atomic<uint16_t> lczero::dag_classic::LowNode::num_parents_ = {} private
Definition at line 746 of file node.h.
Referenced by AddParent(), DebugString(), IsTransposition(), and RemoveParent().
terminal_type_
Terminal lczero::dag_classic::LowNode::terminal_type_ private
Definition at line 753 of file node.h.
Referenced by DebugString(), GetTerminalType(), IsTerminal(), MakeNotTerminal(), and MakeTerminal().
upper_bound_
GameResult lczero::dag_classic::LowNode::upper_bound_ private
Definition at line 756 of file node.h.
Referenced by DebugString(), GetBounds(), MakeNotTerminal(), and SetBounds().
visitor_id_
Node::VisitorId::storage lczero::dag_classic::LowNode::visitor_id_ = {} private
Definition at line 760 of file node.h.
wl_
double lczero::dag_classic::LowNode::wl_ = 0.0f private
Definition at line 727 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), FinalizeScoreUpdate(), GetWL(), MakeNotTerminal(), MakeTerminal(), and SetNNEval().
The documentation for this class was generated from the following files:
search/dag_classic/node.h
search/dag_classic/node.cc