Leela Chess Zero: lczero::BoolOption Class Reference
lczero::BoolOption Class Reference
Represents a boolean option in the Lc0 chess engine's configuration system.
#include <optionsparser.h>
Public Types
using ValueType = bool
Type alias for the underlying value type (bool).
Public Member Functions
BoolOption (const OptionId &id)
Constructor that initializes the boolean option with an identifier.
void SetValue (const std::string &value, OptionsDict *dict) override
Sets the boolean value from a string representation.
Public Member Functions inherited from lczero::OptionsParser::Option
Option (const OptionId &id)
virtual ~Option ()
Private Member Functions
std::string GetOptionString (const OptionsDict &dict) const override
Gets the string representation of the current option value.
bool ProcessLongFlag (const std::string &flag, const std::string &value, OptionsDict *dict) override
Processes a long-form command line flag for this option.
std::string GetHelp (const OptionsDict &dict) const override
Gets help text for this option.
bool ProcessShortFlag (char flag, OptionsDict *dict) override
Processes a short-form command line flag for this option.
ValueType GetVal (const OptionsDict &) const
Gets the current boolean value from the options dictionary.
void SetVal (OptionsDict *dict, const ValueType &val) const
Sets the boolean value in the options dictionary.
void ValidateBoolString (const std::string &val)
Validates that the input string represents a valid boolean value.
Additional Inherited Members
Protected Member Functions inherited from lczero::OptionsParser::Option
const OptionId & GetId () const
std::string GetUciOption () const
std::string GetHelpText () const
std::string GetLongFlag () const
char GetShortFlag () const
Detailed Description
Represents a boolean option in the Lc0 chess engine's configuration system.
This class handles boolean values for engine parameters, allowing them to be configured via UCI options or command line flags. Boolean options can be set to true/false values and are commonly used for enabling/disabling features.
Definition at line 200 of file optionsparser.h.
Member Typedef Documentation
ValueType
using lczero::BoolOption::ValueType = bool
Type alias for the underlying value type (bool).
Definition at line 203 of file optionsparser.h.
Constructor & Destructor Documentation
BoolOption()
lczero::BoolOption::BoolOption (const OptionId & id)
Constructor that initializes the boolean option with an identifier.
Parameters
id The unique identifier for this option.
Definition at line 495 of file optionsparser.cc.
Member Function Documentation
GetHelp()
std::string lczero::BoolOption::GetHelp (const OptionsDict & dict) const override private virtual
Gets help text for this option.
Parameters
dict The options dictionary containing the current value.
Returns
Formatted help string describing the option.
Implements lczero::OptionsParser::Option.
Definition at line 530 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetHelpText(), lczero::OptionsParser::Option::GetLongFlag(), lczero::OptionsParser::Option::GetShortFlag(), lczero::OptionsParser::Option::GetUciOption(), and GetVal().
GetOptionString()
std::string lczero::BoolOption::GetOptionString (const OptionsDict & dict) const override private virtual
Gets the string representation of the current option value.
Parameters
dict The options dictionary containing the current value.
Returns
String representation of the boolean value.
Implements lczero::OptionsParser::Option.
Definition at line 539 of file optionsparser.cc.
References GetVal().
GetVal()
BoolOption::ValueType lczero::BoolOption::GetVal (const OptionsDict & dict) const private
Gets the current boolean value from the options dictionary.
Parameters
dict The options dictionary containing the value.
Returns
The current boolean value.
Definition at line 543 of file optionsparser.cc.
References lczero::OptionsDict::Get(), and lczero::OptionsParser::Option::GetId().
Referenced by GetHelp(), GetOptionString(), and ProcessShortFlag().
ProcessLongFlag()
bool lczero::BoolOption::ProcessLongFlag (const std::string & flag, const std::string & value, OptionsDict * dict) override private virtual
Processes a long-form command line flag for this option.
Parameters
flag The flag name (without dashes).
value The value associated with the flag.
dict Pointer to the options dictionary to update.
Returns
True if the flag was processed successfully, false otherwise.
Reimplemented from lczero::OptionsParser::Option.
Definition at line 502 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag(), SetVal(), ValidateBoolString(), and value.
ProcessShortFlag()
bool lczero::BoolOption::ProcessShortFlag (char flag, OptionsDict * dict) override private virtual
Processes a short-form command line flag for this option.
Parameters
flag The character flag (without dash).
dict Pointer to the options dictionary to update.
Returns
True if the flag was processed successfully, false otherwise.
Reimplemented from lczero::OptionsParser::Option.
Definition at line 522 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetShortFlag(), GetVal(), and SetVal().
SetVal()
void lczero::BoolOption::SetVal (OptionsDict * dict, const ValueType & val) const private
Sets the boolean value in the options dictionary.
Parameters
dict Pointer to the options dictionary to update.
val The boolean value to store.
Definition at line 547 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetId(), and lczero::OptionsDict::Set().
Referenced by ProcessLongFlag(), ProcessShortFlag(), and SetValue().
SetValue()
void lczero::BoolOption::SetValue (const std::string & value, OptionsDict * dict) override virtual
Sets the boolean value from a string representation.
Parameters
value String representation of the boolean value ("true", "false", "1", "0", etc.).
dict Pointer to the options dictionary where the value should be stored.
Implements lczero::OptionsParser::Option.
Definition at line 497 of file optionsparser.cc.
References SetVal(), ValidateBoolString(), and value.
ValidateBoolString()
void lczero::BoolOption::ValidateBoolString (const std::string & val) private
Validates that the input string represents a valid boolean value.
Parameters
val The string to validate.
Exceptions
Exception if the string is not a valid boolean representation.
Definition at line 551 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag().
Referenced by ProcessLongFlag(), and SetValue().
The documentation for this class was generated from the following files:
utils/optionsparser.h
utils/optionsparser.cc