Leela Chess Zero: lczero::LruCache< K, V > Class Template Reference
lczero::LruCache< K, V > Class Template Reference
#include <cache-old.h>
Classes
struct Item
struct PairHash
Public Member Functions
LruCache (int capacity=128)
V * Insert (K key, std::unique_ptr< V > val, bool pinned=false)
V * Lookup (K key)
bool ContainsKey (K key)
void Unpin (K key, V *value)
void SetCapacity (int capacity)
int GetSize () const
int GetCapacity () const
Private Types
using ListIter = typename std::list< Item >::iterator
Private Member Functions
void MaybeCleanup (int size)
void MakePending (typename std::list< Item >::iterator iter)
void BringToFront (typename std::list< Item >::iterator iter)
Private Attributes
int capacity_
std::list< Item > lru_
std::unordered_map< K, ListIter > lookup_
std::unordered_map< std::pair< K, V * >, Item, PairHash > pending_pins_
std::mutex mutex_
Detailed Description
template<class K, class V>
class lczero::LruCache< K, V >
Definition at line 41 of file cache-old.h.
Member Typedef Documentation
ListIter
template<class K , class V > using lczero::LruCache< K, V >::ListIter = typename std::list<Item>::iterator private
Definition at line 149 of file cache-old.h.
Constructor & Destructor Documentation
LruCache()
template<class K , class V > lczero::LruCache< K, V >::LruCache (int capacity = 128) inline
Definition at line 43 of file cache-old.h.
Member Function Documentation
BringToFront()
template<class K , class V > void lczero::LruCache< K, V >::BringToFront (typename std::list< Item >::iterator iter) inline private
Definition at line 142 of file cache-old.h.
References lczero::LruCache< K, V >::lru_.
Referenced by lczero::LruCache< K, V >::Insert().
ContainsKey()
template<class K , class V > bool lczero::LruCache< K, V >::ContainsKey (K key) inline
Definition at line 81 of file cache-old.h.
References key, lczero::LruCache< K, V >::lookup_, and lczero::LruCache< K, V >::mutex_.
GetCapacity()
template<class K , class V > int lczero::LruCache< K, V >::GetCapacity () const inline
Definition at line 108 of file cache-old.h.
References lczero::LruCache< K, V >::capacity_.
GetSize()
template<class K , class V > int lczero::LruCache< K, V >::GetSize () const inline
Definition at line 107 of file cache-old.h.
References lczero::LruCache< K, V >::lru_.
Insert()
template<class K , class V > V * lczero::LruCache< K, V >::Insert (K key, std::unique_ptr< V > val, bool pinned = false) inline
Definition at line 50 of file cache-old.h.
References lczero::LruCache< K, V >::BringToFront(), lczero::LruCache< K, V >::capacity_, key, lczero::LruCache< K, V >::lookup_, lczero::LruCache< K, V >::lru_, lczero::LruCache< K, V >::MakePending(), lczero::LruCache< K, V >::MaybeCleanup(), and lczero::LruCache< K, V >::mutex_.
Lookup()
template<class K , class V > V * lczero::LruCache< K, V >::Lookup (K key) inline
Definition at line 71 of file cache-old.h.
References key, lczero::LruCache< K, V >::lookup_, and lczero::LruCache< K, V >::mutex_.
MakePending()
template<class K , class V > void lczero::LruCache< K, V >::MakePending (typename std::list< Item >::iterator iter) inline private
Definition at line 132 of file cache-old.h.
References key, and lczero::LruCache< K, V >::pending_pins_.
Referenced by lczero::LruCache< K, V >::Insert(), and lczero::LruCache< K, V >::MaybeCleanup().
MaybeCleanup()
template<class K , class V > void lczero::LruCache< K, V >::MaybeCleanup (int size) inline private
Definition at line 112 of file cache-old.h.
References lczero::LruCache< K, V >::lookup_, lczero::LruCache< K, V >::lru_, and lczero::LruCache< K, V >::MakePending().
Referenced by lczero::LruCache< K, V >::Insert(), and lczero::LruCache< K, V >::SetCapacity().
SetCapacity()
template<class K , class V > void lczero::LruCache< K, V >::SetCapacity (int capacity) inline
Definition at line 101 of file cache-old.h.
References lczero::LruCache< K, V >::capacity_, lczero::LruCache< K, V >::MaybeCleanup(), and lczero::LruCache< K, V >::mutex_.
Unpin()
template<class K , class V > void lczero::LruCache< K, V >::Unpin (K key, V * value) inline
Definition at line 88 of file cache-old.h.
References key, lczero::LruCache< K, V >::lookup_, lczero::LruCache< K, V >::mutex_, lczero::LruCache< K, V >::pending_pins_, and value.
Member Data Documentation
capacity_
template<class K , class V > int lczero::LruCache< K, V >::capacity_ private
Definition at line 147 of file cache-old.h.
Referenced by lczero::LruCache< K, V >::GetCapacity(), lczero::LruCache< K, V >::Insert(), and lczero::LruCache< K, V >::SetCapacity().
lookup_
template<class K , class V > std::unordered_map<K, ListIter> lczero::LruCache< K, V >::lookup_ private
Definition at line 150 of file cache-old.h.
Referenced by lczero::LruCache< K, V >::ContainsKey(), lczero::LruCache< K, V >::Insert(), lczero::LruCache< K, V >::Lookup(), lczero::LruCache< K, V >::MaybeCleanup(), and lczero::LruCache< K, V >::Unpin().
lru_
template<class K , class V > std::list<Item> lczero::LruCache< K, V >::lru_ private
Definition at line 148 of file cache-old.h.
Referenced by lczero::LruCache< K, V >::BringToFront(), lczero::LruCache< K, V >::GetSize(), lczero::LruCache< K, V >::Insert(), and lczero::LruCache< K, V >::MaybeCleanup().
mutex_
template<class K , class V > std::mutex lczero::LruCache< K, V >::mutex_ private
Definition at line 158 of file cache-old.h.
Referenced by lczero::LruCache< K, V >::ContainsKey(), lczero::LruCache< K, V >::Insert(), lczero::LruCache< K, V >::Lookup(), lczero::LruCache< K, V >::SetCapacity(), and lczero::LruCache< K, V >::Unpin().
pending_pins_
template<class K , class V > std::unordered_map<std::pair<K, V*>, Item, PairHash> lczero::LruCache< K, V >::pending_pins_ private
Definition at line 157 of file cache-old.h.
Referenced by lczero::LruCache< K, V >::MakePending(), and lczero::LruCache< K, V >::Unpin().
The documentation for this class was generated from the following file:
utils/cache-old.h