Leela Chess Zero: lczero::PjrtCommon Class Reference
lczero::PjrtCommon Class Reference
Shared base class for all PJRT wrappers.
#include <pjrt.h>
Protected Member Functions
PjrtCommon (const PJRT_Api *api)
virtual ~PjrtCommon ()=default
std::string GetErrorMessage (PJRT_Error *error) const
void DestroyErrorMessage (PJRT_Error *error) const
void CheckError (PJRT_Error *error) const
Protected Attributes
const PJRT_Api * api_
Detailed Description
Shared base class for all PJRT wrappers.
Keeps the API pointer and auxiliary functions like error checking.
Definition at line 142 of file pjrt.h.
Constructor & Destructor Documentation
PjrtCommon()
lczero::PjrtCommon::PjrtCommon (const PJRT_Api * api) inline protected
Definition at line 144 of file pjrt.h.
~PjrtCommon()
virtual lczero::PjrtCommon::~PjrtCommon () protected virtual default
Member Function Documentation
CheckError()
void lczero::PjrtCommon::CheckError (PJRT_Error * error) const protected
Definition at line 121 of file pjrt.cc.
References api_, DestroyErrorMessage(), and GetErrorMessage().
Referenced by lczero::PjrtEvent::Await(), lczero::PjrtClient::CompileHlo(), lczero::Pjrt::CreateClient(), lczero::PjrtDeviceBuffer::DeviceToHost(), lczero::PjrtExecutable::ExecuteBlocking(), lczero::Pjrt::GetAttributes(), lczero::PjrtClient::GetDevices(), lczero::PjrtDeviceBuffer::GetDimensions(), lczero::PjrtDeviceBuffer::GetSize(), lczero::PjrtDeviceBuffer::GetType(), lczero::PjrtClient::HostToDevice(), lczero::Pjrt::Initialize(), lczero::PjrtDevice::PjrtDevice(), lczero::PjrtExecutable::PjrtExecutable(), lczero::PjrtDevice::ToString(), lczero::PjrtClient::~PjrtClient(), lczero::PjrtDeviceBuffer::~PjrtDeviceBuffer(), lczero::PjrtEvent::~PjrtEvent(), lczero::PjrtExecutable::~PjrtExecutable(), and lczero::PjrtHostToDeviceTransfer::~PjrtHostToDeviceTransfer().
DestroyErrorMessage()
void lczero::PjrtCommon::DestroyErrorMessage (PJRT_Error * error) const protected
Definition at line 114 of file pjrt.cc.
References api_.
Referenced by CheckError().
GetErrorMessage()
std::string lczero::PjrtCommon::GetErrorMessage (PJRT_Error * error) const protected
Definition at line 108 of file pjrt.cc.
References api_.
Referenced by CheckError().
Member Data Documentation
api_
const PJRT_Api* lczero::PjrtCommon::api_ protected
Definition at line 151 of file pjrt.h.
Referenced by lczero::Pjrt::ApiVersion(), lczero::PjrtEvent::Await(), lczero::PjrtHostToDeviceTransfer::AwaitAndReleaseBuffer(), CheckError(), lczero::PjrtClient::CompileHlo(), lczero::Pjrt::CreateClient(), DestroyErrorMessage(), lczero::PjrtDeviceBuffer::DeviceToHost(), lczero::PjrtExecutable::ExecuteBlocking(), lczero::Pjrt::GetAttributes(), lczero::PjrtClient::GetDevices(), lczero::PjrtDeviceBuffer::GetDimensions(), GetErrorMessage(), lczero::PjrtDeviceBuffer::GetSize(), lczero::PjrtDeviceBuffer::GetType(), lczero::PjrtClient::HostToDevice(), lczero::Pjrt::Initialize(), lczero::Pjrt::Pjrt(), lczero::PjrtDevice::PjrtDevice(), lczero::PjrtExecutable::PjrtExecutable(), lczero::PjrtDevice::ToString(), lczero::PjrtClient::~PjrtClient(), lczero::PjrtDeviceBuffer::~PjrtDeviceBuffer(), lczero::PjrtEvent::~PjrtEvent(), lczero::PjrtExecutable::~PjrtExecutable(), and lczero::PjrtHostToDeviceTransfer::~PjrtHostToDeviceTransfer().
The documentation for this class was generated from the following files:
src/neural/backends/xla/pjrt.h
src/neural/backends/xla/pjrt.cc