Leela Chess Zero: lczero::ChessBoard::Castlings Class Reference
lczero::ChessBoard::Castlings Class Reference
#include <board.h>
Public Member Functions
Castlings ()
void set_we_can_00 ()
void set_we_can_000 ()
void set_they_can_00 ()
void set_they_can_000 ()
void reset_we_can_00 ()
void reset_we_can_000 ()
void reset_they_can_00 ()
void reset_they_can_000 ()
bool we_can_00 () const
bool we_can_000 () const
bool they_can_00 () const
bool they_can_000 () const
bool no_legal_castle () const
void Mirror ()
std::string as_string () const
std::string DebugString () const
uint8_t as_int () const
bool operator== (const Castlings &other) const =default
Public Attributes
File our_queenside_rook
File their_queenside_rook
File our_kingside_rook
File their_kingside_rook
Private Attributes
uint8_t data_
Detailed Description
Definition at line 123 of file board.h.
Constructor & Destructor Documentation
Castlings()
lczero::ChessBoard::Castlings::Castlings () inline
Definition at line 125 of file board.h.
Member Function Documentation
as_int()
uint8_t lczero::ChessBoard::Castlings::as_int () const inline
Definition at line 191 of file board.h.
References data_.
Referenced by lczero::EncodePositionForNN(), and lczero::ChessBoard::Hash().
as_string()
std::string lczero::ChessBoard::Castlings::as_string () const inline
Definition at line 157 of file board.h.
References data_, lczero::kFileA, lczero::kFileH, our_kingside_rook, our_queenside_rook, result, their_kingside_rook, their_queenside_rook, they_can_00(), they_can_000(), lczero::File::ToString(), we_can_00(), and we_can_000().
Referenced by lczero::BoardToFen(), and lczero::PopulateBoard().
DebugString()
std::string lczero::ChessBoard::Castlings::DebugString () const inline
Definition at line 175 of file board.h.
References data_, our_kingside_rook, our_queenside_rook, result, their_kingside_rook, their_queenside_rook, they_can_00(), they_can_000(), lczero::File::ToString(), we_can_00(), and we_can_000().
Mirror()
void lczero::ChessBoard::Castlings::Mirror () inline
Definition at line 148 of file board.h.
References data_, our_kingside_rook, our_queenside_rook, their_kingside_rook, and their_queenside_rook.
Referenced by lczero::ChessBoard::Mirror(), and lczero::PopulateBoard().
no_legal_castle()
bool lczero::ChessBoard::Castlings::no_legal_castle () const inline
Definition at line 146 of file board.h.
References data_.
operator==()
bool lczero::ChessBoard::Castlings::operator== (const Castlings & other) const default
reset_they_can_00()
void lczero::ChessBoard::Castlings::reset_they_can_00 () inline
Definition at line 139 of file board.h.
References data_.
Referenced by lczero::ChessBoard::ApplyMove().
reset_they_can_000()
void lczero::ChessBoard::Castlings::reset_they_can_000 () inline
Definition at line 140 of file board.h.
References data_.
Referenced by lczero::ChessBoard::ApplyMove().
reset_we_can_00()
void lczero::ChessBoard::Castlings::reset_we_can_00 () inline
Definition at line 137 of file board.h.
References data_.
Referenced by lczero::ChessBoard::ApplyMove().
reset_we_can_000()
void lczero::ChessBoard::Castlings::reset_we_can_000 () inline
Definition at line 138 of file board.h.
References data_.
Referenced by lczero::ChessBoard::ApplyMove().
set_they_can_00()
void lczero::ChessBoard::Castlings::set_they_can_00 () inline
Definition at line 134 of file board.h.
References data_.
Referenced by lczero::PopulateBoard(), and lczero::ChessBoard::SetFromFen().
set_they_can_000()
void lczero::ChessBoard::Castlings::set_they_can_000 () inline
Definition at line 135 of file board.h.
References data_.
Referenced by lczero::PopulateBoard(), and lczero::ChessBoard::SetFromFen().
set_we_can_00()
void lczero::ChessBoard::Castlings::set_we_can_00 () inline
Definition at line 132 of file board.h.
References data_.
Referenced by lczero::PopulateBoard(), and lczero::ChessBoard::SetFromFen().
set_we_can_000()
void lczero::ChessBoard::Castlings::set_we_can_000 () inline
Definition at line 133 of file board.h.
References data_.
Referenced by lczero::PopulateBoard(), and lczero::ChessBoard::SetFromFen().
they_can_00()
bool lczero::ChessBoard::Castlings::they_can_00 () const inline
Definition at line 144 of file board.h.
References data_.
Referenced by as_string(), DebugString(), and lczero::EncodePositionForNN().
they_can_000()
bool lczero::ChessBoard::Castlings::they_can_000 () const inline
Definition at line 145 of file board.h.
References data_.
Referenced by as_string(), DebugString(), and lczero::EncodePositionForNN().
we_can_00()
bool lczero::ChessBoard::Castlings::we_can_00 () const inline
Definition at line 142 of file board.h.
References data_.
Referenced by as_string(), DebugString(), lczero::EncodePositionForNN(), and lczero::ChessBoard::GeneratePseudolegalMoves().
we_can_000()
bool lczero::ChessBoard::Castlings::we_can_000 () const inline
Definition at line 143 of file board.h.
References data_.
Referenced by as_string(), DebugString(), lczero::EncodePositionForNN(), and lczero::ChessBoard::GeneratePseudolegalMoves().
Member Data Documentation
data_
uint8_t lczero::ChessBoard::Castlings::data_ private
Definition at line 206 of file board.h.
Referenced by as_int(), as_string(), DebugString(), Mirror(), no_legal_castle(), reset_they_can_00(), reset_they_can_000(), reset_we_can_00(), reset_we_can_000(), set_they_can_00(), set_they_can_000(), set_we_can_00(), set_we_can_000(), they_can_00(), they_can_000(), we_can_00(), and we_can_000().
our_kingside_rook
File lczero::ChessBoard::Castlings::our_kingside_rook
Definition at line 198 of file board.h.
Referenced by lczero::ChessBoard::ApplyMove(), as_string(), DebugString(), lczero::ChessBoard::GeneratePseudolegalMoves(), Mirror(), lczero::PopulateBoard(), lczero::PgnReader::SanToMove(), and lczero::ChessBoard::SetFromFen().
our_queenside_rook
File lczero::ChessBoard::Castlings::our_queenside_rook
Definition at line 195 of file board.h.
Referenced by lczero::ChessBoard::ApplyMove(), as_string(), DebugString(), lczero::ChessBoard::GeneratePseudolegalMoves(), Mirror(), lczero::PopulateBoard(), lczero::PgnReader::SanToMove(), and lczero::ChessBoard::SetFromFen().
their_kingside_rook
File lczero::ChessBoard::Castlings::their_kingside_rook
Definition at line 199 of file board.h.
Referenced by lczero::ChessBoard::ApplyMove(), as_string(), DebugString(), Mirror(), lczero::PopulateBoard(), and lczero::ChessBoard::SetFromFen().
their_queenside_rook
File lczero::ChessBoard::Castlings::their_queenside_rook
Definition at line 196 of file board.h.
Referenced by lczero::ChessBoard::ApplyMove(), as_string(), DebugString(), Mirror(), lczero::PopulateBoard(), and lczero::ChessBoard::SetFromFen().
The documentation for this class was generated from the following file:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/chess/board.h