Leela Chess Zero: lczero::python::Backend Class Reference
lczero::python::Backend Class Reference
#include <weights.h>
Public Member Functions
Backend (const Weights *weights, const std::optional< std::string > &backend, const std::optional< std::string > &options)
BackendCapabilities capabilities () const
std::vector< std::unique_ptr< Output > > evaluate (const std::vector< Input * > &inputs) const
Static Public Member Functions
static std::vector< std::string > available_backends ()
Private Attributes
std::unique_ptr<::lczero::Network > network_
Detailed Description
Definition at line 192 of file weights.h.
Constructor & Destructor Documentation
Backend()
lczero::python::Backend::Backend (const Weights * weights, const std::optional< std::string > & backend, const std::optional< std::string > & options) inline
Definition at line 199 of file weights.h.
References lczero::OptionsDict::AddSubdictFromString(), lczero::NetworkFactory::Create(), lczero::NetworkFactory::Get(), lczero::python::GetAvailableBackends(), network_, and lczero::python::Weights::weights().
Member Function Documentation
available_backends()
static std::vector< std::string > lczero::python::Backend::available_backends () inline static
Definition at line 195 of file weights.h.
References lczero::NetworkFactory::Get(), and lczero::NetworkFactory::GetBackendsList().
capabilities()
BackendCapabilities lczero::python::Backend::capabilities () const inline
Definition at line 211 of file weights.h.
References network_.
Referenced by lczero::python::GameState::as_input().
evaluate()
std::vector< std::unique_ptr< Output > > lczero::python::Backend::evaluate (const std::vector< Input * > & inputs) const inline
Definition at line 215 of file weights.h.
References input, network_, and result.
Member Data Documentation
network_
std::unique_ptr<::lczero::Network> lczero::python::Backend::network_ private
Definition at line 232 of file weights.h.
Referenced by Backend(), capabilities(), and evaluate().
The documentation for this class was generated from the following file:
src/python/weights.h