Leela Chess Zero: lczero::HashKeyedCache< V > Class Template Reference
lczero::HashKeyedCache< V > Class Template Reference abstract
#include <cache.h>
Classes
struct Entry
Public Member Functions
HashKeyedCache (int capacity=128)
~HashKeyedCache ()
void Insert (uint64_t key, std::unique_ptr< V > val)
bool ContainsKey (uint64_t key)
V * LookupAndPin (uint64_t key)
void Unpin (uint64_t key, V *value)
void SetCapacity (int capacity)
void Clear ()
int GetSize () const
int GetCapacity () const
Static Public Member Functions
static constexpr size_t GetItemStructSize ()
Private Member Functions
void EvictItem () REQUIRES(mutex_)
bool InRange (size_t target, size_t start, size_t end)
void EvictToCapacity (int capacity) REQUIRES(mutex_)
int size_ GUARDED_BY (mutex_)=0
int allocated_ GUARDED_BY (mutex_)=0
std::deque< uint64_t > GUARDED_BY (mutex_) insertion_order_
std::vector< Entry > GUARDED_BY (mutex_) evicted_
std::vector< Entry > GUARDED_BY (mutex_) hash_
Private Attributes
std::atomic< int > capacity_
SpinMutex mutex_
Static Private Attributes
static const double constexpr kLoadFactor = 1.9
Detailed Description
template<class V>
class lczero::HashKeyedCache< V >
Definition at line 50 of file cache.h.
Constructor & Destructor Documentation
HashKeyedCache()
template<class V > lczero::HashKeyedCache< V >::HashKeyedCache (int capacity = 128) inline
Definition at line 54 of file cache.h.
~HashKeyedCache()
template<class V > lczero::HashKeyedCache< V >::~HashKeyedCache () inline
Definition at line 58 of file cache.h.
References lczero::HashKeyedCache< V >::EvictToCapacity().
Member Function Documentation
Clear()
template<class V > void lczero::HashKeyedCache< V >::Clear () inline
Definition at line 200 of file cache.h.
References lczero::HashKeyedCache< V >::EvictToCapacity(), and lczero::HashKeyedCache< V >::mutex_.
ContainsKey()
template<class V > bool lczero::HashKeyedCache< V >::ContainsKey (uint64_t key) inline
Definition at line 94 of file cache.h.
References lczero::HashKeyedCache< V >::capacity_, idx, key, and lczero::HashKeyedCache< V >::mutex_.
EvictItem()
template<class V > void lczero::HashKeyedCache< V >::EvictItem () inline private
Definition at line 223 of file cache.h.
References idx, lczero::HashKeyedCache< V >::InRange(), key, and value.
Referenced by lczero::HashKeyedCache< V >::EvictToCapacity().
EvictToCapacity()
template<class V > void lczero::HashKeyedCache< V >::EvictToCapacity (int capacity) inline private
Definition at line 269 of file cache.h.
References lczero::HashKeyedCache< V >::EvictItem().
Referenced by lczero::HashKeyedCache< V >::Clear(), lczero::HashKeyedCache< V >::Insert(), lczero::HashKeyedCache< V >::SetCapacity(), and lczero::HashKeyedCache< V >::~HashKeyedCache().
GetCapacity()
template<class V > int lczero::HashKeyedCache< V >::GetCapacity () const inline
Definition at line 209 of file cache.h.
References lczero::HashKeyedCache< V >::capacity_.
GetItemStructSize()
template<class V > static constexpr size_t lczero::HashKeyedCache< V >::GetItemStructSize () inline static constexpr
Definition at line 210 of file cache.h.
GetSize()
template<class V > int lczero::HashKeyedCache< V >::GetSize () const inline
Definition at line 205 of file cache.h.
References lczero::HashKeyedCache< V >::mutex_.
GUARDED_BY() [1/5]
template<class V > std::vector< Entry > lczero::HashKeyedCache< V >::GUARDED_BY (mutex_) private
GUARDED_BY() [2/5]
template<class V > std::vector< Entry > lczero::HashKeyedCache< V >::GUARDED_BY (mutex_) private
GUARDED_BY() [3/5]
template<class V > std::deque< uint64_t > lczero::HashKeyedCache< V >::GUARDED_BY (mutex_) private
GUARDED_BY() [4/5]
template<class V > int size_ lczero::HashKeyedCache< V >::GUARDED_BY (mutex_) private pure virtual
GUARDED_BY() [5/5]
template<class V > int allocated_ lczero::HashKeyedCache< V >::GUARDED_BY (mutex_) private pure virtual
InRange()
template<class V > bool lczero::HashKeyedCache< V >::InRange (size_t target, size_t start, size_t end) inline private
Definition at line 261 of file cache.h.
Referenced by lczero::HashKeyedCache< V >::EvictItem().
Insert()
template<class V > void lczero::HashKeyedCache< V >::Insert (uint64_t key, std::unique_ptr< V > val) inline
Definition at line 66 of file cache.h.
References lczero::HashKeyedCache< V >::capacity_, lczero::HashKeyedCache< V >::EvictToCapacity(), idx, key, and lczero::HashKeyedCache< V >::mutex_.
LookupAndPin()
template<class V > V * lczero::HashKeyedCache< V >::LookupAndPin (uint64_t key) inline
Definition at line 113 of file cache.h.
References lczero::HashKeyedCache< V >::capacity_, idx, key, and lczero::HashKeyedCache< V >::mutex_.
SetCapacity()
template<class V > void lczero::HashKeyedCache< V >::SetCapacity (int capacity) inline
Definition at line 166 of file cache.h.
References lczero::HashKeyedCache< V >::capacity_, lczero::HashKeyedCache< V >::EvictToCapacity(), idx, lczero::HashKeyedCache< V >::kLoadFactor, and lczero::HashKeyedCache< V >::mutex_.
Unpin()
template<class V > void lczero::HashKeyedCache< V >::Unpin (uint64_t key, V * value) inline
Definition at line 133 of file cache.h.
References idx, key, lczero::HashKeyedCache< V >::mutex_, and value.
Member Data Documentation
capacity_
template<class V > std::atomic<int> lczero::HashKeyedCache< V >::capacity_ private
Definition at line 276 of file cache.h.
Referenced by lczero::HashKeyedCache< V >::ContainsKey(), lczero::HashKeyedCache< V >::GetCapacity(), lczero::HashKeyedCache< V >::Insert(), lczero::HashKeyedCache< V >::LookupAndPin(), and lczero::HashKeyedCache< V >::SetCapacity().
kLoadFactor
template<class V > const double constexpr lczero::HashKeyedCache< V >::kLoadFactor = 1.9 static constexpr private
Definition at line 51 of file cache.h.
Referenced by lczero::HashKeyedCache< V >::SetCapacity().
mutex_
template<class V > SpinMutex lczero::HashKeyedCache< V >::mutex_ mutable private
Definition at line 284 of file cache.h.
Referenced by lczero::HashKeyedCache< V >::Clear(), lczero::HashKeyedCache< V >::ContainsKey(), lczero::HashKeyedCache< V >::GetSize(), lczero::HashKeyedCache< V >::Insert(), lczero::HashKeyedCache< V >::LookupAndPin(), lczero::HashKeyedCache< V >::SetCapacity(), and lczero::HashKeyedCache< V >::Unpin().
The documentation for this class was generated from the following file:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/cache.h