Leela Chess Zero: lczero::PjrtDeviceBuffer Class Reference
lczero::PjrtDeviceBuffer Class Reference
Represents a buffer in device memory.
#include <pjrt.h>
Public Member Functions
PjrtDeviceBuffer (const PJRT_Api *api, PJRT_Buffer *buffer)
~PjrtDeviceBuffer ()
size_t GetSize () const
Returns the size of the buffer in bytes.
std::unique_ptr< PjrtEvent > DeviceToHost (void *dst, size_t size)
Starts an asynchronous copy from the device to the host memory.
PjrtType GetType () const
std::vector< int64_t > GetDimensions () const
Private Attributes
PJRT_Buffer * buffer_
Friends
class PjrtExecutable
Additional Inherited Members
Protected Member Functions inherited from lczero::PjrtCommon
PjrtCommon (const PJRT_Api *api)
virtual ~PjrtCommon ()=default
std::string GetErrorMessage (PJRT_Error *error) const
void DestroyErrorMessage (PJRT_Error *error) const
void CheckError (PJRT_Error *error) const
Protected Attributes inherited from lczero::PjrtCommon
const PJRT_Api * api_
Detailed Description
Represents a buffer in device memory.
Definition at line 179 of file pjrt.h.
Constructor & Destructor Documentation
PjrtDeviceBuffer()
lczero::PjrtDeviceBuffer::PjrtDeviceBuffer (const PJRT_Api * api, PJRT_Buffer * buffer)
Definition at line 257 of file pjrt.cc.
~PjrtDeviceBuffer()
lczero::PjrtDeviceBuffer::~PjrtDeviceBuffer ()
Definition at line 260 of file pjrt.cc.
References lczero::PjrtCommon::api_, buffer_, and lczero::PjrtCommon::CheckError().
Member Function Documentation
DeviceToHost()
std::unique_ptr< PjrtEvent > lczero::PjrtDeviceBuffer::DeviceToHost (void * dst, size_t size)
Starts an asynchronous copy from the device to the host memory.
Definition at line 287 of file pjrt.cc.
References lczero::PjrtCommon::api_, buffer_, and lczero::PjrtCommon::CheckError().
GetDimensions()
std::vector< int64_t > lczero::PjrtDeviceBuffer::GetDimensions () const
Definition at line 280 of file pjrt.cc.
References lczero::PjrtCommon::api_, buffer_, and lczero::PjrtCommon::CheckError().
GetSize()
size_t lczero::PjrtDeviceBuffer::GetSize () const
Returns the size of the buffer in bytes.
Definition at line 266 of file pjrt.cc.
References lczero::PjrtCommon::api_, buffer_, and lczero::PjrtCommon::CheckError().
GetType()
PjrtType lczero::PjrtDeviceBuffer::GetType () const
Definition at line 273 of file pjrt.cc.
References lczero::PjrtCommon::api_, buffer_, and lczero::PjrtCommon::CheckError().
Friends And Related Symbol Documentation
PjrtExecutable
friend class PjrtExecutable friend
Definition at line 192 of file pjrt.h.
Member Data Documentation
buffer_
PJRT_Buffer* lczero::PjrtDeviceBuffer::buffer_ private
Definition at line 191 of file pjrt.h.
Referenced by DeviceToHost(), GetDimensions(), GetSize(), GetType(), and ~PjrtDeviceBuffer().
The documentation for this class was generated from the following files:
src/neural/backends/xla/pjrt.h
src/neural/backends/xla/pjrt.cc