Leela Chess Zero: lczero::dag_classic::ReleaseNodesWork Class Reference
lczero::dag_classic::ReleaseNodesWork Class Reference
Helper class for thread-local release queues.
#include <node.h>
Public Member Functions
ReleaseNodesWork (bool gc_thread=false)
~ReleaseNodesWork ()
bool IsWorker () const
void emplace_back (std::unique_ptr< Node > &&node)
bool empty () const
void swap (ReleaseNodesWork &other)
Private Member Functions
void Submit ()
Private Attributes
std::vector< std::unique_ptr< Node > > released_nodes_
bool is_gc_thread_
Static Private Attributes
static constexpr size_t kCapacity = 32
Detailed Description
Helper class for thread-local release queues.
Definition at line 1095 of file node.h.
Constructor & Destructor Documentation
ReleaseNodesWork()
lczero::dag_classic::ReleaseNodesWork::ReleaseNodesWork (bool gc_thread = false)
Definition at line 934 of file node.cc.
References kCapacity, and released_nodes_.
~ReleaseNodesWork()
lczero::dag_classic::ReleaseNodesWork::~ReleaseNodesWork ()
Definition at line 956 of file node.cc.
References Submit().
Member Function Documentation
emplace_back()
void lczero::dag_classic::ReleaseNodesWork::emplace_back (std::unique_ptr< Node > && node)
Definition at line 940 of file node.cc.
References is_gc_thread_, kCapacity, released_nodes_, and swap().
empty()
bool lczero::dag_classic::ReleaseNodesWork::empty () const
Definition at line 949 of file node.cc.
References released_nodes_.
IsWorker()
bool lczero::dag_classic::ReleaseNodesWork::IsWorker () const
Definition at line 938 of file node.cc.
References is_gc_thread_.
Referenced by Submit(), and swap().
Submit()
void lczero::dag_classic::ReleaseNodesWork::Submit () private
Definition at line 958 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::Instance(), IsWorker(), and released_nodes_.
Referenced by ~ReleaseNodesWork().
swap()
void lczero::dag_classic::ReleaseNodesWork::swap (ReleaseNodesWork & other)
Definition at line 951 of file node.cc.
References IsWorker(), and released_nodes_.
Referenced by emplace_back(), lczero::dag_classic::NodeGarbageCollector::GCThread(), and lczero::dag_classic::NodeGarbageCollector::NotifyThreadGoingSleep().
Member Data Documentation
is_gc_thread_
bool lczero::dag_classic::ReleaseNodesWork::is_gc_thread_ private
Definition at line 1117 of file node.h.
Referenced by emplace_back(), and IsWorker().
kCapacity
constexpr size_t lczero::dag_classic::ReleaseNodesWork::kCapacity = 32 static constexpr private
Definition at line 1096 of file node.h.
Referenced by emplace_back(), and ReleaseNodesWork().
released_nodes_
std::vector<std::unique_ptr<Node> > lczero::dag_classic::ReleaseNodesWork::released_nodes_ private
Definition at line 1116 of file node.h.
Referenced by emplace_back(), empty(), ReleaseNodesWork(), Submit(), and swap().
The documentation for this class was generated from the following files:
src/search/dag_classic/node.h
src/search/dag_classic/node.cc