Leela Chess Zero: lczero::dag_classic::Node Class Reference
lczero::dag_classic::Node Class Reference
Represents an expanded edge in the search DAG.
A Node corresponds to an edge in the graph that has been visited. It wraps an Edge (which contains the move and policy) and adds Monte Carlo statistics such as visit count (N), value (Q), and virtual loss.
Crucially, a Node links to a LowNode, which represents the resulting position. Multiple Nodes from different parents can point to the same LowNode, forming the DAG structure that handles transpositions.
#include <node.h>
Classes
struct VisitorId
Public Types
using Iterator = Edge_Iterator< false >
using ConstIterator = Edge_Iterator< true >
Public Member Functions
Node (uint16_t index)
Constructs a node with a specific index in the parent's edge list.
Node (const Edge &edge, uint16_t index)
Constructs a node from an Edge object.
~Node ()
void Trim ()
Trims the node, resetting statistics but keeping structure.
Node * CreateSingleChildNode (Move move)
Allocates a new edge and a new node.
Node * GetChild () const
Gets the first child (sibling in the linked list of children).
Returns a pointer to the first Node in the linked list of children. This list corresponds to the edges leading out of the underlying position (LowNode).
atomic_unique_ptr< Node > * GetSibling ()
Gets pointer to the next sibling node.
Returns a pointer to the next Node in the linked list of edges for the parent position.
void MoveSiblingIn (std::unique_ptr< Node > &sibling)
Moves a sibling node into this node's sibling chain.
bool HasChildren () const
Returns whether the node has a LowNode attached (children).
A node has children if it points to a valid LowNode which contains the next set of legal moves.
float GetVisitedPolicy () const
Returns sum of policy priors of visited children.
Used during selection to normalize policy probabilities of visited nodes against the total policy mass of visited nodes.
uint32_t GetN () const
Returns the visit count of this node/edge.
This is the 'N' value in MCTS, representing how many times this edge has been traversed.
uint32_t GetNInFlight () const
Returns the number of threads currently visiting this node (virtual loss).
Virtual loss is used to discourage other threads from exploring the exact same path simultaneously, promoting diversity in parallel search.
uint32_t GetChildrenVisits () const
Returns the total visits of all children.
uint32_t GetTotalVisits () const
Returns the total visits passed through this node.
int GetNStarted () const
Returns N + N_in_flight (visits committed + visits in progress).
float GetQ (float draw_score) const
Calculates the Q-value (action value) of the node.
The Q-value represents the expected result of taking this action (move). It is a weighted combination of the win/loss score (WL) and the draw probability (D), adjusted by the draw score.
@param draw_score The value assigned to a draw (typically 0.0 or 0.5 depending on configuration). @return The computed Q-value.
float GetWL () const
Returns the average Win-Loss score.
float GetD () const
Returns the average Draw probability.
float GetM () const
Returns the estimated moves remaining.
bool IsTerminal () const
Returns whether the node is terminal (game end).
bool IsTbTerminal () const
Returns whether the node is a tablebase terminal.
Bounds GetBounds () const
Returns min/max bounds of the value.
uint8_t GetNumEdges () const
Returns the number of edges from the underlying LowNode.
void MakeTerminal (GameResult result, float plies_left=1.0f, Terminal type=Terminal::EndOfGame)
Marks the node as terminal.
void MakeNotTerminal (bool also_low_node=true)
Marks the node as non-terminal, recomputing stats.
void SetBounds (GameResult lower, GameResult upper)
Sets the lower and upper bounds of the value.
bool TryStartScoreUpdate ()
Attempts to start a score update by incrementing virtual loss.
This is an atomic operation. It tries to increment the `n_in_flight_` counter to signal that a thread is processing this node. This helps in parallel search to coordinate multiple threads.
@return True if the update was started successfully.
void CancelScoreUpdate (uint32_t multivisit)
Cancels a score update (decrements virtual loss).
void FinalizeScoreUpdate (float v, float d, float m, uint32_t multivisit)
Finalizes score update with new backpropagated values.
Updates the node's statistics (WL, D, M) with the results from a simulation (or neural net evaluation). This is done atomically or with locks to ensure thread safety.
@param v The win/loss value to mix in. @param d The draw probability to mix in. @param m The moves left estimate to mix in. @param multivisit The number of visits to add (usually 1).
void AdjustForTerminal (float v, float d, float m, uint32_t multivisit)
Adjusts value statistics for terminal nodes.
void IncrementNInFlight (uint32_t multivisit)
Manually increments in-flight count (virtual loss).
ConstIterator Edges () const
Returns an iterator range for potential edges.
Iterator Edges ()
VisitedNode_Iterator< true > VisitedNodes () const
Returns an iterator range for child nodes that have been visited.
VisitedNode_Iterator< false > VisitedNodes ()
void ReleaseChildrenExceptOne (Node *node_to_save) const
Deletes all children except the specified one.
Move GetMove (bool as_opponent=false) const
Returns move from the point of view of the player making it.
float GetP () const
Returns Move policy prior from neural net.
void SetP (float val)
Sets Move policy prior.
const std::shared_ptr< LowNode > & GetLowNode () const
Gets shared pointer to the underlying LowNode (position).
The `LowNode` contains the actual game position data and legal moves. If this returns null, the node is a leaf that hasn't been expanded yet (or is terminal).
void SetLowNode (std::shared_ptr< LowNode > low_node)
Sets the underlying LowNode.
void UnsetLowNode ()
Clears the underlying LowNode.
std::string DebugString () const
Returns debug info string.
void DotEdgeString (std::ofstream &file, bool as_opponent=false, const LowNode *parent=nullptr) const
Generates Graphviz dot string for the edge to the LowNode.
void DotGraphString (std::ofstream &file, bool as_opponent=false) const
Generates Graphviz dot string for the subgraph starting at this node.
bool ZeroNInFlight () const
Debug check for zero in-flight visits.
void SortEdges () const
uint16_t Index () const
void SetRepetition ()
bool IsRepetition () const
bool WLDMInvariantsHold () const
Private Attributes
std::shared_ptr< LowNode > low_node_
double wl_ = 0.0f
double d_ = 0.0f
atomic_unique_ptr< Node > sibling_
float m_ = 0.0f
uint32_t n_ = 0
std::atomic< uint32_t > n_in_flight_ = 0
Edge edge_
uint16_t index_
Terminal terminal_type_: 2
GameResult lower_bound_: 2
GameResult upper_bound_: 2
bool repetition_: 1
Detailed Description
Represents an expanded edge in the search DAG.
A Node corresponds to an edge in the graph that has been visited. It wraps an Edge and adds Monte Carlo statistics (visits, value) and links to the resulting position (LowNode).
Nodes are the primary building blocks of the search tree. They are stored in a NodeTree and are managed by a NodeGarbageCollector to ensure thread safety during deletion.
Definition at line 266 of file node.h.
Member Typedef Documentation
ConstIterator
using lczero::dag_classic::Node::ConstIterator = Edge_Iterator<true>
Definition at line 269 of file node.h.
Iterator
using lczero::dag_classic::Node::Iterator = Edge_Iterator<false>
Definition at line 268 of file node.h.
Constructor & Destructor Documentation
Node() [1/2]
lczero::dag_classic::Node::Node (uint16_t index) inline
Constructs a node with a specific index in the parent's edge list.
Parameters
index Index of the edge in parent's MoveList.
Definition at line 273 of file node.h.
Node() [2/2]
lczero::dag_classic::Node::Node (const Edge & edge, uint16_t index) inline
Constructs a node from an Edge object.
Parameters
edge The edge data (move, policy).
index Index of the edge.
Definition at line 283 of file node.h.
~Node()
lczero::dag_classic::Node::~Node ()
Definition at line 151 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::AddToGcQueue(), lczero::dag_classic::NodeGarbageCollector::Instance(), sibling_, and UnsetLowNode().
Member Function Documentation
AdjustForTerminal()
void lczero::dag_classic::Node::AdjustForTerminal (float v, float d, float m, uint32_t multivisit)
Adjusts value statistics for terminal nodes.
Updates the node's value estimation when a terminal state (win/loss/draw) is reached or propagated. This ensures the search tree reflects the game-theoretic result.
Definition at line 399 of file node.cc.
References d, d_, m, m_, n_, wl_, and WLDMInvariantsHold().
CancelScoreUpdate()
void lczero::dag_classic::Node::CancelScoreUpdate (uint32_t multivisit)
Cancels a score update (decrements virtual loss).
Used when a search path is aborted or when reverting a virtual loss. It decrements the play count and virtual loss count consistent with the multivisit parameter.
Parameters
multivisit Amount to decrement.
Definition at line 349 of file node.cc.
References GetNInFlight(), and n_in_flight_.
CreateSingleChildNode()
Node * lczero::dag_classic::Node::CreateSingleChildNode (Move move) inline
Allocates a new edge and a new node.
Creates a single child node for the specified move. This is typically used when extending the tree along a forced line or a single line of play (e.g. root moves).
The node must not have children before this call.
Parameters
move The move leading to the new child.
Returns
Pointer to the newly created child node.
Definition at line 299 of file node.h.
References GetChild(), low_node_, and SetLowNode().
Referenced by lczero::dag_classic::NodeTree::MakeMove().
DebugString()
std::string lczero::dag_classic::Node::DebugString () const
Returns debug info string.
Definition at line 183 of file node.cc.
References d_, GetMove(), GetNInFlight(), GetP(), index_, low_node_, lower_bound_, m_, n_, sibling_, terminal_type_, lczero::Move::ToString(), upper_bound_, and wl_.
Referenced by WLDMInvariantsHold(), lczero::dag_classic::LowNode::WLDMInvariantsHold(), and ZeroNInFlight().
DotEdgeString()
void lczero::dag_classic::Node::DotEdgeString (std::ofstream & file, bool as_opponent = false, const LowNode * parent = nullptr) const
Generates Graphviz dot string for the edge to the LowNode.
Parameters
file Output stream.
as_opponent Whether to view as opponent.
parent Pointer to parent LowNode for context.
Definition at line 550 of file node.cc.
References d_, GetMove(), GetNInFlight(), GetP(), index_, low_node_, lower_bound_, m_, n_, lczero::dag_classic::PtrToNodeName(), sibling_, terminal_type_, lczero::Move::ToString(), upper_bound_, and wl_.
Referenced by DotGraphString().
DotGraphString()
void lczero::dag_classic::Node::DotGraphString (std::ofstream & file, bool as_opponent = false) const
Generates Graphviz dot string for the subgraph starting at this node.
Definition at line 578 of file node.cc.
References DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), GetN(), and lczero::dag_classic::TreeWalk().
Edges() [1/2]
Node::Iterator lczero::dag_classic::Node::Edges () inline
Definition at line 978 of file node.h.
References GetLowNode().
Edges() [2/2]
Node::ConstIterator lczero::dag_classic::Node::Edges () const inline
Returns an iterator range for potential edges.
Definition at line 975 of file node.h.
References GetLowNode().
Referenced by lczero::dag_classic::Search::GetBestChildrenNoTemperature(), lczero::dag_classic::Search::GetVerboseStats(), lczero::dag_classic::LowNode::MakeNotTerminal(), lczero::dag_classic::Search::SendMovesStats(), and lczero::dag_classic::TreeWalk().
FinalizeScoreUpdate()
void lczero::dag_classic::Node::FinalizeScoreUpdate (float v, float d, float m, uint32_t multivisit)
Finalizes score update with new backpropagated values.
Parameters
v Value to add/update.
d Draw probability to add/update.
m Moves estimate to add/update.
multivisit Number of visits to add.
Definition at line 383 of file node.cc.
References d, d_, GetNInFlight(), m, m_, n_, n_in_flight_, wl_, and WLDMInvariantsHold().
GetBounds()
Bounds lczero::dag_classic::Node::GetBounds () const inline
Returns min/max bounds of the value.
Definition at line 360 of file node.h.
References lower_bound_, and upper_bound_.
Referenced by lczero::dag_classic::EdgeAndNode::GetBounds(), and lczero::dag_classic::SearchWorker::ShouldStopPickingHere().
GetChild()
Node * lczero::dag_classic::Node::GetChild () const
Gets the first child (sibling in the linked list of children).
Definition at line 156 of file node.cc.
References GetChild(), and low_node_.
Referenced by CreateSingleChildNode(), GetChild(), and lczero::dag_classic::NodeTree::MakeMove().
GetChildrenVisits()
uint32_t lczero::dag_classic::Node::GetChildrenVisits () const
Returns the total visits of all children.
Definition at line 173 of file node.cc.
References low_node_.
Referenced by lczero::dag_classic::Search::GetVerboseStats().
GetD()
float lczero::dag_classic::Node::GetD () const inline
Returns the average Draw probability.
Definition at line 348 of file node.h.
References d_.
Referenced by lczero::dag_classic::Search::GetBestEval(), lczero::dag_classic::EdgeAndNode::GetD(), lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition(), lczero::dag_classic::SearchWorker::ShouldStopPickingHere(), WLDMInvariantsHold(), and lczero::dag_classic::LowNode::WLDMInvariantsHold().
GetLowNode()
const std::shared_ptr< LowNode > & lczero::dag_classic::Node::GetLowNode () const inline
Gets shared pointer to the underlying LowNode (position).
Definition at line 425 of file node.h.
References low_node_.
Referenced by lczero::dag_classic::SearchWorker::NodeToProcess::CanEvalOutOfOrder(), lczero::dag_classic::SearchWorker::NodeToProcess::DebugString(), Edges(), Edges(), lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode(), lczero::dag_classic::SearchWorker::NodeToProcess::IsExtendable(), lczero::dag_classic::SearchWorker::ShouldStopPickingHere(), lczero::dag_classic::TreeWalk(), VisitedNodes(), and VisitedNodes().
GetM()
float lczero::dag_classic::Node::GetM () const inline
Returns the estimated moves remaining.
Definition at line 351 of file node.h.
References m_.
Referenced by lczero::dag_classic::Search::GetBestEval(), lczero::dag_classic::EdgeAndNode::GetM(), lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition(), lczero::dag_classic::SearchWorker::ShouldStopPickingHere(), WLDMInvariantsHold(), and lczero::dag_classic::LowNode::WLDMInvariantsHold().
GetMove()
Move lczero::dag_classic::Node::GetMove (bool as_opponent = false) const inline
Returns move from the point of view of the player making it.
Definition at line 414 of file node.h.
References edge_, and lczero::dag_classic::Edge::GetMove().
Referenced by DebugString(), and DotEdgeString().
GetN()
uint32_t lczero::dag_classic::Node::GetN () const inline
Returns the visit count of this node/edge.
Definition at line 324 of file node.h.
References n_.
Referenced by DotGraphString(), lczero::dag_classic::Search::EnsureBestMoveKnown(), lczero::dag_classic::Search::GetBestChildrenNoTemperature(), lczero::dag_classic::EdgeAndNode::GetD(), lczero::dag_classic::EdgeAndNode::GetM(), lczero::dag_classic::EdgeAndNode::GetN(), lczero::dag_classic::EdgeAndNode::GetQ(), lczero::dag_classic::Search::GetVerboseStats(), lczero::dag_classic::EdgeAndNode::GetWL(), lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition(), lczero::dag_classic::VisitedNode_Iterator< is_const >::operator++(), lczero::dag_classic::SearchWorker::ShouldStopPickingHere(), and lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
GetNInFlight()
uint32_t lczero::dag_classic::Node::GetNInFlight () const
Returns the number of threads currently visiting this node (virtual loss).
Definition at line 169 of file node.cc.
References n_in_flight_.
Referenced by CancelScoreUpdate(), DebugString(), DotEdgeString(), FinalizeScoreUpdate(), lczero::dag_classic::EdgeAndNode::GetNInFlight(), GetNStarted(), lczero::dag_classic::Search::GetVerboseStats(), lczero::dag_classic::VisitedNode_Iterator< is_const >::operator++(), and ZeroNInFlight().
GetNStarted()
int lczero::dag_classic::Node::GetNStarted () const inline
Returns N + N_in_flight (visits committed + visits in progress).
Definition at line 337 of file node.h.
References GetNInFlight(), and n_.
Referenced by lczero::dag_classic::EdgeAndNode::GetNStarted().
GetNumEdges()
uint8_t lczero::dag_classic::Node::GetNumEdges () const
Returns the number of edges from the underlying LowNode.
Definition at line 274 of file node.cc.
References low_node_.
Referenced by lczero::dag_classic::Search::GetVerboseStats(), and lczero::dag_classic::LowNode::MakeNotTerminal().
GetP()
float lczero::dag_classic::Node::GetP () const inline
Returns Move policy prior from neural net.
Definition at line 419 of file node.h.
References edge_, and lczero::dag_classic::Edge::GetP().
Referenced by DebugString(), DotEdgeString(), and lczero::dag_classic::EdgeAndNode::GetP().
GetQ()
float lczero::dag_classic::Node::GetQ (float draw_score) const inline
Calculates the Q-value (action value) of the node.
Parameters
draw_score Score to use for draws.
Returns
Q value adjusted for draw score.
Definition at line 342 of file node.h.
References d_, and wl_.
Referenced by lczero::dag_classic::EdgeAndNode::GetQ(), and lczero::dag_classic::Search::GetVerboseStats().
GetSibling()
atomic_unique_ptr< Node > * lczero::dag_classic::Node::GetSibling () inline
Gets pointer to the next sibling node.
Definition at line 310 of file node.h.
References sibling_.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), and lczero::dag_classic::VisitedNode_Iterator< is_const >::operator++().
GetTotalVisits()
uint32_t lczero::dag_classic::Node::GetTotalVisits () const
Returns the total visits passed through this node.
Definition at line 177 of file node.cc.
References low_node_.
Referenced by lczero::dag_classic::Search::GetVerboseStats().
GetVisitedPolicy()
float lczero::dag_classic::Node::GetVisitedPolicy () const
Returns sum of policy priors of visited children.
Definition at line 163 of file node.cc.
References VisitedNodes().
Referenced by lczero::dag_classic::Search::GetVerboseStats().
GetWL()
float lczero::dag_classic::Node::GetWL () const inline
Returns the average Win-Loss score.
Definition at line 345 of file node.h.
References wl_.
Referenced by lczero::dag_classic::Search::GetBestEval(), lczero::dag_classic::Search::GetVerboseStats(), lczero::dag_classic::EdgeAndNode::GetWL(), lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition(), lczero::dag_classic::SearchWorker::ShouldStopPickingHere(), WLDMInvariantsHold(), and lczero::dag_classic::LowNode::WLDMInvariantsHold().
HasChildren()
bool lczero::dag_classic::Node::HasChildren () const
Returns whether the node has a LowNode attached (children).
Definition at line 161 of file node.cc.
References HasChildren(), and low_node_.
Referenced by lczero::dag_classic::Search::EnsureBestMoveKnown(), lczero::dag_classic::Search::GetBestEval(), and HasChildren().
IncrementNInFlight()
void lczero::dag_classic::Node::IncrementNInFlight (uint32_t multivisit)
Manually increments in-flight count (virtual loss).
Parameters
multivisit Amount to increment.
Definition at line 411 of file node.cc.
References n_in_flight_.
Referenced by lczero::dag_classic::SearchWorker::PickNodesToExtendTask().
Index()
uint16_t lczero::dag_classic::Node::Index () const inline
Definition at line 453 of file node.h.
References index_.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Actualize().
IsRepetition()
bool lczero::dag_classic::Node::IsRepetition () const inline
Definition at line 456 of file node.h.
References repetition_.
IsTbTerminal()
bool lczero::dag_classic::Node::IsTbTerminal () const inline
Returns whether the node is a tablebase terminal.
Definition at line 357 of file node.h.
References lczero::dag_classic::Tablebase, and terminal_type_.
Referenced by lczero::dag_classic::EdgeAndNode::IsTbTerminal().
IsTerminal()
bool lczero::dag_classic::Node::IsTerminal () const inline
Returns whether the node is terminal (game end).
Definition at line 354 of file node.h.
References lczero::dag_classic::NonTerminal, and terminal_type_.
Referenced by lczero::dag_classic::SearchWorker::NodeToProcess::CanEvalOutOfOrder(), lczero::dag_classic::SearchWorker::NodeToProcess::IsExtendable(), lczero::dag_classic::EdgeAndNode::IsTerminal(), lczero::dag_classic::NodeTree::MakeMove(), MakeNotTerminal(), lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition(), and lczero::dag_classic::SearchWorker::ShouldStopPickingHere().
MakeNotTerminal()
void lczero::dag_classic::Node::MakeNotTerminal (bool also_low_node = true)
Marks the node as non-terminal, recomputing stats.
Reverts terminal status.
Parameters
also_low_node If true, propagate change to LowNode.
Definition at line 301 of file node.cc.
References lczero::BLACK_WON, d_, IsTerminal(), low_node_, lower_bound_, m_, n_, lczero::dag_classic::NonTerminal, repetition_, terminal_type_, upper_bound_, lczero::WHITE_WON, wl_, and WLDMInvariantsHold().
Referenced by lczero::dag_classic::NodeTree::MakeMove().
MakeTerminal()
void lczero::dag_classic::Node::MakeTerminal (GameResult result, float plies_left = 1.0f, Terminal type = Terminal::EndOfGame)
Marks the node as terminal.
Marks node as terminal.
Parameters
result The game result (Win/Loss/Draw).
plies_left Estimated plies left (usually 0 or 1 for terminals).
type Type of terminal (EndOfGame, Tablebase).
Definition at line 279 of file node.cc.
References lczero::BLACK_WON, d_, lczero::DRAW, m_, result, SetBounds(), SetP(), terminal_type_, type, lczero::WHITE_WON, wl_, and WLDMInvariantsHold().
Referenced by lczero::dag_classic::SearchWorker::ExtendNode(), and lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition().
MoveSiblingIn()
void lczero::dag_classic::Node::MoveSiblingIn (std::unique_ptr< Node > & sibling) inline
Moves a sibling node into this node's sibling chain.
Definition at line 313 of file node.h.
References sibling_.
ReleaseChildrenExceptOne()
void lczero::dag_classic::Node::ReleaseChildrenExceptOne (Node * node_to_save) const
Deletes all children except the specified one.
Deletes all children except one.
Parameters
node_to_save Pointer to the child node to preserve.
Definition at line 442 of file node.cc.
References low_node_.
SetBounds()
void lczero::dag_classic::Node::SetBounds (GameResult lower, GameResult upper)
Sets the lower and upper bounds of the value.
Definition at line 332 of file node.cc.
References lower_bound_, and upper_bound_.
Referenced by MakeTerminal(), and lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition().
SetLowNode()
void lczero::dag_classic::Node::SetLowNode (std::shared_ptr< LowNode > low_node)
Sets the underlying LowNode.
Definition at line 450 of file node.cc.
References low_node_.
Referenced by CreateSingleChildNode().
SetP()
void lczero::dag_classic::Node::SetP (float val) inline
Sets Move policy prior.
Definition at line 422 of file node.h.
References edge_, and lczero::dag_classic::Edge::SetP().
Referenced by MakeTerminal().
SetRepetition()
void lczero::dag_classic::Node::SetRepetition () inline
Definition at line 455 of file node.h.
References repetition_.
SortEdges()
void lczero::dag_classic::Node::SortEdges () const
Definition at line 622 of file node.cc.
References low_node_.
Trim()
void lczero::dag_classic::Node::Trim ()
Trims the node, resetting statistics but keeping structure.
Clears the node's stats and structure for reuse.
Definition at line 128 of file node.cc.
References lczero::BLACK_WON, d_, lower_bound_, m_, n_, n_in_flight_, lczero::dag_classic::NonTerminal, repetition_, terminal_type_, UnsetLowNode(), upper_bound_, lczero::WHITE_WON, and wl_.
Referenced by lczero::dag_classic::NodeTree::TrimTreeAtHead().
TryStartScoreUpdate()
bool lczero::dag_classic::Node::TryStartScoreUpdate ()
Attempts to start a score update by incrementing virtual loss.
Returns
True if successful (node allows updates), false otherwise.
Definition at line 337 of file node.cc.
References n_, and n_in_flight_.
Referenced by lczero::dag_classic::SearchWorker::PickNodesToExtendTask().
UnsetLowNode()
void lczero::dag_classic::Node::UnsetLowNode ()
Clears the underlying LowNode.
Definition at line 456 of file node.cc.
References low_node_.
Referenced by Trim(), and ~Node().
VisitedNodes() [1/2]
VisitedNode_Iterator< false > lczero::dag_classic::Node::VisitedNodes () inline
Definition at line 1046 of file node.h.
References GetLowNode().
VisitedNodes() [2/2]
VisitedNode_Iterator< true > lczero::dag_classic::Node::VisitedNodes () const inline
Returns an iterator range for child nodes that have been visited.
Definition at line 1043 of file node.h.
References GetLowNode().
Referenced by GetVisitedPolicy().
WLDMInvariantsHold()
bool lczero::dag_classic::Node::WLDMInvariantsHold () const
Definition at line 637 of file node.cc.
References DebugString(), GetD(), GetM(), GetWL(), and lczero::dag_classic::WLDMInvariantsHold().
Referenced by AdjustForTerminal(), FinalizeScoreUpdate(), MakeNotTerminal(), and MakeTerminal().
ZeroNInFlight()
bool lczero::dag_classic::Node::ZeroNInFlight () const
Debug check for zero in-flight visits.
Definition at line 601 of file node.cc.
References CERR, DebugString(), GetNInFlight(), and lczero::dag_classic::TreeWalk().
Member Data Documentation
d_
double lczero::dag_classic::Node::d_ = 0.0f private
Definition at line 505 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), FinalizeScoreUpdate(), GetD(), GetQ(), MakeNotTerminal(), MakeTerminal(), and Trim().
edge_
Edge lczero::dag_classic::Node::edge_ private
Definition at line 522 of file node.h.
Referenced by lczero::dag_classic::EdgeAndNode::DebugString(), GetMove(), GetP(), and SetP().
index_
uint16_t lczero::dag_classic::Node::index_ private
Definition at line 526 of file node.h.
Referenced by DebugString(), DotEdgeString(), and Index().
low_node_
std::shared_ptr<LowNode> lczero::dag_classic::Node::low_node_ private
Definition at line 494 of file node.h.
Referenced by CreateSingleChildNode(), DebugString(), DotEdgeString(), GetChild(), GetChildrenVisits(), GetLowNode(), GetNumEdges(), GetTotalVisits(), HasChildren(), MakeNotTerminal(), ReleaseChildrenExceptOne(), SetLowNode(), SortEdges(), and UnsetLowNode().
lower_bound_
GameResult lczero::dag_classic::Node::lower_bound_ private
Definition at line 534 of file node.h.
Referenced by DebugString(), DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), GetBounds(), MakeNotTerminal(), SetBounds(), and Trim().
m_
float lczero::dag_classic::Node::m_ = 0.0f private
Definition at line 513 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), FinalizeScoreUpdate(), GetM(), MakeNotTerminal(), MakeTerminal(), and Trim().
n_
uint32_t lczero::dag_classic::Node::n_ = 0 private
Definition at line 515 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), FinalizeScoreUpdate(), GetN(), GetNStarted(), MakeNotTerminal(), Trim(), and TryStartScoreUpdate().
n_in_flight_
std::atomic<uint32_t> lczero::dag_classic::Node::n_in_flight_ = 0 private
Definition at line 519 of file node.h.
Referenced by CancelScoreUpdate(), FinalizeScoreUpdate(), GetNInFlight(), IncrementNInFlight(), Trim(), and TryStartScoreUpdate().
repetition_
bool lczero::dag_classic::Node::repetition_ private
Definition at line 537 of file node.h.
Referenced by IsRepetition(), MakeNotTerminal(), SetRepetition(), and Trim().
sibling_
atomic_unique_ptr<Node> lczero::dag_classic::Node::sibling_ private
Definition at line 509 of file node.h.
Referenced by DebugString(), DotEdgeString(), GetSibling(), MoveSiblingIn(), and ~Node().
terminal_type_
Terminal lczero::dag_classic::Node::terminal_type_ private
Definition at line 532 of file node.h.
Referenced by DebugString(), DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), IsTbTerminal(), IsTerminal(), MakeNotTerminal(), MakeTerminal(), and Trim().
upper_bound_
GameResult lczero::dag_classic::Node::upper_bound_ private
Definition at line 535 of file node.h.
Referenced by DebugString(), DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), GetBounds(), MakeNotTerminal(), SetBounds(), and Trim().
wl_
double lczero::dag_classic::Node::wl_ = 0.0f private
Definition at line 502 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), DotEdgeString(), lczero::dag_classic::LowNode::DotNodeString(), FinalizeScoreUpdate(), GetQ(), GetWL(), MakeNotTerminal(), MakeTerminal(), and Trim().
The documentation for this class was generated from the following files:
src/search/dag_classic/node.h
src/search/dag_classic/node.cc