Leela Chess Zero: lczero::SelfPlayLoop Class Reference
lczero::SelfPlayLoop Class Reference
#include <loop.h>
Public Member Functions
SelfPlayLoop (StringUciResponder *uci_responder)
~SelfPlayLoop ()
void Run ()
Private Member Functions
void SendGameInfo (const GameInfo &move)
void SendTournament (const TournamentInfo &info)
void EnsureOptionsSent ()
Private Attributes
StringUciResponder * uci_responder_ = nullptr
OptionsParser options_
std::unique_ptr< SelfPlayTournament > tournament_
std::unique_ptr< std::thread > thread_
Detailed Description
Definition at line 38 of file loop.h.
Constructor & Destructor Documentation
SelfPlayLoop()
lczero::SelfPlayLoop::SelfPlayLoop (StringUciResponder * uci_responder) inline
Definition at line 40 of file loop.h.
References options_, lczero::StringUciResponder::PopulateParams(), and uci_responder_.
~SelfPlayLoop()
lczero::SelfPlayLoop::~SelfPlayLoop ()
Definition at line 44 of file loop.cc.
References thread_, and tournament_.
Member Function Documentation
EnsureOptionsSent()
void lczero::SelfPlayLoop::EnsureOptionsSent () private
Run()
void lczero::SelfPlayLoop::Run ()
Definition at line 49 of file loop.cc.
References lczero::OptionsParser::Add(), lczero::Logging::Get(), lczero::OptionsDict::Get(), lczero::OptionsParser::GetOptionsDict(), options_, lczero::SelfPlayTournament::PopulateOptions(), lczero::OptionsParser::ProcessAllFlags(), lczero::SelfPlayTournament::RunBlocking(), SendGameInfo(), lczero::StringUciResponder::SendId(), SendTournament(), lczero::Logging::SetFilename(), and uci_responder_.
Referenced by main().
SendGameInfo()
void lczero::SelfPlayLoop::SendGameInfo (const GameInfo & move) private
Definition at line 69 of file loop.cc.
References lczero::DRAW, lczero::GameInfo::game_id, lczero::GameInfo::game_result, lczero::GameInfo::initial_fen, lczero::GameInfo::is_black, lczero::ChessBoard::kStartposFen, lczero::GameInfo::min_false_positive_threshold, lczero::GameInfo::moves, lczero::GameInfo::play_start_ply, lczero::StringUciResponder::SendRawResponses(), lczero::GameInfo::training_filename, uci_responder_, lczero::UNDECIDED, and lczero::WHITE_WON.
Referenced by Run().
SendTournament()
void lczero::SelfPlayLoop::SendTournament (const TournamentInfo & info) private
Definition at line 105 of file loop.cc.
References lczero::TournamentInfo::finished, lczero::TournamentInfo::move_count_, lczero::TournamentInfo::nodes_total_, lczero::TournamentInfo::results, lczero::StringUciResponder::SendRawResponse(), and uci_responder_.
Referenced by Run().
Member Data Documentation
options_
OptionsParser lczero::SelfPlayLoop::options_ private
Definition at line 55 of file loop.h.
Referenced by Run(), and SelfPlayLoop().
thread_
std::unique_ptr<std::thread> lczero::SelfPlayLoop::thread_ private
Definition at line 57 of file loop.h.
Referenced by ~SelfPlayLoop().
tournament_
std::unique_ptr<SelfPlayTournament> lczero::SelfPlayLoop::tournament_ private
Definition at line 56 of file loop.h.
Referenced by ~SelfPlayLoop().
uci_responder_
StringUciResponder* lczero::SelfPlayLoop::uci_responder_ = nullptr private
Definition at line 54 of file loop.h.
Referenced by Run(), SelfPlayLoop(), SendGameInfo(), and SendTournament().
The documentation for this class was generated from the following files:
src/selfplay/loop.h
src/selfplay/loop.cc