Leela Chess Zero: lczero::classic::NodeTree Class Reference
lczero::classic::NodeTree Class Reference
Manages the MCTS game tree and position history.
#include <node.h>
Public Member Functions
~NodeTree ()
Destructor that deallocates the entire tree.
void MakeMove (Move move)
Advances the current head by applying a move.
void TrimTreeAtHead ()
Resets the current head to clear any leftover state.
bool ResetToPosition (const std::string &starting_fen, const std::vector< std::string > &moves)
Sets the tree to a new position, attempting to reuse existing nodes.
bool ResetToPosition (const GameState &pos)
Sets the tree to a new position from a GameState.
const Position & HeadPosition () const
Gets the current board position.
int GetPlyCount () const
Gets the number of plies (half-moves) in the game.
bool IsBlackToMove () const
Checks if it's black's turn to move.
Node * GetCurrentHead () const
Gets the node at the current search position.
Node * GetGameBeginNode () const
Gets the root node of the entire game tree.
const PositionHistory & GetPositionHistory () const
Gets the position history for repetition detection.
Private Member Functions
void DeallocateTree ()
Deallocates all nodes in the tree.
Private Attributes
Node * current_head_ = nullptr
The current search position in the tree.
std::unique_ptr< Node > gamebegin_node_
Root node of the entire game tree.
PositionHistory history_
History of positions for repetition detection.
Detailed Description
Manages the MCTS game tree and position history.
The NodeTree maintains both the search tree (rooted at gamebegin_node_) and the current search position (current_head_). It handles tree reuse between moves, position updates, and memory management for the entire tree structure.
Definition at line 849 of file node.h.
Constructor & Destructor Documentation
~NodeTree()
lczero::classic::NodeTree::~NodeTree () inline
Destructor that deallocates the entire tree.
Definition at line 852 of file node.h.
References DeallocateTree().
Member Function Documentation
DeallocateTree()
void lczero::classic::NodeTree::DeallocateTree () private
Deallocates all nodes in the tree.
Deallocates the entire tree.
Definition at line 590 of file node.cc.
References current_head_, and gamebegin_node_.
Referenced by ResetToPosition(), and ~NodeTree().
GetCurrentHead()
Node * lczero::classic::NodeTree::GetCurrentHead () const inline
Gets the node at the current search position.
Returns
Pointer to the current head node.
Definition at line 893 of file node.h.
References current_head_.
Referenced by lczero::PolicyEvaluator::Gather(), and lczero::ValueEvaluator::Gather().
GetGameBeginNode()
Node * lczero::classic::NodeTree::GetGameBeginNode () const inline
Gets the root node of the entire game tree.
Returns
Pointer to the game begin node.
Definition at line 897 of file node.h.
References gamebegin_node_.
GetPlyCount()
int lczero::classic::NodeTree::GetPlyCount () const inline
Gets the number of plies (half-moves) in the game.
Returns
The ply count from the starting position.
Definition at line 885 of file node.h.
References lczero::Position::GetGamePly(), and HeadPosition().
GetPositionHistory()
const PositionHistory & lczero::classic::NodeTree::GetPositionHistory () const inline
Gets the position history for repetition detection.
Returns
Reference to the PositionHistory.
Definition at line 901 of file node.h.
References history_.
Referenced by lczero::PolicyEvaluator::Gather(), and lczero::ValueEvaluator::Gather().
HeadPosition()
const Position & lczero::classic::NodeTree::HeadPosition () const inline
Gets the current board position.
Returns
Reference to the Position at the current head.
Definition at line 881 of file node.h.
References history_, and lczero::PositionHistory::Last().
Referenced by GetPlyCount(), and IsBlackToMove().
IsBlackToMove()
bool lczero::classic::NodeTree::IsBlackToMove () const inline
Checks if it's black's turn to move.
Returns
True if black is to move at the current head.
Definition at line 889 of file node.h.
References HeadPosition(), and lczero::Position::IsBlackToMove().
MakeMove()
void lczero::classic::NodeTree::MakeMove (Move move)
Advances the current head by applying a move.
Advances the tree to the next position based on the move.
Parameters
move The move to apply to the current position.
move The move to make.
Definition at line 513 of file node.cc.
References lczero::PositionHistory::Append(), lczero::classic::Node::child_, lczero::classic::Node::CreateSingleChildNode(), current_head_, lczero::classic::Node::Edges(), history_, lczero::classic::Node::IsTerminal(), lczero::classic::Node::MakeNotTerminal(), and lczero::classic::Node::ReleaseChildrenExceptOne().
Referenced by lczero::PolicyEvaluator::MakeBestMove(), lczero::ValueEvaluator::MakeBestMove(), and ResetToPosition().
ResetToPosition() [1/2]
bool lczero::classic::NodeTree::ResetToPosition (const GameState & pos)
Sets the tree to a new position from a GameState.
Resets the tree to a specific game state.
Parameters
pos The game state to set as the current position.
Returns
True if position is a continuation of current game.
True if the new position is a descendant of the current tree state.
Definition at line 544 of file node.cc.
References current_head_, DeallocateTree(), gamebegin_node_, history_, m, MakeMove(), lczero::GameState::moves, lczero::PositionHistory::Reset(), lczero::PositionHistory::Starting(), lczero::GameState::startpos, and TrimTreeAtHead().
ResetToPosition() [2/2]
bool lczero::classic::NodeTree::ResetToPosition (const std::string & starting_fen, const std::vector< std::string > & moves)
Sets the tree to a new position, attempting to reuse existing nodes.
Resets the tree to a position defined by FEN and moves.
If the new position is a continuation of the current game, the tree is preserved and the head is advanced. Otherwise, the tree is rebuilt from scratch.
Parameters
starting_fen The FEN string for the starting position.
moves Vector of move strings from the start position.
Returns
True if position is a continuation of current game.
Definition at line 574 of file node.cc.
References lczero::ChessBoard::ApplyMove(), lczero::Position::FromFen(), lczero::Position::GetBoard(), m, lczero::ChessBoard::Mirror(), lczero::GameState::moves, moves, lczero::ChessBoard::ParseMove(), ResetToPosition(), and lczero::GameState::startpos.
Referenced by ResetToPosition(), lczero::BackendBenchmark::Run(), and lczero::Benchmark::Run().
TrimTreeAtHead()
void lczero::classic::NodeTree::TrimTreeAtHead ()
Resets the current head to clear any leftover state.
Trims the tree at the current head, releasing siblings.
Ensures the search starts fresh without carrying over data from previous searches at the same position.
Definition at line 532 of file node.cc.
References current_head_, lczero::classic::Node::GetParent(), lczero::classic::Node::index_, lczero::classic::Node::ReleaseChildren(), and lczero::classic::Node::sibling_.
Referenced by ResetToPosition().
Member Data Documentation
current_head_
Node* lczero::classic::NodeTree::current_head_ = nullptr private
The current search position in the tree.
Definition at line 908 of file node.h.
Referenced by DeallocateTree(), GetCurrentHead(), MakeMove(), ResetToPosition(), and TrimTreeAtHead().
gamebegin_node_
std::unique_ptr<Node> lczero::classic::NodeTree::gamebegin_node_ private
Root node of the entire game tree.
Definition at line 911 of file node.h.
Referenced by DeallocateTree(), GetGameBeginNode(), and ResetToPosition().
history_
PositionHistory lczero::classic::NodeTree::history_ private
History of positions for repetition detection.
Definition at line 914 of file node.h.
Referenced by GetPositionHistory(), HeadPosition(), MakeMove(), and ResetToPosition().
The documentation for this class was generated from the following files:
search/classic/node.h
search/classic/node.cc