Leela Chess Zero: lczero::EngineControllerBase Class Reference
lczero::EngineControllerBase Class Reference abstract
#include <uciloop.h>
Public Member Functions
virtual ~EngineControllerBase ()=default
virtual void EnsureReady ()=0
virtual void NewGame ()=0
virtual void SetPosition (const std::string &fen, const std::vector< std::string > &moves)=0
virtual void Go (const GoParams &params)=0
virtual void PonderHit ()=0
virtual void Wait ()=0
virtual void Stop ()=0
virtual void RegisterUciResponder (UciResponder *)=0
virtual void UnregisterUciResponder (UciResponder *)=0
Detailed Description
Definition at line 76 of file uciloop.h.
Constructor & Destructor Documentation
~EngineControllerBase()
virtual lczero::EngineControllerBase::~EngineControllerBase () virtual default
Member Function Documentation
EnsureReady()
virtual void lczero::EngineControllerBase::EnsureReady () pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::DispatchCommand().
Go()
virtual void lczero::EngineControllerBase::Go (const GoParams & params) pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::DispatchCommand().
NewGame()
virtual void lczero::EngineControllerBase::NewGame () pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::DispatchCommand().
PonderHit()
virtual void lczero::EngineControllerBase::PonderHit () pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::DispatchCommand().
RegisterUciResponder()
virtual void lczero::EngineControllerBase::RegisterUciResponder (UciResponder *) pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::UciLoop().
SetPosition()
virtual void lczero::EngineControllerBase::SetPosition (const std::string & fen, const std::vector< std::string > & moves) pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::DispatchCommand().
Stop()
virtual void lczero::EngineControllerBase::Stop () pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::DispatchCommand().
UnregisterUciResponder()
virtual void lczero::EngineControllerBase::UnregisterUciResponder (UciResponder *) pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::~UciLoop().
Wait()
virtual void lczero::EngineControllerBase::Wait () pure virtual
Implemented in lczero::Engine.
Referenced by lczero::UciLoop::DispatchCommand().
The documentation for this class was generated from the following file:
src/chess/uciloop.h