Leela Chess Zero: lczero::PolicyEvaluator Class Reference
lczero::PolicyEvaluator Class Reference
Public Member Functions
void Reset (const PlayerOptions &player) override
void Gather (classic::NodeTree *tree) override
void Run () override
void MakeBestMove (classic::NodeTree *tree) override
Public Member Functions inherited from lczero::Evaluator
virtual ~Evaluator ()=default
Public Attributes
std::unique_ptr< BackendComputation > comp_
std::vector< Move > moves_
std::vector< float > p_
Detailed Description
Definition at line 32 of file multigame.cc.
Member Function Documentation
Gather()
void lczero::PolicyEvaluator::Gather (classic::NodeTree * tree) inline override virtual
Implements lczero::Evaluator.
Definition at line 37 of file multigame.cc.
References comp_, lczero::classic::Node::Edges(), lczero::classic::NodeTree::GetCurrentHead(), lczero::classic::NodeTree::GetPositionHistory(), moves_, lczero::EvalResultPtr::p, p_, and lczero::EvalPosition::pos.
MakeBestMove()
void lczero::PolicyEvaluator::MakeBestMove (classic::NodeTree * tree) inline override virtual
Implements lczero::Evaluator.
Definition at line 52 of file multigame.cc.
References lczero::classic::NodeTree::MakeMove(), moves_, and p_.
Reset()
void lczero::PolicyEvaluator::Reset (const PlayerOptions & player) inline override virtual
Implements lczero::Evaluator.
Definition at line 34 of file multigame.cc.
References lczero::PlayerOptions::backend, comp_, and lczero::Backend::CreateComputation().
Run()
void lczero::PolicyEvaluator::Run () inline override virtual
Implements lczero::Evaluator.
Definition at line 51 of file multigame.cc.
References comp_.
Member Data Documentation
comp_
std::unique_ptr<BackendComputation> lczero::PolicyEvaluator::comp_
Definition at line 57 of file multigame.cc.
Referenced by Gather(), Reset(), and Run().
moves_
std::vector<Move> lczero::PolicyEvaluator::moves_
Definition at line 58 of file multigame.cc.
Referenced by Gather(), and MakeBestMove().
p_
std::vector<float> lczero::PolicyEvaluator::p_
Definition at line 59 of file multigame.cc.
Referenced by Gather(), and MakeBestMove().
The documentation for this class was generated from the following file:
src/selfplay/multigame.cc