Leela Chess Zero: lczero::classic::Edge Class Reference
lczero::classic::Edge Class Reference
#include <node.h>
Public Member Functions
Move GetMove (bool as_opponent=false) const
float GetP () const
void SetP (float val)
std::string DebugString () const
Static Public Member Functions
static std::unique_ptr< Edge[]> FromMovelist (const MoveList &moves)
Private Attributes
Move move_
uint16_t p_ = 0
Friends
class Node
Detailed Description
Definition at line 85 of file node.h.
Member Function Documentation
DebugString()
std::string lczero::classic::Edge::DebugString () const
Definition at line 178 of file node.cc.
References GetP(), move_, p_, and lczero::Move::ToString().
Referenced by lczero::classic::EdgeAndNode::DebugString().
FromMovelist()
std::unique_ptr< Edge[]> lczero::classic::Edge::FromMovelist (const MoveList & moves) static
Definition at line 185 of file node.cc.
References move_, and moves.
Referenced by lczero::classic::Node::CreateEdges(), and lczero::classic::Node::CreateSingleChildNode().
GetMove()
Move lczero::classic::Edge::GetMove (bool as_opponent = false) const
Definition at line 124 of file node.cc.
References lczero::Move::Flip(), m, and move_.
Referenced by lczero::classic::EdgeAndNode::GetMove().
GetP()
float lczero::classic::Edge::GetP () const
Definition at line 170 of file node.cc.
References p_.
Referenced by DebugString(), lczero::classic::EdgeAndNode::GetP(), and lczero::classic::Node::GetVisitedPolicy().
SetP()
void lczero::classic::Edge::SetP (float val)
Definition at line 161 of file node.cc.
References p, and p_.
Referenced by lczero::classic::Node::MakeTerminal().
Friends And Related Symbol Documentation
Node
friend class Node friend
Definition at line 111 of file node.h.
Member Data Documentation
move_
Move lczero::classic::Edge::move_ private
Definition at line 106 of file node.h.
Referenced by DebugString(), FromMovelist(), and GetMove().
p_
uint16_t lczero::classic::Edge::p_ = 0 private
Definition at line 110 of file node.h.
Referenced by DebugString(), GetP(), and SetP().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/classic/node.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/classic/node.cc