Leela Chess Zero: lczero::Move Class Reference
lczero::Move Class Reference
Represents a chess move in the Lc0 engine.
#include <types.h>
Public Member Functions
Move ()=default
Default constructor for a move.
bool operator== (const Move &other) const =default
Equality operator for comparing moves.
bool operator!= (const Move &other) const =default
Inequality operator for comparing moves.
void Flip ()
Mirrors the ranks of the move (flips vertically).
std::string ToString (bool is_chess960) const
Converts the move to a string representation.
Square from () const
Gets the source square of the move.
Square to () const
Gets the destination square of the move.
bool is_promotion () const
Checks if the move is a promotion.
PieceType promotion () const
Gets the promotion piece type if this is a promotion move.
bool is_castling () const
Checks if the move is a castling move.
bool is_en_passant () const
Checks if the move is an en passant capture.
bool is_null () const
Checks if the move is null (no move).
uint16_t raw_data () const
Gets the raw data representing the move.
Static Public Member Functions
static constexpr Move White (Square from, Square to)
Creates a move for white pieces.
static constexpr Move WhitePromotion (Square from, Square to, PieceType promotion_piece)
Creates a promotion move for white pieces.
static constexpr Move WhiteCastling (File king, File rook)
Creates a castling move for white pieces.
static constexpr Move WhiteEnPassant (Square from, Square to)
Creates an en passant move for white pieces.
Private Types
enum Masks : uint16_t {
kToMask = 0b0000000000111111 , kFromMask = 0b0000111111000000 , kSpecialMask = 0b0111000000000000 , kCastling = 0b0001000000000000 ,
kEnPassant = 0b0010000000000000 , kPromotion = 0b0100000000000000 , kPieceMask = 0b0011000000000000 , kFlipMask = 0b0000111000111000
}
Bit masks used for decoding the move data.
Private Member Functions
constexpr Move (uint16_t data)
Private constructor for creating a move from raw data.
Private Attributes
uint16_t data_ = 0
The 16-bit encoded representation of the move.
Detailed Description
Represents a chess move in the Lc0 engine.
This class encapsulates all the information about a chess move including source/destination squares, promotion information, and special move types like castling and en passant. The move is encoded efficiently in 16 bits.
Definition at line 143 of file types.h.
Member Enumeration Documentation
Masks
enum lczero::Move::Masks : uint16_t private
Bit masks used for decoding the move data.
Enumerator
kToMask
Mask for extracting "to" square (bits 0-5)
kFromMask
Mask for extracting "from" square (bits 6-11)
kSpecialMask
Mask for extracting special move info (bits 12-14)
kCastling
Bit pattern indicating castling move.
kEnPassant
Bit pattern indicating en passant move.
kPromotion
Bit indicating promotion move.
kPieceMask
Mask for extracting promotion piece type.
kFlipMask
Mask for flipping the move vertically.
Definition at line 254 of file types.h.
Constructor & Destructor Documentation
Move() [1/2]
lczero::Move::Move () default
Default constructor for a move.
Referenced by White(), WhiteCastling(), WhiteEnPassant(), and WhitePromotion().
Move() [2/2]
constexpr lczero::Move::Move (uint16_t data) inline explicit constexpr private
Private constructor for creating a move from raw data.
Parameters
data The 16-bit raw data encoding of the move.
Definition at line 240 of file types.h.
Member Function Documentation
Flip()
void lczero::Move::Flip () inline
Mirrors the ranks of the move (flips vertically).
This is used when changing perspective from white to black or vice versa.
Definition at line 195 of file types.h.
References data_, and kFlipMask.
Referenced by lczero::V6TrainingDataArray::Add(), lczero::classic::Edge::GetMove(), lczero::dag_classic::Edge::GetMove(), lczero::SelfPlayGame::GetMoves(), and lczero::SelfPlayGame::Play().
from()
Square lczero::Move::from () const inline
Gets the source square of the move.
Returns
The source square.
Definition at line 204 of file types.h.
References data_, lczero::Square::FromIdx(), and kFromMask.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::ChessBoard::IsLegalMove(), lczero::MoveToNNIndex(), ToString(), White(), WhiteEnPassant(), and WhitePromotion().
is_castling()
bool lczero::Move::is_castling () const inline
Checks if the move is a castling move.
Returns
True if the move is castling, false otherwise.
Definition at line 222 of file types.h.
References data_, kCastling, and kSpecialMask.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::ChessBoard::IsLegalMove(), and ToString().
is_en_passant()
bool lczero::Move::is_en_passant () const inline
Checks if the move is an en passant capture.
Returns
True if the move is en passant, false otherwise.
Definition at line 226 of file types.h.
References data_, kEnPassant, and kSpecialMask.
Referenced by lczero::ChessBoard::ApplyMove(), and lczero::ChessBoard::IsLegalMove().
is_null()
bool lczero::Move::is_null () const inline
Checks if the move is null (no move).
Returns
True if the move is null, false otherwise.
Note
This is deprecated and will be removed once UciResponder uses std::optional for ponder.
Definition at line 231 of file types.h.
References data_.
Referenced by lczero::StringUciResponder::OutputBestMove().
is_promotion()
bool lczero::Move::is_promotion () const inline
Checks if the move is a promotion.
Returns
True if the move promotes a pawn, false otherwise.
Definition at line 212 of file types.h.
References data_, and kPromotion.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::MoveToNNIndex(), and ToString().
operator!=()
bool lczero::Move::operator!= (const Move & other) const default
Inequality operator for comparing moves.
Parameters
other The other move to compare with.
Returns
True if the moves are not equal, false otherwise.
operator==()
bool lczero::Move::operator== (const Move & other) const default
Equality operator for comparing moves.
Parameters
other The other move to compare with.
Returns
True if the moves are equal, false otherwise.
promotion()
PieceType lczero::Move::promotion () const inline
Gets the promotion piece type if this is a promotion move.
Returns
The piece type to promote to.
Definition at line 216 of file types.h.
References data_, lczero::PieceType::FromIdx(), and kPieceMask.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::MoveToNNIndex(), and ToString().
raw_data()
uint16_t lczero::Move::raw_data () const inline
Gets the raw data representing the move.
Returns
The 16-bit raw data encoding of the move.
Definition at line 235 of file types.h.
References data_.
to()
Square lczero::Move::to () const inline
Gets the destination square of the move.
Returns
The destination square.
Definition at line 208 of file types.h.
References data_, lczero::Square::FromIdx(), and kToMask.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::ChessBoard::IsLegalMove(), lczero::MoveToNNIndex(), ToString(), White(), WhiteEnPassant(), and WhitePromotion().
ToString()
std::string lczero::Move::ToString (bool is_chess960) const inline
Converts the move to a string representation.
Parameters
is_chess960 True if the position is Chess960 variant, false otherwise.
Returns
String representation of the move in algebraic notation.
Definition at line 295 of file types.h.
References lczero::Square::file(), from(), is_castling(), is_promotion(), promotion(), lczero::Square::rank(), to(), lczero::Rank::ToString(), lczero::PieceType::ToString(), and lczero::Square::ToString().
Referenced by lczero::ChessBoard::ApplyMove(), lczero::classic::Edge::DebugString(), lczero::dag_classic::Edge::DebugString(), lczero::dag_classic::Node::DebugString(), lczero::dag_classic::Node::DotEdgeString(), lczero::Benchmark::OnBestMove(), and lczero::StringUciResponder::OutputBestMove().
White()
static constexpr Move lczero::Move::White (Square from, Square to) inline static constexpr
Creates a move for white pieces.
Parameters
from Source square of the move.
to Destination square of the move.
Returns
A Move object representing the move.
Definition at line 152 of file types.h.
References lczero::Square::as_idx(), from(), Move(), and to().
Referenced by lczero::DecodeMoveFromInput(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::MoveFromNNIndex(), lczero::MoveToNNIndex(), lczero::ChessBoard::ParseMove(), and lczero::PgnReader::SanToMove().
WhiteCastling()
static constexpr Move lczero::Move::WhiteCastling (File king, File rook) inline static constexpr
Creates a castling move for white pieces.
Parameters
king File of the king's starting position.
rook File of the rook's starting position.
Returns
A Move object representing the castling move.
Definition at line 171 of file types.h.
References lczero::File::idx, kCastling, and Move().
Referenced by lczero::DecodeMoveFromInput(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::ChessBoard::ParseMove(), and lczero::PgnReader::SanToMove().
WhiteEnPassant()
static constexpr Move lczero::Move::WhiteEnPassant (Square from, Square to) inline static constexpr
Creates an en passant move for white pieces.
Parameters
from Source square of the pawn.
to Destination square of the pawn.
Returns
A Move object representing the en passant move.
Definition at line 179 of file types.h.
References lczero::Square::as_idx(), from(), kEnPassant, Move(), and to().
Referenced by lczero::DecodeMoveFromInput(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::ChessBoard::ParseMove(), and lczero::PgnReader::SanToMove().
WhitePromotion()
static constexpr Move lczero::Move::WhitePromotion (Square from, Square to, PieceType promotion_piece) inline static constexpr
Creates a promotion move for white pieces.
Parameters
from Source square of the move.
to Destination square of the move.
promotion_piece The piece type to promote to (queen, rook, bishop, knight).
Returns
A Move object representing the promotion move.
Definition at line 161 of file types.h.
References lczero::Square::as_idx(), from(), lczero::PieceType::idx, kPromotion, Move(), and to().
Referenced by lczero::DecodeMoveFromInput(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::MoveFromNNIndex(), lczero::MoveToNNIndex(), lczero::ChessBoard::ParseMove(), and lczero::PgnReader::SanToMove().
Member Data Documentation
data_
uint16_t lczero::Move::data_ = 0 private
The 16-bit encoded representation of the move.
Move encoding using 16 bits:
bits 0-5: "to" square (6 bits)
bits 6-11: "from" square (6 bits)
bits 12-13: if is_promotion: promotion piece type if !is_promotion: SpecialMove
bit 14: is_promotion flag
bit 15: reserved (potentially for side-to-move) Castling is always encoded as a "king takes rook" move.
Definition at line 251 of file types.h.
Referenced by Flip(), from(), is_castling(), is_en_passant(), is_null(), is_promotion(), promotion(), raw_data(), and to().
The documentation for this class was generated from the following file:
chess/types.h