Leela Chess Zero: lczero::OptionsParser Class Reference
lczero::OptionsParser Class Reference
#include <optionsparser.h>
Classes
class Option
Public Member Functions
OptionsParser ()
template<typename Option , typename... Args>
Option::ValueType & Add (Args &&... args)
std::vector< std::string > ListOptionsUci () const
void SetUciOption (const std::string &name, const std::string &value, const std::string &context="")
bool ProcessAllFlags ()
bool ProcessFlags (const std::vector< std::string > &args)
const OptionsDict & GetOptionsDict (const std::string &context={})
OptionsDict * GetMutableOptions (const std::string &context={})
OptionsDict * GetMutableDefaultsOptions ()
void AddContext (const std::string &)
void ShowHelp () const
Private Member Functions
Option * FindOptionByLongFlag (const std::string &flag) const
Option * FindOptionByUciName (const std::string &name) const
Option * FindOptionById (const OptionId &id) const
Private Attributes
std::vector< std::unique_ptr< Option > > options_
OptionsDict defaults_
OptionsDict & values_
OptionId::VisibilityMode visibility_mode_ = OptionId::kNormalMode
Detailed Description
Definition at line 40 of file optionsparser.h.
Constructor & Destructor Documentation
OptionsParser()
lczero::OptionsParser::OptionsParser ()
Definition at line 49 of file optionsparser.cc.
Member Function Documentation
Add()
template<typename Option , typename... Args> Option::ValueType & lczero::OptionsParser::Add (Args &&... args) inline
Definition at line 88 of file optionsparser.h.
References defaults_, lczero::OptionsDict::GetRef(), and options_.
Referenced by lczero::SharedBackendParams::Populate(), lczero::classic::BaseSearchParams::Populate(), lczero::classic::SearchParams::Populate(), lczero::classic::PopulateCommonStopperOptions(), lczero::Engine::PopulateOptions(), lczero::SelfPlayTournament::PopulateOptions(), lczero::ConfigFile::PopulateOptions(), lczero::StringUciResponder::PopulateParams(), lczero::classic::PopulateTimeManagementOptions(), lczero::SelfPlayGame::PopulateUciParams(), lczero::SelfPlayLoop::Run(), lczero::BackendBenchmark::Run(), lczero::Benchmark::Run(), lczero::RunEngine(), lczero::RunRescorer(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
AddContext()
void lczero::OptionsParser::AddContext (const std::string & context)
Definition at line 203 of file optionsparser.cc.
References lczero::OptionsDict::AddSubdict(), and values_.
Referenced by lczero::SelfPlayTournament::PopulateOptions().
FindOptionById()
OptionsParser::Option * lczero::OptionsParser::FindOptionById (const OptionId & id) const private
Definition at line 91 of file optionsparser.cc.
References options_.
FindOptionByLongFlag()
OptionsParser::Option * lczero::OptionsParser::FindOptionByLongFlag (const std::string & flag) const private
Definition at line 74 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag(), and options_.
Referenced by ProcessFlags().
FindOptionByUciName()
OptionsParser::Option * lczero::OptionsParser::FindOptionByUciName (const std::string & name) const private
Definition at line 83 of file optionsparser.cc.
References name, options_, and lczero::StringsEqualIgnoreCase().
Referenced by SetUciOption().
GetMutableDefaultsOptions()
OptionsDict * lczero::OptionsParser::GetMutableDefaultsOptions () inline
Definition at line 112 of file optionsparser.h.
References defaults_.
Referenced by lczero::SelfPlayTournament::PopulateOptions(), and lczero::Benchmark::Run().
GetMutableOptions()
OptionsDict * lczero::OptionsParser::GetMutableOptions (const std::string & context = {})
Definition at line 98 of file optionsparser.cc.
References lczero::OptionsDict::GetMutableSubdict(), result, lczero::StrSplit(), and values_.
Referenced by lczero::SelfPlayTournament::PopulateOptions(), ProcessFlags(), and SetUciOption().
GetOptionsDict()
const OptionsDict & lczero::OptionsParser::GetOptionsDict (const std::string & context = {})
Definition at line 107 of file optionsparser.cc.
References lczero::OptionsDict::GetSubdict(), result, lczero::StrSplit(), and values_.
Referenced by lczero::ConvertLeelaToOnnx(), lczero::ConvertOnnxToLeela(), lczero::DescribeNetworkCmd(), lczero::SelfPlayTournament::PopulateOptions(), lczero::StringUciResponder::PopulateParams(), lczero::SelfPlayLoop::Run(), lczero::BackendBenchmark::Run(), lczero::Benchmark::Run(), lczero::RunEngine(), and lczero::RunRescorer().
ListOptionsUci()
std::vector< std::string > lczero::OptionsParser::ListOptionsUci () const
Definition at line 51 of file optionsparser.cc.
References options_, result, values_, and visibility_mode_.
Referenced by lczero::UciLoop::DispatchCommand().
ProcessAllFlags()
bool lczero::OptionsParser::ProcessAllFlags ()
Definition at line 116 of file optionsparser.cc.
References lczero::CommandLine::Arguments(), lczero::ConfigFile::Arguments(), and ProcessFlags().
Referenced by lczero::SelfPlayLoop::Run(), lczero::BackendBenchmark::Run(), lczero::Benchmark::Run(), lczero::RunEngine(), and lczero::RunRescorer().
ProcessFlags()
bool lczero::OptionsParser::ProcessFlags (const std::vector< std::string > & args)
Definition at line 121 of file optionsparser.cc.
References lczero::CommandLine::BinaryName(), CERR, FindOptionByLongFlag(), GetMutableOptions(), lczero::OptionId::kProMode, lczero::OptionId::kSimpleMode, options_, lczero::OptionsParser::Option::ProcessLongFlag(), ShowHelp(), value, and visibility_mode_.
Referenced by ProcessAllFlags().
SetUciOption()
void lczero::OptionsParser::SetUciOption (const std::string & name, const std::string & value, const std::string & context = "")
Definition at line 63 of file optionsparser.cc.
References FindOptionByUciName(), GetMutableOptions(), name, and value.
Referenced by lczero::UciLoop::DispatchCommand(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
ShowHelp()
void lczero::OptionsParser::ShowHelp () const
Definition at line 257 of file optionsparser.cc.
References lczero::CommandLine::BinaryName(), lczero::CommandLine::GetModes(), lczero::OptionsDict::ListSubdicts(), mode, options_, lczero::StrJoin(), values_, and visibility_mode_.
Referenced by ProcessFlags().
Member Data Documentation
defaults_
OptionsDict lczero::OptionsParser::defaults_ private
Definition at line 127 of file optionsparser.h.
Referenced by Add(), and GetMutableDefaultsOptions().
options_
std::vector<std::unique_ptr<Option> > lczero::OptionsParser::options_ private
Definition at line 126 of file optionsparser.h.
Referenced by Add(), FindOptionById(), FindOptionByLongFlag(), FindOptionByUciName(), ListOptionsUci(), ProcessFlags(), and ShowHelp().
values_
OptionsDict& lczero::OptionsParser::values_ private
Definition at line 128 of file optionsparser.h.
Referenced by AddContext(), GetMutableOptions(), GetOptionsDict(), ListOptionsUci(), and ShowHelp().
visibility_mode_
OptionId::VisibilityMode lczero::OptionsParser::visibility_mode_ = OptionId::kNormalMode private
Definition at line 129 of file optionsparser.h.
Referenced by ListOptionsUci(), ProcessFlags(), and ShowHelp().
The documentation for this class was generated from the following files:
utils/optionsparser.h
utils/optionsparser.cc