Leela Chess Zero: lczero::AtomicVector< T > Class Template Reference
lczero::AtomicVector< T > Class Template Reference
#include <atomic_vector.h>
Public Member Functions
AtomicVector (size_t capacity)
~AtomicVector ()
template<typename... Args>
size_t emplace_back (Args &&... args)
T & operator[] (size_t i)
const T & operator[] (size_t i) const
size_t size () const
size_t capacity () const
void clear ()
T * begin ()
T * end ()
const T * begin () const
const T * end () const
Private Attributes
const size_t capacity_
std::atomic< size_t > size_
std::aligned_storage< sizeof(T), alignof(T)>::type * data_
Detailed Description
template<typename T>
class lczero::AtomicVector< T >
Definition at line 33 of file atomic_vector.h.
Constructor & Destructor Documentation
AtomicVector()
template<typename T > lczero::AtomicVector< T >::AtomicVector (size_t capacity) inline explicit
Definition at line 35 of file atomic_vector.h.
References lczero::AtomicVector< T >::capacity(), lczero::AtomicVector< T >::data_, and type.
~AtomicVector()
template<typename T > lczero::AtomicVector< T >::~AtomicVector () inline
Definition at line 40 of file atomic_vector.h.
References lczero::AtomicVector< T >::clear(), and lczero::AtomicVector< T >::data_.
Member Function Documentation
begin() [1/2]
template<typename T > T * lczero::AtomicVector< T >::begin () inline
Definition at line 75 of file atomic_vector.h.
References lczero::AtomicVector< T >::data_.
begin() [2/2]
template<typename T > const T * lczero::AtomicVector< T >::begin () const inline
Definition at line 77 of file atomic_vector.h.
References lczero::AtomicVector< T >::data_.
capacity()
template<typename T > size_t lczero::AtomicVector< T >::capacity () const inline
Definition at line 65 of file atomic_vector.h.
References lczero::AtomicVector< T >::capacity_.
Referenced by lczero::AtomicVector< T >::AtomicVector().
clear()
template<typename T > void lczero::AtomicVector< T >::clear () inline
Definition at line 68 of file atomic_vector.h.
References lczero::AtomicVector< T >::data_, and lczero::AtomicVector< T >::size_.
Referenced by lczero::AtomicVector< T >::~AtomicVector().
emplace_back()
template<typename T > template<typename... Args> size_t lczero::AtomicVector< T >::emplace_back (Args &&... args) inline
Definition at line 47 of file atomic_vector.h.
References lczero::AtomicVector< T >::capacity_, lczero::AtomicVector< T >::data_, and lczero::AtomicVector< T >::size_.
end() [1/2]
template<typename T > T * lczero::AtomicVector< T >::end () inline
Definition at line 76 of file atomic_vector.h.
References lczero::AtomicVector< T >::data_, and lczero::AtomicVector< T >::size().
end() [2/2]
template<typename T > const T * lczero::AtomicVector< T >::end () const inline
Definition at line 78 of file atomic_vector.h.
References lczero::AtomicVector< T >::data_, and lczero::AtomicVector< T >::size().
operator[]() [1/2]
template<typename T > T & lczero::AtomicVector< T >::operator[] (size_t i) inline
Definition at line 54 of file atomic_vector.h.
References lczero::AtomicVector< T >::data_, and lczero::AtomicVector< T >::size().
operator[]() [2/2]
template<typename T > const T & lczero::AtomicVector< T >::operator[] (size_t i) const inline
Definition at line 59 of file atomic_vector.h.
References lczero::AtomicVector< T >::data_, and lczero::AtomicVector< T >::size().
size()
template<typename T > size_t lczero::AtomicVector< T >::size () const inline
Definition at line 64 of file atomic_vector.h.
References lczero::AtomicVector< T >::size_.
Referenced by lczero::AtomicVector< T >::end(), lczero::AtomicVector< T >::end(), lczero::AtomicVector< T >::operator[](), and lczero::AtomicVector< T >::operator[]().
Member Data Documentation
capacity_
template<typename T > const size_t lczero::AtomicVector< T >::capacity_ private
Definition at line 81 of file atomic_vector.h.
Referenced by lczero::AtomicVector< T >::capacity(), and lczero::AtomicVector< T >::emplace_back().
data_
template<typename T > std::aligned_storage<sizeof(T),alignof(T)>::type* lczero::AtomicVector< T >::data_ private
Definition at line 83 of file atomic_vector.h.
Referenced by lczero::AtomicVector< T >::AtomicVector(), lczero::AtomicVector< T >::begin(), lczero::AtomicVector< T >::begin(), lczero::AtomicVector< T >::clear(), lczero::AtomicVector< T >::emplace_back(), lczero::AtomicVector< T >::end(), lczero::AtomicVector< T >::end(), lczero::AtomicVector< T >::operator[](), lczero::AtomicVector< T >::operator[](), and lczero::AtomicVector< T >::~AtomicVector().
size_
template<typename T > std::atomic<size_t> lczero::AtomicVector< T >::size_ private
Definition at line 82 of file atomic_vector.h.
Referenced by lczero::AtomicVector< T >::clear(), lczero::AtomicVector< T >::emplace_back(), and lczero::AtomicVector< T >::size().
The documentation for this class was generated from the following file:
src/utils/atomic_vector.h