Leela Chess Zero: lczero::ChessBoard Class Reference
lczero::ChessBoard Class Reference
Represents a chess board position in the Lc0 engine.
#include <board.h>
Classes
class Castlings
Public Member Functions
ChessBoard ()=default
Default constructor for a chess board.
ChessBoard (const ChessBoard &other)=default
Copy constructor for a chess board.
ChessBoard (const std::string &fen)
Constructor that creates a board from a FEN string.
ChessBoard & operator= (const ChessBoard &other)=default
Assignment operator for copying a chess board.
void SetFromFen (std::string_view fen, int *rule50_ply=nullptr, int *moves=nullptr)
Sets the board position from a FEN string.
void Clear ()
Clears the entire board state to empty.
void Mirror ()
Swaps black and white pieces and mirrors them relative to the middle of the board.
MoveList GeneratePseudolegalMoves () const
Generates a list of possible moves for the current player ("us", treated as white internally).
bool ApplyMove (Move move)
Applies a move to the board.
bool IsUnderAttack (Square square) const
Checks if a square is under attack from the opponent ("them", treated as black internally).
KingAttackInfo GenerateKingAttackInfo () const
Generates king attack information used for legal move detection.
bool IsUnderCheck () const
Checks if the current player's king ("our" king, treated as white internally) is under check.
bool HasMatingMaterial () const
Checks whether at least one side has sufficient material for checkmate.
MoveList GenerateLegalMoves () const
Generates a list of legal moves for the current player.
bool IsLegalMove (Move move, const KingAttackInfo &king_attack_info) const
Checks whether a pseudolegal move is actually legal (doesn't leave own king in check).
Move ParseMove (std::string_view move_str) const
Parses a move from algebraic notation string.
uint64_t Hash () const
Computes a hash value representing the current board state.
std::string DebugString () const
Gets a debug string representation of the board state.
BitBoard ours () const
Gets the bitboard of pieces belonging to the current player ("us").
BitBoard theirs () const
Gets the bitboard of pieces belonging to the opponent ("them").
BitBoard pawns () const
Gets the bitboard of pawns on the board.
BitBoard en_passant () const
Gets the bitboard of en passant targets.
BitBoard bishops () const
Gets the bitboard of bishops on the board.
BitBoard rooks () const
Gets the bitboard of rooks on the board.
BitBoard queens () const
Gets the bitboard of queens on the board.
BitBoard knights () const
Gets the bitboard of knights on the board.
BitBoard kings () const
Gets the bitboard of kings on the board.
const Castlings & castlings () const
Gets the castling rights information for the position.
bool flipped () const
Checks if the board is flipped (currently black's turn to move).
bool operator== (const ChessBoard &other) const =default
Equality operator for comparing chess boards.
bool operator!= (const ChessBoard &other) const =default
Inequality operator for comparing chess boards.
Static Public Attributes
static const char * kStartposFen
Standard chess starting position in FEN notation.
static const ChessBoard kStartposBoard
Pre-initialized starting position board.
static const BitBoard kPawnMask = 0x00FFFFFFFFFFFF00ULL
Bitboard mask for identifying pawns vs en passant markers.
Private Member Functions
void PutPiece (Square square, PieceType piece, bool is_theirs)
Places a piece on a specific square of the board.
bool IsValid () const
Checks if the internal board state is consistent after transformations.
Private Attributes
BitBoard our_pieces_
Bitboard containing all pieces of the current player (treated as white internally).
BitBoard their_pieces_
Bitboard containing all pieces of the opponent (treated as black internally).
BitBoard rooks_
Bitboard containing all rooks and queens (both players).
BitBoard bishops_
Bitboard containing all bishops and queens (both players).
BitBoard pawns_
Bitboard containing all pawns and en passant markers.
Square our_king_
Square position of the current player's king (treated as white internally).
Square their_king_
Square position of the opponent's king (treated as black internally).
Castlings castlings_
Object containing castling rights information for both players.
bool flipped_ = false
Flag indicating if the board is flipped (black to move).
Detailed Description
Represents a chess board position in the Lc0 engine.
This class manages the state of a chess board including piece placement, castling rights, en passant information, and game state. Unlike most chess engines, the board is internally mirrored when it's black's turn to move, so the "us" (current player) is always white from the internal perspective.
Definition at line 64 of file board.h.
Constructor & Destructor Documentation
ChessBoard() [1/3]
lczero::ChessBoard::ChessBoard () default
Default constructor for a chess board.
Referenced by Clear().
ChessBoard() [2/3]
lczero::ChessBoard::ChessBoard (const ChessBoard & other) default
Copy constructor for a chess board.
Parameters
other The other chess board to copy from.
ChessBoard() [3/3]
lczero::ChessBoard::ChessBoard (const std::string & fen) inline
Constructor that creates a board from a FEN string.
Parameters
fen The FEN string representing the initial position.
Definition at line 75 of file board.h.
References fen, and SetFromFen().
Member Function Documentation
ApplyMove()
bool lczero::ChessBoard::ApplyMove (Move move)
Applies a move to the board.
Only applies moves for the "us" (current) player, treated as white internally.
Parameters
move The move to apply to the board.
Returns
True if the 50-move rule counter should be reset, false otherwise.
Definition at line 596 of file board.cc.
References lczero::Square::as_idx(), bishops_, castlings_, CERR, DebugString(), lczero::Square::file(), lczero::Move::from(), lczero::BitBoard::FromSquare(), lczero::BitBoard::get(), lczero::PieceType::idx, lczero::BitBoard::intersects(), lczero::Move::is_castling(), lczero::Move::is_en_passant(), lczero::Move::is_promotion(), IsValid(), lczero::kBishop, lczero::kFileC, lczero::kFileD, lczero::kFileF, lczero::kFileG, kPawnMask, lczero::kQueen, lczero::kRank1, lczero::kRank5, lczero::kRank8, lczero::kRook, our_king_, lczero::ChessBoard::Castlings::our_kingside_rook, our_pieces_, lczero::ChessBoard::Castlings::our_queenside_rook, pawns_, lczero::Move::promotion(), lczero::Square::rank(), lczero::BitBoard::reset(), lczero::ChessBoard::Castlings::reset_they_can_00(), lczero::ChessBoard::Castlings::reset_they_can_000(), lczero::ChessBoard::Castlings::reset_we_can_00(), lczero::ChessBoard::Castlings::reset_we_can_000(), rooks_, lczero::BitBoard::set(), lczero::BitBoard::set_if(), lczero::ChessBoard::Castlings::their_kingside_rook, their_pieces_, lczero::ChessBoard::Castlings::their_queenside_rook, lczero::Move::to(), and lczero::Move::ToString().
Referenced by lczero::PgnReader::AddPgnFile(), IsLegalMove(), lczero::Position::Position(), lczero::classic::NodeTree::ResetToPosition(), lczero::dag_classic::NodeTree::ResetToPosition(), lczero::TEST(), and lczero::TEST().
bishops()
BitBoard lczero::ChessBoard::bishops () const inline
Gets the bitboard of bishops on the board.
Excludes queens, returning only actual bishop pieces.
Returns
A bitboard representing all bishops.
Definition at line 277 of file board.h.
References bishops_, and rooks_.
Referenced by lczero::EncodePositionForNN(), IsValid(), and lczero::PgnReader::SanToMove().
castlings()
const Castlings & lczero::ChessBoard::castlings () const inline
Gets the castling rights information for the position.
Returns
Constant reference to the Castlings object containing castling rights.
Definition at line 304 of file board.h.
References castlings_.
Referenced by lczero::BoardToFen(), lczero::EncodePositionForNN(), and lczero::PgnReader::SanToMove().
Clear()
void lczero::ChessBoard::Clear ()
Clears the entire board state to empty.
Nullifies the whole structure, removing all pieces and resetting game state.
Definition at line 55 of file board.cc.
References ChessBoard().
Referenced by SetFromFen(), and lczero::TEST().
DebugString()
std::string lczero::ChessBoard::DebugString () const
Gets a debug string representation of the board state.
Returns
A string with detailed information about the board for debugging purposes.
Definition at line 1144 of file board.cc.
References lczero::BoardToFen(), and fen.
Referenced by ApplyMove(), and lczero::TEST().
en_passant()
BitBoard lczero::ChessBoard::en_passant () const inline
Gets the bitboard of en passant targets.
These are special markers indicating squares where en passant captures are possible.
Returns
A bitboard representing en passant target squares.
Definition at line 272 of file board.h.
References kPawnMask, and pawns_.
Referenced by lczero::BoardToFen(), lczero::EncodePositionForNN(), lczero::PgnReader::SanToMove(), and lczero::TEST().
flipped()
bool lczero::ChessBoard::flipped () const inline
Checks if the board is flipped (currently black's turn to move).
Returns
True if it's black's turn to move, false if it's white's turn.
Definition at line 308 of file board.h.
References flipped_.
Referenced by lczero::BoardToFen(), lczero::EncodePositionForNN(), lczero::python::GameState::GameState(), lczero::Position::IsBlackToMove(), lczero::SyzygyTablebaseImpl::probe_table(), lczero::PgnReader::SanToMove(), SetFromFen(), and lczero::TEST().
GenerateKingAttackInfo()
KingAttackInfo lczero::ChessBoard::GenerateKingAttackInfo () const
Generates king attack information used for legal move detection.
Returns
KingAttackInfo object containing information about checks and pins.
Definition at line 762 of file board.cc.
References lczero::Square::as_idx(), lczero::BitBoard::as_int(), lczero::KingAttackInfo::attack_lines_, bishops_, lczero::KingAttackInfo::double_check_, lczero::Square::file(), lczero::File::FromIdx(), lczero::Rank::FromIdx(), lczero::BitBoard::get(), lczero::File::idx, lczero::Rank::idx, kPawnMask, our_king_, our_pieces_, pawns_, lczero::KingAttackInfo::pinned_pieces_, lczero::Square::rank(), rooks_, lczero::BitBoard::set(), their_king_, and their_pieces_.
Referenced by GenerateLegalMoves().
GenerateLegalMoves()
MoveList lczero::ChessBoard::GenerateLegalMoves () const
Generates a list of legal moves for the current player.
Filters pseudolegal moves to only include those that don't leave the king in check.
Returns
A list of legal moves that can be played from this position.
Definition at line 959 of file board.cc.
References GenerateKingAttackInfo(), GeneratePseudolegalMoves(), m, and result.
Referenced by lczero::PositionHistory::ComputeGameResult(), lczero::classic::SearchWorker::ExtendNode(), lczero::dag_classic::SearchWorker::ExtendNode(), lczero::python::GameState::moves(), lczero::python::GameState::policy_indices(), lczero::SyzygyTablebase::probe_dtz(), lczero::SyzygyTablebase::root_probe(), lczero::SyzygyTablebase::root_probe_wdl(), lczero::PgnReader::SanToMove(), lczero::SyzygyTablebase::search(), and lczero::TEST().
GeneratePseudolegalMoves()
MoveList lczero::ChessBoard::GeneratePseudolegalMoves () const
Generates a list of possible moves for the current player ("us", treated as white internally).
The moves may leave the king under check - these are called pseudolegal moves.
Returns
A list of pseudolegal moves that could be played from this position.
Definition at line 430 of file board.cc.
References bishops_, castlings_, lczero::BitBoard::get(), IsUnderAttack(), lczero::File::IsValid(), lczero::Rank::IsValid(), lczero::kFileC, lczero::kFileD, lczero::kFileF, lczero::kFileG, kPawnMask, lczero::kRank1, lczero::kRank3, lczero::kRank4, lczero::kRank6, lczero::kRank8, our_king_, lczero::ChessBoard::Castlings::our_kingside_rook, our_pieces_, lczero::ChessBoard::Castlings::our_queenside_rook, pawns_, result, rooks_, their_pieces_, lczero::ChessBoard::Castlings::we_can_00(), lczero::ChessBoard::Castlings::we_can_000(), lczero::Move::White(), lczero::Move::WhiteCastling(), lczero::Move::WhiteEnPassant(), and lczero::Move::WhitePromotion().
Referenced by GenerateLegalMoves(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
Hash()
uint64_t lczero::ChessBoard::Hash () const inline
Computes a hash value representing the current board state.
This hash incorporates all aspects of the position: pieces, castling rights, etc.
Returns
A 64-bit hash value uniquely representing the board state.
Definition at line 157 of file board.h.
References lczero::Square::as_idx(), lczero::BitBoard::as_int(), lczero::ChessBoard::Castlings::as_int(), bishops_, castlings_, flipped_, lczero::HashCat(), our_king_, our_pieces_, pawns_, rooks_, their_king_, and their_pieces_.
Referenced by lczero::Position::Hash().
HasMatingMaterial()
bool lczero::ChessBoard::HasMatingMaterial () const
Checks whether at least one side has sufficient material for checkmate.
Returns
True if either side has mating material, false if the game is drawn due to insufficient material.
Definition at line 1121 of file board.cc.
References bishops_, lczero::BitBoard::empty(), lczero::BitBoard::intersects(), knights(), our_pieces_, pawns_, rooks_, and their_pieces_.
Referenced by lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
IsLegalMove()
bool lczero::ChessBoard::IsLegalMove (Move move, const KingAttackInfo & king_attack_info) const
Checks whether a pseudolegal move is actually legal (doesn't leave own king in check).
Parameters
move The move to check for legality.
king_attack_info Precomputed king attack information for efficiency.
Returns
True if the move is legal, false if it leaves the king in check.
Definition at line 888 of file board.cc.
References ApplyMove(), lczero::Square::file(), lczero::Move::from(), lczero::KingAttackInfo::in_check(), lczero::KingAttackInfo::in_double_check(), lczero::Move::is_castling(), lczero::Move::is_en_passant(), lczero::KingAttackInfo::is_on_attack_line(), lczero::KingAttackInfo::is_pinned(), IsUnderCheck(), our_king_, lczero::Square::rank(), and lczero::Move::to().
IsUnderAttack()
bool lczero::ChessBoard::IsUnderAttack (Square square) const
Checks if a square is under attack from the opponent ("them", treated as black internally).
Parameters
square The square to check for attacks.
Returns
True if the square is attacked by opponent pieces, false otherwise.
Definition at line 728 of file board.cc.
References lczero::Square::as_idx(), bishops_, lczero::Square::file(), kPawnMask, our_pieces_, pawns_, lczero::Square::rank(), rooks_, their_king_, and their_pieces_.
Referenced by GeneratePseudolegalMoves(), and IsUnderCheck().
IsUnderCheck()
bool lczero::ChessBoard::IsUnderCheck () const inline
Checks if the current player's king ("our" king, treated as white internally) is under check.
Returns
True if the current player's king is in check, false otherwise.
Definition at line 131 of file board.h.
References IsUnderAttack(), and our_king_.
Referenced by IsLegalMove(), lczero::SyzygyTablebase::probe_dtz(), and lczero::SyzygyTablebase::root_probe().
IsValid()
bool lczero::ChessBoard::IsValid () const private
Checks if the internal board state is consistent after transformations.
Returns
True if the board state is valid, false otherwise.
Definition at line 577 of file board.cc.
References bishops(), kings(), ours(), pawns(), queens(), rooks(), and theirs().
Referenced by ApplyMove().
kings()
BitBoard lczero::ChessBoard::kings () const inline
Gets the bitboard of kings on the board.
Returns
A bitboard representing both kings (current player's and opponent's).
Definition at line 298 of file board.h.
References lczero::BitBoard::FromSquare(), our_king_, and their_king_.
Referenced by lczero::EncodePositionForNN(), IsValid(), lczero::SyzygyTablebaseImpl::probe_table(), and lczero::PgnReader::SanToMove().
knights()
BitBoard lczero::ChessBoard::knights () const inline
Gets the bitboard of knights on the board.
Calculates knights by subtracting other piece types from all pieces.
Returns
A bitboard representing all knights.
Definition at line 291 of file board.h.
References bishops_, our_king_, our_pieces_, pawns(), rooks_, their_king_, and their_pieces_.
Referenced by lczero::EncodePositionForNN(), HasMatingMaterial(), and lczero::PgnReader::SanToMove().
Mirror()
void lczero::ChessBoard::Mirror ()
Swaps black and white pieces and mirrors them relative to the middle of the board.
What was on rank 1 appears on rank 8, what was on file b remains on file b. This is used to change perspective from white to black or vice versa.
Definition at line 57 of file board.cc.
References bishops_, castlings_, lczero::Square::Flip(), flipped_, lczero::BitBoard::Mirror(), lczero::ChessBoard::Castlings::Mirror(), our_king_, our_pieces_, pawns_, rooks_, their_king_, and their_pieces_.
Referenced by lczero::PgnReader::AddPgnFile(), lczero::python::GameState::as_string(), lczero::BoardToFen(), lczero::EncodePositionForNN(), lczero::Position::Position(), lczero::classic::NodeTree::ResetToPosition(), lczero::dag_classic::NodeTree::ResetToPosition(), SetFromFen(), lczero::TEST(), and lczero::TEST().
operator!=()
bool lczero::ChessBoard::operator!= (const ChessBoard & other) const default
Inequality operator for comparing chess boards.
Parameters
other The other chess board to compare with.
Returns
True if the boards are different, false otherwise.
operator=()
ChessBoard & lczero::ChessBoard::operator= (const ChessBoard & other) default
Assignment operator for copying a chess board.
Parameters
other The other chess board to copy from.
Returns
Reference to this chess board after assignment.
operator==()
bool lczero::ChessBoard::operator== (const ChessBoard & other) const default
Equality operator for comparing chess boards.
Parameters
other The other chess board to compare with.
Returns
True if the boards are identical, false otherwise.
ours()
BitBoard lczero::ChessBoard::ours () const inline
Gets the bitboard of pieces belonging to the current player ("us").
Returns
A bitboard representing all pieces of the current player.
Definition at line 258 of file board.h.
References our_pieces_.
Referenced by lczero::EncodePositionForNN(), IsValid(), lczero::SyzygyTablebaseImpl::probe_table(), lczero::PgnReader::SanToMove(), and SetFromFen().
ParseMove()
Move lczero::ChessBoard::ParseMove (std::string_view move_str) const
Parses a move from algebraic notation string.
The input string should be in "normal" notation rather than from the player to move perspective, e.g. "e7e5" for a black pawn move.
Parameters
move_str The string representing the move in algebraic notation.
Returns
The parsed Move object, or a null move if parsing fails.
Definition at line 1150 of file board.cc.
References lczero::PieceType::CanPromoteInto(), lczero::Square::file(), lczero::Rank::Flip(), flipped_, lczero::BitBoard::get(), lczero::File::IsValid(), lczero::Rank::IsValid(), lczero::kFileA, lczero::kFileH, lczero::kKnight, lczero::kRank1, lczero::kRank8, lczero::kSquareC1, lczero::kSquareE1, lczero::kSquareG1, our_king_, our_pieces_, lczero::PieceType::Parse(), lczero::File::Parse(), lczero::Rank::Parse(), pawns(), pawns_, their_pieces_, lczero::Move::White(), lczero::Move::WhiteCastling(), lczero::Move::WhiteEnPassant(), and lczero::Move::WhitePromotion().
Referenced by lczero::classic::NodeTree::ResetToPosition(), lczero::dag_classic::NodeTree::ResetToPosition(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
pawns()
BitBoard lczero::ChessBoard::pawns () const inline
Gets the bitboard of pawns on the board.
Excludes en passant markers, returning only actual pawn pieces.
Returns
A bitboard representing all pawns.
Definition at line 267 of file board.h.
References kPawnMask, and pawns_.
Referenced by lczero::EncodePositionForNN(), IsValid(), knights(), ParseMove(), lczero::PgnReader::SanToMove(), lczero::SyzygyTablebase::search(), and SetFromFen().
PutPiece()
void lczero::ChessBoard::PutPiece (Square square, PieceType piece, bool is_theirs) private
Places a piece on a specific square of the board.
Parameters
square The square where to place the piece.
piece The type of piece to place.
is_theirs True if the piece belongs to the opponent, false if it belongs to current player.
Definition at line 969 of file board.cc.
References bishops_, lczero::kBishop, lczero::kKing, lczero::kPawn, lczero::kQueen, lczero::kRook, our_king_, our_pieces_, pawns_, rooks_, lczero::BitBoard::set(), their_king_, and their_pieces_.
Referenced by SetFromFen().
queens()
BitBoard lczero::ChessBoard::queens () const inline
Gets the bitboard of queens on the board.
Returns
A bitboard representing all queens.
Definition at line 286 of file board.h.
References bishops_, and rooks_.
Referenced by lczero::EncodePositionForNN(), IsValid(), and lczero::PgnReader::SanToMove().
rooks()
BitBoard lczero::ChessBoard::rooks () const inline
Gets the bitboard of rooks on the board.
Excludes queens, returning only actual rook pieces.
Returns
A bitboard representing all rooks.
Definition at line 282 of file board.h.
References bishops_, and rooks_.
Referenced by lczero::EncodePositionForNN(), IsValid(), lczero::PgnReader::SanToMove(), and SetFromFen().
SetFromFen()
void lczero::ChessBoard::SetFromFen (std::string_view fen, int * rule50_ply = nullptr, int * moves = nullptr)
Sets the board position from a FEN string.
If @rule50_ply and @moves are not nullptr, they are filled with number of moves without capture and number of full moves since the beginning of the game.
Parameters
fen The FEN string to parse.
rule50_ply Pointer to store the 50-move rule ply count (can be nullptr).
moves Pointer to store the number of full moves (can be nullptr).
Definition at line 977 of file board.cc.
References castlings_, Clear(), fen, lczero::Square::file(), flipped(), lczero::File::FromIdx(), lczero::BitBoard::get(), lczero::PieceType::IsValid(), lczero::File::IsValid(), lczero::Rank::IsValid(), lczero::kFileA, lczero::kFileH, lczero::kPawn, lczero::kRank1, lczero::kRank3, lczero::kRank5, lczero::kRank6, lczero::kRank8, Mirror(), moves, num, our_king_, lczero::ChessBoard::Castlings::our_kingside_rook, our_pieces_, lczero::ChessBoard::Castlings::our_queenside_rook, ours(), lczero::PieceType::Parse(), lczero::File::Parse(), lczero::Rank::Parse(), pawns(), pawns_, PutPiece(), rooks(), lczero::BitBoard::set(), lczero::ChessBoard::Castlings::set_they_can_00(), lczero::ChessBoard::Castlings::set_they_can_000(), lczero::ChessBoard::Castlings::set_we_can_00(), lczero::ChessBoard::Castlings::set_we_can_000(), their_king_, lczero::ChessBoard::Castlings::their_kingside_rook, their_pieces_, lczero::ChessBoard::Castlings::their_queenside_rook, and theirs().
Referenced by lczero::PgnReader::AddPgnFile(), ChessBoard(), lczero::PgnReader::Flush(), lczero::Position::FromFen(), lczero::python::GameState::GameState(), lczero::PopulateBoard(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TestValidExpectation().
theirs()
BitBoard lczero::ChessBoard::theirs () const inline
Gets the bitboard of pieces belonging to the opponent ("them").
Returns
A bitboard representing all opponent pieces.
Definition at line 262 of file board.h.
References their_pieces_.
Referenced by lczero::EncodePositionForNN(), IsValid(), lczero::SyzygyTablebaseImpl::probe_table(), and SetFromFen().
Member Data Documentation
bishops_
BitBoard lczero::ChessBoard::bishops_ private
Bitboard containing all bishops and queens (both players).
Definition at line 341 of file board.h.
Referenced by ApplyMove(), bishops(), GenerateKingAttackInfo(), GeneratePseudolegalMoves(), Hash(), HasMatingMaterial(), IsUnderAttack(), knights(), Mirror(), PutPiece(), queens(), and rooks().
castlings_
Castlings lczero::ChessBoard::castlings_ private
Object containing castling rights information for both players.
Definition at line 356 of file board.h.
Referenced by ApplyMove(), castlings(), GeneratePseudolegalMoves(), Hash(), Mirror(), and SetFromFen().
flipped_
bool lczero::ChessBoard::flipped_ = false private
Flag indicating if the board is flipped (black to move).
When true, it indicates that it's black's turn to move.
Definition at line 360 of file board.h.
Referenced by flipped(), Hash(), Mirror(), and ParseMove().
kPawnMask
const BitBoard lczero::ChessBoard::kPawnMask = 0x00FFFFFFFFFFFF00ULL static
Bitboard mask for identifying pawns vs en passant markers.
Definition at line 89 of file board.h.
Referenced by ApplyMove(), en_passant(), GenerateKingAttackInfo(), GeneratePseudolegalMoves(), IsUnderAttack(), and pawns().
kStartposBoard
const ChessBoard lczero::ChessBoard::kStartposBoard static
Pre-initialized starting position board.
Definition at line 86 of file board.h.
Referenced by lczero::EncodePositionForNN().
kStartposFen
const char * lczero::ChessBoard::kStartposFen static
Initial value:
=
    "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
Standard chess starting position in FEN notation.
Definition at line 83 of file board.h.
Referenced by lczero::UciLoop::DispatchCommand(), lczero::PgnReader::Flush(), lczero::python::GameState::GameState(), lczero::Engine::NewGame(), lczero::BackendBenchmark::Run(), lczero::SelfPlayLoop::SendGameInfo(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TEST().
our_king_
Square lczero::ChessBoard::our_king_ private
Square position of the current player's king (treated as white internally).
Definition at line 350 of file board.h.
Referenced by ApplyMove(), GenerateKingAttackInfo(), GeneratePseudolegalMoves(), Hash(), IsLegalMove(), IsUnderCheck(), kings(), knights(), Mirror(), ParseMove(), PutPiece(), and SetFromFen().
our_pieces_
BitBoard lczero::ChessBoard::our_pieces_ private
Bitboard containing all pieces of the current player (treated as white internally).
Definition at line 332 of file board.h.
Referenced by ApplyMove(), GenerateKingAttackInfo(), GeneratePseudolegalMoves(), Hash(), HasMatingMaterial(), IsUnderAttack(), knights(), Mirror(), ours(), ParseMove(), PutPiece(), and SetFromFen().
pawns_
BitBoard lczero::ChessBoard::pawns_ private
Bitboard containing all pawns and en passant markers.
Ranks 1 and 8 have special meaning. A pawn at rank 1 indicates that the corresponding white pawn on rank 4 can be captured en passant. Rank 8 is similar for black pawns. These "fake" pawns are not present in our_pieces_ and their_pieces_ bitboards.
Definition at line 347 of file board.h.
Referenced by ApplyMove(), en_passant(), GenerateKingAttackInfo(), GeneratePseudolegalMoves(), Hash(), HasMatingMaterial(), IsUnderAttack(), Mirror(), ParseMove(), pawns(), PutPiece(), and SetFromFen().
rooks_
BitBoard lczero::ChessBoard::rooks_ private
Bitboard containing all rooks and queens (both players).
Definition at line 338 of file board.h.
Referenced by ApplyMove(), bishops(), GenerateKingAttackInfo(), GeneratePseudolegalMoves(), Hash(), HasMatingMaterial(), IsUnderAttack(), knights(), Mirror(), PutPiece(), queens(), and rooks().
their_king_
Square lczero::ChessBoard::their_king_ private
Square position of the opponent's king (treated as black internally).
Definition at line 353 of file board.h.
Referenced by GenerateKingAttackInfo(), Hash(), IsUnderAttack(), kings(), knights(), Mirror(), PutPiece(), and SetFromFen().
their_pieces_
BitBoard lczero::ChessBoard::their_pieces_ private
Bitboard containing all pieces of the opponent (treated as black internally).
Definition at line 335 of file board.h.
Referenced by ApplyMove(), GenerateKingAttackInfo(), GeneratePseudolegalMoves(), Hash(), HasMatingMaterial(), IsUnderAttack(), knights(), Mirror(), ParseMove(), PutPiece(), SetFromFen(), and theirs().
The documentation for this class was generated from the following files:
chess/board.h
chess/board.cc