Leela Chess Zero: lczero::dag_classic::VisitedNode_Iterator< is_const > Class Template Reference
lczero::dag_classic::VisitedNode_Iterator< is_const > Class Template Reference
#include <node.h>
Public Member Functions
VisitedNode_Iterator ()
VisitedNode_Iterator (LowNode *parent_node)
bool operator== (const VisitedNode_Iterator< is_const > &other) const
bool operator!= (const VisitedNode_Iterator< is_const > &other) const
VisitedNode_Iterator< is_const > begin ()
VisitedNode_Iterator< is_const > end ()
void operator++ ()
Node * operator* ()
Private Attributes
Node * node_ptr_ = nullptr
uint16_t current_idx_ = 0
uint16_t total_count_ = 0
Detailed Description
template<bool is_const>
class lczero::dag_classic::VisitedNode_Iterator< is_const >
Definition at line 990 of file node.h.
Constructor & Destructor Documentation
VisitedNode_Iterator() [1/2]
template<bool is_const> lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator () inline
Definition at line 993 of file node.h.
VisitedNode_Iterator() [2/2]
template<bool is_const> lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator (LowNode * parent_node) inline
Definition at line 996 of file node.h.
References lczero::dag_classic::LowNode::GetChild(), lczero::dag_classic::Node::GetN(), lczero::dag_classic::LowNode::GetNumEdges(), lczero::dag_classic::VisitedNode_Iterator< is_const >::node_ptr_, lczero::dag_classic::VisitedNode_Iterator< is_const >::operator++(), and lczero::dag_classic::VisitedNode_Iterator< is_const >::total_count_.
Member Function Documentation
begin()
template<bool is_const> VisitedNode_Iterator< is_const > lczero::dag_classic::VisitedNode_Iterator< is_const >::begin () inline
Definition at line 1015 of file node.h.
end()
template<bool is_const> VisitedNode_Iterator< is_const > lczero::dag_classic::VisitedNode_Iterator< is_const >::end () inline
Definition at line 1016 of file node.h.
operator!=()
template<bool is_const> bool lczero::dag_classic::VisitedNode_Iterator< is_const >::operator!= (const VisitedNode_Iterator< is_const > & other) const inline
Definition at line 1010 of file node.h.
References lczero::dag_classic::VisitedNode_Iterator< is_const >::node_ptr_.
operator*()
template<bool is_const> Node * lczero::dag_classic::VisitedNode_Iterator< is_const >::operator* () inline
Definition at line 1034 of file node.h.
References lczero::dag_classic::VisitedNode_Iterator< is_const >::node_ptr_.
operator++()
template<bool is_const> void lczero::dag_classic::VisitedNode_Iterator< is_const >::operator++ () inline
Definition at line 1020 of file node.h.
References lczero::dag_classic::Node::GetN(), lczero::dag_classic::Node::GetNInFlight(), lczero::dag_classic::Node::GetSibling(), and lczero::dag_classic::VisitedNode_Iterator< is_const >::node_ptr_.
Referenced by lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
operator==()
template<bool is_const> bool lczero::dag_classic::VisitedNode_Iterator< is_const >::operator== (const VisitedNode_Iterator< is_const > & other) const inline
Definition at line 1007 of file node.h.
References lczero::dag_classic::VisitedNode_Iterator< is_const >::node_ptr_.
Member Data Documentation
current_idx_
template<bool is_const> uint16_t lczero::dag_classic::VisitedNode_Iterator< is_const >::current_idx_ = 0 private
Definition at line 1039 of file node.h.
node_ptr_
template<bool is_const> Node* lczero::dag_classic::VisitedNode_Iterator< is_const >::node_ptr_ = nullptr private
Definition at line 1038 of file node.h.
Referenced by lczero::dag_classic::VisitedNode_Iterator< is_const >::operator!=(), lczero::dag_classic::VisitedNode_Iterator< is_const >::operator*(), lczero::dag_classic::VisitedNode_Iterator< is_const >::operator++(), lczero::dag_classic::VisitedNode_Iterator< is_const >::operator==(), and lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
total_count_
template<bool is_const> uint16_t lczero::dag_classic::VisitedNode_Iterator< is_const >::total_count_ = 0 private
Definition at line 1040 of file node.h.
Referenced by lczero::dag_classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
The documentation for this class was generated from the following file:
src/search/dag_classic/node.h