Leela Chess Zero: lczero::TrainingDataWriter Class Reference
lczero::TrainingDataWriter Class Reference
#include <writer.h>
Public Member Functions
TrainingDataWriter (int game_id)
TrainingDataWriter (std::string filename)
~TrainingDataWriter ()
void WriteChunk (const V6TrainingData &data)
void Finalize ()
std::string GetFileName () const
Private Attributes
std::string filename_
gzFile fout_
Detailed Description
Definition at line 37 of file writer.h.
Constructor & Destructor Documentation
TrainingDataWriter() [1/2]
lczero::TrainingDataWriter::TrainingDataWriter (int game_id)
Definition at line 48 of file writer.cc.
References lczero::CreateDirectory(), filename_, fout_, lczero::Random::Get(), and lczero::Random::GetString().
TrainingDataWriter() [2/2]
lczero::TrainingDataWriter::TrainingDataWriter (std::string filename)
Definition at line 63 of file writer.cc.
References filename_, and fout_.
~TrainingDataWriter()
lczero::TrainingDataWriter::~TrainingDataWriter () inline
Definition at line 44 of file writer.h.
References Finalize(), and fout_.
Member Function Documentation
Finalize()
void lczero::TrainingDataWriter::Finalize ()
Definition at line 77 of file writer.cc.
References fout_.
Referenced by lczero::SelfPlayTournament::PlayOneGame(), and ~TrainingDataWriter().
GetFileName()
std::string lczero::TrainingDataWriter::GetFileName () const inline
Definition at line 55 of file writer.h.
References filename_.
Referenced by lczero::SelfPlayTournament::PlayOneGame().
WriteChunk()
void lczero::TrainingDataWriter::WriteChunk (const V6TrainingData & data)
Definition at line 69 of file writer.cc.
References data, filename_, and fout_.
Referenced by lczero::V6TrainingDataArray::Write().
Member Data Documentation
filename_
std::string lczero::TrainingDataWriter::filename_ private
Definition at line 58 of file writer.h.
Referenced by GetFileName(), TrainingDataWriter(), TrainingDataWriter(), and WriteChunk().
fout_
gzFile lczero::TrainingDataWriter::fout_ private
Definition at line 59 of file writer.h.
Referenced by Finalize(), TrainingDataWriter(), TrainingDataWriter(), WriteChunk(), and ~TrainingDataWriter().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/trainingdata/writer.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/trainingdata/writer.cc