Leela Chess Zero: lczero::dx_backend::FCLayer Class Reference
lczero::dx_backend::FCLayer Class Reference
#include <layers_dx.h>
Public Member Functions
FCLayer (bool fp16, DxContext *dx_context, BaseLayer *ip, int C, int H, int W, bool bias, bool relu, bool tanh)
~FCLayer ()
void LoadWeights (float *cpu_weight, float *cpu_bias, DxContext *dx_context)
void Eval (int N, DXAlloc output, DXAlloc input, DXAlloc input2, DXAlloc scratch, DXAlloc scratch2, ID3D12GraphicsCommandList4 *command_list) override
Public Member Functions inherited from lczero::dx_backend::BaseLayer
int GetC () const
int GetH () const
int GetW () const
BaseLayer (int c, int h, int w, BaseLayer *ip, DxContext *dx_context, bool fp16)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
const bool use_bias_
const bool use_relu_
const bool use_tanh_
DXAlloc biases_
DXAlloc weights_
ShaderWrapper * shader_wrapper_
std::unique_ptr< GemmMetaCommand > meta_command_
Additional Inherited Members
Protected Attributes inherited from lczero::dx_backend::BaseLayer
BaseLayer * input_
DxContext * dx_context_
bool fp16_
int C
int H
int W
Detailed Description
Definition at line 175 of file layers_dx.h.
Constructor & Destructor Documentation
FCLayer()
lczero::dx_backend::FCLayer::FCLayer (bool fp16, DxContext * dx_context, BaseLayer * ip, int C, int H, int W, bool bias, bool relu, bool tanh)
Definition at line 627 of file layers_dx.cc.
References biases_, lczero::dx_backend::BaseLayer::C, lczero::dx_backend::DxContext::CreateAlloc(), lczero::dx_backend::BaseLayer::fp16_, lczero::dx_backend::BaseLayer::GetC(), lczero::dx_backend::BaseLayer::GetH(), lczero::dx_backend::DxContext::getShaderWrapper(), lczero::dx_backend::BaseLayer::GetW(), lczero::dx_backend::BaseLayer::H, meta_command_, shader_wrapper_, use_bias_, lczero::dx_backend::BaseLayer::W, and weights_.
~FCLayer()
lczero::dx_backend::FCLayer::~FCLayer ()
Definition at line 708 of file layers_dx.cc.
References biases_, lczero::dx_backend::DXAlloc::resource, and weights_.
Member Function Documentation
Eval()
void lczero::dx_backend::FCLayer::Eval (int N, DXAlloc output, DXAlloc input, DXAlloc input2, DXAlloc scratch, DXAlloc scratch2, ID3D12GraphicsCommandList4 * command_list) override virtual
Implements lczero::dx_backend::BaseLayer.
Definition at line 687 of file layers_dx.cc.
References lczero::dx_backend::ShaderWrapper::AddVectors(), biases_, lczero::dx_backend::BaseLayer::C, lczero::dx_backend::DivUp(), lczero::dx_backend::BaseLayer::dx_context_, lczero::dx_backend::BaseLayer::fp16_, lczero::dx_backend::BaseLayer::GetC(), lczero::dx_backend::BaseLayer::GetH(), lczero::dx_backend::BaseLayer::GetW(), lczero::dx_backend::BaseLayer::H, input, lczero::dx_backend::BaseLayer::input_, lczero::dx_backend::ShaderWrapper::MatrixMultiply(), meta_command_, output, shader_wrapper_, lczero::dx_backend::DxContext::UavBarrier(), use_bias_, use_relu_, use_tanh_, lczero::dx_backend::BaseLayer::W, and weights_.
LoadWeights()
void lczero::dx_backend::FCLayer::LoadWeights (float * cpu_weight, float * cpu_bias, DxContext * dx_context)
Definition at line 656 of file layers_dx.cc.
References biases_, lczero::dx_backend::BaseLayer::C, lczero::cudnn_backend::CpuTranspose(), lczero::dx_backend::BaseLayer::fp16_, lczero::dx_backend::BaseLayer::GetC(), lczero::dx_backend::BaseLayer::GetH(), lczero::dx_backend::BaseLayer::GetW(), lczero::dx_backend::BaseLayer::H, lczero::dx_backend::BaseLayer::input_, lczero::dx_backend::DxContext::ScheduleUpload(), lczero::dx_backend::BaseLayer::W, and weights_.
Member Data Documentation
biases_
DXAlloc lczero::dx_backend::FCLayer::biases_ private
Definition at line 194 of file layers_dx.h.
Referenced by Eval(), FCLayer(), LoadWeights(), and ~FCLayer().
meta_command_
std::unique_ptr<GemmMetaCommand> lczero::dx_backend::FCLayer::meta_command_ private
Definition at line 197 of file layers_dx.h.
Referenced by Eval(), and FCLayer().
shader_wrapper_
ShaderWrapper* lczero::dx_backend::FCLayer::shader_wrapper_ private
Definition at line 196 of file layers_dx.h.
Referenced by Eval(), and FCLayer().
use_bias_
const bool lczero::dx_backend::FCLayer::use_bias_ private
Definition at line 188 of file layers_dx.h.
Referenced by Eval(), and FCLayer().
use_relu_
const bool lczero::dx_backend::FCLayer::use_relu_ private
Definition at line 191 of file layers_dx.h.
Referenced by Eval().
use_tanh_
const bool lczero::dx_backend::FCLayer::use_tanh_ private
Definition at line 192 of file layers_dx.h.
Referenced by Eval().
weights_
DXAlloc lczero::dx_backend::FCLayer::weights_ private
Definition at line 195 of file layers_dx.h.
Referenced by Eval(), FCLayer(), LoadWeights(), and ~FCLayer().
The documentation for this class was generated from the following files:
src/neural/backends/dx/layers_dx.h
src/neural/backends/dx/layers_dx.cc