Leela Chess Zero: lczero::classic::StoppersHints Class Reference
lczero::classic::StoppersHints Class Reference
Hints from stoppers back to the search engine.
#include <timemgr.h>
Public Member Functions
StoppersHints ()
Default constructor initializing hints.
void Reset ()
Resets all hints to default values.
void UpdateEstimatedRemainingTimeMs (int64_t v)
Updates estimated remaining time.
int64_t GetEstimatedRemainingTimeMs () const
Gets estimated remaining time.
void UpdateEstimatedRemainingPlayouts (int64_t v)
Updates estimated remaining playouts.
int64_t GetEstimatedRemainingPlayouts () const
Gets estimated remaining playouts.
void UpdateEstimatedNps (float v)
Updates estimated nodes per second.
std::optional< float > GetEstimatedNps () const
Gets estimated nodes per second.
Private Attributes
int64_t remaining_time_ms_
Estimated remaining thinking time (ms).
int64_t remaining_playouts_
Estimated remaining playouts.
std::optional< float > estimated_nps_
Estimated nodes per second.
Detailed Description
Hints from stoppers back to the search engine.
Provides estimates for remaining resources to help with:
Watchdog thread timing for stop detection
Smart pruning to avoid exploring unpromising root moves
Definition at line 95 of file timemgr.h.
Constructor & Destructor Documentation
StoppersHints()
lczero::classic::StoppersHints::StoppersHints ()
Default constructor initializing hints.
Definition at line 35 of file timemgr.cc.
References Reset().
Member Function Documentation
GetEstimatedNps()
std::optional< float > lczero::classic::StoppersHints::GetEstimatedNps () const
Gets estimated nodes per second.
Returns
Optional NPS estimate (empty if not set).
Definition at line 54 of file timemgr.cc.
References estimated_nps_.
Referenced by lczero::classic::SmartPruningStopper::ShouldStop().
GetEstimatedRemainingPlayouts()
int64_t lczero::classic::StoppersHints::GetEstimatedRemainingPlayouts () const
Gets estimated remaining playouts.
Returns
Remaining playout count.
Definition at line 47 of file timemgr.cc.
References remaining_playouts_.
Referenced by lczero::classic::SmartPruningStopper::ShouldStop().
GetEstimatedRemainingTimeMs()
int64_t lczero::classic::StoppersHints::GetEstimatedRemainingTimeMs () const
Gets estimated remaining time.
Returns
Remaining time in milliseconds.
Definition at line 40 of file timemgr.cc.
References remaining_time_ms_.
Referenced by lczero::dag_classic::Search::MaybeTriggerStop(), lczero::classic::SmartPruningStopper::ShouldStop(), lczero::classic::Search::WatchdogThread(), and lczero::dag_classic::Search::WatchdogThread().
Reset()
void lczero::classic::StoppersHints::Reset ()
Resets all hints to default values.
Definition at line 58 of file timemgr.cc.
References estimated_nps_, remaining_playouts_, and remaining_time_ms_.
Referenced by lczero::dag_classic::Search::MaybeTriggerStop(), lczero::classic::Search::MaybeTriggerStop(), and StoppersHints().
UpdateEstimatedNps()
void lczero::classic::StoppersHints::UpdateEstimatedNps (float v)
Updates estimated nodes per second.
Parameters
v New NPS estimate.
Definition at line 52 of file timemgr.cc.
References estimated_nps_.
Referenced by lczero::dag_classic::Search::MaybeTriggerStop(), and lczero::classic::Search::MaybeTriggerStop().
UpdateEstimatedRemainingPlayouts()
void lczero::classic::StoppersHints::UpdateEstimatedRemainingPlayouts (int64_t v)
Updates estimated remaining playouts.
Parameters
v New estimate of remaining playouts.
Definition at line 44 of file timemgr.cc.
References remaining_playouts_.
Referenced by lczero::classic::VisitsStopper::ShouldStop(), lczero::classic::PlayoutsStopper::ShouldStop(), and lczero::classic::SmartPruningStopper::ShouldStop().
UpdateEstimatedRemainingTimeMs()
void lczero::classic::StoppersHints::UpdateEstimatedRemainingTimeMs (int64_t v)
Updates estimated remaining time.
Parameters
v New estimate in milliseconds.
Definition at line 37 of file timemgr.cc.
References remaining_time_ms_.
Referenced by lczero::classic::TimeLimitStopper::ShouldStop().
Member Data Documentation
estimated_nps_
std::optional<float> lczero::classic::StoppersHints::estimated_nps_ private
Estimated nodes per second.
Definition at line 135 of file timemgr.h.
Referenced by GetEstimatedNps(), Reset(), and UpdateEstimatedNps().
remaining_playouts_
int64_t lczero::classic::StoppersHints::remaining_playouts_ private
Estimated remaining playouts.
Definition at line 132 of file timemgr.h.
Referenced by GetEstimatedRemainingPlayouts(), Reset(), and UpdateEstimatedRemainingPlayouts().
remaining_time_ms_
int64_t lczero::classic::StoppersHints::remaining_time_ms_ private
Estimated remaining thinking time (ms).
Definition at line 129 of file timemgr.h.
Referenced by GetEstimatedRemainingTimeMs(), Reset(), and UpdateEstimatedRemainingTimeMs().
The documentation for this class was generated from the following files:
search/classic/stoppers/timemgr.h
search/classic/stoppers/timemgr.cc