Leela Chess Zero: lczero::cudnn_backend::ConvLayer< DataType > Class Template Reference
lczero::cudnn_backend::ConvLayer< DataType > Class Template Reference
Convolutional Layer using CuDNN.
#include <layers.h>
Public Member Functions
ConvLayer (BaseLayer< DataType > *ip, int C, int H, int W, int size, int Cin, ActivationFunction activation=ACTIVATION_NONE, bool bias=false)
Constructor for ConvLayer.
ConvLayer (bool nhwc, int C, int H, int W, int size, int Cin, ActivationFunction activation=ACTIVATION_NONE, bool bias=false)
~ConvLayer ()
void LoadWeights (float *pfilter, float *pBias, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType ***=nullptr) override
Executes the forward pass for the convolution layer.
void LoadWeights (float *pfilter, float *pBias, void *scratch)
void LoadWeights (float *pfilter, float *pBias, void *)
Public Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc)
Constructor.
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, bool use_gemm_ex)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Member Functions
void init ()
Private Attributes
const int c_input_
const int filter_size_
const ActivationFunction act_
const bool use_bias_
DataType * biases = nullptr
DataType * weights = nullptr
cudnnFilterDescriptor_t filter_desc_
cudnnConvolutionDescriptor_t conv_desc_
cudnnConvolutionFwdAlgo_t conv_algo_
cudnnTensorDescriptor_t bias_desc_
cudnnTensorDescriptor_t in_tensor_desc_
cudnnTensorDescriptor_t out_tensor_desc_
cudnnActivationDescriptor_t activation_
Additional Inherited Members
Protected Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const half *A, const half *B, half *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
Protected Attributes inherited from lczero::cudnn_backend::BaseLayer< DataType >
BaseLayer * input_
int C
int H
int W
bool nhwc_
const bool use_gemm_ex_
Detailed Description
template<typename DataType>
class lczero::cudnn_backend::ConvLayer< DataType >
Convolutional Layer using CuDNN.
Definition at line 99 of file layers.h.
Constructor & Destructor Documentation
ConvLayer() [1/2]
template<typename DataType > lczero::cudnn_backend::ConvLayer< DataType >::ConvLayer (BaseLayer< DataType > * ip, int C, int H, int W, int filter, int Cin, ActivationFunction activation = ACTIVATION_NONE, bool bias = false)
Constructor for ConvLayer.
Parameters
ip Input layer.
C Output channels.
H Output height.
W Output width.
filter Filter size.
Cin Input channels.
activation Activation function.
bias Whether to use bias.
Definition at line 203 of file layers.cc.
References lczero::cudnn_backend::ConvLayer< DataType >::init().
ConvLayer() [2/2]
template<typename DataType > lczero::cudnn_backend::ConvLayer< DataType >::ConvLayer (bool nhwc, int C, int H, int W, int size, int Cin, ActivationFunction activation = ACTIVATION_NONE, bool bias = false)
Definition at line 215 of file layers.cc.
References lczero::cudnn_backend::ConvLayer< DataType >::init().
~ConvLayer()
template<typename DataType > lczero::cudnn_backend::ConvLayer< DataType >::~ConvLayer ()
Definition at line 384 of file layers.cc.
References ReportCUDAErrors.
Member Function Documentation
Eval()
template<typename DataType > void lczero::cudnn_backend::ConvLayer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType *** = nullptr) override virtual
Executes the forward pass for the convolution layer.
Parameters
N Batch size.
output Output buffer.
input Input buffer.
input2 Second input buffer (for residual addition).
scratch Scratch memory buffer.
scratch_size Size of scratch memory.
cudnn CuDNN handle.
cublas Cublas handle.
stream CUDA stream.
Implements lczero::cudnn_backend::BaseLayer< DataType >.
Definition at line 282 of file layers.cc.
References lczero::ACTIVATION_NONE, lczero::ACTIVATION_RELU, lczero::cudnn_backend::addBias_NCHW(), lczero::cudnn_backend::addVectors(), C, input, output, and ReportCUDNNErrors.
init()
template<typename DataType > void lczero::cudnn_backend::ConvLayer< DataType >::init () private
Definition at line 133 of file layers.cc.
References lczero::ACTIVATION_RELU, C, ReportCUDAErrors, and ReportCUDNNErrors.
Referenced by lczero::cudnn_backend::ConvLayer< DataType >::ConvLayer(), and lczero::cudnn_backend::ConvLayer< DataType >::ConvLayer().
LoadWeights() [1/3]
void lczero::cudnn_backend::ConvLayer< float >::LoadWeights (float * pfilter, float * pBias, void *)
Definition at line 255 of file layers.cc.
References C, and ReportCUDAErrors.
LoadWeights() [2/3]
void lczero::cudnn_backend::ConvLayer< half >::LoadWeights (float * pfilter, float * pBias, void * scratch)
Definition at line 227 of file layers.cc.
References C, lczero::cudnn_backend::convertNCHWtoNHWC(), lczero::cudnn_backend::copyTypeConverted(), and ReportCUDAErrors.
LoadWeights() [3/3]
template<typename DataType > void lczero::cudnn_backend::ConvLayer< DataType >::LoadWeights (float * pfilter, float * pBias, void * scratch)
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::cudnn_backend::ConvLayer< DataType >::act_ private
Definition at line 125 of file layers.h.
activation_
template<typename DataType > cudnnActivationDescriptor_t lczero::cudnn_backend::ConvLayer< DataType >::activation_ private
Definition at line 138 of file layers.h.
bias_desc_
template<typename DataType > cudnnTensorDescriptor_t lczero::cudnn_backend::ConvLayer< DataType >::bias_desc_ private
Definition at line 135 of file layers.h.
biases
template<typename DataType > DataType* lczero::cudnn_backend::ConvLayer< DataType >::biases = nullptr private
Definition at line 128 of file layers.h.
c_input_
template<typename DataType > const int lczero::cudnn_backend::ConvLayer< DataType >::c_input_ private
Definition at line 123 of file layers.h.
conv_algo_
template<typename DataType > cudnnConvolutionFwdAlgo_t lczero::cudnn_backend::ConvLayer< DataType >::conv_algo_ private
Definition at line 133 of file layers.h.
conv_desc_
template<typename DataType > cudnnConvolutionDescriptor_t lczero::cudnn_backend::ConvLayer< DataType >::conv_desc_ private
Definition at line 132 of file layers.h.
filter_desc_
template<typename DataType > cudnnFilterDescriptor_t lczero::cudnn_backend::ConvLayer< DataType >::filter_desc_ private
Definition at line 131 of file layers.h.
filter_size_
template<typename DataType > const int lczero::cudnn_backend::ConvLayer< DataType >::filter_size_ private
Definition at line 124 of file layers.h.
in_tensor_desc_
template<typename DataType > cudnnTensorDescriptor_t lczero::cudnn_backend::ConvLayer< DataType >::in_tensor_desc_ private
Definition at line 136 of file layers.h.
out_tensor_desc_
template<typename DataType > cudnnTensorDescriptor_t lczero::cudnn_backend::ConvLayer< DataType >::out_tensor_desc_ private
Definition at line 137 of file layers.h.
use_bias_
template<typename DataType > const bool lczero::cudnn_backend::ConvLayer< DataType >::use_bias_ private
Definition at line 126 of file layers.h.
weights
template<typename DataType > DataType* lczero::cudnn_backend::ConvLayer< DataType >::weights = nullptr private
Definition at line 129 of file layers.h.
The documentation for this class was generated from the following files:
neural/backends/cuda/layers.h
neural/backends/cuda/layers.cc