Leela Chess Zero: lczero::classic::Edge_Iterator< is_const > Class Template Reference
lczero::classic::Edge_Iterator< is_const > Class Template Reference
#include <node.h>
Public Types
using Ptr = std::conditional_t< is_const, const std::unique_ptr< Node > *, std::unique_ptr< Node > * >
using value_type = Edge_Iterator
using iterator_category = std::forward_iterator_tag
using difference_type = std::ptrdiff_t
using pointer = Edge_Iterator *
using reference = Edge_Iterator &
Public Member Functions
Edge_Iterator ()
Edge_Iterator (const Node &parent_node, Ptr child_ptr)
Edge_Iterator< is_const > begin ()
Edge_Iterator< is_const > end ()
void operator++ ()
Edge_Iterator & operator* ()
Node * GetOrSpawnNode (Node *parent)
Public Member Functions inherited from lczero::classic::EdgeAndNode
EdgeAndNode ()=default
Default constructor creating a null pair.
EdgeAndNode (Edge *edge, Node *node)
Constructs an EdgeAndNode with the given edge and node.
void Reset ()
Resets this pair to null state.
operator bool () const
Boolean conversion operator.
bool operator== (const EdgeAndNode &other) const
Equality comparison operator.
bool operator!= (const EdgeAndNode &other) const
Inequality comparison operator.
bool HasNode () const
Checks if this edge has an expanded node.
Edge * edge () const
Gets the edge pointer.
Node * node () const
Gets the node pointer.
float GetQ (float default_q, float draw_score) const
Gets Q value with default for unexpanded nodes.
float GetWL (float default_wl) const
Gets WL value with default for unexpanded nodes.
float GetD (float default_d) const
Gets draw probability with default for unexpanded nodes.
float GetM (float default_m) const
Gets moves left estimate with default for unexpanded nodes.
uint32_t GetN () const
Gets visit count from node.
int GetNStarted () const
Gets started visits from node.
uint32_t GetNInFlight () const
Gets in-flight visits from node.
bool IsTerminal () const
Checks if node is terminal.
bool IsTbTerminal () const
Checks if node is tablebase terminal.
Node::Bounds GetBounds () const
Gets game result bounds from node.
float GetP () const
Gets policy prior from edge.
Move GetMove (bool flip=false) const
Gets move from edge.
float GetU (float numerator) const
Calculates the UCT exploration bonus U.
std::string DebugString () const
Returns debug string representation.
Private Member Functions
void Actualize ()
Private Attributes
Ptr node_ptr_
uint16_t current_idx_ = 0
uint16_t total_count_ = 0
Additional Inherited Members
Protected Attributes inherited from lczero::classic::EdgeAndNode
Edge * edge_ = nullptr
Edge pointer (nullptr indicates null pair).
Node * node_ = nullptr
Node pointer (nullptr if edge not yet expanded).
Detailed Description
template<bool is_const>
class lczero::classic::Edge_Iterator< is_const >
Definition at line 646 of file node.h.
Member Typedef Documentation
difference_type
template<bool is_const> using lczero::classic::Edge_Iterator< is_const >::difference_type = std::ptrdiff_t
Definition at line 652 of file node.h.
iterator_category
template<bool is_const> using lczero::classic::Edge_Iterator< is_const >::iterator_category = std::forward_iterator_tag
Definition at line 651 of file node.h.
pointer
template<bool is_const> using lczero::classic::Edge_Iterator< is_const >::pointer = Edge_Iterator*
Definition at line 653 of file node.h.
Ptr
template<bool is_const> using lczero::classic::Edge_Iterator< is_const >::Ptr = std::conditional_t<is_const, const std::unique_ptr<Node>*, std::unique_ptr<Node>*>
Definition at line 648 of file node.h.
reference
template<bool is_const> using lczero::classic::Edge_Iterator< is_const >::reference = Edge_Iterator&
Definition at line 654 of file node.h.
value_type
template<bool is_const> using lczero::classic::Edge_Iterator< is_const >::value_type = Edge_Iterator
Definition at line 650 of file node.h.
Constructor & Destructor Documentation
Edge_Iterator() [1/2]
template<bool is_const> lczero::classic::Edge_Iterator< is_const >::Edge_Iterator () inline
Definition at line 657 of file node.h.
Edge_Iterator() [2/2]
template<bool is_const> lczero::classic::Edge_Iterator< is_const >::Edge_Iterator (const Node & parent_node, Ptr child_ptr) inline
Definition at line 661 of file node.h.
References lczero::classic::Edge_Iterator< is_const >::Actualize(), lczero::classic::Node::child_, lczero::classic::EdgeAndNode::edge_, and lczero::classic::EdgeAndNode::node_.
Member Function Documentation
Actualize()
template<bool is_const> void lczero::classic::Edge_Iterator< is_const >::Actualize () inline private
Definition at line 724 of file node.h.
References lczero::classic::Edge_Iterator< is_const >::current_idx_, lczero::classic::EdgeAndNode::node_, lczero::classic::Edge_Iterator< is_const >::node_ptr_, and lczero::classic::Node::sibling_.
Referenced by lczero::classic::Edge_Iterator< is_const >::Edge_Iterator(), lczero::classic::Edge_Iterator< is_const >::GetOrSpawnNode(), and lczero::classic::Edge_Iterator< is_const >::operator++().
begin()
template<bool is_const> Edge_Iterator< is_const > lczero::classic::Edge_Iterator< is_const >::begin () inline
Definition at line 672 of file node.h.
end()
template<bool is_const> Edge_Iterator< is_const > lczero::classic::Edge_Iterator< is_const >::end () inline
Definition at line 673 of file node.h.
GetOrSpawnNode()
template<bool is_const> Node * lczero::classic::Edge_Iterator< is_const >::GetOrSpawnNode (Node * parent) inline
Definition at line 693 of file node.h.
References lczero::classic::Edge_Iterator< is_const >::Actualize(), lczero::classic::Edge_Iterator< is_const >::current_idx_, lczero::classic::EdgeAndNode::node_, and lczero::classic::Edge_Iterator< is_const >::node_ptr_.
Referenced by lczero::classic::SearchWorker::PickNodesToExtendTask().
operator*()
template<bool is_const> Edge_Iterator & lczero::classic::Edge_Iterator< is_const >::operator* () inline
Definition at line 690 of file node.h.
operator++()
template<bool is_const> void lczero::classic::Edge_Iterator< is_const >::operator++ () inline
Definition at line 677 of file node.h.
References lczero::classic::Edge_Iterator< is_const >::Actualize(), lczero::classic::Edge_Iterator< is_const >::current_idx_, lczero::classic::EdgeAndNode::edge_, lczero::classic::EdgeAndNode::node_, lczero::classic::Edge_Iterator< is_const >::node_ptr_, and lczero::classic::Edge_Iterator< is_const >::total_count_.
Member Data Documentation
current_idx_
template<bool is_const> uint16_t lczero::classic::Edge_Iterator< is_const >::current_idx_ = 0 private
Definition at line 747 of file node.h.
Referenced by lczero::classic::Edge_Iterator< is_const >::Actualize(), lczero::classic::Edge_Iterator< is_const >::GetOrSpawnNode(), and lczero::classic::Edge_Iterator< is_const >::operator++().
node_ptr_
template<bool is_const> Ptr lczero::classic::Edge_Iterator< is_const >::node_ptr_ private
Definition at line 746 of file node.h.
Referenced by lczero::classic::Edge_Iterator< is_const >::Actualize(), lczero::classic::Edge_Iterator< is_const >::GetOrSpawnNode(), and lczero::classic::Edge_Iterator< is_const >::operator++().
total_count_
template<bool is_const> uint16_t lczero::classic::Edge_Iterator< is_const >::total_count_ = 0 private
Definition at line 748 of file node.h.
Referenced by lczero::classic::Edge_Iterator< is_const >::operator++().
The documentation for this class was generated from the following file:
src/search/classic/node.h