Leela Chess Zero: lczero::LogMessage Class Reference
lczero::LogMessage Class Reference
#include <logging.h>
Public Member Functions
LogMessage (const char *file, int line)
~LogMessage ()
Detailed Description
Definition at line 61 of file logging.h.
Constructor & Destructor Documentation
LogMessage()
lczero::LogMessage::LogMessage (const char * file, int line)
Definition at line 72 of file logging.cc.
References lczero::FormatTime().
~LogMessage()
lczero::LogMessage::~LogMessage ()
Definition at line 78 of file logging.cc.
References lczero::Logging::Get(), and lczero::Logging::WriteLineRaw().
The documentation for this class was generated from the following files:
src/utils/logging.h
src/utils/logging.cc