Leela Chess Zero: lczero::SelfPlayTournament Class Reference
lczero::SelfPlayTournament Class Reference abstract
#include <tournament.h>
Public Member Functions
SelfPlayTournament (const OptionsDict &options, UciResponder *uci_responder, GameInfo::Callback game_info, TournamentInfo::Callback tournament_info)
void StartAsync ()
void RunBlocking ()
void Wait ()
void Abort ()
void Stop ()
~SelfPlayTournament ()
Static Public Member Functions
static void PopulateOptions (OptionsParser *options)
Private Member Functions
void Worker ()
void PlayOneGame (int game_id)
void PlayMultiGames (int game_id, size_t game_count)
void SaveResults () REQUIRES(mutex_)
bool first_game_black_ GUARDED_BY (mutex_)
std::unique_ptr< SyzygyTablebase > syzygy_tb_ GUARDED_BY (mutex_)
std::vector< Opening > discard_pile_ GUARDED_BY (mutex_)
int games_count_ GUARDED_BY (mutex_)=0
bool abort_ GUARDED_BY (mutex_)
std::vector< Opening > openings_ GUARDED_BY (mutex_)
std::list< std::unique_ptr< SelfPlayGame > > games_ GUARDED_BY (mutex_)
std::list< std::unique_ptr< MultiSelfPlayGames > > multigames_ GUARDED_BY (mutex_)
TournamentInfo tournament_info_ GUARDED_BY (mutex_)
std::vector< std::thread > threads_ GUARDED_BY (threads_mutex_)
Private Attributes
Mutex mutex_
Mutex threads_mutex_
std::shared_ptr< Backend > backends_ [2][2]
const OptionsDict player_options_ [2][2]
SelfPlayLimits search_limits_ [2][2]
UciResponder * uci_responder_
GameInfo::Callback game_callback_
TournamentInfo::Callback tournament_callback_
const int kTotalGames
const bool kShareTree
const size_t kParallelism
const bool kTraining
const float kResignPlaythrough
const int kPolicyGamesSize
const int kValueGamesSize
int multi_games_size_
const std::string kTournamentResultsFile
const float kDiscardedStartChance
Detailed Description
Definition at line 44 of file tournament.h.
Constructor & Destructor Documentation
SelfPlayTournament()
lczero::SelfPlayTournament::SelfPlayTournament (const OptionsDict & options, UciResponder * uci_responder, GameInfo::Callback game_info, TournamentInfo::Callback tournament_info)
Definition at line 160 of file tournament.cc.
References lczero::OptionsDict::GetSubdict().
~SelfPlayTournament()
lczero::SelfPlayTournament::~SelfPlayTournament ()
Definition at line 641 of file tournament.cc.
Member Function Documentation
Abort()
void lczero::SelfPlayTournament::Abort ()
Definition at line 627 of file tournament.cc.
References abort_, and mutex_.
GUARDED_BY() [1/10]
bool first_game_black_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [2/10]
std::unique_ptr< SyzygyTablebase > syzygy_tb_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [3/10]
std::vector< Opening > discard_pile_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [4/10]
bool abort_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [5/10]
std::vector< Opening > openings_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [6/10]
std::list< std::unique_ptr< SelfPlayGame > > games_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [7/10]
std::list< std::unique_ptr< MultiSelfPlayGames > > multigames_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [8/10]
TournamentInfo tournament_info_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private
GUARDED_BY() [9/10]
int games_count_ lczero::SelfPlayTournament::GUARDED_BY (mutex_) private pure virtual
GUARDED_BY() [10/10]
std::vector< std::thread > threads_ lczero::SelfPlayTournament::GUARDED_BY (threads_mutex_) private
PlayMultiGames()
void lczero::SelfPlayTournament::PlayMultiGames (int game_id, size_t game_count) private
Definition at line 439 of file tournament.cc.
References abort_, lczero::PlayerOptions::backend, backends_, lczero::GameInfo::game_id, lczero::GameInfo::game_result, lczero::GameInfo::initial_fen, lczero::GameInfo::is_black, lczero::GameInfo::moves, mutex_, lczero::GameInfo::play_start_ply, and result.
PlayOneGame()
void lczero::SelfPlayTournament::PlayOneGame (int game_id) private
Definition at line 275 of file tournament.cc.
References lczero::PlayerOptions::backend, backends_, lczero::TrainingDataWriter::Finalize(), lczero::BestMoveInfo::game_id, lczero::GameInfo::game_id, lczero::GameInfo::game_result, lczero::TrainingDataWriter::GetFileName(), idx, lczero::GameInfo::initial_fen, lczero::BestMoveInfo::is_black, lczero::GameInfo::is_black, lczero::GameInfo::min_false_positive_threshold, lczero::GameInfo::moves, moves, mutex_, lczero::GameInfo::play_start_ply, lczero::BestMoveInfo::player, result, lczero::Opening::start_fen, and lczero::GameInfo::training_filename.
PopulateOptions()
void lczero::SelfPlayTournament::PopulateOptions (OptionsParser * options) static
Definition at line 103 of file tournament.cc.
References lczero::OptionsParser::Add(), lczero::OptionsDict::AddAliasDict(), lczero::OptionsParser::AddContext(), lczero::OptionsDict::AddSubdict(), lczero::OptionsParser::GetMutableDefaultsOptions(), lczero::OptionsParser::GetMutableOptions(), lczero::OptionsParser::GetOptionsDict(), lczero::SharedBackendParams::kBackendId, lczero::classic::BaseSearchParams::kCacheHistoryLengthId, lczero::classic::BaseSearchParams::kCpuctFactorId, lczero::classic::BaseSearchParams::kCpuctId, lczero::classic::BaseSearchParams::kFpuValueId, lczero::SharedBackendParams::kHistoryFill, lczero::classic::BaseSearchParams::kMaxCollisionEventsId, lczero::classic::BaseSearchParams::kMaxCollisionVisitsId, lczero::classic::BaseSearchParams::kMiniBatchSizeId, lczero::classic::BaseSearchParams::kNoiseEpsilonId, lczero::classic::BaseSearchParams::kOutOfOrderEvalId, lczero::SharedBackendParams::kPolicySoftmaxTemp, lczero::classic::BaseSearchParams::kStickyEndgamesId, lczero::classic::BaseSearchParams::kTaskWorkersPerSearchWorkerId, lczero::classic::BaseSearchParams::kTemperatureId, lczero::classic::BaseSearchParams::kTwoFoldDrawsId, lczero::SharedBackendParams::Populate(), lczero::classic::SearchParams::Populate(), lczero::SelfPlayGame::PopulateUciParams(), and lczero::OptionsDict::Set().
Referenced by lczero::SelfPlayLoop::Run().
RunBlocking()
void lczero::SelfPlayTournament::RunBlocking ()
Definition at line 593 of file tournament.cc.
References abort_, and mutex_.
Referenced by lczero::SelfPlayLoop::Run().
SaveResults()
void lczero::SelfPlayTournament::SaveResults () private
Definition at line 646 of file tournament.cc.
References output.
StartAsync()
void lczero::SelfPlayTournament::StartAsync ()
Definition at line 586 of file tournament.cc.
References threads_.
Stop()
void lczero::SelfPlayTournament::Stop ()
Definition at line 636 of file tournament.cc.
References abort_, and mutex_.
Wait()
void lczero::SelfPlayTournament::Wait ()
Definition at line 609 of file tournament.cc.
References abort_, mutex_, and threads_.
Worker()
void lczero::SelfPlayTournament::Worker () private
Definition at line 537 of file tournament.cc.
References abort_, and mutex_.
Member Data Documentation
backends_
std::shared_ptr<Backend> lczero::SelfPlayTournament::backends_[2][2] private
Definition at line 98 of file tournament.h.
game_callback_
GameInfo::Callback lczero::SelfPlayTournament::game_callback_ private
Definition at line 103 of file tournament.h.
kDiscardedStartChance
const float lczero::SelfPlayTournament::kDiscardedStartChance private
Definition at line 114 of file tournament.h.
kParallelism
const size_t lczero::SelfPlayTournament::kParallelism private
Definition at line 107 of file tournament.h.
kPolicyGamesSize
const int lczero::SelfPlayTournament::kPolicyGamesSize private
Definition at line 110 of file tournament.h.
kResignPlaythrough
const float lczero::SelfPlayTournament::kResignPlaythrough private
Definition at line 109 of file tournament.h.
kShareTree
const bool lczero::SelfPlayTournament::kShareTree private
Definition at line 106 of file tournament.h.
kTotalGames
const int lczero::SelfPlayTournament::kTotalGames private
Definition at line 105 of file tournament.h.
kTournamentResultsFile
const std::string lczero::SelfPlayTournament::kTournamentResultsFile private
Definition at line 113 of file tournament.h.
kTraining
const bool lczero::SelfPlayTournament::kTraining private
Definition at line 108 of file tournament.h.
kValueGamesSize
const int lczero::SelfPlayTournament::kValueGamesSize private
Definition at line 111 of file tournament.h.
multi_games_size_
int lczero::SelfPlayTournament::multi_games_size_ private
Definition at line 112 of file tournament.h.
mutex_
Mutex lczero::SelfPlayTournament::mutex_ private
Definition at line 77 of file tournament.h.
player_options_
const OptionsDict lczero::SelfPlayTournament::player_options_[2][2] private
Definition at line 99 of file tournament.h.
search_limits_
SelfPlayLimits lczero::SelfPlayTournament::search_limits_[2][2] private
Definition at line 100 of file tournament.h.
threads_mutex_
Mutex lczero::SelfPlayTournament::threads_mutex_ private
Definition at line 94 of file tournament.h.
tournament_callback_
TournamentInfo::Callback lczero::SelfPlayTournament::tournament_callback_ private
Definition at line 104 of file tournament.h.
uci_responder_
UciResponder* lczero::SelfPlayTournament::uci_responder_ private
Definition at line 102 of file tournament.h.
The documentation for this class was generated from the following files:
src/selfplay/tournament.h
src/selfplay/tournament.cc