Leela Chess Zero: lczero::OptionsDict Class Reference
lczero::OptionsDict Class Reference
#include <optionsdict.h>
Public Member Functions
OptionsDict (const OptionsDict *parent=nullptr)
template<typename T >
T Get (const std::string &key) const
template<typename T >
T Get (const OptionId &option_id) const
template<typename T >
std::optional< T > OwnGet (const std::string &key) const
template<typename T >
std::optional< T > OwnGet (const OptionId &option_id) const
template<typename T >
bool Exists (const std::string &key) const
template<typename T >
bool Exists (const OptionId &option_id) const
template<typename T >
void EnsureExists (const OptionId &option_id) const
template<typename T >
bool OwnExists (const std::string &key) const
template<typename T >
bool OwnExists (const OptionId &option_id) const
template<typename T >
T GetOrDefault (const std::string &key, const T &default_val) const
template<typename T >
T GetOrDefault (const OptionId &option_id, const T &default_val) const
template<typename T >
void Set (const std::string &key, const T &value)
template<typename T >
void Set (const OptionId &option_id, const T &value)
template<typename T >
T & GetRef (const std::string &key)
template<typename T >
T & GetRef (const OptionId &option_id)
template<typename T >
bool IsDefault (const std::string &key) const
template<typename T >
bool IsDefault (const OptionId &option_id) const
const OptionsDict & GetSubdict (const std::string &name) const
OptionsDict * GetMutableSubdict (const std::string &name)
OptionsDict * AddSubdict (const std::string &name)
std::vector< std::string > ListSubdicts () const
void AddAliasDict (const OptionsDict *dict)
void AddSubdictFromString (const std::string &str)
void CheckAllOptionsRead (const std::string &path_from_parent) const
bool HasSubdict (const std::string &name) const
Static Private Member Functions
static std::string GetOptionId (const OptionId &option_id)
Private Attributes
const OptionsDict * parent_ = nullptr
std::map< std::string, OptionsDict > subdicts_
std::vector< const OptionsDict * > aliases_
Additional Inherited Members
Private Member Functions inherited from lczero::TypeDict< bool >
void EnsureNoUnusedOptions (const std::string &type_name, const std::string &prefix) const
const std::unordered_map< std::string, V > & dict () const
std::unordered_map< std::string, V > * mutable_dict ()
Private Member Functions inherited from lczero::TypeDict< Button >
void EnsureNoUnusedOptions (const std::string &type_name, const std::string &prefix) const
const std::unordered_map< std::string, V > & dict () const
std::unordered_map< std::string, V > * mutable_dict ()
Private Member Functions inherited from lczero::TypeDict< int >
void EnsureNoUnusedOptions (const std::string &type_name, const std::string &prefix) const
const std::unordered_map< std::string, V > & dict () const
std::unordered_map< std::string, V > * mutable_dict ()
Private Member Functions inherited from lczero::TypeDict< std::string >
void EnsureNoUnusedOptions (const std::string &type_name, const std::string &prefix) const
const std::unordered_map< std::string, V > & dict () const
std::unordered_map< std::string, V > * mutable_dict ()
Private Member Functions inherited from lczero::TypeDict< float >
void EnsureNoUnusedOptions (const std::string &type_name, const std::string &prefix) const
const std::unordered_map< std::string, V > & dict () const
std::unordered_map< std::string, V > * mutable_dict ()
Detailed Description
Definition at line 163 of file optionsdict.h.
Constructor & Destructor Documentation
OptionsDict()
lczero::OptionsDict::OptionsDict (const OptionsDict * parent = nullptr) inline explicit
Definition at line 169 of file optionsdict.h.
Member Function Documentation
AddAliasDict()
void lczero::OptionsDict::AddAliasDict (const OptionsDict * dict)
Definition at line 63 of file optionsdict.cc.
References aliases_, and lczero::TypeDict< bool >::dict().
Referenced by lczero::SelfPlayTournament::PopulateOptions().
AddSubdict()
OptionsDict * lczero::OptionsDict::AddSubdict (const std::string & name)
Definition at line 55 of file optionsdict.cc.
References name, and subdicts_.
Referenced by lczero::OptionsParser::AddContext(), and lczero::SelfPlayTournament::PopulateOptions().
AddSubdictFromString()
void lczero::OptionsDict::AddSubdictFromString (const std::string & str)
Definition at line 326 of file optionsdict.cc.
Referenced by lczero::python::Backend::Backend(), lczero::NetworkAsBackendFactory::Create(), lczero::NetworkFactory::LoadNetwork(), and lczero::classic::MakeTimeManager().
CheckAllOptionsRead()
void lczero::OptionsDict::CheckAllOptionsRead (const std::string & path_from_parent) const
Definition at line 331 of file optionsdict.cc.
References lczero::TypeDict< bool >::dict(), lczero::TypeDict< T >::EnsureNoUnusedOptions(), and subdicts_.
Referenced by lczero::NetworkFactory::LoadNetwork().
EnsureExists()
template<typename T > void lczero::OptionsDict::EnsureExists (const OptionId & option_id) const
Definition at line 309 of file optionsdict.h.
References lczero::OptionId::long_flag().
Exists() [1/2]
template<typename T > bool lczero::OptionsDict::Exists (const OptionId & option_id) const
Definition at line 305 of file optionsdict.h.
References GetOptionId().
Exists() [2/2]
template<typename T > bool lczero::OptionsDict::Exists (const std::string & key) const
Definition at line 298 of file optionsdict.h.
References aliases_, Exists(), key, and parent_.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), Exists(), lczero::onnx::MakeOnnxNetwork(), lczero::OnednnNetwork::OnednnNetwork(), and lczero::SyclNetwork< DataType >::SyclNetwork().
Get() [1/2]
template<typename T > T lczero::OptionsDict::Get (const OptionId & option_id) const
Definition at line 280 of file optionsdict.h.
References GetOptionId().
Get() [2/2]
template<typename T > T lczero::OptionsDict::Get (const std::string & key) const
Definition at line 271 of file optionsdict.h.
References aliases_, Get(), key, parent_, and value.
Referenced by lczero::Backend::ConfigurationHash(), lczero::ConvertLeelaToOnnx(), lczero::ConvertOnnxToLeela(), lczero::NetworkAsBackendFactory::Create(), lczero::BackendManager::CreateFromParams(), lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), lczero::DescribeNetworkCmd(), lczero::Engine::Engine(), lczero::Engine::EnsureSyzygyTablebasesLoaded(), Get(), lczero::classic::BaseSearchParams::GetContemptMode(), lczero::classic::BaseSearchParams::GetLogLiveStats(), lczero::classic::SearchParams::GetMaxPrefetchBatch(), lczero::classic::BaseSearchParams::GetMultiPv(), lczero::classic::BaseSearchParams::GetPerPvCounters(), lczero::classic::BaseSearchParams::GetScoreType(), lczero::classic::BaseSearchParams::GetTempDecayDelayMoves(), lczero::classic::BaseSearchParams::GetTempDecayMoves(), lczero::classic::BaseSearchParams::GetTemperature(), lczero::classic::BaseSearchParams::GetTemperatureCutoffMove(), lczero::classic::BaseSearchParams::GetTemperatureEndgame(), lczero::classic::BaseSearchParams::GetTemperatureVisitOffset(), lczero::classic::BaseSearchParams::GetTemperatureWinpctCutoff(), lczero::StringOption::GetVal(), lczero::IntOption::GetVal(), lczero::FloatOption::GetVal(), lczero::BoolOption::GetVal(), lczero::ChoiceOption::GetVal(), lczero::classic::BaseSearchParams::GetVerboseStats(), lczero::StringUciResponder::IsChess960(), lczero::NetworkFactory::LoadNetwork(), lczero::onnx::MakeOnnxNetwork(), lczero::classic::MakeTimeManager(), lczero::OnednnNetwork::OnednnNetwork(), lczero::StringUciResponder::OutputThinkingInfo(), lczero::SelfPlayGame::Play(), lczero::classic::PopulateIntrinsicStoppers(), lczero::SelfPlayLoop::Run(), lczero::RunRescorer(), lczero::SelfPlayGame::SelfPlayGame(), lczero::Engine::SetPosition(), lczero::SyclNetwork< DataType >::SyclNetwork(), and lczero::Engine::UpdateBackendConfig().
GetMutableSubdict()
OptionsDict * lczero::OptionsDict::GetMutableSubdict (const std::string & name)
Definition at line 47 of file optionsdict.cc.
References name, and subdicts_.
Referenced by lczero::OptionsParser::GetMutableOptions().
GetOptionId()
static std::string lczero::OptionsDict::GetOptionId (const OptionId & option_id) inline static private
Definition at line 259 of file optionsdict.h.
Referenced by Exists(), Get(), GetOrDefault(), GetRef(), IsDefault(), OwnExists(), OwnGet(), and Set().
GetOrDefault() [1/2]
template<typename T > T lczero::OptionsDict::GetOrDefault (const OptionId & option_id, const T & default_val) const
Definition at line 338 of file optionsdict.h.
References GetOptionId().
GetOrDefault() [2/2]
template<typename T > T lczero::OptionsDict::GetOrDefault (const std::string & key, const T & default_val) const
Definition at line 328 of file optionsdict.h.
References aliases_, GetOrDefault(), key, parent_, and value.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), lczero::dx_backend::DxContext::DxContext(), lczero::dx_backend::DxNetwork::DxNetwork(), GetOrDefault(), lczero::MakeCudaNetworkAuto(), lczero::MakeCudnnNetworkAuto(), lczero::onnx::MakeOnnxNetwork(), lczero::MakeSyclNetworkAuto(), lczero::metal_backend::MetalNetwork::MetalNetwork(), lczero::OnednnNetwork::OnednnNetwork(), lczero::onnx::OnnxNetwork::OnnxNetwork(), and lczero::SyclNetwork< DataType >::SyclNetwork().
GetRef() [1/2]
template<typename T > T & lczero::OptionsDict::GetRef (const OptionId & option_id)
Definition at line 357 of file optionsdict.h.
References GetOptionId().
GetRef() [2/2]
template<typename T > T & lczero::OptionsDict::GetRef (const std::string & key)
Definition at line 353 of file optionsdict.h.
References key.
Referenced by lczero::OptionsParser::Add().
GetSubdict()
const OptionsDict & lczero::OptionsDict::GetSubdict (const std::string & name) const
Definition at line 39 of file optionsdict.cc.
References name, and subdicts_.
Referenced by lczero::OptionsParser::GetOptionsDict(), and lczero::SelfPlayTournament::SelfPlayTournament().
HasSubdict()
bool lczero::OptionsDict::HasSubdict (const std::string & name) const
Definition at line 76 of file optionsdict.cc.
References name, and subdicts_.
IsDefault() [1/2]
template<typename T > bool lczero::OptionsDict::IsDefault (const OptionId & option_id) const
Definition at line 370 of file optionsdict.h.
References GetOptionId().
IsDefault() [2/2]
template<typename T > bool lczero::OptionsDict::IsDefault (const std::string & key) const
Definition at line 362 of file optionsdict.h.
References aliases_, IsDefault(), key, and parent_.
Referenced by IsDefault(), lczero::classic::MakeTimeManager(), and lczero::RunRescorer().
ListSubdicts()
std::vector< std::string > lczero::OptionsDict::ListSubdicts () const
Definition at line 68 of file optionsdict.cc.
References result, and subdicts_.
Referenced by lczero::OptionsParser::ShowHelp().
OwnExists() [1/2]
template<typename T > bool lczero::OptionsDict::OwnExists (const OptionId & option_id) const
Definition at line 323 of file optionsdict.h.
References GetOptionId().
OwnExists() [2/2]
template<typename T > bool lczero::OptionsDict::OwnExists (const std::string & key) const
Definition at line 317 of file optionsdict.h.
References lczero::TypeDict< T >::dict(), lczero::TypeDict< bool >::dict(), and key.
Referenced by lczero::ConvertLeelaToOnnx(), and lczero::ConvertOnnxToLeela().
OwnGet() [1/2]
template<typename T > std::optional< T > lczero::OptionsDict::OwnGet (const OptionId & option_id) const
Definition at line 293 of file optionsdict.h.
References GetOptionId().
OwnGet() [2/2]
template<typename T > std::optional< T > lczero::OptionsDict::OwnGet (const std::string & key) const
Definition at line 284 of file optionsdict.h.
References lczero::TypeDict< T >::dict(), lczero::TypeDict< bool >::dict(), and key.
Set() [1/2]
template<typename T > void lczero::OptionsDict::Set (const OptionId & option_id, const T & value)
Definition at line 348 of file optionsdict.h.
References GetOptionId(), and value.
Set() [2/2]
template<typename T > void lczero::OptionsDict::Set (const std::string & key, const T & value)
Definition at line 344 of file optionsdict.h.
References key, lczero::TypeDict< T >::mutable_dict(), Set(), and value.
Referenced by lczero::SelfPlayTournament::PopulateOptions(), lczero::Benchmark::Run(), Set(), lczero::StringOption::SetVal(), lczero::IntOption::SetVal(), lczero::FloatOption::SetVal(), lczero::BoolOption::SetVal(), lczero::ChoiceOption::SetVal(), and lczero::ButtonOption::SetValue().
Member Data Documentation
aliases_
std::vector<const OptionsDict*> lczero::OptionsDict::aliases_ private
Definition at line 267 of file optionsdict.h.
Referenced by AddAliasDict(), Exists(), Get(), GetOrDefault(), and IsDefault().
parent_
const OptionsDict* lczero::OptionsDict::parent_ = nullptr private
Definition at line 263 of file optionsdict.h.
Referenced by Exists(), Get(), GetOrDefault(), and IsDefault().
subdicts_
std::map<std::string, OptionsDict> lczero::OptionsDict::subdicts_ private
Definition at line 264 of file optionsdict.h.
Referenced by AddSubdict(), CheckAllOptionsRead(), GetMutableSubdict(), GetSubdict(), HasSubdict(), and ListSubdicts().
The documentation for this class was generated from the following files:
src/utils/optionsdict.h
src/utils/optionsdict.cc