Leela Chess Zero: lczero::sycldnn_backend::FCLayer< DataType > Class Template Reference
lczero::sycldnn_backend::FCLayer< DataType > Class Template Reference
#include <layers.h>
Public Member Functions
FCLayer (BaseLayer< DataType > *ip, int C, int H, int W, bool bias, ActivationFunction activation, sycl::queue &sycl_queue)
~FCLayer ()
void LoadWeights (float *cpuWeight, float *cpuBias, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, sycl::queue &sycl_queue, DataType ***=nullptr) override
void LoadWeights (float *cpuWeight, float *cpuBias, void *scratch)
void LoadWeights (float *cpuWeight, float *cpuBias, void *)
void Eval (int N, sycl::half *output_tensor, const sycl::half *input_tensor, const sycl::half *, void *, size_t, sycl::queue &sycl_queue, sycl::half ***)
void Eval (int N, float *output_tensor, const float *input_tensor, const float *, void *, size_t, sycl::queue &sycl_queue, float ***)
Public Member Functions inherited from lczero::sycldnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
sycl::queue GetSycl_Queue ()
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip, sycl::queue &sycl_queue)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, sycl::queue &sycl_queue)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
const bool use_bias_
const ActivationFunction act_
DataType * weights_ = nullptr
DataType * biases_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from lczero::sycldnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasRowMajorMatrixMul (const sycl::half *A, const sycl::half *B, sycl::half *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
Protected Attributes inherited from lczero::sycldnn_backend::BaseLayer< DataType >
BaseLayer * input_
sycl::queue & sycl_queue_
int C
int H
int W
bool nhwc_
Detailed Description
template<typename DataType>
class lczero::sycldnn_backend::FCLayer< DataType >
Definition at line 79 of file layers.h.
Constructor & Destructor Documentation
FCLayer()
template<typename DataType > lczero::sycldnn_backend::FCLayer< DataType >::FCLayer (BaseLayer< DataType > * ip, int C, int H, int W, bool bias, ActivationFunction activation, sycl::queue & sycl_queue)
Definition at line 456 of file layers.cc.dp.cpp.
References lczero::sycldnn_backend::FCLayer< DataType >::biases_, lczero::sycldnn_backend::BaseLayer< DataType >::C, lczero::sycldnn_backend::BaseLayer< DataType >::GetC(), lczero::sycldnn_backend::BaseLayer< DataType >::GetH(), lczero::sycldnn_backend::BaseLayer< DataType >::GetW(), lczero::sycldnn_backend::BaseLayer< DataType >::H, lczero::sycldnn_backend::BaseLayer< DataType >::sycl_queue_, lczero::sycldnn_backend::FCLayer< DataType >::use_bias_, lczero::sycldnn_backend::BaseLayer< DataType >::W, and lczero::sycldnn_backend::FCLayer< DataType >::weights_.
~FCLayer()
template<typename DataType > lczero::sycldnn_backend::FCLayer< DataType >::~FCLayer ()
Definition at line 659 of file layers.cc.dp.cpp.
References weights_.
Member Function Documentation
Eval() [1/3]
template<typename DataType > void lczero::sycldnn_backend::FCLayer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, sycl::queue & sycl_queue, DataType *** = nullptr) override virtual
Implements lczero::sycldnn_backend::BaseLayer< DataType >.
Eval() [2/3]
void lczero::sycldnn_backend::FCLayer< float >::Eval (int N, float * output_tensor, const float * input_tensor, const float * , void * , size_t , sycl::queue & sycl_queue, float ***)
Definition at line 594 of file layers.cc.dp.cpp.
References lczero::ACTIVATION_NONE, lczero::sycldnn_backend::addVectors(), C, input_, ReportCUBLASErrors, transpose_type_notranspose, transpose_type_transpose, and weights_.
Eval() [3/3]
void lczero::sycldnn_backend::FCLayer< sycl::half >::Eval (int N, sycl::half * output_tensor, const sycl::half * input_tensor, const sycl::half * , void * , size_t , sycl::queue & sycl_queue, sycl::half ***)
Definition at line 520 of file layers.cc.dp.cpp.
References lczero::ACTIVATION_NONE, lczero::sycldnn_backend::addVectors(), C, input_, ReportCUBLASErrors, transpose_type_notranspose, transpose_type_transpose, and weights_.
LoadWeights() [1/3]
void lczero::sycldnn_backend::FCLayer< float >::LoadWeights (float * cpuWeight, float * cpuBias, void *)
Definition at line 501 of file layers.cc.dp.cpp.
References C, input_, and weights_.
LoadWeights() [2/3]
void lczero::sycldnn_backend::FCLayer< sycl::half >::LoadWeights (float * cpuWeight, float * cpuBias, void * scratch)
Definition at line 473 of file layers.cc.dp.cpp.
References C, lczero::sycldnn_backend::convertNCHWtoNHWC(), lczero::sycldnn_backend::copyTypeConverted(), input_, and weights_.
LoadWeights() [3/3]
template<typename DataType > void lczero::sycldnn_backend::FCLayer< DataType >::LoadWeights (float * cpuWeight, float * cpuBias, void * scratch)
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::sycldnn_backend::FCLayer< DataType >::act_ private
Definition at line 100 of file layers.h.
biases_
template<typename DataType > DataType* lczero::sycldnn_backend::FCLayer< DataType >::biases_ = nullptr private
Definition at line 102 of file layers.h.
Referenced by lczero::sycldnn_backend::FCLayer< DataType >::FCLayer().
use_bias_
template<typename DataType > const bool lczero::sycldnn_backend::FCLayer< DataType >::use_bias_ private
Definition at line 99 of file layers.h.
Referenced by lczero::sycldnn_backend::FCLayer< DataType >::FCLayer().
weights_
template<typename DataType > DataType* lczero::sycldnn_backend::FCLayer< DataType >::weights_ = nullptr private
Definition at line 101 of file layers.h.
Referenced by lczero::sycldnn_backend::FCLayer< DataType >::FCLayer().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/sycl/layers.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/sycl/layers.cc.dp.cpp