Leela Chess Zero: lczero::Square Class Reference
lczero::Square Class Reference
#include <types.h>
Public Member Functions
constexpr Square ()=default
constexpr Square (File file, Rank rank)
constexpr File file () const
constexpr Rank rank () const
void Flip ()
std::string ToString (bool uppercase=false) const
constexpr bool operator== (const Square &other) const =default
constexpr bool operator!= (const Square &other) const =default
constexpr uint8_t as_idx () const
Static Public Member Functions
static constexpr Square FromIdx (uint8_t idx)
static constexpr Square Parse (std::string_view)
Private Member Functions
constexpr Square (uint8_t idx)
Private Attributes
uint8_t idx_
Detailed Description
Definition at line 109 of file types.h.
Constructor & Destructor Documentation
Square() [1/3]
constexpr lczero::Square::Square () constexpr default
Referenced by Parse().
Square() [2/3]
constexpr lczero::Square::Square (File file, Rank rank) inline constexpr
Definition at line 112 of file types.h.
Square() [3/3]
constexpr lczero::Square::Square (uint8_t idx) inline explicit constexpr private
Definition at line 127 of file types.h.
Member Function Documentation
as_idx()
constexpr uint8_t lczero::Square::as_idx () const inline constexpr
Definition at line 124 of file types.h.
References idx_.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::BitBoard::FromSquare(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::BitBoard::get(), lczero::ChessBoard::Hash(), lczero::ChessBoard::IsUnderAttack(), lczero::BitBoard::reset(), lczero::BitBoard::set(), lczero::BitBoard::set_if(), lczero::Move::White(), lczero::Move::WhiteEnPassant(), and lczero::Move::WhitePromotion().
file()
constexpr File lczero::Square::file () const inline constexpr
Definition at line 115 of file types.h.
References lczero::File::FromIdx(), and idx_.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::BoardToFen(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::ChessBoard::IsLegalMove(), lczero::ChessBoard::IsUnderAttack(), lczero::ChessBoard::ParseMove(), lczero::PgnReader::SanToMove(), lczero::ChessBoard::SetFromFen(), lczero::Move::ToString(), and ToString().
Flip()
void lczero::Square::Flip () inline
Definition at line 118 of file types.h.
References idx_.
Referenced by lczero::ChessBoard::Mirror().
FromIdx()
static constexpr Square lczero::Square::FromIdx (uint8_t idx) inline static constexpr
Definition at line 113 of file types.h.
References idx.
Referenced by lczero::Move::from(), lczero::BitBoard::Uin64ToSquare::operator()(), and lczero::Move::to().
operator!=()
constexpr bool lczero::Square::operator!= (const Square & other) const constexpr default
operator==()
constexpr bool lczero::Square::operator== (const Square & other) const constexpr default
Parse()
constexpr Square lczero::Square::Parse (std::string_view str) inline static constexpr
Definition at line 208 of file types.h.
References lczero::File::Parse(), lczero::Rank::Parse(), and Square().
Referenced by lczero::MoveFromNNIndex().
rank()
constexpr Rank lczero::Square::rank () const inline constexpr
Definition at line 116 of file types.h.
References lczero::Rank::FromIdx(), and idx_.
Referenced by lczero::ChessBoard::ApplyMove(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::ChessBoard::IsLegalMove(), lczero::ChessBoard::IsUnderAttack(), lczero::Move::ToString(), and ToString().
ToString()
std::string lczero::Square::ToString (bool uppercase = false) const inline
Definition at line 119 of file types.h.
References file(), rank(), lczero::Rank::ToString(), and lczero::File::ToString().
Referenced by lczero::PopulateBoard(), and lczero::Move::ToString().
Member Data Documentation
idx_
uint8_t lczero::Square::idx_ private
Definition at line 130 of file types.h.
Referenced by as_idx(), file(), Flip(), and rank().
The documentation for this class was generated from the following file:
src/chess/types.h