Leela Chess Zero: lczero::dx_backend::PolicyMapLayer Class Reference
lczero::dx_backend::PolicyMapLayer Class Reference
#include <layers_dx.h>
Public Member Functions
PolicyMapLayer (bool fp16, DxContext *dx_context, BaseLayer *ip, int C, int H, int W, int used_size)
~PolicyMapLayer ()
void LoadWeights (const short *cpu_weights)
void Eval (int N, DXAlloc output, DXAlloc input, DXAlloc input2, DXAlloc scratch, DXAlloc scratch2, ID3D12GraphicsCommandList4 *command_list) override
Public Member Functions inherited from lczero::dx_backend::BaseLayer
int GetC () const
int GetH () const
int GetW () const
BaseLayer (int c, int h, int w, BaseLayer *ip, DxContext *dx_context, bool fp16)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
const int used_size_
DXAlloc weights_
Additional Inherited Members
Protected Attributes inherited from lczero::dx_backend::BaseLayer
BaseLayer * input_
DxContext * dx_context_
bool fp16_
int C
int H
int W
Detailed Description
Definition at line 200 of file layers_dx.h.
Constructor & Destructor Documentation
PolicyMapLayer()
lczero::dx_backend::PolicyMapLayer::PolicyMapLayer (bool fp16, DxContext * dx_context, BaseLayer * ip, int C, int H, int W, int used_size)
Definition at line 713 of file layers_dx.cc.
References lczero::dx_backend::DxContext::CreateAlloc(), used_size_, and weights_.
~PolicyMapLayer()
lczero::dx_backend::PolicyMapLayer::~PolicyMapLayer ()
Definition at line 739 of file layers_dx.cc.
References lczero::dx_backend::DXAlloc::resource, and weights_.
Member Function Documentation
Eval()
void lczero::dx_backend::PolicyMapLayer::Eval (int N, DXAlloc output, DXAlloc input, DXAlloc input2, DXAlloc scratch, DXAlloc scratch2, ID3D12GraphicsCommandList4 * command_list) override virtual
Implements lczero::dx_backend::BaseLayer.
Definition at line 727 of file layers_dx.cc.
References lczero::dx_backend::BaseLayer::C, lczero::dx_backend::BaseLayer::dx_context_, lczero::dx_backend::BaseLayer::fp16_, lczero::dx_backend::BaseLayer::GetC(), lczero::dx_backend::BaseLayer::GetH(), lczero::dx_backend::DxContext::getShaderWrapper(), lczero::dx_backend::BaseLayer::GetW(), lczero::dx_backend::BaseLayer::H, input, lczero::dx_backend::BaseLayer::input_, output, lczero::dx_backend::ShaderWrapper::PolicyMap(), used_size_, lczero::dx_backend::BaseLayer::W, and weights_.
LoadWeights()
void lczero::dx_backend::PolicyMapLayer::LoadWeights (const short * cpu_weights)
Definition at line 720 of file layers_dx.cc.
References lczero::dx_backend::BaseLayer::dx_context_, lczero::dx_backend::DxContext::ScheduleUpload(), used_size_, and weights_.
Member Data Documentation
used_size_
const int lczero::dx_backend::PolicyMapLayer::used_size_ private
Definition at line 211 of file layers_dx.h.
Referenced by Eval(), LoadWeights(), and PolicyMapLayer().
weights_
DXAlloc lczero::dx_backend::PolicyMapLayer::weights_ private
Definition at line 212 of file layers_dx.h.
Referenced by Eval(), LoadWeights(), PolicyMapLayer(), and ~PolicyMapLayer().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/dx/layers_dx.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/backends/dx/layers_dx.cc