Leela Chess Zero: lczero::FloatOption Class Reference
lczero::FloatOption Class Reference
#include <optionsparser.h>
Public Types
using ValueType = float
Public Member Functions
FloatOption (const OptionId &id, float min, float max)
void SetValue (const std::string &value, OptionsDict *dict) override
Public Member Functions inherited from lczero::OptionsParser::Option
Option (const OptionId &id)
virtual ~Option ()
Private Member Functions
std::string GetOptionString (const OptionsDict &dict) const override
bool ProcessLongFlag (const std::string &flag, const std::string &value, OptionsDict *dict) override
std::string GetHelp (const OptionsDict &dict) const override
bool ProcessShortFlagWithValue (char flag, const std::string &value, OptionsDict *dict) override
ValueType GetVal (const OptionsDict &) const
void SetVal (OptionsDict *dict, const ValueType &val) const
Private Attributes
float min_
float max_
Additional Inherited Members
Protected Member Functions inherited from lczero::OptionsParser::Option
const OptionId & GetId () const
std::string GetUciOption () const
std::string GetHelpText () const
std::string GetLongFlag () const
char GetShortFlag () const
Detailed Description
Definition at line 174 of file optionsparser.h.
Member Typedef Documentation
ValueType
using lczero::FloatOption::ValueType = float
Definition at line 176 of file optionsparser.h.
Constructor & Destructor Documentation
FloatOption()
lczero::FloatOption::FloatOption (const OptionId & id, float min, float max)
Definition at line 416 of file optionsparser.cc.
Member Function Documentation
GetHelp()
std::string lczero::FloatOption::GetHelp (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 459 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetHelpText(), lczero::OptionsParser::Option::GetLongFlag(), lczero::OptionsParser::Option::GetShortFlag(), lczero::OptionsParser::Option::GetUciOption(), GetVal(), max_, and min_.
GetOptionString()
std::string lczero::FloatOption::GetOptionString (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 473 of file optionsparser.cc.
References GetVal().
GetVal()
FloatOption::ValueType lczero::FloatOption::GetVal (const OptionsDict & dict) const private
Definition at line 477 of file optionsparser.cc.
References lczero::OptionsDict::Get(), and lczero::OptionsParser::Option::GetId().
Referenced by GetHelp(), and GetOptionString().
ProcessLongFlag()
bool lczero::FloatOption::ProcessLongFlag (const std::string & flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 429 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag(), SetVal(), and value.
ProcessShortFlagWithValue()
bool lczero::FloatOption::ProcessShortFlagWithValue (char flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 444 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetShortFlag(), SetVal(), and value.
SetVal()
void lczero::FloatOption::SetVal (OptionsDict * dict, const ValueType & val) const private
Definition at line 481 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetId(), lczero::OptionsParser::Option::GetLongFlag(), max_, min_, and lczero::OptionsDict::Set().
Referenced by ProcessLongFlag(), ProcessShortFlagWithValue(), and SetValue().
SetValue()
void lczero::FloatOption::SetValue (const std::string & value, OptionsDict * dict) override virtual
Implements lczero::OptionsParser::Option.
Definition at line 419 of file optionsparser.cc.
References SetVal(), and value.
Member Data Documentation
max_
float lczero::FloatOption::max_ private
Definition at line 193 of file optionsparser.h.
Referenced by GetHelp(), and SetVal().
min_
float lczero::FloatOption::min_ private
Definition at line 192 of file optionsparser.h.
Referenced by GetHelp(), and SetVal().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/optionsparser.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/optionsparser.cc