Leela Chess Zero: lczero::TypeDict< T > Class Template Reference
lczero::TypeDict< T > Class Template Reference
#include <optionsdict.h>
Classes
struct V
Protected Member Functions
void EnsureNoUnusedOptions (const std::string &type_name, const std::string &prefix) const
const std::unordered_map< std::string, V > & dict () const
std::unordered_map< std::string, V > * mutable_dict ()
Private Attributes
std::unordered_map< std::string, V > dict_
Detailed Description
template<typename T>
class lczero::TypeDict< T >
Definition at line 43 of file optionsdict.h.
Member Function Documentation
dict()
template<typename T > const std::unordered_map< std::string, V > & lczero::TypeDict< T >::dict () const inline protected
Definition at line 88 of file optionsdict.h.
References lczero::TypeDict< T >::dict_.
Referenced by lczero::OptionsDict::OwnExists(), and lczero::OptionsDict::OwnGet().
EnsureNoUnusedOptions()
template<typename T > void lczero::TypeDict< T >::EnsureNoUnusedOptions (const std::string & type_name, const std::string & prefix) const inline protected
Definition at line 78 of file optionsdict.h.
References lczero::TypeDict< T >::dict_.
Referenced by lczero::OptionsDict::CheckAllOptionsRead().
mutable_dict()
template<typename T > std::unordered_map< std::string, V > * lczero::TypeDict< T >::mutable_dict () inline protected
Definition at line 89 of file optionsdict.h.
References lczero::TypeDict< T >::dict_.
Referenced by lczero::OptionsDict::Set().
Member Data Documentation
dict_
template<typename T > std::unordered_map<std::string, V> lczero::TypeDict< T >::dict_ private
Definition at line 92 of file optionsdict.h.
Referenced by lczero::TypeDict< T >::dict(), lczero::TypeDict< T >::EnsureNoUnusedOptions(), and lczero::TypeDict< T >::mutable_dict().
The documentation for this class was generated from the following file:
src/utils/optionsdict.h