Leela Chess Zero: lczero::classic::Search Class Reference
lczero::classic::Search Class Reference abstract
Main MCTS search engine for the classic search implementation.
#include <search.h>
Public Member Functions
Search (const NodeTree &tree, Backend *network, std::unique_ptr< UciResponder > uci_responder, const MoveList &searchmoves, std::chrono::steady_clock::time_point start_time, std::unique_ptr< SearchStopper > stopper, bool infinite, bool ponder, const OptionsDict &options, SyzygyTablebase *syzygy_tb)
Constructs a Search instance.
~Search ()
Destructor that ensures all threads are stopped.
void StartThreads (size_t how_many)
Starts the specified number of worker threads.
void RunBlocking (size_t threads)
Runs search with specified threads, blocking until complete.
void Stop ()
Initiates search stop (non-blocking).
void Abort ()
Aborts search without returning best move (non-blocking).
void Wait ()
Blocks until all worker threads have finished.
bool IsSearchActive () const
Checks if search is still running.
std::pair< Move, Move > GetBestMove ()
Gets the best move and ponder move.
Eval GetBestEval (Move *move=nullptr, bool *is_terminal=nullptr) const
Gets the evaluation of the best move (without temperature).
std::int64_t GetTotalPlayouts () const
Gets total playouts completed in search.
const SearchParams & GetParams () const
Gets the search parameters.
void ResetBestMove ()
Resets cached best move for temperature re-sampling.
Private Member Functions
void EnsureBestMoveKnown ()
Computes best move, applying temperature if configured.
EdgeAndNode GetBestChildNoTemperature (Node *parent, int depth) const
Gets best child without temperature randomization.
std::vector< EdgeAndNode > GetBestChildrenNoTemperature (Node *parent, int count, int depth) const
Gets top N children without temperature.
EdgeAndNode GetBestRootChildWithTemperature (float temperature) const
Gets best child with temperature for root node.
int64_t GetTimeSinceStart () const
Gets milliseconds since search started.
int64_t GetTimeSinceFirstBatch () const
Gets milliseconds since first batch completed.
void MaybeTriggerStop (const IterationStats &stats, StoppersHints *hints)
Checks if search should stop based on limits.
void MaybeOutputInfo ()
Outputs search info if enough time has passed.
void SendUciInfo ()
Sends UCI info string.
void FireStopInternal ()
Internal method to fire stop signal.
void SendMovesStats () const
Outputs detailed move statistics.
void WatchdogThread ()
Watchdog thread monitoring time and stop commands.
void PopulateCommonIterationStats (IterationStats *stats)
Fills iteration stats with global search data.
std::vector< std::string > GetVerboseStats (const Node *node) const
Gets verbose debug info for a node.
float GetDrawScore (bool is_odd_depth) const
Gets draw score adjusted for depth parity.
void CancelSharedCollisions ()
Cancels shared collisions and clears list.
PositionHistory GetPositionHistoryAtNode (const Node *node) const
Reconstructs position history at given node.
Mutex counters_mutex_ ACQUIRED_AFTER (nodes_mutex_)
bool ok_to_respond_bestmove_ GUARDED_BY (counters_mutex_)
bool bestmove_is_sent_ GUARDED_BY (counters_mutex_)
Move final_bestmove_ GUARDED_BY (counters_mutex_)
Move final_pondermove_ GUARDED_BY (counters_mutex_)
std::unique_ptr< SearchStopper > stopper_ GUARDED_BY (counters_mutex_)
std::vector< std::thread > threads_ GUARDED_BY (threads_mutex_)
EdgeAndNode current_best_edge_ GUARDED_BY (nodes_mutex_)
Edge *last_outputted_info_edge_ GUARDED_BY (nodes_mutex_)
ThinkingInfo last_outputted_uci_info_ GUARDED_BY (nodes_mutex_)
int64_t total_playouts_ GUARDED_BY (nodes_mutex_)=0
int64_t network_evaluations_ GUARDED_BY (nodes_mutex_)=0
int64_t total_batches_ GUARDED_BY (nodes_mutex_)=0
uint16_t max_depth_ GUARDED_BY (nodes_mutex_)=0
uint64_t cum_depth_ GUARDED_BY (nodes_mutex_)=0
std::optional< std::chrono::steady_clock::time_point > nps_start_time_ GUARDED_BY (counters_mutex_)
std::vector< std::pair< Node *, int > > shared_collisions_ GUARDED_BY (nodes_mutex_)
Private Attributes
std::atomic< bool > stop_ {false}
std::condition_variable watchdog_cv_
Mutex threads_mutex_
Node * root_node_
SyzygyTablebase * syzygy_tb_
const PositionHistory & played_history_
Backend *const backend_
BackendAttributes backend_attributes_
const SearchParams params_
const MoveList searchmoves_
const std::chrono::steady_clock::time_point start_time_
int64_t initial_visits_
bool root_is_in_dtz_ = false
std::atomic< int > tb_hits_ {0}
const MoveList root_move_filter_
SharedMutex nodes_mutex_
std::atomic< int > pending_searchers_ {0}
std::atomic< int > backend_waiting_counter_ {0}
std::atomic< int > thread_count_ {0}
std::unique_ptr< UciResponder > uci_responder_
ContemptMode contempt_mode_
Friends
class SearchWorker
Detailed Description
Main MCTS search engine for the classic search implementation.
Orchestrates the Monte Carlo Tree Search, managing worker threads, neural network evaluations, time management, and UCI communication. The search operates on a NodeTree and coordinates multiple SearchWorker threads to explore the game tree in parallel.
Definition at line 55 of file search.h.
Constructor & Destructor Documentation
Search()
lczero::dag_classic::Search::Search (const NodeTree & tree, Backend * network, std::unique_ptr< UciResponder > uci_responder, const MoveList & searchmoves, std::chrono::steady_clock::time_point start_time, std::unique_ptr< SearchStopper > stopper, bool infinite, bool ponder, const OptionsDict & options, SyzygyTablebase * syzygy_tb)
Constructs a Search instance.
Parameters
tree The node tree to search within.
network Backend for neural network evaluation.
uci_responder UCI responder for search output.
searchmoves List of moves to restrict search to (empty = all).
start_time Timestamp when search was initiated.
stopper Search stopper for time/node limits.
infinite True if search should run until stopped.
ponder True if search is in ponder mode.
options Configuration options dictionary.
syzygy_tb Syzygy tablebase for endgame lookups.
Definition at line 158 of file search.cc.
References lczero::classic::BLACK, contempt_mode_, lczero::classic::BaseSearchParams::GetContemptMode(), lczero::classic::BaseSearchParams::GetMaxConcurrentSearchers(), lczero::classic::BaseSearchParams::GetWDLRescaleDiff(), lczero::PositionHistory::IsBlackToMove(), lczero::classic::NONE, params_, pending_searchers_, lczero::classic::PLAY, played_history_, uci_responder_, and lczero::classic::WHITE.
~Search()
lczero::classic::Search::~Search ()
Destructor that ensures all threads are stopped.
Definition at line 1115 of file search.cc.
References LOGFILE.
Member Function Documentation
Abort()
void lczero::classic::Search::Abort ()
Aborts search without returning best move (non-blocking).
Aborts the search immediately.
Definition at line 1084 of file search.cc.
References LOGFILE, and stop_.
ACQUIRED_AFTER()
Mutex counters_mutex_ lczero::classic::Search::ACQUIRED_AFTER (nodes_mutex_) mutable private
CancelSharedCollisions()
void lczero::classic::Search::CancelSharedCollisions () private
Cancels shared collisions and clears list.
Cancels shared collision updates (used during cleanup).
Definition at line 1104 of file search.cc.
References lczero::classic::Node::CancelScoreUpdate(), and lczero::classic::Node::GetParent().
EnsureBestMoveKnown()
void lczero::classic::Search::EnsureBestMoveKnown () private
Computes best move, applying temperature if configured.
Ensures the best move is calculated and stored, respecting temperature settings.
Definition at line 711 of file search.cc.
References GetBestChildNoTemperature(), GetBestRootChildWithTemperature(), lczero::Position::GetGamePly(), lczero::classic::EdgeAndNode::GetMove(), lczero::classic::Node::GetN(), lczero::classic::BaseSearchParams::GetTempDecayDelayMoves(), lczero::classic::BaseSearchParams::GetTempDecayMoves(), lczero::classic::BaseSearchParams::GetTemperature(), lczero::classic::BaseSearchParams::GetTemperatureCutoffMove(), lczero::classic::BaseSearchParams::GetTemperatureEndgame(), lczero::classic::Node::HasChildren(), lczero::PositionHistory::IsBlackToMove(), lczero::PositionHistory::Last(), moves, params_, played_history_, and root_node_.
Referenced by GetBestMove(), MaybeTriggerStop(), and ResetBestMove().
FireStopInternal()
void lczero::classic::Search::FireStopInternal () private
Internal method to fire stop signal.
Internal helper to signal all threads to stop.
Definition at line 1070 of file search.cc.
References stop_.
Referenced by MaybeTriggerStop().
GetBestChildNoTemperature()
EdgeAndNode lczero::classic::Search::GetBestChildNoTemperature (Node * parent, int depth) const private
Gets best child without temperature randomization.
Returns the single best child based on visit count (no temperature).
Parameters
parent The parent node to select from.
depth Current depth in tree.
Returns
EdgeAndNode pair for best child.
Definition at line 853 of file search.cc.
Referenced by EnsureBestMoveKnown(), GetBestEval(), and SendUciInfo().
GetBestChildrenNoTemperature()
std::vector< EdgeAndNode > lczero::classic::Search::GetBestChildrenNoTemperature (Node * parent, int count, int depth) const private
Gets top N children without temperature.
Returns the best children based on visit count (no temperature).
Parameters
parent The parent node to select from.
count Number of children to return.
depth Current depth in tree.
Returns
Vector of best EdgeAndNode pairs.
Definition at line 752 of file search.cc.
References lczero::classic::Node::Edges(), GetDrawScore(), lczero::classic::Node::GetN(), root_move_filter_, and root_node_.
Referenced by SendUciInfo().
GetBestEval()
Eval lczero::classic::Search::GetBestEval (Move * move = nullptr, bool * is_terminal = nullptr) const
Gets the evaluation of the best move (without temperature).
Returns the evaluation of the best child (ignoring temperature).
More deterministic than GetBestMove() when temperature is used.
Parameters
move Optional output for the best move.
is_terminal Optional output for terminal node status.
Returns
Evaluation struct with WL, D, M values.
Definition at line 670 of file search.cc.
References GetBestChildNoTemperature(), lczero::classic::Node::GetD(), lczero::classic::EdgeAndNode::GetD(), lczero::classic::Node::GetM(), lczero::classic::EdgeAndNode::GetM(), lczero::classic::EdgeAndNode::GetMove(), lczero::classic::Node::GetWL(), lczero::classic::EdgeAndNode::GetWL(), lczero::classic::Node::HasChildren(), lczero::PositionHistory::IsBlackToMove(), lczero::classic::EdgeAndNode::IsTerminal(), nodes_mutex_, played_history_, and root_node_.
GetBestMove()
std::pair< Move, Move > lczero::classic::Search::GetBestMove ()
Gets the best move and ponder move.
Returns the best move and ponder move found so far.
Returns moves from white's perspective. May apply temperature for move selection randomization.
Returns
Pair of (best_move, ponder_move).
Definition at line 685 of file search.cc.
References EnsureBestMoveKnown(), and nodes_mutex_.
GetBestRootChildWithTemperature()
EdgeAndNode lczero::classic::Search::GetBestRootChildWithTemperature (float temperature) const private
Gets best child with temperature for root node.
Selects a root child based on visit count weighted by temperature.
Parameters
temperature Temperature value for move selection.
Returns
EdgeAndNode pair for selected child.
Definition at line 861 of file search.cc.
References lczero::Random::Get(), lczero::Random::GetFloat(), idx, offset, and params_.
Referenced by EnsureBestMoveKnown().
GetDrawScore()
float lczero::classic::Search::GetDrawScore (bool is_odd_depth) const private
Gets draw score adjusted for depth parity.
Returns the score for a draw based on the current search depth (even/odd).
Parameters
is_odd_depth True if at odd search depth.
Returns
Draw score from perspective of side to move.
Definition at line 436 of file search.cc.
References lczero::classic::BaseSearchParams::GetDrawScore(), lczero::PositionHistory::IsBlackToMove(), params_, and played_history_.
Referenced by GetBestChildrenNoTemperature(), GetVerboseStats(), and SendUciInfo().
GetParams()
const SearchParams & lczero::classic::Search::GetParams () const inline
Gets the search parameters.
Returns
Reference to SearchParams configuration.
Definition at line 121 of file search.h.
References params_.
GetPositionHistoryAtNode()
PositionHistory lczero::classic::Search::GetPositionHistoryAtNode (const Node * node) const private
Reconstructs position history at given node.
Reconstructs the position history leading to a specific node.
Parameters
node Node to get history for.
Returns
PositionHistory to the node.
Definition at line 622 of file search.cc.
References lczero::PositionHistory::Append(), lczero::classic::Node::GetParent(), played_history_, and root_node_.
Referenced by GetVerboseStats().
GetTimeSinceFirstBatch()
int64_t lczero::classic::Search::GetTimeSinceFirstBatch () const private
Gets milliseconds since first batch completed.
Definition at line 426 of file search.cc.
GetTimeSinceStart()
int64_t lczero::classic::Search::GetTimeSinceStart () const private
Gets milliseconds since search started.
Definition at line 420 of file search.cc.
References start_time_.
Referenced by MaybeOutputInfo(), and SendUciInfo().
GetTotalPlayouts()
std::int64_t lczero::classic::Search::GetTotalPlayouts () const
Gets total playouts completed in search.
Returns the total number of playouts performed.
Returns
Number of completed MCTS simulations.
Definition at line 693 of file search.cc.
References nodes_mutex_.
GetVerboseStats()
std::vector< std::string > lczero::classic::Search::GetVerboseStats (const Node * node) const private
Gets verbose debug info for a node.
Generates verbose statistics for a node and its children.
Parameters
node Node to describe (root or ponder).
Returns
Vector of debug strings.
Definition at line 476 of file search.cc.
References backend_, backend_attributes_, lczero::classic::BLACK, lczero::BLACK_WON, contempt_mode_, d, lczero::DRAW, lczero::classic::Node::Edges(), lczero::Backend::GetCachedEvaluation(), lczero::classic::Node::GetChildrenVisits(), GetDrawScore(), lczero::classic::Node::GetN(), lczero::classic::Node::GetNInFlight(), lczero::classic::Node::GetNumEdges(), lczero::classic::Node::GetParent(), GetPositionHistoryAtNode(), lczero::classic::Node::GetQ(), lczero::classic::Node::GetVisitedPolicy(), lczero::classic::BaseSearchParams::GetWDLEvalObjectivity(), lczero::classic::BaseSearchParams::GetWDLMaxS(), lczero::classic::BaseSearchParams::GetWDLRescaleDiff(), lczero::classic::BaseSearchParams::GetWDLRescaleRatio(), lczero::classic::Node::GetWL(), lczero::BackendAttributes::has_mlh, lczero::PositionHistory::IsBlackToMove(), lczero::MoveToNNIndex(), lczero::classic::NONE, p, params_, played_history_, root_node_, and lczero::WHITE_WON.
Referenced by SendMovesStats().
GUARDED_BY() [1/16]
bool ok_to_respond_bestmove_ lczero::classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [2/16]
bool bestmove_is_sent_ lczero::classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [3/16]
Move final_bestmove_ lczero::classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [4/16]
Move final_pondermove_ lczero::classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [5/16]
std::unique_ptr< SearchStopper > stopper_ lczero::classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [6/16]
std::optional< std::chrono::steady_clock::time_point > nps_start_time_ lczero::classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [7/16]
EdgeAndNode current_best_edge_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private
GUARDED_BY() [8/16]
Edge *last_outputted_info_edge_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private
GUARDED_BY() [9/16]
ThinkingInfo last_outputted_uci_info_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private
GUARDED_BY() [10/16]
std::vector< std::pair< Node *, int > > shared_collisions_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private
GUARDED_BY() [11/16]
int64_t total_playouts_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [12/16]
int64_t network_evaluations_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [13/16]
int64_t total_batches_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [14/16]
uint16_t max_depth_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [15/16]
uint64_t cum_depth_ lczero::classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [16/16]
std::vector< std::thread > threads_ lczero::classic::Search::GUARDED_BY (threads_mutex_) private
IsSearchActive()
bool lczero::classic::Search::IsSearchActive () const
Checks if search is still running.
Checks if the search is currently active (not stopped).
Workers poll this to determine if more iterations are needed.
Returns
True if search is active.
Definition at line 956 of file search.cc.
References stop_.
Referenced by lczero::classic::SearchWorker::RunBlocking().
MaybeOutputInfo()
void lczero::classic::Search::MaybeOutputInfo () private
Outputs search info if enough time has passed.
Checks if UCI info output is needed and sends it if so.
Definition at line 396 of file search.cc.
References lczero::classic::BaseSearchParams::GetLogLiveStats(), GetTimeSinceStart(), nodes_mutex_, params_, SendMovesStats(), SendUciInfo(), stop_, and uci_responder_.
MaybeTriggerStop()
void lczero::classic::Search::MaybeTriggerStop (const IterationStats & stats, StoppersHints * hints) private
Checks if search should stop based on limits.
Checks if the search should stop based on current stats and limits.
Parameters
stats Current iteration statistics.
hints Hints for time management.
Definition at line 635 of file search.cc.
References EnsureBestMoveKnown(), FireStopInternal(), lczero::classic::BaseSearchParams::GetNpsLimit(), nodes_mutex_, params_, lczero::classic::StoppersHints::Reset(), SendMovesStats(), SendUciInfo(), stop_, lczero::classic::IterationStats::total_nodes, uci_responder_, and lczero::classic::StoppersHints::UpdateEstimatedNps().
PopulateCommonIterationStats()
void lczero::classic::Search::PopulateCommonIterationStats (IterationStats * stats) private
Fills iteration stats with global search data.
Populates statistics for the current iteration.
Parameters
stats Stats structure to populate.
Definition at line 961 of file search.cc.
References lczero::classic::IterationStats::average_depth, lczero::classic::IterationStats::batches_since_movestart, lczero::classic::IterationStats::edge_n, m, lczero::classic::IterationStats::mate_depth, lczero::classic::IterationStats::may_resign, lczero::classic::IterationStats::nodes_since_movestart, lczero::classic::IterationStats::num_losing_edges, params_, q, lczero::classic::IterationStats::time_since_first_batch, lczero::classic::IterationStats::time_since_movestart, lczero::classic::IterationStats::time_usage_hint_, lczero::classic::IterationStats::total_nodes, and lczero::classic::IterationStats::win_found.
ResetBestMove()
void lczero::classic::Search::ResetBestMove ()
Resets cached best move for temperature re-sampling.
Resets the best move logic to allow re-sending the best move.
Definition at line 699 of file search.cc.
References EnsureBestMoveKnown(), and nodes_mutex_.
RunBlocking()
void lczero::classic::Search::RunBlocking (size_t threads)
Runs search with specified threads, blocking until complete.
Runs the search blocking the current thread until finished.
Parameters
threads Number of threads to use.
Definition at line 950 of file search.cc.
SendMovesStats()
void lczero::classic::Search::SendMovesStats () const private
Outputs detailed move statistics.
Sends detailed move statistics to the UCI output or log.
Definition at line 592 of file search.cc.
References lczero::classic::Node::Edges(), lczero::classic::BaseSearchParams::GetVerboseStats(), GetVerboseStats(), lczero::PositionHistory::IsBlackToMove(), LOGFILE, params_, played_history_, root_node_, and uci_responder_.
Referenced by MaybeOutputInfo(), and MaybeTriggerStop().
SendUciInfo()
void lczero::classic::Search::SendUciInfo () private
Sends UCI info string.
Sends search information (depth, score, PV, etc.) to the UCI interface.
Note
Requires nodes_mutex_ to be held.
Definition at line 271 of file search.cc.
References backend_attributes_, lczero::classic::BLACK, contempt_mode_, d, lczero::ThinkingInfo::depth, lczero::ThinkingInfo::eps, GetBestChildNoTemperature(), GetBestChildrenNoTemperature(), lczero::classic::Node::GetD(), GetDrawScore(), lczero::classic::Node::GetM(), lczero::classic::BaseSearchParams::GetMultiPv(), lczero::classic::BaseSearchParams::GetPerPvCounters(), lczero::classic::Node::GetQ(), lczero::classic::BaseSearchParams::GetScoreType(), GetTimeSinceStart(), lczero::classic::BaseSearchParams::GetWDLEvalObjectivity(), lczero::classic::BaseSearchParams::GetWDLMaxS(), lczero::classic::BaseSearchParams::GetWDLRescaleDiff(), lczero::classic::BaseSearchParams::GetWDLRescaleRatio(), lczero::classic::Node::GetWL(), lczero::BackendAttributes::has_mlh, lczero::BackendAttributes::has_wdl, initial_visits_, lczero::PositionHistory::IsBlackToMove(), lczero::ThinkingInfo::nodes, lczero::classic::NONE, lczero::ThinkingInfo::nps, params_, played_history_, q, root_node_, lczero::ThinkingInfo::seldepth, lczero::ThinkingInfo::tb_hits, tb_hits_, lczero::ThinkingInfo::time, and uci_responder_.
Referenced by MaybeOutputInfo(), and MaybeTriggerStop().
StartThreads()
void lczero::classic::Search::StartThreads (size_t how_many)
Starts the specified number of worker threads.
Starts the specified number of search threads.
Returns immediately; threads run asynchronously.
Parameters
how_many Number of worker threads to start.
Definition at line 924 of file search.cc.
References LOGFILE, params_, lczero::classic::SearchWorker::RunBlocking(), and threads_.
Stop()
void lczero::classic::Search::Stop ()
Initiates search stop (non-blocking).
Stops the search gracefully.
Best move will be returned when search completes.
Definition at line 1076 of file search.cc.
References LOGFILE.
Wait()
void lczero::classic::Search::Wait ()
Blocks until all worker threads have finished.
Waits for all search threads to complete.
Definition at line 1095 of file search.cc.
References threads_.
WatchdogThread()
void lczero::classic::Search::WatchdogThread () private
Watchdog thread monitoring time and stop commands.
Watchdog thread function to monitor search progress and handle time management.
Definition at line 1036 of file search.cc.
References lczero::classic::StoppersHints::GetEstimatedRemainingTimeMs(), and LOGFILE.
Friends And Related Symbol Documentation
SearchWorker
friend class SearchWorker friend
Definition at line 260 of file search.h.
Member Data Documentation
backend_
Backend* const lczero::classic::Search::backend_ private
Definition at line 224 of file search.h.
Referenced by GetVerboseStats().
backend_attributes_
BackendAttributes lczero::classic::Search::backend_attributes_ private
Definition at line 225 of file search.h.
Referenced by GetVerboseStats(), lczero::classic::SearchWorker::SearchWorker(), and SendUciInfo().
backend_waiting_counter_
std::atomic<int> lczero::classic::Search::backend_waiting_counter_ {0} private
Definition at line 252 of file search.h.
contempt_mode_
ContemptMode lczero::classic::Search::contempt_mode_ private
Definition at line 259 of file search.h.
Referenced by GetVerboseStats(), Search(), and SendUciInfo().
initial_visits_
int64_t lczero::classic::Search::initial_visits_ private
Definition at line 229 of file search.h.
Referenced by SendUciInfo().
nodes_mutex_
SharedMutex lczero::classic::Search::nodes_mutex_ mutable private
Definition at line 236 of file search.h.
Referenced by GetBestEval(), GetBestMove(), GetTotalPlayouts(), MaybeOutputInfo(), MaybeTriggerStop(), and ResetBestMove().
params_
const SearchParams lczero::classic::Search::params_ private
Definition at line 226 of file search.h.
Referenced by EnsureBestMoveKnown(), GetDrawScore(), GetParams(), GetVerboseStats(), MaybeOutputInfo(), MaybeTriggerStop(), Search(), SendMovesStats(), and SendUciInfo().
pending_searchers_
std::atomic<int> lczero::classic::Search::pending_searchers_ {0} private
Definition at line 251 of file search.h.
Referenced by Search().
played_history_
const PositionHistory& lczero::classic::Search::played_history_ private
Definition at line 222 of file search.h.
Referenced by EnsureBestMoveKnown(), GetBestEval(), GetDrawScore(), GetPositionHistoryAtNode(), GetVerboseStats(), Search(), SendMovesStats(), and SendUciInfo().
root_is_in_dtz_
bool lczero::classic::Search::root_is_in_dtz_ = false private
Definition at line 231 of file search.h.
root_move_filter_
const MoveList lczero::classic::Search::root_move_filter_ private
Definition at line 234 of file search.h.
Referenced by GetBestChildrenNoTemperature().
root_node_
Node* lczero::classic::Search::root_node_ private
Definition at line 219 of file search.h.
Referenced by EnsureBestMoveKnown(), GetBestChildrenNoTemperature(), GetBestEval(), GetPositionHistoryAtNode(), GetVerboseStats(), SendMovesStats(), and SendUciInfo().
searchmoves_
const MoveList lczero::classic::Search::searchmoves_ private
Definition at line 227 of file search.h.
start_time_
const std::chrono::steady_clock::time_point lczero::classic::Search::start_time_ private
Definition at line 228 of file search.h.
Referenced by GetTimeSinceStart().
stop_
std::atomic<bool> lczero::classic::Search::stop_ {false} private
Definition at line 200 of file search.h.
Referenced by MaybeOutputInfo(), and MaybeTriggerStop().
syzygy_tb_
SyzygyTablebase* lczero::classic::Search::syzygy_tb_ private
Definition at line 220 of file search.h.
tb_hits_
std::atomic<int> lczero::classic::Search::tb_hits_ {0} private
Definition at line 233 of file search.h.
Referenced by SendUciInfo().
thread_count_
std::atomic<int> lczero::classic::Search::thread_count_ {0} private
Definition at line 253 of file search.h.
Referenced by lczero::classic::SearchWorker::SearchWorker().
threads_mutex_
Mutex lczero::classic::Search::threads_mutex_ private
Definition at line 216 of file search.h.
uci_responder_
std::unique_ptr<UciResponder> lczero::classic::Search::uci_responder_ private
Definition at line 258 of file search.h.
Referenced by MaybeOutputInfo(), MaybeTriggerStop(), Search(), SendMovesStats(), and SendUciInfo().
watchdog_cv_
std::condition_variable lczero::classic::Search::watchdog_cv_ private
Definition at line 202 of file search.h.
The documentation for this class was generated from the following files:
search/classic/search.h
search/classic/search.cc
search/dag_classic/search.cc