Leela Chess Zero: lczero::dag_classic::Search Class Reference
lczero::dag_classic::Search Class Reference abstract
Main search engine for the DAG-based MCTS implementation.
#include <search.h>
Public Member Functions
~Search ()
Destructor that ensures all threads are stopped.
void StartThreads (size_t how_many)
Starts worker threads and returns immediately.
void RunBlocking (size_t threads)
Starts search with k threads and wait until it finishes.
void Stop ()
Stops search. At the end bestmove will be returned.
void Abort ()
Stops search, but does not return bestmove. The function is not blocking.
void Wait ()
Blocks until all worker thread finish.
bool IsSearchActive () const
Returns whether search is active.
std::pair< Move, Move > GetBestMove ()
Returns best move and ponder move, from the point of view of white player.
Eval GetBestEval (Move *move=nullptr, bool *is_terminal=nullptr) const
Returns the evaluation of the best move (highest visit count), IGNORING temperature.
std::int64_t GetTotalPlayouts () const
Returns the total number of playouts in the search.
const SearchParams & GetParams () const
Returns the search parameters.
void ResetBestMove ()
Resets the best move status.
void RecordNPSStartTime ()
Public Attributes
std::unique_ptr< UciResponder > uci_responder
Constructs a Search instance.
std::unique_ptr< UciResponder > const MoveList & searchmoves
std::unique_ptr< UciResponder > const MoveList std::chrono::steady_clock::time_point start_time
std::unique_ptr< UciResponder > const MoveList std::chrono::steady_clock::time_point std::unique_ptr< classic::SearchStopper > stopper
std::unique_ptr< UciResponder > const MoveList std::chrono::steady_clock::time_point std::unique_ptr< classic::SearchStopper > bool infinite
std::unique_ptr< UciResponder > const MoveList std::chrono::steady_clock::time_point std::unique_ptr< classic::SearchStopper > bool bool ponder
std::unique_ptr< UciResponder > const MoveList std::chrono::steady_clock::time_point std::unique_ptr< classic::SearchStopper > bool bool const OptionsDict & options
std::unique_ptr< UciResponder > const MoveList std::chrono::steady_clock::time_point std::unique_ptr< classic::SearchStopper > bool bool const OptionsDict TranspositionTable * tt
std::unique_ptr< UciResponder > const MoveList std::chrono::steady_clock::time_point std::unique_ptr< classic::SearchStopper > bool bool const OptionsDict TranspositionTable SyzygyTablebase * syzygy_tb
Private Member Functions
void EnsureBestMoveKnown ()
Computes and caches the best move if not already known.
EdgeAndNode GetBestChildNoTemperature (Node *parent, int depth) const
Returns a child with most visits, with or without temperature.
std::vector< EdgeAndNode > GetBestChildrenNoTemperature (Node *parent, int count, int depth) const
EdgeAndNode GetBestRootChildWithTemperature (float temperature) const
int64_t GetTimeSinceStart () const
int64_t GetTimeSinceFirstBatch () const
void MaybeTriggerStop (const classic::IterationStats &stats, classic::StoppersHints *hints)
void MaybeOutputInfo (const classic::IterationStats &stats)
void SendUciInfo (const classic::IterationStats &stats)
void FireStopInternal ()
void SendMovesStats () const
void WatchdogThread ()
Function which runs in a separate thread and watches for time and uci stop command.
void PopulateCommonIterationStats (classic::IterationStats *stats)
Fills IterationStats with global (rather than per-thread) portion of search statistics.
std::vector< std::string > GetVerboseStats (const Node *node, std::optional< Move > move_to_node) const
Returns verbose information about given node, as vector of strings.
float GetDrawScore (bool is_odd_depth) const
Returns the draw score at the root of the search.
Mutex counters_mutex_ ACQUIRED_AFTER (nodes_mutex_)
bool ok_to_respond_bestmove_ GUARDED_BY (counters_mutex_)
bool bestmove_is_sent_ GUARDED_BY (counters_mutex_)
bool gc_started_ GUARDED_BY (counters_mutex_)
Move final_bestmove_ GUARDED_BY (counters_mutex_)
Move final_pondermove_ GUARDED_BY (counters_mutex_)
std::unique_ptr< classic::SearchStopper > stopper_ GUARDED_BY (counters_mutex_)
std::vector< std::thread > threads_ GUARDED_BY (threads_mutex_)
EdgeAndNode current_best_edge_ GUARDED_BY (nodes_mutex_)
Edge *last_outputted_info_edge_ GUARDED_BY (nodes_mutex_)
ThinkingInfo last_outputted_uci_info_ GUARDED_BY (nodes_mutex_)
int64_t total_playouts_ GUARDED_BY (nodes_mutex_)=0
int64_t network_evaluations_ GUARDED_BY (nodes_mutex_)=0
int64_t total_batches_ GUARDED_BY (nodes_mutex_)=0
uint16_t max_depth_ GUARDED_BY (nodes_mutex_)=0
uint64_t cum_depth_ GUARDED_BY (nodes_mutex_)=0
Private Attributes
std::atomic< bool > stop_ {false}
std::condition_variable watchdog_cv_
Mutex threads_mutex_
Node * root_node_
TranspositionTable * tt_
SyzygyTablebase * syzygy_tb_
const PositionHistory & played_history_
Backend *const backend_
BackendAttributes backend_attributes_
const SearchParams params_
const MoveList searchmoves_
const std::chrono::steady_clock::time_point start_time_
int64_t initial_visits_
bool root_is_in_dtz_ = false
std::atomic< int > tb_hits_ {0}
const MoveList root_move_filter_
SharedMutex nodes_mutex_
std::optional< std::chrono::steady_clock::time_point > nps_start_time_
std::atomic< int > pending_searchers_ {0}
std::atomic< int > backend_waiting_counter_ {0}
std::atomic< int > thread_count_ {0}
std::unique_ptr< UciResponder > uci_responder_
ContemptMode contempt_mode_
Friends
class SearchWorker
Detailed Description
Main search engine for the DAG-based MCTS implementation.
This class orchestrates the search process using a Directed Acyclic Graph (DAG) structure to handle transpositions efficiently. It manages worker threads, neural network evaluations, time management, and UCI communication. Unlike the classic tree search, this implementation allows nodes to be shared across different paths (transpositions), reducing redundant work.
Definition at line 64 of file search.h.
Constructor & Destructor Documentation
~Search()
lczero::dag_classic::Search::~Search ()
Destructor that ensures all threads are stopped.
Definition at line 1139 of file search.cc.
References LOGFILE.
Member Function Documentation
Abort()
void lczero::dag_classic::Search::Abort ()
Stops search, but does not return bestmove. The function is not blocking.
Definition at line 1102 of file search.cc.
References LOGFILE, and stop_.
ACQUIRED_AFTER()
Mutex counters_mutex_ lczero::dag_classic::Search::ACQUIRED_AFTER (nodes_mutex_) mutable private
EnsureBestMoveKnown()
void lczero::dag_classic::Search::EnsureBestMoveKnown () private
Computes and caches the best move if not already known.
Applies temperature logic if applicable. This method ensures that final_bestmove_ and final_pondermove_ are populated. It is called internally before returning results to the interface.
Definition at line 745 of file search.cc.
References moves, and params_.
FireStopInternal()
void lczero::dag_classic::Search::FireStopInternal () private
Definition at line 1089 of file search.cc.
References stop_.
GetBestChildNoTemperature()
EdgeAndNode lczero::dag_classic::Search::GetBestChildNoTemperature (Node * parent, int depth) const private
Returns a child with most visits, with or without temperature.
NoTemperature is safe to use on non-extended nodes, while WithTemperature accepts only nodes with at least 1 visited child.
Definition at line 885 of file search.cc.
GetBestChildrenNoTemperature()
std::vector< EdgeAndNode > lczero::dag_classic::Search::GetBestChildrenNoTemperature (Node * parent, int count, int depth) const private
Definition at line 785 of file search.cc.
References lczero::dag_classic::Node::Edges(), and lczero::dag_classic::Node::GetN().
GetBestEval()
Eval lczero::dag_classic::Search::GetBestEval (Move * move = nullptr, bool * is_terminal = nullptr) const
Returns the evaluation of the best move (highest visit count), IGNORING temperature.
This provides the "objective" best evaluation found by the search, which may differ from the chosen move if temperature caused a sub-optimal move to be selected for diversity.
Parameters
move Set to the best move if not nullptr.
is_terminal Set to true if the best move leads to a terminal node.
Definition at line 709 of file search.cc.
References lczero::dag_classic::EdgeAndNode::GetD(), lczero::dag_classic::EdgeAndNode::GetM(), lczero::dag_classic::EdgeAndNode::GetMove(), lczero::dag_classic::EdgeAndNode::GetWL(), and lczero::dag_classic::EdgeAndNode::IsTerminal().
GetBestMove()
std::pair< Move, Move > lczero::dag_classic::Search::GetBestMove ()
Returns best move and ponder move, from the point of view of white player.
Determines the best move based on visit counts. If temperature is enabled (typically in early game or training), the move is selected probabilistically. Otherwise, the move with the highest visit count is chosen.
Returns
Pair of (best move, ponder move).
Definition at line 723 of file search.cc.
GetBestRootChildWithTemperature()
EdgeAndNode lczero::dag_classic::Search::GetBestRootChildWithTemperature (float temperature) const private
Definition at line 892 of file search.cc.
References idx, offset, and params_.
GetDrawScore()
float lczero::dag_classic::Search::GetDrawScore (bool is_odd_depth) const private
Returns the draw score at the root of the search.
Depth of a root node is 0 (even number).
Parameters
is_odd_depth At odd depth pass true to change the sign of the draw score.
Definition at line 478 of file search.cc.
References params_.
GetParams()
const SearchParams & lczero::dag_classic::Search::GetParams () const inline
Returns the search parameters.
Definition at line 130 of file search.h.
References params_.
GetTimeSinceFirstBatch()
int64_t lczero::dag_classic::Search::GetTimeSinceFirstBatch () const private
Definition at line 465 of file search.cc.
GetTimeSinceStart()
int64_t lczero::dag_classic::Search::GetTimeSinceStart () const private
Definition at line 459 of file search.cc.
GetTotalPlayouts()
std::int64_t lczero::dag_classic::Search::GetTotalPlayouts () const
Returns the total number of playouts in the search.
Definition at line 730 of file search.cc.
GetVerboseStats()
std::vector< std::string > lczero::dag_classic::Search::GetVerboseStats (const Node * node, std::optional< Move > move_to_node) const private
Returns verbose information about given node, as vector of strings.
Node can only be root or ponder (depth 1) and move_to_node is only given for the ponder node.
Definition at line 515 of file search.cc.
References backend_, d, lczero::dag_classic::Node::Edges(), lczero::dag_classic::Node::GetChildrenVisits(), lczero::dag_classic::Node::GetN(), lczero::dag_classic::Node::GetNInFlight(), lczero::dag_classic::Node::GetNumEdges(), lczero::dag_classic::Node::GetQ(), lczero::dag_classic::Node::GetTotalVisits(), lczero::dag_classic::Node::GetVisitedPolicy(), lczero::dag_classic::Node::GetWL(), lczero::MoveToNNIndex(), p, and params_.
GUARDED_BY() [1/15]
bool ok_to_respond_bestmove_ lczero::dag_classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [2/15]
bool bestmove_is_sent_ lczero::dag_classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [3/15]
bool gc_started_ lczero::dag_classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [4/15]
Move final_bestmove_ lczero::dag_classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [5/15]
Move final_pondermove_ lczero::dag_classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [6/15]
std::unique_ptr< classic::SearchStopper > stopper_ lczero::dag_classic::Search::GUARDED_BY (counters_mutex_) private
GUARDED_BY() [7/15]
EdgeAndNode current_best_edge_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private
GUARDED_BY() [8/15]
Edge *last_outputted_info_edge_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private
GUARDED_BY() [9/15]
ThinkingInfo last_outputted_uci_info_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private
GUARDED_BY() [10/15]
int64_t total_playouts_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [11/15]
int64_t network_evaluations_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [12/15]
int64_t total_batches_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [13/15]
uint16_t max_depth_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [14/15]
uint64_t cum_depth_ lczero::dag_classic::Search::GUARDED_BY (nodes_mutex_) private pure virtual
GUARDED_BY() [15/15]
std::vector< std::thread > threads_ lczero::dag_classic::Search::GUARDED_BY (threads_mutex_) private
IsSearchActive()
bool lczero::dag_classic::Search::IsSearchActive () const
Returns whether search is active.
Workers check that to see whether another search iteration is needed.
Definition at line 984 of file search.cc.
References stop_.
Referenced by lczero::dag_classic::SearchWorker::RunBlocking().
MaybeOutputInfo()
void lczero::dag_classic::Search::MaybeOutputInfo (const classic::IterationStats & stats) private
Definition at line 435 of file search.cc.
References params_, and stop_.
MaybeTriggerStop()
void lczero::dag_classic::Search::MaybeTriggerStop (const classic::IterationStats & stats, classic::StoppersHints * hints) private
Definition at line 665 of file search.cc.
References lczero::classic::StoppersHints::GetEstimatedRemainingTimeMs(), params_, lczero::classic::StoppersHints::Reset(), stop_, lczero::classic::IterationStats::time_since_movestart, lczero::classic::IterationStats::total_nodes, and lczero::classic::StoppersHints::UpdateEstimatedNps().
PopulateCommonIterationStats()
void lczero::dag_classic::Search::PopulateCommonIterationStats (classic::IterationStats * stats) private
Fills IterationStats with global (rather than per-thread) portion of search statistics.
Currently all stats there (in IterationStats) are global though.
Definition at line 988 of file search.cc.
References lczero::classic::IterationStats::average_depth, lczero::classic::IterationStats::batches_since_movestart, lczero::classic::IterationStats::edge_n, m, lczero::classic::IterationStats::mate_depth, lczero::classic::IterationStats::may_resign, lczero::classic::IterationStats::nodes_since_movestart, lczero::classic::IterationStats::num_losing_edges, params_, q, lczero::classic::IterationStats::time_since_first_batch, lczero::classic::IterationStats::time_since_movestart, lczero::classic::IterationStats::time_usage_hint_, lczero::classic::IterationStats::total_nodes, and lczero::classic::IterationStats::win_found.
RecordNPSStartTime()
void lczero::dag_classic::Search::RecordNPSStartTime ()
Definition at line 472 of file search.cc.
ResetBestMove()
void lczero::dag_classic::Search::ResetBestMove ()
Resets the best move status.
If called after GetBestMove, another call to GetBestMove will have results from temperature having been applied again.
Definition at line 735 of file search.cc.
RunBlocking()
void lczero::dag_classic::Search::RunBlocking (size_t threads)
Starts search with k threads and wait until it finishes.
Definition at line 979 of file search.cc.
SendMovesStats()
void lczero::dag_classic::Search::SendMovesStats () const private
Definition at line 636 of file search.cc.
References LOGFILE, and params_.
SendUciInfo()
void lczero::dag_classic::Search::SendUciInfo (const classic::IterationStats & stats) private
Definition at line 310 of file search.cc.
References d, lczero::ThinkingInfo::depth, lczero::ThinkingInfo::eps, lczero::ThinkingInfo::nodes, lczero::ThinkingInfo::nps, params_, q, lczero::ThinkingInfo::seldepth, lczero::ThinkingInfo::tb_hits, and lczero::ThinkingInfo::time.
StartThreads()
void lczero::dag_classic::Search::StartThreads (size_t how_many)
Starts worker threads and returns immediately.
Definition at line 954 of file search.cc.
References LOGFILE, params_, lczero::dag_classic::SearchWorker::RunBlocking(), and threads_.
Stop()
void lczero::dag_classic::Search::Stop ()
Stops search. At the end bestmove will be returned.
The function is not blocking, so it returns before search is actually done.
Definition at line 1094 of file search.cc.
References LOGFILE.
Wait()
void lczero::dag_classic::Search::Wait ()
Blocks until all worker thread finish.
Definition at line 1113 of file search.cc.
References LOGFILE, and threads_.
WatchdogThread()
void lczero::dag_classic::Search::WatchdogThread () private
Function which runs in a separate thread and watches for time and uci stop command.
Definition at line 1056 of file search.cc.
References lczero::classic::StoppersHints::GetEstimatedRemainingTimeMs(), and LOGFILE.
Friends And Related Symbol Documentation
SearchWorker
friend class SearchWorker friend
Definition at line 256 of file search.h.
Member Data Documentation
backend_
Backend* const lczero::dag_classic::Search::backend_ private
Definition at line 221 of file search.h.
backend_attributes_
BackendAttributes lczero::dag_classic::Search::backend_attributes_ private
Definition at line 222 of file search.h.
Referenced by lczero::dag_classic::SearchWorker::SearchWorker().
backend_waiting_counter_
std::atomic<int> lczero::dag_classic::Search::backend_waiting_counter_ {0} private
Definition at line 251 of file search.h.
contempt_mode_
ContemptMode lczero::dag_classic::Search::contempt_mode_ private
Definition at line 255 of file search.h.
infinite
std::unique_ptr<UciResponder> const MoveList std::chrono::steady_clock::time_point std::unique_ptr<classic::SearchStopper> bool lczero::dag_classic::Search::infinite
Definition at line 81 of file search.h.
initial_visits_
int64_t lczero::dag_classic::Search::initial_visits_ private
Definition at line 226 of file search.h.
nodes_mutex_
SharedMutex lczero::dag_classic::Search::nodes_mutex_ mutable private
Definition at line 233 of file search.h.
nps_start_time_
std::optional<std::chrono::steady_clock::time_point> lczero::dag_classic::Search::nps_start_time_ private
Definition at line 248 of file search.h.
options
std::unique_ptr<UciResponder> const MoveList std::chrono::steady_clock::time_point std::unique_ptr<classic::SearchStopper> bool bool const OptionsDict& lczero::dag_classic::Search::options
Definition at line 82 of file search.h.
params_
const SearchParams lczero::dag_classic::Search::params_ private
Definition at line 223 of file search.h.
Referenced by GetParams().
pending_searchers_
std::atomic<int> lczero::dag_classic::Search::pending_searchers_ {0} private
Definition at line 250 of file search.h.
played_history_
const PositionHistory& lczero::dag_classic::Search::played_history_ private
Definition at line 219 of file search.h.
ponder
std::unique_ptr<UciResponder> const MoveList std::chrono::steady_clock::time_point std::unique_ptr<classic::SearchStopper> bool bool lczero::dag_classic::Search::ponder
Definition at line 82 of file search.h.
root_is_in_dtz_
bool lczero::dag_classic::Search::root_is_in_dtz_ = false private
Definition at line 228 of file search.h.
root_move_filter_
const MoveList lczero::dag_classic::Search::root_move_filter_ private
Definition at line 231 of file search.h.
root_node_
Node* lczero::dag_classic::Search::root_node_ private
Definition at line 215 of file search.h.
searchmoves
std::unique_ptr<UciResponder> const MoveList& lczero::dag_classic::Search::searchmoves
Definition at line 79 of file search.h.
searchmoves_
const MoveList lczero::dag_classic::Search::searchmoves_ private
Definition at line 224 of file search.h.
start_time
std::unique_ptr<UciResponder> const MoveList std::chrono::steady_clock::time_point lczero::dag_classic::Search::start_time
Definition at line 80 of file search.h.
start_time_
const std::chrono::steady_clock::time_point lczero::dag_classic::Search::start_time_ private
Definition at line 225 of file search.h.
stop_
std::atomic<bool> lczero::dag_classic::Search::stop_ {false} private
Definition at line 193 of file search.h.
stopper
std::unique_ptr<UciResponder> const MoveList std::chrono::steady_clock::time_point std::unique_ptr<classic::SearchStopper> lczero::dag_classic::Search::stopper
Definition at line 81 of file search.h.
syzygy_tb
std::unique_ptr<UciResponder> const MoveList std::chrono::steady_clock::time_point std::unique_ptr<classic::SearchStopper> bool bool const OptionsDict TranspositionTable SyzygyTablebase* lczero::dag_classic::Search::syzygy_tb
Definition at line 83 of file search.h.
syzygy_tb_
SyzygyTablebase* lczero::dag_classic::Search::syzygy_tb_ private
Definition at line 217 of file search.h.
tb_hits_
std::atomic<int> lczero::dag_classic::Search::tb_hits_ {0} private
Definition at line 230 of file search.h.
thread_count_
std::atomic<int> lczero::dag_classic::Search::thread_count_ {0} private
Definition at line 252 of file search.h.
Referenced by lczero::dag_classic::SearchWorker::SearchWorker().
threads_mutex_
Mutex lczero::dag_classic::Search::threads_mutex_ private
Definition at line 212 of file search.h.
tt
std::unique_ptr<UciResponder> const MoveList std::chrono::steady_clock::time_point std::unique_ptr<classic::SearchStopper> bool bool const OptionsDict TranspositionTable* lczero::dag_classic::Search::tt
Definition at line 82 of file search.h.
tt_
TranspositionTable* lczero::dag_classic::Search::tt_ private
Definition at line 216 of file search.h.
uci_responder
std::unique_ptr<UciResponder> lczero::dag_classic::Search::uci_responder
Constructs a Search instance.
Parameters
tree The node tree to search within.
backend Backend for neural network evaluation.
uci_responder UCI responder for search output.
searchmoves List of moves to restrict search to (empty = all).
start_time Timestamp when search was initiated.
stopper Search stopper for time/node limits.
infinite True if search should run until stopped.
ponder True if search is in ponder mode.
options Configuration options dictionary.
tt Transposition table for caching evaluations.
syzygy_tb Syzygy tablebase for endgame lookups.
Definition at line 78 of file search.h.
uci_responder_
std::unique_ptr<UciResponder> lczero::dag_classic::Search::uci_responder_ private
Definition at line 254 of file search.h.
watchdog_cv_
std::condition_variable lczero::dag_classic::Search::watchdog_cv_ private
Definition at line 195 of file search.h.
The documentation for this class was generated from the following files:
search/dag_classic/search.h
search/dag_classic/search.cc