Leela Chess Zero: lczero::onnx::OnnxComputation< DataType > Class Template Reference
lczero::onnx::OnnxComputation< DataType > Class Template Reference final
ONNX computation class.
Public Member Functions
OnnxComputation (OnnxNetwork *network)
~OnnxComputation ()
void AddInput (InputPlanes &&input) override
Adds a sample to the current batch for computation.
int GetBatchSize () const override
Returns the number of samples currently in the batch.
void ComputeBlocking () override
Executes the neural network computation for the accumulated batch.
float GetQVal (int sample) const override
Retrieves the Q-value (expected game result) for a specific sample.
float GetDVal (int sample) const override
Retrieves the D-value (draw probability) for a specific sample.
float GetPVal (int sample, int move_id) const override
Retrieves the P-value (policy/move probability) for a specific move in a sample.
float GetMVal (int sample) const override
Retrieves the M-value (moves left) for a specific sample.
Public Member Functions inherited from lczero::NetworkComputation
virtual ~NetworkComputation ()=default
Private Member Functions
Ort::IoBinding PrepareInputs (int start, int batch_size, int step)
Private Attributes
OnnxNetwork * network_
size_t input_size_ = 0
std::vector< InputPlanes > raw_input_
std::unique_ptr< InputsOutputs > inputs_outputs_
Detailed Description
template<typename DataType>
class lczero::onnx::OnnxComputation< DataType >
ONNX computation class.
Handles the execution of the network using ONNX Runtime.
Definition at line 122 of file network_onnx.cc.
Constructor & Destructor Documentation
OnnxComputation()
template<typename DataType > lczero::onnx::OnnxComputation< DataType >::OnnxComputation (OnnxNetwork * network)
Definition at line 327 of file network_onnx.cc.
References lczero::onnx::OnnxNetwork::GetInputsOutputs(), lczero::onnx::OnnxComputation< DataType >::inputs_outputs_, and lczero::onnx::OnnxComputation< DataType >::network_.
~OnnxComputation()
template<typename DataType > lczero::onnx::OnnxComputation< DataType >::~OnnxComputation ()
Definition at line 333 of file network_onnx.cc.
References network_.
Member Function Documentation
AddInput()
template<typename DataType > void lczero::onnx::OnnxComputation< DataType >::AddInput (InputPlanes && input) override virtual
Adds a sample to the current batch for computation.
Parameters
input The input planes representing the position to evaluate.
Implements lczero::NetworkComputation.
Definition at line 348 of file network_onnx.cc.
References lczero::onnx::AsDataType(), lczero::onnx::CUDA, input, lczero::kInputPlanes, network_, raw_input_, lczero::onnx::TRT, and value.
ComputeBlocking()
template<typename DataType > void lczero::onnx::OnnxComputation< DataType >::ComputeBlocking () override virtual
Executes the neural network computation for the accumulated batch.
This method blocks until the computation is complete.
Implements lczero::NetworkComputation.
Definition at line 485 of file network_onnx.cc.
References lczero::onnx::AsFloat(), lczero::onnx::CPU, lczero::onnx::CUDA, d, data, lczero::onnx::expandPlanesOnnx(), lczero::kInputPlanes, LCTRACE_FUNCTION_SCOPE, m, network_, offset, ReportCUDAErrors, and lczero::onnx::TRT.
GetBatchSize()
template<typename DataType > int lczero::onnx::OnnxComputation< DataType >::GetBatchSize () const override virtual
Returns the number of samples currently in the batch.
Returns
The batch size.
Implements lczero::NetworkComputation.
Definition at line 383 of file network_onnx.cc.
GetDVal()
template<typename DataType > float lczero::onnx::OnnxComputation< DataType >::GetDVal (int sample) const override virtual
Retrieves the D-value (draw probability) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The D-value.
Implements lczero::NetworkComputation.
Definition at line 412 of file network_onnx.cc.
References network_.
GetMVal()
template<typename DataType > float lczero::onnx::OnnxComputation< DataType >::GetMVal (int sample) const override virtual
Retrieves the M-value (moves left) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The expected number of moves left.
Implements lczero::NetworkComputation.
Definition at line 425 of file network_onnx.cc.
References lczero::onnx::AsFloat(), data, and network_.
GetPVal()
template<typename DataType > float lczero::onnx::OnnxComputation< DataType >::GetPVal (int sample, int move_id) const override virtual
Retrieves the P-value (policy/move probability) for a specific move in a sample.
Parameters
sample The index of the sample in the batch.
move_id The index of the move.
Returns
The P-value (probability) for the move.
Implements lczero::NetworkComputation.
Definition at line 418 of file network_onnx.cc.
References lczero::onnx::AsFloat(), data, lczero::onnx::kNumOutputPolicy, and network_.
GetQVal()
template<typename DataType > float lczero::onnx::OnnxComputation< DataType >::GetQVal (int sample) const override virtual
Retrieves the Q-value (expected game result) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The Q-value (typically from -1.0 to 1.0).
Implements lczero::NetworkComputation.
Definition at line 400 of file network_onnx.cc.
References lczero::onnx::AsFloat(), data, and network_.
PrepareInputs()
template<typename DataType > Ort::IoBinding lczero::onnx::OnnxComputation< DataType >::PrepareInputs (int start, int batch_size, int step) private
Definition at line 433 of file network_onnx.cc.
References lczero::onnx::AsDataType(), lczero::onnx::CUDA, lczero::kInputPlanes, network_, raw_input_, lczero::onnx::TRT, and value.
Member Data Documentation
input_size_
template<typename DataType > size_t lczero::onnx::OnnxComputation< DataType >::input_size_ = 0 private
Definition at line 138 of file network_onnx.cc.
inputs_outputs_
template<typename DataType > std::unique_ptr<InputsOutputs> lczero::onnx::OnnxComputation< DataType >::inputs_outputs_ private
Definition at line 140 of file network_onnx.cc.
Referenced by lczero::onnx::OnnxComputation< DataType >::OnnxComputation().
network_
template<typename DataType > OnnxNetwork* lczero::onnx::OnnxComputation< DataType >::network_ private
Definition at line 137 of file network_onnx.cc.
Referenced by lczero::onnx::OnnxComputation< DataType >::OnnxComputation().
raw_input_
template<typename DataType > std::vector<InputPlanes> lczero::onnx::OnnxComputation< DataType >::raw_input_ private
Definition at line 139 of file network_onnx.cc.
The documentation for this class was generated from the following file:
src/neural/backends/onnx/network_onnx.cc