Leela Chess Zero: lczero::IntOption Class Reference
lczero::IntOption Class Reference
#include <optionsparser.h>
Public Types
using ValueType = int
Public Member Functions
IntOption (const OptionId &id, int min, int max)
void SetValue (const std::string &value, OptionsDict *dict) override
Public Member Functions inherited from lczero::OptionsParser::Option
Option (const OptionId &id)
virtual ~Option ()
Private Member Functions
std::string GetOptionString (const OptionsDict &dict) const override
bool ProcessLongFlag (const std::string &flag, const std::string &value, OptionsDict *dict) override
std::string GetHelp (const OptionsDict &dict) const override
bool ProcessShortFlagWithValue (char flag, const std::string &value, OptionsDict *dict) override
ValueType GetVal (const OptionsDict &) const
void SetVal (OptionsDict *dict, const ValueType &val) const
int ValidateIntString (const std::string &val) const
Private Attributes
int min_
int max_
Additional Inherited Members
Protected Member Functions inherited from lczero::OptionsParser::Option
const OptionId & GetId () const
std::string GetUciOption () const
std::string GetHelpText () const
std::string GetLongFlag () const
char GetShortFlag () const
Detailed Description
Definition at line 151 of file optionsparser.h.
Member Typedef Documentation
ValueType
using lczero::IntOption::ValueType = int
Definition at line 153 of file optionsparser.h.
Constructor & Destructor Documentation
IntOption()
lczero::IntOption::IntOption (const OptionId & id, int min, int max)
Definition at line 342 of file optionsparser.cc.
Member Function Documentation
GetHelp()
std::string lczero::IntOption::GetHelp (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 367 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetHelpText(), lczero::OptionsParser::Option::GetLongFlag(), lczero::OptionsParser::Option::GetShortFlag(), lczero::OptionsParser::Option::GetUciOption(), GetVal(), max_, and min_.
GetOptionString()
std::string lczero::IntOption::GetOptionString (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 378 of file optionsparser.cc.
References GetVal(), max_, and min_.
GetVal()
IntOption::ValueType lczero::IntOption::GetVal (const OptionsDict & dict) const private
Definition at line 383 of file optionsparser.cc.
References lczero::OptionsDict::Get(), and lczero::OptionsParser::Option::GetId().
Referenced by GetHelp(), and GetOptionString().
ProcessLongFlag()
bool lczero::IntOption::ProcessLongFlag (const std::string & flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 349 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag(), SetVal(), ValidateIntString(), and value.
ProcessShortFlagWithValue()
bool lczero::IntOption::ProcessShortFlagWithValue (char flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 358 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetShortFlag(), SetVal(), ValidateIntString(), and value.
SetVal()
void lczero::IntOption::SetVal (OptionsDict * dict, const ValueType & val) const private
Definition at line 387 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetId(), lczero::OptionsParser::Option::GetLongFlag(), max_, min_, and lczero::OptionsDict::Set().
Referenced by ProcessLongFlag(), ProcessShortFlagWithValue(), and SetValue().
SetValue()
void lczero::IntOption::SetValue (const std::string & value, OptionsDict * dict) override virtual
Implements lczero::OptionsParser::Option.
Definition at line 345 of file optionsparser.cc.
References SetVal(), ValidateIntString(), and value.
ValidateIntString()
int lczero::IntOption::ValidateIntString (const std::string & val) const private
Definition at line 397 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag(), ptr, and result.
Referenced by ProcessLongFlag(), ProcessShortFlagWithValue(), and SetValue().
Member Data Documentation
max_
int lczero::IntOption::max_ private
Definition at line 171 of file optionsparser.h.
Referenced by GetHelp(), GetOptionString(), and SetVal().
min_
int lczero::IntOption::min_ private
Definition at line 170 of file optionsparser.h.
Referenced by GetHelp(), GetOptionString(), and SetVal().
The documentation for this class was generated from the following files:
utils/optionsparser.h
utils/optionsparser.cc