Leela Chess Zero: lczero::Position Class Reference
lczero::Position Class Reference
Represents a chess position in the Lc0 engine.
#include <position.h>
Public Member Functions
Position ()=default
Default constructor for a position.
Position (const Position &parent, Move m)
Creates a position from a parent position and a move.
Position (const ChessBoard &board, int rule50_ply, int game_ply)
Creates a position from a specific board state.
uint64_t Hash () const
Computes a hash value for the position.
bool IsBlackToMove () const
Checks if it's black's turn to move.
int GetGamePly () const
Gets the number of half-moves since the beginning of the game.
int GetRepetitions () const
Gets the number of times this position has appeared in the game before.
int GetPliesSincePrevRepetition () const
Gets the number of half-moves since the same position last appeared in the game.
void SetRepetitions (int repetitions, int cycle_length)
Sets the repetition count and cycle length for this position.
int GetRule50Ply () const
Gets the number of half-moves since the last capture or pawn move.
const ChessBoard & GetBoard () const
Gets the board from the point of view of the player to move.
bool operator== (const Position &other) const =default
Equality operator for comparing positions.
bool operator!= (const Position &other) const =default
Inequality operator for comparing positions.
std::string DebugString () const
Gets a debug string representation of the position.
Static Public Member Functions
static Position FromFen (std::string_view fen)
Creates a position from Forsyth-Edwards Notation (FEN).
Private Attributes
ChessBoard us_board_
The board from the point of view of the player to move.
int rule50_ply_ = 0
Number of half-moves without capture or pawn move.
int repetitions_ = 0
Number of repetitions this position had before (0 for new positions).
int cycle_length_ = 0
Number of half-moves since the position was repeated, or 0.
int ply_count_ = 0
Number of half-moves since the beginning of the game.
Detailed Description
Represents a chess position in the Lc0 engine.
This class manages the current state of a chess position including the board, game state information, repetition counting, and 50-move rule tracking. It's used extensively throughout the engine for position evaluation and search.
Definition at line 42 of file position.h.
Constructor & Destructor Documentation
Position() [1/3]
lczero::Position::Position () default
Default constructor for a position.
Position() [2/3]
lczero::Position::Position (const Position & parent, Move m)
Creates a position from a parent position and a move.
Parameters
parent The parent position to derive from.
m The move to apply to the parent position.
Definition at line 40 of file position.cc.
References lczero::ChessBoard::ApplyMove(), m, lczero::ChessBoard::Mirror(), rule50_ply_, and us_board_.
Position() [3/3]
lczero::Position::Position (const ChessBoard & board, int rule50_ply, int game_ply)
Creates a position from a specific board state.
Parameters
board The chess board state.
rule50_ply Number of half-moves since the last capture or pawn move.
game_ply Total number of half-moves since the start of the game.
Definition at line 48 of file position.cc.
References us_board_.
Member Function Documentation
DebugString()
std::string lczero::Position::DebugString () const
Gets a debug string representation of the position.
Returns
A string with detailed information about the position for debugging.
Definition at line 63 of file position.cc.
References fen, and lczero::PositionToFen().
FromFen()
Position lczero::Position::FromFen (std::string_view fen) static
Creates a position from Forsyth-Edwards Notation (FEN).
Parameters
fen The FEN string representing the position.
Returns
A Position object initialized from the FEN string.
Definition at line 53 of file position.cc.
References fen, ply_count_, rule50_ply_, lczero::ChessBoard::SetFromFen(), and us_board_.
Referenced by lczero::classic::NodeTree::ResetToPosition(), and lczero::dag_classic::NodeTree::ResetToPosition().
GetBoard()
const ChessBoard & lczero::Position::GetBoard () const inline
Gets the board from the point of view of the player to move.
Returns
A constant reference to the chess board.
Definition at line 98 of file position.h.
References us_board_.
Referenced by lczero::python::GameState::as_string(), lczero::PositionHistory::ComputeGameResult(), lczero::EncodePositionForNN(), lczero::classic::SearchWorker::ExtendNode(), lczero::dag_classic::SearchWorker::ExtendNode(), lczero::python::GameState::GameState(), lczero::python::GameState::moves(), lczero::python::GameState::policy_indices(), lczero::PositionToFen(), lczero::SyzygyTablebase::probe_dtz(), lczero::classic::NodeTree::ResetToPosition(), lczero::dag_classic::NodeTree::ResetToPosition(), lczero::SyzygyTablebase::root_probe(), lczero::SyzygyTablebase::root_probe_wdl(), lczero::SyzygyTablebase::search(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), lczero::TEST(), and lczero::TransformForPosition().
GetGamePly()
int lczero::Position::GetGamePly () const inline
Gets the number of half-moves since the beginning of the game.
Returns
The game ply count.
Definition at line 73 of file position.h.
References ply_count_.
Referenced by lczero::classic::Search::EnsureBestMoveKnown(), lczero::classic::NodeTree::GetPlyCount(), lczero::dag_classic::NodeTree::GetPlyCount(), and lczero::PositionToFen().
GetPliesSincePrevRepetition()
int lczero::Position::GetPliesSincePrevRepetition () const inline
Gets the number of half-moves since the same position last appeared in the game.
Returns
The number of plies since the last repetition, or 0 if not repeated.
Definition at line 81 of file position.h.
References cycle_length_.
Referenced by lczero::classic::SearchWorker::ExtendNode(), and lczero::dag_classic::SearchWorker::GetRepetitions().
GetRepetitions()
int lczero::Position::GetRepetitions () const inline
Gets the number of times this position has appeared in the game before.
Returns
The repetition count.
Definition at line 77 of file position.h.
References repetitions_.
Referenced by lczero::EncodePositionForNN(), lczero::classic::SearchWorker::ExtendNode(), lczero::dag_classic::SearchWorker::GetRepetitions(), lczero::TEST(), and lczero::TEST().
GetRule50Ply()
int lczero::Position::GetRule50Ply () const inline
Gets the number of half-moves since the last capture or pawn move.
Returns
The 50-move rule ply count.
Definition at line 94 of file position.h.
References rule50_ply_.
Referenced by lczero::EncodePositionForNN(), lczero::classic::SearchWorker::ExtendNode(), lczero::dag_classic::SearchWorker::ExtendNode(), lczero::PositionToFen(), lczero::SyzygyTablebase::probe_dtz(), and lczero::SyzygyTablebase::root_probe().
Hash()
uint64_t lczero::Position::Hash () const
Computes a hash value for the position.
Returns
A 64-bit hash representing the position state.
Definition at line 59 of file position.cc.
References lczero::ChessBoard::Hash(), lczero::HashCat(), repetitions_, and us_board_.
IsBlackToMove()
bool lczero::Position::IsBlackToMove () const inline
Checks if it's black's turn to move.
Returns
True if black is to move, false if white is to move.
Definition at line 69 of file position.h.
References lczero::ChessBoard::flipped(), and us_board_.
Referenced by lczero::SelfPlayGame::GetMoves(), lczero::PositionHistory::IsBlackToMove(), lczero::classic::NodeTree::IsBlackToMove(), lczero::dag_classic::NodeTree::IsBlackToMove(), and lczero::PositionToFen().
operator!=()
bool lczero::Position::operator!= (const Position & other) const default
Inequality operator for comparing positions.
Parameters
other The other position to compare with.
Returns
True if the positions are not equal, false otherwise.
operator==()
bool lczero::Position::operator== (const Position & other) const default
Equality operator for comparing positions.
Parameters
other The other position to compare with.
Returns
True if the positions are equal, false otherwise.
SetRepetitions()
void lczero::Position::SetRepetitions (int repetitions, int cycle_length) inline
Sets the repetition count and cycle length for this position.
This is used when external code has better knowledge about repetitions.
Parameters
repetitions The number of repetitions this position has had before.
cycle_length The number of half-moves since the position was repeated, or 0.
Definition at line 87 of file position.h.
References cycle_length_, and repetitions_.
Member Data Documentation
cycle_length_
int lczero::Position::cycle_length_ = 0 private
Number of half-moves since the position was repeated, or 0.
Definition at line 125 of file position.h.
Referenced by GetPliesSincePrevRepetition(), and SetRepetitions().
ply_count_
int lczero::Position::ply_count_ = 0 private
Number of half-moves since the beginning of the game.
Definition at line 128 of file position.h.
Referenced by FromFen(), and GetGamePly().
repetitions_
int lczero::Position::repetitions_ = 0 private
Number of repetitions this position had before (0 for new positions).
Definition at line 122 of file position.h.
Referenced by GetRepetitions(), Hash(), and SetRepetitions().
rule50_ply_
int lczero::Position::rule50_ply_ = 0 private
Number of half-moves without capture or pawn move.
Definition at line 119 of file position.h.
Referenced by FromFen(), GetRule50Ply(), and Position().
us_board_
ChessBoard lczero::Position::us_board_ private
The board from the point of view of the player to move.
Definition at line 116 of file position.h.
Referenced by FromFen(), GetBoard(), Hash(), IsBlackToMove(), Position(), and Position().
The documentation for this class was generated from the following files:
chess/position.h
chess/position.cc