Leela Chess Zero: lczero::python::GameState Class Reference
lczero::python::GameState Class Reference
#include <weights.h>
Public Member Functions
GameState (const std::optional< std::string > startpos, const std::vector< std::string > &moves, const bool is_c960)
GameState (const std::optional< std::string > startpos, const std::vector< std::string > &moves)
std::unique_ptr< Input > as_input (const Backend &backend) const
std::vector< std::string > moves () const
std::vector< int > policy_indices () const
std::string as_string () const
Private Attributes
PositionHistory history_
bool is_c960_
Detailed Description
Definition at line 235 of file weights.h.
Constructor & Destructor Documentation
GameState() [1/2]
lczero::python::GameState::GameState (const std::optional< std::string > startpos, const std::vector< std::string > & moves, const bool is_c960) inline
Definition at line 237 of file weights.h.
References lczero::PositionHistory::Append(), lczero::ChessBoard::flipped(), lczero::Position::GetBoard(), history_, lczero::ChessBoard::kStartposFen, lczero::PositionHistory::Last(), m, moves(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
GameState() [2/2]
lczero::python::GameState::GameState (const std::optional< std::string > startpos, const std::vector< std::string > & moves) inline
Definition at line 256 of file weights.h.
Member Function Documentation
as_input()
std::unique_ptr< Input > lczero::python::GameState::as_input (const Backend & backend) const inline
Definition at line 260 of file weights.h.
References lczero::python::Backend::capabilities(), lczero::EncodePositionForNN(), lczero::FEN_ONLY, history_, and lczero::python::BackendCapabilities::input_format().
as_string()
std::string lczero::python::GameState::as_string () const inline
Definition at line 288 of file weights.h.
References lczero::Position::GetBoard(), history_, lczero::PositionHistory::IsBlackToMove(), lczero::PositionHistory::Last(), and lczero::ChessBoard::Mirror().
moves()
std::vector< std::string > lczero::python::GameState::moves () const inline
Definition at line 268 of file weights.h.
References lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), history_, is_c960_, lczero::PositionHistory::IsBlackToMove(), lczero::PositionHistory::Last(), m, and result.
Referenced by GameState().
policy_indices()
std::vector< int > lczero::python::GameState::policy_indices () const inline
Definition at line 279 of file weights.h.
References lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), history_, lczero::PositionHistory::Last(), m, lczero::MoveToNNIndex(), and result.
Member Data Documentation
history_
PositionHistory lczero::python::GameState::history_ private
Definition at line 295 of file weights.h.
Referenced by as_input(), as_string(), GameState(), moves(), and policy_indices().
is_c960_
bool lczero::python::GameState::is_c960_ private
Definition at line 296 of file weights.h.
Referenced by moves().
The documentation for this class was generated from the following file:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/python/weights.h