Leela Chess Zero: lczero::dag_classic::atomic_unique_ptr< T > Class Template Reference
lczero::dag_classic::atomic_unique_ptr< T > Class Template Reference
A thread-safe unique pointer with atomic operations.
#include <node.h>
Public Member Functions
constexpr atomic_unique_ptr () noexcept
atomic_unique_ptr (pointer p) noexcept
atomic_unique_ptr (atomic_unique_ptr &&p) noexcept
atomic_unique_ptr & operator= (atomic_unique_ptr &&p) noexcept
atomic_unique_ptr (unique_pointer &&p) noexcept
atomic_unique_ptr & operator= (unique_pointer &&p) noexcept
void reset (pointer p=pointer()) noexcept
~atomic_unique_ptr ()
operator pointer () const noexcept
pointer operator-> () const noexcept
pointer get () const noexcept
operator bool () const noexcept
pointer set (pointer p=pointer()) noexcept
pointer release () noexcept
bool compare_exchange (pointer &expected, atomic_unique_ptr< T > &source) noexcept
Private Types
using pointer = T *
using unique_pointer = std::unique_ptr< T >
Private Attributes
std::atomic< pointer > ptr
Detailed Description
template<class T>
class lczero::dag_classic::atomic_unique_ptr< T >
A thread-safe unique pointer with atomic operations.
Template Parameters
T The type of the managed object.
Definition at line 108 of file node.h.
Member Typedef Documentation
pointer
template<class T > using lczero::dag_classic::atomic_unique_ptr< T >::pointer = T* private
Definition at line 109 of file node.h.
unique_pointer
template<class T > using lczero::dag_classic::atomic_unique_ptr< T >::unique_pointer = std::unique_ptr<T> private
Definition at line 110 of file node.h.
Constructor & Destructor Documentation
atomic_unique_ptr() [1/4]
template<class T > constexpr lczero::dag_classic::atomic_unique_ptr< T >::atomic_unique_ptr () inline constexpr noexcept
Definition at line 114 of file node.h.
atomic_unique_ptr() [2/4]
template<class T > lczero::dag_classic::atomic_unique_ptr< T >::atomic_unique_ptr (pointer p) inline explicit noexcept
Definition at line 117 of file node.h.
atomic_unique_ptr() [3/4]
template<class T > lczero::dag_classic::atomic_unique_ptr< T >::atomic_unique_ptr (atomic_unique_ptr< T > && p) inline noexcept
Definition at line 120 of file node.h.
atomic_unique_ptr() [4/4]
template<class T > lczero::dag_classic::atomic_unique_ptr< T >::atomic_unique_ptr (unique_pointer && p) inline noexcept
Definition at line 128 of file node.h.
~atomic_unique_ptr()
template<class T > lczero::dag_classic::atomic_unique_ptr< T >::~atomic_unique_ptr () inline
Definition at line 141 of file node.h.
References lczero::dag_classic::atomic_unique_ptr< T >::reset().
Member Function Documentation
compare_exchange()
template<class T > bool lczero::dag_classic::atomic_unique_ptr< T >::compare_exchange (pointer & expected, atomic_unique_ptr< T > & source) inline noexcept
Definition at line 162 of file node.h.
References lczero::dag_classic::atomic_unique_ptr< T >::ptr.
get()
template<class T > pointer lczero::dag_classic::atomic_unique_ptr< T >::get () const inline noexcept
Definition at line 148 of file node.h.
References lczero::dag_classic::atomic_unique_ptr< T >::ptr.
Referenced by lczero::dag_classic::atomic_unique_ptr< T >::operator bool(), lczero::dag_classic::atomic_unique_ptr< T >::operator pointer(), and lczero::dag_classic::atomic_unique_ptr< T >::operator->().
operator bool()
template<class T > lczero::dag_classic::atomic_unique_ptr< T >::operator bool () const inline explicit noexcept
Definition at line 151 of file node.h.
References lczero::dag_classic::atomic_unique_ptr< T >::get().
operator pointer()
template<class T > lczero::dag_classic::atomic_unique_ptr< T >::operator pointer () const inline noexcept
Definition at line 144 of file node.h.
References lczero::dag_classic::atomic_unique_ptr< T >::get().
operator->()
template<class T > pointer lczero::dag_classic::atomic_unique_ptr< T >::operator-> () const inline noexcept
Definition at line 146 of file node.h.
References lczero::dag_classic::atomic_unique_ptr< T >::get().
operator=() [1/2]
template<class T > atomic_unique_ptr & lczero::dag_classic::atomic_unique_ptr< T >::operator= (atomic_unique_ptr< T > && p) inline noexcept
Definition at line 122 of file node.h.
References p, and lczero::dag_classic::atomic_unique_ptr< T >::reset().
operator=() [2/2]
template<class T > atomic_unique_ptr & lczero::dag_classic::atomic_unique_ptr< T >::operator= (unique_pointer && p) inline noexcept
Definition at line 130 of file node.h.
References p, and lczero::dag_classic::atomic_unique_ptr< T >::reset().
release()
template<class T > pointer lczero::dag_classic::atomic_unique_ptr< T >::release () inline noexcept
Definition at line 158 of file node.h.
References lczero::dag_classic::atomic_unique_ptr< T >::set().
reset()
template<class T > void lczero::dag_classic::atomic_unique_ptr< T >::reset (pointer p = pointer()) inline noexcept
Definition at line 136 of file node.h.
References p, and lczero::dag_classic::atomic_unique_ptr< T >::ptr.
Referenced by lczero::dag_classic::atomic_unique_ptr< T >::operator=(), lczero::dag_classic::atomic_unique_ptr< T >::operator=(), and lczero::dag_classic::atomic_unique_ptr< T >::~atomic_unique_ptr().
set()
template<class T > pointer lczero::dag_classic::atomic_unique_ptr< T >::set (pointer p = pointer()) inline noexcept
Definition at line 154 of file node.h.
References p, and lczero::dag_classic::atomic_unique_ptr< T >::ptr.
Referenced by lczero::dag_classic::atomic_unique_ptr< T >::release().
Member Data Documentation
ptr
template<class T > std::atomic<pointer> lczero::dag_classic::atomic_unique_ptr< T >::ptr private
Definition at line 174 of file node.h.
Referenced by lczero::dag_classic::atomic_unique_ptr< T >::compare_exchange(), lczero::dag_classic::atomic_unique_ptr< T >::get(), lczero::dag_classic::atomic_unique_ptr< T >::reset(), and lczero::dag_classic::atomic_unique_ptr< T >::set().
The documentation for this class was generated from the following file:
search/dag_classic/node.h