Leela Chess Zero: lczero::classic::SearchWorker Class Reference
lczero::classic::SearchWorker Class Reference
Single-threaded worker for MCTS search iterations.
#include <search.h>
Classes
struct NodeToProcess
struct PickTask
struct TaskWorkspace
Public Member Functions
SearchWorker (Search *search, const SearchParams &params)
Constructs a SearchWorker.
~SearchWorker ()
Destructor that stops all task threads.
void RunBlocking ()
Runs search iterations until search is stopped.
void ExecuteOneIteration ()
Executes one complete MCTS iteration.
void InitializeIteration ()
Phase 1: Initialize internal structures for iteration.
void GatherMinibatch ()
Phase 2: Gather a minibatch of nodes to evaluate.
void CollectCollisions ()
Phase 2b: Copy collisions to shared collision list.
void MaybePrefetchIntoCache ()
Phase 3: Prefetch positions into evaluation cache.
void RunNNComputation ()
Phase 4: Run neural network evaluation.
void FetchMinibatchResults ()
Phase 5: Retrieve NN results and terminal values.
void DoBackupUpdate ()
Phase 6: Backpropagate values to parent nodes.
void UpdateCounters ()
Phase 7: Update global search counters.
Private Member Functions
NodeToProcess PickNodeToExtend (int collision_limit)
int PrefetchIntoCache (Node *node, int budget, bool is_odd_depth)
Recursively finds and prefetches nodes into the cache.
void DoBackupUpdateSingleNode (const NodeToProcess &node_to_process)
Updates a single node and propagates values up the tree.
bool MaybeSetBounds (Node *p, float m, int *n_to_fix, float *v_delta, float *d_delta, float *m_delta) const
Updates the bounds of a node based on its children's bounds.
void PickNodesToExtend (int collision_limit)
Orchestrates picking nodes to extend, potentially distributing work to task threads.
void PickNodesToExtendTask (Node *starting_point, int base_depth, int collision_limit, const std::vector< Move > &moves_to_base, std::vector< NodeToProcess > *receiver, TaskWorkspace *workspace)
Worker task to pick nodes to extend from a sub-tree.
void EnsureNodeTwoFoldCorrectForDepth (Node *node, int depth)
Ensures 3-fold repetition correctness by reverting terminal status if needed.
void ProcessPickedTask (int batch_start, int batch_end, TaskWorkspace *workspace)
Processes a range of picked tasks (nodes) to prepare them for evaluation.
void ExtendNode (Node *node, int depth, const std::vector< Move > &moves_to_add, PositionHistory *history)
Extends a leaf node by generating legal moves and checking for terminal states.
void FetchSingleNodeResult (NodeToProcess *node_to_process)
Retrieves the result for a single node (NN or terminal).
void RunTasks (int tid)
Main loop for a search worker thread to process tasks.
void ResetTasks ()
Resets the task queue and counters.
int WaitForTasks ()
Waits for all assigned tasks to complete.
Private Attributes
Search *const search_
std::vector< NodeToProcess > minibatch_
std::unique_ptr< BackendComputation > computation_
int task_workers_
int target_minibatch_size_
int max_out_of_order_
PositionHistory history_
int number_out_of_order_ = 0
const SearchParams & params_
const bool moves_left_support_
IterationStats iteration_stats_
StoppersHints latest_time_manager_hints_
Mutex picking_tasks_mutex_
std::vector< PickTask > picking_tasks_
std::atomic< int > task_count_ = -1
std::atomic< int > task_taking_started_ = 0
std::atomic< int > tasks_taken_ = 0
std::atomic< int > completed_tasks_ = 0
std::condition_variable task_added_
std::vector< std::thread > task_threads_
std::vector< TaskWorkspace > task_workspaces_
TaskWorkspace main_workspace_
bool exiting_ = false
Detailed Description
Single-threaded worker for MCTS search iterations.
Performs the core MCTS loop: node selection, expansion, evaluation, and backpropagation. Each SearchWorker runs in its own thread and coordinates with the main Search object for synchronization and stopping conditions. The worker handles minibatch gathering for efficient NN evaluation.
Definition at line 269 of file search.h.
Constructor & Destructor Documentation
SearchWorker()
lczero::classic::SearchWorker::SearchWorker (Search * search, const SearchParams & params) inline
Constructs a SearchWorker.
Parameters
search Pointer to the parent Search object.
params Search parameters configuration.
Definition at line 274 of file search.h.
References lczero::classic::Search::backend_attributes_, lczero::classic::BaseSearchParams::GetMaxOutOfOrderEvalsFactor(), lczero::classic::BaseSearchParams::GetMiniBatchSize(), lczero::classic::BaseSearchParams::GetTaskWorkersPerSearchWorker(), max_out_of_order_, params_, lczero::BackendAttributes::recommended_batch_size, lczero::BackendAttributes::runs_on_cpu, RunTasks(), search_, target_minibatch_size_, task_threads_, task_workers_, task_workspaces_, and lczero::classic::Search::thread_count_.
~SearchWorker()
lczero::classic::SearchWorker::~SearchWorker () inline
Destructor that stops all task threads.
Definition at line 305 of file search.h.
References exiting_, picking_tasks_mutex_, task_added_, task_count_, and task_threads_.
Member Function Documentation
CollectCollisions()
void lczero::classic::SearchWorker::CollectCollisions ()
Phase 2b: Copy collisions to shared collision list.
Collects collision nodes to be handled centrally.
Definition at line 2076 of file search.cc.
References LCTRACE_FUNCTION_SCOPE, and search_.
DoBackupUpdate()
void lczero::classic::SearchWorker::DoBackupUpdate ()
Phase 6: Backpropagate values to parent nodes.
Updates the tree with results from the minibatch.
Definition at line 2263 of file search.cc.
References LCTRACE_FUNCTION_SCOPE, and search_.
DoBackupUpdateSingleNode()
void lczero::classic::SearchWorker::DoBackupUpdateSingleNode (const NodeToProcess & node_to_process) private
Updates a single node and propagates values up the tree.
Definition at line 2281 of file search.cc.
References d, lczero::classic::Node::GetN(), lczero::classic::Node::GetParent(), lczero::classic::Node::IsTerminal(), m, p, params_, and search_.
EnsureNodeTwoFoldCorrectForDepth()
void lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth (Node * node, int depth) private
Ensures 3-fold repetition correctness by reverting terminal status if needed.
Definition at line 1585 of file search.cc.
References d, lczero::classic::Node::GetD(), lczero::classic::Node::GetM(), lczero::classic::Node::GetN(), lczero::classic::Node::GetParent(), lczero::classic::Node::GetWL(), lczero::classic::Node::IsTwoFoldTerminal(), m, lczero::classic::Node::MakeNotTerminal(), and search_.
ExecuteOneIteration()
void lczero::classic::SearchWorker::ExecuteOneIteration ()
Executes one complete MCTS iteration.
Executes a single iteration of the search (initialization, gather, NN, backup).
The iteration consists of 7 phases:
Initialize internal structures
Gather minibatch of nodes to evaluate
Prefetch positions into cache
Run neural network computation
Retrieve NN results into nodes
Backpropagate values through tree
Update search statistics
Definition at line 1205 of file search.cc.
References params_, and search_.
Referenced by RunBlocking().
ExtendNode()
void lczero::classic::SearchWorker::ExtendNode (Node * node, int depth, const std::vector< Move > & moves_to_add, PositionHistory * history) private
Extends a leaf node by generating legal moves and checking for terminal states.
Definition at line 1977 of file search.cc.
References lczero::PositionHistory::Append(), lczero::BLACK_WON, lczero::classic::Node::CreateEdges(), lczero::DRAW, lczero::FAIL, lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), lczero::classic::Node::GetParent(), lczero::Position::GetPliesSincePrevRepetition(), lczero::Position::GetRepetitions(), lczero::Position::GetRule50Ply(), lczero::PositionHistory::Last(), legal_moves, m, lczero::classic::Node::MakeTerminal(), lczero::SyzygyTablebase::max_cardinality(), params_, lczero::SyzygyTablebase::probe_wdl(), search_, lczero::SearchBase::syzygy_tb_, lczero::PositionHistory::Trim(), lczero::WDL_LOSS, lczero::WDL_WIN, and lczero::WHITE_WON.
FetchMinibatchResults()
void lczero::classic::SearchWorker::FetchMinibatchResults ()
Phase 5: Retrieve NN results and terminal values.
Retrieves results for all nodes in the minibatch.
Definition at line 2212 of file search.cc.
References LCTRACE_FUNCTION_SCOPE.
FetchSingleNodeResult()
void lczero::classic::SearchWorker::FetchSingleNodeResult (NodeToProcess * node_to_process) private
Retrieves the result for a single node (NN or terminal).
Definition at line 2221 of file search.cc.
References lczero::classic::SearchWorker::NodeToProcess::depth, lczero::classic::Node::Edges(), lczero::classic::SearchWorker::NodeToProcess::eval, lczero::classic::Node::GetD(), lczero::classic::Node::GetM(), lczero::classic::Node::GetWL(), lczero::classic::SearchWorker::NodeToProcess::IsCollision(), lczero::classic::SearchWorker::NodeToProcess::nn_queried, lczero::classic::SearchWorker::NodeToProcess::node, params_, search_, and lczero::classic::Node::SortEdges().
GatherMinibatch()
void lczero::classic::SearchWorker::GatherMinibatch ()
Phase 2: Gather a minibatch of nodes to evaluate.
Gathers a minibatch of nodes to process (extend or evaluate).
Definition at line 1335 of file search.cc.
References lczero::classic::Node::CancelScoreUpdate(), computation_, lczero::classic::Node::GetParent(), lczero::classic::Node::IncrementNInFlight(), LCTRACE_FUNCTION_SCOPE, params_, and search_.
InitializeIteration()
void lczero::classic::SearchWorker::InitializeIteration ()
Phase 1: Initialize internal structures for iteration.
Initializes structures for a new search iteration.
Definition at line 1297 of file search.cc.
References lczero::SearchBase::backend_, computation_, lczero::Backend::CreateComputation(), LCTRACE_FUNCTION_SCOPE, and search_.
MaybePrefetchIntoCache()
void lczero::classic::SearchWorker::MaybePrefetchIntoCache ()
Phase 3: Prefetch positions into evaluation cache.
Prefetches likely future nodes into the backend cache.
Definition at line 2091 of file search.cc.
References computation_, LCTRACE_FUNCTION_SCOPE, params_, and search_.
MaybeSetBounds()
bool lczero::classic::SearchWorker::MaybeSetBounds (Node * p, float m, int * n_to_fix, float * v_delta, float * d_delta, float * m_delta) const private
Updates the bounds of a node based on its children's bounds.
Definition at line 2367 of file search.cc.
References m, and p.
PickNodesToExtend()
void lczero::classic::SearchWorker::PickNodesToExtend (int collision_limit) private
Orchestrates picking nodes to extend, potentially distributing work to task threads.
Definition at line 1558 of file search.cc.
References search_.
PickNodesToExtendTask()
void lczero::classic::SearchWorker::PickNodesToExtendTask (Node * starting_point, int base_depth, int collision_limit, const std::vector< Move > & moves_to_base, std::vector< NodeToProcess > * receiver, TaskWorkspace * workspace) private
Worker task to pick nodes to extend from a sub-tree.
Definition at line 1627 of file search.cc.
References lczero::classic::EdgeAndNode::GetMove(), lczero::classic::Node::GetN(), lczero::classic::Edge_Iterator< is_const >::GetOrSpawnNode(), idx, lczero::classic::Node::IncrementNInFlight(), lczero::classic::Node::IsTerminal(), LCTRACE_FUNCTION_SCOPE, MAX_TASKS, params_, q, lczero::classic::EdgeAndNode::Reset(), search_, and lczero::classic::Node::TryStartScoreUpdate().
PickNodeToExtend()
NodeToProcess lczero::classic::SearchWorker::PickNodeToExtend (int collision_limit) private
PrefetchIntoCache()
int lczero::classic::SearchWorker::PrefetchIntoCache (Node * node, int budget, bool is_odd_depth) private
Recursively finds and prefetches nodes into the cache.
Definition at line 2111 of file search.cc.
References lczero::SearchBase::backend_, computation_, lczero::Backend::GetCachedEvaluation(), lczero::classic::Node::GetNStarted(), moves, and search_.
ProcessPickedTask()
void lczero::classic::SearchWorker::ProcessPickedTask (int batch_start, int batch_end, TaskWorkspace * workspace) private
Processes a range of picked tasks (nodes) to prepare them for evaluation.
Definition at line 1492 of file search.cc.
References computation_, lczero::BackendComputation::FETCHED_IMMEDIATELY, lczero::classic::SearchWorker::TaskWorkspace::history, LCTRACE_FUNCTION_SCOPE, legal_moves, params_, lczero::EvalPosition::pos, and search_.
ResetTasks()
void lczero::classic::SearchWorker::ResetTasks () private
Resets the task queue and counters.
Definition at line 1536 of file search.cc.
References MAX_TASKS.
RunBlocking()
void lczero::classic::SearchWorker::RunBlocking () inline
Runs search iterations until search is stopped.
Main entry point for worker thread execution.
Definition at line 319 of file search.h.
References ExecuteOneIteration(), lczero::classic::Search::IsSearchActive(), LOGFILE, and search_.
Referenced by lczero::classic::Search::StartThreads().
RunNNComputation()
void lczero::classic::SearchWorker::RunNNComputation ()
Phase 4: Run neural network evaluation.
blocking call to run the neural network computation.
Definition at line 2205 of file search.cc.
References computation_.
RunTasks()
void lczero::classic::SearchWorker::RunTasks (int tid) private
Main loop for a search worker thread to process tasks.
Definition at line 1130 of file search.cc.
References lczero::classic::SearchWorker::PickTask::base_depth, lczero::classic::SearchWorker::PickTask::collision_limit, lczero::classic::SearchWorker::PickTask::end_idx, lczero::classic::SearchWorker::PickTask::moves_to_base, lczero::classic::SearchWorker::PickTask::results, lczero::SpinloopPause(), lczero::classic::SearchWorker::PickTask::start, lczero::classic::SearchWorker::PickTask::start_idx, and lczero::classic::SearchWorker::PickTask::task_type.
Referenced by SearchWorker().
UpdateCounters()
void lczero::classic::SearchWorker::UpdateCounters ()
Phase 7: Update global search counters.
Updates search statistics and handles time management triggers.
Definition at line 2439 of file search.cc.
References LCTRACE_FUNCTION_SCOPE, and search_.
WaitForTasks()
int lczero::classic::SearchWorker::WaitForTasks () private
Waits for all assigned tasks to complete.
Definition at line 1546 of file search.cc.
References lczero::SpinloopPause().
Member Data Documentation
completed_tasks_
std::atomic<int> lczero::classic::SearchWorker::completed_tasks_ = 0 private
Definition at line 510 of file search.h.
computation_
std::unique_ptr<BackendComputation> lczero::classic::SearchWorker::computation_ private
Definition at line 491 of file search.h.
exiting_
bool lczero::classic::SearchWorker::exiting_ = false private
Definition at line 515 of file search.h.
Referenced by ~SearchWorker().
history_
PositionHistory lczero::classic::SearchWorker::history_ private
Definition at line 496 of file search.h.
iteration_stats_
IterationStats lczero::classic::SearchWorker::iteration_stats_ private
Definition at line 500 of file search.h.
latest_time_manager_hints_
StoppersHints lczero::classic::SearchWorker::latest_time_manager_hints_ private
Definition at line 501 of file search.h.
main_workspace_
TaskWorkspace lczero::classic::SearchWorker::main_workspace_ private
Definition at line 514 of file search.h.
max_out_of_order_
int lczero::classic::SearchWorker::max_out_of_order_ private
Definition at line 494 of file search.h.
Referenced by SearchWorker().
minibatch_
std::vector<NodeToProcess> lczero::classic::SearchWorker::minibatch_ private
Definition at line 490 of file search.h.
moves_left_support_
const bool lczero::classic::SearchWorker::moves_left_support_ private
Definition at line 499 of file search.h.
number_out_of_order_
int lczero::classic::SearchWorker::number_out_of_order_ = 0 private
Definition at line 497 of file search.h.
params_
const SearchParams& lczero::classic::SearchWorker::params_ private
Definition at line 498 of file search.h.
Referenced by SearchWorker().
picking_tasks_
std::vector<PickTask> lczero::classic::SearchWorker::picking_tasks_ private
Definition at line 506 of file search.h.
picking_tasks_mutex_
Mutex lczero::classic::SearchWorker::picking_tasks_mutex_ private
Definition at line 505 of file search.h.
Referenced by ~SearchWorker().
search_
Search* const lczero::classic::SearchWorker::search_ private
Definition at line 488 of file search.h.
Referenced by RunBlocking(), and SearchWorker().
target_minibatch_size_
int lczero::classic::SearchWorker::target_minibatch_size_ private
Definition at line 493 of file search.h.
Referenced by SearchWorker().
task_added_
std::condition_variable lczero::classic::SearchWorker::task_added_ private
Definition at line 511 of file search.h.
Referenced by ~SearchWorker().
task_count_
std::atomic<int> lczero::classic::SearchWorker::task_count_ = -1 private
Definition at line 507 of file search.h.
Referenced by ~SearchWorker().
task_taking_started_
std::atomic<int> lczero::classic::SearchWorker::task_taking_started_ = 0 private
Definition at line 508 of file search.h.
task_threads_
std::vector<std::thread> lczero::classic::SearchWorker::task_threads_ private
Definition at line 512 of file search.h.
Referenced by SearchWorker(), and ~SearchWorker().
task_workers_
int lczero::classic::SearchWorker::task_workers_ private
Definition at line 492 of file search.h.
Referenced by SearchWorker().
task_workspaces_
std::vector<TaskWorkspace> lczero::classic::SearchWorker::task_workspaces_ private
Definition at line 513 of file search.h.
Referenced by SearchWorker().
tasks_taken_
std::atomic<int> lczero::classic::SearchWorker::tasks_taken_ = 0 private
Definition at line 509 of file search.h.
The documentation for this class was generated from the following files:
src/search/classic/search.h
src/search/classic/search.cc