Leela Chess Zero: lczero::XlaTensor Class Reference
lczero::XlaTensor Class Reference abstract
#include <xla_tensor.h>
Public Member Functions
virtual ~XlaTensor ()=default
virtual const std::vector< int64_t > & shape () const =0
virtual const void * data () const =0
virtual size_t size () const =0
virtual size_t capacity () const =0
virtual pblczero::XlaShapeProto::Type type () const =0
std::string DebugString ()
Detailed Description
Definition at line 66 of file xla_tensor.h.
Constructor & Destructor Documentation
~XlaTensor()
virtual lczero::XlaTensor::~XlaTensor () virtual default
Member Function Documentation
capacity()
virtual size_t lczero::XlaTensor::capacity () const pure virtual
Implemented in lczero::XlaTensorNotOwned, and lczero::XlaMutableTensor.
data()
virtual const void * lczero::XlaTensor::data () const pure virtual
Implemented in lczero::XlaTensorNotOwned, and lczero::XlaMutableTensor.
Referenced by DebugString().
DebugString()
std::string lczero::XlaTensor::DebugString ()
Definition at line 50 of file xla_tensor.cc.
References data(), result, shape(), size(), and type().
shape()
virtual const std::vector< int64_t > & lczero::XlaTensor::shape () const pure virtual
Implemented in lczero::XlaTensorNotOwned, and lczero::XlaMutableTensor.
Referenced by DebugString().
size()
virtual size_t lczero::XlaTensor::size () const pure virtual
Implemented in lczero::XlaTensorNotOwned, and lczero::XlaMutableTensor.
Referenced by DebugString().
type()
virtual pblczero::XlaShapeProto::Type lczero::XlaTensor::type () const pure virtual
Implemented in lczero::XlaTensorNotOwned, and lczero::XlaMutableTensor.
Referenced by DebugString().
The documentation for this class was generated from the following files:
src/neural/xla/xla_tensor.h
src/neural/xla/xla_tensor.cc