Leela Chess Zero: lczero::sycldnn_backend::SELayer< DataType > Class Template Reference
lczero::sycldnn_backend::SELayer< DataType > Class Template Reference
Fused Squeeze-and-Excitation (SE) Layer.
#include <layers.h>
Public Member Functions
SELayer (BaseLayer< DataType > *ip, int numFc1Out, bool addPrevLayerBias, ActivationFunction activation, sycl::queue &sycl_queue)
~SELayer ()
void LoadWeights (float *w1, float *b1, float *w2, float *b2, float *prevLayerBias, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, sycl::queue &sycl_queue, DataType ***=nullptr) override
Evaluates the layer.
void LoadWeights (float *w1, float *b1, float *w2, float *b2, float *prevLayerBias, void *)
void LoadWeights (float *w1, float *b1, float *w2, float *b2, float *prevLayerBias, void *scratch)
void Eval (int N, float *output, const float *input, const float *, void *scratch, size_t scratch_size, sycl::queue &sycl_queue, float ***)
void Eval (int N, sycl::half *output, const sycl::half *input, const sycl::half *input2, void *scratch, size_t scratch_size, sycl::queue &sycl_queue, sycl::half ***)
Public Member Functions inherited from lczero::sycldnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
sycl::queue GetSycl_Queue ()
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip, sycl::queue &sycl_queue)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, sycl::queue &sycl_queue)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
DataType * w1_ = nullptr
DataType * w1_t_ = nullptr
DataType * b1_ = nullptr
DataType * w2_ = nullptr
DataType * w2_t_ = nullptr
DataType * b2_ = nullptr
DataType * bPrev_ = nullptr
int numFc1Out_
bool addPrevLayerBias_
const ActivationFunction act_
Additional Inherited Members
Protected Member Functions inherited from lczero::sycldnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasRowMajorMatrixMul (const sycl::half *A, const sycl::half *B, sycl::half *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, sycl::queue &sycl_queue)
Protected Attributes inherited from lczero::sycldnn_backend::BaseLayer< DataType >
BaseLayer * input_
sycl::queue & sycl_queue_
int C
int H
int W
bool nhwc_
Detailed Description
template<typename DataType>
class lczero::sycldnn_backend::SELayer< DataType >
Fused Squeeze-and-Excitation (SE) Layer.
Operations: (optional bias add +) global avg -> FC1 -> FC2 -> global scale -> add skip connection -> RELU.
Definition at line 136 of file layers.h.
Constructor & Destructor Documentation
SELayer()
template<typename DataType > lczero::sycldnn_backend::SELayer< DataType >::SELayer (BaseLayer< DataType > * ip, int numFc1Out, bool addPrevLayerBias, ActivationFunction activation, sycl::queue & sycl_queue)
Definition at line 94 of file layers.cc.dp.cpp.
References lczero::sycldnn_backend::SELayer< DataType >::b1_, lczero::sycldnn_backend::SELayer< DataType >::b2_, lczero::sycldnn_backend::SELayer< DataType >::bPrev_, lczero::sycldnn_backend::BaseLayer< DataType >::C, lczero::sycldnn_backend::kUseFusedSELayer, lczero::sycldnn_backend::BaseLayer< DataType >::nhwc_, lczero::sycldnn_backend::SELayer< DataType >::numFc1Out_, lczero::sycldnn_backend::BaseLayer< DataType >::sycl_queue_, lczero::sycldnn_backend::SELayer< DataType >::w1_, lczero::sycldnn_backend::SELayer< DataType >::w1_t_, lczero::sycldnn_backend::SELayer< DataType >::w2_, and lczero::sycldnn_backend::SELayer< DataType >::w2_t_.
~SELayer()
template<typename DataType > lczero::sycldnn_backend::SELayer< DataType >::~SELayer ()
Definition at line 120 of file layers.cc.dp.cpp.
Member Function Documentation
Eval() [1/3]
template<typename DataType > void lczero::sycldnn_backend::SELayer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, sycl::queue & sycl_queue, DataType *** = nullptr) override virtual
Evaluates the layer.
Implements lczero::sycldnn_backend::BaseLayer< DataType >.
Eval() [2/3]
void lczero::sycldnn_backend::SELayer< float >::Eval (int N, float * output, const float * input, const float * , void * scratch, size_t scratch_size, sycl::queue & sycl_queue, float ***)
Definition at line 220 of file layers.cc.dp.cpp.
References lczero::ACTIVATION_NONE, lczero::sycldnn_backend::addVectors(), C, lczero::sycldnn_backend::globalAvgPool(), lczero::sycldnn_backend::globalScale(), input, output, ReportCUBLASErrors, transpose_type_notranspose, and transpose_type_transpose.
Eval() [3/3]
void lczero::sycldnn_backend::SELayer< sycl::half >::Eval (int N, sycl::half * output, const sycl::half * input, const sycl::half * input2, void * scratch, size_t scratch_size, sycl::queue & sycl_queue, sycl::half ***)
Definition at line 327 of file layers.cc.dp.cpp.
References lczero::ACTIVATION_NONE, lczero::sycldnn_backend::addVectors(), C, lczero::sycldnn_backend::globalAvgPool(), lczero::sycldnn_backend::globalScale(), input, lczero::sycldnn_backend::kUseFusedSELayer, output, ReportCUBLASErrors, lczero::sycldnn_backend::Se_Fp16_NHWC(), transpose_type_notranspose, and transpose_type_transpose.
LoadWeights() [1/3]
void lczero::sycldnn_backend::SELayer< float >::LoadWeights (float * w1, float * b1, float * w2, float * b2, float * prevLayerBias, void *)
Definition at line 129 of file layers.cc.dp.cpp.
References C.
LoadWeights() [2/3]
void lczero::sycldnn_backend::SELayer< sycl::half >::LoadWeights (float * w1, float * b1, float * w2, float * b2, float * prevLayerBias, void * scratch)
Definition at line 162 of file layers.cc.dp.cpp.
References C, lczero::sycldnn_backend::copyTypeConverted(), lczero::sycldnn_backend::cpuTranspose(), and lczero::sycldnn_backend::kUseFusedSELayer.
LoadWeights() [3/3]
template<typename DataType > void lczero::sycldnn_backend::SELayer< DataType >::LoadWeights (float * w1, float * b1, float * w2, float * b2, float * prevLayerBias, void * scratch)
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::sycldnn_backend::SELayer< DataType >::act_ private
Definition at line 163 of file layers.h.
addPrevLayerBias_
template<typename DataType > bool lczero::sycldnn_backend::SELayer< DataType >::addPrevLayerBias_ private
Definition at line 162 of file layers.h.
b1_
template<typename DataType > DataType* lczero::sycldnn_backend::SELayer< DataType >::b1_ = nullptr private
Definition at line 156 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
b2_
template<typename DataType > DataType* lczero::sycldnn_backend::SELayer< DataType >::b2_ = nullptr private
Definition at line 159 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
bPrev_
template<typename DataType > DataType* lczero::sycldnn_backend::SELayer< DataType >::bPrev_ = nullptr private
Definition at line 160 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
numFc1Out_
template<typename DataType > int lczero::sycldnn_backend::SELayer< DataType >::numFc1Out_ private
Definition at line 161 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
w1_
template<typename DataType > DataType* lczero::sycldnn_backend::SELayer< DataType >::w1_ = nullptr private
Definition at line 154 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
w1_t_
template<typename DataType > DataType* lczero::sycldnn_backend::SELayer< DataType >::w1_t_ = nullptr private
Definition at line 155 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
w2_
template<typename DataType > DataType* lczero::sycldnn_backend::SELayer< DataType >::w2_ = nullptr private
Definition at line 157 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
w2_t_
template<typename DataType > DataType* lczero::sycldnn_backend::SELayer< DataType >::w2_t_ = nullptr private
Definition at line 158 of file layers.h.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::SELayer().
The documentation for this class was generated from the following files:
src/neural/backends/sycl/layers.h
src/neural/backends/sycl/layers.cc.dp.cpp