Leela Chess Zero: lczero::dag_classic::Edge_Iterator< is_const > Class Template Reference
lczero::dag_classic::Edge_Iterator< is_const > Class Template Reference
#include <node.h>
Public Types
using Ptr = std::conditional_t< is_const, const atomic_unique_ptr< Node > *, atomic_unique_ptr< Node > * >
using value_type = Edge_Iterator
using iterator_category = std::forward_iterator_tag
using difference_type = std::ptrdiff_t
using pointer = Edge_Iterator *
using reference = Edge_Iterator &
Public Member Functions
Edge_Iterator ()
Creates "end()" iterator.
Edge_Iterator (LowNode *parent_node)
Creates "begin()" iterator.
Edge_Iterator< is_const > begin ()
Edge_Iterator< is_const > end ()
void operator++ ()
Edge_Iterator & operator* ()
Node * GetOrSpawnNode (Node *parent)
Public Member Functions inherited from lczero::dag_classic::EdgeAndNode
EdgeAndNode ()=default
EdgeAndNode (Edge *edge, Node *node)
void Reset ()
operator bool () const
bool operator== (const EdgeAndNode &other) const
bool operator!= (const EdgeAndNode &other) const
bool HasNode () const
Edge * edge () const
Node * node () const
float GetQ (float default_q, float draw_score) const
float GetWL (float default_wl) const
float GetD (float default_d) const
float GetM (float default_m) const
uint32_t GetN () const
int GetNStarted () const
uint32_t GetNInFlight () const
bool IsTerminal () const
bool IsTbTerminal () const
Bounds GetBounds () const
float GetP () const
Move GetMove (bool flip=false) const
float GetU (float numerator) const
Returns U = numerator * p / (N + 1).
std::string DebugString () const
Private Member Functions
Node * Actualize ()
Private Attributes
Ptr node_ptr_
uint16_t current_idx_ = 0
uint16_t total_count_ = 0
Additional Inherited Members
Protected Attributes inherited from lczero::dag_classic::EdgeAndNode
Edge * edge_ = nullptr
Node * node_ = nullptr
Detailed Description
template<bool is_const>
class lczero::dag_classic::Edge_Iterator< is_const >
Definition at line 852 of file node.h.
Member Typedef Documentation
difference_type
template<bool is_const> using lczero::dag_classic::Edge_Iterator< is_const >::difference_type = std::ptrdiff_t
Definition at line 858 of file node.h.
iterator_category
template<bool is_const> using lczero::dag_classic::Edge_Iterator< is_const >::iterator_category = std::forward_iterator_tag
Definition at line 857 of file node.h.
pointer
template<bool is_const> using lczero::dag_classic::Edge_Iterator< is_const >::pointer = Edge_Iterator*
Definition at line 859 of file node.h.
Ptr
template<bool is_const> using lczero::dag_classic::Edge_Iterator< is_const >::Ptr = std::conditional_t<is_const, const atomic_unique_ptr<Node>*, atomic_unique_ptr<Node>*>
Definition at line 854 of file node.h.
reference
template<bool is_const> using lczero::dag_classic::Edge_Iterator< is_const >::reference = Edge_Iterator&
Definition at line 860 of file node.h.
value_type
template<bool is_const> using lczero::dag_classic::Edge_Iterator< is_const >::value_type = Edge_Iterator
Definition at line 856 of file node.h.
Constructor & Destructor Documentation
Edge_Iterator() [1/2]
template<bool is_const> lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator () inline
Creates "end()" iterator.
Definition at line 863 of file node.h.
Edge_Iterator() [2/2]
template<bool is_const> lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator (LowNode * parent_node) inline
Creates "begin()" iterator.
Definition at line 866 of file node.h.
References lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), lczero::dag_classic::EdgeAndNode::edge_, lczero::dag_classic::LowNode::GetChild(), lczero::dag_classic::LowNode::GetNumEdges(), lczero::dag_classic::Edge_Iterator< is_const >::node_ptr_, and lczero::dag_classic::Edge_Iterator< is_const >::total_count_.
Member Function Documentation
Actualize()
template<bool is_const> Node * lczero::dag_classic::Edge_Iterator< is_const >::Actualize () inline private
Definition at line 944 of file node.h.
References lczero::dag_classic::Edge_Iterator< is_const >::current_idx_, lczero::dag_classic::Node::GetSibling(), lczero::dag_classic::Node::Index(), lczero::dag_classic::EdgeAndNode::node(), lczero::dag_classic::EdgeAndNode::node_, and lczero::dag_classic::Edge_Iterator< is_const >::node_ptr_.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator(), lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode(), and lczero::dag_classic::Edge_Iterator< is_const >::operator++().
begin()
template<bool is_const> Edge_Iterator< is_const > lczero::dag_classic::Edge_Iterator< is_const >::begin () inline
Definition at line 877 of file node.h.
end()
template<bool is_const> Edge_Iterator< is_const > lczero::dag_classic::Edge_Iterator< is_const >::end () inline
Definition at line 878 of file node.h.
GetOrSpawnNode()
template<bool is_const> Node * lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode (Node * parent) inline
Definition at line 894 of file node.h.
References lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), lczero::dag_classic::Edge_Iterator< is_const >::current_idx_, lczero::dag_classic::Node::GetLowNode(), lczero::dag_classic::EdgeAndNode::node(), lczero::dag_classic::EdgeAndNode::node_, and lczero::dag_classic::Edge_Iterator< is_const >::node_ptr_.
Referenced by lczero::dag_classic::SearchWorker::PickNodesToExtendTask().
operator*()
template<bool is_const> Edge_Iterator & lczero::dag_classic::Edge_Iterator< is_const >::operator* () inline
Definition at line 891 of file node.h.
operator++()
template<bool is_const> void lczero::dag_classic::Edge_Iterator< is_const >::operator++ () inline
Definition at line 882 of file node.h.
References lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), lczero::dag_classic::Edge_Iterator< is_const >::current_idx_, lczero::dag_classic::EdgeAndNode::edge_, and lczero::dag_classic::Edge_Iterator< is_const >::total_count_.
Member Data Documentation
current_idx_
template<bool is_const> uint16_t lczero::dag_classic::Edge_Iterator< is_const >::current_idx_ = 0 private
Definition at line 971 of file node.h.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode(), and lczero::dag_classic::Edge_Iterator< is_const >::operator++().
node_ptr_
template<bool is_const> Ptr lczero::dag_classic::Edge_Iterator< is_const >::node_ptr_ private
Definition at line 970 of file node.h.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Actualize(), lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator(), and lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode().
total_count_
template<bool is_const> uint16_t lczero::dag_classic::Edge_Iterator< is_const >::total_count_ = 0 private
Definition at line 972 of file node.h.
Referenced by lczero::dag_classic::Edge_Iterator< is_const >::Edge_Iterator(), and lczero::dag_classic::Edge_Iterator< is_const >::operator++().
The documentation for this class was generated from the following file:
src/search/dag_classic/node.h