Leela Chess Zero: lczero::LayerAdapter Class Reference
lczero::LayerAdapter Class Reference
#include <weights_adapter.h>
Classes
class Iterator
Public Member Functions
LayerAdapter (const pblczero::Weights::Layer &layer)
std::vector< float > as_vector () const
size_t size () const
float operator[] (size_t idx) const
Iterator begin () const
Iterator end () const
Private Attributes
const pblczero::Weights::Layer::Encoding encoding_
const size_t element_size_ = 0
const std::byte * data_ = nullptr
const size_t size_ = 0
const float min_
const float max_
Detailed Description
Definition at line 38 of file weights_adapter.h.
Constructor & Destructor Documentation
LayerAdapter()
lczero::LayerAdapter::LayerAdapter (const pblczero::Weights::Layer & layer)
Definition at line 64 of file weights_adapter.cc.
References encoding_.
Member Function Documentation
as_vector()
std::vector< float > lczero::LayerAdapter::as_vector () const
Definition at line 86 of file weights_adapter.cc.
References begin(), and end().
Referenced by lczero::MultiHeadWeights::MultiHeadWeights().
begin()
Iterator lczero::LayerAdapter::begin () const inline
Definition at line 88 of file weights_adapter.h.
References data_.
Referenced by as_vector(), and operator[]().
end()
Iterator lczero::LayerAdapter::end () const inline
Definition at line 89 of file weights_adapter.h.
References data_, element_size_, and size_.
Referenced by as_vector().
operator[]()
float lczero::LayerAdapter::operator[] (size_t idx) const inline
Definition at line 87 of file weights_adapter.h.
References begin(), and idx.
size()
size_t lczero::LayerAdapter::size () const inline
Definition at line 86 of file weights_adapter.h.
References size_.
Member Data Documentation
data_
const std::byte* lczero::LayerAdapter::data_ = nullptr private
Definition at line 94 of file weights_adapter.h.
Referenced by begin(), end(), and lczero::LayerAdapter::Iterator::operator[]().
element_size_
const size_t lczero::LayerAdapter::element_size_ = 0 private
Definition at line 93 of file weights_adapter.h.
Referenced by end(), lczero::LayerAdapter::Iterator::operator++(), lczero::LayerAdapter::Iterator::operator-(), and lczero::LayerAdapter::Iterator::operator--().
encoding_
const pblczero::Weights::Layer::Encoding lczero::LayerAdapter::encoding_ private
Definition at line 92 of file weights_adapter.h.
Referenced by lczero::LayerAdapter::Iterator::ExtractValue(), and LayerAdapter().
max_
const float lczero::LayerAdapter::max_ private
Definition at line 97 of file weights_adapter.h.
Referenced by lczero::LayerAdapter::Iterator::ExtractValue().
min_
const float lczero::LayerAdapter::min_ private
Definition at line 96 of file weights_adapter.h.
Referenced by lczero::LayerAdapter::Iterator::ExtractValue().
size_
const size_t lczero::LayerAdapter::size_ = 0 private
Definition at line 95 of file weights_adapter.h.
Referenced by end(), and size().
The documentation for this class was generated from the following files:
src/utils/weights_adapter.h
src/utils/weights_adapter.cc