Leela Chess Zero: lczero::classic::SmartPruningStopper Class Reference
lczero::classic::SmartPruningStopper Class Reference
Smart pruning stopper for early search termination.
#include <stoppers.h>
Public Member Functions
SmartPruningStopper (float smart_pruning_factor, int64_t minimum_batches)
Constructs smart pruning stopper.
bool ShouldStop (const IterationStats &, StoppersHints *) override
Checks if smart pruning condition is met.
Public Member Functions inherited from lczero::classic::SearchStopper
virtual ~SearchStopper ()=default
Virtual destructor for proper cleanup.
virtual void OnSearchDone (const IterationStats &)
Called when search completes.
Private Member Functions
std::optional< int64_t > first_eval_time_ GUARDED_BY (mutex_)
Time of first evaluation (for NPS calculation).
Private Attributes
const double smart_pruning_factor_
Scaling factor for pruning threshold.
const int64_t minimum_batches_
Minimum batches required before pruning.
Mutex mutex_
Mutex for thread-safe access.
Detailed Description
Smart pruning stopper for early search termination.
Computes remaining nodes from time/node limits and stops when it's impossible for the second-best move to become best. Uses a configurable pruning factor to adjust aggressiveness.
Definition at line 229 of file stoppers.h.
Constructor & Destructor Documentation
SmartPruningStopper()
lczero::classic::SmartPruningStopper::SmartPruningStopper (float smart_pruning_factor, int64_t minimum_batches)
Constructs smart pruning stopper.
Parameters
smart_pruning_factor Scaling factor for pruning threshold.
minimum_batches Minimum batches before pruning can trigger.
Definition at line 199 of file stoppers.cc.
Member Function Documentation
GUARDED_BY()
std::optional< int64_t > first_eval_time_ lczero::classic::SmartPruningStopper::GUARDED_BY (mutex_) private
Time of first evaluation (for NPS calculation).
ShouldStop()
bool lczero::classic::SmartPruningStopper::ShouldStop (const IterationStats & stats, StoppersHints * hints) override virtual
Checks if smart pruning condition is met.
Returns
True if best move cannot change.
Implements lczero::classic::SearchStopper.
Definition at line 204 of file stoppers.cc.
References lczero::classic::IterationStats::batches_since_movestart, lczero::classic::IterationStats::edge_n, lczero::classic::StoppersHints::GetEstimatedNps(), lczero::classic::StoppersHints::GetEstimatedRemainingPlayouts(), lczero::classic::StoppersHints::GetEstimatedRemainingTimeMs(), LOGFILE, lczero::classic::IterationStats::may_resign, minimum_batches_, mutex_, lczero::classic::IterationStats::nodes_since_movestart, lczero::classic::IterationStats::num_losing_edges, smart_pruning_factor_, lczero::classic::IterationStats::time_since_movestart, lczero::classic::StoppersHints::UpdateEstimatedRemainingPlayouts(), and lczero::classic::IterationStats::win_found.
Member Data Documentation
minimum_batches_
const int64_t lczero::classic::SmartPruningStopper::minimum_batches_ private
Minimum batches required before pruning.
Definition at line 245 of file stoppers.h.
Referenced by ShouldStop().
mutex_
Mutex lczero::classic::SmartPruningStopper::mutex_ private
Mutex for thread-safe access.
Definition at line 248 of file stoppers.h.
Referenced by ShouldStop().
smart_pruning_factor_
const double lczero::classic::SmartPruningStopper::smart_pruning_factor_ private
Scaling factor for pruning threshold.
Definition at line 242 of file stoppers.h.
Referenced by ShouldStop().
The documentation for this class was generated from the following files:
src/search/classic/stoppers/stoppers.h
src/search/classic/stoppers/stoppers.cc