Leela Chess Zero: lczero::V6TrainingDataArray Class Reference
lczero::V6TrainingDataArray Class Reference
#include <trainingdata.h>
Public Member Functions
V6TrainingDataArray (FillEmptyHistory white_fill_empty_history, FillEmptyHistory black_fill_empty_history, pblczero::NetworkFormat::InputFormat input_format)
void Add (const classic::Node *node, const PositionHistory &history, classic::Eval best_eval, classic::Eval played_eval, bool best_is_proven, Move best_move, Move played_move, std::span< Move > legal_moves, const std::optional< EvalResult > &nneval, float policy_softmax_temp)
void Write (TrainingDataWriter *writer, GameResult result, bool adjudicated) const
Private Attributes
std::vector< V6TrainingData > training_data_
FillEmptyHistory fill_empty_history_ [2]
pblczero::NetworkFormat::InputFormat input_format_
Detailed Description
Definition at line 37 of file trainingdata.h.
Constructor & Destructor Documentation
V6TrainingDataArray()
lczero::V6TrainingDataArray::V6TrainingDataArray (FillEmptyHistory white_fill_empty_history, FillEmptyHistory black_fill_empty_history, pblczero::NetworkFormat::InputFormat input_format) inline
Definition at line 39 of file trainingdata.h.
Member Function Documentation
Add()
void lczero::V6TrainingDataArray::Add (const classic::Node * node, const PositionHistory & history, classic::Eval best_eval, classic::Eval played_eval, bool best_is_proven, Move best_move, Move played_move, std::span< Move > legal_moves, const std::optional< EvalResult > & nneval, float policy_softmax_temp)
Definition at line 114 of file trainingdata.cc.
References lczero::classic::Eval::d, lczero::classic::Node::Edges(), lczero::EncodePositionForNN(), fill_empty_history_, lczero::Move::Flip(), lczero::FlipTransform, lczero::classic::Node::GetChildrenVisits(), lczero::classic::Node::GetD(), lczero::classic::Node::GetM(), lczero::classic::Node::GetN(), lczero::classic::Node::GetNumEdges(), lczero::classic::Node::GetWL(), input_format_, lczero::Is960CastlingFormat(), lczero::IsCanonicalFormat(), lczero::PositionHistory::Last(), legal_moves, lczero::classic::Eval::ml, lczero::MoveToNNIndex(), result, lczero::ReverseBitsInBytes(), training_data_, transform, and lczero::classic::Eval::wl.
Referenced by lczero::SelfPlayGame::Play().
Write()
void lczero::V6TrainingDataArray::Write (TrainingDataWriter * writer, GameResult result, bool adjudicated) const
Definition at line 80 of file trainingdata.cc.
References lczero::BLACK_WON, lczero::IsCanonicalFormat(), result, training_data_, lczero::UNDECIDED, lczero::WHITE_WON, and lczero::TrainingDataWriter::WriteChunk().
Referenced by lczero::SelfPlayGame::WriteTrainingData().
Member Data Documentation
fill_empty_history_
FillEmptyHistory lczero::V6TrainingDataArray::fill_empty_history_[2] private
Definition at line 58 of file trainingdata.h.
Referenced by Add().
input_format_
pblczero::NetworkFormat::InputFormat lczero::V6TrainingDataArray::input_format_ private
Definition at line 59 of file trainingdata.h.
Referenced by Add().
training_data_
std::vector<V6TrainingData> lczero::V6TrainingDataArray::training_data_ private
Definition at line 57 of file trainingdata.h.
Referenced by Add(), and Write().
The documentation for this class was generated from the following files:
src/trainingdata/trainingdata.h
src/trainingdata/trainingdata.cc