Leela Chess Zero: lczero::SelfPlayGame Class Reference
lczero::SelfPlayGame Class Reference
#include <game.h>
Public Member Functions
SelfPlayGame (PlayerOptions white, PlayerOptions black, bool shared_tree, const Opening &opening)
void Play (int white_threads, int black_threads, bool training, SyzygyTablebase *syzygy_tb, bool enable_resign=true)
void Abort ()
int GetStartPly () const
void WriteTrainingData (TrainingDataWriter *writer) const
GameResult GetGameResult () const
std::vector< Move > GetMoves () const
float GetWorstEvalForWinnerOrDraw () const
Static Public Member Functions
static void PopulateUciParams (OptionsParser *options)
Public Attributes
int move_count_ = 0
uint64_t nodes_total_ = 0
Private Attributes
PlayerOptions options_ [2]
std::shared_ptr< classic::NodeTree > tree_ [2]
std::string orig_fen_
int start_ply_
std::unique_ptr< classic::Search > search_
bool abort_ = false
GameResult game_result_ = GameResult::UNDECIDED
bool adjudicated_ = false
float min_eval_ [2] = {1.0f, 1.0f}
float max_eval_ [3] = {0.0f, 0.0f, 0.0f}
const bool chess960_
std::mutex mutex_
V6TrainingDataArray training_data_
std::unique_ptr< SyzygyTablebase > syzygy_tb_
Detailed Description
Definition at line 66 of file game.h.
Constructor & Destructor Documentation
SelfPlayGame()
lczero::SelfPlayGame::SelfPlayGame (PlayerOptions white, PlayerOptions black, bool shared_tree, const Opening & opening)
Definition at line 82 of file game.cc.
References lczero::Random::Get(), lczero::OptionsDict::Get(), lczero::Random::GetFloat(), m, lczero::Opening::moves, orig_fen_, lczero::Opening::start_fen, start_ply_, tree_, and lczero::PlayerOptions::uci_options.
Member Function Documentation
Abort()
void lczero::SelfPlayGame::Abort ()
Definition at line 345 of file game.cc.
References abort_, mutex_, and search_.
GetGameResult()
GameResult lczero::SelfPlayGame::GetGameResult () const inline
Definition at line 91 of file game.h.
References game_result_.
GetMoves()
std::vector< Move > lczero::SelfPlayGame::GetMoves () const
Definition at line 309 of file game.cc.
References lczero::Move::Flip(), lczero::classic::Node::GetParent(), lczero::Position::IsBlackToMove(), moves, result, and tree_.
Referenced by Play().
GetStartPly()
int lczero::SelfPlayGame::GetStartPly () const inline
Definition at line 86 of file game.h.
References start_ply_.
GetWorstEvalForWinnerOrDraw()
float lczero::SelfPlayGame::GetWorstEvalForWinnerOrDraw () const
Definition at line 328 of file game.cc.
References lczero::BLACK_WON, game_result_, max_eval_, min_eval_, options_, and lczero::WHITE_WON.
Play()
void lczero::SelfPlayGame::Play (int white_threads, int black_threads, bool training, SyzygyTablebase * syzygy_tb, bool enable_resign = true)
Definition at line 131 of file game.cc.
References abort_, lczero::V6TrainingDataArray::Add(), adjudicated_, lczero::PositionHistory::Append(), lczero::PlayerOptions::backend, lczero::BLACK_WON, CERR, lczero::PositionHistory::ComputeGameResult(), lczero::classic::Eval::d, lczero::PlayerOptions::discarded_callback, lczero::DRAW, lczero::Move::Flip(), game_result_, lczero::OptionsDict::Get(), lczero::Backend::GetCachedEvaluation(), GetMoves(), idx, legal_moves, lczero::SelfPlayLimits::MakeSearchStopper(), max_eval_, min_eval_, lczero::classic::Eval::ml, move_count_, mutex_, nodes_total_, options_, orig_fen_, lczero::classic::PopulateIntrinsicStoppers(), search_, lczero::PlayerOptions::search_limits, syzygy_tb_, training_data_, tree_, lczero::PlayerOptions::uci_options, lczero::UNDECIDED, lczero::WHITE_WON, and lczero::classic::Eval::wl.
PopulateUciParams()
void lczero::SelfPlayGame::PopulateUciParams (OptionsParser * options) static
Definition at line 70 of file game.cc.
References lczero::OptionsParser::Add(), and lczero::classic::kSelfplay.
Referenced by lczero::SelfPlayTournament::PopulateOptions().
WriteTrainingData()
void lczero::SelfPlayGame::WriteTrainingData (TrainingDataWriter * writer) const
Definition at line 351 of file game.cc.
References adjudicated_, game_result_, training_data_, and lczero::V6TrainingDataArray::Write().
Member Data Documentation
abort_
bool lczero::SelfPlayGame::abort_ = false private
Definition at line 111 of file game.h.
Referenced by Abort(), and Play().
adjudicated_
bool lczero::SelfPlayGame::adjudicated_ = false private
Definition at line 113 of file game.h.
Referenced by Play(), and WriteTrainingData().
chess960_
const bool lczero::SelfPlayGame::chess960_ private
Definition at line 120 of file game.h.
game_result_
GameResult lczero::SelfPlayGame::game_result_ = GameResult::UNDECIDED private
Definition at line 112 of file game.h.
Referenced by GetGameResult(), GetWorstEvalForWinnerOrDraw(), Play(), and WriteTrainingData().
max_eval_
float lczero::SelfPlayGame::max_eval_[3] = {0.0f, 0.0f, 0.0f} private
Definition at line 119 of file game.h.
Referenced by GetWorstEvalForWinnerOrDraw(), and Play().
min_eval_
float lczero::SelfPlayGame::min_eval_[2] = {1.0f, 1.0f} private
Definition at line 116 of file game.h.
Referenced by GetWorstEvalForWinnerOrDraw(), and Play().
move_count_
int lczero::SelfPlayGame::move_count_ = 0
Definition at line 96 of file game.h.
Referenced by Play().
mutex_
std::mutex lczero::SelfPlayGame::mutex_ private
Definition at line 121 of file game.h.
Referenced by Abort(), and Play().
nodes_total_
uint64_t lczero::SelfPlayGame::nodes_total_ = 0
Definition at line 97 of file game.h.
Referenced by Play().
options_
PlayerOptions lczero::SelfPlayGame::options_[2] private
Definition at line 101 of file game.h.
Referenced by GetWorstEvalForWinnerOrDraw(), and Play().
orig_fen_
std::string lczero::SelfPlayGame::orig_fen_ private
Definition at line 105 of file game.h.
Referenced by Play(), and SelfPlayGame().
search_
std::unique_ptr<classic::Search> lczero::SelfPlayGame::search_ private
Definition at line 110 of file game.h.
Referenced by Abort(), and Play().
start_ply_
int lczero::SelfPlayGame::start_ply_ private
Definition at line 106 of file game.h.
Referenced by GetStartPly(), and SelfPlayGame().
syzygy_tb_
std::unique_ptr<SyzygyTablebase> lczero::SelfPlayGame::syzygy_tb_ private
Definition at line 126 of file game.h.
Referenced by Play().
training_data_
V6TrainingDataArray lczero::SelfPlayGame::training_data_ private
Definition at line 124 of file game.h.
Referenced by Play(), and WriteTrainingData().
tree_
std::shared_ptr<classic::NodeTree> lczero::SelfPlayGame::tree_[2] private
Definition at line 104 of file game.h.
Referenced by GetMoves(), Play(), and SelfPlayGame().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/selfplay/game.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/selfplay/game.cc