Leela Chess Zero: lczero::python::Input Class Reference
lczero::python::Input Class Reference
#include <weights.h>
Public Member Functions
Input ()=default
void set_mask (int plane, uint64_t mask)
void set_val (int plane, float val)
uint64_t mask (int plane) const
float val (int plane) const
std::unique_ptr< Input > clone () const
const InputPlanes GetPlanes () const
Input (const InputPlanes &data)
Private Member Functions
void CheckPlaneExists (int plane) const
Private Attributes
InputPlanes data_ {kInputPlanes}
Detailed Description
Definition at line 91 of file weights.h.
Constructor & Destructor Documentation
Input() [1/2]
lczero::python::Input::Input () default
Input() [2/2]
lczero::python::Input::Input (const InputPlanes & data) inline
Definition at line 117 of file weights.h.
Member Function Documentation
CheckPlaneExists()
void lczero::python::Input::CheckPlaneExists (int plane) const inline private
Definition at line 120 of file weights.h.
References data_.
Referenced by mask(), set_mask(), set_val(), and val().
clone()
std::unique_ptr< Input > lczero::python::Input::clone () const inline
Definition at line 111 of file weights.h.
References data_.
GetPlanes()
const InputPlanes lczero::python::Input::GetPlanes () const inline
Definition at line 116 of file weights.h.
References data_.
mask()
uint64_t lczero::python::Input::mask (int plane) const inline
Definition at line 103 of file weights.h.
References CheckPlaneExists(), and data_.
Referenced by set_mask().
set_mask()
void lczero::python::Input::set_mask (int plane, uint64_t mask) inline
Definition at line 95 of file weights.h.
References CheckPlaneExists(), data_, and mask().
set_val()
void lczero::python::Input::set_val (int plane, float val) inline
Definition at line 99 of file weights.h.
References CheckPlaneExists(), data_, and val().
val()
float lczero::python::Input::val (int plane) const inline
Definition at line 107 of file weights.h.
References CheckPlaneExists(), and data_.
Referenced by set_val().
Member Data Documentation
data_
InputPlanes lczero::python::Input::data_ {kInputPlanes} private
Definition at line 127 of file weights.h.
Referenced by CheckPlaneExists(), clone(), GetPlanes(), mask(), set_mask(), set_val(), and val().
The documentation for this class was generated from the following file:
src/python/weights.h