Leela Chess Zero: lczero::classic::SearchParams Class Reference
lczero::classic::SearchParams Class Reference
Extended search parameters with additional classic-search-specific options.
#include <params.h>
Public Member Functions
SearchParams (const OptionsDict &options)
Constructs search parameters from an options dictionary.
SearchParams (const SearchParams &)=delete
Deleted copy constructor (parameters are not copyable).
int GetMaxPrefetchBatch () const
Gets maximum batch size for prefetch operations.
int GetSolidTreeThreshold () const
Gets threshold for converting to solid tree representation.
Public Member Functions inherited from lczero::classic::BaseSearchParams
BaseSearchParams (const OptionsDict &options)
Constructs search parameters from an options dictionary.
BaseSearchParams (const BaseSearchParams &)=delete
Deleted copy constructor (parameters are not copyable).
int GetMiniBatchSize () const
Gets mini-batch size for neural network evaluation.
float GetCpuct (bool at_root) const
Gets CPUCT exploration constant.
float GetCpuctBase (bool at_root) const
Gets CPUCT base for logarithmic scaling.
float GetCpuctFactor (bool at_root) const
Gets CPUCT scaling factor.
bool GetTwoFoldDraws () const
Whether to use two-fold repetition draws.
float GetTemperature () const
Gets temperature for move selection randomization.
float GetTemperatureVisitOffset () const
Gets temperature visit offset.
int GetTempDecayMoves () const
Gets number of moves for temperature decay.
int GetTempDecayDelayMoves () const
Gets delay before temperature decay starts.
int GetTemperatureCutoffMove () const
Gets move number to cut off temperature.
float GetTemperatureEndgame () const
Gets endgame temperature value.
float GetTemperatureWinpctCutoff () const
Gets win percentage cutoff for temperature.
float GetNoiseEpsilon () const
Gets Dirichlet noise epsilon for root exploration.
float GetNoiseAlpha () const
Gets Dirichlet noise alpha parameter.
bool GetVerboseStats () const
Whether to output verbose move statistics.
bool GetLogLiveStats () const
Whether to log live statistics during search.
bool GetFpuAbsolute (bool at_root) const
Whether FPU value is absolute or relative.
float GetFpuValue (bool at_root) const
Gets FPU value for unexplored nodes.
int GetCacheHistoryLength () const
Gets number of positions to include in cache key.
float GetPolicySoftmaxTemp () const
Gets policy softmax temperature.
int GetMaxCollisionEvents () const
Gets maximum collision events before backing off.
int GetMaxCollisionVisits () const
Gets maximum visits during collision.
bool GetOutOfOrderEval () const
Whether out-of-order evaluation is enabled.
bool GetStickyEndgames () const
Whether sticky endgames option is enabled.
bool GetSyzygyFastPlay () const
Whether fast Syzygy tablebase play is enabled.
int GetMultiPv () const
Gets number of principal variations to calculate.
bool GetPerPvCounters () const
Whether to use per-PV counters.
std::string GetScoreType () const
Gets score display type.
FillEmptyHistory GetHistoryFill () const
Gets history fill strategy.
float GetMovesLeftMaxEffect () const
Gets maximum moves-left effect on search.
float GetMovesLeftThreshold () const
Gets threshold for moves-left application.
float GetMovesLeftSlope () const
Gets moves-left slope factor.
float GetMovesLeftConstantFactor () const
Gets constant factor for moves-left calculation.
float GetMovesLeftScaledFactor () const
Gets scaled factor for moves-left calculation.
float GetMovesLeftQuadraticFactor () const
Gets quadratic factor for moves-left calculation.
int GetMaxConcurrentSearchers () const
Gets maximum concurrent searcher threads.
float GetDrawScore () const
Gets base draw score value.
ContemptMode GetContemptMode () const
Gets contempt mode setting.
float GetWDLRescaleRatio () const
Gets WDL rescale ratio.
float GetWDLRescaleDiff () const
Gets WDL rescale difference.
float GetWDLMaxS () const
Gets maximum WDL scaling factor.
float GetWDLEvalObjectivity () const
Gets WDL evaluation objectivity.
float GetMaxOutOfOrderEvalsFactor () const
Gets maximum out-of-order evaluations factor.
float GetNpsLimit () const
Gets nodes per second limit.
int GetTaskWorkersPerSearchWorker () const
Gets task workers per search worker.
int GetMinimumWorkSizeForProcessing () const
Gets minimum work size for processing.
int GetMinimumWorkSizeForPicking () const
Gets minimum work size for picking nodes.
int GetMinimumRemainingWorkSizeForPicking () const
Gets minimum remaining work for picking.
int GetMinimumWorkPerTaskForProcessing () const
Gets minimum work per task for processing.
int GetIdlingMinimumWork () const
Gets idling minimum work threshold.
int GetThreadIdlingThreshold () const
Gets thread idling threshold.
int GetMaxCollisionVisitsScalingStart () const
Gets collision visits scaling start.
int GetMaxCollisionVisitsScalingEnd () const
Gets collision visits scaling end.
float GetMaxCollisionVisitsScalingPower () const
Gets collision visits scaling power.
bool GetSearchSpinBackoff () const
Whether search spin backoff is enabled.
float GetGarbageCollectionDelay () const
Gets garbage collection delay.
Static Public Member Functions
static void Populate (OptionsParser *options)
Populates UCI options with search parameters.
Static Public Member Functions inherited from lczero::classic::BaseSearchParams
static void Populate (OptionsParser *options)
Populates UCI options with search parameters.
Static Public Attributes
static const OptionId kMaxPrefetchBatchId
Option ID for maximum prefetch batch size.
static const OptionId kSolidTreeThresholdId
Option ID for solid tree threshold.
Static Public Attributes inherited from lczero::classic::BaseSearchParams
static const OptionId kMiniBatchSizeId
static const OptionId kCpuctId
static const OptionId kCpuctAtRootId
static const OptionId kCpuctBaseId
static const OptionId kCpuctBaseAtRootId
static const OptionId kCpuctFactorId
static const OptionId kCpuctFactorAtRootId
static const OptionId kRootHasOwnCpuctParamsId
static const OptionId kTwoFoldDrawsId
static const OptionId kTemperatureId
static const OptionId kTempDecayMovesId
static const OptionId kTempDecayDelayMovesId
static const OptionId kTemperatureCutoffMoveId
static const OptionId kTemperatureEndgameId
static const OptionId kTemperatureWinpctCutoffId
static const OptionId kTemperatureVisitOffsetId
static const OptionId kNoiseEpsilonId
static const OptionId kNoiseAlphaId
static const OptionId kVerboseStatsId
static const OptionId kLogLiveStatsId
static const OptionId kFpuStrategyId
static const OptionId kFpuValueId
static const OptionId kFpuStrategyAtRootId
static const OptionId kFpuValueAtRootId
static const OptionId kCacheHistoryLengthId
static const OptionId kMaxCollisionEventsId
static const OptionId kMaxCollisionVisitsId
static const OptionId kOutOfOrderEvalId
static const OptionId kStickyEndgamesId
static const OptionId kSyzygyFastPlayId
static const OptionId kMultiPvId
static const OptionId kPerPvCountersId
static const OptionId kScoreTypeId
static const OptionId kMovesLeftMaxEffectId
static const OptionId kMovesLeftThresholdId
static const OptionId kMovesLeftConstantFactorId
static const OptionId kMovesLeftScaledFactorId
static const OptionId kMovesLeftQuadraticFactorId
static const OptionId kMovesLeftSlopeId
static const OptionId kMaxConcurrentSearchersId
static const OptionId kDrawScoreId
static const OptionId kContemptModeId
static const OptionId kContemptId
static const OptionId kContemptMaxValueId
static const OptionId kWDLCalibrationEloId
static const OptionId kWDLContemptAttenuationId
static const OptionId kWDLMaxSId
static const OptionId kWDLEvalObjectivityId
static const OptionId kWDLDrawRateTargetId
static const OptionId kWDLDrawRateReferenceId
static const OptionId kWDLBookExitBiasId
static const OptionId kMaxOutOfOrderEvalsFactorId
static const OptionId kNpsLimitId
static const OptionId kTaskWorkersPerSearchWorkerId
static const OptionId kMinimumWorkSizeForProcessingId
static const OptionId kMinimumWorkSizeForPickingId
static const OptionId kMinimumRemainingWorkSizeForPickingId
static const OptionId kMinimumWorkPerTaskForProcessingId
static const OptionId kIdlingMinimumWorkId
static const OptionId kThreadIdlingThresholdId
static const OptionId kMaxCollisionVisitsScalingStartId
static const OptionId kMaxCollisionVisitsScalingEndId
static const OptionId kMaxCollisionVisitsScalingPowerId
static const OptionId kUCIOpponentId
static const OptionId kUCIRatingAdvId
static const OptionId kSearchSpinBackoffId
static const OptionId kGarbageCollectionDelayId
Private Attributes
const int kSolidTreeThreshold
Cached solid tree threshold value.
Additional Inherited Members
Protected Attributes inherited from lczero::classic::BaseSearchParams
const OptionsDict & options_
Detailed Description
Extended search parameters with additional classic-search-specific options.
Inherits from BaseSearchParams and adds parameters specific to the classic MCTS implementation such as prefetch batch size and solid tree threshold.
Definition at line 491 of file params.h.
Constructor & Destructor Documentation
SearchParams() [1/2]
lczero::classic::SearchParams::SearchParams (const OptionsDict & options)
Constructs search parameters from an options dictionary.
Initializes SearchParams from the provided options dictionary.
Parameters
options The options dictionary containing parameter values.
Definition at line 746 of file params.cc.
SearchParams() [2/2]
lczero::classic::SearchParams::SearchParams (const SearchParams &) delete
Deleted copy constructor (parameters are not copyable).
Member Function Documentation
GetMaxPrefetchBatch()
int lczero::classic::SearchParams::GetMaxPrefetchBatch () const inline
Gets maximum batch size for prefetch operations.
Returns
Maximum prefetch batch size.
Definition at line 506 of file params.h.
References lczero::OptionsDict::Get(), kMaxPrefetchBatchId, and lczero::classic::BaseSearchParams::options_.
GetSolidTreeThreshold()
int lczero::classic::SearchParams::GetSolidTreeThreshold () const inline
Gets threshold for converting to solid tree representation.
Solid trees use array-based storage for better memory efficiency after the tree has stabilized.
Returns
Solid tree conversion threshold.
Definition at line 514 of file params.h.
References kSolidTreeThreshold.
Populate()
void lczero::classic::SearchParams::Populate (OptionsParser * options) static
Populates UCI options with search parameters.
Registers search definition options, including specialized ones, with the parser.
Parameters
options The options parser to populate.
Definition at line 650 of file params.cc.
References lczero::OptionsParser::Add(), DEFAULT_MAX_PREFETCH, kMaxPrefetchBatchId, kSolidTreeThresholdId, and lczero::classic::BaseSearchParams::Populate().
Referenced by lczero::SelfPlayTournament::PopulateOptions(), and lczero::Benchmark::Run().
Member Data Documentation
kMaxPrefetchBatchId
const OptionId lczero::classic::SearchParams::kMaxPrefetchBatchId static
Initial value:
{
    "max-prefetch", "MaxPrefetch",
    "When the engine cannot gather a large enough batch for immediate use, try "
    "to prefetch up to X positions which are likely to be useful soon, and put "
    "them into cache."}
Option ID for maximum prefetch batch size.
Definition at line 517 of file params.h.
Referenced by GetMaxPrefetchBatch(), and Populate().
kSolidTreeThreshold
const int lczero::classic::SearchParams::kSolidTreeThreshold private
Cached solid tree threshold value.
Definition at line 524 of file params.h.
Referenced by GetSolidTreeThreshold().
kSolidTreeThresholdId
const OptionId lczero::classic::SearchParams::kSolidTreeThresholdId static
Initial value:
{
    "solid-tree-threshold", "SolidTreeThreshold",
    "Only nodes with at least this number of visits will be considered for "
    "solidification for improved cache locality."}
Option ID for solid tree threshold.
Definition at line 520 of file params.h.
Referenced by Populate().
The documentation for this class was generated from the following files:
search/classic/params.h
search/classic/params.cc