Leela Chess Zero: lczero::PjrtHostToDeviceTransfer Class Reference
lczero::PjrtHostToDeviceTransfer Class Reference
Handles ongoing host-to-device transfer.
#include <pjrt.h>
Public Member Functions
PjrtHostToDeviceTransfer (const PJRT_Api *api, PJRT_Buffer *buffer, std::unique_ptr< PjrtEvent > event)
~PjrtHostToDeviceTransfer ()
void Await ()
Blocks until the transfer is complete.
std::unique_ptr< PjrtDeviceBuffer > AwaitAndReleaseBuffer ()
Waits for the transfer to complete and releases the ownership of the buffer.
Private Attributes
PJRT_Buffer * buffer_
std::unique_ptr< PjrtEvent > event_
Additional Inherited Members
Protected Member Functions inherited from lczero::PjrtCommon
PjrtCommon (const PJRT_Api *api)
virtual ~PjrtCommon ()=default
std::string GetErrorMessage (PJRT_Error *error) const
void DestroyErrorMessage (PJRT_Error *error) const
void CheckError (PJRT_Error *error) const
Protected Attributes inherited from lczero::PjrtCommon
const PJRT_Api * api_
Detailed Description
Handles ongoing host-to-device transfer.
After the transfer is complete, it's possible to fetch the device buffer.
Definition at line 214 of file pjrt.h.
Constructor & Destructor Documentation
PjrtHostToDeviceTransfer()
lczero::PjrtHostToDeviceTransfer::PjrtHostToDeviceTransfer (const PJRT_Api * api, PJRT_Buffer * buffer, std::unique_ptr< PjrtEvent > event)
Definition at line 297 of file pjrt.cc.
~PjrtHostToDeviceTransfer()
lczero::PjrtHostToDeviceTransfer::~PjrtHostToDeviceTransfer ()
Definition at line 315 of file pjrt.cc.
References lczero::PjrtCommon::api_, Await(), buffer_, and lczero::PjrtCommon::CheckError().
Member Function Documentation
Await()
void lczero::PjrtHostToDeviceTransfer::Await ()
Blocks until the transfer is complete.
Not really necessary as AwaitAndReleaseBuffer() waits anyway.
Definition at line 301 of file pjrt.cc.
References event_.
Referenced by AwaitAndReleaseBuffer(), and ~PjrtHostToDeviceTransfer().
AwaitAndReleaseBuffer()
std::unique_ptr< PjrtDeviceBuffer > lczero::PjrtHostToDeviceTransfer::AwaitAndReleaseBuffer ()
Waits for the transfer to complete and releases the ownership of the buffer.
Definition at line 304 of file pjrt.cc.
References lczero::PjrtCommon::api_, Await(), buffer_, and lczero::INVALID_ARGUMENT.
Member Data Documentation
buffer_
PJRT_Buffer* lczero::PjrtHostToDeviceTransfer::buffer_ private
Definition at line 227 of file pjrt.h.
Referenced by AwaitAndReleaseBuffer(), and ~PjrtHostToDeviceTransfer().
event_
std::unique_ptr<PjrtEvent> lczero::PjrtHostToDeviceTransfer::event_ private
Definition at line 228 of file pjrt.h.
Referenced by Await().
The documentation for this class was generated from the following files:
src/neural/backends/xla/pjrt.h
src/neural/backends/xla/pjrt.cc