Leela Chess Zero: lczero::onednn_backend::FCLayer Class Reference
lczero::onednn_backend::FCLayer Class Reference
#include <layers.h>
Public Member Functions
FCLayer (BaseLayer *ip, int C, int H, int W, ActivationFunction activation)
void LoadWeights (dnnl::memory &w1, dnnl::memory &b1, dnnl::engine &eng, dnnl::stream &stream)
void Eval (int N, dnnl::memory &output, dnnl::memory &input, dnnl::engine &eng, dnnl::stream &stream) override
Public Member Functions inherited from lczero::onednn_backend::BaseLayer
int GetC () const
int GetH () const
int GetW () const
BaseLayer (int c, int h, int w, BaseLayer *ip)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
void SetDataType (dnnl::memory::data_type type)
void SetConvolutionType (dnnl::algorithm type)
Private Attributes
ActivationFunction activation_
dnnl::memory filter_mem
dnnl::memory bias_mem
int last_batch_ = 0
dnnl::inner_product_forward fc_
dnnl::reorder in_reorder_
dnnl::memory scratchpad_mem
dnnl::memory::desc in_md
dnnl::memory::desc out_md
Additional Inherited Members
Protected Attributes inherited from lczero::onednn_backend::BaseLayer
BaseLayer * input_
int C
int H
int W
dnnl::memory::data_type data_type_
dnnl::algorithm convolution_type_
std::mutex lock_
Detailed Description
Definition at line 99 of file layers.h.
Constructor & Destructor Documentation
FCLayer()
lczero::onednn_backend::FCLayer::FCLayer (BaseLayer * ip, int C, int H, int W, ActivationFunction activation)
Definition at line 469 of file layers.cc.
Member Function Documentation
Eval()
void lczero::onednn_backend::FCLayer::Eval (int N, dnnl::memory & output, dnnl::memory & input, dnnl::engine & eng, dnnl::stream & stream) override virtual
Implements lczero::onednn_backend::BaseLayer.
Definition at line 489 of file layers.cc.
References activation_, lczero::ACTIVATION_MISH, lczero::ACTIVATION_RELU, lczero::ACTIVATION_TANH, bias_mem, lczero::onednn_backend::BaseLayer::C, lczero::onednn_backend::BaseLayer::data_type_, fc_, filter_mem, lczero::onednn_backend::BaseLayer::GetC(), lczero::onednn_backend::BaseLayer::GetH(), lczero::onednn_backend::BaseLayer::GetW(), lczero::onednn_backend::BaseLayer::H, in_md, in_reorder_, input, lczero::onednn_backend::BaseLayer::input_, last_batch_, lczero::onednn_backend::BaseLayer::lock_, out_md, output, scratchpad_mem, and lczero::onednn_backend::BaseLayer::W.
LoadWeights()
void lczero::onednn_backend::FCLayer::LoadWeights (dnnl::memory & w1, dnnl::memory & b1, dnnl::engine & eng, dnnl::stream & stream)
Definition at line 473 of file layers.cc.
References bias_mem, lczero::onednn_backend::BaseLayer::C, lczero::onednn_backend::BaseLayer::data_type_, filter_mem, lczero::onednn_backend::BaseLayer::GetC(), lczero::onednn_backend::BaseLayer::GetH(), lczero::onednn_backend::BaseLayer::GetW(), lczero::onednn_backend::BaseLayer::H, lczero::onednn_backend::BaseLayer::input_, and lczero::onednn_backend::BaseLayer::W.
Member Data Documentation
activation_
ActivationFunction lczero::onednn_backend::FCLayer::activation_ private
Definition at line 109 of file layers.h.
Referenced by Eval().
bias_mem
dnnl::memory lczero::onednn_backend::FCLayer::bias_mem private
Definition at line 112 of file layers.h.
Referenced by Eval(), and LoadWeights().
fc_
dnnl::inner_product_forward lczero::onednn_backend::FCLayer::fc_ private
Definition at line 116 of file layers.h.
Referenced by Eval().
filter_mem
dnnl::memory lczero::onednn_backend::FCLayer::filter_mem private
Definition at line 111 of file layers.h.
Referenced by Eval(), and LoadWeights().
in_md
dnnl::memory::desc lczero::onednn_backend::FCLayer::in_md private
Definition at line 120 of file layers.h.
Referenced by Eval().
in_reorder_
dnnl::reorder lczero::onednn_backend::FCLayer::in_reorder_ private
Definition at line 117 of file layers.h.
Referenced by Eval().
last_batch_
int lczero::onednn_backend::FCLayer::last_batch_ = 0 private
Definition at line 115 of file layers.h.
Referenced by Eval().
out_md
dnnl::memory::desc lczero::onednn_backend::FCLayer::out_md private
Definition at line 121 of file layers.h.
Referenced by Eval().
scratchpad_mem
dnnl::memory lczero::onednn_backend::FCLayer::scratchpad_mem private
Definition at line 118 of file layers.h.
Referenced by Eval().
The documentation for this class was generated from the following files:
src/neural/backends/onednn/layers.h
src/neural/backends/onednn/layers.cc