Leela Chess Zero: lczero::dag_classic::SearchWorker Class Reference
lczero::dag_classic::SearchWorker Class Reference
Single thread worker of the search engine.
#include <search.h>
Classes
struct NodeToProcess
struct PickTask
struct TaskWorkspace
Holds per task worker scratch data.
Public Member Functions
SearchWorker (Search *search, const SearchParams &params)
~SearchWorker ()
void RunBlocking ()
Runs iterations while needed (blocking).
void ExecuteOneIteration ()
Does one full iteration of MCTS search:
void InitializeIteration ()
Initialize internal structures.
void GatherMinibatch ()
Gather minibatch.
void CollectCollisions ()
2b. Copy collisions into shared_collisions_.
void RunNNComputation ()
Run NN computation.
void FetchMinibatchResults ()
Retrieve NN computations (and terminal values) into nodes.
void DoBackupUpdate ()
Propagate the new nodes' information to all their parents in the tree.
void UpdateCounters ()
Update the Search's status and progress information.
Static Public Attributes
static constexpr int kTaskCountDigits = std::numeric_limits<int>::digits + 1
static constexpr int kTasksTakenShift = kTaskCountDigits / 2
static constexpr int kTasksTakenOne = 1 << kTasksTakenShift
static constexpr int kTaskCountSuspend = kTasksTakenOne - 1
Private Member Functions
NodeToProcess PickNodeToExtend (int collision_limit)
bool MaybeAdjustForTerminalOrTransposition (Node *n, const std::shared_ptr< LowNode > &nl, float &v, float &d, float &m, uint32_t &n_to_fix, float &v_delta, float &d_delta, float &m_delta, bool &update_parent_bounds) const
Adjust parameters for updating node
and its parent low node.
void DoBackupUpdateSingleNode (const NodeToProcess &node_to_process)
Performs backup update for a single node chain.
bool MaybeSetBounds (Node *p, float m, uint32_t *n_to_fix, float *v_delta, float *d_delta, float *m_delta) const
Returns whether a node's bounds were set based on its children.
void PickNodesToExtend (int collision_limit)
Selects nodes to extend from the current tree.
void PickNodesToExtendTask (const BackupPath &path, int collision_limit, PositionHistory &history, std::vector< NodeToProcess > *receiver, TaskWorkspace *workspace)
void CancelCollisions ()
std::pair< int, int > GetRepetitions (int depth, const Position &position)
Check if the situation is a safe two-fold or a draw by repetition.
bool ShouldStopPickingHere (Node *node, bool is_root_node, int repetitions)
Check if there is a reason to stop picking and pick @node.
void ProcessPickedTask (int batch_start, int batch_end)
Processes a range of picked nodes for extension.
void ExtendNode (NodeToProcess &picked_node)
Extends a leaf node by generating moves and checking for terminal states.
void FetchSingleNodeResult (NodeToProcess *node_to_process)
Updates a single node with NN results and applies noise/rescaling.
std::tuple< PickTask *, int, int > PickTaskToProcess ()
void ProcessTask (PickTask *task, int id, std::vector< NodeToProcess > *receiver, TaskWorkspace *workspace)
void RunTasks (int tid)
void ResetTasks ()
Resets the task counters and queues.
int WaitForTasks ()
Returns how many tasks there were.
Private Attributes
Search *const search_
std::vector< NodeToProcess > minibatch_
List of nodes to process.
std::unique_ptr< BackendComputation > computation_
int task_workers_
int target_minibatch_size_
int max_out_of_order_
PositionHistory history_
int number_out_of_order_ = 0
const SearchParams & params_
std::unique_ptr< Node > precached_node_
const bool moves_left_support_
classic::IterationStats iteration_stats_
classic::StoppersHints latest_time_manager_hints_
Mutex picking_tasks_mutex_
std::vector< PickTask > picking_tasks_
std::atomic< int > task_count_ = kTaskCountSuspend
std::atomic< int > completed_tasks_ = 0
std::condition_variable task_added_
std::vector< std::thread > task_threads_
std::vector< TaskWorkspace > task_workspaces_
TaskWorkspace main_workspace_
bool exiting_ = false
Detailed Description
Single thread worker of the search engine.
That used to be just a function Search::Worker(), but to parallelize it within one thread, have to split into stages.
Definition at line 226 of file search.h.
Constructor & Destructor Documentation
SearchWorker()
lczero::dag_classic::SearchWorker::SearchWorker (Search * search, const SearchParams & params) inline
Definition at line 234 of file search.h.
References lczero::dag_classic::Search::backend_attributes_, lczero::classic::BaseSearchParams::GetMaxOutOfOrderEvalsFactor(), lczero::classic::BaseSearchParams::GetMiniBatchSize(), lczero::classic::BaseSearchParams::GetTaskWorkersPerSearchWorker(), LOGFILE, max_out_of_order_, params_, lczero::BackendAttributes::recommended_batch_size, lczero::BackendAttributes::runs_on_cpu, RunTasks(), search_, target_minibatch_size_, task_threads_, task_workers_, task_workspaces_, and lczero::dag_classic::Search::thread_count_.
~SearchWorker()
lczero::dag_classic::SearchWorker::~SearchWorker ()
Definition at line 1149 of file search.cc.
References LOGFILE.
Member Function Documentation
CancelCollisions()
void lczero::dag_classic::SearchWorker::CancelCollisions () private
Definition at line 1129 of file search.cc.
Referenced by GatherMinibatch().
CollectCollisions()
void lczero::dag_classic::SearchWorker::CollectCollisions ()
2b. Copy collisions into shared_collisions_.
DoBackupUpdate()
void lczero::dag_classic::SearchWorker::DoBackupUpdate ()
Propagate the new nodes' information to all their parents in the tree.
Propagates values from new nodes up the tree.
Definition at line 2170 of file search.cc.
References LCTRACE_FUNCTION_SCOPE, and search_.
DoBackupUpdateSingleNode()
void lczero::dag_classic::SearchWorker::DoBackupUpdateSingleNode (const NodeToProcess & node_to_process) private
Performs backup update for a single node chain.
Definition at line 2244 of file search.cc.
References d, m, p, params_, and search_.
ExecuteOneIteration()
void lczero::dag_classic::SearchWorker::ExecuteOneIteration ()
Does one full iteration of MCTS search:
Initialize internal structures.
Gather minibatch. 3.
Run NN computation.
Retrieve NN computations (and terminal values) into nodes.
Propagate the new nodes' information to all their parents in the tree.
Update the Search's status and progress information.
Definition at line 1243 of file search.cc.
References params_, and search_.
Referenced by RunBlocking().
ExtendNode()
void lczero::dag_classic::SearchWorker::ExtendNode (NodeToProcess & picked_node) private
Extends a leaf node by generating moves and checking for terminal states.
Definition at line 2016 of file search.cc.
References lczero::BLACK_WON, computation_, lczero::DRAW, lczero::dag_classic::SearchWorker::NodeToProcess::eval, lczero::FAIL, lczero::BackendComputation::FETCHED_IMMEDIATELY, lczero::ChessBoard::GenerateLegalMoves(), lczero::Position::GetBoard(), lczero::PositionHistory::GetPositions(), lczero::Position::GetRule50Ply(), lczero::dag_classic::SearchWorker::NodeToProcess::hash, lczero::PositionHistory::HashLast(), lczero::dag_classic::SearchWorker::NodeToProcess::history, lczero::dag_classic::SearchWorker::NodeToProcess::is_cache_hit, lczero::dag_classic::SearchWorker::NodeToProcess::is_tt_hit, lczero::PositionHistory::Last(), legal_moves, m, lczero::dag_classic::Node::MakeTerminal(), lczero::SyzygyTablebase::max_cardinality(), lczero::dag_classic::SearchWorker::NodeToProcess::nn_queried, lczero::dag_classic::SearchWorker::NodeToProcess::node, params_, lczero::dag_classic::SearchWorker::NodeToProcess::path, lczero::EvalPosition::pos, lczero::SyzygyTablebase::probe_wdl(), lczero::dag_classic::SearchWorker::NodeToProcess::repetitions, search_, lczero::SearchBase::syzygy_tb_, lczero::dag_classic::SearchWorker::NodeToProcess::tt_low_node, lczero::WDL_LOSS, lczero::WDL_WIN, and lczero::WHITE_WON.
FetchMinibatchResults()
void lczero::dag_classic::SearchWorker::FetchMinibatchResults ()
Retrieve NN computations (and terminal values) into nodes.
Retrieves results from NN computation and updates nodes.
Definition at line 2125 of file search.cc.
References LCTRACE_FUNCTION_SCOPE.
FetchSingleNodeResult()
void lczero::dag_classic::SearchWorker::FetchSingleNodeResult (NodeToProcess * node_to_process) private
Updates a single node with NN results and applies noise/rescaling.
Definition at line 2134 of file search.cc.
References lczero::dag_classic::SearchWorker::NodeToProcess::eval, lczero::dag_classic::SearchWorker::NodeToProcess::history, lczero::PositionHistory::IsBlackToMove(), lczero::dag_classic::SearchWorker::NodeToProcess::nn_queried, lczero::dag_classic::SearchWorker::NodeToProcess::node, params_, search_, and lczero::dag_classic::SearchWorker::NodeToProcess::tt_low_node.
GatherMinibatch()
void lczero::dag_classic::SearchWorker::GatherMinibatch ()
Gather minibatch.
Definition at line 1359 of file search.cc.
References CancelCollisions(), computation_, LCTRACE_FUNCTION_SCOPE, params_, and search_.
GetRepetitions()
std::pair< int, int > lczero::dag_classic::SearchWorker::GetRepetitions (int depth, const Position & position) private
Check if the situation is a safe two-fold or a draw by repetition.
Returns
Pair of (safe repetitions, moves_left).
Definition at line 1605 of file search.cc.
References lczero::Position::GetPliesSincePrevRepetition(), lczero::Position::GetRepetitions(), and params_.
InitializeIteration()
void lczero::dag_classic::SearchWorker::InitializeIteration ()
Initialize internal structures.
Definition at line 1324 of file search.cc.
References lczero::SearchBase::backend_, computation_, lczero::Backend::CreateComputation(), LCTRACE_FUNCTION_SCOPE, and search_.
MaybeAdjustForTerminalOrTransposition()
bool lczero::dag_classic::SearchWorker::MaybeAdjustForTerminalOrTransposition (Node * n, const std::shared_ptr< LowNode > & nl, float & v, float & d, float & m, uint32_t & n_to_fix, float & v_delta, float & d_delta, float & m_delta, bool & update_parent_bounds) const private
Adjust parameters for updating node
and its parent low node.
Adjusts node values if it is terminal or a transposition.
Adjusts if node is terminal or its child low node is a transposition. Also update bounds and terminal status of node
using information from its child low node.
Returns
true if adjustment happened.
Definition at line 2187 of file search.cc.
References lczero::BLACK_WON, d, lczero::DRAW, lczero::dag_classic::Node::GetD(), lczero::dag_classic::Node::GetM(), lczero::dag_classic::Node::GetN(), lczero::dag_classic::Node::GetWL(), lczero::dag_classic::Node::IsTerminal(), m, lczero::dag_classic::Node::MakeTerminal(), params_, lczero::dag_classic::Node::SetBounds(), and lczero::WHITE_WON.
MaybeSetBounds()
bool lczero::dag_classic::SearchWorker::MaybeSetBounds (Node * p, float m, uint32_t * n_to_fix, float * v_delta, float * d_delta, float * m_delta) const private
Returns whether a node's bounds were set based on its children.
Updates the bounds of a node based on its children.
Definition at line 2394 of file search.cc.
References lczero::BLACK_WON, m, p, and lczero::WHITE_WON.
PickNodesToExtend()
void lczero::dag_classic::SearchWorker::PickNodesToExtend (int collision_limit) private
Selects nodes to extend from the current tree.
Definition at line 1577 of file search.cc.
References search_.
PickNodesToExtendTask()
void lczero::dag_classic::SearchWorker::PickNodesToExtendTask (const BackupPath & path, int collision_limit, PositionHistory & history, std::vector< NodeToProcess > * receiver, TaskWorkspace * workspace) private
Definition at line 1669 of file search.cc.
References lczero::dag_classic::EdgeAndNode::GetMove(), lczero::dag_classic::Edge_Iterator< is_const >::GetOrSpawnNode(), idx, lczero::dag_classic::Node::IncrementNInFlight(), LCTRACE_FUNCTION_SCOPE, MAX_TASKS, params_, q, lczero::dag_classic::EdgeAndNode::Reset(), search_, and lczero::dag_classic::Node::TryStartScoreUpdate().
PickNodeToExtend()
NodeToProcess lczero::dag_classic::SearchWorker::PickNodeToExtend (int collision_limit) private
PickTaskToProcess()
std::tuple< SearchWorker::PickTask *, int, int > lczero::dag_classic::SearchWorker::PickTaskToProcess () private
Definition at line 1166 of file search.cc.
ProcessPickedTask()
void lczero::dag_classic::SearchWorker::ProcessPickedTask (int batch_start, int batch_end) private
Processes a range of picked nodes for extension.
Definition at line 1520 of file search.cc.
References params_.
ProcessTask()
void lczero::dag_classic::SearchWorker::ProcessTask (PickTask * task, int id, std::vector< NodeToProcess > * receiver, TaskWorkspace * workspace) private
Definition at line 1185 of file search.cc.
References lczero::dag_classic::SearchWorker::PickTask::collision_limit, lczero::dag_classic::SearchWorker::PickTask::end_idx, lczero::dag_classic::SearchWorker::PickTask::history, lczero::dag_classic::SearchWorker::PickTask::start_idx, lczero::dag_classic::SearchWorker::PickTask::start_path, and lczero::dag_classic::SearchWorker::PickTask::task_type.
ResetTasks()
void lczero::dag_classic::SearchWorker::ResetTasks () private
Resets the task counters and queues.
Definition at line 1541 of file search.cc.
References MAX_TASKS.
RunBlocking()
void lczero::dag_classic::SearchWorker::RunBlocking () inline
Runs iterations while needed (blocking).
Definition at line 271 of file search.h.
References ExecuteOneIteration(), lczero::dag_classic::Search::IsSearchActive(), LOGFILE, and search_.
Referenced by lczero::dag_classic::Search::StartThreads().
RunNNComputation()
void lczero::dag_classic::SearchWorker::RunNNComputation ()
Run NN computation.
Runs the neural network computation for the current batch.
Definition at line 2118 of file search.cc.
References computation_.
RunTasks()
void lczero::dag_classic::SearchWorker::RunTasks (int tid) private
Definition at line 1203 of file search.cc.
References lczero::dag_classic::SearchWorker::PickTask::results, and lczero::SpinloopPause().
Referenced by SearchWorker().
ShouldStopPickingHere()
bool lczero::dag_classic::SearchWorker::ShouldStopPickingHere (Node * node, bool is_root_node, int repetitions) private
Check if there is a reason to stop picking and pick @node.
Definition at line 1623 of file search.cc.
References lczero::dag_classic::Node::GetBounds(), lczero::dag_classic::Node::GetD(), lczero::dag_classic::Node::GetLowNode(), lczero::dag_classic::Node::GetM(), lczero::dag_classic::Node::GetN(), lczero::dag_classic::Node::GetWL(), lczero::dag_classic::Node::IsTerminal(), and search_.
UpdateCounters()
void lczero::dag_classic::SearchWorker::UpdateCounters ()
Update the Search's status and progress information.
Updates search statistics and handles output.
Definition at line 2467 of file search.cc.
References LCTRACE_FUNCTION_SCOPE, and search_.
WaitForTasks()
int lczero::dag_classic::SearchWorker::WaitForTasks () private
Returns how many tasks there were.
Waits for all scheduled tasks to complete.
Definition at line 1552 of file search.cc.
References lczero::SpinloopPause().
Member Data Documentation
completed_tasks_
std::atomic<int> lczero::dag_classic::SearchWorker::completed_tasks_ = 0 private
Definition at line 519 of file search.h.
computation_
std::unique_ptr<BackendComputation> lczero::dag_classic::SearchWorker::computation_ private
Definition at line 500 of file search.h.
exiting_
bool lczero::dag_classic::SearchWorker::exiting_ = false private
Definition at line 524 of file search.h.
history_
PositionHistory lczero::dag_classic::SearchWorker::history_ private
Definition at line 505 of file search.h.
iteration_stats_
classic::IterationStats lczero::dag_classic::SearchWorker::iteration_stats_ private
Definition at line 510 of file search.h.
kTaskCountDigits
constexpr int lczero::dag_classic::SearchWorker::kTaskCountDigits = std::numeric_limits<int>::digits + 1 static constexpr
Definition at line 228 of file search.h.
kTaskCountSuspend
constexpr int lczero::dag_classic::SearchWorker::kTaskCountSuspend = kTasksTakenOne - 1 static constexpr
Definition at line 232 of file search.h.
kTasksTakenOne
constexpr int lczero::dag_classic::SearchWorker::kTasksTakenOne = 1 << kTasksTakenShift static constexpr
Definition at line 230 of file search.h.
kTasksTakenShift
constexpr int lczero::dag_classic::SearchWorker::kTasksTakenShift = kTaskCountDigits / 2 static constexpr
Definition at line 229 of file search.h.
latest_time_manager_hints_
classic::StoppersHints lczero::dag_classic::SearchWorker::latest_time_manager_hints_ private
Definition at line 511 of file search.h.
main_workspace_
TaskWorkspace lczero::dag_classic::SearchWorker::main_workspace_ private
Definition at line 523 of file search.h.
max_out_of_order_
int lczero::dag_classic::SearchWorker::max_out_of_order_ private
Definition at line 503 of file search.h.
Referenced by SearchWorker().
minibatch_
std::vector<NodeToProcess> lczero::dag_classic::SearchWorker::minibatch_ private
List of nodes to process.
Definition at line 499 of file search.h.
moves_left_support_
const bool lczero::dag_classic::SearchWorker::moves_left_support_ private
Definition at line 509 of file search.h.
number_out_of_order_
int lczero::dag_classic::SearchWorker::number_out_of_order_ = 0 private
Definition at line 506 of file search.h.
params_
const SearchParams& lczero::dag_classic::SearchWorker::params_ private
Definition at line 507 of file search.h.
Referenced by SearchWorker().
picking_tasks_
std::vector<PickTask> lczero::dag_classic::SearchWorker::picking_tasks_ private
Definition at line 516 of file search.h.
picking_tasks_mutex_
Mutex lczero::dag_classic::SearchWorker::picking_tasks_mutex_ private
Definition at line 515 of file search.h.
precached_node_
std::unique_ptr<Node> lczero::dag_classic::SearchWorker::precached_node_ private
Definition at line 508 of file search.h.
search_
Search* const lczero::dag_classic::SearchWorker::search_ private
Definition at line 497 of file search.h.
Referenced by RunBlocking(), and SearchWorker().
target_minibatch_size_
int lczero::dag_classic::SearchWorker::target_minibatch_size_ private
Definition at line 502 of file search.h.
Referenced by SearchWorker().
task_added_
std::condition_variable lczero::dag_classic::SearchWorker::task_added_ private
Definition at line 520 of file search.h.
task_count_
std::atomic<int> lczero::dag_classic::SearchWorker::task_count_ = kTaskCountSuspend private
Definition at line 518 of file search.h.
task_threads_
std::vector<std::thread> lczero::dag_classic::SearchWorker::task_threads_ private
Definition at line 521 of file search.h.
Referenced by SearchWorker().
task_workers_
int lczero::dag_classic::SearchWorker::task_workers_ private
Definition at line 501 of file search.h.
Referenced by SearchWorker().
task_workspaces_
std::vector<TaskWorkspace> lczero::dag_classic::SearchWorker::task_workspaces_ private
Definition at line 522 of file search.h.
Referenced by SearchWorker().
The documentation for this class was generated from the following files:
src/search/dag_classic/search.h
src/search/dag_classic/search.cc