Leela Chess Zero: lczero::XlaMutableTensor Class Reference
lczero::XlaMutableTensor Class Reference
#include <xla_tensor.h>
Public Member Functions
XlaMutableTensor (pblczero::XlaShapeProto::Type type, const std::vector< int64_t > &shape, size_t capacity=0)
const std::vector< int64_t > & shape () const override
const void * data () const override
void * mutable_data ()
size_t size () const override
size_t capacity () const override
pblczero::XlaShapeProto::Type type () const override
void Reshape (const std::vector< int64_t > &new_shape)
void Cast (pblczero::XlaShapeProto::Type new_type)
Public Member Functions inherited from lczero::XlaTensor
virtual ~XlaTensor ()=default
std::string DebugString ()
Static Public Member Functions
static size_t GetBufferSize (pblczero::XlaShapeProto::Type type, const std::vector< int64_t > &shape)
Private Attributes
std::vector< int64_t > shape_
pblczero::XlaShapeProto::Type type_
size_t size_
size_t capacity_
std::unique_ptr< char[]> data_
Detailed Description
Definition at line 103 of file xla_tensor.h.
Constructor & Destructor Documentation
XlaMutableTensor()
lczero::XlaMutableTensor::XlaMutableTensor (pblczero::XlaShapeProto::Type type, const std::vector< int64_t > & shape, size_t capacity = 0) inline
Definition at line 105 of file xla_tensor.h.
Member Function Documentation
capacity()
size_t lczero::XlaMutableTensor::capacity () const inline override virtual
Implements lczero::XlaTensor.
Definition at line 120 of file xla_tensor.h.
References capacity_.
Cast()
void lczero::XlaMutableTensor::Cast (pblczero::XlaShapeProto::Type new_type)
Definition at line 95 of file xla_tensor.cc.
References lczero::BF16toFP32(), capacity_, data_, lczero::FP16toFP32(), lczero::FP32toBF16(), lczero::FP32toFP16(), lczero::FP32toFP8E5M2_Saturate(), lczero::FP8E5M2toFP32(), GetBufferSize(), lczero::GetXlaTypeSize(), result, shape_, size_, and type_.
data()
const void * lczero::XlaMutableTensor::data () const inline override virtual
Implements lczero::XlaTensor.
Definition at line 116 of file xla_tensor.h.
References data_.
GetBufferSize()
static size_t lczero::XlaMutableTensor::GetBufferSize (pblczero::XlaShapeProto::Type type, const std::vector< int64_t > & shape) inline static
Definition at line 125 of file xla_tensor.h.
References lczero::GetXlaTypeSize(), shape(), and type().
Referenced by Cast(), and Reshape().
mutable_data()
void * lczero::XlaMutableTensor::mutable_data () inline
Definition at line 118 of file xla_tensor.h.
References data_.
Reshape()
void lczero::XlaMutableTensor::Reshape (const std::vector< int64_t > & new_shape)
Definition at line 75 of file xla_tensor.cc.
References capacity_, GetBufferSize(), shape_, size_, and type_.
shape()
const std::vector< int64_t > & lczero::XlaMutableTensor::shape () const inline override virtual
Implements lczero::XlaTensor.
Definition at line 115 of file xla_tensor.h.
References shape_.
Referenced by GetBufferSize().
size()
size_t lczero::XlaMutableTensor::size () const inline override virtual
Implements lczero::XlaTensor.
Definition at line 119 of file xla_tensor.h.
References size_.
type()
pblczero::XlaShapeProto::Type lczero::XlaMutableTensor::type () const inline override virtual
Implements lczero::XlaTensor.
Definition at line 121 of file xla_tensor.h.
References type_.
Referenced by GetBufferSize().
Member Data Documentation
capacity_
size_t lczero::XlaMutableTensor::capacity_ private
Definition at line 135 of file xla_tensor.h.
Referenced by capacity(), Cast(), and Reshape().
data_
std::unique_ptr<char[]> lczero::XlaMutableTensor::data_ private
Definition at line 136 of file xla_tensor.h.
Referenced by Cast(), data(), and mutable_data().
shape_
std::vector<int64_t> lczero::XlaMutableTensor::shape_ private
Definition at line 132 of file xla_tensor.h.
Referenced by Cast(), Reshape(), and shape().
size_
size_t lczero::XlaMutableTensor::size_ private
Definition at line 134 of file xla_tensor.h.
Referenced by Cast(), Reshape(), and size().
type_
pblczero::XlaShapeProto::Type lczero::XlaMutableTensor::type_ private
Definition at line 133 of file xla_tensor.h.
Referenced by Cast(), Reshape(), and type().
The documentation for this class was generated from the following files:
src/neural/xla/xla_tensor.h
src/neural/xla/xla_tensor.cc