Leela Chess Zero: lczero::dx_backend::DxContext Class Reference
lczero::dx_backend::DxContext Class Reference
#include <network_dx.h>
Public Member Functions
DxContext (const OptionsDict &options)
~DxContext ()
ID3D12Device5 * getDevice ()
ID3D12GraphicsCommandList4 * getCommandList ()
ShaderWrapper * getShaderWrapper ()
void CreateAlloc (size_t size, D3D12_HEAP_TYPE type, DXAlloc &alloc, bool fp16)
void UavBarrier (ID3D12GraphicsCommandList4 *cl=nullptr)
uint64_t FlushCL (ID3D12GraphicsCommandList4 *cl=nullptr)
void WaitForGpu (uint64_t fence_val=0)
void ResetCL (ID3D12GraphicsCommandList4 *cl=nullptr, ID3D12CommandAllocator *ca=nullptr, bool reset=true)
void FlushAndWait ()
void ScheduleUpload (DXAlloc alloc, const void *data, size_t size)
void DumpFp32 (float *buf, int elements)
void CopyTensor (DXAlloc dst, DXAlloc src, int bytes)
void DumpTensor (const char *message, DXAlloc alloc, int size, bool fp16=true, bool allnewline=false)
void DumpCpuTensor (void *data, int size, bool fp16=true, bool allnewline=false)
Private Attributes
ID3D12Device5 * device_
ID3D12CommandQueue * command_queue_
ID3D12GraphicsCommandList4 * command_list_
ID3D12CommandAllocator * command_allocator_
ID3D12DescriptorHeap * desc_heap_
ID3D12Fence * fence_
uint64_t fence_val_
ShaderWrapper shader_wrapper_
std::atomic< unsigned int > next_slot_in_desc_heap_
DXAlloc upload_scratch_mem_
DXAlloc readback_scratch_mem_
int gpu_id_
Static Private Attributes
static constexpr int kNumDescHeapSlots = 65536
static constexpr size_t kUploadDownloadScratchSize = 256 * 1024 * 1024
Detailed Description
Definition at line 148 of file network_dx.h.
Constructor & Destructor Documentation
DxContext()
lczero::dx_backend::DxContext::DxContext (const OptionsDict & options)
Definition at line 166 of file network_dx.cc.
References command_allocator_, command_list_, command_queue_, CreateAlloc(), desc_heap_, device_, fence_, fence_val_, lczero::OptionsDict::GetOrDefault(), gpu_id_, lczero::dx_backend::ShaderWrapper::Init(), kNumDescHeapSlots, kUploadDownloadScratchSize, next_slot_in_desc_heap_, readback_scratch_mem_, ReportDxErrors, shader_wrapper_, and upload_scratch_mem_.
~DxContext()
lczero::dx_backend::DxContext::~DxContext ()
Definition at line 220 of file network_dx.cc.
References command_allocator_, command_list_, command_queue_, desc_heap_, lczero::dx_backend::ShaderWrapper::Destroy(), device_, fence_, FlushAndWait(), readback_scratch_mem_, lczero::dx_backend::DXAlloc::resource, shader_wrapper_, and upload_scratch_mem_.
Member Function Documentation
CopyTensor()
void lczero::dx_backend::DxContext::CopyTensor (DXAlloc dst, DXAlloc src, int bytes)
Definition at line 96 of file network_dx.cc.
References command_list_, lczero::dx_backend::DXAlloc::offset, and lczero::dx_backend::DXAlloc::resource.
CreateAlloc()
void lczero::dx_backend::DxContext::CreateAlloc (size_t size, D3D12_HEAP_TYPE type, DXAlloc & alloc, bool fp16)
Definition at line 236 of file network_dx.cc.
References lczero::dx_backend::DXAlloc::desc_handle_scalar, lczero::dx_backend::DXAlloc::desc_handle_vector, desc_heap_, device_, lczero::dx_backend::DivUp(), factor, lczero::dx_backend::DXAlloc::gpu_va, next_slot_in_desc_heap_, lczero::dx_backend::DXAlloc::offset, ReportDxErrors, lczero::dx_backend::DXAlloc::resource, and type.
Referenced by lczero::dx_backend::ConvLayer::ConvLayer(), lczero::dx_backend::ConvMetaCommand::ConvMetaCommand(), DxContext(), lczero::dx_backend::DxNetwork::DxNetwork(), lczero::dx_backend::FCLayer::FCLayer(), lczero::dx_backend::GemmMetaCommand::GemmMetaCommand(), lczero::dx_backend::InputsOutputsDx::InputsOutputsDx(), and lczero::dx_backend::PolicyMapLayer::PolicyMapLayer().
DumpCpuTensor()
void lczero::dx_backend::DxContext::DumpCpuTensor (void * data, int size, bool fp16 = true, bool allnewline = false)
Definition at line 123 of file network_dx.cc.
References data, and lczero::FP16toFP32().
DumpFp32()
void lczero::dx_backend::DxContext::DumpFp32 (float * buf, int elements)
Definition at line 87 of file network_dx.cc.
DumpTensor()
void lczero::dx_backend::DxContext::DumpTensor (const char * message, DXAlloc alloc, int size, bool fp16 = true, bool allnewline = false)
Definition at line 163 of file network_dx.cc.
Referenced by lczero::dx_backend::DxNetwork::Eval().
FlushAndWait()
void lczero::dx_backend::DxContext::FlushAndWait ()
Definition at line 75 of file network_dx.cc.
References FlushCL(), ResetCL(), and WaitForGpu().
Referenced by lczero::dx_backend::DxNetwork::DxNetwork(), lczero::dx_backend::DxNetwork::Eval(), ScheduleUpload(), ~DxContext(), and lczero::dx_backend::DxNetwork::~DxNetwork().
FlushCL()
uint64_t lczero::dx_backend::DxContext::FlushCL (ID3D12GraphicsCommandList4 * cl = nullptr)
Definition at line 46 of file network_dx.cc.
References command_list_, command_queue_, fence_, and fence_val_.
Referenced by lczero::dx_backend::DxNetwork::Eval(), and FlushAndWait().
getCommandList()
ID3D12GraphicsCommandList4 * lczero::dx_backend::DxContext::getCommandList () inline
Definition at line 177 of file network_dx.h.
References command_list_.
Referenced by lczero::dx_backend::ConvMetaCommand::ConvMetaCommand(), lczero::dx_backend::DxNetwork::Eval(), and lczero::dx_backend::GemmMetaCommand::GemmMetaCommand().
getDevice()
ID3D12Device5 * lczero::dx_backend::DxContext::getDevice () inline
Definition at line 176 of file network_dx.h.
References device_.
Referenced by lczero::dx_backend::ConvMetaCommand::ConvMetaCommand(), lczero::dx_backend::GemmMetaCommand::GemmMetaCommand(), and lczero::dx_backend::InputsOutputsDx::InputsOutputsDx().
getShaderWrapper()
ShaderWrapper * lczero::dx_backend::DxContext::getShaderWrapper () inline
Definition at line 178 of file network_dx.h.
References shader_wrapper_.
Referenced by lczero::dx_backend::ConvLayer::ConvLayer(), lczero::dx_backend::DxNetwork::Eval(), lczero::dx_backend::PolicyMapLayer::Eval(), and lczero::dx_backend::FCLayer::FCLayer().
ResetCL()
void lczero::dx_backend::DxContext::ResetCL (ID3D12GraphicsCommandList4 * cl = nullptr, ID3D12CommandAllocator * ca = nullptr, bool reset = true)
Definition at line 64 of file network_dx.cc.
References command_allocator_, command_list_, and desc_heap_.
Referenced by lczero::dx_backend::DxNetwork::Eval(), and FlushAndWait().
ScheduleUpload()
void lczero::dx_backend::DxContext::ScheduleUpload (DXAlloc alloc, const void * data, size_t size)
Definition at line 340 of file network_dx.cc.
References command_list_, data, FlushAndWait(), kUploadDownloadScratchSize, lczero::dx_backend::DXAlloc::offset, lczero::dx_backend::DXAlloc::resource, and upload_scratch_mem_.
Referenced by lczero::dx_backend::ConvLayer::LoadSEWeights(), lczero::dx_backend::PolicyMapLayer::LoadWeights(), lczero::dx_backend::FCLayer::LoadWeights(), and lczero::dx_backend::ConvLayer::LoadWeights().
UavBarrier()
void lczero::dx_backend::DxContext::UavBarrier (ID3D12GraphicsCommandList4 * cl = nullptr)
Definition at line 81 of file network_dx.cc.
References command_list_.
Referenced by lczero::dx_backend::DxNetwork::Eval(), lczero::dx_backend::ConvLayer::Eval(), and lczero::dx_backend::FCLayer::Eval().
WaitForGpu()
void lczero::dx_backend::DxContext::WaitForGpu (uint64_t fence_val = 0)
Definition at line 54 of file network_dx.cc.
References fence_, fence_val_, lczero::dx_backend::DXAlloc::offset, and upload_scratch_mem_.
Referenced by lczero::dx_backend::DxNetwork::Eval(), and FlushAndWait().
Member Data Documentation
command_allocator_
ID3D12CommandAllocator* lczero::dx_backend::DxContext::command_allocator_ private
Definition at line 156 of file network_dx.h.
Referenced by DxContext(), ResetCL(), and ~DxContext().
command_list_
ID3D12GraphicsCommandList4* lczero::dx_backend::DxContext::command_list_ private
Definition at line 155 of file network_dx.h.
Referenced by CopyTensor(), DxContext(), FlushCL(), getCommandList(), ResetCL(), ScheduleUpload(), UavBarrier(), and ~DxContext().
command_queue_
ID3D12CommandQueue* lczero::dx_backend::DxContext::command_queue_ private
Definition at line 154 of file network_dx.h.
Referenced by DxContext(), FlushCL(), and ~DxContext().
desc_heap_
ID3D12DescriptorHeap* lczero::dx_backend::DxContext::desc_heap_ private
Definition at line 157 of file network_dx.h.
Referenced by CreateAlloc(), DxContext(), ResetCL(), and ~DxContext().
device_
ID3D12Device5* lczero::dx_backend::DxContext::device_ private
Definition at line 153 of file network_dx.h.
Referenced by CreateAlloc(), DxContext(), getDevice(), and ~DxContext().
fence_
ID3D12Fence* lczero::dx_backend::DxContext::fence_ private
Definition at line 158 of file network_dx.h.
Referenced by DxContext(), FlushCL(), WaitForGpu(), and ~DxContext().
fence_val_
uint64_t lczero::dx_backend::DxContext::fence_val_ private
Definition at line 159 of file network_dx.h.
Referenced by DxContext(), FlushCL(), and WaitForGpu().
gpu_id_
int lczero::dx_backend::DxContext::gpu_id_ private
Definition at line 170 of file network_dx.h.
Referenced by DxContext().
kNumDescHeapSlots
constexpr int lczero::dx_backend::DxContext::kNumDescHeapSlots = 65536 static constexpr private
Definition at line 151 of file network_dx.h.
Referenced by DxContext().
kUploadDownloadScratchSize
constexpr size_t lczero::dx_backend::DxContext::kUploadDownloadScratchSize = 256 * 1024 * 1024 static constexpr private
Definition at line 166 of file network_dx.h.
Referenced by DxContext(), and ScheduleUpload().
next_slot_in_desc_heap_
std::atomic<unsigned int> lczero::dx_backend::DxContext::next_slot_in_desc_heap_ private
Definition at line 162 of file network_dx.h.
Referenced by CreateAlloc(), and DxContext().
readback_scratch_mem_
DXAlloc lczero::dx_backend::DxContext::readback_scratch_mem_ private
Definition at line 168 of file network_dx.h.
Referenced by DxContext(), and ~DxContext().
shader_wrapper_
ShaderWrapper lczero::dx_backend::DxContext::shader_wrapper_ private
Definition at line 160 of file network_dx.h.
Referenced by DxContext(), getShaderWrapper(), and ~DxContext().
upload_scratch_mem_
DXAlloc lczero::dx_backend::DxContext::upload_scratch_mem_ private
Definition at line 167 of file network_dx.h.
Referenced by DxContext(), ScheduleUpload(), WaitForGpu(), and ~DxContext().
The documentation for this class was generated from the following files:
src/neural/backends/dx/network_dx.h
src/neural/backends/dx/network_dx.cc