Leela Chess Zero: lczero::Random Class Reference
lczero::Random Class Reference
Thread-safe random number generator for the Lc0 engine.
#include <random.h>
Public Member Functions
double GetDouble (double max_val)
Generates a random double value in the range [0, max_val).
float GetFloat (float max_val)
Generates a random float value in the range [0, max_val).
double GetGamma (double alpha, double beta)
Generates a random value from a gamma distribution.
int GetInt (int min, int max)
Generates a random integer in the inclusive range [min, max].
std::string GetString (int length)
Generates a random string of specified length.
bool GetBool ()
Generates a random boolean value.
template<class RandomAccessIterator >
void Shuffle (RandomAccessIterator s, RandomAccessIterator e)
Shuffles elements in a range using the random generator.
Static Public Member Functions
static Random & Get ()
Gets the singleton instance of the random number generator.
Private Member Functions
Random ()
Private constructor to enforce singleton pattern.
std::mt19937 gen_ GUARDED_BY (mutex_)
The underlying random number generator (Mersenne Twister).
Private Attributes
Mutex mutex_
Mutex to ensure thread safety when accessing the generator.
Detailed Description
Thread-safe random number generator for the Lc0 engine.
This class provides a singleton instance of a random number generator that can be safely used across multiple threads. It offers various methods for generating different types of random values needed throughout the engine.
Definition at line 41 of file random.h.
Constructor & Destructor Documentation
Random()
lczero::Random::Random () private
Private constructor to enforce singleton pattern.
Definition at line 33 of file random.cc.
Member Function Documentation
Get()
Random & lczero::Random::Get () static
Gets the singleton instance of the random number generator.
Returns
Reference to the global Random instance.
Definition at line 35 of file random.cc.
Referenced by lczero::classic::Search::GetBestRootChildWithTemperature(), lczero::SelfPlayGame::SelfPlayGame(), and lczero::TrainingDataWriter::TrainingDataWriter().
GetBool()
bool lczero::Random::GetBool ()
Generates a random boolean value.
Returns
Either true or false with equal probability.
Definition at line 46 of file random.cc.
References GetInt().
GetDouble()
double lczero::Random::GetDouble (double max_val)
Generates a random double value in the range [0, max_val).
Parameters
max_val The upper bound (exclusive) for the generated value.
Returns
A random double value between 0 (inclusive) and max_val (exclusive).
Definition at line 48 of file random.cc.
References mutex_.
GetFloat()
float lczero::Random::GetFloat (float max_val)
Generates a random float value in the range [0, max_val).
Parameters
max_val The upper bound (exclusive) for the generated value.
Returns
A random float value between 0 (inclusive) and max_val (exclusive).
Definition at line 54 of file random.cc.
References mutex_.
Referenced by lczero::classic::Search::GetBestRootChildWithTemperature(), and lczero::SelfPlayGame::SelfPlayGame().
GetGamma()
double lczero::Random::GetGamma (double alpha, double beta)
Generates a random value from a gamma distribution.
Parameters
alpha Shape parameter of the gamma distribution.
beta Scale parameter of the gamma distribution.
Returns
A random value following the gamma distribution with given parameters.
Definition at line 68 of file random.cc.
References mutex_.
GetInt()
int lczero::Random::GetInt (int min, int max)
Generates a random integer in the inclusive range [min, max].
Parameters
min The lower bound (inclusive) for the generated value.
max The upper bound (inclusive) for the generated value.
Returns
A random integer between min and max, both inclusive.
Definition at line 40 of file random.cc.
References mutex_.
Referenced by GetBool(), and GetString().
GetString()
std::string lczero::Random::GetString (int length)
Generates a random string of specified length.
Parameters
length The length of the string to generate.
Returns
A random string containing lowercase letters and digits.
Definition at line 60 of file random.cc.
References GetInt(), and result.
Referenced by lczero::TrainingDataWriter::TrainingDataWriter().
GUARDED_BY()
std::mt19937 gen_ lczero::Random::GUARDED_BY (mutex_) private
The underlying random number generator (Mersenne Twister).
Shuffle()
template<class RandomAccessIterator > void lczero::Random::Shuffle (RandomAccessIterator s, RandomAccessIterator e)
Shuffles elements in a range using the random generator.
Template Parameters
RandomAccessIterator Iterator type for the range to shuffle.
Parameters
s Start iterator of the range to shuffle.
e End iterator of the range to shuffle.
Definition at line 97 of file random.h.
References mutex_.
Member Data Documentation
mutex_
Mutex lczero::Random::mutex_ private
Mutex to ensure thread safety when accessing the generator.
Definition at line 90 of file random.h.
Referenced by GetDouble(), GetFloat(), GetGamma(), GetInt(), and Shuffle().
The documentation for this class was generated from the following files:
utils/random.h
utils/random.cc