Leela Chess Zero: lczero::NetworkComputation Class Reference
lczero::NetworkComputation Class Reference abstract
Abstract interface for neural network computation backends.
#include <network.h>
Public Member Functions
virtual void AddInput (InputPlanes &&input)=0
Adds a sample to the current batch for computation.
virtual void ComputeBlocking ()=0
Executes the neural network computation for the accumulated batch.
virtual int GetBatchSize () const =0
Returns the number of samples currently in the batch.
virtual float GetQVal (int sample) const =0
Retrieves the Q-value (expected game result) for a specific sample.
virtual float GetDVal (int sample) const =0
Retrieves the D-value (draw probability) for a specific sample.
virtual float GetPVal (int sample, int move_id) const =0
Retrieves the P-value (policy/move probability) for a specific move in a sample.
virtual float GetMVal (int sample) const =0
Retrieves the M-value (moves left) for a specific sample.
virtual ~NetworkComputation ()=default
Detailed Description
Abstract interface for neural network computation backends.
This class defines the methods required to perform inference, including adding inputs, running the computation, and retrieving results.
Definition at line 68 of file network.h.
Constructor & Destructor Documentation
~NetworkComputation()
virtual lczero::NetworkComputation::~NetworkComputation () virtual default
Member Function Documentation
AddInput()
virtual void lczero::NetworkComputation::AddInput (InputPlanes && input) pure virtual
Adds a sample to the current batch for computation.
Parameters
input The input planes representing the position to evaluate.
Implemented in lczero::CudaNetworkComputation< DataType >, lczero::CudnnNetworkComputation< DataType >, lczero::dx_backend::DxNetworkComputation, lczero::metal_backend::MetalNetworkComputation, lczero::OnednnNetworkComputation, lczero::onnx::OnnxComputation< DataType >, and lczero::SyclNetworkComputation< DataType >.
ComputeBlocking()
virtual void lczero::NetworkComputation::ComputeBlocking () pure virtual
Executes the neural network computation for the accumulated batch.
This method blocks until the computation is complete.
Implemented in lczero::CudaNetworkComputation< DataType >, lczero::CudnnNetworkComputation< DataType >, lczero::dx_backend::DxNetworkComputation, lczero::metal_backend::MetalNetworkComputation, lczero::OnednnNetworkComputation, lczero::onnx::OnnxComputation< DataType >, and lczero::SyclNetworkComputation< DataType >.
GetBatchSize()
virtual int lczero::NetworkComputation::GetBatchSize () const pure virtual
Returns the number of samples currently in the batch.
Returns
The batch size.
Implemented in lczero::CudaNetworkComputation< DataType >, lczero::CudnnNetworkComputation< DataType >, lczero::dx_backend::DxNetworkComputation, lczero::metal_backend::MetalNetworkComputation, lczero::OnednnNetworkComputation, lczero::onnx::OnnxComputation< DataType >, and lczero::SyclNetworkComputation< DataType >.
GetDVal()
virtual float lczero::NetworkComputation::GetDVal (int sample) const pure virtual
Retrieves the D-value (draw probability) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The D-value.
Implemented in lczero::CudaNetworkComputation< DataType >, lczero::CudnnNetworkComputation< DataType >, lczero::dx_backend::DxNetworkComputation, lczero::metal_backend::MetalNetworkComputation, lczero::OnednnNetworkComputation, lczero::onnx::OnnxComputation< DataType >, and lczero::SyclNetworkComputation< DataType >.
Referenced by lczero::python::Output::Output().
GetMVal()
virtual float lczero::NetworkComputation::GetMVal (int sample) const pure virtual
Retrieves the M-value (moves left) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The expected number of moves left.
Implemented in lczero::CudaNetworkComputation< DataType >, lczero::CudnnNetworkComputation< DataType >, lczero::dx_backend::DxNetworkComputation, lczero::metal_backend::MetalNetworkComputation, lczero::OnednnNetworkComputation, lczero::onnx::OnnxComputation< DataType >, and lczero::SyclNetworkComputation< DataType >.
Referenced by lczero::python::Output::Output().
GetPVal()
virtual float lczero::NetworkComputation::GetPVal (int sample, int move_id) const pure virtual
Retrieves the P-value (policy/move probability) for a specific move in a sample.
Parameters
sample The index of the sample in the batch.
move_id The index of the move.
Returns
The P-value (probability) for the move.
Implemented in lczero::CudaNetworkComputation< DataType >, lczero::CudnnNetworkComputation< DataType >, lczero::dx_backend::DxNetworkComputation, lczero::metal_backend::MetalNetworkComputation, lczero::OnednnNetworkComputation, lczero::onnx::OnnxComputation< DataType >, and lczero::SyclNetworkComputation< DataType >.
Referenced by lczero::python::Output::Output().
GetQVal()
virtual float lczero::NetworkComputation::GetQVal (int sample) const pure virtual
Retrieves the Q-value (expected game result) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The Q-value (typically from -1.0 to 1.0).
Implemented in lczero::CudaNetworkComputation< DataType >, lczero::CudnnNetworkComputation< DataType >, lczero::dx_backend::DxNetworkComputation, lczero::metal_backend::MetalNetworkComputation, lczero::OnednnNetworkComputation, lczero::onnx::OnnxComputation< DataType >, and lczero::SyclNetworkComputation< DataType >.
Referenced by lczero::python::Output::Output().
The documentation for this class was generated from the following file:
src/neural/network.h