Leela Chess Zero: lczero::ChoiceOption Class Reference
lczero::ChoiceOption Class Reference
#include <optionsparser.h>
Public Types
using ValueType = std::string
Public Member Functions
ChoiceOption (const OptionId &id, const std::vector< std::string > &choices)
void SetValue (const std::string &value, OptionsDict *dict) override
Public Member Functions inherited from lczero::OptionsParser::Option
Option (const OptionId &id)
virtual ~Option ()
Private Member Functions
std::string GetOptionString (const OptionsDict &dict) const override
bool ProcessLongFlag (const std::string &flag, const std::string &value, OptionsDict *dict) override
std::string GetHelp (const OptionsDict &dict) const override
bool ProcessShortFlagWithValue (char flag, const std::string &value, OptionsDict *dict) override
ValueType GetVal (const OptionsDict &) const
void SetVal (OptionsDict *dict, const ValueType &val) const
Private Attributes
std::vector< std::string > choices_
Additional Inherited Members
Protected Member Functions inherited from lczero::OptionsParser::Option
const OptionId & GetId () const
std::string GetUciOption () const
std::string GetHelpText () const
std::string GetLongFlag () const
char GetShortFlag () const
Detailed Description
Definition at line 233 of file optionsparser.h.
Member Typedef Documentation
ValueType
using lczero::ChoiceOption::ValueType = std::string
Definition at line 235 of file optionsparser.h.
Constructor & Destructor Documentation
ChoiceOption()
lczero::ChoiceOption::ChoiceOption (const OptionId & id, const std::vector< std::string > & choices)
Definition at line 592 of file optionsparser.cc.
Member Function Documentation
GetHelp()
std::string lczero::ChoiceOption::GetHelp (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 620 of file optionsparser.cc.
References choices_, lczero::OptionsParser::Option::GetHelpText(), lczero::OptionsParser::Option::GetLongFlag(), lczero::OptionsParser::Option::GetShortFlag(), lczero::OptionsParser::Option::GetUciOption(), and GetVal().
GetOptionString()
std::string lczero::ChoiceOption::GetOptionString (const OptionsDict & dict) const override private virtual
Implements lczero::OptionsParser::Option.
Definition at line 630 of file optionsparser.cc.
References choices_, and GetVal().
GetVal()
std::string lczero::ChoiceOption::GetVal (const OptionsDict & dict) const private
Definition at line 638 of file optionsparser.cc.
References lczero::OptionsDict::Get(), and lczero::OptionsParser::Option::GetId().
Referenced by GetHelp(), and GetOptionString().
ProcessLongFlag()
bool lczero::ChoiceOption::ProcessLongFlag (const std::string & flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 600 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetLongFlag(), SetVal(), and value.
ProcessShortFlagWithValue()
bool lczero::ChoiceOption::ProcessShortFlagWithValue (char flag, const std::string & value, OptionsDict * dict) override private virtual
Reimplemented from lczero::OptionsParser::Option.
Definition at line 610 of file optionsparser.cc.
References lczero::OptionsParser::Option::GetShortFlag(), SetVal(), and value.
SetVal()
void lczero::ChoiceOption::SetVal (OptionsDict * dict, const ValueType & val) const private
Definition at line 642 of file optionsparser.cc.
References choices_, lczero::OptionsParser::Option::GetId(), lczero::OptionsParser::Option::GetLongFlag(), and lczero::OptionsDict::Set().
Referenced by ProcessLongFlag(), ProcessShortFlagWithValue(), and SetValue().
SetValue()
void lczero::ChoiceOption::SetValue (const std::string & value, OptionsDict * dict) override virtual
Implements lczero::OptionsParser::Option.
Definition at line 596 of file optionsparser.cc.
References SetVal(), and value.
Member Data Documentation
choices_
std::vector<std::string> lczero::ChoiceOption::choices_ private
Definition at line 251 of file optionsparser.h.
Referenced by GetHelp(), GetOptionString(), and SetVal().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/optionsparser.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/optionsparser.cc