Leela Chess Zero: Tuner Class Reference
Tuner Class Reference
#include <OpenCLTuner.h>
Public Member Functions
std::string tune_sgemm (const int m, const int n, const int k, const int batch_size, const int runs=4)
std::string load_sgemm_tuners (const int m, const int n, const int k, const int batch_size)
Tuner (OpenCL &opencl, const OpenCLParams &params, cl::Context context, cl::Device device)
Static Public Attributes
static constexpr auto TUNER_VERSION = 0
Private Member Functions
void store_sgemm_tuners (const int m, const int n, const int k, const int batch_size, std::string tuners)
bool valid_config_sgemm (TuneParameters p, bool exhaustive)
std::string parameters_to_defines (const TuneParameters &p)
std::string parameters_to_string (const TuneParameters &p)
TuneParameters get_parameters_by_int (const std::vector< Configurations > &opts, const int n)
std::string sgemm_tuners_from_line (std::string line, const int m, const int n, const int k, const int batch_size)
Private Attributes
OpenCL & m_opencl
const OpenCLParams & m_params
cl::Context m_context
cl::Device m_device
Detailed Description
Definition at line 37 of file OpenCLTuner.h.
Constructor & Destructor Documentation
Tuner()
Tuner::Tuner (OpenCL & opencl, const OpenCLParams & params, cl::Context context, cl::Device device) inline
Definition at line 50 of file OpenCLTuner.h.
Member Function Documentation
get_parameters_by_int()
TuneParameters Tuner::get_parameters_by_int (const std::vector< Configurations > & opts, const int n) private
Definition at line 99 of file OpenCLTuner.cc.
Referenced by tune_sgemm().
load_sgemm_tuners()
std::string Tuner::load_sgemm_tuners (const int m, const int n, const int k, const int batch_size)
Definition at line 453 of file OpenCLTuner.cc.
References CERR, OpenCLParams::force_tune, m, m_params, sgemm_tuners_from_line(), store_sgemm_tuners(), OpenCLParams::tune_only, tune_sgemm(), OpenCLParams::tuner_file, and WINOGRAD_P.
parameters_to_defines()
std::string Tuner::parameters_to_defines (const TuneParameters & p) private
Definition at line 120 of file OpenCLTuner.cc.
References p.
Referenced by tune_sgemm().
parameters_to_string()
std::string Tuner::parameters_to_string (const TuneParameters & p) private
Definition at line 128 of file OpenCLTuner.cc.
References p.
Referenced by tune_sgemm().
sgemm_tuners_from_line()
std::string Tuner::sgemm_tuners_from_line (std::string line, const int m, const int n, const int k, const int batch_size) private
Definition at line 407 of file OpenCLTuner.cc.
References OpenCL::get_device_name(), m, m_opencl, and TUNER_VERSION.
Referenced by load_sgemm_tuners().
store_sgemm_tuners()
void Tuner::store_sgemm_tuners (const int m, const int n, const int k, const int batch_size, std::string tuners) private
Definition at line 366 of file OpenCLTuner.cc.
References CERR, OpenCL::get_device_name(), m, m_opencl, m_params, OpenCLParams::tuner_file, and TUNER_VERSION.
Referenced by load_sgemm_tuners().
tune_sgemm()
std::string Tuner::tune_sgemm (const int m, const int n, const int k, const int batch_size, const int runs = 4)
Definition at line 182 of file OpenCLTuner.cc.
References ceilMultiple(), CERR, compare_ref(), get_parameters_by_int(), m, OpenCL::m_cl_args, m_context, m_device, m_opencl, m_params, MAX_ERROR, next_power_of_two(), p, parameters_to_defines(), parameters_to_string(), sgemm_generate_data(), sgemmBatched_ref(), sourceCode_sgemm, OpenCLParams::tune_exhaustive, valid_config_sgemm(), and WINOGRAD_P.
Referenced by load_sgemm_tuners().
valid_config_sgemm()
bool Tuner::valid_config_sgemm (TuneParameters p, bool exhaustive) private
Definition at line 65 of file OpenCLTuner.cc.
References IsMultiple(), and p.
Referenced by tune_sgemm().
Member Data Documentation
m_context
cl::Context Tuner::m_context private
Definition at line 40 of file OpenCLTuner.h.
Referenced by tune_sgemm().
m_device
cl::Device Tuner::m_device private
Definition at line 41 of file OpenCLTuner.h.
Referenced by tune_sgemm().
m_opencl
OpenCL& Tuner::m_opencl private
Definition at line 38 of file OpenCLTuner.h.
Referenced by sgemm_tuners_from_line(), store_sgemm_tuners(), and tune_sgemm().
m_params
const OpenCLParams& Tuner::m_params private
Definition at line 39 of file OpenCLTuner.h.
Referenced by load_sgemm_tuners(), store_sgemm_tuners(), and tune_sgemm().
TUNER_VERSION
constexpr auto Tuner::TUNER_VERSION = 0 static constexpr
Definition at line 49 of file OpenCLTuner.h.
Referenced by sgemm_tuners_from_line(), and store_sgemm_tuners().
The documentation for this class was generated from the following files:
src/neural/backends/opencl/OpenCLTuner.h
src/neural/backends/opencl/OpenCLTuner.cc