Leela Chess Zero: lczero::SearchManager Class Reference
lczero::SearchManager Class Reference
#include <register.h>
Classes
struct Register
Public Member Functions
void AddSearchFactory (std::unique_ptr< SearchFactory >)
std::vector< std::string_view > GetSearchNames () const
SearchFactory * GetFactoryByName (std::string_view name) const
Static Public Member Functions
static SearchManager * Get ()
Private Member Functions
SearchManager ()=default
Private Attributes
std::vector< std::unique_ptr< SearchFactory > > algorithms_
Detailed Description
Definition at line 40 of file register.h.
Constructor & Destructor Documentation
SearchManager()
lczero::SearchManager::SearchManager () private default
Member Function Documentation
AddSearchFactory()
void lczero::SearchManager::AddSearchFactory (std::unique_ptr< SearchFactory > algorithm)
Definition at line 39 of file register.cc.
References algorithms_.
Referenced by lczero::SearchManager::Register::Register().
Get()
SearchManager * lczero::SearchManager::Get () static
Definition at line 34 of file register.cc.
Referenced by lczero::ChooseAndRunEngine(), and lczero::SearchManager::Register::Register().
GetFactoryByName()
SearchFactory * lczero::SearchManager::GetFactoryByName (std::string_view name) const
Definition at line 52 of file register.cc.
References algorithms_, and name.
Referenced by lczero::ChooseAndRunEngine().
GetSearchNames()
std::vector< std::string_view > lczero::SearchManager::GetSearchNames () const
Definition at line 43 of file register.cc.
References algorithms_.
Referenced by lczero::ChooseAndRunEngine().
Member Data Documentation
algorithms_
std::vector<std::unique_ptr<SearchFactory> > lczero::SearchManager::algorithms_ private
Definition at line 60 of file register.h.
Referenced by AddSearchFactory(), GetFactoryByName(), and GetSearchNames().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/register.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/register.cc