Leela Chess Zero: lczero::OnnxBuilder Class Reference
lczero::OnnxBuilder Class Reference
#include <builder.h>
Public Member Functions
OnnxBuilder (int opset, int ir=-1)
void AddInput (const std::string &name, std::initializer_list< int > dims, pblczero::TensorProto::DataType datatype)
void AddOutput (const std::string &name, std::initializer_list< int > dims, pblczero::TensorProto::DataType datatype)
std::string Conv (const std::string &name, const std::string &input_name, const OnnxConst &kernel_weights, const OnnxConst &bias_weights, int pads=1)
std::string Add (const std::string &name, const std::string &input1, const std::string &input2)
std::string Add (const std::string &name, const std::string &input1, const OnnxConst &input2)
std::string GlobalAveragePool (const std::string &name, const std::string &input)
std::string Squeeze (const std::string &name, const std::string &input, std::initializer_list< int > axes)
std::string MatMul (const std::string &name, const std::string &input1, const OnnxConst &input2)
std::string MatMul (const std::string &name, const std::string &input1, const std::string &input2)
std::string Mul (const std::string &name, const std::string &input1, const std::string &input2)
std::string Mul (const std::string &name, const std::string &input1, const OnnxConst &)
std::string Relu (const std::string &name, const std::string &input)
std::string Tanh (const std::string &name, const std::string &input)
std::string Softmax (const std::string &name, const std::string &input, int axis=1)
std::string AddInitializer (const std::string &name, const OnnxConst &weights)
std::string Reshape (const std::string &name, const std::string &input, const std::string &shape)
std::vector< std::string > Split (const std::string &name, const std::string &input, int axis, std::initializer_list< int > split={})
std::string Sigmoid (const std::string &name, const std::string &input)
std::string Gather (const std::string &name, const std::string &input1, const std::string &input2, int axis)
std::string Softplus (const std::string &name, const std::string &input)
std::string Identity (const std::string &name, const std::string &input)
std::string Transpose (const std::string &name, const std::string &input, std::initializer_list< int > perm={})
std::string Pad (const std::string &name, const std::string &input, std::initializer_list< int > pads)
std::string Selu (const std::string &name, const std::string &input)
std::string Slice (const std::string &name, const std::string &input, std::initializer_list< int > starts, std::initializer_list< int > ends)
std::string Concat (const std::string &name, const std::vector< std::string > &input, int axis)
std::string LayerNormalization (const std::string &name, const std::string &input, const OnnxConst &scale, const OnnxConst &bias, int axis, float epsilon=1e-6)
std::string Expand (const std::string &name, const std::string &input, const std::string &shape)
std::string Shape (const std::string &name, const std::string &input)
std::string Exp (const std::string &name, const std::string &input)
std::string Div (const std::string &name, const std::string &input1, const std::string &input2)
std::string Sub (const std::string &name, const std::string &input1, const std::string &input2)
std::string Greater (const std::string &name, const std::string &input1, const OnnxConst &)
std::string Where (const std::string &name, const std::string &input1, const std::string &input2, const std::string &input3)
std::string Mish (const std::string &name, const std::string &input)
std::string Sqrt (const std::string &name, const std::string &input)
std::string Reciprocal (const std::string &name, const std::string &input)
std::string Cast (const std::string &name, const std::string &input, pblczero::TensorProto::DataType type)
std::string ReduceMean (const std::string &name, const std::string &input, std::initializer_list< int > axes, bool keepdims=true)
const pblczero::ModelProto & as_proto () const
std::string OutputAsString () const
Private Attributes
const int opset_
pblczero::ModelProto model_
Detailed Description
Definition at line 46 of file builder.h.
Constructor & Destructor Documentation
OnnxBuilder()
lczero::OnnxBuilder::OnnxBuilder (int opset, int ir = -1)
Definition at line 38 of file builder.cc.
References GetVersionStr(), and model_.
Member Function Documentation
Add() [1/2]
std::string lczero::OnnxBuilder::Add (const std::string & name, const std::string & input1, const OnnxConst & input2)
Definition at line 163 of file builder.cc.
References AddInitializer(), model_, and name.
Add() [2/2]
std::string lczero::OnnxBuilder::Add (const std::string & name, const std::string & input1, const std::string & input2)
Definition at line 155 of file builder.cc.
References model_, and name.
AddInitializer()
std::string lczero::OnnxBuilder::AddInitializer (const std::string & name, const OnnxConst & weights)
Definition at line 115 of file builder.cc.
References lczero::OnnxConst::GetDataType(), lczero::OnnxConst::GetDimensions(), lczero::OnnxConst::GetRawData(), model_, and name.
Referenced by Add(), Conv(), Greater(), LayerNormalization(), MatMul(), Mul(), ReduceMean(), Slice(), Split(), and Squeeze().
AddInput()
void lczero::OnnxBuilder::AddInput (const std::string & name, std::initializer_list< int > dims, pblczero::TensorProto::DataType datatype)
Definition at line 103 of file builder.cc.
References model_, and name.
AddOutput()
void lczero::OnnxBuilder::AddOutput (const std::string & name, std::initializer_list< int > dims, pblczero::TensorProto::DataType datatype)
Definition at line 109 of file builder.cc.
References model_, and name.
as_proto()
const pblczero::ModelProto & lczero::OnnxBuilder::as_proto () const inline
Definition at line 130 of file builder.h.
References model_.
Cast()
std::string lczero::OnnxBuilder::Cast (const std::string & name, const std::string & input, pblczero::TensorProto::DataType type)
Definition at line 461 of file builder.cc.
References input, model_, name, and type.
Concat()
std::string lczero::OnnxBuilder::Concat (const std::string & name, const std::vector< std::string > & input, int axis)
Definition at line 351 of file builder.cc.
References input, model_, and name.
Conv()
std::string lczero::OnnxBuilder::Conv (const std::string & name, const std::string & input_name, const OnnxConst & kernel_weights, const OnnxConst & bias_weights, int pads = 1)
Definition at line 141 of file builder.cc.
References AddInitializer(), lczero::OnnxConst::GetDimensions(), model_, and name.
Div()
std::string lczero::OnnxBuilder::Div (const std::string & name, const std::string & input1, const std::string & input2)
Definition at line 407 of file builder.cc.
References model_, and name.
Exp()
std::string lczero::OnnxBuilder::Exp (const std::string & name, const std::string & input)
Definition at line 401 of file builder.cc.
References input, model_, and name.
Expand()
std::string lczero::OnnxBuilder::Expand (const std::string & name, const std::string & input, const std::string & shape)
Definition at line 386 of file builder.cc.
References input, model_, and name.
Gather()
std::string lczero::OnnxBuilder::Gather (const std::string & name, const std::string & input1, const std::string & input2, int axis)
Definition at line 273 of file builder.cc.
References model_, and name.
GlobalAveragePool()
std::string lczero::OnnxBuilder::GlobalAveragePool (const std::string & name, const std::string & input)
Definition at line 171 of file builder.cc.
References input, model_, and name.
Greater()
std::string lczero::OnnxBuilder::Greater (const std::string & name, const std::string & input1, const OnnxConst & input2)
Definition at line 423 of file builder.cc.
References AddInitializer(), model_, and name.
Identity()
std::string lczero::OnnxBuilder::Identity (const std::string & name, const std::string & input)
Definition at line 289 of file builder.cc.
References input, model_, and name.
LayerNormalization()
std::string lczero::OnnxBuilder::LayerNormalization (const std::string & name, const std::string & input, const OnnxConst & scale, const OnnxConst & bias, int axis, float epsilon = 1e-6)
Definition at line 372 of file builder.cc.
References AddInitializer(), bias, input, model_, and name.
MatMul() [1/2]
std::string lczero::OnnxBuilder::MatMul (const std::string & name, const std::string & input1, const OnnxConst & input2)
Definition at line 209 of file builder.cc.
References AddInitializer(), model_, and name.
MatMul() [2/2]
std::string lczero::OnnxBuilder::MatMul (const std::string & name, const std::string & input1, const std::string & input2)
Definition at line 218 of file builder.cc.
References model_, and name.
Mish()
std::string lczero::OnnxBuilder::Mish (const std::string & name, const std::string & input)
Definition at line 443 of file builder.cc.
References input, model_, and name.
Mul() [1/2]
std::string lczero::OnnxBuilder::Mul (const std::string & name, const std::string & input1, const OnnxConst & input2)
Definition at line 201 of file builder.cc.
References AddInitializer(), model_, and name.
Mul() [2/2]
std::string lczero::OnnxBuilder::Mul (const std::string & name, const std::string & input1, const std::string & input2)
Definition at line 193 of file builder.cc.
References model_, and name.
OutputAsString()
std::string lczero::OnnxBuilder::OutputAsString () const inline
Definition at line 132 of file builder.h.
References model_.
Pad()
std::string lczero::OnnxBuilder::Pad (const std::string & name, const std::string & input, std::initializer_list< int > pads)
Definition at line 265 of file builder.cc.
References input, model_, and name.
Reciprocal()
std::string lczero::OnnxBuilder::Reciprocal (const std::string & name, const std::string & input)
Definition at line 455 of file builder.cc.
References input, model_, and name.
ReduceMean()
std::string lczero::OnnxBuilder::ReduceMean (const std::string & name, const std::string & input, std::initializer_list< int > axes, bool keepdims = true)
Definition at line 469 of file builder.cc.
References AddInitializer(), input, model_, name, and opset_.
Relu()
std::string lczero::OnnxBuilder::Relu (const std::string & name, const std::string & input)
Definition at line 227 of file builder.cc.
References input, model_, and name.
Reshape()
std::string lczero::OnnxBuilder::Reshape (const std::string & name, const std::string & input, const std::string & shape)
Definition at line 247 of file builder.cc.
References input, model_, and name.
Selu()
std::string lczero::OnnxBuilder::Selu (const std::string & name, const std::string & input)
Definition at line 295 of file builder.cc.
References input, model_, and name.
Shape()
std::string lczero::OnnxBuilder::Shape (const std::string & name, const std::string & input)
Definition at line 395 of file builder.cc.
References input, model_, and name.
Sigmoid()
std::string lczero::OnnxBuilder::Sigmoid (const std::string & name, const std::string & input)
Definition at line 365 of file builder.cc.
References input, model_, and name.
Slice()
std::string lczero::OnnxBuilder::Slice (const std::string & name, const std::string & input, std::initializer_list< int > starts, std::initializer_list< int > ends)
Definition at line 331 of file builder.cc.
References AddInitializer(), input, model_, name, and opset_.
Softmax()
std::string lczero::OnnxBuilder::Softmax (const std::string & name, const std::string & input, int axis = 1)
Definition at line 239 of file builder.cc.
References input, model_, and name.
Softplus()
std::string lczero::OnnxBuilder::Softplus (const std::string & name, const std::string & input)
Definition at line 283 of file builder.cc.
References input, model_, and name.
Split()
std::vector< std::string > lczero::OnnxBuilder::Split (const std::string & name, const std::string & input, int axis, std::initializer_list< int > split = {})
Definition at line 301 of file builder.cc.
References AddInitializer(), input, model_, name, and opset_.
Sqrt()
std::string lczero::OnnxBuilder::Sqrt (const std::string & name, const std::string & input)
Definition at line 449 of file builder.cc.
References input, model_, and name.
Squeeze()
std::string lczero::OnnxBuilder::Squeeze (const std::string & name, const std::string & input, std::initializer_list< int > axes)
Definition at line 177 of file builder.cc.
References AddInitializer(), input, model_, name, and opset_.
Sub()
std::string lczero::OnnxBuilder::Sub (const std::string & name, const std::string & input1, const std::string & input2)
Definition at line 415 of file builder.cc.
References model_, and name.
Tanh()
std::string lczero::OnnxBuilder::Tanh (const std::string & name, const std::string & input)
Definition at line 233 of file builder.cc.
References input, model_, and name.
Transpose()
std::string lczero::OnnxBuilder::Transpose (const std::string & name, const std::string & input, std::initializer_list< int > perm = {})
Definition at line 256 of file builder.cc.
References input, model_, and name.
Where()
std::string lczero::OnnxBuilder::Where (const std::string & name, const std::string & input1, const std::string & input2, const std::string & input3)
Definition at line 432 of file builder.cc.
References model_, and name.
Member Data Documentation
model_
pblczero::ModelProto lczero::OnnxBuilder::model_ private
Definition at line 136 of file builder.h.
Referenced by Add(), Add(), AddInitializer(), AddInput(), AddOutput(), as_proto(), Cast(), Concat(), Conv(), Div(), Exp(), Expand(), Gather(), GlobalAveragePool(), Greater(), Identity(), LayerNormalization(), MatMul(), MatMul(), Mish(), Mul(), Mul(), OnnxBuilder(), OutputAsString(), Pad(), Reciprocal(), ReduceMean(), Relu(), Reshape(), Selu(), Shape(), Sigmoid(), Slice(), Softmax(), Softplus(), Split(), Sqrt(), Squeeze(), Sub(), Tanh(), Transpose(), and Where().
opset_
const int lczero::OnnxBuilder::opset_ private
Definition at line 135 of file builder.h.
Referenced by ReduceMean(), Slice(), Split(), and Squeeze().
The documentation for this class was generated from the following files:
src/neural/onnx/builder.h
src/neural/onnx/builder.cc