Leela Chess Zero: lczero::BackendBenchmark Class Reference
lczero::BackendBenchmark Class Reference
#include <backendbench.h>
Public Member Functions
BackendBenchmark ()=default
void Run ()
Detailed Description
Definition at line 32 of file backendbench.h.
Constructor & Destructor Documentation
BackendBenchmark()
lczero::BackendBenchmark::BackendBenchmark () default
Member Function Documentation
Run()
void lczero::BackendBenchmark::Run ()
Definition at line 80 of file backendbench.cc.
References lczero::OptionsParser::Add(), lczero::BackendManager::CreateFromParams(), lczero::BackendManager::Get(), lczero::OptionsParser::GetOptionsDict(), lczero::ChessBoard::kStartposFen, lczero::SharedBackendParams::Populate(), lczero::OptionsParser::ProcessAllFlags(), and lczero::classic::NodeTree::ResetToPosition().
Referenced by main().
The documentation for this class was generated from the following files:
src/tools/backendbench.h
src/tools/backendbench.cc