Leela Chess Zero: lczero::cudnn_backend::FCLayer< DataType > Class Template Reference
lczero::cudnn_backend::FCLayer< DataType > Class Template Reference
Fully Connected Layer.
#include <layers.h>
Public Member Functions
FCLayer (BaseLayer< DataType > *ip, int C, int H, int W, bool bias, ActivationFunction activation)
Constructor for FCLayer.
~FCLayer ()
void LoadWeights (float *cpuWeight, float *cpuBias, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType ***=nullptr) override
Evaluates the layer.
void LoadWeights (float *cpuWeight, float *cpuBias, void *scratch)
void LoadWeights (float *cpuWeight, float *cpuBias, void *)
void Eval (int N, half *output_tensor, const half *input_tensor, const half *, void *, size_t, cudnnHandle_t, cublasHandle_t cublas, cudaStream_t stream, half ***)
void Eval (int N, float *output_tensor, const float *input_tensor, const float *, void *, size_t, cudnnHandle_t, cublasHandle_t cublas, cudaStream_t stream, float ***)
Public Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc)
Constructor.
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, bool use_gemm_ex)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
const bool use_bias_
const ActivationFunction act_
DataType * weights_ = nullptr
DataType * biases_ = nullptr
Additional Inherited Members
Protected Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const half *A, const half *B, half *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
Protected Attributes inherited from lczero::cudnn_backend::BaseLayer< DataType >
BaseLayer * input_
int C
int H
int W
bool nhwc_
const bool use_gemm_ex_
Detailed Description
template<typename DataType>
class lczero::cudnn_backend::FCLayer< DataType >
Fully Connected Layer.
Definition at line 147 of file layers.h.
Constructor & Destructor Documentation
FCLayer()
template<typename DataType > lczero::cudnn_backend::FCLayer< DataType >::FCLayer (BaseLayer< DataType > * ip, int C, int H, int W, bool bias, ActivationFunction activation)
Constructor for FCLayer.
Parameters
ip Input layer.
C Output channels (or size).
H Output height (usually 1).
W Output width (usually 1).
bias Whether to use bias.
activation Activation function.
Definition at line 605 of file layers.cc.
References lczero::cudnn_backend::FCLayer< DataType >::biases_, lczero::cudnn_backend::BaseLayer< DataType >::C, lczero::cudnn_backend::BaseLayer< DataType >::GetC(), lczero::cudnn_backend::BaseLayer< DataType >::GetH(), lczero::cudnn_backend::BaseLayer< DataType >::GetW(), lczero::cudnn_backend::BaseLayer< DataType >::H, ReportCUDAErrors, lczero::cudnn_backend::FCLayer< DataType >::use_bias_, lczero::cudnn_backend::BaseLayer< DataType >::W, and lczero::cudnn_backend::FCLayer< DataType >::weights_.
~FCLayer()
template<typename DataType > lczero::cudnn_backend::FCLayer< DataType >::~FCLayer ()
Definition at line 711 of file layers.cc.
References ReportCUDAErrors, and weights_.
Member Function Documentation
Eval() [1/3]
template<typename DataType > void lczero::cudnn_backend::FCLayer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType *** = nullptr) override virtual
Evaluates the layer.
Parameters
N Batch size.
output Output buffer.
input Input buffer.
input2 Optional second input (e.g., skip connection).
scratch Scratch memory.
scratch_size Size of scratch memory.
cudnn CuDNN handle.
cublas CuBLAS handle.
stream CUDA stream.
offset_pointers Optional pointers for batched offset calculations.
Implements lczero::cudnn_backend::BaseLayer< DataType >.
Eval() [2/3]
void lczero::cudnn_backend::FCLayer< float >::Eval (int N, float * output_tensor, const float * input_tensor, const float * , void * , size_t , cudnnHandle_t , cublasHandle_t cublas, cudaStream_t stream, float ***)
Definition at line 690 of file layers.cc.
References lczero::ACTIVATION_NONE, lczero::cudnn_backend::addVectors(), C, input_, ReportCUBLASErrors, and weights_.
Eval() [3/3]
void lczero::cudnn_backend::FCLayer< half >::Eval (int N, half * output_tensor, const half * input_tensor, const half * , void * , size_t , cudnnHandle_t , cublasHandle_t cublas, cudaStream_t stream, half ***)
Definition at line 666 of file layers.cc.
References lczero::ACTIVATION_NONE, lczero::cudnn_backend::addVectors(), C, input_, ReportCUBLASErrors, and weights_.
LoadWeights() [1/3]
void lczero::cudnn_backend::FCLayer< float >::LoadWeights (float * cpuWeight, float * cpuBias, void *)
Definition at line 649 of file layers.cc.
References C, input_, ReportCUDAErrors, and weights_.
LoadWeights() [2/3]
void lczero::cudnn_backend::FCLayer< half >::LoadWeights (float * cpuWeight, float * cpuBias, void * scratch)
Definition at line 620 of file layers.cc.
References C, lczero::cudnn_backend::convertNCHWtoNHWC(), lczero::cudnn_backend::copyTypeConverted(), input_, ReportCUDAErrors, and weights_.
LoadWeights() [3/3]
template<typename DataType > void lczero::cudnn_backend::FCLayer< DataType >::LoadWeights (float * cpuWeight, float * cpuBias, void * scratch)
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::cudnn_backend::FCLayer< DataType >::act_ private
Definition at line 163 of file layers.h.
biases_
template<typename DataType > DataType* lczero::cudnn_backend::FCLayer< DataType >::biases_ = nullptr private
Definition at line 165 of file layers.h.
Referenced by lczero::cudnn_backend::FCLayer< DataType >::FCLayer().
use_bias_
template<typename DataType > const bool lczero::cudnn_backend::FCLayer< DataType >::use_bias_ private
Definition at line 162 of file layers.h.
Referenced by lczero::cudnn_backend::FCLayer< DataType >::FCLayer().
weights_
template<typename DataType > DataType* lczero::cudnn_backend::FCLayer< DataType >::weights_ = nullptr private
Definition at line 164 of file layers.h.
Referenced by lczero::cudnn_backend::FCLayer< DataType >::FCLayer().
The documentation for this class was generated from the following files:
src/neural/backends/cuda/layers.h
src/neural/backends/cuda/layers.cc