Leela Chess Zero: lczero::SyzygyTablebaseImpl Class Reference
lczero::SyzygyTablebaseImpl Class Reference
Internal implementation of Syzygy tablebase probing.
Public Member Functions
SyzygyTablebaseImpl (const std::string &paths)
~SyzygyTablebaseImpl ()
int max_cardinality () const
int probe_wdl_table (const ChessBoard &pos, int *success)
int probe_dtm_table (const ChessBoard &pos, int won, int *success)
int probe_dtz_table (const ChessBoard &pos, int wdl, int *success)
Private Member Functions
std::string name_for_tb (const char *str, const char *suffix)
bool test_tb (const char *str, const char *suffix)
void * map_tb (const char *name, const char *suffix, map_t *mapping)
void unmap_file (void *base_address, map_t mapping)
void add_to_hash (BaseEntry *ptr, Key key)
void init_tb (char *str)
void free_tb_entry (BaseEntry *be)
bool init_table (BaseEntry *be, const char *str, int type)
int probe_table (const ChessBoard &pos, int s, int *success, const int type)
Private Attributes
int max_cardinality_ = 0
int max_cardinality_dtm_ = 0
Mutex ready_mutex_
std::string paths_
int num_piece_entries_ = 0
int num_pawn_entries_ = 0
int num_wdl_ = 0
int num_dtm_ = 0
int num_dtz_ = 0
std::vector< PieceEntry > piece_entries_
std::vector< PawnEntry > pawn_entries_
std::vector< TbHashEntry > tb_hash_
Detailed Description
Internal implementation of Syzygy tablebase probing.
Handles tablebase file loading, memory mapping, hash table management, and the core probing algorithms. This class is hidden from the public API via the PIMPL pattern in SyzygyTablebase.
Definition at line 894 of file syzygy.cc.
Constructor & Destructor Documentation
SyzygyTablebaseImpl()
lczero::SyzygyTablebaseImpl::SyzygyTablebaseImpl (const std::string & paths) inline
Definition at line 896 of file syzygy.cc.
References CERR, init_tb(), m, num_dtm_, num_dtz_, num_wdl_, paths_, pchr, tb_hash_, TB_HASHBITS, and TB_PIECES.
~SyzygyTablebaseImpl()
lczero::SyzygyTablebaseImpl::~SyzygyTablebaseImpl () inline
Definition at line 1029 of file syzygy.cc.
References free_tb_entry(), num_pawn_entries_, num_piece_entries_, paths_, pawn_entries_, and piece_entries_.
Member Function Documentation
add_to_hash()
void lczero::SyzygyTablebaseImpl::add_to_hash (BaseEntry * ptr, Key key) inline private
Definition at line 1127 of file syzygy.cc.
References idx, key, ptr, tb_hash_, and TB_HASHBITS.
Referenced by init_tb().
free_tb_entry()
void lczero::SyzygyTablebaseImpl::free_tb_entry (BaseEntry * be) inline private
Definition at line 1201 of file syzygy.cc.
References ei, num, precomp, type, and unmap_file().
Referenced by ~SyzygyTablebaseImpl().
init_table()
bool lczero::SyzygyTablebaseImpl::init_table (BaseEntry * be, const char * str, int type) inline private
Definition at line 1217 of file syzygy.cc.
References data, ei, map_tb(), num, PAWN, PIECE, pieces, type, and unmap_file().
Referenced by probe_table().
init_tb()
void lczero::SyzygyTablebaseImpl::init_tb (char * str) inline private
Definition at line 1138 of file syzygy.cc.
References add_to_hash(), key, max_cardinality_, max_cardinality_dtm_, num_dtm_, num_dtz_, num_pawn_entries_, num_piece_entries_, num_wdl_, PAWN, pawn_entries_, piece_entries_, Swap, test_tb(), and type.
Referenced by SyzygyTablebaseImpl().
map_tb()
void * lczero::SyzygyTablebaseImpl::map_tb (const char * name, const char * suffix, map_t * mapping) inline private
Definition at line 1070 of file syzygy.cc.
References lczero::GetFileSize(), mapping, name, and name_for_tb().
Referenced by init_table().
max_cardinality()
int lczero::SyzygyTablebaseImpl::max_cardinality () const inline
Definition at line 1039 of file syzygy.cc.
References max_cardinality_.
name_for_tb()
std::string lczero::SyzygyTablebaseImpl::name_for_tb (const char * str, const char * suffix) inline private
Definition at line 1054 of file syzygy.cc.
References paths_, and SEP_CHAR.
Referenced by map_tb(), and test_tb().
probe_dtm_table()
int lczero::SyzygyTablebaseImpl::probe_dtm_table (const ChessBoard & pos, int won, int * success) inline
Definition at line 1045 of file syzygy.cc.
References probe_table().
probe_dtz_table()
int lczero::SyzygyTablebaseImpl::probe_dtz_table (const ChessBoard & pos, int wdl, int * success) inline
Definition at line 1049 of file syzygy.cc.
References probe_table().
probe_table()
int lczero::SyzygyTablebaseImpl::probe_table (const ChessBoard & pos, int s, int * success, const int type) inline private
Definition at line 1356 of file syzygy.cc.
References dtmMap, dtmMapIdx, dtzMap, dtzMapIdx, ei, lczero::ChessBoard::flipped(), idx, init_table(), key, lczero::ChessBoard::kings(), m, num, lczero::ChessBoard::ours(), p, PAWN, PIECE, ptr, ready_mutex_, tb_hash_, TB_HASHBITS, TB_PIECES, lczero::ChessBoard::theirs(), and type.
Referenced by probe_dtm_table(), probe_dtz_table(), and probe_wdl_table().
probe_wdl_table()
int lczero::SyzygyTablebaseImpl::probe_wdl_table (const ChessBoard & pos, int * success) inline
Definition at line 1041 of file syzygy.cc.
References probe_table().
test_tb()
bool lczero::SyzygyTablebaseImpl::test_tb (const char * str, const char * suffix) inline private
Definition at line 1066 of file syzygy.cc.
References name_for_tb().
Referenced by init_tb().
unmap_file()
void lczero::SyzygyTablebaseImpl::unmap_file (void * base_address, map_t mapping) inline private
Definition at line 1118 of file syzygy.cc.
References mapping.
Referenced by free_tb_entry(), and init_table().
Member Data Documentation
max_cardinality_
int lczero::SyzygyTablebaseImpl::max_cardinality_ = 0 private
Definition at line 1484 of file syzygy.cc.
Referenced by init_tb(), and max_cardinality().
max_cardinality_dtm_
int lczero::SyzygyTablebaseImpl::max_cardinality_dtm_ = 0 private
Definition at line 1485 of file syzygy.cc.
Referenced by init_tb().
num_dtm_
int lczero::SyzygyTablebaseImpl::num_dtm_ = 0 private
Definition at line 1493 of file syzygy.cc.
Referenced by init_tb(), and SyzygyTablebaseImpl().
num_dtz_
int lczero::SyzygyTablebaseImpl::num_dtz_ = 0 private
Definition at line 1494 of file syzygy.cc.
Referenced by init_tb(), and SyzygyTablebaseImpl().
num_pawn_entries_
int lczero::SyzygyTablebaseImpl::num_pawn_entries_ = 0 private
Definition at line 1491 of file syzygy.cc.
Referenced by init_tb(), and ~SyzygyTablebaseImpl().
num_piece_entries_
int lczero::SyzygyTablebaseImpl::num_piece_entries_ = 0 private
Definition at line 1490 of file syzygy.cc.
Referenced by init_tb(), and ~SyzygyTablebaseImpl().
num_wdl_
int lczero::SyzygyTablebaseImpl::num_wdl_ = 0 private
Definition at line 1492 of file syzygy.cc.
Referenced by init_tb(), and SyzygyTablebaseImpl().
paths_
std::string lczero::SyzygyTablebaseImpl::paths_ private
Definition at line 1488 of file syzygy.cc.
Referenced by name_for_tb(), SyzygyTablebaseImpl(), and ~SyzygyTablebaseImpl().
pawn_entries_
std::vector<PawnEntry> lczero::SyzygyTablebaseImpl::pawn_entries_ private
Definition at line 1497 of file syzygy.cc.
Referenced by init_tb(), and ~SyzygyTablebaseImpl().
piece_entries_
std::vector<PieceEntry> lczero::SyzygyTablebaseImpl::piece_entries_ private
Definition at line 1496 of file syzygy.cc.
Referenced by init_tb(), and ~SyzygyTablebaseImpl().
ready_mutex_
Mutex lczero::SyzygyTablebaseImpl::ready_mutex_ private
Definition at line 1487 of file syzygy.cc.
Referenced by probe_table().
tb_hash_
std::vector<TbHashEntry> lczero::SyzygyTablebaseImpl::tb_hash_ private
Definition at line 1498 of file syzygy.cc.
Referenced by add_to_hash(), probe_table(), and SyzygyTablebaseImpl().
The documentation for this class was generated from the following file:
src/syzygy/syzygy.cc