Leela Chess Zero: lczero::KingAttackInfo Class Reference
lczero::KingAttackInfo Class Reference
#include <board.h>
Public Member Functions
bool in_check () const
bool in_double_check () const
bool is_pinned (const Square square) const
bool is_on_attack_line (const Square square) const
Public Attributes
bool double_check_ = 0
BitBoard pinned_pieces_ = {0}
BitBoard attack_lines_ = {0}
Detailed Description
Definition at line 43 of file board.h.
Member Function Documentation
in_check()
bool lczero::KingAttackInfo::in_check () const inline
Definition at line 45 of file board.h.
References lczero::BitBoard::as_int(), and attack_lines_.
Referenced by lczero::ChessBoard::IsLegalMove().
in_double_check()
bool lczero::KingAttackInfo::in_double_check () const inline
Definition at line 46 of file board.h.
References double_check_.
Referenced by lczero::ChessBoard::IsLegalMove().
is_on_attack_line()
bool lczero::KingAttackInfo::is_on_attack_line (const Square square) const inline
Definition at line 50 of file board.h.
References attack_lines_, and lczero::BitBoard::get().
Referenced by lczero::ChessBoard::IsLegalMove().
is_pinned()
bool lczero::KingAttackInfo::is_pinned (const Square square) const inline
Definition at line 47 of file board.h.
References lczero::BitBoard::get(), and pinned_pieces_.
Referenced by lczero::ChessBoard::IsLegalMove().
Member Data Documentation
attack_lines_
BitBoard lczero::KingAttackInfo::attack_lines_ = {0}
Definition at line 56 of file board.h.
Referenced by lczero::ChessBoard::GenerateKingAttackInfo(), in_check(), and is_on_attack_line().
double_check_
bool lczero::KingAttackInfo::double_check_ = 0
Definition at line 54 of file board.h.
Referenced by lczero::ChessBoard::GenerateKingAttackInfo(), and in_double_check().
pinned_pieces_
BitBoard lczero::KingAttackInfo::pinned_pieces_ = {0}
Definition at line 55 of file board.h.
Referenced by lczero::ChessBoard::GenerateKingAttackInfo(), and is_pinned().
The documentation for this class was generated from the following file:
src/chess/board.h