Leela Chess Zero: lczero::CudaNetworkComputation< DataType > Class Template Reference
lczero::CudaNetworkComputation< DataType > Class Template Reference
CUDA network computation class.
Public Member Functions
CudaNetworkComputation (CudaNetwork< DataType > *network, bool wdl, bool moves_left)
Constructor.
~CudaNetworkComputation ()
void AddInput (InputPlanes &&input) override
Adds a sample (input planes) to the current batch.
void ComputeBlocking () override
Computes the network outputs for the current batch.
void CaptureGraph (std::unique_lock< std::mutex > &&lock={})
Captures the CUDA graph for the current batch.
int GetBatchSize () const override
Returns the number of samples in the current batch.
float GetQVal (int sample) const override
Retrieves the Q-value (expected game result) for a specific sample.
float GetDVal (int sample) const override
Retrieves the D-value (draw probability) for a specific sample.
float GetPVal (int sample, int move_id) const override
Retrieves the P-value (policy/move probability) for a specific move in a sample.
float GetMVal (int sample) const override
Retrieves the M-value (moves left) for a specific sample.
Public Member Functions inherited from lczero::NetworkComputation
virtual ~NetworkComputation ()=default
Private Attributes
std::unique_ptr< InputsOutputs< DataType > > inputs_outputs_
int batch_size_
bool wdl_
bool moves_left_
CudaNetwork< DataType > * network_
Detailed Description
template<typename DataType>
class lczero::CudaNetworkComputation< DataType >
CUDA network computation class.
Handles the execution of the network on CUDA.
Definition at line 134 of file network_cuda.cc.
Constructor & Destructor Documentation
CudaNetworkComputation()
template<typename DataType > lczero::CudaNetworkComputation< DataType >::CudaNetworkComputation (CudaNetwork< DataType > * network, bool wdl, bool moves_left)
Constructor.
Parameters
network Pointer to the CudaNetwork instance.
wdl Whether WDL (Win/Draw/Loss) output is enabled.
moves_left Whether moves left output is enabled.
Definition at line 1231 of file network_cuda.cc.
References lczero::CudaNetworkComputation< DataType >::batch_size_, lczero::CudaNetworkComputation< DataType >::inputs_outputs_, and lczero::CudaNetworkComputation< DataType >::network_.
~CudaNetworkComputation()
template<typename DataType > lczero::CudaNetworkComputation< DataType >::~CudaNetworkComputation ()
Definition at line 1239 of file network_cuda.cc.
References network_.
Member Function Documentation
AddInput()
template<typename DataType > void lczero::CudaNetworkComputation< DataType >::AddInput (InputPlanes && input) inline override virtual
Adds a sample (input planes) to the current batch.
Parameters
input Input planes for a single position.
Implements lczero::NetworkComputation.
Definition at line 146 of file network_cuda.cc.
References lczero::CudaNetworkComputation< DataType >::batch_size_, input, lczero::CudaNetworkComputation< DataType >::inputs_outputs_, lczero::kInputPlanes, and lczero::cudnn_backend::ToType().
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork().
CaptureGraph()
template<typename DataType > void lczero::CudaNetworkComputation< DataType >::CaptureGraph (std::unique_lock< std::mutex > && lock = {})
Captures the CUDA graph for the current batch.
Parameters
lock Optional lock to hold during capture.
Definition at line 1244 of file network_cuda.cc.
References CERR, and network_.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork().
ComputeBlocking()
template<typename DataType > void lczero::CudaNetworkComputation< DataType >::ComputeBlocking () override virtual
Computes the network outputs for the current batch.
This function triggers the forward pass on the GPU.
Implements lczero::NetworkComputation.
Definition at line 1262 of file network_cuda.cc.
References LCTRACE_FUNCTION_SCOPE, and network_.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork().
GetBatchSize()
template<typename DataType > int lczero::CudaNetworkComputation< DataType >::GetBatchSize () const inline override virtual
Returns the number of samples in the current batch.
Returns
Batch size.
Implements lczero::NetworkComputation.
Definition at line 172 of file network_cuda.cc.
References lczero::CudaNetworkComputation< DataType >::batch_size_.
GetDVal()
template<typename DataType > float lczero::CudaNetworkComputation< DataType >::GetDVal (int sample) const inline override virtual
Retrieves the D-value (draw probability) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The D-value.
Implements lczero::NetworkComputation.
Definition at line 185 of file network_cuda.cc.
References lczero::CudaNetworkComputation< DataType >::inputs_outputs_, and lczero::CudaNetworkComputation< DataType >::wdl_.
GetMVal()
template<typename DataType > float lczero::CudaNetworkComputation< DataType >::GetMVal (int sample) const inline override virtual
Retrieves the M-value (moves left) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The expected number of moves left.
Implements lczero::NetworkComputation.
Definition at line 201 of file network_cuda.cc.
References lczero::cudnn_backend::FromType(), lczero::CudaNetworkComputation< DataType >::inputs_outputs_, and lczero::CudaNetworkComputation< DataType >::moves_left_.
GetPVal()
template<typename DataType > float lczero::CudaNetworkComputation< DataType >::GetPVal (int sample, int move_id) const inline override virtual
Retrieves the P-value (policy/move probability) for a specific move in a sample.
Parameters
sample The index of the sample in the batch.
move_id The index of the move.
Returns
The P-value (probability) for the move.
Implements lczero::NetworkComputation.
Definition at line 196 of file network_cuda.cc.
References lczero::cudnn_backend::FromType(), lczero::CudaNetworkComputation< DataType >::inputs_outputs_, and lczero::cudnn_backend::kNumOutputPolicy.
GetQVal()
template<typename DataType > float lczero::CudaNetworkComputation< DataType >::GetQVal (int sample) const inline override virtual
Retrieves the Q-value (expected game result) for a specific sample.
Parameters
sample The index of the sample in the batch.
Returns
The Q-value (typically from -1.0 to 1.0).
Implements lczero::NetworkComputation.
Definition at line 174 of file network_cuda.cc.
References lczero::cudnn_backend::FromType(), lczero::CudaNetworkComputation< DataType >::inputs_outputs_, and lczero::CudaNetworkComputation< DataType >::wdl_.
Member Data Documentation
batch_size_
template<typename DataType > int lczero::CudaNetworkComputation< DataType >::batch_size_ private
Definition at line 211 of file network_cuda.cc.
Referenced by lczero::CudaNetworkComputation< DataType >::AddInput(), lczero::CudaNetworkComputation< DataType >::CudaNetworkComputation(), and lczero::CudaNetworkComputation< DataType >::GetBatchSize().
inputs_outputs_
template<typename DataType > std::unique_ptr<InputsOutputs<DataType> > lczero::CudaNetworkComputation< DataType >::inputs_outputs_ private
Definition at line 210 of file network_cuda.cc.
Referenced by lczero::CudaNetworkComputation< DataType >::AddInput(), lczero::CudaNetworkComputation< DataType >::CudaNetworkComputation(), lczero::CudaNetworkComputation< DataType >::GetDVal(), lczero::CudaNetworkComputation< DataType >::GetMVal(), lczero::CudaNetworkComputation< DataType >::GetPVal(), and lczero::CudaNetworkComputation< DataType >::GetQVal().
moves_left_
template<typename DataType > bool lczero::CudaNetworkComputation< DataType >::moves_left_ private
Definition at line 213 of file network_cuda.cc.
Referenced by lczero::CudaNetworkComputation< DataType >::GetMVal().
network_
template<typename DataType > CudaNetwork<DataType>* lczero::CudaNetworkComputation< DataType >::network_ private
Definition at line 215 of file network_cuda.cc.
Referenced by lczero::CudaNetworkComputation< DataType >::CudaNetworkComputation().
wdl_
template<typename DataType > bool lczero::CudaNetworkComputation< DataType >::wdl_ private
Definition at line 212 of file network_cuda.cc.
Referenced by lczero::CudaNetworkComputation< DataType >::GetDVal(), and lczero::CudaNetworkComputation< DataType >::GetQVal().
The documentation for this class was generated from the following file:
src/neural/backends/cuda/network_cuda.cc