Leela Chess Zero: lczero::python::Output Class Reference
lczero::python::Output Class Reference
#include <weights.h>
Public Member Functions
Output (const NetworkComputation &computation, int idx)
float q () const
float d () const
float m () const
std::vector< float > p_raw (const std::vector< int > &indicies)
std::vector< float > p_softmax (const std::vector< int > &indicies)
Private Attributes
float p_ [1858]
float q_
float d_
float m_
Detailed Description
Definition at line 130 of file weights.h.
Constructor & Destructor Documentation
Output()
lczero::python::Output::Output (const NetworkComputation & computation, int idx) inline
Definition at line 133 of file weights.h.
References d_, lczero::NetworkComputation::GetDVal(), lczero::NetworkComputation::GetMVal(), lczero::NetworkComputation::GetPVal(), lczero::NetworkComputation::GetQVal(), idx, m_, p_, and q_.
Member Function Documentation
d()
float lczero::python::Output::d () const inline
Definition at line 140 of file weights.h.
References d_.
m()
float lczero::python::Output::m () const inline
Definition at line 141 of file weights.h.
References m_.
p_raw()
std::vector< float > lczero::python::Output::p_raw (const std::vector< int > & indicies) inline
Definition at line 142 of file weights.h.
References idx, p_, and result.
Referenced by p_softmax().
p_softmax()
std::vector< float > lczero::python::Output::p_softmax (const std::vector< int > & indicies) inline
Definition at line 154 of file weights.h.
References lczero::FastExp(), and p_raw().
q()
float lczero::python::Output::q () const inline
Definition at line 139 of file weights.h.
References q_.
Member Data Documentation
d_
float lczero::python::Output::d_ private
Definition at line 175 of file weights.h.
Referenced by d(), and Output().
m_
float lczero::python::Output::m_ private
Definition at line 176 of file weights.h.
Referenced by m(), and Output().
p_
float lczero::python::Output::p_[1858] private
Definition at line 173 of file weights.h.
Referenced by Output(), and p_raw().
q_
float lczero::python::Output::q_ private
Definition at line 174 of file weights.h.
Referenced by Output(), and q().
The documentation for this class was generated from the following file:
python/weights.h