Leela Chess Zero: lczero::ConfigFile Class Reference
lczero::ConfigFile Class Reference
#include <configfile.h>
Public Member Functions
ConfigFile ()=delete
Static Public Member Functions
static bool Init ()
static const std::vector< std::string > & Arguments ()
static void PopulateOptions (OptionsParser *options)
Static Private Member Functions
static bool ParseFile (std::string &filename)
static std::string ProcessConfigFlag (const std::vector< std::string > &args)
Static Private Attributes
static std::vector< std::string > arguments_
Detailed Description
Definition at line 37 of file configfile.h.
Constructor & Destructor Documentation
ConfigFile()
lczero::ConfigFile::ConfigFile () delete
Member Function Documentation
Arguments()
static const std::vector< std::string > & lczero::ConfigFile::Arguments () inline static
Definition at line 45 of file configfile.h.
References arguments_.
Referenced by lczero::OptionsParser::ProcessAllFlags().
Init()
bool lczero::ConfigFile::Init () static
Definition at line 83 of file configfile.cc.
References lczero::CommandLine::Arguments(), arguments_, ParseFile(), and ProcessConfigFlag().
Referenced by lczero::RunEngine().
ParseFile()
bool lczero::ConfigFile::ParseFile (std::string & filename) static private
Definition at line 99 of file configfile.cc.
References arguments_, lczero::CommandLine::BinaryDirectory(), CERR, lczero::GetSystemConfigDirectoryList(), lczero::GetUserConfigDirectory(), input, and lczero::Trim().
Referenced by Init().
PopulateOptions()
void lczero::ConfigFile::PopulateOptions (OptionsParser * options) static
Definition at line 52 of file configfile.cc.
References lczero::OptionsParser::Add().
Referenced by lczero::RunEngine().
ProcessConfigFlag()
std::string lczero::ConfigFile::ProcessConfigFlag (const std::vector< std::string > & args) static private
Definition at line 58 of file configfile.cc.
Referenced by Init().
Member Data Documentation
arguments_
std::vector< std::string > lczero::ConfigFile::arguments_ static private
Definition at line 57 of file configfile.h.
Referenced by Arguments(), Init(), and ParseFile().
The documentation for this class was generated from the following files:
src/utils/configfile.h
src/utils/configfile.cc