Leela Chess Zero: lczero::NetworkFactory Class Reference
lczero::NetworkFactory Class Reference
Factory methods for creating Network instances.
#include <factory.h>
Classes
struct BackendConfiguration
Holds configuration for a specific backend instantiation.
struct Factory
class Register
Helper class for self-registering networks.
Public Types
using FactoryFunc = std::function< std::unique_ptr< Network >(const std::optional< WeightsFile > &, const OptionsDict &)>
Public Member Functions
std::vector< std::string > GetBackendsList () const
Returns a list of available backend names.
std::unique_ptr< Network > Create (const std::string &network, const std::optional< WeightsFile > &, const OptionsDict &options)
Creates a backend instance based on the provided configuration.
Static Public Member Functions
static NetworkFactory * Get ()
Retrieves the singleton instance of the NetworkFactory.
static std::unique_ptr< Network > LoadNetwork (const OptionsDict &options)
Helper function to load or reload a network based on options.
Private Member Functions
void RegisterNetwork (const std::string &name, FactoryFunc factory, int priority)
NetworkFactory ()
Private Attributes
std::vector< Factory > factories_
Friends
class Register
Detailed Description
Factory methods for creating Network instances.
This class manages the registration and creation of neural network backends. It follows the singleton pattern for global access to registered factories.
Definition at line 46 of file factory.h.
Member Typedef Documentation
FactoryFunc
using lczero::NetworkFactory::FactoryFunc = std::function<std::unique_ptr<Network>(const std::optional<WeightsFile>&, const OptionsDict&)>
Definition at line 48 of file factory.h.
Constructor & Destructor Documentation
NetworkFactory()
lczero::NetworkFactory::NetworkFactory () inline private
Definition at line 114 of file factory.h.
Member Function Documentation
Create()
std::unique_ptr< Network > lczero::NetworkFactory::Create (const std::string & network, const std::optional< WeightsFile > & weights, const OptionsDict & options)
Creates a backend instance based on the provided configuration.
Parameters
network The name of the network backend to create.
weights_file Optional weights file (if required).
options Additional options for the backend.
Returns
A unique pointer to the created Network instance.
Definition at line 70 of file factory.cc.
References CERR, and factories_.
Referenced by lczero::python::Backend::Backend(), LoadNetwork(), and lczero::MakeCudnnNetwork().
Get()
NetworkFactory * lczero::NetworkFactory::Get () static
Retrieves the singleton instance of the NetworkFactory.
Returns
A pointer to the global NetworkFactory.
Definition at line 40 of file factory.cc.
Referenced by lczero::python::Backend::available_backends(), lczero::python::Backend::Backend(), lczero::python::GetAvailableBackends(), LoadNetwork(), lczero::MakeCudnnNetwork(), and lczero::NetworkFactory::Register::Register().
GetBackendsList()
std::vector< std::string > lczero::NetworkFactory::GetBackendsList () const
Returns a list of available backend names.
Returns
A vector of backend names, sorted by priority (highest first).
Definition at line 56 of file factory.cc.
References factories_, and result.
Referenced by lczero::python::Backend::available_backends(), and lczero::python::GetAvailableBackends().
LoadNetwork()
std::unique_ptr< Network > lczero::NetworkFactory::LoadNetwork (const OptionsDict & options) static
Helper function to load or reload a network based on options.
Returns
A unique pointer to the new Network, or nullptr if configuration hasn't changed.
Definition at line 95 of file factory.cc.
References lczero::OptionsDict::AddSubdictFromString(), lczero::OptionsDict::CheckAllOptionsRead(), Create(), Get(), lczero::OptionsDict::Get(), lczero::SharedBackendParams::kBackendId, lczero::SharedBackendParams::kBackendOptionsId, lczero::SharedBackendParams::kWeightsId, lczero::LoadWeights(), and ptr.
RegisterNetwork()
void lczero::NetworkFactory::RegisterNetwork (const std::string & name, FactoryFunc factory, int priority) private
Definition at line 50 of file factory.cc.
References factories_, and name.
Referenced by lczero::NetworkFactory::Register::Register().
Friends And Related Symbol Documentation
Register
friend class Register friend
Definition at line 131 of file factory.h.
Member Data Documentation
factories_
std::vector<Factory> lczero::NetworkFactory::factories_ private
Definition at line 130 of file factory.h.
Referenced by Create(), GetBackendsList(), and RegisterNetwork().
The documentation for this class was generated from the following files:
src/neural/factory.h
src/neural/factory.cc