Leela Chess Zero: lczero::classic::VisitedNode_Iterator< is_const > Class Template Reference
lczero::classic::VisitedNode_Iterator< is_const > Class Template Reference
#include <node.h>
Public Member Functions
VisitedNode_Iterator ()
VisitedNode_Iterator (const Node &parent_node, Node *child_ptr)
bool operator== (const VisitedNode_Iterator< is_const > &other) const
bool operator!= (const VisitedNode_Iterator< is_const > &other) const
VisitedNode_Iterator< is_const > begin ()
VisitedNode_Iterator< is_const > end ()
void operator++ ()
Node * operator* ()
Private Attributes
Node * node_ptr_ = nullptr
uint16_t current_idx_ = 0
uint16_t total_count_ = 0
bool solid_ = false
Detailed Description
template<bool is_const>
class lczero::classic::VisitedNode_Iterator< is_const >
Definition at line 761 of file node.h.
Constructor & Destructor Documentation
VisitedNode_Iterator() [1/2]
template<bool is_const> lczero::classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator () inline
Definition at line 764 of file node.h.
VisitedNode_Iterator() [2/2]
template<bool is_const> lczero::classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator (const Node & parent_node, Node * child_ptr) inline
Definition at line 768 of file node.h.
References lczero::classic::Node::GetN(), lczero::classic::VisitedNode_Iterator< is_const >::node_ptr_, and lczero::classic::VisitedNode_Iterator< is_const >::operator++().
Member Function Documentation
begin()
template<bool is_const> VisitedNode_Iterator< is_const > lczero::classic::VisitedNode_Iterator< is_const >::begin () inline
Definition at line 785 of file node.h.
end()
template<bool is_const> VisitedNode_Iterator< is_const > lczero::classic::VisitedNode_Iterator< is_const >::end () inline
Definition at line 786 of file node.h.
operator!=()
template<bool is_const> bool lczero::classic::VisitedNode_Iterator< is_const >::operator!= (const VisitedNode_Iterator< is_const > & other) const inline
Definition at line 780 of file node.h.
References lczero::classic::VisitedNode_Iterator< is_const >::node_ptr_.
operator*()
template<bool is_const> Node * lczero::classic::VisitedNode_Iterator< is_const >::operator* () inline
Definition at line 821 of file node.h.
References lczero::classic::VisitedNode_Iterator< is_const >::current_idx_, lczero::classic::VisitedNode_Iterator< is_const >::node_ptr_, and lczero::classic::VisitedNode_Iterator< is_const >::solid_.
operator++()
template<bool is_const> void lczero::classic::VisitedNode_Iterator< is_const >::operator++ () inline
Definition at line 790 of file node.h.
References lczero::classic::VisitedNode_Iterator< is_const >::current_idx_, lczero::classic::Node::GetN(), lczero::classic::Node::GetNInFlight(), lczero::classic::VisitedNode_Iterator< is_const >::node_ptr_, lczero::classic::Node::sibling_, lczero::classic::VisitedNode_Iterator< is_const >::solid_, and lczero::classic::VisitedNode_Iterator< is_const >::total_count_.
Referenced by lczero::classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
operator==()
template<bool is_const> bool lczero::classic::VisitedNode_Iterator< is_const >::operator== (const VisitedNode_Iterator< is_const > & other) const inline
Definition at line 777 of file node.h.
References lczero::classic::VisitedNode_Iterator< is_const >::node_ptr_.
Member Data Documentation
current_idx_
template<bool is_const> uint16_t lczero::classic::VisitedNode_Iterator< is_const >::current_idx_ = 0 private
Definition at line 832 of file node.h.
Referenced by lczero::classic::VisitedNode_Iterator< is_const >::operator*(), and lczero::classic::VisitedNode_Iterator< is_const >::operator++().
node_ptr_
template<bool is_const> Node* lczero::classic::VisitedNode_Iterator< is_const >::node_ptr_ = nullptr private
Definition at line 831 of file node.h.
Referenced by lczero::classic::VisitedNode_Iterator< is_const >::operator!=(), lczero::classic::VisitedNode_Iterator< is_const >::operator*(), lczero::classic::VisitedNode_Iterator< is_const >::operator++(), lczero::classic::VisitedNode_Iterator< is_const >::operator==(), and lczero::classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
solid_
template<bool is_const> bool lczero::classic::VisitedNode_Iterator< is_const >::solid_ = false private
Definition at line 834 of file node.h.
Referenced by lczero::classic::VisitedNode_Iterator< is_const >::operator*(), and lczero::classic::VisitedNode_Iterator< is_const >::operator++().
total_count_
template<bool is_const> uint16_t lczero::classic::VisitedNode_Iterator< is_const >::total_count_ = 0 private
Definition at line 833 of file node.h.
Referenced by lczero::classic::VisitedNode_Iterator< is_const >::operator++().
The documentation for this class was generated from the following file:
src/search/classic/node.h