Leela Chess Zero: lczero::classic::Node Class Reference
lczero::classic::Node Class Reference
#include <node.h>
Public Types
enum class Terminal : uint8_t { NonTerminal , EndOfGame , Tablebase , TwoFold }
using Iterator = Edge_Iterator< false >
using ConstIterator = Edge_Iterator< true >
typedef std::pair< GameResult, GameResult > Bounds
Public Member Functions
Node (Node *parent, uint16_t index)
Node (Node &&move_from)=default
Node & operator= (Node &&move_from)=default
Node * CreateSingleChildNode (Move m)
void CreateEdges (const MoveList &moves)
Node * GetParent () const
bool HasChildren () const
float GetVisitedPolicy () const
uint32_t GetN () const
uint32_t GetNInFlight () const
uint32_t GetChildrenVisits () const
int GetNStarted () const
float GetQ (float draw_score) const
float GetWL () const
float GetD () const
float GetM () const
bool IsTerminal () const
bool IsTbTerminal () const
bool IsTwoFoldTerminal () const
Bounds GetBounds () const
uint8_t GetNumEdges () const
void CopyPolicy (int max_needed, float *output) const
void MakeTerminal (GameResult result, float plies_left=0.0f, Terminal type=Terminal::EndOfGame)
void MakeNotTerminal ()
void SetBounds (GameResult lower, GameResult upper)
bool TryStartScoreUpdate ()
void CancelScoreUpdate (int multivisit)
void FinalizeScoreUpdate (float v, float d, float m, int multivisit)
void AdjustForTerminal (float v, float d, float m, int multivisit)
void RevertTerminalVisits (float v, float d, float m, int multivisit)
void IncrementNInFlight (int multivisit)
void UpdateMaxDepth (int depth)
bool UpdateFullDepth (uint16_t *depth)
ConstIterator Edges () const
Iterator Edges ()
VisitedNode_Iterator< true > VisitedNodes () const
VisitedNode_Iterator< false > VisitedNodes ()
void ReleaseChildren ()
void ReleaseChildrenExceptOne (Node *node)
Edge * GetEdgeToNode (const Node *node) const
Edge * GetOwnEdge () const
std::string DebugString () const
bool MakeSolid ()
void SortEdges ()
uint16_t Index () const
~Node ()
Private Member Functions
void UpdateChildrenParents ()
Private Attributes
double wl_ = 0.0f
std::unique_ptr< Edge[]> edges_
Node * parent_ = nullptr
std::unique_ptr< Node > child_
std::unique_ptr< Node > sibling_
float d_ = 0.0f
float m_ = 0.0f
uint32_t n_ = 0
uint32_t n_in_flight_ = 0
uint16_t index_
uint8_t num_edges_ = 0
Terminal terminal_type_: 2
GameResult lower_bound_: 2
GameResult upper_bound_: 2
bool solid_children_: 1
Friends
class NodeTree
class Edge_Iterator< true >
class Edge_Iterator< false >
class Edge
class VisitedNode_Iterator< true >
class VisitedNode_Iterator< false >
Detailed Description
Definition at line 127 of file node.h.
Member Typedef Documentation
Bounds
typedef std::pair<GameResult, GameResult> lczero::classic::Node::Bounds
Definition at line 179 of file node.h.
ConstIterator
using lczero::classic::Node::ConstIterator = Edge_Iterator<true>
Definition at line 130 of file node.h.
Iterator
using lczero::classic::Node::Iterator = Edge_Iterator<false>
Definition at line 129 of file node.h.
Member Enumeration Documentation
Terminal
enum class lczero::classic::Node::Terminal : uint8_t strong
Enumerator
NonTerminal
EndOfGame
Tablebase
TwoFold
Definition at line 132 of file node.h.
Constructor & Destructor Documentation
Node() [1/2]
lczero::classic::Node::Node (Node * parent, uint16_t index) inline
Definition at line 135 of file node.h.
Node() [2/2]
lczero::classic::Node::Node (Node && move_from) default
~Node()
lczero::classic::Node::~Node () inline
Definition at line 262 of file node.h.
References child_, num_edges_, and solid_children_.
Member Function Documentation
AdjustForTerminal()
void lczero::classic::Node::AdjustForTerminal (float v, float d, float m, int multivisit)
Definition at line 368 of file node.cc.
References d, d_, m, m_, n_, and wl_.
CancelScoreUpdate()
void lczero::classic::Node::CancelScoreUpdate (int multivisit)
Definition at line 354 of file node.cc.
References n_in_flight_.
Referenced by lczero::classic::Search::CancelSharedCollisions(), and lczero::classic::SearchWorker::GatherMinibatch().
CopyPolicy()
void lczero::classic::Node::CopyPolicy (int max_needed, float * output) const inline
Definition at line 184 of file node.h.
References edges_, num_edges_, and output.
CreateEdges()
void lczero::classic::Node::CreateEdges (const MoveList & moves)
Definition at line 205 of file node.cc.
References child_, edges_, lczero::classic::Edge::FromMovelist(), moves, and num_edges_.
Referenced by lczero::classic::SearchWorker::ExtendNode().
CreateSingleChildNode()
Node * lczero::classic::Node::CreateSingleChildNode (Move m)
Definition at line 196 of file node.cc.
References child_, edges_, lczero::classic::Edge::FromMovelist(), and num_edges_.
Referenced by lczero::classic::NodeTree::MakeMove().
DebugString()
std::string lczero::classic::Node::DebugString () const
Definition at line 233 of file node.cc.
References child_, index_, lower_bound_, n_, n_in_flight_, num_edges_, parent_, sibling_, solid_children_, terminal_type_, upper_bound_, and wl_.
Referenced by lczero::classic::EdgeAndNode::DebugString().
Edges() [1/2]
Node::Iterator lczero::classic::Node::Edges ()
Definition at line 215 of file node.cc.
References child_, and solid_children_.
Edges() [2/2]
Node::ConstIterator lczero::classic::Node::Edges () const
Definition at line 212 of file node.cc.
References child_, and solid_children_.
Referenced by lczero::V6TrainingDataArray::Add(), lczero::classic::SearchWorker::FetchSingleNodeResult(), lczero::PolicyEvaluator::Gather(), lczero::ValueEvaluator::Gather(), lczero::classic::Search::GetBestChildrenNoTemperature(), lczero::classic::Search::GetVerboseStats(), lczero::classic::NodeTree::MakeMove(), MakeNotTerminal(), and lczero::classic::Search::SendMovesStats().
FinalizeScoreUpdate()
void lczero::classic::Node::FinalizeScoreUpdate (float v, float d, float m, int multivisit)
Definition at line 356 of file node.cc.
References d, d_, m, m_, n_, n_in_flight_, and wl_.
GetBounds()
Bounds lczero::classic::Node::GetBounds () const inline
Definition at line 180 of file node.h.
References lower_bound_, and upper_bound_.
Referenced by lczero::classic::EdgeAndNode::GetBounds().
GetChildrenVisits()
uint32_t lczero::classic::Node::GetChildrenVisits () const inline
Definition at line 165 of file node.h.
References n_.
Referenced by lczero::V6TrainingDataArray::Add(), and lczero::classic::Search::GetVerboseStats().
GetD()
float lczero::classic::Node::GetD () const inline
Definition at line 172 of file node.h.
References d_.
Referenced by lczero::V6TrainingDataArray::Add(), lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth(), lczero::classic::SearchWorker::FetchSingleNodeResult(), lczero::classic::Search::GetBestEval(), lczero::classic::EdgeAndNode::GetD(), and lczero::classic::Search::SendUciInfo().
GetEdgeToNode()
Edge * lczero::classic::Node::GetEdgeToNode (const Node * node) const
Definition at line 225 of file node.cc.
References edges_, index_, num_edges_, and parent_.
Referenced by GetOwnEdge(), and GetVisitedPolicy().
GetM()
float lczero::classic::Node::GetM () const inline
Definition at line 173 of file node.h.
References m_.
Referenced by lczero::V6TrainingDataArray::Add(), lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth(), lczero::classic::SearchWorker::FetchSingleNodeResult(), lczero::classic::Search::GetBestEval(), lczero::classic::EdgeAndNode::GetM(), and lczero::classic::Search::SendUciInfo().
GetN()
uint32_t lczero::classic::Node::GetN () const inline
Definition at line 163 of file node.h.
References n_.
Referenced by lczero::V6TrainingDataArray::Add(), lczero::classic::SearchWorker::DoBackupUpdateSingleNode(), lczero::classic::Search::EnsureBestMoveKnown(), lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth(), lczero::classic::Search::GetBestChildrenNoTemperature(), lczero::classic::EdgeAndNode::GetD(), lczero::classic::EdgeAndNode::GetM(), lczero::classic::EdgeAndNode::GetN(), lczero::classic::EdgeAndNode::GetQ(), lczero::classic::Search::GetVerboseStats(), lczero::classic::EdgeAndNode::GetWL(), MakeSolid(), lczero::classic::VisitedNode_Iterator< is_const >::operator++(), lczero::classic::SearchWorker::PickNodesToExtendTask(), and lczero::classic::VisitedNode_Iterator< is_const >::VisitedNode_Iterator().
GetNInFlight()
uint32_t lczero::classic::Node::GetNInFlight () const inline
Definition at line 164 of file node.h.
References n_in_flight_.
Referenced by lczero::classic::EdgeAndNode::GetNInFlight(), lczero::classic::Search::GetVerboseStats(), MakeSolid(), and lczero::classic::VisitedNode_Iterator< is_const >::operator++().
GetNStarted()
int lczero::classic::Node::GetNStarted () const inline
Definition at line 167 of file node.h.
References n_, and n_in_flight_.
Referenced by lczero::classic::EdgeAndNode::GetNStarted(), and lczero::classic::SearchWorker::PrefetchIntoCache().
GetNumEdges()
uint8_t lczero::classic::Node::GetNumEdges () const inline
Definition at line 181 of file node.h.
References num_edges_.
Referenced by lczero::V6TrainingDataArray::Add(), lczero::ValueEvaluator::Gather(), and lczero::classic::Search::GetVerboseStats().
GetOwnEdge()
Edge * lczero::classic::Node::GetOwnEdge () const
Definition at line 231 of file node.cc.
References GetEdgeToNode(), and GetParent().
Referenced by MakeTerminal().
GetParent()
Node * lczero::classic::Node::GetParent () const inline
Definition at line 156 of file node.h.
References parent_.
Referenced by lczero::classic::Search::CancelSharedCollisions(), lczero::classic::SearchWorker::DoBackupUpdateSingleNode(), lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth(), lczero::classic::SearchWorker::ExtendNode(), lczero::classic::SearchWorker::GatherMinibatch(), lczero::SelfPlayGame::GetMoves(), lczero::MultiSelfPlayGames::GetMoves(), GetOwnEdge(), lczero::classic::Search::GetPositionHistoryAtNode(), lczero::classic::Search::GetVerboseStats(), MakeTerminal(), and lczero::classic::NodeTree::TrimTreeAtHead().
GetQ()
float lczero::classic::Node::GetQ (float draw_score) const inline
Definition at line 168 of file node.h.
References d_, and wl_.
Referenced by lczero::classic::EdgeAndNode::GetQ(), lczero::classic::Search::GetVerboseStats(), and lczero::classic::Search::SendUciInfo().
GetVisitedPolicy()
float lczero::classic::Node::GetVisitedPolicy () const
Definition at line 219 of file node.cc.
References GetEdgeToNode(), lczero::classic::Edge::GetP(), and VisitedNodes().
Referenced by lczero::classic::Search::GetVerboseStats().
GetWL()
float lczero::classic::Node::GetWL () const inline
Definition at line 171 of file node.h.
References wl_.
Referenced by lczero::V6TrainingDataArray::Add(), lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth(), lczero::classic::SearchWorker::FetchSingleNodeResult(), lczero::classic::Search::GetBestEval(), lczero::classic::Search::GetVerboseStats(), lczero::classic::EdgeAndNode::GetWL(), and lczero::classic::Search::SendUciInfo().
HasChildren()
bool lczero::classic::Node::HasChildren () const inline
Definition at line 159 of file node.h.
References edges_.
Referenced by lczero::classic::Search::EnsureBestMoveKnown(), and lczero::classic::Search::GetBestEval().
IncrementNInFlight()
void lczero::classic::Node::IncrementNInFlight (int multivisit) inline
Definition at line 219 of file node.h.
References n_in_flight_.
Referenced by lczero::classic::SearchWorker::GatherMinibatch(), and lczero::classic::SearchWorker::PickNodesToExtendTask().
Index()
uint16_t lczero::classic::Node::Index () const inline
Definition at line 260 of file node.h.
References index_.
IsTbTerminal()
bool lczero::classic::Node::IsTbTerminal () const inline
Definition at line 177 of file node.h.
References Tablebase, and terminal_type_.
Referenced by lczero::classic::EdgeAndNode::IsTbTerminal().
IsTerminal()
bool lczero::classic::Node::IsTerminal () const inline
Definition at line 176 of file node.h.
References NonTerminal, and terminal_type_.
Referenced by lczero::classic::SearchWorker::NodeToProcess::CanEvalOutOfOrder(), lczero::classic::SearchWorker::DoBackupUpdateSingleNode(), lczero::classic::SearchWorker::NodeToProcess::IsExtendable(), lczero::classic::EdgeAndNode::IsTerminal(), lczero::classic::NodeTree::MakeMove(), MakeSolid(), and lczero::classic::SearchWorker::PickNodesToExtendTask().
IsTwoFoldTerminal()
bool lczero::classic::Node::IsTwoFoldTerminal () const inline
Definition at line 178 of file node.h.
References terminal_type_, and TwoFold.
Referenced by lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth().
MakeNotTerminal()
void lczero::classic::Node::MakeNotTerminal ()
Definition at line 319 of file node.cc.
References d_, Edges(), edges_, n_, NonTerminal, terminal_type_, and wl_.
Referenced by lczero::classic::SearchWorker::EnsureNodeTwoFoldCorrectForDepth(), and lczero::classic::NodeTree::MakeMove().
MakeSolid()
bool lczero::classic::Node::MakeSolid ()
Definition at line 245 of file node.cc.
References child_, GetN(), GetNInFlight(), IsTerminal(), num_edges_, sibling_, and solid_children_.
MakeTerminal()
void lczero::classic::Node::MakeTerminal (GameResult result, float plies_left = 0.0f, Terminal type = Terminal::EndOfGame)
Definition at line 300 of file node.cc.
References lczero::BLACK_WON, d_, lczero::DRAW, GetOwnEdge(), GetParent(), m_, result, SetBounds(), lczero::classic::Edge::SetP(), terminal_type_, TwoFold, type, lczero::WHITE_WON, and wl_.
Referenced by lczero::classic::SearchWorker::ExtendNode().
operator=()
Node & lczero::classic::Node::operator= (Node && move_from) default
ReleaseChildren()
void lczero::classic::Node::ReleaseChildren ()
Definition at line 409 of file node.cc.
References child_, num_edges_, and solid_children_.
Referenced by lczero::classic::NodeTree::TrimTreeAtHead().
ReleaseChildrenExceptOne()
void lczero::classic::Node::ReleaseChildrenExceptOne (Node * node)
Definition at line 413 of file node.cc.
References child_, edges_, index_, num_edges_, and solid_children_.
Referenced by lczero::classic::NodeTree::MakeMove().
RevertTerminalVisits()
void lczero::classic::Node::RevertTerminalVisits (float v, float d, float m, int multivisit)
Definition at line 375 of file node.cc.
References d, d_, m, m_, n_, and wl_.
SetBounds()
void lczero::classic::Node::SetBounds (GameResult lower, GameResult upper)
Definition at line 343 of file node.cc.
References lower_bound_, and upper_bound_.
Referenced by MakeTerminal().
SortEdges()
void lczero::classic::Node::SortEdges ()
Definition at line 291 of file node.cc.
References child_, edges_, and num_edges_.
Referenced by lczero::classic::SearchWorker::FetchSingleNodeResult().
TryStartScoreUpdate()
bool lczero::classic::Node::TryStartScoreUpdate ()
Definition at line 348 of file node.cc.
References n_, and n_in_flight_.
Referenced by lczero::classic::SearchWorker::PickNodesToExtendTask().
UpdateChildrenParents()
void lczero::classic::Node::UpdateChildrenParents () private
Definition at line 394 of file node.cc.
References child_, num_edges_, parent_, sibling_, and solid_children_.
UpdateFullDepth()
bool lczero::classic::Node::UpdateFullDepth (uint16_t * depth)
UpdateMaxDepth()
void lczero::classic::Node::UpdateMaxDepth (int depth)
VisitedNodes() [1/2]
VisitedNode_Iterator< false > lczero::classic::Node::VisitedNodes () inline
Definition at line 632 of file node.h.
References child_.
VisitedNodes() [2/2]
VisitedNode_Iterator< true > lczero::classic::Node::VisitedNodes () const inline
Definition at line 629 of file node.h.
References child_.
Referenced by GetVisitedPolicy().
Friends And Related Symbol Documentation
Edge
friend class Edge friend
Definition at line 336 of file node.h.
Edge_Iterator< false >
friend class Edge_Iterator< false > friend
Definition at line 333 of file node.h.
Edge_Iterator< true >
friend class Edge_Iterator< true > friend
Definition at line 333 of file node.h.
NodeTree
friend class NodeTree friend
Definition at line 333 of file node.h.
VisitedNode_Iterator< false >
friend class VisitedNode_Iterator< false > friend
Definition at line 336 of file node.h.
VisitedNode_Iterator< true >
friend class VisitedNode_Iterator< true > friend
Definition at line 336 of file node.h.
Member Data Documentation
child_
std::unique_ptr<Node> lczero::classic::Node::child_ private
Definition at line 297 of file node.h.
Referenced by CreateEdges(), CreateSingleChildNode(), DebugString(), lczero::classic::Edge_Iterator< is_const >::Edge_Iterator(), Edges(), Edges(), lczero::classic::NodeTree::MakeMove(), MakeSolid(), ReleaseChildren(), ReleaseChildrenExceptOne(), SortEdges(), UpdateChildrenParents(), VisitedNodes(), VisitedNodes(), and ~Node().
d_
float lczero::classic::Node::d_ = 0.0f private
Definition at line 305 of file node.h.
Referenced by AdjustForTerminal(), FinalizeScoreUpdate(), GetD(), GetQ(), MakeNotTerminal(), MakeTerminal(), and RevertTerminalVisits().
edges_
std::unique_ptr<Edge[]> lczero::classic::Node::edges_ private
Definition at line 292 of file node.h.
Referenced by CopyPolicy(), CreateEdges(), CreateSingleChildNode(), GetEdgeToNode(), HasChildren(), MakeNotTerminal(), ReleaseChildrenExceptOne(), and SortEdges().
index_
uint16_t lczero::classic::Node::index_ private
Definition at line 317 of file node.h.
Referenced by DebugString(), GetEdgeToNode(), Index(), ReleaseChildrenExceptOne(), and lczero::classic::NodeTree::TrimTreeAtHead().
lower_bound_
GameResult lczero::classic::Node::lower_bound_ private
Definition at line 327 of file node.h.
Referenced by DebugString(), GetBounds(), and SetBounds().
m_
float lczero::classic::Node::m_ = 0.0f private
Definition at line 307 of file node.h.
Referenced by AdjustForTerminal(), FinalizeScoreUpdate(), GetM(), MakeTerminal(), and RevertTerminalVisits().
n_
uint32_t lczero::classic::Node::n_ = 0 private
Definition at line 309 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), FinalizeScoreUpdate(), GetChildrenVisits(), GetN(), GetNStarted(), MakeNotTerminal(), RevertTerminalVisits(), and TryStartScoreUpdate().
n_in_flight_
uint32_t lczero::classic::Node::n_in_flight_ = 0 private
Definition at line 313 of file node.h.
Referenced by CancelScoreUpdate(), DebugString(), FinalizeScoreUpdate(), GetNInFlight(), GetNStarted(), IncrementNInFlight(), and TryStartScoreUpdate().
num_edges_
uint8_t lczero::classic::Node::num_edges_ = 0 private
Definition at line 321 of file node.h.
Referenced by CopyPolicy(), CreateEdges(), CreateSingleChildNode(), DebugString(), GetEdgeToNode(), GetNumEdges(), MakeSolid(), ReleaseChildren(), ReleaseChildrenExceptOne(), SortEdges(), UpdateChildrenParents(), and ~Node().
parent_
Node* lczero::classic::Node::parent_ = nullptr private
Definition at line 294 of file node.h.
Referenced by DebugString(), GetEdgeToNode(), GetParent(), and UpdateChildrenParents().
sibling_
std::unique_ptr<Node> lczero::classic::Node::sibling_ private
Definition at line 300 of file node.h.
Referenced by lczero::classic::Edge_Iterator< is_const >::Actualize(), DebugString(), MakeSolid(), lczero::classic::VisitedNode_Iterator< is_const >::operator++(), lczero::classic::NodeTree::TrimTreeAtHead(), and UpdateChildrenParents().
solid_children_
bool lczero::classic::Node::solid_children_ private
Definition at line 330 of file node.h.
Referenced by DebugString(), Edges(), Edges(), MakeSolid(), ReleaseChildren(), ReleaseChildrenExceptOne(), UpdateChildrenParents(), and ~Node().
terminal_type_
Terminal lczero::classic::Node::terminal_type_ private
Definition at line 325 of file node.h.
Referenced by DebugString(), IsTbTerminal(), IsTerminal(), IsTwoFoldTerminal(), MakeNotTerminal(), and MakeTerminal().
upper_bound_
GameResult lczero::classic::Node::upper_bound_ private
Definition at line 328 of file node.h.
Referenced by DebugString(), GetBounds(), and SetBounds().
wl_
double lczero::classic::Node::wl_ = 0.0f private
Definition at line 288 of file node.h.
Referenced by AdjustForTerminal(), DebugString(), FinalizeScoreUpdate(), GetQ(), GetWL(), MakeNotTerminal(), MakeTerminal(), and RevertTerminalVisits().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/classic/node.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/search/classic/node.cc