Leela Chess Zero: lczero::dag_classic::NodeTree Class Reference
lczero::dag_classic::NodeTree Class Reference
Manages the game tree (or DAG) for the search.
#include <node.h>
Public Member Functions
~NodeTree ()
void MakeMove (Move move)
Advances the current state of the game tree by one move.
void TrimTreeAtHead ()
Reinitializes the tree at the current head position.
bool ResetToPosition (const std::string &starting_fen, const std::vector< std::string > &moves)
Resets the tree to a specific position defined by FEN and moves.
bool ResetToPosition (const GameState &pos)
Resets to a specific GameState.
const Position & HeadPosition () const
Returns the position at the current head of the tree.
int GetPlyCount () const
bool IsBlackToMove () const
Node * GetCurrentHead () const
Node * GetGameBeginNode () const
const PositionHistory & GetPositionHistory () const
const std::vector< Move > & GetMoves () const
Private Member Functions
void DeallocateTree ()
Private Attributes
Node * current_head_ = nullptr
std::unique_ptr< Node > gamebegin_node_
PositionHistory history_
std::vector< Move > moves_
Detailed Description
Manages the game tree (or DAG) for the search.
This class is responsible for the overall structure of the search tree, including the current root (head), the game history, and the transition between moves. It handles the logic for reusing the tree when moves are made or when the position is reset (transposition handling).
Definition at line 1129 of file node.h.
Constructor & Destructor Documentation
~NodeTree()
lczero::dag_classic::NodeTree::~NodeTree ()
Definition at line 667 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::Instance().
Member Function Documentation
DeallocateTree()
void lczero::dag_classic::NodeTree::DeallocateTree () private
Definition at line 751 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::AddToGcQueue(), and lczero::dag_classic::NodeGarbageCollector::Instance().
GetCurrentHead()
Node * lczero::dag_classic::NodeTree::GetCurrentHead () const inline
Definition at line 1163 of file node.h.
References current_head_.
GetGameBeginNode()
Node * lczero::dag_classic::NodeTree::GetGameBeginNode () const inline
Definition at line 1164 of file node.h.
References gamebegin_node_.
GetMoves()
const std::vector< Move > & lczero::dag_classic::NodeTree::GetMoves () const inline
Definition at line 1166 of file node.h.
References moves_.
GetPlyCount()
int lczero::dag_classic::NodeTree::GetPlyCount () const inline
Definition at line 1161 of file node.h.
References lczero::Position::GetGamePly(), and HeadPosition().
GetPositionHistory()
const PositionHistory & lczero::dag_classic::NodeTree::GetPositionHistory () const inline
Definition at line 1165 of file node.h.
References history_.
HeadPosition()
const Position & lczero::dag_classic::NodeTree::HeadPosition () const inline
Returns the position at the current head of the tree.
Definition at line 1160 of file node.h.
References history_, and lczero::PositionHistory::Last().
Referenced by GetPlyCount(), and IsBlackToMove().
IsBlackToMove()
bool lczero::dag_classic::NodeTree::IsBlackToMove () const inline
Definition at line 1162 of file node.h.
References HeadPosition(), and lczero::Position::IsBlackToMove().
MakeMove()
void lczero::dag_classic::NodeTree::MakeMove (Move move)
Advances the current state of the game tree by one move.
Adds a move to current_head_.
Updates the current head of the tree to the child corresponding to the given move. If the child does not exist, it creates a new one. Also updates the internal position history.
Parameters
move The move to apply.
Definition at line 676 of file node.cc.
References lczero::dag_classic::Node::CreateSingleChildNode(), lczero::dag_classic::Node::GetChild(), lczero::dag_classic::Node::IsTerminal(), lczero::dag_classic::Node::MakeNotTerminal(), and moves_.
ResetToPosition() [1/2]
bool lczero::dag_classic::NodeTree::ResetToPosition (const GameState & pos)
Resets to a specific GameState.
Sets the position in the tree, trying to reuse the tree.
Definition at line 705 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::Instance(), m, lczero::GameState::moves, moves_, lczero::dag_classic::NodeGarbageCollector::NotifyThreadGoingSleep(), and lczero::GameState::startpos.
ResetToPosition() [2/2]
bool lczero::dag_classic::NodeTree::ResetToPosition (const std::string & starting_fen, const std::vector< std::string > & moves)
Resets the tree to a specific position defined by FEN and moves.
Attempts to reuse the existing tree structure if the new position is an extension or a known transposition of the current state. This preserves statistical information (visits, values) for the relevant nodes.
Parameters
starting_fen FEN of game start.
moves Sequence of moves from the start.
Returns
True if tree reuse (same game lineage) was possible, False otherwise.
Definition at line 736 of file node.cc.
References lczero::ChessBoard::ApplyMove(), lczero::Position::FromFen(), lczero::Position::GetBoard(), m, lczero::ChessBoard::Mirror(), lczero::GameState::moves, moves, lczero::ChessBoard::ParseMove(), and lczero::GameState::startpos.
TrimTreeAtHead()
void lczero::dag_classic::NodeTree::TrimTreeAtHead ()
Reinitializes the tree at the current head position.
Resets the current head to ensure it doesn't carry over details from a previous search.
Effectively disconnects the current head from previous history in terms of tree structure, allowing for a fresh search from this position without carrying over potential baggage from previous searches, while maintaining the position itself.
Definition at line 698 of file node.cc.
References lczero::dag_classic::NodeGarbageCollector::Instance(), lczero::dag_classic::NodeGarbageCollector::NotifyThreadGoingSleep(), and lczero::dag_classic::Node::Trim().
Member Data Documentation
current_head_
Node* lczero::dag_classic::NodeTree::current_head_ = nullptr private
Definition at line 1171 of file node.h.
Referenced by GetCurrentHead().
gamebegin_node_
std::unique_ptr<Node> lczero::dag_classic::NodeTree::gamebegin_node_ private
Definition at line 1173 of file node.h.
Referenced by GetGameBeginNode().
history_
PositionHistory lczero::dag_classic::NodeTree::history_ private
Definition at line 1174 of file node.h.
Referenced by GetPositionHistory(), and HeadPosition().
moves_
std::vector<Move> lczero::dag_classic::NodeTree::moves_ private
Definition at line 1175 of file node.h.
Referenced by GetMoves().
The documentation for this class was generated from the following files:
search/dag_classic/node.h
search/dag_classic/node.cc