Leela Chess Zero: lczero::CommandLine Class Reference
lczero::CommandLine Class Reference
#include <commandline.h>
Public Member Functions
CommandLine ()=delete
Static Public Member Functions
static void Init (int argc, const char **argv)
static const std::string & BinaryName ()
static std::string BinaryDirectory ()
static bool ConsumeCommand (std::string_view command)
static const std::vector< std::string > & Arguments ()
static void RegisterMode (const std::string &mode, const std::string &description)
static const std::vector< std::pair< std::string, std::string > > & GetModes ()
Static Private Attributes
static std::string binary_
static std::vector< std::string > arguments_
static std::vector< std::pair< std::string, std::string > > modes_
Detailed Description
Definition at line 35 of file commandline.h.
Constructor & Destructor Documentation
CommandLine()
lczero::CommandLine::CommandLine () delete
Member Function Documentation
Arguments()
static const std::vector< std::string > & lczero::CommandLine::Arguments () inline static
Definition at line 53 of file commandline.h.
References arguments_.
Referenced by lczero::ConfigFile::Init(), and lczero::OptionsParser::ProcessAllFlags().
BinaryDirectory()
std::string lczero::CommandLine::BinaryDirectory () static
Definition at line 71 of file commandline.cc.
References binary_.
Referenced by lczero::DiscoverWeightsFile(), lczero::onnx::OnnxNetwork::GetOptions(), and lczero::ConfigFile::ParseFile().
BinaryName()
static const std::string & lczero::CommandLine::BinaryName () inline static
Definition at line 43 of file commandline.h.
References binary_.
Referenced by lczero::ChooseAndRunEngine(), lczero::LoadWeights(), lczero::OptionsParser::ProcessFlags(), and lczero::OptionsParser::ShowHelp().
ConsumeCommand()
bool lczero::CommandLine::ConsumeCommand (std::string_view command) static
Definition at line 59 of file commandline.cc.
References arguments_.
Referenced by lczero::ChooseAndRunEngine().
GetModes()
static const std::vector< std::pair< std::string, std::string > > & lczero::CommandLine::GetModes () inline static
Definition at line 58 of file commandline.h.
References modes_.
Referenced by lczero::OptionsParser::ShowHelp().
Init()
void lczero::CommandLine::Init (int argc, const char ** argv) static
Definition at line 37 of file commandline.cc.
References arguments_, binary_, and LOGFILE.
RegisterMode()
void lczero::CommandLine::RegisterMode (const std::string & mode, const std::string & description) static
Definition at line 66 of file commandline.cc.
References mode, and modes_.
Member Data Documentation
arguments_
std::vector< std::string > lczero::CommandLine::arguments_ static private
Definition at line 64 of file commandline.h.
Referenced by Arguments(), ConsumeCommand(), and Init().
binary_
std::string lczero::CommandLine::binary_ static private
Definition at line 63 of file commandline.h.
Referenced by BinaryDirectory(), BinaryName(), and Init().
modes_
std::vector< std::pair< std::string, std::string > > lczero::CommandLine::modes_ static private
Definition at line 65 of file commandline.h.
Referenced by GetModes(), and RegisterMode().
The documentation for this class was generated from the following files:
utils/commandline.h
utils/commandline.cc