Leela Chess Zero: lczero::OptionsParser::Option Class Reference
lczero::OptionsParser::Option Class Reference abstract
#include <optionsparser.h>
Public Member Functions
Option (const OptionId &id)
virtual ~Option ()
virtual void SetValue (const std::string &value, OptionsDict *dict)=0
Protected Member Functions
const OptionId & GetId () const
std::string GetUciOption () const
std::string GetHelpText () const
std::string GetLongFlag () const
char GetShortFlag () const
Private Member Functions
virtual std::string GetOptionString (const OptionsDict &dict) const =0
virtual bool ProcessLongFlag (const std::string &, const std::string &, OptionsDict *)
virtual bool ProcessShortFlag (char, OptionsDict *)
virtual bool ProcessShortFlagWithValue (char, const std::string &, OptionsDict *)
virtual std::string GetHelp (const OptionsDict &dict) const =0
Private Attributes
const OptionId & id_
Friends
class OptionsParser
Detailed Description
Definition at line 44 of file optionsparser.h.
Constructor & Destructor Documentation
Option()
lczero::OptionsParser::Option::Option (const OptionId & id)
Definition at line 47 of file optionsparser.cc.
~Option()
virtual lczero::OptionsParser::Option::~Option () inline virtual
Definition at line 47 of file optionsparser.h.
Member Function Documentation
GetHelp()
virtual std::string lczero::OptionsParser::Option::GetHelp (const OptionsDict & dict) const private pure virtual
Implemented in lczero::StringOption, lczero::IntOption, lczero::FloatOption, lczero::BoolOption, lczero::ButtonOption, and lczero::ChoiceOption.
GetHelpText()
std::string lczero::OptionsParser::Option::GetHelpText () const inline protected
Definition at line 56 of file optionsparser.h.
References lczero::OptionId::help_text(), and id_.
Referenced by lczero::StringOption::GetHelp(), lczero::IntOption::GetHelp(), lczero::FloatOption::GetHelp(), lczero::BoolOption::GetHelp(), and lczero::ChoiceOption::GetHelp().
GetId()
const OptionId & lczero::OptionsParser::Option::GetId () const inline protected
Definition at line 52 of file optionsparser.h.
References id_.
Referenced by lczero::StringOption::GetVal(), lczero::IntOption::GetVal(), lczero::FloatOption::GetVal(), lczero::BoolOption::GetVal(), lczero::ChoiceOption::GetVal(), lczero::StringOption::SetVal(), lczero::IntOption::SetVal(), lczero::FloatOption::SetVal(), lczero::BoolOption::SetVal(), lczero::ChoiceOption::SetVal(), and lczero::ButtonOption::SetValue().
GetLongFlag()
std::string lczero::OptionsParser::Option::GetLongFlag () const inline protected
Definition at line 57 of file optionsparser.h.
References id_, and lczero::OptionId::long_flag().
Referenced by lczero::OptionsParser::FindOptionByLongFlag(), lczero::StringOption::GetHelp(), lczero::IntOption::GetHelp(), lczero::FloatOption::GetHelp(), lczero::BoolOption::GetHelp(), lczero::ChoiceOption::GetHelp(), lczero::StringOption::ProcessLongFlag(), lczero::IntOption::ProcessLongFlag(), lczero::FloatOption::ProcessLongFlag(), lczero::BoolOption::ProcessLongFlag(), lczero::ChoiceOption::ProcessLongFlag(), lczero::IntOption::SetVal(), lczero::FloatOption::SetVal(), lczero::ChoiceOption::SetVal(), lczero::BoolOption::ValidateBoolString(), and lczero::IntOption::ValidateIntString().
GetOptionString()
virtual std::string lczero::OptionsParser::Option::GetOptionString (const OptionsDict & dict) const private pure virtual
Implemented in lczero::StringOption, lczero::IntOption, lczero::FloatOption, lczero::BoolOption, lczero::ButtonOption, and lczero::ChoiceOption.
GetShortFlag()
char lczero::OptionsParser::Option::GetShortFlag () const inline protected
Definition at line 60 of file optionsparser.h.
References id_, and lczero::OptionId::short_flag().
Referenced by lczero::StringOption::GetHelp(), lczero::IntOption::GetHelp(), lczero::FloatOption::GetHelp(), lczero::BoolOption::GetHelp(), lczero::ChoiceOption::GetHelp(), lczero::BoolOption::ProcessShortFlag(), lczero::StringOption::ProcessShortFlagWithValue(), lczero::IntOption::ProcessShortFlagWithValue(), lczero::FloatOption::ProcessShortFlagWithValue(), and lczero::ChoiceOption::ProcessShortFlagWithValue().
GetUciOption()
std::string lczero::OptionsParser::Option::GetUciOption () const inline protected
Definition at line 53 of file optionsparser.h.
References id_, and lczero::OptionId::uci_option().
Referenced by lczero::StringOption::GetHelp(), lczero::IntOption::GetHelp(), lczero::FloatOption::GetHelp(), lczero::BoolOption::GetHelp(), and lczero::ChoiceOption::GetHelp().
ProcessLongFlag()
virtual bool lczero::OptionsParser::Option::ProcessLongFlag (const std::string & , const std::string & , OptionsDict *) inline private virtual
Reimplemented in lczero::StringOption, lczero::IntOption, lczero::FloatOption, lczero::BoolOption, lczero::ButtonOption, and lczero::ChoiceOption.
Definition at line 64 of file optionsparser.h.
Referenced by lczero::OptionsParser::ProcessFlags().
ProcessShortFlag()
virtual bool lczero::OptionsParser::Option::ProcessShortFlag (char , OptionsDict *) inline private virtual
Reimplemented in lczero::BoolOption, and lczero::ButtonOption.
Definition at line 69 of file optionsparser.h.
ProcessShortFlagWithValue()
virtual bool lczero::OptionsParser::Option::ProcessShortFlagWithValue (char , const std::string & , OptionsDict *) inline private virtual
Reimplemented in lczero::StringOption, lczero::IntOption, lczero::FloatOption, and lczero::ChoiceOption.
Definition at line 72 of file optionsparser.h.
SetValue()
virtual void lczero::OptionsParser::Option::SetValue (const std::string & value, OptionsDict * dict) pure virtual
Implemented in lczero::StringOption, lczero::IntOption, lczero::FloatOption, lczero::BoolOption, lczero::ButtonOption, and lczero::ChoiceOption.
Friends And Related Symbol Documentation
OptionsParser
friend class OptionsParser friend
Definition at line 80 of file optionsparser.h.
Member Data Documentation
id_
const OptionId& lczero::OptionsParser::Option::id_ private
Definition at line 79 of file optionsparser.h.
Referenced by GetHelpText(), GetId(), GetLongFlag(), GetShortFlag(), and GetUciOption().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/optionsparser.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/utils/optionsparser.cc