Leela Chess Zero: lczero::ValueEvaluator Class Reference
lczero::ValueEvaluator Class Reference
Public Member Functions
void Reset (const PlayerOptions &player) override
void Gather (classic::NodeTree *tree) override
void Run () override
void MakeBestMove (classic::NodeTree *tree) override
Public Member Functions inherited from lczero::Evaluator
virtual ~Evaluator ()=default
Public Attributes
std::unique_ptr< BackendComputation > comp_
std::vector< Move > moves_
std::vector< float > q_
Detailed Description
Definition at line 62 of file multigame.cc.
Member Function Documentation
Gather()
void lczero::ValueEvaluator::Gather (classic::NodeTree * tree) inline override virtual
Implements lczero::Evaluator.
Definition at line 67 of file multigame.cc.
References lczero::PositionHistory::Append(), comp_, lczero::PositionHistory::ComputeGameResult(), lczero::DRAW, lczero::classic::Node::Edges(), lczero::classic::NodeTree::GetCurrentHead(), lczero::classic::Node::GetNumEdges(), lczero::classic::NodeTree::GetPositionHistory(), lczero::PositionHistory::GetPositions(), moves_, lczero::PositionHistory::Pop(), lczero::EvalPosition::pos, lczero::EvalResultPtr::q, q_, result, and lczero::UNDECIDED.
MakeBestMove()
void lczero::ValueEvaluator::MakeBestMove (classic::NodeTree * tree) inline override virtual
Implements lczero::Evaluator.
Definition at line 94 of file multigame.cc.
References lczero::classic::NodeTree::MakeMove(), moves_, and q_.
Reset()
void lczero::ValueEvaluator::Reset (const PlayerOptions & player) inline override virtual
Implements lczero::Evaluator.
Definition at line 64 of file multigame.cc.
References lczero::PlayerOptions::backend, comp_, and lczero::Backend::CreateComputation().
Run()
void lczero::ValueEvaluator::Run () inline override virtual
Implements lczero::Evaluator.
Definition at line 93 of file multigame.cc.
References comp_.
Member Data Documentation
comp_
std::unique_ptr<BackendComputation> lczero::ValueEvaluator::comp_
Definition at line 99 of file multigame.cc.
Referenced by Gather(), Reset(), and Run().
moves_
std::vector<Move> lczero::ValueEvaluator::moves_
Definition at line 100 of file multigame.cc.
Referenced by Gather(), and MakeBestMove().
q_
std::vector<float> lczero::ValueEvaluator::q_
Definition at line 101 of file multigame.cc.
Referenced by Gather(), and MakeBestMove().
The documentation for this class was generated from the following file:
src/selfplay/multigame.cc