Leela Chess Zero: lczero::HloTensorType Class Reference
lczero::HloTensorType Class Reference
#include <hlo_builder.h>
Public Member Functions
HloTensorType ()=default
HloTensorType (const HloTensorType &)=default
HloTensorType (pblczero::XlaShapeProto::Type el_type)
HloTensorType (pblczero::XlaShapeProto::Type el_type, const std::vector< int64_t > &dimensions)
HloTensorType (const pblczero::XlaShapeProto &)
pblczero::XlaShapeProto ToProto () const override
std::string ToString () const override
void SetElementType (pblczero::XlaShapeProto::Type el_type)
pblczero::XlaShapeProto::Type GetElementType () const
void AddDimension (int64_t size)
const std::vector< int64_t > & GetDimensions () const
int64_t GetDimension (size_t idx) const
void SetDimension (size_t idx, int64_t size)
void SetDimensions (const std::vector< int64_t > &dimensions)
size_t Rank () const
size_t NumElements () const
Public Member Functions inherited from lczero::HloType
virtual ~HloType ()=default
Private Attributes
pblczero::XlaShapeProto::Type type_
std::vector< int64_t > dimensions_
Detailed Description
Definition at line 66 of file hlo_builder.h.
Constructor & Destructor Documentation
HloTensorType() [1/5]
lczero::HloTensorType::HloTensorType () default
HloTensorType() [2/5]
lczero::HloTensorType::HloTensorType (const HloTensorType &) default
HloTensorType() [3/5]
lczero::HloTensorType::HloTensorType (pblczero::XlaShapeProto::Type el_type) inline explicit
Definition at line 70 of file hlo_builder.h.
HloTensorType() [4/5]
lczero::HloTensorType::HloTensorType (pblczero::XlaShapeProto::Type el_type, const std::vector< int64_t > & dimensions) inline explicit
Definition at line 72 of file hlo_builder.h.
HloTensorType() [5/5]
lczero::HloTensorType::HloTensorType (const pblczero::XlaShapeProto & proto) explicit
Definition at line 38 of file hlo_builder.cc.
References type_.
Member Function Documentation
AddDimension()
void lczero::HloTensorType::AddDimension (int64_t size) inline
Definition at line 83 of file hlo_builder.h.
References dimensions_.
Referenced by lczero::HloBuilder::Dot(), lczero::HloBuilder::Gather(), lczero::HloBuilder::Reduce(), lczero::HloBuilder::Slice(), and lczero::HloBuilder::Transpose().
GetDimension()
int64_t lczero::HloTensorType::GetDimension (size_t idx) const inline
Definition at line 85 of file hlo_builder.h.
References dimensions_, and idx.
Referenced by lczero::HloBuilder::Broadcast(), lczero::HloBuilder::Concatenate(), lczero::HloBuilder::Dot(), lczero::HloBuilder::Gather(), and lczero::HloBuilder::Slice().
GetDimensions()
const std::vector< int64_t > & lczero::HloTensorType::GetDimensions () const inline
Definition at line 84 of file hlo_builder.h.
References dimensions_.
GetElementType()
pblczero::XlaShapeProto::Type lczero::HloTensorType::GetElementType () const inline
Definition at line 82 of file hlo_builder.h.
References type_.
Referenced by lczero::HloBuilder::Concatenate(), lczero::HloBuilder::Dot(), lczero::HloBuilder::Gather(), lczero::HloBuilder::Reshape(), and lczero::HloBuilder::Slice().
NumElements()
size_t lczero::HloTensorType::NumElements () const
Definition at line 72 of file hlo_builder.cc.
References dimensions_.
Referenced by lczero::HloBuilder::Reshape().
Rank()
size_t lczero::HloTensorType::Rank () const inline
Definition at line 90 of file hlo_builder.h.
References dimensions_.
Referenced by lczero::HloBuilder::Concatenate(), lczero::HloBuilder::Gather(), and lczero::HloBuilder::Slice().
SetDimension()
void lczero::HloTensorType::SetDimension (size_t idx, int64_t size) inline
Definition at line 86 of file hlo_builder.h.
References dimensions_, and idx.
Referenced by lczero::HloBuilder::Concatenate().
SetDimensions()
void lczero::HloTensorType::SetDimensions (const std::vector< int64_t > & dimensions) inline
Definition at line 87 of file hlo_builder.h.
References dimensions_.
SetElementType()
void lczero::HloTensorType::SetElementType (pblczero::XlaShapeProto::Type el_type) inline
Definition at line 79 of file hlo_builder.h.
References type_.
Referenced by lczero::HloBuilder::Compare().
ToProto()
pblczero::XlaShapeProto lczero::HloTensorType::ToProto () const override virtual
Implements lczero::HloType.
Definition at line 51 of file hlo_builder.cc.
References dimensions_, and type_.
Referenced by lczero::HloBuilder::Broadcast(), lczero::HloBuilder::Compare(), lczero::HloBuilder::Concatenate(), lczero::HloBuilder::Dot(), lczero::HloBuilder::Gather(), lczero::HloBuilder::Reduce(), lczero::HloBuilder::Reshape(), lczero::HloBuilder::Slice(), and lczero::HloBuilder::Transpose().
ToString()
std::string lczero::HloTensorType::ToString () const override virtual
Implements lczero::HloType.
Definition at line 63 of file hlo_builder.cc.
References dimensions_, and type_.
Referenced by lczero::HloBuilder::Broadcast(), lczero::HloBuilder::Concatenate(), lczero::HloBuilder::Reshape(), and lczero::HloBuilder::Slice().
Member Data Documentation
dimensions_
std::vector<int64_t> lczero::HloTensorType::dimensions_ private
Definition at line 96 of file hlo_builder.h.
Referenced by AddDimension(), GetDimension(), GetDimensions(), NumElements(), Rank(), SetDimension(), SetDimensions(), ToProto(), and ToString().
type_
pblczero::XlaShapeProto::Type lczero::HloTensorType::type_ private
Initial value:
=
      pblczero::XlaShapeProto::PRIMITIVE_TYPE_INVALID
Definition at line 94 of file hlo_builder.h.
Referenced by GetElementType(), HloTensorType(), SetElementType(), ToProto(), and ToString().
The documentation for this class was generated from the following files:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/xla/hlo_builder.h
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/neural/xla/hlo_builder.cc