Leela Chess Zero: lczero::cudnn_backend::FusedWinogradConvSELayer< DataType > Class Template Reference
lczero::cudnn_backend::FusedWinogradConvSELayer< DataType > Class Template Reference
Multi-pass Winograd Convolution fused with (optional) SE.
#include <layers.h>
Public Member Functions
FusedWinogradConvSELayer (BaseLayer< DataType > *ip, int C, int H, int W, int Cin, ActivationFunction activation, bool bias, bool skipAdd, bool se, int se_k, bool use_gemm_ex, bool op_nhcw=false)
Constructor for FusedWinogradConvSELayer.
~FusedWinogradConvSELayer ()
void LoadWeights (float *pfilter, float *pBias, void *scratch)
void LoadSEWeights (float *w1, float *b1, float *w2, float *b2, void *scratch)
void Eval (int N, DataType *output, const DataType *input, const DataType *input2, void *scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType ***=nullptr) override
Evaluates the layer.
Public Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
int GetC () const
int GetH () const
int GetW () const
bool isNHWC () const
BaseLayer (int c, int h, int w, BaseLayer *ip)
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc)
Constructor.
BaseLayer (int c, int h, int w, BaseLayer *ip, bool nhwc, bool use_gemm_ex)
virtual ~BaseLayer ()=default
size_t GetOutputSize (int N) const
Private Attributes
const int c_input_
const ActivationFunction act_
const bool use_bias_
const bool skip_add_
const bool has_se_
const int se_k_
const bool op_nhcw_
DataType * biases_ = nullptr
DataType * transformed_weights_ = nullptr
DataType * w1_
DataType * w2_
DataType * b1_
DataType * b2_
Additional Inherited Members
Protected Member Functions inherited from lczero::cudnn_backend::BaseLayer< DataType >
void cublasRowMajorMatrixMul (const DataType *A, const DataType *B, DataType *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const half *A, const half *B, half *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
void cublasRowMajorMatrixMul (const float *A, const float *B, float *Out, int M, int N, int K, int batchSize, cublasHandle_t cublas)
Protected Attributes inherited from lczero::cudnn_backend::BaseLayer< DataType >
BaseLayer * input_
int C
int H
int W
bool nhwc_
const bool use_gemm_ex_
Detailed Description
template<typename DataType>
class lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >
Multi-pass Winograd Convolution fused with (optional) SE.
Definition at line 228 of file layers.h.
Constructor & Destructor Documentation
FusedWinogradConvSELayer()
template<typename DataType > lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer (BaseLayer< DataType > * ip, int C, int H, int W, int Cin, ActivationFunction activation, bool bias, bool skip_add, bool se, int se_k, bool use_gemm_ex, bool op_nhcw = false)
Constructor for FusedWinogradConvSELayer.
A specialized layer that fuses Winograd convolution, SE unit, and activation.
Parameters
ip Input layer.
C Output channels.
H Output height.
W Output width.
Cin Input channels.
activation Activation function.
bias Whether to use bias.
skip_add Whether to add residual skip connection.
se Whether to apply SE unit.
se_k Size of SE internal layer.
use_gemm_ex Whether to use extended GEMM.
op_nhcw Whether to use NHCW output layout.
Definition at line 839 of file layers.cc.
References lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::act_, lczero::ACTIVATION_MISH, lczero::ACTIVATION_NONE, lczero::ACTIVATION_RELU, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::b1_, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::b2_, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::biases_, lczero::cudnn_backend::BaseLayer< DataType >::C, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::c_input_, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::has_se_, ReportCUDAErrors, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::se_k_, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::transformed_weights_, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::use_bias_, lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::w1_, and lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::w2_.
~FusedWinogradConvSELayer()
template<typename DataType > lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::~FusedWinogradConvSELayer ()
Definition at line 1071 of file layers.cc.
References ReportCUDAErrors.
Member Function Documentation
Eval()
template<typename DataType > void lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::Eval (int N, DataType * output, const DataType * input, const DataType * input2, void * scratch, size_t scratch_size, cudnnHandle_t cudnn, cublasHandle_t cublas, cudaStream_t stream, DataType *** = nullptr) override virtual
Evaluates the layer.
Parameters
N Batch size.
output Output buffer.
input Input buffer.
input2 Optional second input (e.g., skip connection).
scratch Scratch memory.
scratch_size Size of scratch memory.
cudnn CuDNN handle.
cublas CuBLAS handle.
stream CUDA stream.
offset_pointers Optional pointers for batched offset calculations.
Implements lczero::cudnn_backend::BaseLayer< DataType >.
Definition at line 996 of file layers.cc.
References lczero::ACTIVATION_MISH, lczero::ACTIVATION_NONE, lczero::ACTIVATION_RELU, C, lczero::cudnn_backend::BaseLayer< DataType >::cublasRowMajorMatrixMul(), input, output, and lczero::cudnn_backend::OutputTransform().
LoadSEWeights()
template<typename DataType > void lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::LoadSEWeights (float * w1, float * b1, float * w2, float * b2, void * scratch)
Definition at line 920 of file layers.cc.
References C, lczero::cudnn_backend::copyTypeConverted(), lczero::cudnn_backend::CpuTranspose(), and ReportCUDAErrors.
LoadWeights()
template<typename DataType > void lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::LoadWeights (float * pfilter, float * pBias, void * scratch)
Definition at line 885 of file layers.cc.
References C, lczero::cudnn_backend::copyTypeConverted(), lczero::cudnn_backend::FilterTransform(), and ReportCUDAErrors.
Member Data Documentation
act_
template<typename DataType > const ActivationFunction lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::act_ private
Definition at line 253 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
b1_
template<typename DataType > DataType* lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::b1_ private
Definition at line 266 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
b2_
template<typename DataType > DataType* lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::b2_ private
Definition at line 267 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
biases_
template<typename DataType > DataType* lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::biases_ = nullptr private
Definition at line 260 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
c_input_
template<typename DataType > const int lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::c_input_ private
Definition at line 252 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
has_se_
template<typename DataType > const bool lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::has_se_ private
Definition at line 256 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
op_nhcw_
template<typename DataType > const bool lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::op_nhcw_ private
Definition at line 258 of file layers.h.
se_k_
template<typename DataType > const int lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::se_k_ private
Definition at line 257 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
skip_add_
template<typename DataType > const bool lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::skip_add_ private
Definition at line 255 of file layers.h.
transformed_weights_
template<typename DataType > DataType* lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::transformed_weights_ = nullptr private
Definition at line 261 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
use_bias_
template<typename DataType > const bool lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::use_bias_ private
Definition at line 254 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
w1_
template<typename DataType > DataType* lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::w1_ private
Definition at line 264 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
w2_
template<typename DataType > DataType* lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::w2_ private
Definition at line 265 of file layers.h.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::FusedWinogradConvSELayer().
The documentation for this class was generated from the following files:
neural/backends/cuda/layers.h
neural/backends/cuda/layers.cc