Leela Chess Zero: lczero::dag_classic Namespace Reference
lczero::dag_classic Namespace Reference
Classes
class atomic_unique_ptr
A thread-safe unique pointer with atomic operations.
class Edge
Represents a single edge in the search graph (a move).
class Edge_Iterator
class EdgeAndNode
Contains Edge and Node pair and set of proxy functions.
struct Eval
Raw evaluation results.
class LowNode
Represents a unique position in the game DAG.
struct NNEval
Neural network evaluation result tailored for storage.
class Node
Represents an expanded edge in the search DAG.
class NodeGarbageCollector
Garbage collector for nodes in the DAG.
class NodeTree
Manages the game tree (or DAG).
class ReleaseNodesWork
Helper class for thread-local release queues.
class Search
class SearchWorker
Single thread worker of the search engine.
class VisitedNode_Iterator
Typedefs
typedef std::pair< GameResult, GameResult > Bounds
typedef absl::flat_hash_map< uint64_t, std::weak_ptr< LowNode > > TranspositionTable
using ContemptMode = classic::ContemptMode
Alias for ContemptMode from the classic search namespace.
using SearchParams = classic::BaseSearchParams
Alias for BaseSearchParams from the classic search namespace.
typedef std::vector< std::tuple< Node *, int, int > > BackupPath
Tuple representing a path to a node: (Node*, repetitions, moves_left).
Enumerations
enum class Terminal : uint8_t { NonTerminal , EndOfGame , Tablebase }
Type of terminal node.
Functions
template<typename VisitorType , typename EdgeVisitorType >
static void TreeWalk (const Node *node, bool as_opponent, Node::VisitorId::type id, VisitorType visitor, EdgeVisitorType edge)
static std::string PtrToNodeName (const void *ptr)
template<typename VisitorType , typename EdgeVisitorType >
static void TreeWalk (const Node *node, bool as_opponent, VisitorType visitor, EdgeVisitorType edge)
static bool WLDMInvariantsHold (float wl, float d, float m)
static bool operator< (const EdgeAndNode &, const EdgeAndNode &)
Variables
static constexpr float wld_tolerance = 0.000001f
static constexpr float m_tolerance = 0.000001f
Typedef Documentation
BackupPath
typedef std::vector<std::tuple<Node*, int, int> > lczero::dag_classic::BackupPath
Tuple representing a path to a node: (Node*, repetitions, moves_left).
Definition at line 55 of file search.h.
Bounds
typedef std::pair<GameResult, GameResult> lczero::dag_classic::Bounds
Definition at line 242 of file node.h.
ContemptMode
using lczero::dag_classic::ContemptMode = typedef classic::ContemptMode
Alias for ContemptMode from the classic search namespace.
Definition at line 36 of file params.h.
SearchParams
using lczero::dag_classic::SearchParams = typedef classic::BaseSearchParams
Alias for BaseSearchParams from the classic search namespace.
Definition at line 39 of file params.h.
TranspositionTable
typedef absl::flat_hash_map<uint64_t, std::weak_ptr<LowNode> > lczero::dag_classic::TranspositionTable
Definition at line 1052 of file node.h.
Enumeration Type Documentation
Terminal
enum class lczero::dag_classic::Terminal : uint8_t strong
Type of terminal node.
Enumerator
NonTerminal
Not a terminal node.
EndOfGame
Game over (mate, checkmate, draw).
Tablebase
Tablebase hit.
Definition at line 245 of file node.h.
Function Documentation
operator<()
static bool lczero::dag_classic::operator< (const EdgeAndNode & , const EdgeAndNode &) static
Definition at line 513 of file search.cc.
PtrToNodeName()
static std::string lczero::dag_classic::PtrToNodeName (const void * ptr) static
Definition at line 508 of file node.cc.
References ptr.
Referenced by lczero::dag_classic::Node::DotEdgeString(), and lczero::dag_classic::LowNode::DotNodeString().
TreeWalk() [1/2]
template<typename VisitorType , typename EdgeVisitorType > static void lczero::dag_classic::TreeWalk (const Node * node, bool as_opponent, Node::VisitorId::type id, VisitorType visitor, EdgeVisitorType edge) static
Definition at line 481 of file node.cc.
References lczero::dag_classic::Node::Edges(), lczero::dag_classic::Node::GetLowNode(), and TreeWalk().
Referenced by lczero::dag_classic::Node::DotGraphString(), TreeWalk(), TreeWalk(), and lczero::dag_classic::Node::ZeroNInFlight().
TreeWalk() [2/2]
template<typename VisitorType , typename EdgeVisitorType > static void lczero::dag_classic::TreeWalk (const Node * node, bool as_opponent, VisitorType visitor, EdgeVisitorType edge) static
Definition at line 515 of file node.cc.
References TreeWalk().
WLDMInvariantsHold()
static bool lczero::dag_classic::WLDMInvariantsHold (float wl, float d, float m) static
Definition at line 630 of file node.cc.
References d, m, m_tolerance, and wld_tolerance.
Referenced by lczero::dag_classic::Node::WLDMInvariantsHold(), and lczero::dag_classic::LowNode::WLDMInvariantsHold().
Variable Documentation
m_tolerance
constexpr float lczero::dag_classic::m_tolerance = 0.000001f static constexpr
Definition at line 628 of file node.cc.
Referenced by WLDMInvariantsHold().
wld_tolerance
constexpr float lczero::dag_classic::wld_tolerance = 0.000001f static constexpr
Definition at line 627 of file node.cc.
Referenced by WLDMInvariantsHold().