Leela Chess Zero: lczero::cudnn_backend Namespace Reference
lczero::cudnn_backend Namespace Reference
Classes
class AttentionBody
Attention Body.
class AttentionPolicyHead
Attention Policy Head.
class BaseLayer
Base class for neural network layers in CUDA backend.
class Conv1Layer
1x1 Convolution Layer.
class ConvLayer
Convolutional Layer using CuDNN.
struct CudaGraphCapture
Forward declaration of CudaGraphCapture.
struct CudaGraphExec
Wrapper for CUDA Graph Execution.
class EmbeddingLayer
Embedding Layer.
class EncoderBlock
Encoder Block Layer (part of Transformer architecture).
class FCLayer
Fully Connected Layer.
class FusedWinogradConvSELayer
Multi-pass Winograd Convolution fused with (optional) SE.
struct InputsOutputs
Manages input and output buffers for the network.
class PolicyMapLayer
Policy Map Layer.
class ResidualBlock
Residual Block Layer.
class SELayer
Fused Squeeze-and-Excitation (SE) Layer.
class ValueHead
Value Head.
Functions
void CudnnError (cudnnStatus_t status, const char *file, const int &line)
void CublasError (cublasStatus_t status, const char *file, const int &line)
void CudaError (cudaError_t status, const char *file, const int &line)
int DivUp (int a, int b)
void ToType (float &dst, float src)
void ToType (half &dst, float src)
float FromType (float src)
float FromType (half src)
template<typename T >
void addVectors (T *c, T *a, T *b, int size, int asize, int bsize, ActivationFunction activation, cudaStream_t stream)
Adds two vectors (possibly of different sizes), with optional activation.
template<typename T >
void addVectorsHNC_NHC (T *a, T *b, int N, int H, int C, cudaStream_t stream)
Adds two vectors of equal size, overwriting the first.
template<typename T >
void addBiasBatched (T *output, const T *input, const T *bias, int Batch, int N, int C, ActivationFunction activation, cudaStream_t stream)
Adds bias to innermost dimension and performs optional activation.
template<typename T >
void addBiasBatched (T *output, const T *input, const T *bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, cudaStream_t stream)
template<typename T >
void addBias_NCHW (T *c, T *a, T *b, int N, int C, int H, int W, ActivationFunction activation, cudaStream_t stream)
Adds bias to convolution's output (NCHW layout).
template<typename DstType , typename SrcType >
void convertNCHWtoNHWC (DstType *output_tensor, const SrcType *input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, cudaStream_t stream)
Converts tensor from NCHW to NHWC layout.
template<typename DstType , typename SrcType >
void copyTypeConverted (DstType *op, SrcType *ip, int N, cudaStream_t stream)
template<typename T >
void batchNorm (T *output, const T *input, const T *skipInput, int N, int C, int H, int W, float *means, float *var_multipliers, ActivationFunction activation, cudaStream_t stream)
Performs batch normalization.
template<typename T >
void expandPlanes_NHWC (T *output, const uint64_t *masks, const T *values, int n, cudaStream_t stream)
Unpacks input planes to NHWC layout.
template<typename T >
void expandPlanes_NCHW (T *output, const uint64_t *masks, const T *values, int n, cudaStream_t stream)
template<typename T >
void globalAvgPool (int N, int C, T *output, const T *input, const T *prevLayerBias, bool nhwc, cudaStream_t steam)
Performs global average pooling.
template<typename T >
void globalScale (int N, int C, T *output, const T *input, const T *scaleBias, const T *prevLayerBias, bool nhwc, ActivationFunction activation, cudaStream_t steam)
bool Se_Fp16_NHWC (int N, int C, int numFc1Out, half *output, const half *skip, const half *input, const half *w1, const half *b1, const half *w2, const half *b2, const half *bPrev, ActivationFunction activation, cudaStream_t stream)
Performs Squeeze-and-Excitation (SE) in a single fused kernel.
template<typename T >
void PolicyMap (int N, T *output, const T *input, const short *indices, int inputSize, int usedSize, int outputSize, cudaStream_t stream)
template<typename T >
void FilterTransform (int N, int C, T *transformedFilter, const T *filter, cudaStream_t stream)
Winograd filter transformation.
template<typename T , bool nhcw>
void InputTransform (int N, int C, T *transformedInput, const T *input, cudaStream_t stream)
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip, bool skipInput_nhcw, bool output_nhcw>
void OutputTransform (int N, int C, int se_K, T *output, const T *input, const T *skip, const T *bias, const T *w1, const T *b1, const T *w2, const T *b2, cudaStream_t stream)
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip>
void OutputInputTransform (int N, int C, int se_K, T *output, const T *input, const T *skip, const T *bias, const T *w1, const T *b1, const T *w2, const T *b2, cudaStream_t stream)
template<typename T >
void Softmax (int N, int C, T *output, const T *input, const T *input2, cudaStream_t stream)
template<typename T >
void LayerNorm (int N, int C, T *output, const T *input, const T *bias, const T *skip, const T *gammas, const T *betas, float ep, float alpha, ActivationFunction act, cudaStream_t stream)
template<typename T >
void ComputePromotionLogits (int N, int C, T *output, const T *keys, const T *ppo, const T *policy_attn_logits, cudaStream_t stream)
template<typename T >
void inputPreprocessForAttentionBody (T *output, const T *input, const T *encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, cudaStream_t stream)
template<typename T >
void applyInputGating (T *output, const T *input, const T *mult, const T *add, int N, int HW, int C, cudaStream_t stream)
template<typename T >
void genOffsetPointers (T **offsets, int heads, int max_batch, int depth, int d_model, T *k, T *q, T *b1, T *v, T *b2, cudaStream_t stream)
void fusedMHA (void *output, void *mha_q, void *mha_k, void *mha_v, void *skip, int batch_size, int num_heads, int depth, cudaStream_t stream)
void cpuTranspose (float *op, float *ip, int rows, int cols)
static void CpuTranspose (float *op, float *ip, size_t rows, size_t cols)
template<typename DataType >
void allocAndUpload (DataType **gpu_dest, std::vector< float > cpu_src, void *scratch)
template<typename DataType >
static void cublasXgemm (cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, float alpha, const DataType *A, int lda, const DataType *B, int ldb, float beta, DataType *C, int ldc)
template<typename DataType >
static void cublasXGemmStridedBatched (cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, float alpha, const void *A, int lda, long long int strideA, const void *B, int ldb, long long int strideB, float beta, void *C, int ldc, long long int strideC, int batchCount, bool use_gemm_ex)
template<typename DataType >
static void cublasXGemmBatched (cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, float alpha, DataType **A, int lda, DataType **B, int ldb, float beta, DataType **C, int ldc, int batchCount)
const char * CublasGetErrorString (cublasStatus_t status)
Variables
static constexpr int kNumOutputPolicy = 1858
Maximum number of output policy channels.
static constexpr int kMaxResBlockFusingChannels = 384
Maximum supported filter count for residual block fusing.
static constexpr int kMaxResBlockFusingSeKFp16Ampere
static constexpr int kMaxResBlockFusingSeK
static constexpr int kMaxResBlockFusingSeFp16AmpereSmem
static constexpr bool kUseFusedSELayer = true
Function Documentation
addBias_NCHW()
template<typename T > void lczero::cudnn_backend::addBias_NCHW (T * c, T * a, T * b, int N, int C, int H, int W, ActivationFunction activation, cudaStream_t stream)
Adds bias to convolution's output (NCHW layout).
Parameters
c Output.
a Input.
b Bias.
N Batch size.
C Channels.
H Height.
W Width.
activation Activation function.
stream CUDA stream.
Referenced by lczero::cudnn_backend::ConvLayer< DataType >::Eval(), and lczero::cudnn_backend::Conv1Layer< DataType >::Eval().
addBiasBatched() [1/2]
template<typename T > void lczero::cudnn_backend::addBiasBatched (T * output, const T * input, const T * bias, int Batch, int N, int C, ActivationFunction activation, cudaStream_t stream)
Adds bias to innermost dimension and performs optional activation.
Parameters
output Output buffer.
input Input buffer.
bias Bias vector.
Batch Batch size.
N Outer dimension size.
C Inner dimension (channel) size.
activation Activation function.
stream CUDA stream.
Referenced by lczero::cudnn_backend::EncoderBlock< DataType >::Eval(), lczero::cudnn_backend::AttentionPolicyHead< DataType >::Eval(), lczero::cudnn_backend::EmbeddingLayer< DataType >::Eval(), and lczero::cudnn_backend::AttentionBody< DataType >::Eval().
addBiasBatched() [2/2]
template<typename T > void lczero::cudnn_backend::addBiasBatched (T * output, const T * input, const T * bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, cudaStream_t stream)
addVectors()
template<typename T > void lczero::cudnn_backend::addVectors (T * c, T * a, T * b, int size, int asize, int bsize, ActivationFunction activation, cudaStream_t stream)
Adds two vectors (possibly of different sizes), with optional activation.
Parameters
c Output vector.
a Input vector A.
b Input vector B.
size Total number of elements to process.
asize Size of vector A.
bsize Size of vector B.
activation Activation function to apply.
stream CUDA stream.
Referenced by lczero::cudnn_backend::ConvLayer< DataType >::Eval(), lczero::cudnn_backend::Conv1Layer< DataType >::Eval(), lczero::cudnn_backend::AttentionBody< DataType >::Eval(), lczero::cudnn_backend::ValueHead< DataType >::Eval(), lczero::cudnn_backend::SELayer< DataType >::Eval(), lczero::cudnn_backend::FCLayer< DataType >::Eval(), lczero::cudnn_backend::SELayer< DataType >::Eval(), and lczero::cudnn_backend::FCLayer< DataType >::Eval().
addVectorsHNC_NHC()
template<typename T > void lczero::cudnn_backend::addVectorsHNC_NHC (T * a, T * b, int N, int H, int C, cudaStream_t stream)
Adds two vectors of equal size, overwriting the first.
Performs transposition of the first 2 indexes of the second vector.
Parameters
a Input/Output vector A.
b Input vector B.
N Batch size.
H Height.
C Channels.
stream CUDA stream.
allocAndUpload()
template<typename DataType > void lczero::cudnn_backend::allocAndUpload (DataType ** gpu_dest, std::vector< float > cpu_src, void * scratch)
Definition at line 1461 of file layers.cc.
References copyTypeConverted(), and ReportCUDAErrors.
applyInputGating()
template<typename T > void lczero::cudnn_backend::applyInputGating (T * output, const T * input, const T * mult, const T * add, int N, int HW, int C, cudaStream_t stream)
batchNorm()
template<typename T > void lczero::cudnn_backend::batchNorm (T * output, const T * input, const T * skipInput, int N, int C, int H, int W, float * means, float * var_multipliers, ActivationFunction activation, cudaStream_t stream)
Performs batch normalization.
Parameters
output Output buffer.
input Input buffer.
skipInput Optional skip connection input.
N Batch size.
C Channels.
H Height.
W Width.
means Batch normalization means.
var_multipliers Batch normalization variance multipliers.
activation Activation function.
stream CUDA stream.
ComputePromotionLogits()
template<typename T > void lczero::cudnn_backend::ComputePromotionLogits (int N, int C, T * output, const T * keys, const T * ppo, const T * policy_attn_logits, cudaStream_t stream)
convertNCHWtoNHWC()
template<typename DstType , typename SrcType > void lczero::cudnn_backend::convertNCHWtoNHWC (DstType * output_tensor, const SrcType * input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, cudaStream_t stream)
Converts tensor from NCHW to NHWC layout.
Can also change datatype and pad/un-pad elements.
Parameters
output_tensor Output tensor.
input_tensor Input tensor.
Nin Input batch size.
Cin Input channels.
Nout Output batch size.
Cout Output channels.
H Height.
W Width.
stream CUDA stream.
Referenced by lczero::cudnn_backend::AttentionPolicyHead< DataType >::Eval(), lczero::cudnn_backend::AttentionBody< DataType >::Eval(), lczero::cudnn_backend::FCLayer< DataType >::LoadWeights(), and lczero::cudnn_backend::ConvLayer< DataType >::LoadWeights().
copyTypeConverted()
template<typename DstType , typename SrcType > void lczero::cudnn_backend::copyTypeConverted (DstType * op, SrcType * ip, int N, cudaStream_t stream)
Referenced by allocAndUpload(), lczero::cudnn_backend::AttentionBody< DataType >::AttentionBody(), lczero::SyclNetwork< DataType >::forwardEval(), lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::LoadSEWeights(), lczero::cudnn_backend::ResidualBlock< DataType >::LoadSEWeights(), lczero::cudnn_backend::FCLayer< DataType >::LoadWeights(), lczero::cudnn_backend::ConvLayer< DataType >::LoadWeights(), lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::LoadWeights(), lczero::cudnn_backend::Conv1Layer< DataType >::LoadWeights(), lczero::cudnn_backend::SELayer< DataType >::LoadWeights(), lczero::cudnn_backend::ResidualBlock< DataType >::LoadWeights0(), and lczero::cudnn_backend::ResidualBlock< DataType >::LoadWeights1().
cpuTranspose()
void lczero::cudnn_backend::cpuTranspose (float * op, float * ip, int rows, int cols)
Definition at line 461 of file layers.cc.
Referenced by lczero::cudnn_backend::SELayer< DataType >::LoadWeights().
CpuTranspose()
static void lczero::cudnn_backend::CpuTranspose (float * op, float * ip, size_t rows, size_t cols) inline static
Definition at line 913 of file layers.cc.
Referenced by lczero::dx_backend::ConvLayer::LoadSEWeights(), lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::LoadSEWeights(), lczero::cudnn_backend::ResidualBlock< DataType >::LoadSEWeights(), and lczero::dx_backend::FCLayer::LoadWeights().
CublasError()
void lczero::cudnn_backend::CublasError (cublasStatus_t status, const char * file, const int & line)
Definition at line 2547 of file layers.cc.
References CERR, and CublasGetErrorString().
CublasGetErrorString()
const char * lczero::cudnn_backend::CublasGetErrorString (cublasStatus_t status)
Definition at line 2521 of file layers.cc.
Referenced by CublasError().
cublasXgemm()
template<typename DataType > static void lczero::cudnn_backend::cublasXgemm (cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, float alpha, const DataType * A, int lda, const DataType * B, int ldb, float beta, DataType * C, int ldc) static
Definition at line 1643 of file layers.cc.
References C, lczero::FP32toFP16(), m, and ReportCUBLASErrors.
Referenced by lczero::cudnn_backend::EncoderBlock< DataType >::Eval(), and lczero::cudnn_backend::AttentionBody< DataType >::Eval().
cublasXGemmBatched()
template<typename DataType > static void lczero::cudnn_backend::cublasXGemmBatched (cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, float alpha, DataType ** A, int lda, DataType ** B, int ldb, float beta, DataType ** C, int ldc, int batchCount) static
Definition at line 1693 of file layers.cc.
References C, lczero::FP32toFP16(), m, and ReportCUBLASErrors.
cublasXGemmStridedBatched()
template<typename DataType > static void lczero::cudnn_backend::cublasXGemmStridedBatched (cublasHandle_t handle, cublasOperation_t transa, cublasOperation_t transb, int m, int n, int k, float alpha, const void * A, int lda, long long int strideA, const void * B, int ldb, long long int strideB, float beta, void * C, int ldc, long long int strideC, int batchCount, bool use_gemm_ex) static
Definition at line 1663 of file layers.cc.
References C, lczero::FP32toFP16(), m, and ReportCUBLASErrors.
CudaError()
void lczero::cudnn_backend::CudaError (cudaError_t status, const char * file, const int & line)
Definition at line 2557 of file layers.cc.
References CERR.
CudnnError()
void lczero::cudnn_backend::CudnnError (cudnnStatus_t status, const char * file, const int & line)
Definition at line 2510 of file layers.cc.
References CERR.
DivUp()
int lczero::cudnn_backend::DivUp (int a, int b) inline
Definition at line 78 of file cuda_common.h.
expandPlanes_NCHW()
template<typename T > void lczero::cudnn_backend::expandPlanes_NCHW (T * output, const uint64_t * masks, const T * values, int n, cudaStream_t stream)
Referenced by lczero::CudaNetwork< DataType >::forwardEval(), and lczero::CudnnNetwork< DataType >::forwardEval().
expandPlanes_NHWC()
template<typename T > void lczero::cudnn_backend::expandPlanes_NHWC (T * output, const uint64_t * masks, const T * values, int n, cudaStream_t stream)
Unpacks input planes to NHWC layout.
Referenced by lczero::CudnnNetwork< DataType >::forwardEval().
FilterTransform()
template<typename T > void lczero::cudnn_backend::FilterTransform (int N, int C, T * transformedFilter, const T * filter, cudaStream_t stream)
Winograd filter transformation.
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::LoadWeights(), lczero::cudnn_backend::ResidualBlock< DataType >::LoadWeights0(), and lczero::cudnn_backend::ResidualBlock< DataType >::LoadWeights1().
FromType() [1/2]
float lczero::cudnn_backend::FromType (float src) inline
Definition at line 46 of file inputs_outputs.h.
Referenced by lczero::CudaNetwork< DataType >::finishEval(), lczero::CudnnNetwork< DataType >::finishEval(), lczero::CudaNetworkComputation< DataType >::GetMVal(), lczero::CudnnNetworkComputation< DataType >::GetMVal(), lczero::CudaNetworkComputation< DataType >::GetPVal(), lczero::CudnnNetworkComputation< DataType >::GetPVal(), lczero::CudaNetworkComputation< DataType >::GetQVal(), and lczero::CudnnNetworkComputation< DataType >::GetQVal().
FromType() [2/2]
float lczero::cudnn_backend::FromType (half src) inline
Definition at line 47 of file inputs_outputs.h.
References lczero::FP16toFP32().
fusedMHA()
void lczero::cudnn_backend::fusedMHA (void * output, void * mha_q, void * mha_k, void * mha_v, void * skip, int batch_size, int num_heads, int depth, cudaStream_t stream)
Referenced by lczero::cudnn_backend::EncoderBlock< DataType >::Eval().
genOffsetPointers()
template<typename T > void lczero::cudnn_backend::genOffsetPointers (T ** offsets, int heads, int max_batch, int depth, int d_model, T * k, T * q, T * b1, T * v, T * b2, cudaStream_t stream)
Referenced by lczero::cudnn_backend::EncoderBlock< DataType >::Eval().
globalAvgPool()
template<typename T > void lczero::cudnn_backend::globalAvgPool (int N, int C, T * output, const T * input, const T * prevLayerBias, bool nhwc, cudaStream_t steam)
Performs global average pooling.
Referenced by lczero::cudnn_backend::SELayer< DataType >::Eval(), and lczero::cudnn_backend::SELayer< DataType >::Eval().
globalScale()
template<typename T > void lczero::cudnn_backend::globalScale (int N, int C, T * output, const T * input, const T * scaleBias, const T * prevLayerBias, bool nhwc, ActivationFunction activation, cudaStream_t steam)
Referenced by lczero::cudnn_backend::SELayer< DataType >::Eval(), and lczero::cudnn_backend::SELayer< DataType >::Eval().
inputPreprocessForAttentionBody()
template<typename T > void lczero::cudnn_backend::inputPreprocessForAttentionBody (T * output, const T * input, const T * encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, cudaStream_t stream)
Referenced by lczero::cudnn_backend::AttentionBody< DataType >::Eval().
InputTransform()
template<typename T , bool nhcw> void lczero::cudnn_backend::InputTransform (int N, int C, T * transformedInput, const T * input, cudaStream_t stream)
LayerNorm()
template<typename T > void lczero::cudnn_backend::LayerNorm (int N, int C, T * output, const T * input, const T * bias, const T * skip, const T * gammas, const T * betas, float ep, float alpha, ActivationFunction act, cudaStream_t stream)
OutputInputTransform()
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip> void lczero::cudnn_backend::OutputInputTransform (int N, int C, int se_K, T * output, const T * input, const T * skip, const T * bias, const T * w1, const T * b1, const T * w2, const T * b2, cudaStream_t stream)
OutputTransform()
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip, bool skipInput_nhcw, bool output_nhcw> void lczero::cudnn_backend::OutputTransform (int N, int C, int se_K, T * output, const T * input, const T * skip, const T * bias, const T * w1, const T * b1, const T * w2, const T * b2, cudaStream_t stream)
Referenced by lczero::cudnn_backend::FusedWinogradConvSELayer< DataType >::Eval(), and lczero::cudnn_backend::ResidualBlock< DataType >::Eval().
PolicyMap()
template<typename T > void lczero::cudnn_backend::PolicyMap (int N, T * output, const T * input, const short * indices, int inputSize, int usedSize, int outputSize, cudaStream_t stream)
Referenced by lczero::cudnn_backend::PolicyMapLayer< DataType >::Eval().
Se_Fp16_NHWC()
bool lczero::cudnn_backend::Se_Fp16_NHWC (int N, int C, int numFc1Out, half * output, const half * skip, const half * input, const half * w1, const half * b1, const half * w2, const half * b2, const half * bPrev, ActivationFunction activation, cudaStream_t stream)
Performs Squeeze-and-Excitation (SE) in a single fused kernel.
Returns
False if the fused kernel can't handle the sizes.
Referenced by lczero::cudnn_backend::SELayer< DataType >::Eval().
Softmax()
template<typename T > void lczero::cudnn_backend::Softmax (int N, int C, T * output, const T * input, const T * input2, cudaStream_t stream)
Referenced by lczero::cudnn_backend::EncoderBlock< DataType >::Eval().
ToType() [1/2]
void lczero::cudnn_backend::ToType (float & dst, float src) inline
Definition at line 40 of file inputs_outputs.h.
Referenced by lczero::CudaNetworkComputation< DataType >::AddInput(), and lczero::CudnnNetworkComputation< DataType >::AddInput().
ToType() [2/2]
void lczero::cudnn_backend::ToType (half & dst, float src) inline
Definition at line 41 of file inputs_outputs.h.
References lczero::FP32toFP16().
Variable Documentation
kMaxResBlockFusingChannels
constexpr int lczero::cudnn_backend::kMaxResBlockFusingChannels = 384 static constexpr
Maximum supported filter count for residual block fusing.
Limited by number of registers per thread.
Definition at line 56 of file cuda_common.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::Eval().
kMaxResBlockFusingSeFp16AmpereSmem
constexpr int lczero::cudnn_backend::kMaxResBlockFusingSeFp16AmpereSmem static constexpr
Initial value:
=
    72 * kMaxResBlockFusingSeKFp16Ampere *
    sizeof(half)
Definition at line 61 of file cuda_common.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::Eval().
kMaxResBlockFusingSeK
constexpr int lczero::cudnn_backend::kMaxResBlockFusingSeK static constexpr
Initial value:
=
    128
Definition at line 59 of file cuda_common.h.
kMaxResBlockFusingSeKFp16Ampere
constexpr int lczero::cudnn_backend::kMaxResBlockFusingSeKFp16Ampere static constexpr
Initial value:
=
    512
Definition at line 57 of file cuda_common.h.
Referenced by lczero::cudnn_backend::ResidualBlock< DataType >::Eval().
kNumOutputPolicy
constexpr int lczero::cudnn_backend::kNumOutputPolicy = 1858 static constexpr
Maximum number of output policy channels.
Definition at line 52 of file cuda_common.h.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), lczero::SyclNetwork< DataType >::forwardEval(), lczero::OnednnNetwork::forwardEval(), lczero::CudaNetwork< DataType >::forwardEval(), lczero::CudnnNetwork< DataType >::forwardEval(), lczero::CudaNetworkComputation< DataType >::GetPVal(), lczero::CudnnNetworkComputation< DataType >::GetPVal(), lczero::OnednnNetworkComputation::GetPVal(), lczero::SyclNetworkComputation< DataType >::GetPVal(), lczero::InputsOutputs::InputsOutputs(), lczero::cudnn_backend::InputsOutputs< DataType >::InputsOutputs(), lczero::OnednnNetwork::OnednnNetwork(), and lczero::SyclNetwork< DataType >::SyclNetwork().
kUseFusedSELayer
constexpr bool lczero::cudnn_backend::kUseFusedSELayer = true static constexpr
Definition at line 102 of file layers.cc.
Referenced by lczero::cudnn_backend::SELayer< DataType >::Eval(), lczero::cudnn_backend::SELayer< DataType >::LoadWeights(), and lczero::cudnn_backend::SELayer< DataType >::SELayer().