Leela Chess Zero: lczero::classic Namespace Reference
lczero::classic Namespace Reference
Classes
class BaseSearchParams
Base configuration parameters for MCTS search.
class ChainedSearchStopper
Composite stopper that chains multiple stoppers together.
class DepthStopper
Stopper that enforces a minimum search depth.
class Edge
Represents an edge in the MCTS game tree connecting a parent node to a child move.
class Edge_Iterator
class EdgeAndNode
Composite class holding an Edge and its corresponding Node pointer.
struct Eval
Container for neural network evaluation outputs.
struct IterationStats
Statistics from search sent to stoppers for stopping decisions.
class KldGainStopper
Stopper based on Kullback-Leibler divergence gain.
class MateStopper
Stopper that stops when a forced mate is found.
class MemoryWatchingStopper
Stopper that limits tree size based on available memory.
class Node
Represents a node in the MCTS (Monte Carlo Tree Search) game tree.
class NodeTree
Manages the MCTS game tree and position history.
class PlayoutsStopper
Stopper that limits search by new tree nodes (playouts).
class Search
Main MCTS search engine for the classic search implementation.
class SearchParams
Extended search parameters with additional classic-search-specific options.
class SearchStopper
Abstract base class for search stopping conditions.
class SearchWorker
Single-threaded worker for MCTS search iterations.
class SmartPruningStopper
Smart pruning stopper for early search termination.
class StoppersHints
Hints from stoppers back to the search engine.
class TimeLimitStopper
Stopper that enforces a fixed time limit.
class TimeManager
Abstract factory for creating search stoppers.
class VisitedNode_Iterator
class VisitsStopper
Stopper that limits search by total tree nodes (visits).
Enumerations
enum class ContemptMode { PLAY , WHITE , BLACK , NONE }
Contempt mode for adjusting draw value.
enum class RunType { kUci , kSelfplay }
Execution context for time management options.
Functions
static bool operator< (const EdgeAndNode &, const EdgeAndNode &)
std::unique_ptr< TimeManager > MakeAlphazeroTimeManager (int64_t move_overhead, const OptionsDict &params)
Creates an AlphaZero-style time manager.
void PopulateCommonStopperOptions (RunType for_what, OptionsParser *options)
Populates common stopper options for all time managers.
void PopulateIntrinsicStoppers (ChainedSearchStopper *stopper, const OptionsDict &options)
Adds KLD gain and smart pruning stoppers to a chain.
std::unique_ptr< TimeManager > MakeCommonTimeManager (std::unique_ptr< TimeManager > child_manager, const OptionsDict &options, int64_t move_overhead)
Wraps a time manager with common stopping conditions.
void PopulateTimeManagementOptions (RunType for_what, OptionsParser *options)
Populates options parser with time management configuration.
std::unique_ptr< TimeManager > MakeTimeManager (const OptionsDict &dict)
Creates a time manager based on configuration.
float ComputeEstimatedMovesToGo (int ply, float midpoint, float steepness)
Estimates moves remaining in the game using a standard formula.
std::unique_ptr< TimeManager > MakeLegacyTimeManager (int64_t move_overhead, const OptionsDict &params)
Creates a legacy time manager.
std::unique_ptr< TimeManager > MakeSimpleTimeManager (int64_t move_overhead, const OptionsDict &params)
Creates a simple time manager.
std::unique_ptr< TimeManager > MakeSmoothTimeManager (int64_t move_overhead, const OptionsDict &params)
Creates a smooth time manager.
Enumeration Type Documentation
ContemptMode
enum class lczero::classic::ContemptMode strong
Contempt mode for adjusting draw value.
Controls how the engine treats draws against opponents.
Enumerator
PLAY
Contempt active during normal play.
WHITE
Analyze from white's perspective.
BLACK
Analyze from black's perspective.
NONE
Contempt disabled.
Definition at line 39 of file params.h.
RunType
enum class lczero::classic::RunType strong
Execution context for time management options.
Enumerator
kUci
Running as UCI chess engine.
kSelfplay
Running in self-play/training mode.
Definition at line 38 of file common.h.
Function Documentation
ComputeEstimatedMovesToGo()
float lczero::classic::ComputeEstimatedMovesToGo (int ply, float midpoint, float steepness)
Estimates moves remaining in the game using a standard formula.
Used by legacy time management to adjust time allocation.
Parameters
ply Current game ply (half-move number).
midpoint Midpoint parameter for the estimation curve.
steepness Steepness parameter for the estimation curve.
Returns
Estimated number of moves remaining.
Definition at line 37 of file legacy.cc.
MakeAlphazeroTimeManager()
std::unique_ptr< TimeManager > lczero::classic::MakeAlphazeroTimeManager (int64_t move_overhead, const OptionsDict & params)
Creates an AlphaZero-style time manager.
This time manager attempts to replicate the time management strategy used by AlphaZero, typically using a fixed percentage of remaining time per move.
Parameters
move_overhead Overhead time per move in milliseconds to subtract.
params Configuration options for the time manager.
Returns
Unique pointer to the AlphaZero time manager.
Definition at line 81 of file alphazero.cc.
Referenced by MakeTimeManager().
MakeCommonTimeManager()
std::unique_ptr< TimeManager > lczero::classic::MakeCommonTimeManager (std::unique_ptr< TimeManager > child_manager, const OptionsDict & options, int64_t move_overhead)
Wraps a time manager with common stopping conditions.
Adds memory limits, move overhead, and intrinsic stoppers.
Parameters
child_manager The base time manager to wrap.
options Configuration options.
move_overhead Overhead time per move in milliseconds.
Returns
Wrapped time manager with common conditions.
Definition at line 202 of file common.cc.
Referenced by MakeTimeManager().
MakeLegacyTimeManager()
std::unique_ptr< TimeManager > lczero::classic::MakeLegacyTimeManager (int64_t move_overhead, const OptionsDict & params)
Creates a legacy time manager.
Implements traditional chess engine time management strategies, taking into account increments, moves to go, and estimated game length.
Parameters
move_overhead Overhead time per move in milliseconds.
params Configuration options including curve parameters.
Returns
Unique pointer to the legacy time manager.
Definition at line 180 of file legacy.cc.
Referenced by MakeTimeManager().
MakeSimpleTimeManager()
std::unique_ptr< TimeManager > lczero::classic::MakeSimpleTimeManager (int64_t move_overhead, const OptionsDict & params)
Creates a simple time manager.
A basic time manager that typically allocates a fixed fraction of remaining time or a fixed time per move.
Parameters
move_overhead Overhead time per move in milliseconds.
params Configuration options.
Returns
Unique pointer to the simple time manager.
Definition at line 133 of file simple.cc.
Referenced by MakeTimeManager().
MakeSmoothTimeManager()
std::unique_ptr< TimeManager > lczero::classic::MakeSmoothTimeManager (int64_t move_overhead, const OptionsDict & params)
Creates a smooth time manager.
A sophisticated time manager that aims for smooth time usage across moves, avoiding erratic time consumption.
Parameters
move_overhead Overhead time per move in milliseconds.
params Configuration options.
Returns
Unique pointer to the smooth time manager.
Definition at line 655 of file smooth.cc.
References MakeSmoothTimeManager().
Referenced by MakeSmoothTimeManager(), and MakeTimeManager().
MakeTimeManager()
std::unique_ptr< TimeManager > lczero::classic::MakeTimeManager (const OptionsDict & dict)
Creates a time manager based on configuration.
Factory function that instantiates the appropriate TimeManager implementation based on the options dictionary settings.
Parameters
dict Options dictionary with time management configuration.
Returns
Unique pointer to configured TimeManager.
Definition at line 77 of file factory.cc.
References lczero::OptionsDict::AddSubdictFromString(), lczero::OptionsDict::Get(), lczero::OptionsDict::IsDefault(), MakeAlphazeroTimeManager(), MakeCommonTimeManager(), MakeLegacyTimeManager(), MakeSimpleTimeManager(), and MakeSmoothTimeManager().
operator<()
static bool lczero::classic::operator< (const EdgeAndNode & , const EdgeAndNode &) static
Definition at line 473 of file search.cc.
PopulateCommonStopperOptions()
void lczero::classic::PopulateCommonStopperOptions (RunType for_what, OptionsParser * options)
Populates common stopper options for all time managers.
Parameters
for_what The execution context (UCI or selfplay).
options The options parser to populate.
Definition at line 88 of file common.cc.
References lczero::OptionsParser::Add(), and kUci.
Referenced by PopulateTimeManagementOptions().
PopulateIntrinsicStoppers()
void lczero::classic::PopulateIntrinsicStoppers (ChainedSearchStopper * stopper, const OptionsDict & options)
Adds KLD gain and smart pruning stoppers to a chain.
Configures intrinsic stopping conditions that apply regardless of the time management strategy.
Parameters
stopper The chained stopper to populate.
options Configuration options dictionary.
Definition at line 99 of file common.cc.
References lczero::classic::ChainedSearchStopper::AddStopper(), and lczero::OptionsDict::Get().
Referenced by lczero::SelfPlayGame::Play().
PopulateTimeManagementOptions()
void lczero::classic::PopulateTimeManagementOptions (RunType for_what, OptionsParser * options)
Populates options parser with time management configuration.
Adds UCI options for time control and stopper behavior.
Parameters
for_what Whether options are for UCI or selfplay mode.
options The options parser to populate.
Definition at line 69 of file factory.cc.
References lczero::OptionsParser::Add(), and PopulateCommonStopperOptions().