Leela Chess Zero: lczero::onnx Namespace Reference
lczero::onnx Namespace Reference
Classes
struct InputsOutputs
Manages input and output buffers for the ONNX network.
class OnnxComputation
ONNX computation class.
class OnnxNetwork
ONNX network implementation.
Enumerations
enum class OnnxProvider {
CPU , CUDA , DML , ROCM ,
TRT , MIGRAPHX
}
Supported ONNX execution providers.
Functions
void AsDataType (float x, float *y)
void AsDataType (float x, Ort::Float16_t *y)
void AsDataType (float x, Ort::BFloat16_t *y)
float AsFloat (float x)
float AsFloat (Ort::Float16_t x)
float AsFloat (Ort::BFloat16_t x)
template<OnnxProvider kProvider>
std::unique_ptr< Network > MakeOnnxNetwork (const std::optional< WeightsFile > &w, const OptionsDict &opts)
template<typename DataType >
void expandPlanesOnnx (DataType *output, const void *input, unsigned n, cudaStream_t stream)
Expands input planes from bitmask to floating point tensors.
void CudaError (cudaError_t status, const char *file, int line)
int DivUp (int a, int b)
Variables
static constexpr int kNumOutputPolicy = 1858
Constant for the number of output policy channels.
Enumeration Type Documentation
OnnxProvider
enum class lczero::onnx::OnnxProvider strong
Supported ONNX execution providers.
Enumerator
CPU
CUDA
DML
ROCM
TRT
MIGRAPHX
Definition at line 64 of file network_onnx.cc.
Function Documentation
AsDataType() [1/3]
void lczero::onnx::AsDataType (float x, float * y)
Definition at line 337 of file network_onnx.cc.
Referenced by lczero::onnx::OnnxComputation< DataType >::AddInput(), and lczero::onnx::OnnxComputation< DataType >::PrepareInputs().
AsDataType() [2/3]
void lczero::onnx::AsDataType (float x, Ort::BFloat16_t * y)
Definition at line 342 of file network_onnx.cc.
References lczero::FP32toBF16().
AsDataType() [3/3]
void lczero::onnx::AsDataType (float x, Ort::Float16_t * y)
Definition at line 338 of file network_onnx.cc.
References lczero::FP32toFP16().
AsFloat() [1/3]
float lczero::onnx::AsFloat (float x)
Definition at line 387 of file network_onnx.cc.
Referenced by lczero::onnx::OnnxComputation< DataType >::ComputeBlocking(), lczero::onnx::OnnxComputation< DataType >::GetMVal(), lczero::onnx::OnnxComputation< DataType >::GetPVal(), and lczero::onnx::OnnxComputation< DataType >::GetQVal().
AsFloat() [2/3]
float lczero::onnx::AsFloat (Ort::BFloat16_t x)
Definition at line 393 of file network_onnx.cc.
References lczero::BF16toFP32().
AsFloat() [3/3]
float lczero::onnx::AsFloat (Ort::Float16_t x)
Definition at line 388 of file network_onnx.cc.
References lczero::FP16toFP32().
CudaError()
void lczero::onnx::CudaError (cudaError_t status, const char * file, int line)
DivUp()
int lczero::onnx::DivUp (int a, int b) inline
Definition at line 51 of file onnx_kernels.h.
expandPlanesOnnx()
template<typename DataType > void lczero::onnx::expandPlanesOnnx (DataType * output, const void * input, unsigned n, cudaStream_t stream)
Expands input planes from bitmask to floating point tensors.
Used as a preprocessing step for ONNX models.
Template Parameters
DataType Type of the output tensor data (float, half, bfloat16).
Parameters
output Output tensor data pointer.
input Input bitmask pointer.
n Number of elements to process.
stream CUDA stream.
Referenced by lczero::onnx::OnnxComputation< DataType >::ComputeBlocking().
MakeOnnxNetwork()
template<OnnxProvider kProvider> std::unique_ptr< Network > lczero::onnx::MakeOnnxNetwork (const std::optional< WeightsFile > & w, const OptionsDict & opts)
Definition at line 914 of file network_onnx.cc.
References lczero::WeightsToOnnxConverterOptions::alt_layernorm, lczero::WeightsToOnnxConverterOptions::alt_mish, lczero::ConvertWeightsToOnnx(), CPU, lczero::WeightsToOnnxConverterOptions::data_type, DML, lczero::OptionsDict::Exists(), lczero::OptionsDict::Get(), lczero::OptionsDict::GetOrDefault(), lczero::WeightsToOnnxConverterOptions::ir, lczero::WeightsToOnnxConverterOptions::kBFloat16, lczero::WeightsToOnnxConverterOptions::no_shape, lczero::WeightsToOnnxConverterOptions::no_wdl_softmax, lczero::WeightsToOnnxConverterOptions::opset, lczero::WeightsToOnnxConverterOptions::policy_head, lczero::WeightsToOnnxConverterOptions::real_mish, lczero::WeightsToOnnxConverterOptions::StringToDataType(), and lczero::WeightsToOnnxConverterOptions::value_head.
Variable Documentation
kNumOutputPolicy
constexpr int lczero::onnx::kNumOutputPolicy = 1858 static constexpr
Constant for the number of output policy channels.
Definition at line 69 of file network_onnx.cc.
Referenced by lczero::onnx::OnnxComputation< DataType >::GetPVal(), and lczero::onnx::InputsOutputs::InputsOutputs().