Leela Chess Zero: lczero::sycldnn_backend Namespace Reference
lczero::sycldnn_backend Namespace Reference
Implements the neural network backend using SYCL for GPU acceleration.
The sycldnn_backend leverages the SYCL abstraction layer to run Leela's neural network computations on a wide range of hardware, including Intel, AMD, and NVIDIA GPUs. It provides optimized implementations for key neural network layers such as:
Winograd Convolution: High-performance convolution for 3x3 filters (FusedWinogradConvSELayer).
Fully Connected Layers: Efficient matrix multiplication for the policy and value heads (FCLayer).
Squeeze-and-Excitation: Optimized kernels for the SE blocks (SELayer).
The backend manages memory and execution queues via the SyclContext and ensures thread-safe execution of concurrent search tasks.
Classes
class AttentionBody
Attention Body.
class AttentionPolicyHead
Attention Policy Head.
class BaseLayer
Base class for neural network layers in SYCL backend.
class Conv1Layer
1x1 Convolution Layer.
struct DeviceCapabilities
Helper class to query and cache device capabilities.
class EmbeddingLayer
Embedding Layer.
class EncoderBlock
Encoder Block Layer (part of Transformer architecture).
class FCLayer
Fully Connected Layer.
class FusedWinogradConvSELayer
Multi-pass Winograd Convolution fused with (optional) SE.
struct InputsOutputs
Manages input and output buffers for the SYCL network.
class PolicyMapLayer
Policy Map Layer.
class ResidualBlock
Residual Block Layer.
class SELayer
Fused Squeeze-and-Excitation (SE) Layer.
class ValueHead
Value Head.
Functions
template<typename T >
void addVectors_kernel (T *c, T *a, T *b, int size, int asize, int bsize, ActivationFunction activation, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void addVectors (T *c, T *a, T *b, int size, int asize, int bsize, ActivationFunction activation, sycl::queue &sycl_queue)
Adds two vectors (possibly of different sizes), with optional activation.
template<typename T >
void addVectorsHNC_NHC_kernel (T *a, T *b, int N, int H, int C, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void addVectorsHNC_NHC (T *a, T *b, int N, int H, int C, sycl::queue &sycl_queue)
Adds two vectors of equal size, overwriting the first.
template<typename T , ActivationFunction act>
void addBiasBatched_kernel (T *output, const T *input, const T *bias, int N, int C, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void addBiasBatched (T *output, const T *input, const T *bias, int Batch, int N, int C, ActivationFunction activation, sycl::queue &sycl_queue)
Adds bias to innermost dimension and performs optional activation.
template<typename T , ActivationFunction act>
void addBiasBatched_kernel (T *output, const T *input, const T *bias, int N, int C, int Nstride, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void addBiasBatched (T *output, const T *input, const T *bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, sycl::queue &sycl_queue)
template<typename T >
void addBias_NCHW_kernel (T *c, T *a, T *b, int N, int C, int H, int W, ActivationFunction activation, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void addBias_NCHW (T *c, T *a, T *b, int N, int C, int H, int W, ActivationFunction activation, sycl::queue &sycl_queue)
Adds bias to convolution's output.
template<typename dT , typename sT >
dT readNCHW (const sT *input_tensor, int n, int c, int h, int w, int Nin, int Cin, int H, int W)
template<typename dT , typename sT >
void NCHWtoNHWC_kernel (dT *output_tensor, const sT *input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, const sycl::nd_item< 3 > &item_ct1)
template<typename DstType , typename SrcType >
void convertNCHWtoNHWC (DstType *output_tensor, const SrcType *input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue &sycl_queue)
Converts tensor from NCHW to NHWC layout.
template<typename DstType , typename SrcType >
void copyTypeConverted_kernel (DstType *op, SrcType *ip, int N, const sycl::nd_item< 3 > &item_ct1)
template<typename DstType , typename SrcType >
void copyTypeConverted (DstType *op, SrcType *ip, int N, sycl::queue &sycl_queue)
template<typename T >
void batchNorm_kernel (T *output, const T *input, const T *skipInput, int N, int C, int H, int W, const float *means, const float *varMultipliers, ActivationFunction activation, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void batchNorm (T *output, const T *input, const T *skipInput, int N, int C, int H, int W, float *means, float *var_multipliers, ActivationFunction activation, sycl::queue &sycl_queue)
Performs batch normalization.
void expandPlanes_kernel_Fp32_NCHW (float *output, const uint64_t *masks, const float *values, int n, const sycl::nd_item< 3 > &item_ct1, uint64_t *shMasks, float *shVals)
void expandPlanes_Fp32_NCHW (float *output, const uint64_t *masks, const float *values, int n, sycl::queue &sycl_queue)
void expandPlanes_kernel_Fp16_NHWC (sycl::half *output, const uint64_t *masks, const float *values, int n, const sycl::nd_item< 3 > &item_ct1)
void expandPlanes_Fp16_NHWC (sycl::half *output, const uint64_t *masks, const float *values, int n, sycl::queue &sycl_queue)
void expandPlanes_kernel_Fp16_NCHW (sycl::half *output, const uint64_t *masks, const float *values, int n, const sycl::nd_item< 3 > &item_ct1, uint64_t *shMasks, sycl::half *shVals)
void expandPlanes_Fp16_NCHW (sycl::half *output, const uint64_t *masks, const float *values, int n, sycl::queue &sycl_queue)
template<typename T >
void globalScale_kernel (T *output, const T *input, const T *scaleBias, const T *prevLayerBias, int inputSize, int C, ActivationFunction activation, const sycl::nd_item< 3 > &item_ct1)
void globalScale_kernel_fp16_nhwc (sycl::half *output, const sycl::half *input, const sycl::half *scaleBias, const sycl::half *prevLayerBias, int inputSize, int C, int HWC, ActivationFunction activation, const sycl::nd_item< 3 > &item_ct1)
void globalAvgPool_kernel_NHWC_fp16 (sycl::half *output, const sycl::half *input, const sycl::half *prevLayerBias, int inputSize, int outputSize, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void globalAvgPool_kernel (T *output, const T *input, const T *prevLayerBias, int inputSize, int outputSize, int C, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void globalAvgPool (int N, int C, T *output, const T *input, const T *prevLayerBias, bool nhwc, sycl::queue &sycl_queue)
Performs global average pooling.
template<typename T >
void globalScale (int N, int C, T *output, const T *input, const T *scaleBias, const T *prevLayerBias, bool nhwc, ActivationFunction activation, sycl::queue &sycl_queue)
template<typename T >
void policyMap_kernel (T *output, const T *input, const short *indices, int N, int inputSize, int usedSize, int outputSize, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void PolicyMap (int N, T *output, const T *input, const short *indices, int inputSize, int usedSize, int outputSize, sycl::queue &sycl_queue)
template<typename T = float, bool use_se, ActivationFunction activation, bool use_bias, bool use_skip>
void OutputInputTransform (int N, int C, int se_K, T *output, const T *input, const T *skip, const T *bias, const T *w1, const T *b1, const T *w2, const T *b2, sycl::queue &sycl_queue)
template<typename T >
void softmax_opt_64_kernel (T *output, const T *input, const T *input2, int N, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void softmax_kernel (T *output, const T *input, const T *input2, const sycl::nd_item< 3 > &item_ct1, float &localsum, float &localmax)
template<typename T >
void Softmax (int N, int C, T *output, const T *input, const T *input2, sycl::queue &sycl_queue)
float shared_sum_for_layer_norm (float x, const sycl::nd_item< 3 > &item_ct1, sycl::local_accessor< float, 2 > sum)
template<typename T >
void layer_norm_kernel (int N, int C, T *output, const T *input, const T *bias, const T *skip, const T *gammas, const T *betas, float ep, float alpha, ActivationFunction act, const sycl::nd_item< 3 > &item_ct1, sycl::local_accessor< float, 2 > sum)
template<typename T >
void LayerNorm (int N, int C, T *output, const T *input, const T *bias, const T *skip, const T *gammas, const T *betas, float ep, float alpha, ActivationFunction act, sycl::queue &sycl_queue)
template<typename T >
void promotion_logits_kernel (int C, T *output, const T *keys, const T *ppo, const T *policy_attn_logits, const sycl::nd_item< 3 > &item_ct1, sycl::local_accessor< float, 2 > promotion_offsets)
template<typename T >
void ComputePromotionLogits (int N, int C, T *output, const T *keys, const T *ppo, const T *policy_attn_logits, sycl::queue &sycl_queue)
template<typename T >
void preprocess_for_attention_body_kernel (T *output, const T *input, const T *encoding, int input_size, int encoding_size, bool is_pe_dense_embedding, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void inputPreprocessForAttentionBody (T *output, const T *input, const T *encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, sycl::queue &sycl_queue)
template<typename T >
void input_gating_kernel (T *output, const T *input, const T *mult, const T *add, int HW, int C, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void applyInputGating (T *output, const T *input, const T *mult, const T *add, int N, int HW, int C, sycl::queue &sycl_queue)
template<typename T , int kWorkPerThread>
static void genOffsetPointers_kernel (T **offsets, int heads, int block_size, int depth, int d_model, T *k, T *q, T *b1, T *v, T *b2, const sycl::nd_item< 1 > &item_ct)
template<typename T >
void genOffsetPointers (T **offsets, int heads, int max_batch, int depth, int d_model, T *k, T *q, T *b1, T *v, T *b2, sycl::queue &sycl_queue)
template void copyTypeConverted< sycl::half, float > (sycl::half *op, float *ip, int N, sycl::queue &sycl_queue)
template void copyTypeConverted< float, sycl::half > (float *op, sycl::half *ip, int N, sycl::queue &sycl_queue)
template void copyTypeConverted< float, float > (float *op, float *ip, int N, sycl::queue &sycl_queue)
template void copyTypeConverted< sycl::half, sycl::half > (sycl::half *op, sycl::half *ip, int N, sycl::queue &sycl_queue)
template void batchNorm< float > (float *output, const float *input, const float *skipInput, int N, int C, int H, int W, float *means, float *var_multipliers, ActivationFunction activation, sycl::queue &sycl_queue)
template void batchNorm< sycl::half > (sycl::half *output, const sycl::half *input, const sycl::half *skipInput, int N, int C, int H, int W, float *means, float *var_multipliers, ActivationFunction activation, sycl::queue &sycl_queue)
template void addVectors< float > (float *c, float *a, float *b, int size, int asize, int bsize, ActivationFunction act, sycl::queue &sycl_queue)
template void addVectors< sycl::half > (sycl::half *c, sycl::half *a, sycl::half *b, int size, int asize, int bsize, ActivationFunction act, sycl::queue &sycl_queue)
template void addVectorsHNC_NHC< float > (float *a, float *b, int N, int H, int C, sycl::queue &sycl_queue)
template void addVectorsHNC_NHC< sycl::half > (sycl::half *a, sycl::half *b, int N, int H, int C, sycl::queue &sycl_queue)
template void addBiasBatched< float > (float *output, const float *input, const float *bias, int Batch, int N, int C, ActivationFunction activation, sycl::queue &sycl_queue)
template void addBiasBatched< sycl::half > (sycl::half *output, const sycl::half *input, const sycl::half *bias, int Batch, int N, int C, ActivationFunction activation, sycl::queue &sycl_queue)
template void addBiasBatched< float > (float *output, const float *input, const float *bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, sycl::queue &sycl_queue)
template void addBiasBatched< sycl::half > (sycl::half *output, const sycl::half *input, const sycl::half *bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, sycl::queue &sycl_queue)
template void addBias_NCHW< float > (float *c, float *a, float *b, int N, int C, int H, int W, ActivationFunction activation, sycl::queue &sycl_queue)
template void addBias_NCHW< sycl::half > (sycl::half *c, sycl::half *a, sycl::half *b, int N, int C, int H, int W, ActivationFunction activation, sycl::queue &sycl_queue)
template void globalAvgPool< float > (int N, int C, float *output, const float *input, const float *prevLayerBias, bool nhwc, sycl::queue &sycl_queue)
template void globalAvgPool< sycl::half > (int N, int C, sycl::half *output, const sycl::half *input, const sycl::half *prevLayerBias, bool nhwc, sycl::queue &sycl_queue)
template void globalScale< float > (int N, int C, float *output, const float *input, const float *scaleBias, const float *prevLayerBias, bool nhwc, ActivationFunction activation, sycl::queue &sycl_queue)
template void globalScale< sycl::half > (int N, int C, sycl::half *output, const sycl::half *input, const sycl::half *scaleBias, const sycl::half *prevLayerBias, bool nhwc, ActivationFunction activation, sycl::queue &sycl_queue)
template void PolicyMap< float > (int N, float *output, const float *input, const short *indices, int inputSize, int usedSize, int outputSize, sycl::queue &sycl_queue)
template void PolicyMap< sycl::half > (int N, sycl::half *output, const sycl::half *input, const short *indices, int inputSize, int usedSize, int outputSize, sycl::queue &sycl_queue)
template void FilterTransform< float > (int N, int C, float *transformedFilter, const float *filter, sycl::queue &sycl_queue)
template void InputTransform< float, true > (int N, int C, float *transformed_input, const float *input, sycl::queue &sycl_queue)
template void InputTransform< float, false > (int N, int C, float *transformed_input, const float *input, sycl::queue &sycl_queue)
template void OutputTransform< float, true, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, true, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_RELU, true, false, false, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_RELU, true, false, false, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, true, ACTIVATION_RELU, true, true, true, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, true, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, true, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_MISH, true, false, false, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_MISH, true, false, false, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, true, ACTIVATION_MISH, true, true, true, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputTransform< float, false, ACTIVATION_NONE, true, false, false, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< float, true, ACTIVATION_RELU, true, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< float, false, ACTIVATION_RELU, true, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< float, false, ACTIVATION_RELU, true, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< float, true, ACTIVATION_MISH, true, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< float, false, ACTIVATION_MISH, true, true > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< float, false, ACTIVATION_MISH, true, false > (int N, int C, int se_K, float *output, const float *input, const float *skip, const float *bias, const float *w1, const float *b1, const float *w2, const float *b2, sycl::queue &sycl_queue)
template void Softmax< sycl::half > (int N, int C, sycl::half *output, const sycl::half *input, const sycl::half *input2, sycl::queue &sycl_queue)
template void Softmax< float > (int N, int C, float *output, const float *input, const float *input2, sycl::queue &sycl_queue)
template void LayerNorm< sycl::half > (int N, int C, sycl::half *output, const sycl::half *input, const sycl::half *bias, const sycl::half *skip, const sycl::half *gammas, const sycl::half *betas, float ep, float alpha, ActivationFunction act, sycl::queue &sycl_queue)
template void LayerNorm< float > (int N, int C, float *output, const float *input, const float *bias, const float *skip, const float *gammas, const float *betas, float ep, float alpha, ActivationFunction act, sycl::queue &sycl_queue)
template void ComputePromotionLogits< sycl::half > (int N, int C, sycl::half *output, const sycl::half *keys, const sycl::half *ppo, const sycl::half *policy_attn_logits, sycl::queue &sycl_queue)
template void ComputePromotionLogits< float > (int N, int C, float *output, const float *keys, const float *ppo, const float *policy_attn_logits, sycl::queue &sycl_queue)
template void convertNCHWtoNHWC< sycl::half, float > (sycl::half *output_tensor, const float *input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue &sycl_queue)
template void convertNCHWtoNHWC< float, float > (float *output_tensor, const float *input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue &sycl_queue)
template void convertNCHWtoNHWC< sycl::half, sycl::half > (sycl::half *output_tensor, const sycl::half *input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue &sycl_queue)
template void inputPreprocessForAttentionBody< sycl::half > (sycl::half *output, const sycl::half *input, const sycl::half *encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, sycl::queue &sycl_queue)
template void inputPreprocessForAttentionBody< float > (float *output, const float *input, const float *encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, sycl::queue &sycl_queue)
template void applyInputGating< sycl::half > (sycl::half *output, const sycl::half *input, const sycl::half *mult, const sycl::half *add, int N, int C, int output_size, sycl::queue &sycl_queue)
template void applyInputGating< float > (float *output, const float *input, const float *mult, const float *add, int N, int C, int output_size, sycl::queue &sycl_queue)
template void genOffsetPointers< float > (float **offsets, int heads, int max_batch, int depth, int d_model, float *k, float *q, float *b1, float *v, float *b2, sycl::queue &sycl_queue)
template void genOffsetPointers< sycl::half > (sycl::half **offsets, int heads, int max_batch, int depth, int d_model, sycl::half *k, sycl::half *q, sycl::half *b1, sycl::half *v, sycl::half *b2, sycl::queue &sycl_queue)
template<int C, int K>
void SE_Layer_NHWC (sycl::half *output, const sycl::half *skip, const sycl::half *input, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, const sycl::half *bPrev, ActivationFunction activation, const sycl::nd_item< 3 > &item_ct1, sycl::half *sharedData)
bool Se_Fp16_NHWC (int N, int C, int numFc1Out, sycl::half *output, const sycl::half *skip, const sycl::half *input, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, const sycl::half *bPrev, ActivationFunction activation, sycl::queue &sycl_queue)
Performs Squeeze-and-Excitation (SE) in a single fused kernel.
template<ActivationFunction activation, bool use_bias, bool use_skip>
void OutputInputTransformKernel_fp16_shmem_board (int N, int C, int se_K, sycl::half *output, const sycl::half *input, sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, const sycl::nd_item< 3 > &item_ct1, uint8_t *dpct_local, float *shared_data, sycl::local_accessor< float, 2 > shared_sums)
template void FilterTransform< sycl::half > (int N, int C, sycl::half *transformedFilter, const sycl::half *filter, sycl::queue &sycl_queue)
template void InputTransform< sycl::half, true > (int N, int C, sycl::half *transformed_input, const sycl::half *input, sycl::queue &sycl_queue)
template void InputTransform< sycl::half, false > (int N, int C, sycl::half *transformed_input, const sycl::half *input, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_RELU, true, false, false, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_RELU, true, false, false, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, true, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_MISH, true, false, false, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_MISH, true, false, false, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, true, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputTransform< sycl::half, false, ACTIVATION_NONE, true, false, false, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< sycl::half, true, ACTIVATION_RELU, true, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< sycl::half, false, ACTIVATION_RELU, true, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< sycl::half, false, ACTIVATION_RELU, true, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< sycl::half, true, ACTIVATION_MISH, true, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< sycl::half, false, ACTIVATION_MISH, true, true > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template void OutputInputTransform< sycl::half, false, ACTIVATION_MISH, true, false > (int N, int C, int se_K, sycl::half *output, const sycl::half *input, const sycl::half *skip, const sycl::half *bias, const sycl::half *w1, const sycl::half *b1, const sycl::half *w2, const sycl::half *b2, sycl::queue &sycl_queue)
template<typename T >
void FilterTransform (int N, int C, T *transformedFilter, const T *filter, sycl::queue &sycl_queue)
Winograd filter transformation.
template<typename T , bool nhcw>
void InputTransform (int N, int C, T *transformedInput, const T *input, sycl::queue &sycl_queue)
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip, bool skipInput_nhcw, bool output_nhcw>
void OutputTransform (int N, int C, int se_K, T *output, const T *input, const T *skip, const T *bias, const T *w1, const T *b1, const T *w2, const T *b2, sycl::queue &sycl_queue)
void cpuTranspose (float *op, float *ip, int rows, int cols)
static void CpuTranspose (float *op, float *ip, size_t rows, size_t cols)
template<typename DataType >
void allocAndUpload (DataType **gpu_dest, std::vector< float > cpu_src, void *scratch, sycl::queue &sycl_queue)
template<typename DataType >
static void cublasXgemm (oneapi::mkl::transpose transa, oneapi::mkl::transpose transb, int m, int n, int k, float alpha, const DataType *A, int lda, const DataType *B, int ldb, float beta, DataType *C, int ldc, sycl::queue &sycl_queue)
template<typename DataType >
static void cublasXGemmStridedBatched (oneapi::mkl::transpose transa, oneapi::mkl::transpose transb, int m, int n, int k, float alpha, const void *A, int lda, long long int strideA, const void *B, int ldb, long long int strideB, float beta, void *C, int ldc, long long int strideC, int batchCount, sycl::queue &sycl_queue)
template<typename DataType >
static void cublasXGemmBatched (oneapi::mkl::transpose transa, oneapi::mkl::transpose transb, int m, int n, int k, float alpha, DataType **A, int lda, DataType **B, int ldb, float beta, DataType **C, int ldc, int batchCount, sycl::queue &sycl_queue)
int DivUp (int a, int b)
float mishActivate (float el)
float activate (float cVal, ActivationFunction activation)
template<typename T , int M, int N, int K>
void matrixMul_gpu_serial (T *c, const T *a, const T *b)
template<typename T >
void FilterTransform4x4 (T *transformed_filter, const T *filter)
template<typename T >
void InputTransform4x4 (T *transformedInput, const T *input)
template<typename T >
void OutputTransform4x4 (T *output, const T *transformedOutput)
template<typename T >
void filterTransform_kernel (int K, int C, int elements, T *transformed_filter, const T *filter, const sycl::nd_item< 3 > &item_ct1)
template<typename T , bool nhcw>
void InputTransform_kernel (int N, int C, const T *input, T *output, const sycl::nd_item< 3 > &item_ct1)
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip, bool skipInput_nhcw, bool output_nhcw>
void OutputTransform_kernel (int N, int C, int se_K, T *output, const T *input, const T *skip, const T *bias, const T *w1, const T *b1, const T *w2, const T *b2, const sycl::nd_item< 3 > &item_ct1, float *shared_data)
float warpReduce (float x, const sycl::nd_item< 3 > &item_ct1)
float warpMax (float x, const sycl::nd_item< 3 > &item_ct1)
template<typename T >
void copyAs (void *dst, const void *src)
template<typename T , ActivationFunction activation, bool use_bias, bool use_skip>
void OutputTransform_SE_relu_InputTransform_kernel (int N, int C, int se_K, T *output, const T *input, T *skip, const T *bias, const T *w1, const T *b1, const T *w2, const T *b2, const sycl::nd_item< 3 > &item_ct1, float *shared_data, sycl::local_accessor< float, 2 > shared_sums)
template<typename T , ActivationFunction activation, bool use_bias, bool use_skip>
void OutputTransform_relu_InputTransform_kernel (int N, int C, T *output, const T *input, T *skip, const T *bias, const sycl::nd_item< 3 > &item_ct1)
Variables
static constexpr bool kUseFusedSELayer = true
static constexpr int kNumOutputPolicy = 1858
Maximum number of output policy channels.
static constexpr int kMaxResBlockFusingChannels = 384
Maximum supported filter count for residual block fusing.
static constexpr int kMaxResBlockFusingSeKFp16Ampere
static constexpr int kMaxResBlockFusingSeK
static constexpr int kMaxResBlockFusingSeFp16AmpereSmem
constexpr int kOpInpTransformBlockSize = 64
Function Documentation
activate()
float lczero::sycldnn_backend::activate (float cVal, ActivationFunction activation) inline
Definition at line 39 of file winograd_helper.h.
References lczero::ACTIVATION_MISH, lczero::ACTIVATION_RELU, lczero::ACTIVATION_RELU_2, lczero::ACTIVATION_SELU, lczero::ACTIVATION_SIGMOID, lczero::ACTIVATION_SWISH, lczero::ACTIVATION_TANH, and mishActivate().
Referenced by addBias_NCHW_kernel(), addBiasBatched_kernel(), addBiasBatched_kernel(), addVectors_kernel(), batchNorm_kernel(), globalScale_kernel(), globalScale_kernel_fp16_nhwc(), layer_norm_kernel(), OutputInputTransformKernel_fp16_shmem_board(), OutputTransform_kernel(), OutputTransform_relu_InputTransform_kernel(), OutputTransform_SE_relu_InputTransform_kernel(), and SE_Layer_NHWC().
addBias_NCHW()
template<typename T > void lczero::sycldnn_backend::addBias_NCHW (T * c, T * a, T * b, int N, int C, int H, int W, ActivationFunction activation, sycl::queue & sycl_queue)
Adds bias to convolution's output.
Definition at line 417 of file common_kernels.dp.cpp.
References addBias_NCHW_kernel(), C, and DivUp().
Referenced by lczero::sycldnn_backend::Conv1Layer< DataType >::Eval().
addBias_NCHW< float >()
template void lczero::sycldnn_backend::addBias_NCHW< float > (float * c, float * a, float * b, int N, int C, int H, int W, ActivationFunction activation, sycl::queue & sycl_queue)
addBias_NCHW< sycl::half >()
template void lczero::sycldnn_backend::addBias_NCHW< sycl::half > (sycl::half * c, sycl::half * a, sycl::half * b, int N, int C, int H, int W, ActivationFunction activation, sycl::queue & sycl_queue)
addBias_NCHW_kernel()
template<typename T > void lczero::sycldnn_backend::addBias_NCHW_kernel (T * c, T * a, T * b, int N, int C, int H, int W, ActivationFunction activation, const sycl::nd_item< 3 > & item_ct1)
Definition at line 392 of file common_kernels.dp.cpp.
References activate(), and C.
Referenced by addBias_NCHW().
addBiasBatched() [1/2]
template<typename T > void lczero::sycldnn_backend::addBiasBatched (T * output, const T * input, const T * bias, int Batch, int N, int C, ActivationFunction activation, sycl::queue & sycl_queue)
Adds bias to innermost dimension and performs optional activation.
Definition at line 167 of file common_kernels.dp.cpp.
References lczero::ACTIVATION_MISH, lczero::ACTIVATION_NONE, lczero::ACTIVATION_RELU, lczero::ACTIVATION_RELU_2, lczero::ACTIVATION_SELU, lczero::ACTIVATION_SWISH, bias, C, DivUp(), lczero::sycldnn_backend::DeviceCapabilities::GetMaxWorkgroupSize(), input, and output.
Referenced by lczero::sycldnn_backend::EncoderBlock< DataType >::Eval(), lczero::sycldnn_backend::AttentionPolicyHead< DataType >::Eval(), lczero::sycldnn_backend::EmbeddingLayer< DataType >::Eval(), and lczero::sycldnn_backend::AttentionBody< DataType >::Eval().
addBiasBatched() [2/2]
template<typename T > void lczero::sycldnn_backend::addBiasBatched (T * output, const T * input, const T * bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, sycl::queue & sycl_queue)
Definition at line 304 of file common_kernels.dp.cpp.
References lczero::ACTIVATION_MISH, lczero::ACTIVATION_NONE, lczero::ACTIVATION_RELU, lczero::ACTIVATION_RELU_2, lczero::ACTIVATION_SELU, lczero::ACTIVATION_SWISH, bias, C, DivUp(), lczero::sycldnn_backend::DeviceCapabilities::GetMaxWorkgroupSize(), input, and output.
addBiasBatched< float >() [1/2]
template void lczero::sycldnn_backend::addBiasBatched< float > (float * output, const float * input, const float * bias, int Batch, int N, int C, ActivationFunction activation, sycl::queue & sycl_queue)
addBiasBatched< float >() [2/2]
template void lczero::sycldnn_backend::addBiasBatched< float > (float * output, const float * input, const float * bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, sycl::queue & sycl_queue)
addBiasBatched< sycl::half >() [1/2]
template void lczero::sycldnn_backend::addBiasBatched< sycl::half > (sycl::half * output, const sycl::half * input, const sycl::half * bias, int Batch, int N, int C, ActivationFunction activation, sycl::queue & sycl_queue)
addBiasBatched< sycl::half >() [2/2]
template void lczero::sycldnn_backend::addBiasBatched< sycl::half > (sycl::half * output, const sycl::half * input, const sycl::half * bias, int Batch, int N, int C, int Nstride, ActivationFunction activation, sycl::queue & sycl_queue)
addBiasBatched_kernel() [1/2]
template<typename T , ActivationFunction act> void lczero::sycldnn_backend::addBiasBatched_kernel (T * output, const T * input, const T * bias, int N, int C, const sycl::nd_item< 3 > & item_ct1)
Definition at line 114 of file common_kernels.dp.cpp.
References activate(), bias, C, input, and output.
addBiasBatched_kernel() [2/2]
template<typename T , ActivationFunction act> void lczero::sycldnn_backend::addBiasBatched_kernel (T * output, const T * input, const T * bias, int N, int C, int Nstride, const sycl::nd_item< 3 > & item_ct1)
Definition at line 251 of file common_kernels.dp.cpp.
References activate(), bias, C, input, and output.
addVectors()
template<typename T > void lczero::sycldnn_backend::addVectors (T * c, T * a, T * b, int size, int asize, int bsize, ActivationFunction activation, sycl::queue & sycl_queue)
Adds two vectors (possibly of different sizes), with optional activation.
Definition at line 65 of file common_kernels.dp.cpp.
References addVectors_kernel(), and DivUp().
Referenced by lczero::sycldnn_backend::Conv1Layer< DataType >::Eval(), lczero::sycldnn_backend::AttentionBody< DataType >::Eval(), lczero::sycldnn_backend::ValueHead< DataType >::Eval(), lczero::sycldnn_backend::SELayer< DataType >::Eval(), lczero::sycldnn_backend::FCLayer< DataType >::Eval(), lczero::sycldnn_backend::SELayer< DataType >::Eval(), and lczero::sycldnn_backend::FCLayer< DataType >::Eval().
addVectors< float >()
template void lczero::sycldnn_backend::addVectors< float > (float * c, float * a, float * b, int size, int asize, int bsize, ActivationFunction act, sycl::queue & sycl_queue)
addVectors< sycl::half >()
template void lczero::sycldnn_backend::addVectors< sycl::half > (sycl::half * c, sycl::half * a, sycl::half * b, int size, int asize, int bsize, ActivationFunction act, sycl::queue & sycl_queue)
addVectors_kernel()
template<typename T > void lczero::sycldnn_backend::addVectors_kernel (T * c, T * a, T * b, int size, int asize, int bsize, ActivationFunction activation, const sycl::nd_item< 3 > & item_ct1)
Definition at line 43 of file common_kernels.dp.cpp.
References activate().
Referenced by addVectors().
addVectorsHNC_NHC()
template<typename T > void lczero::sycldnn_backend::addVectorsHNC_NHC (T * a, T * b, int N, int H, int C, sycl::queue & sycl_queue)
Adds two vectors of equal size, overwriting the first.
Performs transposition of the first 2 indexes of the second vector.
Definition at line 101 of file common_kernels.dp.cpp.
References addVectorsHNC_NHC_kernel(), C, and DivUp().
addVectorsHNC_NHC< float >()
template void lczero::sycldnn_backend::addVectorsHNC_NHC< float > (float * a, float * b, int N, int H, int C, sycl::queue & sycl_queue)
addVectorsHNC_NHC< sycl::half >()
template void lczero::sycldnn_backend::addVectorsHNC_NHC< sycl::half > (sycl::half * a, sycl::half * b, int N, int H, int C, sycl::queue & sycl_queue)
addVectorsHNC_NHC_kernel()
template<typename T > void lczero::sycldnn_backend::addVectorsHNC_NHC_kernel (T * a, T * b, int N, int H, int C, const sycl::nd_item< 3 > & item_ct1)
Definition at line 80 of file common_kernels.dp.cpp.
References C.
Referenced by addVectorsHNC_NHC().
allocAndUpload()
template<typename DataType > void lczero::sycldnn_backend::allocAndUpload (DataType ** gpu_dest, std::vector< float > cpu_src, void * scratch, sycl::queue & sycl_queue)
Definition at line 1564 of file layers.cc.dp.cpp.
References copyTypeConverted().
applyInputGating()
template<typename T > void lczero::sycldnn_backend::applyInputGating (T * output, const T * input, const T * mult, const T * add, int N, int HW, int C, sycl::queue & sycl_queue)
Definition at line 1667 of file common_kernels.dp.cpp.
References blockSize, C, DivUp(), lczero::sycldnn_backend::DeviceCapabilities::GetMaxWorkgroupSize(), input, and output.
applyInputGating< float >()
template void lczero::sycldnn_backend::applyInputGating< float > (float * output, const float * input, const float * mult, const float * add, int N, int C, int output_size, sycl::queue & sycl_queue)
applyInputGating< sycl::half >()
template void lczero::sycldnn_backend::applyInputGating< sycl::half > (sycl::half * output, const sycl::half * input, const sycl::half * mult, const sycl::half * add, int N, int C, int output_size, sycl::queue & sycl_queue)
batchNorm()
template<typename T > void lczero::sycldnn_backend::batchNorm (T * output, const T * input, const T * skipInput, int N, int C, int H, int W, float * means, float * var_multipliers, ActivationFunction activation, sycl::queue & sycl_queue)
Performs batch normalization.
Definition at line 543 of file common_kernels.dp.cpp.
References batchNorm_kernel(), C, DivUp(), input, and output.
batchNorm< float >()
template void lczero::sycldnn_backend::batchNorm< float > (float * output, const float * input, const float * skipInput, int N, int C, int H, int W, float * means, float * var_multipliers, ActivationFunction activation, sycl::queue & sycl_queue)
batchNorm< sycl::half >()
template void lczero::sycldnn_backend::batchNorm< sycl::half > (sycl::half * output, const sycl::half * input, const sycl::half * skipInput, int N, int C, int H, int W, float * means, float * var_multipliers, ActivationFunction activation, sycl::queue & sycl_queue)
batchNorm_kernel()
template<typename T > void lczero::sycldnn_backend::batchNorm_kernel (T * output, const T * input, const T * skipInput, int N, int C, int H, int W, const float * means, const float * varMultipliers, ActivationFunction activation, const sycl::nd_item< 3 > & item_ct1)
Definition at line 513 of file common_kernels.dp.cpp.
References activate(), C, input, and output.
Referenced by batchNorm().
ComputePromotionLogits()
template<typename T > void lczero::sycldnn_backend::ComputePromotionLogits (int N, int C, T * output, const T * keys, const T * ppo, const T * policy_attn_logits, sycl::queue & sycl_queue)
Definition at line 1570 of file common_kernels.dp.cpp.
References C, and output.
ComputePromotionLogits< float >()
template void lczero::sycldnn_backend::ComputePromotionLogits< float > (int N, int C, float * output, const float * keys, const float * ppo, const float * policy_attn_logits, sycl::queue & sycl_queue)
ComputePromotionLogits< sycl::half >()
template void lczero::sycldnn_backend::ComputePromotionLogits< sycl::half > (int N, int C, sycl::half * output, const sycl::half * keys, const sycl::half * ppo, const sycl::half * policy_attn_logits, sycl::queue & sycl_queue)
convertNCHWtoNHWC()
template<typename DstType , typename SrcType > void lczero::sycldnn_backend::convertNCHWtoNHWC (DstType * output_tensor, const SrcType * input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue & sycl_queue)
Converts tensor from NCHW to NHWC layout.
Can also change datatype and pad/un-pad elements.
Definition at line 473 of file common_kernels.dp.cpp.
References blockSize, DivUp(), and NCHWtoNHWC_kernel().
Referenced by lczero::sycldnn_backend::AttentionPolicyHead< DataType >::Eval(), lczero::sycldnn_backend::AttentionBody< DataType >::Eval(), and lczero::sycldnn_backend::FCLayer< DataType >::LoadWeights().
convertNCHWtoNHWC< float, float >()
template void lczero::sycldnn_backend::convertNCHWtoNHWC< float, float > (float * output_tensor, const float * input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue & sycl_queue)
convertNCHWtoNHWC< sycl::half, float >()
template void lczero::sycldnn_backend::convertNCHWtoNHWC< sycl::half, float > (sycl::half * output_tensor, const float * input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue & sycl_queue)
convertNCHWtoNHWC< sycl::half, sycl::half >()
template void lczero::sycldnn_backend::convertNCHWtoNHWC< sycl::half, sycl::half > (sycl::half * output_tensor, const sycl::half * input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, sycl::queue & sycl_queue)
copyAs()
template<typename T > void lczero::sycldnn_backend::copyAs (void * dst, const void * src) inline
Definition at line 495 of file winograd_helper.h.
copyTypeConverted()
template<typename DstType , typename SrcType > void lczero::sycldnn_backend::copyTypeConverted (DstType * op, SrcType * ip, int N, sycl::queue & sycl_queue)
Definition at line 501 of file common_kernels.dp.cpp.
References copyTypeConverted_kernel(), and DivUp().
Referenced by allocAndUpload(), lczero::sycldnn_backend::AttentionBody< DataType >::AttentionBody(), lczero::sycldnn_backend::FusedWinogradConvSELayer< DataType >::LoadSEWeights(), lczero::sycldnn_backend::ResidualBlock< DataType >::LoadSEWeights(), lczero::sycldnn_backend::FCLayer< DataType >::LoadWeights(), lczero::sycldnn_backend::FusedWinogradConvSELayer< DataType >::LoadWeights(), lczero::sycldnn_backend::Conv1Layer< DataType >::LoadWeights(), lczero::sycldnn_backend::SELayer< DataType >::LoadWeights(), lczero::sycldnn_backend::ResidualBlock< DataType >::LoadWeights0(), and lczero::sycldnn_backend::ResidualBlock< DataType >::LoadWeights1().
copyTypeConverted< float, float >()
template void lczero::sycldnn_backend::copyTypeConverted< float, float > (float * op, float * ip, int N, sycl::queue & sycl_queue)
copyTypeConverted< float, sycl::half >()
template void lczero::sycldnn_backend::copyTypeConverted< float, sycl::half > (float * op, sycl::half * ip, int N, sycl::queue & sycl_queue)
copyTypeConverted< sycl::half, float >()
template void lczero::sycldnn_backend::copyTypeConverted< sycl::half, float > (sycl::half * op, float * ip, int N, sycl::queue & sycl_queue)
copyTypeConverted< sycl::half, sycl::half >()
template void lczero::sycldnn_backend::copyTypeConverted< sycl::half, sycl::half > (sycl::half * op, sycl::half * ip, int N, sycl::queue & sycl_queue)
copyTypeConverted_kernel()
template<typename DstType , typename SrcType > void lczero::sycldnn_backend::copyTypeConverted_kernel (DstType * op, SrcType * ip, int N, const sycl::nd_item< 3 > & item_ct1)
Definition at line 489 of file common_kernels.dp.cpp.
Referenced by copyTypeConverted().
cpuTranspose()
void lczero::sycldnn_backend::cpuTranspose (float * op, float * ip, int rows, int cols)
Definition at line 156 of file layers.cc.dp.cpp.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::LoadWeights().
CpuTranspose()
static void lczero::sycldnn_backend::CpuTranspose (float * op, float * ip, size_t rows, size_t cols) inline static
Definition at line 852 of file layers.cc.dp.cpp.
Referenced by lczero::sycldnn_backend::FusedWinogradConvSELayer< DataType >::LoadSEWeights(), and lczero::sycldnn_backend::ResidualBlock< DataType >::LoadSEWeights().
cublasXgemm()
template<typename DataType > static void lczero::sycldnn_backend::cublasXgemm (oneapi::mkl::transpose transa, oneapi::mkl::transpose transb, int m, int n, int k, float alpha, const DataType * A, int lda, const DataType * B, int ldb, float beta, DataType * C, int ldc, sycl::queue & sycl_queue) static
Definition at line 1737 of file layers.cc.dp.cpp.
References C, lczero::FP32toFP16(), m, and ReportCUBLASErrors.
Referenced by lczero::sycldnn_backend::EncoderBlock< DataType >::Eval(), and lczero::sycldnn_backend::AttentionBody< DataType >::Eval().
cublasXGemmBatched()
template<typename DataType > static void lczero::sycldnn_backend::cublasXGemmBatched (oneapi::mkl::transpose transa, oneapi::mkl::transpose transb, int m, int n, int k, float alpha, DataType ** A, int lda, DataType ** B, int ldb, float beta, DataType ** C, int ldc, int batchCount, sycl::queue & sycl_queue) static
Definition at line 1893 of file layers.cc.dp.cpp.
References C, lczero::FP32toFP16(), m, and ReportCUBLASErrors.
cublasXGemmStridedBatched()
template<typename DataType > static void lczero::sycldnn_backend::cublasXGemmStridedBatched (oneapi::mkl::transpose transa, oneapi::mkl::transpose transb, int m, int n, int k, float alpha, const void * A, int lda, long long int strideA, const void * B, int ldb, long long int strideB, float beta, void * C, int ldc, long long int strideC, int batchCount, sycl::queue & sycl_queue) static
Definition at line 1803 of file layers.cc.dp.cpp.
References C, lczero::FP32toFP16(), m, and ReportCUBLASErrors.
DivUp()
int lczero::sycldnn_backend::DivUp (int a, int b) inline
Definition at line 60 of file sycl_common.h.
Referenced by addBias_NCHW(), addBiasBatched(), addBiasBatched(), addVectors(), addVectorsHNC_NHC(), applyInputGating(), batchNorm(), convertNCHWtoNHWC(), copyTypeConverted(), expandPlanes_Fp16_NCHW(), expandPlanes_Fp16_NHWC(), expandPlanes_Fp32_NCHW(), FilterTransform(), genOffsetPointers(), globalAvgPool(), globalScale(), inputPreprocessForAttentionBody(), LayerNorm(), OutputInputTransform(), PolicyMap(), and Softmax().
expandPlanes_Fp16_NCHW()
void lczero::sycldnn_backend::expandPlanes_Fp16_NCHW (sycl::half * output, const uint64_t * masks, const float * values, int n, sycl::queue & sycl_queue)
Definition at line 717 of file common_kernels.dp.cpp.
References blockSize, DivUp(), expandPlanes_kernel_Fp16_NCHW(), and output.
Referenced by lczero::SyclNetwork< DataType >::forwardEval().
expandPlanes_Fp16_NHWC()
void lczero::sycldnn_backend::expandPlanes_Fp16_NHWC (sycl::half * output, const uint64_t * masks, const float * values, int n, sycl::queue & sycl_queue)
Definition at line 659 of file common_kernels.dp.cpp.
References DivUp(), expandPlanes_kernel_Fp16_NHWC(), and output.
expandPlanes_Fp32_NCHW()
void lczero::sycldnn_backend::expandPlanes_Fp32_NCHW (float * output, const uint64_t * masks, const float * values, int n, sycl::queue & sycl_queue)
Definition at line 602 of file common_kernels.dp.cpp.
References blockSize, DivUp(), expandPlanes_kernel_Fp32_NCHW(), and output.
Referenced by lczero::SyclNetwork< DataType >::forwardEval().
expandPlanes_kernel_Fp16_NCHW()
void lczero::sycldnn_backend::expandPlanes_kernel_Fp16_NCHW (sycl::half * output, const uint64_t * masks, const float * values, int n, const sycl::nd_item< 3 > & item_ct1, uint64_t * shMasks, sycl::half * shVals)
Definition at line 676 of file common_kernels.dp.cpp.
References output.
Referenced by expandPlanes_Fp16_NCHW().
expandPlanes_kernel_Fp16_NHWC()
void lczero::sycldnn_backend::expandPlanes_kernel_Fp16_NHWC (sycl::half * output, const uint64_t * masks, const float * values, int n, const sycl::nd_item< 3 > & item_ct1)
Definition at line 637 of file common_kernels.dp.cpp.
References lczero::kInputPlanes, and output.
Referenced by expandPlanes_Fp16_NHWC().
expandPlanes_kernel_Fp32_NCHW()
void lczero::sycldnn_backend::expandPlanes_kernel_Fp32_NCHW (float * output, const uint64_t * masks, const float * values, int n, const sycl::nd_item< 3 > & item_ct1, uint64_t * shMasks, float * shVals)
Definition at line 560 of file common_kernels.dp.cpp.
References output.
Referenced by expandPlanes_Fp32_NCHW().
FilterTransform()
template<typename T > void lczero::sycldnn_backend::FilterTransform (int N, int C, T * transformedFilter, const T * filter, sycl::queue & sycl_queue)
Winograd filter transformation.
Definition at line 892 of file winograd_helper.h.
References C, DivUp(), and filterTransform_kernel().
Referenced by lczero::sycldnn_backend::FusedWinogradConvSELayer< DataType >::LoadWeights(), lczero::sycldnn_backend::ResidualBlock< DataType >::LoadWeights0(), and lczero::sycldnn_backend::ResidualBlock< DataType >::LoadWeights1().
FilterTransform4x4()
template<typename T > void lczero::sycldnn_backend::FilterTransform4x4 (T * transformed_filter, const T * filter) inline
Definition at line 88 of file winograd_helper.h.
Referenced by filterTransform_kernel().
FilterTransform< float >()
template void lczero::sycldnn_backend::FilterTransform< float > (int N, int C, float * transformedFilter, const float * filter, sycl::queue & sycl_queue)
FilterTransform< sycl::half >()
template void lczero::sycldnn_backend::FilterTransform< sycl::half > (int N, int C, sycl::half * transformedFilter, const sycl::half * filter, sycl::queue & sycl_queue)
filterTransform_kernel()
template<typename T > void lczero::sycldnn_backend::filterTransform_kernel (int K, int C, int elements, T * transformed_filter, const T * filter, const sycl::nd_item< 3 > & item_ct1)
Definition at line 139 of file winograd_helper.h.
References C, FILTER_IDX_NCHW, and FilterTransform4x4().
Referenced by FilterTransform().
genOffsetPointers()
template<typename T > void lczero::sycldnn_backend::genOffsetPointers (T ** offsets, int heads, int max_batch, int depth, int d_model, T * k, T * q, T * b1, T * v, T * b2, sycl::queue & sycl_queue)
Definition at line 1727 of file common_kernels.dp.cpp.
References DivUp(), and q.
Referenced by lczero::sycldnn_backend::EncoderBlock< DataType >::Eval().
genOffsetPointers< float >()
template void lczero::sycldnn_backend::genOffsetPointers< float > (float ** offsets, int heads, int max_batch, int depth, int d_model, float * k, float * q, float * b1, float * v, float * b2, sycl::queue & sycl_queue)
genOffsetPointers< sycl::half >()
template void lczero::sycldnn_backend::genOffsetPointers< sycl::half > (sycl::half ** offsets, int heads, int max_batch, int depth, int d_model, sycl::half * k, sycl::half * q, sycl::half * b1, sycl::half * v, sycl::half * b2, sycl::queue & sycl_queue)
genOffsetPointers_kernel()
template<typename T , int kWorkPerThread> static void lczero::sycldnn_backend::genOffsetPointers_kernel (T ** offsets, int heads, int block_size, int depth, int d_model, T * k, T * q, T * b1, T * v, T * b2, const sycl::nd_item< 1 > & item_ct) static
Definition at line 1690 of file common_kernels.dp.cpp.
References q.
globalAvgPool()
template<typename T > void lczero::sycldnn_backend::globalAvgPool (int N, int C, T * output, const T * input, const T * prevLayerBias, bool nhwc, sycl::queue & sycl_queue)
Performs global average pooling.
Definition at line 901 of file common_kernels.dp.cpp.
References C, DivUp(), globalAvgPool_kernel(), globalAvgPool_kernel_NHWC_fp16(), input, output, and SYCL_SUB_GROUP_SIZE.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::Eval(), and lczero::sycldnn_backend::SELayer< DataType >::Eval().
globalAvgPool< float >()
template void lczero::sycldnn_backend::globalAvgPool< float > (int N, int C, float * output, const float * input, const float * prevLayerBias, bool nhwc, sycl::queue & sycl_queue)
globalAvgPool< sycl::half >()
template void lczero::sycldnn_backend::globalAvgPool< sycl::half > (int N, int C, sycl::half * output, const sycl::half * input, const sycl::half * prevLayerBias, bool nhwc, sycl::queue & sycl_queue)
globalAvgPool_kernel()
template<typename T > void lczero::sycldnn_backend::globalAvgPool_kernel (T * output, const T * input, const T * prevLayerBias, int inputSize, int outputSize, int C, const sycl::nd_item< 3 > & item_ct1)
Definition at line 854 of file common_kernels.dp.cpp.
References C, input, offset, and output.
Referenced by globalAvgPool().
globalAvgPool_kernel_NHWC_fp16()
void lczero::sycldnn_backend::globalAvgPool_kernel_NHWC_fp16 (sycl::half * output, const sycl::half * input, const sycl::half * prevLayerBias, int inputSize, int outputSize, const sycl::nd_item< 3 > & item_ct1)
Definition at line 826 of file common_kernels.dp.cpp.
References input, and output.
Referenced by globalAvgPool().
globalScale()
template<typename T > void lczero::sycldnn_backend::globalScale (int N, int C, T * output, const T * input, const T * scaleBias, const T * prevLayerBias, bool nhwc, ActivationFunction activation, sycl::queue & sycl_queue)
Definition at line 948 of file common_kernels.dp.cpp.
References C, DivUp(), globalScale_kernel(), globalScale_kernel_fp16_nhwc(), input, and output.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::Eval(), and lczero::sycldnn_backend::SELayer< DataType >::Eval().
globalScale< float >()
template void lczero::sycldnn_backend::globalScale< float > (int N, int C, float * output, const float * input, const float * scaleBias, const float * prevLayerBias, bool nhwc, ActivationFunction activation, sycl::queue & sycl_queue)
globalScale< sycl::half >()
template void lczero::sycldnn_backend::globalScale< sycl::half > (int N, int C, sycl::half * output, const sycl::half * input, const sycl::half * scaleBias, const sycl::half * prevLayerBias, bool nhwc, ActivationFunction activation, sycl::queue & sycl_queue)
globalScale_kernel()
template<typename T > void lczero::sycldnn_backend::globalScale_kernel (T * output, const T * input, const T * scaleBias, const T * prevLayerBias, int inputSize, int C, ActivationFunction activation, const sycl::nd_item< 3 > & item_ct1)
Definition at line 754 of file common_kernels.dp.cpp.
References activate(), C, input, and output.
Referenced by globalScale().
globalScale_kernel_fp16_nhwc()
void lczero::sycldnn_backend::globalScale_kernel_fp16_nhwc (sycl::half * output, const sycl::half * input, const sycl::half * scaleBias, const sycl::half * prevLayerBias, int inputSize, int C, int HWC, ActivationFunction activation, const sycl::nd_item< 3 > & item_ct1)
Definition at line 789 of file common_kernels.dp.cpp.
References activate(), C, input, and output.
Referenced by globalScale().
input_gating_kernel()
template<typename T > void lczero::sycldnn_backend::input_gating_kernel (T * output, const T * input, const T * mult, const T * add, int HW, int C, const sycl::nd_item< 3 > & item_ct1)
Definition at line 1645 of file common_kernels.dp.cpp.
References C, idx, input, and output.
inputPreprocessForAttentionBody()
template<typename T > void lczero::sycldnn_backend::inputPreprocessForAttentionBody (T * output, const T * input, const T * encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, sycl::queue & sycl_queue)
Definition at line 1619 of file common_kernels.dp.cpp.
References blockSize, DivUp(), lczero::sycldnn_backend::DeviceCapabilities::GetMaxWorkgroupSize(), input, and output.
Referenced by lczero::sycldnn_backend::AttentionBody< DataType >::Eval().
inputPreprocessForAttentionBody< float >()
template void lczero::sycldnn_backend::inputPreprocessForAttentionBody< float > (float * output, const float * input, const float * encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, sycl::queue & sycl_queue)
inputPreprocessForAttentionBody< sycl::half >()
template void lczero::sycldnn_backend::inputPreprocessForAttentionBody< sycl::half > (sycl::half * output, const sycl::half * input, const sycl::half * encoding, int N, int input_size, int encoding_size, bool is_pe_dense_embedding, sycl::queue & sycl_queue)
InputTransform()
template<typename T , bool nhcw> void lczero::sycldnn_backend::InputTransform (int N, int C, T * transformedInput, const T * input, sycl::queue & sycl_queue)
Definition at line 909 of file winograd_helper.h.
References C, and input.
InputTransform4x4()
template<typename T > void lczero::sycldnn_backend::InputTransform4x4 (T * transformedInput, const T * input) inline
Definition at line 107 of file winograd_helper.h.
References input, and transformedInput.
Referenced by InputTransform_kernel(), OutputInputTransformKernel_fp16_shmem_board(), OutputTransform_relu_InputTransform_kernel(), and OutputTransform_SE_relu_InputTransform_kernel().
InputTransform< float, false >()
template void lczero::sycldnn_backend::InputTransform< float, false > (int N, int C, float * transformed_input, const float * input, sycl::queue & sycl_queue)
InputTransform< float, true >()
template void lczero::sycldnn_backend::InputTransform< float, true > (int N, int C, float * transformed_input, const float * input, sycl::queue & sycl_queue)
InputTransform< sycl::half, false >()
template void lczero::sycldnn_backend::InputTransform< sycl::half, false > (int N, int C, sycl::half * transformed_input, const sycl::half * input, sycl::queue & sycl_queue)
InputTransform< sycl::half, true >()
template void lczero::sycldnn_backend::InputTransform< sycl::half, true > (int N, int C, sycl::half * transformed_input, const sycl::half * input, sycl::queue & sycl_queue)
InputTransform_kernel()
template<typename T , bool nhcw> void lczero::sycldnn_backend::InputTransform_kernel (int N, int C, const T * input, T * output, const sycl::nd_item< 3 > & item_ct1)
Definition at line 187 of file winograd_helper.h.
References INDEX_NCHW, INDEX_NHCW, input, InputTransform4x4(), output, and TEMP_INDEX_HWNC.
layer_norm_kernel()
template<typename T > void lczero::sycldnn_backend::layer_norm_kernel (int N, int C, T * output, const T * input, const T * bias, const T * skip, const T * gammas, const T * betas, float ep, float alpha, ActivationFunction act, const sycl::nd_item< 3 > & item_ct1, sycl::local_accessor< float, 2 > sum)
Definition at line 1289 of file common_kernels.dp.cpp.
References activate(), bias, C, d, input, norm, output, and shared_sum_for_layer_norm().
LayerNorm()
template<typename T > void lczero::sycldnn_backend::LayerNorm (int N, int C, T * output, const T * input, const T * bias, const T * skip, const T * gammas, const T * betas, float ep, float alpha, ActivationFunction act, sycl::queue & sycl_queue)
Definition at line 1445 of file common_kernels.dp.cpp.
References bias, C, DivUp(), input, output, and SYCL_SUB_GROUP_SIZE.
LayerNorm< float >()
template void lczero::sycldnn_backend::LayerNorm< float > (int N, int C, float * output, const float * input, const float * bias, const float * skip, const float * gammas, const float * betas, float ep, float alpha, ActivationFunction act, sycl::queue & sycl_queue)
LayerNorm< sycl::half >()
template void lczero::sycldnn_backend::LayerNorm< sycl::half > (int N, int C, sycl::half * output, const sycl::half * input, const sycl::half * bias, const sycl::half * skip, const sycl::half * gammas, const sycl::half * betas, float ep, float alpha, ActivationFunction act, sycl::queue & sycl_queue)
matrixMul_gpu_serial()
template<typename T , int M, int N, int K> void lczero::sycldnn_backend::matrixMul_gpu_serial (T * c, const T * a, const T * b) inline
Definition at line 74 of file winograd_helper.h.
mishActivate()
float lczero::sycldnn_backend::mishActivate (float el) inline
Definition at line 28 of file winograd_helper.h.
References d.
Referenced by activate().
NCHWtoNHWC_kernel()
template<typename dT , typename sT > void lczero::sycldnn_backend::NCHWtoNHWC_kernel (dT * output_tensor, const sT * input_tensor, int Nin, int Cin, int Nout, int Cout, int H, int W, const sycl::nd_item< 3 > & item_ct1)
Definition at line 450 of file common_kernels.dp.cpp.
Referenced by convertNCHWtoNHWC().
OutputInputTransform()
template<typename T = float, bool use_se, ActivationFunction activation, bool use_bias, bool use_skip> void lczero::sycldnn_backend::OutputInputTransform (int N, int C, int se_K, T * output, const T * input, const T * skip, const T * bias, const T * w1, const T * b1, const T * w2, const T * b2, sycl::queue & sycl_queue)
Definition at line 1021 of file common_kernels.dp.cpp.
References bias, C, DivUp(), input, kMaxResBlockFusingChannels, kOpInpTransformBlockSize, output, OutputTransform_relu_InputTransform_kernel(), OutputTransform_SE_relu_InputTransform_kernel(), se_K, and SYCL_SUB_GROUP_SIZE.
OutputInputTransform< float, false, ACTIVATION_MISH, true, false >()
template void lczero::sycldnn_backend::OutputInputTransform< float, false, ACTIVATION_MISH, true, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputInputTransform< float, false, ACTIVATION_MISH, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< float, false, ACTIVATION_MISH, true, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputInputTransform< float, false, ACTIVATION_RELU, true, false >()
template void lczero::sycldnn_backend::OutputInputTransform< float, false, ACTIVATION_RELU, true, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputInputTransform< float, false, ACTIVATION_RELU, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< float, false, ACTIVATION_RELU, true, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputInputTransform< float, true, ACTIVATION_MISH, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< float, true, ACTIVATION_MISH, true, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputInputTransform< float, true, ACTIVATION_RELU, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< float, true, ACTIVATION_RELU, true, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputInputTransform< sycl::half, false, ACTIVATION_MISH, true, false >()
template void lczero::sycldnn_backend::OutputInputTransform< sycl::half, false, ACTIVATION_MISH, true, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputInputTransform< sycl::half, false, ACTIVATION_MISH, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< sycl::half, false, ACTIVATION_MISH, true, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputInputTransform< sycl::half, false, ACTIVATION_RELU, true, false >()
template void lczero::sycldnn_backend::OutputInputTransform< sycl::half, false, ACTIVATION_RELU, true, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputInputTransform< sycl::half, false, ACTIVATION_RELU, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< sycl::half, false, ACTIVATION_RELU, true, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputInputTransform< sycl::half, true, ACTIVATION_MISH, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< sycl::half, true, ACTIVATION_MISH, true, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputInputTransform< sycl::half, true, ACTIVATION_RELU, true, true >()
template void lczero::sycldnn_backend::OutputInputTransform< sycl::half, true, ACTIVATION_RELU, true, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputInputTransformKernel_fp16_shmem_board()
template<ActivationFunction activation, bool use_bias, bool use_skip> void lczero::sycldnn_backend::OutputInputTransformKernel_fp16_shmem_board (int N, int C, int se_K, sycl::half * output, const sycl::half * input, sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, const sycl::nd_item< 3 > & item_ct1, uint8_t * dpct_local, float * shared_data, sycl::local_accessor< float, 2 > shared_sums)
Definition at line 461 of file fp16_kernels.dp.cpp.
References activate(), lczero::ACTIVATION_NONE, bias, BOARD, C, INDEX_NHCW, input, InputTransform4x4(), output, OutputTransform4x4(), readw1, readw2, se_K, TEMP_INDEX_HWNC, and warpReduce().
OutputTransform()
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip, bool skipInput_nhcw, bool output_nhcw> void lczero::sycldnn_backend::OutputTransform (int N, int C, int se_K, T * output, const T * input, const T * skip, const T * bias, const T * w1, const T * b1, const T * w2, const T * b2, sycl::queue & sycl_queue)
Definition at line 932 of file winograd_helper.h.
References bias, C, input, output, OutputTransform_kernel(), and se_K.
Referenced by lczero::sycldnn_backend::ResidualBlock< DataType >::Eval().
OutputTransform4x4()
template<typename T > void lczero::sycldnn_backend::OutputTransform4x4 (T * output, const T * transformedOutput) inline
Definition at line 124 of file winograd_helper.h.
References output, and transformedOutput.
Referenced by OutputInputTransformKernel_fp16_shmem_board(), OutputTransform_kernel(), OutputTransform_relu_InputTransform_kernel(), and OutputTransform_SE_relu_InputTransform_kernel().
OutputTransform< float, false, ACTIVATION_MISH, true, false, false, false >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_MISH, true, false, false, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_MISH, true, false, false, true >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_MISH, true, false, false, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_MISH, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_MISH, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_NONE, true, false, false, false >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_NONE, true, false, false, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_RELU, true, false, false, false >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_RELU, true, false, false, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_RELU, true, false, false, true >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_RELU, true, false, false, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_RELU, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, false, ACTIVATION_RELU, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< float, false, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, true, ACTIVATION_MISH, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< float, true, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, true, ACTIVATION_MISH, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< float, true, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, true, ACTIVATION_MISH, true, true, true, true >()
template void lczero::sycldnn_backend::OutputTransform< float, true, ACTIVATION_MISH, true, true, true, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, true, ACTIVATION_RELU, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< float, true, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, true, ACTIVATION_RELU, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< float, true, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< float, true, ACTIVATION_RELU, true, true, true, true >()
template void lczero::sycldnn_backend::OutputTransform< float, true, ACTIVATION_RELU, true, true, true, true > (int N, int C, int se_K, float * output, const float * input, const float * skip, const float * bias, const float * w1, const float * b1, const float * w2, const float * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_MISH, true, false, false, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_MISH, true, false, false, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_MISH, true, false, false, true >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_MISH, true, false, false, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_MISH, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_MISH, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_NONE, true, false, false, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_NONE, true, false, false, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_RELU, true, false, false, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_RELU, true, false, false, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_RELU, true, false, false, true >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_RELU, true, false, false, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_RELU, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, false, ACTIVATION_RELU, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, false, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, false, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, true, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, true, true >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, true, ACTIVATION_MISH, true, true, true, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, false, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, false, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, true, false >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, true, false > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, true, true >()
template void lczero::sycldnn_backend::OutputTransform< sycl::half, true, ACTIVATION_RELU, true, true, true, true > (int N, int C, int se_K, sycl::half * output, const sycl::half * input, const sycl::half * skip, const sycl::half * bias, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, sycl::queue & sycl_queue)
OutputTransform_kernel()
template<typename T , bool use_se, ActivationFunction activation, bool use_bias, bool use_skip, bool skipInput_nhcw, bool output_nhcw> void lczero::sycldnn_backend::OutputTransform_kernel (int N, int C, int se_K, T * output, const T * input, const T * skip, const T * bias, const T * w1, const T * b1, const T * w2, const T * b2, const sycl::nd_item< 3 > & item_ct1, float * shared_data)
Definition at line 297 of file winograd_helper.h.
References activate(), lczero::ACTIVATION_NONE, bias, C, INDEX_NCHW, INDEX_NHCW, input, output, OutputTransform4x4(), readw1, readw2, se_K, and TEMP_INDEX_HWNC.
Referenced by OutputTransform().
OutputTransform_relu_InputTransform_kernel()
template<typename T , ActivationFunction activation, bool use_bias, bool use_skip> void lczero::sycldnn_backend::OutputTransform_relu_InputTransform_kernel (int N, int C, T * output, const T * input, T * skip, const T * bias, const sycl::nd_item< 3 > & item_ct1)
Definition at line 740 of file winograd_helper.h.
References activate(), lczero::ACTIVATION_NONE, bias, C, INDEX_NHCW, input, InputTransform4x4(), kOpInpTransformBlockSize, output, OutputTransform4x4(), and TEMP_INDEX_HWNC.
Referenced by OutputInputTransform().
OutputTransform_SE_relu_InputTransform_kernel()
template<typename T , ActivationFunction activation, bool use_bias, bool use_skip> void lczero::sycldnn_backend::OutputTransform_SE_relu_InputTransform_kernel (int N, int C, int se_K, T * output, const T * input, T * skip, const T * bias, const T * w1, const T * b1, const T * w2, const T * b2, const sycl::nd_item< 3 > & item_ct1, float * shared_data, sycl::local_accessor< float, 2 > shared_sums)
Definition at line 514 of file winograd_helper.h.
References activate(), lczero::ACTIVATION_NONE, bias, C, INDEX_NHCW, input, InputTransform4x4(), output, OutputTransform4x4(), readw1, readw2, se_K, TEMP_INDEX_HWNC, and warpReduce().
Referenced by OutputInputTransform().
PolicyMap()
template<typename T > void lczero::sycldnn_backend::PolicyMap (int N, T * output, const T * input, const short * indices, int inputSize, int usedSize, int outputSize, sycl::queue & sycl_queue)
Definition at line 1002 of file common_kernels.dp.cpp.
References DivUp(), input, and output.
Referenced by lczero::sycldnn_backend::PolicyMapLayer< DataType >::Eval().
PolicyMap< float >()
template void lczero::sycldnn_backend::PolicyMap< float > (int N, float * output, const float * input, const short * indices, int inputSize, int usedSize, int outputSize, sycl::queue & sycl_queue)
PolicyMap< sycl::half >()
template void lczero::sycldnn_backend::PolicyMap< sycl::half > (int N, sycl::half * output, const sycl::half * input, const short * indices, int inputSize, int usedSize, int outputSize, sycl::queue & sycl_queue)
policyMap_kernel()
template<typename T > void lczero::sycldnn_backend::policyMap_kernel (T * output, const T * input, const short * indices, int N, int inputSize, int usedSize, int outputSize, const sycl::nd_item< 3 > & item_ct1)
Definition at line 982 of file common_kernels.dp.cpp.
References input, and output.
preprocess_for_attention_body_kernel()
template<typename T > void lczero::sycldnn_backend::preprocess_for_attention_body_kernel (T * output, const T * input, const T * encoding, int input_size, int encoding_size, bool is_pe_dense_embedding, const sycl::nd_item< 3 > & item_ct1)
Definition at line 1590 of file common_kernels.dp.cpp.
References input, and output.
promotion_logits_kernel()
template<typename T > void lczero::sycldnn_backend::promotion_logits_kernel (int C, T * output, const T * keys, const T * ppo, const T * policy_attn_logits, const sycl::nd_item< 3 > & item_ct1, sycl::local_accessor< float, 2 > promotion_offsets)
Definition at line 1488 of file common_kernels.dp.cpp.
References C, and output.
readNCHW()
template<typename dT , typename sT > dT lczero::sycldnn_backend::readNCHW (const sT * input_tensor, int n, int c, int h, int w, int Nin, int Cin, int H, int W)
Definition at line 433 of file common_kernels.dp.cpp.
Se_Fp16_NHWC()
bool lczero::sycldnn_backend::Se_Fp16_NHWC (int N, int C, int numFc1Out, sycl::half * output, const sycl::half * skip, const sycl::half * input, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, const sycl::half * bPrev, ActivationFunction activation, sycl::queue & sycl_queue)
Performs Squeeze-and-Excitation (SE) in a single fused kernel.
Returns
False if the fused kernel can't handle the sizes.
Definition at line 134 of file fp16_kernels.dp.cpp.
References C, input, and output.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::Eval().
SE_Layer_NHWC()
template<int C, int K> void lczero::sycldnn_backend::SE_Layer_NHWC (sycl::half * output, const sycl::half * skip, const sycl::half * input, const sycl::half * w1, const sycl::half * b1, const sycl::half * w2, const sycl::half * b2, const sycl::half * bPrev, ActivationFunction activation, const sycl::nd_item< 3 > & item_ct1, sycl::half * sharedData)
Definition at line 52 of file fp16_kernels.dp.cpp.
References activate(), bias, C, input, output, readw1, readw2, and se_K.
shared_sum_for_layer_norm()
float lczero::sycldnn_backend::shared_sum_for_layer_norm (float x, const sycl::nd_item< 3 > & item_ct1, sycl::local_accessor< float, 2 > sum) inline
Definition at line 1254 of file common_kernels.dp.cpp.
References warpReduce().
Referenced by layer_norm_kernel().
Softmax()
template<typename T > void lczero::sycldnn_backend::Softmax (int N, int C, T * output, const T * input, const T * input2, sycl::queue & sycl_queue)
Definition at line 1217 of file common_kernels.dp.cpp.
References C, DivUp(), input, output, and SYCL_SUB_GROUP_SIZE.
Referenced by lczero::sycldnn_backend::EncoderBlock< DataType >::Eval().
Softmax< float >()
template void lczero::sycldnn_backend::Softmax< float > (int N, int C, float * output, const float * input, const float * input2, sycl::queue & sycl_queue)
Softmax< sycl::half >()
template void lczero::sycldnn_backend::Softmax< sycl::half > (int N, int C, sycl::half * output, const sycl::half * input, const sycl::half * input2, sycl::queue & sycl_queue)
softmax_kernel()
template<typename T > void lczero::sycldnn_backend::softmax_kernel (T * output, const T * input, const T * input2, const sycl::nd_item< 3 > & item_ct1, float & localsum, float & localmax)
Definition at line 1167 of file common_kernels.dp.cpp.
References C, input, output, warpMax(), and warpReduce().
softmax_opt_64_kernel()
template<typename T > void lczero::sycldnn_backend::softmax_opt_64_kernel (T * output, const T * input, const T * input2, int N, const sycl::nd_item< 3 > & item_ct1)
Definition at line 1091 of file common_kernels.dp.cpp.
References input, output, warpMax(), and warpReduce().
warpMax()
float lczero::sycldnn_backend::warpMax (float x, const sycl::nd_item< 3 > & item_ct1) inline
Definition at line 470 of file winograd_helper.h.
Referenced by softmax_kernel(), and softmax_opt_64_kernel().
warpReduce()
float lczero::sycldnn_backend::warpReduce (float x, const sycl::nd_item< 3 > & item_ct1) inline
Definition at line 447 of file winograd_helper.h.
Referenced by OutputInputTransformKernel_fp16_shmem_board(), OutputTransform_SE_relu_InputTransform_kernel(), shared_sum_for_layer_norm(), softmax_kernel(), and softmax_opt_64_kernel().
Variable Documentation
kMaxResBlockFusingChannels
constexpr int lczero::sycldnn_backend::kMaxResBlockFusingChannels = 384 static constexpr
Maximum supported filter count for residual block fusing.
Limited by number of registers per thread.
Definition at line 44 of file sycl_common.h.
Referenced by lczero::sycldnn_backend::ResidualBlock< DataType >::Eval(), and OutputInputTransform().
kMaxResBlockFusingSeFp16AmpereSmem
constexpr int lczero::sycldnn_backend::kMaxResBlockFusingSeFp16AmpereSmem static constexpr
Initial value:
=
 72 * kMaxResBlockFusingSeKFp16Ampere
              *
 sizeof(sycl::half)
Definition at line 49 of file sycl_common.h.
Referenced by lczero::sycldnn_backend::ResidualBlock< DataType >::Eval().
kMaxResBlockFusingSeK
constexpr int lczero::sycldnn_backend::kMaxResBlockFusingSeK static constexpr
Initial value:
=
 128
Definition at line 47 of file sycl_common.h.
kMaxResBlockFusingSeKFp16Ampere
constexpr int lczero::sycldnn_backend::kMaxResBlockFusingSeKFp16Ampere static constexpr
Initial value:
=
 512
Definition at line 45 of file sycl_common.h.
Referenced by lczero::sycldnn_backend::ResidualBlock< DataType >::Eval().
kNumOutputPolicy
constexpr int lczero::sycldnn_backend::kNumOutputPolicy = 1858 static constexpr
Maximum number of output policy channels.
Definition at line 40 of file sycl_common.h.
Referenced by lczero::sycldnn_backend::InputsOutputs::InputsOutputs().
kOpInpTransformBlockSize
constexpr int lczero::sycldnn_backend::kOpInpTransformBlockSize = 64 constexpr
Definition at line 730 of file winograd_helper.h.
Referenced by OutputInputTransform(), and OutputTransform_relu_InputTransform_kernel().
kUseFusedSELayer
constexpr bool lczero::sycldnn_backend::kUseFusedSELayer = true static constexpr
Definition at line 77 of file layers.cc.dp.cpp.
Referenced by lczero::sycldnn_backend::SELayer< DataType >::Eval(), lczero::sycldnn_backend::SELayer< DataType >::LoadWeights(), and lczero::sycldnn_backend::SELayer< DataType >::SELayer().