Leela Chess Zero: lczero Namespace Reference
lczero Namespace Reference
Namespaces
namespace classic
namespace cudnn_backend
namespace dag_classic
namespace dx_backend
namespace metal_backend
namespace onednn_backend
namespace onnx
namespace python
namespace sycldnn_backend
Classes
struct Activations
class AtomicVector
class Backend
Abstract interface for a neural network backend provider.
struct BackendAttributes
Configuration attributes for a neural network backend.
class BackendBenchmark
class BackendComputation
Abstract interface for a specific backend computation instance.
class BackendFactory
Abstract factory for creating Backend instances.
class BackendManager
struct BaseWeights
class Benchmark
struct BestMoveInfo
class BFloat16OnnxConst
class BFloat16OnnxWeightsAdapter
class BitBoard
class BitIterator
class BoolOption
Represents a boolean option in the Lc0 chess engine's configuration system.
class Button
class ButtonOption
class CachingBackend
class CallbackUciResponder
class ChessBoard
Represents a chess board position in the Lc0 engine.
class ChoiceOption
class CommandLine
class ConfigFile
struct ConvCreateDesc
class Convolution1
Implements 1x1 Convolution.
class CudaNetwork
CUDA network implementation.
class CudaNetworkComputation
CUDA network computation class.
class CudnnNetwork
CuDNN network implementation.
class CudnnNetworkComputation
CuDNN network computation class.
class Engine
class EngineControllerBase
class EscCodes
struct EvalPosition
Represents a chess position and its legal moves for evaluation.
struct EvalResult
Stores the full result of a single neural network evaluation.
struct EvalResultPtr
Pointers to the result buffers for a single evaluation.
class Evaluator
class Exception
struct ExecuteConvDesc
class ExponentialBackoffSpinHelper
struct File
class Float16OnnxConst
class Float16OnnxWeightsAdapter
class Float8E5M2OnnxConst
class Float8E5M2OnnxWeightsAdapter
class FloatOnnxConst
class FloatOnnxWeightsAdapter
class FloatOption
class FullyConnectedLayer
Implements a Fully Connected (Dense) Layer.
struct GameInfo
struct GameState
struct GemmCreateDesc
struct GemmExecuteDesc
struct GemmInitDesc
class GenericOnnxConst
struct GoParams
class HashKeyedCache
class HashKeyedCacheLock
class Histogram
class HloBuilder
class HloComputation
class HloContext
class HloTensorType
class HloType
struct InitConvDesc
struct InputPlane
Represents a single input plane for the neural network.
struct InputsOutputs
class Int32OnnxConst
class Int64OnnxConst
class IntOption
class IterateBits
class KingAttackInfo
class LayerAdapter
struct LegacyWeights
class Logging
class LogMessage
class LruCache
class LruCacheLock
class MockBackend
class MockBackendComputation
class MockBackendFactory
class MockSearch
Mock implementation of SearchBase for unit testing.
class MockSearchFactory
Mock implementation of SearchFactory for unit testing.
class Move
Represents a chess move in the Lc0 engine.
struct MultiHeadWeights
class MultiSelfPlayGames
class Network
Abstract base class for a neural network backend.
class NetworkAsBackendFactory
struct NetworkCapabilities
Describes the capabilities and requirements of a neural network backend.
class NetworkComputation
Abstract interface for neural network computation backends.
class NetworkFactory
Factory methods for creating Network instances.
class NonOwningUciRespondForwarder
class Numa
class OnednnNetwork
class OnednnNetworkComputation
struct Onnx2HloOptions
struct Onnx2HloResult
class OnnxBuilder
class OnnxConst
struct Opening
class OptionId
class OptionsDict
class OptionsParser
class PgnReader
struct PieceType
class Pjrt
class PjrtClient
class PjrtCommon
Shared base class for all PJRT wrappers.
class PjrtDevice
class PjrtDeviceBuffer
Represents a buffer in device memory.
class PjrtEvent
Represents a PJRT event for asynchronous operations.
class PjrtException
Exception class for PJRT errors.
class PjrtExecutable
class PjrtHostToDeviceTransfer
Handles ongoing host-to-device transfer.
class PjrtKeyValue
Wrapper for PJRT_NamedValue.
struct PlayerOptions
class PolicyEvaluator
class Position
Represents a chess position in the Lc0 engine.
class PositionHistory
Maintains a history of chess positions in a game.
struct PrettyPrintHloOptions
class ProtoMessage
class Random
Thread-safe random number generator for the Lc0 engine.
struct Rank
struct SearchArtifacts
Container for search artifacts used in training data generation.
class SearchBase
Abstract base class for all search algorithm implementations.
class SearchFactory
Factory interface for creating search algorithm instances.
class SearchManager
Singleton manager for search algorithm factory registration.
class SelfPlayGame
struct SelfPlayLimits
class SelfPlayLoop
class SelfPlayTournament
struct SharedBackendParams
class SmallArray
A lightweight, non-resizeable array implementation optimized for small collections.
class SpinHelper
class Square
class StderrLogMessage
class StdoutLogMessage
class StdoutUciResponder
class StringOption
class StringUciResponder
class SyclNetwork
SYCL network implementation.
class SyclNetworkComputation
SYCL network computation class.
class SyzygyTablebase
Interface for loading and probing Syzygy endgame tablebases.
class SyzygyTablebaseImpl
Internal implementation of Syzygy tablebase probing.
struct TensorDesc
struct ThinkingInfo
struct TournamentInfo
class TrainingDataReader
class TrainingDataWriter
class TransformingUciResponder
class TypeDict
class UciLoop
class UciResponder
class UciResponderForwarder
struct V6TrainingData
class V6TrainingDataArray
class ValueEvaluator
struct WeightsToOnnxConverterOptions
class WinogradConvolution3
Convolution 3x3 on a 8x8 board using the Winograd algorithm.
class XlaMutableTensor
class XlaRunner
Manages XLA executables and execution.
class XlaTensor
class XlaTensorNotOwned
Typedefs
using MoveList = std::vector< Move >
template<typename T >
using EigenMatrixMap = Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > >
template<typename T >
using ConstEigenMatrixMap = Eigen::Map< const Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > >
template<typename T >
using EigenVectorMap = Eigen::Map< Eigen::Matrix< T, Eigen::Dynamic, 1 > >
template<typename T >
using ConstEigenVectorMap = Eigen::Map< const Eigen::Matrix< T, Eigen::Dynamic, 1 > >
using FloatVector = std::vector< float >
using FloatVectors = std::vector< FloatVector >
using WeightsFile = pblczero::Net
using InputPlanes = std::vector< InputPlane >
using HloFlow = const pblczero::HloInstructionProto *
using InstructionList = std::vector< std::unique_ptr< pblczero::HloInstructionProto > >
Enumerations
enum class GameResult : uint8_t { UNDECIDED , BLACK_WON , DRAW , WHITE_WON }
enum class PjrtErrorCode {
CANCELLED = 1 , UNKNOWN = 2 , INVALID_ARGUMENT = 3 , DEADLINE_EXCEEDED = 4 ,
NOT_FOUND = 5 , ALREADY_EXISTS = 6 , PERMISSION_DENIED = 7 , RESOURCE_EXHAUSTED = 8 ,
FAILED_PRECONDITION = 9 , ABORTED = 10 , OUT_OF_RANGE = 11 , UNIMPLEMENTED = 12 ,
INTERNAL = 13 , UNAVAILABLE = 14 , DATA_LOSS = 15 , UNAUTHENTICATED = 16
}
PJRT error codes.
enum class PjrtType {
INVALID , PRED , S8 , S16 ,
S32 , S64 , U8 , U16 ,
U32 , U64 , F16 , F32 ,
F64 , BF16 , C64 , C128 ,
F8E5M2 , F8E4M3FN , F8E4M3B11FNUZ , F8E5M2FNUZ ,
F8E4M3FNUZ , S4 , U4
}
PJRT data types.
enum class FillEmptyHistory { NO , FEN_ONLY , ALWAYS }
enum InputEmbedding { INPUT_EMBEDDING_NONE = 0 , INPUT_EMBEDDING_PE_MAP = 1 , INPUT_EMBEDDING_PE_DENSE = 2 }
enum ActivationFunction {
ACTIVATION_DEFAULT = 0 , ACTIVATION_MISH = 1 , ACTIVATION_RELU = 2 , ACTIVATION_NONE = 3 ,
ACTIVATION_TANH = 4 , ACTIVATION_SIGMOID = 5 , ACTIVATION_SELU = 6 , ACTIVATION_SWISH = 7 ,
ACTIVATION_RELU_2 = 8 , ACTIVATION_SOFTMAX = 9
}
enum WDLScore {
WDL_LOSS = -2 , WDL_BLESSED_LOSS , WDL_DRAW = 0 , WDL_CURSED_WIN = 1 ,
WDL_WIN = 2
}
Win/Draw/Loss score from tablebase probing.
enum ProbeState { FAIL = 0 , OK = 1 , CHANGE_STM = -1 , ZEROING_BEST_MOVE = 2 }
Possible states after a tablebase probe operation.
enum BoardTransform { NoTransform = 0 , FlipTransform = 1 , MirrorTransform = 2 , TransposeTransform = 4 }
Functions
void InitializeMagicBitboards ()
std::string BoardToFen (const ChessBoard &in_board)
TEST (ChessBoard, IllegalFirstRankPawns)
TEST (ChessBoard, PseudolegalMovesStartingPos)
TEST (ChessBoard, PartialFen)
TEST (ChessBoard, PartialFenWithSpaces)
TEST (ChessBoard, MoveGenKiwipete)
TEST (ChessBoard, MoveGenPosition3)
TEST (ChessBoard, MoveGenPosition4)
TEST (ChessBoard, MoveGenPosition5)
TEST (ChessBoard, MoveGenPosition6)
TEST (ChessBoard, FRC)
TEST (ChessBoard, HasMatingMaterialStartPosition)
TEST (ChessBoard, HasMatingMaterialBareKings)
TEST (ChessBoard, HasMatingMaterialSingleMinorPiece)
TEST (ChessBoard, HasMatingMaterialSingleMajorPieceOrPawn)
TEST (ChessBoard, HasMatingMaterialTwoKnights)
TEST (ChessBoard, HasMatingMaterialBishopAndKnight)
TEST (ChessBoard, HasMatingMaterialMultipleBishopsSameColor)
TEST (ChessBoard, HasMatingMaterialMultipleBishopsNotSameColor)
TEST (ChessBoard, InvalidFEN)
TEST (ChessBoard, InvalidEnPassantFromKnightPromotion)
TEST (ChessBoard, QueenMoveFromEnPassantFlagBug)
bool GzGetLine (gzFile file, std::string &line)
GameResult operator- (const GameResult &res)
std::string PositionToFen (const Position &pos)
TEST (Position, SetFenGetFen)
TEST (PositionHistory, ComputeLastMoveRepetitionsWithoutLegalEnPassant)
TEST (PositionHistory, ComputeLastMoveRepetitionsWithLegalEnPassant)
TEST (PositionHistory, DidRepeatSinceLastZeroingMoveCurent)
TEST (PositionHistory, DidRepeatSinceLastZeroingMoveBefore)
TEST (PositionHistory, DidRepeatSinceLastZeroingMoveOlder)
TEST (PositionHistory, DidRepeatSinceLastZeroingMoveBeforeZero)
TEST (PositionHistory, DidRepeatSinceLastZeroingMoveNeverRepeated)
int operator- (File a, File b)
int operator- (Rank a, Rank b)
void RunEngine (SearchFactory *factory)
void ChooseAndRunEngine ()
void LayerNorm2DWithSkipConnection (const size_t batch_size, const size_t channels, float *data, const float alpha, const float *skip, const float *gammas, const float *betas, float epsilon)
Performs layer normalization with an optional skip connection for 2D data.
static void global_avg_pooling (size_t batches, size_t channels, const float *input, const float *bias, float *output)
Computes global average pooling.
static void apply_se (const size_t channels, const size_t batch_size, const float *input, const float *bias, const float *res, const float *scale, float *output, const ActivationFunction activation)
Applies Squeeze-and-Excitation (SE) scaling.
template<bool use_eigen>
void ApplySEUnit (const size_t batch_size, const size_t channels, const size_t se_fc_outputs, const float *input, const float *bias, const float *residual, const float *weights_w1, const float *weights_b1, const float *weights_w2, const float *weights_b2, float *output, const ActivationFunction activation)
Applies Squeeze-and-Excitation (SE) unit.
template void ApplySEUnit< true > (const size_t batch_size, const size_t channels, const size_t se_fc_outputs, const float *input, const float *bias, const float *residual, const float *weights_w1, const float *weights_b1, const float *weights_w2, const float *weights_b2, float *output, const ActivationFunction activation)
template void ApplySEUnit< false > (const size_t batch_size, const size_t channels, const size_t se_fc_outputs, const float *input, const float *bias, const float *residual, const float *weights_w1, const float *weights_b1, const float *weights_w2, const float *weights_b2, float *output, const ActivationFunction activation)
static size_t getMaxAttentionHeadSize (const MultiHeadWeights::PolicyHead &weights, int N)
Computes maximum attention head size.
static size_t getMaxAttentionBodySize (const MultiHeadWeights &weights, int N)
Computes maximum attention body size.
template<typename DataType >
std::unique_ptr< Network > MakeCudaNetwork (const std::optional< WeightsFile > &w, const OptionsDict &options)
std::unique_ptr< Network > MakeCudaNetworkAuto (const std::optional< WeightsFile > &weights, const OptionsDict &options)
static size_t getMaxAttentionHeadSize (const MultiHeadWeights::PolicyHead &weights, int N)
Computes maximum attention head size.
template<typename DataType >
std::unique_ptr< Network > MakeCudnnNetwork (const std::optional< WeightsFile > &w, const OptionsDict &options)
std::unique_ptr< Network > MakeCudnnNetworkAuto (const std::optional< WeightsFile > &weights, const OptionsDict &options)
std::unique_ptr< Network > MakeRandomNetwork (const std::optional< WeightsFile > &, const OptionsDict &options)
Factory function to create a RandomNetwork instance.
std::unique_ptr< Network > MakeTrivialNetwork (const std::optional< WeightsFile > &, const OptionsDict &options)
Factory function to create a TrivialNetwork instance.
std::unique_ptr< Network > MakeOnednnNetwork (const std::optional< WeightsFile > &w, const OptionsDict &options)
void SoftmaxActivation (const size_t size, const float *input, float *output)
Computes Softmax activation for a vector.
static float mish (float val)
static float selu (float val)
float Activate (const float val, const ActivationFunction activation)
Applies activation function to a single value.
void Activate (const size_t len, const float *data, const float *bias, float *output, const ActivationFunction activation)
Applies activation function to a vector with bias: output = activation(data + bias).
void Activate (const size_t len, float gamma, const float *data, const float *bias, float beta, float *out, const ActivationFunction activation)
Applies activation with batch normalization parameters: output = activation(gamma * data + bias + beta).
void BiasResidual (const size_t batch_size, const size_t channels, float *data, const float *biases, const float *eltwise, const ActivationFunction activation)
Computes: array = activation(array + residual + bias).
void BiasActivate (const size_t batch_size, const size_t channels, float *data, const float *biases, const ActivationFunction activation)
Computes: array = activation(array + bias).
std::vector< float > WinogradFilterZeropadU (const std::vector< float > &U, const size_t outputs, const size_t channels, const size_t outputs_pad, const size_t channels_pad)
Create the zero-padded U matrix for 3x3 Winograd convolution.
std::vector< float > WinogradFilterTransformF (const std::vector< float > &f, const size_t outputs, const size_t channels)
Create the filter transform matrix F(2x2, 3x3).
static size_t getMaxAttentionHeadSize (const MultiHeadWeights::PolicyHead &weights, int N)
Computes maximum attention head size.
static size_t getMaxAttentionBodySize (const MultiHeadWeights &weights, int N)
Computes maximum attention body size.
template<typename DataType >
std::unique_ptr< Network > MakeSyclNetwork (const std::optional< WeightsFile > &w, const OptionsDict &options)
std::unique_ptr< Network > MakeSyclNetworkAuto (const std::optional< WeightsFile > &weights, const OptionsDict &options)
PjrtKeyValue MakeKeyValue (const PJRT_NamedValue *kv)
std::unique_ptr< Backend > CreateBatchSplitingBackend (Backend *parent)
void PopulateBoard (pblczero::NetworkFormat::InputFormat input_format, InputPlanes planes, ChessBoard *board, int *rule50, int *gameply)
Reconstructs a ChessBoard object from input planes.
Move DecodeMoveFromInput (const InputPlanes &planes, const InputPlanes &prev)
Reconstructs the move that led to the current position from input planes.
bool IsCanonicalFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format is one of the canonical formats.
bool IsCanonicalArmageddonFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format is for Armageddon games.
bool IsHectopliesFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format uses hectoplies (100 half-moves) for time encoding.
bool Is960CastlingFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format supports Chess960 castling rules.
int TransformForPosition (pblczero::NetworkFormat::InputFormat input_format, const PositionHistory &history)
Determines the required transformation for a position based on history.
InputPlanes EncodePositionForNN (pblczero::NetworkFormat::InputFormat input_format, std::span< const Position > history, int history_planes, FillEmptyHistory fill_empty_history, int *transform_out)
InputPlanes EncodePositionForNN (pblczero::NetworkFormat::InputFormat input_format, const PositionHistory &history, int history_planes, FillEmptyHistory fill_empty_history, int *transform_out)
Encodes a position history into input planes for the neural network.
uint16_t MoveToNNIndex (Move move, int transform)
Converts a move to a neural network output index.
Move MoveFromNNIndex (int idx, int transform)
Converts a neural network output index back to a move.
TEST (EncodePositionForNN, EncodeStartPosition)
TEST (EncodePositionForNN, EncodeStartPositionFormat2)
TEST (EncodePositionForNN, EncodeStartPositionFormat3)
TEST (EncodePositionForNN, EncodeFiftyMoveCounter)
TEST (EncodePositionForNN, EncodeFiftyMoveCounterFormat3)
TEST (EncodePositionForNN, EncodeEndGameFormat1)
TEST (EncodePositionForNN, EncodeEndGameFormat3)
TEST (EncodePositionForNN, EncodeEndGameKingOnDiagonalFormat3)
TEST (EncodePositionForNN, EncodeEnpassantFormat3)
TEST (EncodePositionForNN, EncodeEarlyGameFlipFormat3)
WeightsFile LoadWeightsFromFile (const std::string &filename)
std::optional< WeightsFile > LoadWeights (std::string_view location)
std::string DiscoverWeightsFile ()
std::unique_ptr< CachingBackend > CreateMemCache (std::unique_ptr< Backend > wrapped, const OptionsDict &options)
pblczero::Net ConvertWeightsToOnnx (const pblczero::Net &net, const WeightsToOnnxConverterOptions &options)
Onnx2HloResult ConvertOnnxToHlo (const pblczero::ModelProto &onnx_model, size_t minibatch_size, const Onnx2HloOptions &options)
std::unique_ptr< XlaTensor > OnnxTensorToXlaTensor (const pblczero::TensorProto &onnx_tensor)
void PrettyPrintHlo (const pblczero::HloModuleProto &module, PrettyPrintHloOptions options, std::ostream &stream)
pblczero::XlaShapeProto::Type StringToXlaType (const std::string &type)
size_t GetXlaTypeSize (pblczero::XlaShapeProto::Type type)
void TestValidRootExpectation (SyzygyTablebase *tablebase, const std::string &fen, const std::vector< std::string > &valid_moves, const std::vector< std::string > &invalid_moves, const std::vector< std::string > &invalid_dtz_only={}, bool has_repeated=false)
void TestValidExpectation (SyzygyTablebase *tablebase, const std::string &fen, WDLScore expected, int expected_dtz)
TEST (Syzygy, Simple3PieceProbes)
TEST (Syzygy, Root3PieceProbes)
TEST (Syzygy, Simple4PieceProbes)
TEST (Syzygy, Simple5PieceProbes)
TEST (Syzygy, Root5PieceProbes)
void ShowNetworkGenericInfo (const pblczero::Net &weights)
void ShowNetworkFormatInfo (const pblczero::Net &weights)
void ShowNetworkTrainingInfo (const pblczero::Net &weights)
void ShowNetworkWeightsBodyInfo (const pblczero::Net &weights)
void ShowNetworkWeightsPolicyInfo (const pblczero::Net &weights)
void ShowNetworkWeightsInfo (const pblczero::Net &weights)
void ShowNetworkOnnxInfo (const pblczero::Net &weights, bool show_onnx_internals)
void ShowAllNetworkInfo (const pblczero::Net &weights)
void DescribeNetworkCmd ()
void ConvertLeelaToOnnx ()
void ConvertOnnxToLeela ()
InputPlanes PlanesFromTrainingData (const V6TrainingData &data)
void RunRescorer ()
std::vector< V6TrainingData > RescoreTrainingData (std::vector< V6TrainingData > fileContents, SyzygyTablebase *tablebase, float distTemp, float distOffset, float dtzBoost, int newInputFormat)
bool RescorerDeblunderSetup (float threshold, float width)
bool RescorerGaviotaSetup (std::string dtmPaths)
bool RescorerPolicySubstitutionSetup (std::string policySubsDir)
static uint16_t FP32toBF16 (float f32)
static float BF16toFP32 (uint16_t bf16)
template<class To , class From >
To bit_cast (const From &src) noexcept
unsigned long GetLowestBit (std::uint64_t value)
uint64_t ReverseBitsInBytes (uint64_t v)
uint64_t ReverseBytesInBytes (uint64_t v)
uint64_t TransposeBitsInBytes (uint64_t v)
float FastLog2 (const float a)
float FastExp2 (const float a)
float FastLog (const float a)
float FastExp (const float a)
float FastLogistic (const float a)
float FastSign (const float a)
std::string ReadFileToString (const std::string &filename)
void WriteStringToFile (const std::string &filename, const std::string_view content)
void WriteStringToGzFile (const std::string &filename, std::string_view content)
void CreateDirectory (const std::string &path)
std::vector< std::string > GetFileList (const std::string &directory)
uint64_t GetFileSize (const std::string &filename)
time_t GetFileTime (const std::string &filename)
std::string GetUserCacheDirectory ()
std::string GetUserConfigDirectory ()
std::string GetUserDataDirectory ()
std::vector< std::string > GetSystemConfigDirectoryList ()
std::vector< std::string > GetSystemDataDirectoryList ()
uint16_t FP32toFP16 (float f32)
float FP16toFP32 (uint16_t f16)
testing::AssertionResult FP16Equal (const char *a_expr, const char *b_expr, uint16_t a, uint16_t b)
TEST (FP16, TestNormalConversion)
uint8_t FP32toFP8E5M2 (float f32, bool saturate=true)
uint8_t FP32toFP8E5M2_Saturate (float f32)
float FP8E5M2toFP32 (uint8_t f8)
uint8_t FP32toFP8E4M3FN (float f32, bool saturate=true)
float FP8E4M3FNtoFP32 (uint8_t f8)
uint64_t Hash (uint64_t val)
uint64_t HashCat (uint64_t hash, uint64_t x)
uint64_t HashCat (std::initializer_list< uint64_t > args)
TEST (HashCat, TestCollision)
std::chrono::time_point< std::chrono::system_clock > SteadyClockToSystemClock (std::chrono::time_point< std::chrono::steady_clock > time)
std::string FormatTime (std::chrono::time_point< std::chrono::system_clock > time)
class CAPABILITY ("mutex") RpSharedMutex
static void SpinloopPause ()
TEST (OptionsParser, CheckInvalidOption)
TEST (OptionsParser, IntOptionCheckValueConstraints)
TEST (OptionsParser, FloatOptionCheckValueConstraints)
TEST (OptionsParser, BoolOptionsCheckValueConstraints)
TEST (OptionsParser, ChoiceOptionCheckValueConstraints)
std::string StrJoin (const std::vector< std::string > &strings, const std::string &delim)
std::vector< std::string > StrSplitAtWhitespace (const std::string &str)
std::vector< std::string > StrSplit (const std::string &str, const std::string &delim)
std::vector< int > ParseIntList (const std::string &str)
std::string LeftTrim (std::string str)
std::string RightTrim (std::string str)
std::string Trim (std::string str)
bool StringsEqualIgnoreCase (const std::string &a, const std::string &b)
std::vector< std::string > FlowText (const std::string &src, size_t width)
template<class T >
void TransposeTensor (const std::vector< int > &dims, std::vector< int > order, const std::vector< T > from, T *to)
Variables
constexpr PieceType kKnight = PieceType::FromIdx(0)
constexpr PieceType kQueen = PieceType::FromIdx(1)
constexpr PieceType kRook = PieceType::FromIdx(2)
constexpr PieceType kBishop = PieceType::FromIdx(3)
constexpr PieceType kPawn = PieceType::FromIdx(4)
constexpr PieceType kKing = PieceType::FromIdx(5)
constexpr File kFileA = File::FromIdx(0)
constexpr File kFileB = File::FromIdx(1)
constexpr File kFileC = File::FromIdx(2)
constexpr File kFileD = File::FromIdx(3)
constexpr File kFileE = File::FromIdx(4)
constexpr File kFileF = File::FromIdx(5)
constexpr File kFileG = File::FromIdx(6)
constexpr File kFileH = File::FromIdx(7)
constexpr Rank kRank1 = Rank::FromIdx(0)
constexpr Rank kRank2 = Rank::FromIdx(1)
constexpr Rank kRank3 = Rank::FromIdx(2)
constexpr Rank kRank4 = Rank::FromIdx(3)
constexpr Rank kRank5 = Rank::FromIdx(4)
constexpr Rank kRank6 = Rank::FromIdx(5)
constexpr Rank kRank7 = Rank::FromIdx(6)
constexpr Rank kRank8 = Rank::FromIdx(7)
constexpr Square kSquareA1 = Square(kFileA, kRank1)
constexpr Square kSquareC1 = Square(kFileC, kRank1)
constexpr Square kSquareE1 = Square(kFileE, kRank1)
constexpr Square kSquareG1 = Square(kFileG, kRank1)
constexpr Square kSquareH1 = Square(kFileH, kRank1)
constexpr GUID GemmGuid
constexpr GUID ConvGuid
static constexpr int kNumOutputPolicy = 1858
constexpr int kMoveHistory = 8
constexpr int kPlanesPerBoard = 13
constexpr int kAuxPlaneBase = kPlanesPerBoard * kMoveHistory
auto kAllSquaresMask = std::numeric_limits<std::uint64_t>::max()
const int kInputPlanes = 112
const short kAttnPolicyMap []
constexpr int kNumPosEncodingChannels = 64
const float kPosEncoding [64][kNumPosEncodingChannels]
const short kConvPolicyMap []
constexpr auto kPaths = "syzygy"
struct lczero::V6TrainingData PACKED_STRUCT
Typedef Documentation
ConstEigenMatrixMap
template<typename T > using lczero::ConstEigenMatrixMap = typedef Eigen::Map<const Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> >
Definition at line 27 of file convolution1.cc.
ConstEigenVectorMap
template<typename T > using lczero::ConstEigenVectorMap = typedef Eigen::Map<const Eigen::Matrix<T, Eigen::Dynamic, 1> >
Definition at line 47 of file fully_connected_layer.cc.
EigenMatrixMap
template<typename T > using lczero::EigenMatrixMap = typedef Eigen::Map<Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic> >
Definition at line 24 of file convolution1.cc.
EigenVectorMap
template<typename T > using lczero::EigenVectorMap = typedef Eigen::Map<Eigen::Matrix<T, Eigen::Dynamic, 1> >
Definition at line 45 of file fully_connected_layer.cc.
FloatVector
using lczero::FloatVector = typedef std::vector<float>
Definition at line 41 of file loader.h.
FloatVectors
using lczero::FloatVectors = typedef std::vector<FloatVector>
Definition at line 42 of file loader.h.
HloFlow
using lczero::HloFlow = typedef const pblczero::HloInstructionProto*
Definition at line 43 of file hlo_builder.h.
InputPlanes
using lczero::InputPlanes = typedef std::vector<InputPlane>
Definition at line 62 of file network.h.
InstructionList
using lczero::InstructionList = typedef std::vector<std::unique_ptr<pblczero::HloInstructionProto> >
Definition at line 44 of file hlo_builder.h.
MoveList
using lczero::MoveList = typedef std::vector<Move>
Definition at line 304 of file types.h.
WeightsFile
using lczero::WeightsFile = typedef pblczero::Net
Definition at line 44 of file loader.h.
Enumeration Type Documentation
ActivationFunction
enum lczero::ActivationFunction
Enumerator
ACTIVATION_DEFAULT
ACTIVATION_MISH
ACTIVATION_RELU
ACTIVATION_NONE
ACTIVATION_TANH
ACTIVATION_SIGMOID
ACTIVATION_SELU
ACTIVATION_SWISH
ACTIVATION_RELU_2
ACTIVATION_SOFTMAX
Definition at line 24 of file activation_function.h.
BoardTransform
enum lczero::BoardTransform
Enumerator
NoTransform
FlipTransform
MirrorTransform
TransposeTransform
Definition at line 56 of file bititer.h.
FillEmptyHistory
enum class lczero::FillEmptyHistory strong
Enumerator
NO
FEN_ONLY
ALWAYS
Definition at line 42 of file encoder.h.
GameResult
enum class lczero::GameResult : uint8_t strong
Enumerator
UNDECIDED
BLACK_WON
DRAW
WHITE_WON
Definition at line 135 of file position.h.
InputEmbedding
enum lczero::InputEmbedding
Enumerator
INPUT_EMBEDDING_NONE
INPUT_EMBEDDING_PE_MAP
INPUT_EMBEDDING_PE_DENSE
Definition at line 231 of file network_legacy.h.
PjrtErrorCode
enum class lczero::PjrtErrorCode strong
PJRT error codes.
Coincidentally, the error codes are the same as in absl Status module.
Enumerator
CANCELLED
UNKNOWN
INVALID_ARGUMENT
DEADLINE_EXCEEDED
NOT_FOUND
ALREADY_EXISTS
PERMISSION_DENIED
RESOURCE_EXHAUSTED
FAILED_PRECONDITION
ABORTED
OUT_OF_RANGE
UNIMPLEMENTED
INTERNAL
UNAVAILABLE
DATA_LOSS
UNAUTHENTICATED
Definition at line 51 of file pjrt.h.
PjrtType
enum class lczero::PjrtType strong
PJRT data types.
Unfortunately, only the first 13 types are the same as in XLA and HloModuleProto.
Enumerator
INVALID
PRED
S8
S16
S32
S64
U8
U16
U32
U64
F16
F32
F64
BF16
C64
C128
F8E5M2
F8E4M3FN
F8E4M3B11FNUZ
F8E5M2FNUZ
F8E4M3FNUZ
S4
U4
Definition at line 73 of file pjrt.h.
ProbeState
enum lczero::ProbeState
Possible states after a tablebase probe operation.
Indicates whether the probe succeeded and provides additional information about the nature of optimal play.
Enumerator
FAIL
Probe failed (tablebase file not available).
OK
Probe successful.
CHANGE_STM
DTZ should probe the other side to move.
ZEROING_BEST_MOVE
Best move zeroes DTZ counter (capture/pawn move).
Definition at line 66 of file syzygy.h.
WDLScore
enum lczero::WDLScore
Win/Draw/Loss score from tablebase probing.
Represents the theoretical outcome of a position assuming optimal play from both sides. Includes special cases for 50-move rule interactions.
Enumerator
WDL_LOSS
Losing position (opponent wins).
WDL_BLESSED_LOSS
Theoretically lost, but drawable under 50-move rule.
WDL_DRAW
Drawn position.
WDL_CURSED_WIN
Theoretically won, but drawable under 50-move rule.
WDL_WIN
Winning position (side to move wins).
Definition at line 54 of file syzygy.h.
Function Documentation
Activate() [1/3]
float lczero::Activate (const float val, const ActivationFunction activation)
Applies activation function to a single value.
Parameters
val Input value.
activation Activation function.
Returns
Activated value.
Definition at line 71 of file activation.cc.
References ACTIVATION_MISH, ACTIVATION_NONE, ACTIVATION_RELU, ACTIVATION_RELU_2, ACTIVATION_SELU, ACTIVATION_SIGMOID, ACTIVATION_SWISH, ACTIVATION_TANH, mish(), and selu().
Referenced by Activate(), Activate(), apply_se(), BiasActivate(), and BiasResidual().
Activate() [2/3]
void lczero::Activate (const size_t len, const float * data, const float * bias, float * output, const ActivationFunction activation)
Applies activation function to a vector with bias: output = activation(data + bias).
Parameters
len Length of the vector.
data Input data.
bias Bias data.
output Output buffer.
activation Activation function.
Definition at line 96 of file activation.cc.
References Activate(), ACTIVATION_MISH, ACTIVATION_NONE, ACTIVATION_RELU, ACTIVATION_RELU_2, ACTIVATION_SELU, ACTIVATION_SWISH, bias, data, mish(), output, and selu().
Activate() [3/3]
void lczero::Activate (const size_t len, float gamma, const float * data, const float * bias, float beta, float * out, const ActivationFunction activation)
Applies activation with batch normalization parameters: output = activation(gamma * data + bias + beta).
Parameters
len Length of the vector.
gamma Batch norm gamma.
data Input data.
bias Bias data.
beta Batch norm beta.
out Output buffer.
activation Activation function.
Definition at line 156 of file activation.cc.
References Activate(), ACTIVATION_MISH, ACTIVATION_NONE, ACTIVATION_RELU, bias, data, mish(), and output.
apply_se()
static void lczero::apply_se (const size_t channels, const size_t batch_size, const float * input, const float * bias, const float * res, const float * scale, float * output, const ActivationFunction activation) static
Applies Squeeze-and-Excitation (SE) scaling.
Scales the input by the computed excitation values.
Parameters
channels Number of channels.
batch_size Batch size.
input Input data.
bias Channel biases.
res Residual data.
scale Scaling factors (excitation).
output Output data.
activation Activation function.
Definition at line 65 of file se_unit.cc.
References Activate(), bias, input, kSquares, and output.
Referenced by ApplySEUnit().
ApplySEUnit()
template<bool use_eigen> void lczero::ApplySEUnit (const size_t batch_size, const size_t channels, const size_t se_fc_outputs, const float * input, const float * bias, const float * residual, const float * weights_w1, const float * weights_b1, const float * weights_w2, const float * weights_b2, float * output, const ActivationFunction activation)
Applies Squeeze-and-Excitation (SE) unit.
Template Parameters
use_eigen If true, uses Eigen; otherwise uses BLAS.
Parameters
batch_size Batch size.
channels Number of channels.
se_fc_outputs Number of outputs for the squeeze fully connected layer.
input Input data.
bias Channel biases.
residual Residual connection data.
weights_w1 Weights for first FC layer.
weights_b1 Biases for first FC layer.
weights_w2 Weights for second FC layer.
weights_b2 Biases for second FC layer.
output Output buffer.
activation Activation function used inside SE block.
Definition at line 85 of file se_unit.cc.
References ACTIVATION_NONE, apply_se(), lczero::FullyConnectedLayer< use_eigen >::Forward1D(), global_avg_pooling(), input, and output.
ApplySEUnit< false >()
template void lczero::ApplySEUnit< false > (const size_t batch_size, const size_t channels, const size_t se_fc_outputs, const float * input, const float * bias, const float * residual, const float * weights_w1, const float * weights_b1, const float * weights_w2, const float * weights_b2, float * output, const ActivationFunction activation)
ApplySEUnit< true >()
template void lczero::ApplySEUnit< true > (const size_t batch_size, const size_t channels, const size_t se_fc_outputs, const float * input, const float * bias, const float * residual, const float * weights_w1, const float * weights_b1, const float * weights_w2, const float * weights_b2, float * output, const ActivationFunction activation)
BF16toFP32()
static float lczero::BF16toFP32 (uint16_t bf16) inline static
Definition at line 42 of file bf16_utils.h.
Referenced by lczero::onnx::AsFloat(), lczero::XlaMutableTensor::Cast(), and lczero::LayerAdapter::Iterator::ExtractValue().
BiasActivate()
void lczero::BiasActivate (const size_t batch_size, const size_t channels, float * data, const float * biases, const ActivationFunction activation)
Computes: array = activation(array + bias).
Parameters
batch_size Batch size.
channels Number of channels.
data Pointer to data (array).
biases Pointer to biases.
activation The activation function to apply.
Definition at line 233 of file activation.cc.
References Activate(), ACTIVATION_MISH, ACTIVATION_NONE, ACTIVATION_RELU, bias, data, kSquares, and mish().
BiasResidual()
void lczero::BiasResidual (const size_t batch_size, const size_t channels, float * data, const float * biases, const float * eltwise, const ActivationFunction activation)
Computes: array = activation(array + residual + bias).
Parameters
batch_size Batch size.
channels Number of channels.
data Pointer to data (array).
biases Pointer to biases.
eltwise Pointer to residual data.
activation The activation function to apply.
Definition at line 190 of file activation.cc.
References Activate(), ACTIVATION_MISH, ACTIVATION_NONE, ACTIVATION_RELU, bias, data, kSquares, and mish().
bit_cast()
template<class To , class From > To lczero::bit_cast (const From & src) noexcept
Definition at line 38 of file bit.h.
BoardToFen()
std::string lczero::BoardToFen (const ChessBoard & in_board)
Definition at line 1227 of file board.cc.
References lczero::ChessBoard::Castlings::as_string(), lczero::BitBoard::begin(), lczero::ChessBoard::castlings(), lczero::BitBoard::empty(), lczero::ChessBoard::en_passant(), lczero::Square::file(), lczero::ChessBoard::flipped(), lczero::Rank::IsValid(), kFileA, kFileH, kRank1, kRank3, kRank6, kRank8, lczero::ChessBoard::Mirror(), and result.
Referenced by lczero::ChessBoard::DebugString(), and PositionToFen().
CAPABILITY()
class lczero::CAPABILITY ("mutex")
Definition at line 1 of file mutex.h.
References ACQUIRE, ACQUIRE_SHARED, CAPABILITY, m, mutex_, RELEASE, RELEASE_SHARED, and SCOPED_CAPABILITY.
ChooseAndRunEngine()
void lczero::ChooseAndRunEngine ()
Definition at line 45 of file main.cc.
References lczero::CommandLine::BinaryName(), lczero::CommandLine::ConsumeCommand(), lczero::SearchManager::Get(), lczero::SearchManager::GetFactoryByName(), lczero::SearchManager::GetSearchNames(), and RunEngine().
Referenced by main().
ConvertLeelaToOnnx()
void lczero::ConvertLeelaToOnnx ()
Definition at line 132 of file leela2onnx.cc.
References lczero::WeightsToOnnxConverterOptions::alt_layernorm, lczero::WeightsToOnnxConverterOptions::batch_size, ConvertOnnxToHlo(), ConvertWeightsToOnnx(), COUT, lczero::WeightsToOnnxConverterOptions::data_type, lczero::Onnx2HloOptions::debugging_allow_partial_result, lczero::OptionsDict::Get(), lczero::OptionsParser::GetOptionsDict(), lczero::WeightsToOnnxConverterOptions::input_planes_name, lczero::WeightsToOnnxConverterOptions::ir, LoadWeightsFromFile(), lczero::WeightsToOnnxConverterOptions::opset, lczero::WeightsToOnnxConverterOptions::output_policy_head, lczero::WeightsToOnnxConverterOptions::output_value, lczero::WeightsToOnnxConverterOptions::output_wdl, lczero::OptionsDict::OwnExists(), lczero::WeightsToOnnxConverterOptions::policy_head, PrettyPrintHlo(), ShowNetworkFormatInfo(), ShowNetworkOnnxInfo(), ShowNetworkWeightsInfo(), lczero::WeightsToOnnxConverterOptions::StringToDataType(), lczero::WeightsToOnnxConverterOptions::value_head, and WriteStringToFile().
Referenced by main().
ConvertOnnxToHlo()
Onnx2HloResult lczero::ConvertOnnxToHlo (const pblczero::ModelProto & onnx_model, size_t minibatch_size, const Onnx2HloOptions & options)
Definition at line 1733 of file onnx2hlo.cc.
Referenced by ConvertLeelaToOnnx().
ConvertOnnxToLeela()
void lczero::ConvertOnnxToLeela ()
Definition at line 420 of file onnx2leela.cc.
References COUT, lczero::OptionsDict::Get(), lczero::OptionsParser::GetOptionsDict(), lczero::OptionsDict::OwnExists(), ReadFileToString(), ShowNetworkFormatInfo(), ShowNetworkOnnxInfo(), and WriteStringToGzFile().
Referenced by main().
ConvertWeightsToOnnx()
pblczero::Net lczero::ConvertWeightsToOnnx (const pblczero::Net & net, const WeightsToOnnxConverterOptions & options)
Definition at line 1239 of file converter.cc.
References ConvertWeightsToOnnx().
Referenced by ConvertLeelaToOnnx(), ConvertWeightsToOnnx(), and lczero::onnx::MakeOnnxNetwork().
CreateBatchSplitingBackend()
std::unique_ptr< Backend > lczero::CreateBatchSplitingBackend (Backend * parent)
Definition at line 97 of file batchsplit.cc.
CreateDirectory()
void lczero::CreateDirectory (const std::string & path)
Definition at line 38 of file filesystem.posix.cc.
Referenced by lczero::TrainingDataWriter::TrainingDataWriter().
CreateMemCache()
std::unique_ptr< CachingBackend > lczero::CreateMemCache (std::unique_ptr< Backend > wrapped, const OptionsDict & options)
Definition at line 188 of file memcache.cc.
Referenced by lczero::Benchmark::Run(), and lczero::Engine::UpdateBackendConfig().
DecodeMoveFromInput()
Move lczero::DecodeMoveFromInput (const InputPlanes & planes, const InputPlanes & prev)
Reconstructs the move that led to the current position from input planes.
Useful for debugging or recovering game state from network inputs.
Parameters
planes The current position's input planes.
prev The previous position's input planes.
Returns
The decoded Move.
Definition at line 253 of file decoder.cc.
References kBishop, kKnight, kQueen, kRank8, kRook, m, lczero::Move::White(), lczero::Move::WhiteCastling(), lczero::Move::WhiteEnPassant(), and lczero::Move::WhitePromotion().
DescribeNetworkCmd()
void lczero::DescribeNetworkCmd ()
Definition at line 307 of file describenet.cc.
References lczero::OptionsDict::Get(), lczero::OptionsParser::GetOptionsDict(), LoadWeightsFromFile(), and ShowAllNetworkInfo().
Referenced by main().
DiscoverWeightsFile()
std::string lczero::DiscoverWeightsFile ()
Definition at line 230 of file loader.cc.
References lczero::CommandLine::BinaryDirectory(), GetFileList(), GetFileSize(), GetFileTime(), GetSystemDataDirectoryList(), GetUserDataDirectory(), and LOGFILE.
Referenced by LoadWeights().
EncodePositionForNN() [1/2]
InputPlanes lczero::EncodePositionForNN (pblczero::NetworkFormat::InputFormat input_format, const PositionHistory & history, int history_planes, FillEmptyHistory fill_empty_history, int * transform_out)
Encodes a position history into input planes for the neural network.
Parameters
input_format The format required by the network.
history The position history.
history_planes The number of history planes to include.
fill_empty_history Strategy for filling missing history (e.g., at game start).
transform_out [out] Stores the transformation applied.
Returns
A vector of InputPlane structures representing the encoded position.
Definition at line 330 of file encoder.cc.
References EncodePositionForNN(), lczero::PositionHistory::GetPositions(), and input_format.
EncodePositionForNN() [2/2]
InputPlanes lczero::EncodePositionForNN (pblczero::NetworkFormat::InputFormat input_format, std::span< const Position > history, int history_planes, FillEmptyHistory fill_empty_history, int * transform_out)
Definition at line 134 of file encoder.cc.
References lczero::BitBoard::as_int(), lczero::ChessBoard::Castlings::as_int(), base, lczero::ChessBoard::bishops(), lczero::ChessBoard::castlings(), lczero::BitBoard::empty(), lczero::ChessBoard::en_passant(), FEN_ONLY, lczero::ChessBoard::flipped(), FlipTransform, lczero::BitBoard::FromSquare(), lczero::Position::GetBoard(), GetLowestBit(), lczero::Position::GetRepetitions(), lczero::Position::GetRule50Ply(), idx, input_format, IsCanonicalArmageddonFormat(), IsCanonicalFormat(), IsHectopliesFormat(), kAuxPlaneBase, lczero::ChessBoard::kings(), kMoveHistory, lczero::ChessBoard::knights(), kPlanesPerBoard, kRank1, kRank8, lczero::ChessBoard::kStartposBoard, lczero::ChessBoard::Mirror(), MirrorTransform, NO, NoTransform, lczero::ChessBoard::ours(), lczero::ChessBoard::pawns(), lczero::ChessBoard::queens(), result, ReverseBitsInBytes(), ReverseBytesInBytes(), lczero::ChessBoard::rooks(), lczero::ChessBoard::theirs(), lczero::ChessBoard::Castlings::they_can_00(), lczero::ChessBoard::Castlings::they_can_000(), transform, TransposeBitsInBytes(), TransposeTransform, lczero::ChessBoard::Castlings::we_can_00(), and lczero::ChessBoard::Castlings::we_can_000().
Referenced by lczero::V6TrainingDataArray::Add(), lczero::python::GameState::as_input(), EncodePositionForNN(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), TEST(), and TEST().
FastExp()
float lczero::FastExp (const float a) inline
Definition at line 86 of file fastmath.h.
References FastExp2().
Referenced by FastLogistic(), and lczero::python::Output::p_softmax().
FastExp2()
float lczero::FastExp2 (const float a) inline
Definition at line 59 of file fastmath.h.
Referenced by FastExp().
FastLog()
float lczero::FastLog (const float a) inline
Definition at line 81 of file fastmath.h.
References FastLog2().
FastLog2()
float lczero::FastLog2 (const float a) inline
Definition at line 42 of file fastmath.h.
Referenced by FastLog().
FastLogistic()
float lczero::FastLogistic (const float a) inline
Definition at line 89 of file fastmath.h.
References FastExp().
FastSign()
float lczero::FastSign (const float a) inline
Definition at line 95 of file fastmath.h.
FlowText()
std::vector< std::string > lczero::FlowText (const std::string & src, size_t width)
Definition at line 99 of file string.cc.
References result, and StrSplit().
FormatTime()
std::string lczero::FormatTime (std::chrono::time_point< std::chrono::system_clock > time)
Definition at line 103 of file logging.cc.
Referenced by lczero::LogMessage::LogMessage().
FP16Equal()
testing::AssertionResult lczero::FP16Equal (const char * a_expr, const char * b_expr, uint16_t a, uint16_t b)
Definition at line 34 of file fp16_utils_test.cc.
Referenced by TEST().
FP16toFP32()
float lczero::FP16toFP32 (uint16_t f16) inline
Definition at line 99 of file fp16_utils.h.
Referenced by lczero::onnx::AsFloat(), lczero::XlaMutableTensor::Cast(), lczero::dx_backend::DxContext::DumpCpuTensor(), lczero::dx_backend::DxNetwork::Eval(), lczero::LayerAdapter::Iterator::ExtractValue(), lczero::cudnn_backend::FromType(), and TEST().
FP32toBF16()
static uint16_t lczero::FP32toBF16 (float f32) inline static
Definition at line 30 of file bf16_utils.h.
Referenced by lczero::onnx::AsDataType(), lczero::XlaMutableTensor::Cast(), and lczero::BFloat16OnnxWeightsAdapter::GetRawData().
FP32toFP16()
uint16_t lczero::FP32toFP16 (float f32) inline
Definition at line 72 of file fp16_utils.h.
Referenced by lczero::onnx::AsDataType(), lczero::XlaMutableTensor::Cast(), lczero::cudnn_backend::cublasXgemm(), lczero::sycldnn_backend::cublasXgemm(), lczero::cudnn_backend::cublasXGemmBatched(), lczero::sycldnn_backend::cublasXGemmBatched(), lczero::cudnn_backend::cublasXGemmStridedBatched(), lczero::sycldnn_backend::cublasXGemmStridedBatched(), lczero::Float16OnnxWeightsAdapter::GetRawData(), TEST(), and lczero::cudnn_backend::ToType().
FP32toFP8E4M3FN()
uint8_t lczero::FP32toFP8E4M3FN (float f32, bool saturate = true) inline
Definition at line 111 of file fp8_utils.h.
FP32toFP8E5M2()
uint8_t lczero::FP32toFP8E5M2 (float f32, bool saturate = true) inline
Definition at line 44 of file fp8_utils.h.
Referenced by FP32toFP8E5M2_Saturate().
FP32toFP8E5M2_Saturate()
uint8_t lczero::FP32toFP8E5M2_Saturate (float f32) inline
Definition at line 75 of file fp8_utils.h.
References FP32toFP8E5M2().
Referenced by lczero::XlaMutableTensor::Cast().
FP8E4M3FNtoFP32()
float lczero::FP8E4M3FNtoFP32 (uint8_t f8) inline
Definition at line 140 of file fp8_utils.h.
FP8E5M2toFP32()
float lczero::FP8E5M2toFP32 (uint8_t f8) inline
Definition at line 82 of file fp8_utils.h.
Referenced by lczero::XlaMutableTensor::Cast().
GetFileList()
std::vector< std::string > lczero::GetFileList (const std::string & directory)
Definition at line 44 of file filesystem.posix.cc.
References result.
Referenced by DiscoverWeightsFile(), RescorerPolicySubstitutionSetup(), and RunRescorer().
GetFileSize()
uint64_t lczero::GetFileSize (const std::string & filename)
Definition at line 68 of file filesystem.posix.cc.
Referenced by DiscoverWeightsFile(), and lczero::SyzygyTablebaseImpl::map_tb().
GetFileTime()
time_t lczero::GetFileTime (const std::string & filename)
Definition at line 76 of file filesystem.posix.cc.
Referenced by DiscoverWeightsFile().
GetLowestBit()
unsigned long lczero::GetLowestBit (std::uint64_t value) inline
Definition at line 37 of file bititer.h.
References result, and value.
Referenced by EncodePositionForNN(), lczero::BitIterator< T, Convert >::operator*(), PopulateBoard(), and lczero::PgnReader::SanToMove().
getMaxAttentionBodySize() [1/2]
static size_t lczero::getMaxAttentionBodySize (const MultiHeadWeights & weights, int N) static
Computes maximum attention body size.
Definition at line 98 of file network_cuda.cc.
References lczero::BaseWeights::encoder, lczero::BaseWeights::encoder_head_count, and lczero::BaseWeights::ip_emb_b.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork(), and lczero::SyclNetwork< DataType >::SyclNetwork().
getMaxAttentionBodySize() [2/2]
static size_t lczero::getMaxAttentionBodySize (const MultiHeadWeights & weights, int N) static
Computes maximum attention body size.
Definition at line 92 of file network_sycl.cc.dp.cpp.
References lczero::BaseWeights::encoder, lczero::BaseWeights::encoder_head_count, and lczero::BaseWeights::ip_emb_b.
getMaxAttentionHeadSize() [1/3]
static size_t lczero::getMaxAttentionHeadSize (const MultiHeadWeights::PolicyHead & weights, int N) static
Computes maximum attention head size.
Definition at line 61 of file network_cuda.cc.
References lczero::MultiHeadWeights::PolicyHead::ip2_pol_b, lczero::MultiHeadWeights::PolicyHead::ip3_pol_b, lczero::MultiHeadWeights::PolicyHead::ip_pol_b, lczero::MultiHeadWeights::PolicyHead::pol_encoder, and lczero::MultiHeadWeights::PolicyHead::pol_encoder_head_count.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), and lczero::SyclNetwork< DataType >::SyclNetwork().
getMaxAttentionHeadSize() [2/3]
static size_t lczero::getMaxAttentionHeadSize (const MultiHeadWeights::PolicyHead & weights, int N) static
Computes maximum attention head size.
Definition at line 53 of file network_cudnn.cc.
References lczero::MultiHeadWeights::PolicyHead::ip2_pol_b, lczero::MultiHeadWeights::PolicyHead::ip3_pol_b, lczero::MultiHeadWeights::PolicyHead::ip_pol_b, lczero::MultiHeadWeights::PolicyHead::pol_encoder, and lczero::MultiHeadWeights::PolicyHead::pol_encoder_head_count.
getMaxAttentionHeadSize() [3/3]
static size_t lczero::getMaxAttentionHeadSize (const MultiHeadWeights::PolicyHead & weights, int N) static
Computes maximum attention head size.
Definition at line 55 of file network_sycl.cc.dp.cpp.
References lczero::MultiHeadWeights::PolicyHead::ip2_pol_b, lczero::MultiHeadWeights::PolicyHead::ip3_pol_b, lczero::MultiHeadWeights::PolicyHead::ip_pol_b, lczero::MultiHeadWeights::PolicyHead::pol_encoder, and lczero::MultiHeadWeights::PolicyHead::pol_encoder_head_count.
GetSystemConfigDirectoryList()
std::vector< std::string > lczero::GetSystemConfigDirectoryList ()
Definition at line 147 of file filesystem.posix.cc.
References result, and StrSplit().
Referenced by lczero::ConfigFile::ParseFile().
GetSystemDataDirectoryList()
std::vector< std::string > lczero::GetSystemDataDirectoryList ()
Definition at line 161 of file filesystem.posix.cc.
References result, and StrSplit().
Referenced by DiscoverWeightsFile().
GetUserCacheDirectory()
std::string lczero::GetUserCacheDirectory ()
Definition at line 96 of file filesystem.posix.cc.
GetUserConfigDirectory()
std::string lczero::GetUserConfigDirectory ()
Definition at line 113 of file filesystem.posix.cc.
Referenced by lczero::ConfigFile::ParseFile().
GetUserDataDirectory()
std::string lczero::GetUserDataDirectory ()
Definition at line 130 of file filesystem.posix.cc.
Referenced by DiscoverWeightsFile().
GetXlaTypeSize()
size_t lczero::GetXlaTypeSize (pblczero::XlaShapeProto::Type type) inline
Definition at line 43 of file xla_tensor.h.
References type.
Referenced by lczero::XlaMutableTensor::Cast(), and lczero::XlaMutableTensor::GetBufferSize().
global_avg_pooling()
static void lczero::global_avg_pooling (size_t batches, size_t channels, const float * input, const float * bias, float * output) static
Computes global average pooling.
Calculates the mean value for each channel across spatial dimensions (kSquares).
Parameters
batches Number of batches.
channels Number of channels.
input Input data [batches, channels, kSquares].
bias Channel bias.
output Output buffer [batches, channels].
Definition at line 40 of file se_unit.cc.
References bias, input, kSquares, and output.
Referenced by ApplySEUnit().
GzGetLine()
bool lczero::GzGetLine (gzFile file, std::string & line) inline
Definition at line 50 of file pgn.h.
Referenced by lczero::PgnReader::AddPgnFile().
Hash()
uint64_t lczero::Hash (uint64_t val) inline
Definition at line 35 of file hashcat.h.
Referenced by HashCat().
HashCat() [1/2]
uint64_t lczero::HashCat (std::initializer_list< uint64_t > args) inline
Definition at line 47 of file hashcat.h.
References HashCat().
HashCat() [2/2]
uint64_t lczero::HashCat (uint64_t hash, uint64_t x) inline
Definition at line 41 of file hashcat.h.
References Hash().
Referenced by lczero::Backend::ConfigurationHash(), lczero::ChessBoard::Hash(), lczero::Position::Hash(), HashCat(), lczero::PositionHistory::HashLast(), lczero::LruCache< K, V >::PairHash::operator()(), and TEST().
InitializeMagicBitboards()
void lczero::InitializeMagicBitboards ()
Definition at line 413 of file board.cc.
Referenced by main().
Is960CastlingFormat()
bool lczero::Is960CastlingFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format supports Chess960 castling rules.
Definition at line 121 of file encoder.cc.
References input_format.
Referenced by lczero::V6TrainingDataArray::Add().
IsCanonicalArmageddonFormat()
bool lczero::IsCanonicalArmageddonFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format is for Armageddon games.
Definition at line 109 of file encoder.cc.
References input_format.
Referenced by EncodePositionForNN(), and PlanesFromTrainingData().
IsCanonicalFormat()
bool lczero::IsCanonicalFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format is one of the canonical formats.
Definition at line 105 of file encoder.cc.
References input_format.
Referenced by lczero::V6TrainingDataArray::Add(), EncodePositionForNN(), PlanesFromTrainingData(), PopulateBoard(), TransformForPosition(), and lczero::V6TrainingDataArray::Write().
IsHectopliesFormat()
bool lczero::IsHectopliesFormat (pblczero::NetworkFormat::InputFormat input_format)
Checks if the input format uses hectoplies (100 half-moves) for time encoding.
Definition at line 117 of file encoder.cc.
References input_format.
Referenced by EncodePositionForNN(), PlanesFromTrainingData(), and PopulateBoard().
LayerNorm2DWithSkipConnection()
void lczero::LayerNorm2DWithSkipConnection (const size_t batch_size, const size_t channels, float * data, const float alpha, const float * skip, const float * gammas, const float * betas, float epsilon)
Performs layer normalization with an optional skip connection for 2D data.
Computes: data = LayerNorm(alpha * data + skip).
Parameters
batch_size Batch size.
channels Number of channels.
data Pointer to input/output data.
alpha Scaling factor for data.
skip Pointer to skip connection data (optional).
gammas Gamma parameters for LayerNorm.
betas Beta parameters for LayerNorm.
epsilon Epsilon for numerical stability.
Definition at line 40 of file encoder.h.
References data.
LeftTrim()
std::string lczero::LeftTrim (std::string str)
Definition at line 75 of file string.cc.
Referenced by Trim().
LoadWeights()
std::optional< WeightsFile > lczero::LoadWeights (std::string_view location)
Definition at line 214 of file loader.cc.
References lczero::CommandLine::BinaryName(), CERR, DiscoverWeightsFile(), lczero::SharedBackendParams::kAutoDiscover, lczero::SharedBackendParams::kEmbed, and LoadWeightsFromFile().
Referenced by lczero::NetworkAsBackendFactory::Create(), and lczero::NetworkFactory::LoadNetwork().
LoadWeightsFromFile()
WeightsFile lczero::LoadWeightsFromFile (const std::string & filename)
Definition at line 195 of file loader.cc.
Referenced by ConvertLeelaToOnnx(), DescribeNetworkCmd(), and LoadWeights().
MakeCudaNetwork()
template<typename DataType > std::unique_ptr< Network > lczero::MakeCudaNetwork (const std::optional< WeightsFile > & w, const OptionsDict & options)
Definition at line 1280 of file network_cuda.cc.
MakeCudaNetworkAuto()
std::unique_ptr< Network > lczero::MakeCudaNetworkAuto (const std::optional< WeightsFile > & weights, const OptionsDict & options)
Definition at line 1350 of file network_cuda.cc.
References CERR, and lczero::OptionsDict::GetOrDefault().
MakeCudnnNetwork()
template<typename DataType > std::unique_ptr< Network > lczero::MakeCudnnNetwork (const std::optional< WeightsFile > & w, const OptionsDict & options)
Definition at line 1214 of file network_cudnn.cc.
References CERR, lczero::NetworkFactory::Create(), and lczero::NetworkFactory::Get().
MakeCudnnNetworkAuto()
std::unique_ptr< Network > lczero::MakeCudnnNetworkAuto (const std::optional< WeightsFile > & weights, const OptionsDict & options)
Definition at line 1283 of file network_cudnn.cc.
References CERR, and lczero::OptionsDict::GetOrDefault().
MakeKeyValue()
PjrtKeyValue lczero::MakeKeyValue (const PJRT_NamedValue * kv)
Definition at line 84 of file pjrt.cc.
References result.
Referenced by lczero::Pjrt::GetAttributes().
MakeOnednnNetwork()
std::unique_ptr< Network > lczero::MakeOnednnNetwork (const std::optional< WeightsFile > & w, const OptionsDict & options)
Definition at line 881 of file network_onednn.cc.
MakeRandomNetwork()
std::unique_ptr< Network > lczero::MakeRandomNetwork (const std::optional< WeightsFile > & , const OptionsDict & options)
Factory function to create a RandomNetwork instance.
Definition at line 148 of file network_random.cc.
MakeSyclNetwork()
template<typename DataType > std::unique_ptr< Network > lczero::MakeSyclNetwork (const std::optional< WeightsFile > & w, const OptionsDict & options)
Definition at line 1090 of file network_sycl.cc.dp.cpp.
MakeSyclNetworkAuto()
std::unique_ptr< Network > lczero::MakeSyclNetworkAuto (const std::optional< WeightsFile > & weights, const OptionsDict & options)
Definition at line 1160 of file network_sycl.cc.dp.cpp.
References CERR, and lczero::OptionsDict::GetOrDefault().
MakeTrivialNetwork()
std::unique_ptr< Network > lczero::MakeTrivialNetwork (const std::optional< WeightsFile > & , const OptionsDict & options)
Factory function to create a TrivialNetwork instance.
Definition at line 495 of file network_trivial.cc.
mish()
static float lczero::mish (float val) inline static
Definition at line 51 of file activation.cc.
References d.
Referenced by Activate(), Activate(), Activate(), BiasActivate(), and BiasResidual().
MoveFromNNIndex()
Move lczero::MoveFromNNIndex (int idx, int transform)
Converts a neural network output index back to a move.
Parameters
idx The index in the policy vector.
transform The transformation applied to the position.
Returns
The decoded Move.
Definition at line 621 of file encoder.cc.
References FlipTransform, idx, MirrorTransform, lczero::PieceType::Parse(), lczero::Square::Parse(), transform, TransposeTransform, lczero::Move::White(), and lczero::Move::WhitePromotion().
MoveToNNIndex()
uint16_t lczero::MoveToNNIndex (Move move, int transform)
Converts a move to a neural network output index.
Parameters
move The move to convert.
transform The transformation applied to the position.
Returns
The index in the policy vector.
Definition at line 611 of file encoder.cc.
References lczero::Move::from(), lczero::Move::is_promotion(), lczero::Move::promotion(), lczero::Move::to(), transform, lczero::Move::White(), and lczero::Move::WhitePromotion().
Referenced by lczero::V6TrainingDataArray::Add(), lczero::classic::Search::GetVerboseStats(), lczero::dag_classic::Search::GetVerboseStats(), and lczero::python::GameState::policy_indices().
OnnxTensorToXlaTensor()
std::unique_ptr< XlaTensor > lczero::OnnxTensorToXlaTensor (const pblczero::TensorProto & onnx_tensor)
Definition at line 1740 of file onnx2hlo.cc.
operator-() [1/3]
GameResult lczero::operator- (const GameResult & res)
Definition at line 69 of file position.cc.
References BLACK_WON, and WHITE_WON.
operator-() [2/3]
int lczero::operator- (File a, File b) inline
Definition at line 269 of file types.h.
References lczero::File::idx.
operator-() [3/3]
int lczero::operator- (Rank a, Rank b) inline
Definition at line 270 of file types.h.
References lczero::Rank::idx.
ParseIntList()
std::vector< int > lczero::ParseIntList (const std::string & str)
Definition at line 67 of file string.cc.
References result, and StrSplit().
PlanesFromTrainingData()
InputPlanes lczero::PlanesFromTrainingData (const V6TrainingData & data)
Definition at line 32 of file reader.cc.
References data, FlipTransform, IsCanonicalArmageddonFormat(), IsCanonicalFormat(), IsHectopliesFormat(), MirrorTransform, result, ReverseBitsInBytes(), ReverseBytesInBytes(), transform, TransposeBitsInBytes(), and TransposeTransform.
PopulateBoard()
void lczero::PopulateBoard (pblczero::NetworkFormat::InputFormat input_format, InputPlanes planes, ChessBoard * board, int * rule50, int * gameply)
Reconstructs a ChessBoard object from input planes.
Parameters
input_format The format used in the input planes.
planes The input planes to decode.
board [out] The reconstructed board.
rule50 [out] Halfmove clock.
gameply [out] Fullmove number.
Definition at line 58 of file decoder.cc.
References lczero::ChessBoard::Castlings::as_string(), fen, lczero::File::FromIdx(), lczero::Rank::FromIdx(), GetLowestBit(), lczero::File::idx, input_format, IsCanonicalFormat(), IsHectopliesFormat(), kAuxPlaneBase, kFileA, kFileH, kPlanesPerBoard, kRank3, kRank6, lczero::ChessBoard::Castlings::Mirror(), lczero::ChessBoard::Castlings::our_kingside_rook, lczero::ChessBoard::Castlings::our_queenside_rook, lczero::ChessBoard::Castlings::set_they_can_00(), lczero::ChessBoard::Castlings::set_they_can_000(), lczero::ChessBoard::Castlings::set_we_can_00(), lczero::ChessBoard::Castlings::set_we_can_000(), lczero::ChessBoard::SetFromFen(), lczero::ChessBoard::Castlings::their_kingside_rook, lczero::ChessBoard::Castlings::their_queenside_rook, lczero::Square::ToString(), and value.
PositionToFen()
std::string lczero::PositionToFen (const Position & pos)
Definition at line 151 of file position.cc.
References BoardToFen(), lczero::Position::GetBoard(), lczero::Position::GetGamePly(), lczero::Position::GetRule50Ply(), lczero::Position::IsBlackToMove(), and result.
Referenced by lczero::Position::DebugString(), and TEST().
PrettyPrintHlo()
void lczero::PrettyPrintHlo (const pblczero::HloModuleProto & module, PrettyPrintHloOptions options, std::ostream & stream)
Definition at line 431 of file print_hlo.cc.
Referenced by ConvertLeelaToOnnx().
ReadFileToString()
std::string lczero::ReadFileToString (const std::string & filename)
Definition at line 36 of file files.cc.
References result.
Referenced by ConvertOnnxToLeela().
RescorerDeblunderSetup()
bool lczero::RescorerDeblunderSetup (float threshold, float width)
Definition at line 1429 of file rescorer.cc.
Referenced by RunRescorer().
RescorerGaviotaSetup()
bool lczero::RescorerGaviotaSetup (std::string dtmPaths)
Definition at line 1436 of file rescorer.cc.
References SEP_CHAR.
Referenced by RunRescorer().
RescorerPolicySubstitutionSetup()
bool lczero::RescorerPolicySubstitutionSetup (std::string policySubsDir)
Definition at line 1457 of file rescorer.cc.
References GetFileList().
Referenced by RunRescorer().
RescoreTrainingData()
std::vector< V6TrainingData > lczero::RescoreTrainingData (std::vector< V6TrainingData > fileContents, SyzygyTablebase * tablebase, float distTemp, float distOffset, float dtzBoost, int newInputFormat)
Definition at line 1420 of file rescorer.cc.
References data, and fileContents.
ReverseBitsInBytes()
uint64_t lczero::ReverseBitsInBytes (uint64_t v) inline
Definition at line 66 of file bititer.h.
Referenced by lczero::V6TrainingDataArray::Add(), EncodePositionForNN(), and PlanesFromTrainingData().
ReverseBytesInBytes()
uint64_t lczero::ReverseBytesInBytes (uint64_t v) inline
Definition at line 73 of file bititer.h.
Referenced by EncodePositionForNN(), lczero::BitBoard::Mirror(), and PlanesFromTrainingData().
RightTrim()
std::string lczero::RightTrim (std::string str)
Definition at line 82 of file string.cc.
Referenced by Trim().
RunEngine()
void lczero::RunEngine (SearchFactory * factory)
Definition at line 47 of file engine_loop.cc.
References lczero::OptionsParser::Add(), CERR, lczero::Logging::Get(), lczero::SearchFactory::GetName(), lczero::OptionsParser::GetOptionsDict(), lczero::ConfigFile::Init(), LOGFILE, lczero::SharedBackendParams::Populate(), lczero::Engine::PopulateOptions(), lczero::ConfigFile::PopulateOptions(), lczero::SearchFactory::PopulateParams(), lczero::StringUciResponder::PopulateParams(), lczero::OptionsParser::ProcessAllFlags(), lczero::UciLoop::ProcessLine(), lczero::StringUciResponder::SendRawResponse(), and lczero::Logging::SetFilename().
Referenced by ChooseAndRunEngine().
RunRescorer()
void lczero::RunRescorer ()
Definition at line 1275 of file rescorer.cc.
References lczero::OptionsParser::Add(), lczero::OptionsDict::Get(), GetFileList(), lczero::OptionsParser::GetOptionsDict(), lczero::SyzygyTablebase::init(), lczero::OptionsDict::IsDefault(), lczero::SyzygyTablebase::max_cardinality(), offset, lczero::OptionsParser::ProcessAllFlags(), RescorerDeblunderSetup(), RescorerGaviotaSetup(), RescorerPolicySubstitutionSetup(), and threads_.
selu()
static float lczero::selu (float val) inline static
Definition at line 62 of file activation.cc.
Referenced by Activate(), and Activate().
ShowAllNetworkInfo()
void lczero::ShowAllNetworkInfo (const pblczero::Net & weights)
Definition at line 299 of file describenet.cc.
References ShowNetworkFormatInfo(), ShowNetworkGenericInfo(), ShowNetworkOnnxInfo(), ShowNetworkTrainingInfo(), and ShowNetworkWeightsInfo().
Referenced by DescribeNetworkCmd().
ShowNetworkFormatInfo()
void lczero::ShowNetworkFormatInfo (const pblczero::Net & weights)
Definition at line 67 of file describenet.cc.
References COUT.
Referenced by ConvertLeelaToOnnx(), ConvertOnnxToLeela(), and ShowAllNetworkInfo().
ShowNetworkGenericInfo()
void lczero::ShowNetworkGenericInfo (const pblczero::Net & weights)
Definition at line 59 of file describenet.cc.
References COUT.
Referenced by ShowAllNetworkInfo().
ShowNetworkOnnxInfo()
void lczero::ShowNetworkOnnxInfo (const pblczero::Net & weights, bool show_onnx_internals)
Definition at line 226 of file describenet.cc.
References COUT, input, name, and output.
Referenced by ConvertLeelaToOnnx(), ConvertOnnxToLeela(), and ShowAllNetworkInfo().
ShowNetworkTrainingInfo()
void lczero::ShowNetworkTrainingInfo (const pblczero::Net & weights)
Definition at line 120 of file describenet.cc.
References COUT.
Referenced by ShowAllNetworkInfo().
ShowNetworkWeightsBodyInfo()
void lczero::ShowNetworkWeightsBodyInfo (const pblczero::Net & weights)
Definition at line 146 of file describenet.cc.
References COUT.
Referenced by ShowNetworkWeightsInfo().
ShowNetworkWeightsInfo()
void lczero::ShowNetworkWeightsInfo (const pblczero::Net & weights)
Definition at line 212 of file describenet.cc.
References COUT, ShowNetworkWeightsBodyInfo(), and ShowNetworkWeightsPolicyInfo().
Referenced by ConvertLeelaToOnnx(), and ShowAllNetworkInfo().
ShowNetworkWeightsPolicyInfo()
void lczero::ShowNetworkWeightsPolicyInfo (const pblczero::Net & weights)
Definition at line 169 of file describenet.cc.
References COUT.
Referenced by ShowNetworkWeightsInfo().
SoftmaxActivation()
void lczero::SoftmaxActivation (const size_t size, const float * input, float * output)
Computes Softmax activation for a vector.
Parameters
size The size of the input vector.
input Pointer to input data.
output Pointer to store the output.
Definition at line 37 of file activation.cc.
References input, and output.
SpinloopPause()
static void lczero::SpinloopPause () inline static
Definition at line 127 of file mutex.h.
Referenced by lczero::ExponentialBackoffSpinHelper::Backoff(), lczero::classic::SearchWorker::RunTasks(), lczero::ExponentialBackoffSpinHelper::Wait(), and lczero::classic::SearchWorker::WaitForTasks().
SteadyClockToSystemClock()
std::chrono::time_point< std::chrono::system_clock > lczero::SteadyClockToSystemClock (std::chrono::time_point< std::chrono::steady_clock > time)
Definition at line 96 of file logging.cc.
StringsEqualIgnoreCase()
bool lczero::StringsEqualIgnoreCase (const std::string & a, const std::string & b)
Definition at line 93 of file string.cc.
Referenced by lczero::OptionsParser::FindOptionByUciName(), and StringToXlaType().
StringToXlaType()
pblczero::XlaShapeProto::Type lczero::StringToXlaType (const std::string & type)
Definition at line 158 of file xla_tensor.cc.
References StringsEqualIgnoreCase(), and type.
StrJoin()
std::string lczero::StrJoin (const std::vector< std::string > & strings, const std::string & delim)
Definition at line 37 of file string.cc.
Referenced by lczero::OptionsParser::ShowHelp().
StrSplit()
std::vector< std::string > lczero::StrSplit (const std::string & str, const std::string & delim)
Definition at line 55 of file string.cc.
References result.
Referenced by FlowText(), lczero::OptionsParser::GetMutableOptions(), lczero::OptionsParser::GetOptionsDict(), GetSystemConfigDirectoryList(), GetSystemDataDirectoryList(), and ParseIntList().
StrSplitAtWhitespace()
std::vector< std::string > lczero::StrSplitAtWhitespace (const std::string & str)
Definition at line 47 of file string.cc.
References result.
Referenced by lczero::UciLoop::DispatchCommand(), and lczero::Benchmark::Run().
TEST() [1/51]
lczero::TEST (ChessBoard , FRC)
Definition at line 2128 of file board_test.cc.
References lczero::ChessBoard::DebugString(), and lczero::ChessBoard::SetFromFen().
TEST() [2/51]
lczero::TEST (ChessBoard , HasMatingMaterialBareKings)
Definition at line 2147 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), and lczero::ChessBoard::SetFromFen().
TEST() [3/51]
lczero::TEST (ChessBoard , HasMatingMaterialBishopAndKnight)
Definition at line 2179 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), and lczero::ChessBoard::SetFromFen().
TEST() [4/51]
lczero::TEST (ChessBoard , HasMatingMaterialMultipleBishopsNotSameColor)
Definition at line 2199 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), and lczero::ChessBoard::SetFromFen().
TEST() [5/51]
lczero::TEST (ChessBoard , HasMatingMaterialMultipleBishopsSameColor)
Definition at line 2187 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), and lczero::ChessBoard::SetFromFen().
TEST() [6/51]
lczero::TEST (ChessBoard , HasMatingMaterialSingleMajorPieceOrPawn)
Definition at line 2161 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), and lczero::ChessBoard::SetFromFen().
TEST() [7/51]
lczero::TEST (ChessBoard , HasMatingMaterialSingleMinorPiece)
Definition at line 2153 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), and lczero::ChessBoard::SetFromFen().
TEST() [8/51]
lczero::TEST (ChessBoard , HasMatingMaterialStartPosition)
Definition at line 2141 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), lczero::ChessBoard::kStartposFen, and lczero::ChessBoard::SetFromFen().
TEST() [9/51]
lczero::TEST (ChessBoard , HasMatingMaterialTwoKnights)
Definition at line 2171 of file board_test.cc.
References lczero::ChessBoard::HasMatingMaterial(), and lczero::ChessBoard::SetFromFen().
TEST() [10/51]
lczero::TEST (ChessBoard , IllegalFirstRankPawns)
Definition at line 30 of file board_test.cc.
References lczero::ChessBoard::SetFromFen().
TEST() [11/51]
lczero::TEST (ChessBoard , InvalidEnPassantFromKnightPromotion)
Definition at line 2232 of file board_test.cc.
References lczero::ChessBoard::ApplyMove(), lczero::BitBoard::empty(), lczero::ChessBoard::en_passant(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
TEST() [12/51]
lczero::TEST (ChessBoard , InvalidFEN)
Definition at line 2223 of file board_test.cc.
TEST() [13/51]
lczero::TEST (ChessBoard , MoveGenKiwipete)
Definition at line 127 of file board_test.cc.
References lczero::ChessBoard::SetFromFen().
TEST() [14/51]
lczero::TEST (ChessBoard , MoveGenPosition3)
Definition at line 139 of file board_test.cc.
References lczero::ChessBoard::SetFromFen().
TEST() [15/51]
lczero::TEST (ChessBoard , MoveGenPosition4)
Definition at line 151 of file board_test.cc.
References lczero::ChessBoard::SetFromFen().
TEST() [16/51]
lczero::TEST (ChessBoard , MoveGenPosition5)
Definition at line 163 of file board_test.cc.
References lczero::ChessBoard::SetFromFen().
TEST() [17/51]
lczero::TEST (ChessBoard , MoveGenPosition6)
Definition at line 174 of file board_test.cc.
References lczero::ChessBoard::SetFromFen().
TEST() [18/51]
lczero::TEST (ChessBoard , PartialFen)
Definition at line 46 of file board_test.cc.
References lczero::ChessBoard::GeneratePseudolegalMoves(), moves, and lczero::ChessBoard::SetFromFen().
TEST() [19/51]
lczero::TEST (ChessBoard , PartialFenWithSpaces)
Definition at line 58 of file board_test.cc.
References lczero::ChessBoard::GeneratePseudolegalMoves(), moves, and lczero::ChessBoard::SetFromFen().
TEST() [20/51]
lczero::TEST (ChessBoard , PseudolegalMovesStartingPos)
Definition at line 37 of file board_test.cc.
References lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::ChessBoard::kStartposFen, lczero::ChessBoard::Mirror(), moves, and lczero::ChessBoard::SetFromFen().
TEST() [21/51]
lczero::TEST (ChessBoard , QueenMoveFromEnPassantFlagBug)
Definition at line 2240 of file board_test.cc.
References lczero::ChessBoard::ApplyMove(), lczero::ChessBoard::GenerateLegalMoves(), legal_moves, m, lczero::ChessBoard::Mirror(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
TEST() [22/51]
lczero::TEST (EncodePositionForNN , EncodeEarlyGameFlipFormat3)
Definition at line 490 of file encoder_test.cc.
References lczero::PositionHistory::Append(), EncodePositionForNN(), FlipTransform, lczero::Position::GetBoard(), lczero::ChessBoard::kStartposFen, lczero::PositionHistory::Last(), lczero::InputPlane::mask, NO, NoTransform, lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), transform, and lczero::InputPlane::value.
TEST() [23/51]
lczero::TEST (EncodePositionForNN , EncodeEndGameFormat1)
Definition at line 357 of file encoder_test.cc.
References EncodePositionForNN(), lczero::InputPlane::mask, NO, NoTransform, lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), transform, and lczero::InputPlane::value.
TEST() [24/51]
lczero::TEST (EncodePositionForNN , EncodeEndGameFormat3)
Definition at line 378 of file encoder_test.cc.
References EncodePositionForNN(), FlipTransform, lczero::InputPlane::mask, MirrorTransform, NO, lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), transform, TransposeTransform, and lczero::InputPlane::value.
TEST() [25/51]
lczero::TEST (EncodePositionForNN , EncodeEndGameKingOnDiagonalFormat3)
Definition at line 399 of file encoder_test.cc.
References EncodePositionForNN(), FlipTransform, lczero::InputPlane::mask, MirrorTransform, NO, lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), transform, and lczero::InputPlane::value.
TEST() [26/51]
lczero::TEST (EncodePositionForNN , EncodeEnpassantFormat3)
Definition at line 423 of file encoder_test.cc.
References lczero::PositionHistory::Append(), EncodePositionForNN(), lczero::Position::GetBoard(), lczero::ChessBoard::kStartposFen, lczero::PositionHistory::Last(), lczero::InputPlane::mask, NO, lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [27/51]
lczero::TEST (EncodePositionForNN , EncodeFiftyMoveCounter)
Definition at line 286 of file encoder_test.cc.
References lczero::PositionHistory::Append(), EncodePositionForNN(), lczero::Position::GetBoard(), kAllSquaresMask, lczero::ChessBoard::kStartposFen, lczero::PositionHistory::Last(), lczero::InputPlane::mask, NO, lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), and lczero::InputPlane::value.
TEST() [28/51]
lczero::TEST (EncodePositionForNN , EncodeFiftyMoveCounterFormat3)
Definition at line 322 of file encoder_test.cc.
References lczero::PositionHistory::Append(), EncodePositionForNN(), lczero::Position::GetBoard(), kAllSquaresMask, lczero::ChessBoard::kStartposFen, lczero::PositionHistory::Last(), lczero::InputPlane::mask, NO, lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), and lczero::InputPlane::value.
TEST() [29/51]
lczero::TEST (EncodePositionForNN , EncodeStartPosition)
Definition at line 27 of file encoder_test.cc.
References EncodePositionForNN(), kAllSquaresMask, lczero::ChessBoard::kStartposFen, lczero::InputPlane::mask, NO, lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), and lczero::InputPlane::value.
TEST() [30/51]
lczero::TEST (EncodePositionForNN , EncodeStartPositionFormat2)
Definition at line 108 of file encoder_test.cc.
References EncodePositionForNN(), kAllSquaresMask, lczero::ChessBoard::kStartposFen, lczero::InputPlane::mask, NO, lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), and lczero::InputPlane::value.
TEST() [31/51]
lczero::TEST (EncodePositionForNN , EncodeStartPositionFormat3)
Definition at line 197 of file encoder_test.cc.
References EncodePositionForNN(), kAllSquaresMask, lczero::ChessBoard::kStartposFen, lczero::InputPlane::mask, NO, lczero::PositionHistory::Reset(), lczero::ChessBoard::SetFromFen(), and lczero::InputPlane::value.
TEST() [32/51]
lczero::TEST (FP16 , TestNormalConversion)
Definition at line 49 of file fp16_utils_test.cc.
References FP16Equal(), FP16toFP32(), and FP32toFP16().
TEST() [33/51]
lczero::TEST (HashCat , TestCollision)
Definition at line 33 of file hashcat_test.cc.
References HashCat().
TEST() [34/51]
lczero::TEST (OptionsParser , BoolOptionsCheckValueConstraints)
Definition at line 60 of file optionsparser_test.cc.
References lczero::OptionsParser::Add(), and lczero::OptionsParser::SetUciOption().
TEST() [35/51]
lczero::TEST (OptionsParser , CheckInvalidOption)
Definition at line 25 of file optionsparser_test.cc.
References lczero::OptionsParser::Add(), and lczero::OptionsParser::SetUciOption().
TEST() [36/51]
lczero::TEST (OptionsParser , ChoiceOptionCheckValueConstraints)
Definition at line 70 of file optionsparser_test.cc.
References lczero::OptionsParser::Add(), and lczero::OptionsParser::SetUciOption().
TEST() [37/51]
lczero::TEST (OptionsParser , FloatOptionCheckValueConstraints)
Definition at line 48 of file optionsparser_test.cc.
References lczero::OptionsParser::Add(), and lczero::OptionsParser::SetUciOption().
TEST() [38/51]
lczero::TEST (OptionsParser , IntOptionCheckValueConstraints)
Definition at line 36 of file optionsparser_test.cc.
References lczero::OptionsParser::Add(), and lczero::OptionsParser::SetUciOption().
TEST() [39/51]
lczero::TEST (Position , SetFenGetFen)
Definition at line 29 of file position_test.cc.
References lczero::ChessBoard::Clear(), lczero::ChessBoard::flipped(), lczero::PositionHistory::Last(), PositionToFen(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [40/51]
lczero::TEST (PositionHistory , ComputeLastMoveRepetitionsWithLegalEnPassant)
Definition at line 76 of file position_test.cc.
References lczero::PositionHistory::Append(), lczero::Position::GetBoard(), lczero::PositionHistory::GetLength(), lczero::PositionHistory::GetPositionAt(), lczero::Position::GetRepetitions(), lczero::PositionHistory::Last(), lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [41/51]
lczero::TEST (PositionHistory , ComputeLastMoveRepetitionsWithoutLegalEnPassant)
Definition at line 60 of file position_test.cc.
References lczero::PositionHistory::Append(), lczero::Position::GetBoard(), lczero::PositionHistory::GetLength(), lczero::PositionHistory::GetPositionAt(), lczero::Position::GetRepetitions(), lczero::PositionHistory::Last(), lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [42/51]
lczero::TEST (PositionHistory , DidRepeatSinceLastZeroingMoveBefore)
Definition at line 106 of file position_test.cc.
References lczero::PositionHistory::Append(), lczero::PositionHistory::DidRepeatSinceLastZeroingMove(), lczero::Position::GetBoard(), lczero::PositionHistory::Last(), lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [43/51]
lczero::TEST (PositionHistory , DidRepeatSinceLastZeroingMoveBeforeZero)
Definition at line 137 of file position_test.cc.
References lczero::PositionHistory::Append(), lczero::PositionHistory::DidRepeatSinceLastZeroingMove(), lczero::Position::GetBoard(), lczero::PositionHistory::Last(), lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [44/51]
lczero::TEST (PositionHistory , DidRepeatSinceLastZeroingMoveCurent)
Definition at line 92 of file position_test.cc.
References lczero::PositionHistory::Append(), lczero::PositionHistory::DidRepeatSinceLastZeroingMove(), lczero::Position::GetBoard(), lczero::PositionHistory::Last(), lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [45/51]
lczero::TEST (PositionHistory , DidRepeatSinceLastZeroingMoveNeverRepeated)
Definition at line 154 of file position_test.cc.
References lczero::PositionHistory::Append(), lczero::PositionHistory::DidRepeatSinceLastZeroingMove(), lczero::Position::GetBoard(), lczero::PositionHistory::Last(), lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [46/51]
lczero::TEST (PositionHistory , DidRepeatSinceLastZeroingMoveOlder)
Definition at line 121 of file position_test.cc.
References lczero::PositionHistory::Append(), lczero::PositionHistory::DidRepeatSinceLastZeroingMove(), lczero::Position::GetBoard(), lczero::PositionHistory::Last(), lczero::ChessBoard::ParseMove(), lczero::PositionHistory::Reset(), and lczero::ChessBoard::SetFromFen().
TEST() [47/51]
lczero::TEST (Syzygy , Root3PieceProbes)
Definition at line 134 of file syzygy_test.cc.
References lczero::SyzygyTablebase::init(), kPaths, lczero::SyzygyTablebase::max_cardinality(), and TestValidRootExpectation().
TEST() [48/51]
lczero::TEST (Syzygy , Root5PieceProbes)
Definition at line 226 of file syzygy_test.cc.
References lczero::SyzygyTablebase::init(), kPaths, lczero::SyzygyTablebase::max_cardinality(), and TestValidRootExpectation().
TEST() [49/51]
lczero::TEST (Syzygy , Simple3PieceProbes)
Definition at line 94 of file syzygy_test.cc.
References lczero::SyzygyTablebase::init(), kPaths, lczero::SyzygyTablebase::max_cardinality(), TestValidExpectation(), WDL_DRAW, WDL_LOSS, and WDL_WIN.
TEST() [50/51]
lczero::TEST (Syzygy , Simple4PieceProbes)
Definition at line 153 of file syzygy_test.cc.
References lczero::SyzygyTablebase::init(), kPaths, lczero::SyzygyTablebase::max_cardinality(), TestValidExpectation(), WDL_LOSS, and WDL_WIN.
TEST() [51/51]
lczero::TEST (Syzygy , Simple5PieceProbes)
Definition at line 176 of file syzygy_test.cc.
References lczero::SyzygyTablebase::init(), kPaths, lczero::SyzygyTablebase::max_cardinality(), TestValidExpectation(), WDL_BLESSED_LOSS, WDL_CURSED_WIN, WDL_DRAW, WDL_LOSS, and WDL_WIN.
TestValidExpectation()
void lczero::TestValidExpectation (SyzygyTablebase * tablebase, const std::string & fen, WDLScore expected, int expected_dtz)
Definition at line 79 of file syzygy_test.cc.
References FAIL, fen, lczero::PositionHistory::Last(), moves, lczero::SyzygyTablebase::probe_dtz(), lczero::SyzygyTablebase::probe_wdl(), lczero::PositionHistory::Reset(), result, and lczero::ChessBoard::SetFromFen().
Referenced by TEST(), TEST(), and TEST().
TestValidRootExpectation()
void lczero::TestValidRootExpectation (SyzygyTablebase * tablebase, const std::string & fen, const std::vector< std::string > & valid_moves, const std::vector< std::string > & invalid_moves, const std::vector< std::string > & invalid_dtz_only = {}, bool has_repeated = false)
Definition at line 39 of file syzygy_test.cc.
Referenced by TEST(), and TEST().
TransformForPosition()
int lczero::TransformForPosition (pblczero::NetworkFormat::InputFormat input_format, const PositionHistory & history)
Determines the required transformation for a position based on history.
Used to normalize or augment data for the neural network.
Parameters
input_format The expected input format of the network.
history The history of positions.
Returns
An integer representing the transformation.
Definition at line 125 of file encoder.cc.
References lczero::Position::GetBoard(), input_format, IsCanonicalFormat(), and lczero::PositionHistory::Last().
TransposeBitsInBytes()
uint64_t lczero::TransposeBitsInBytes (uint64_t v) inline
Definition at line 81 of file bititer.h.
Referenced by EncodePositionForNN(), and PlanesFromTrainingData().
TransposeTensor()
template<class T > void lczero::TransposeTensor (const std::vector< int > & dims, std::vector< int > order, const std::vector< T > from, T * to)
Definition at line 41 of file transpose.h.
Trim()
std::string lczero::Trim (std::string str)
Definition at line 89 of file string.cc.
References LeftTrim(), and RightTrim().
Referenced by lczero::ConfigFile::ParseFile().
WinogradFilterTransformF()
std::vector< float > lczero::WinogradFilterTransformF (const std::vector< float > & f, const size_t outputs, const size_t channels)
Create the filter transform matrix F(2x2, 3x3).
Computes transpose(G.dot(f).dot(G.transpose())). U matrix is transposed for better memory layout in SGEMM.
Parameters
f Filter weights.
outputs Number of output channels.
channels Number of input channels.
Returns
The transformed filter matrix U.
Definition at line 54 of file winograd_filter.cc.
WinogradFilterZeropadU()
std::vector< float > lczero::WinogradFilterZeropadU (const std::vector< float > & U, const size_t outputs, const size_t channels, const size_t outputs_pad, const size_t channels_pad)
Create the zero-padded U matrix for 3x3 Winograd convolution.
Parameters
U Input U matrix.
outputs Number of output channels.
channels Number of input channels.
outputs_pad Padded number of output channels.
channels_pad Padded number of input channels.
Returns
The zero-padded U matrix.
Definition at line 31 of file winograd_filter.cc.
WriteStringToFile()
void lczero::WriteStringToFile (const std::string & filename, const std::string_view content)
Definition at line 62 of file files.cc.
Referenced by ConvertLeelaToOnnx().
WriteStringToGzFile()
void lczero::WriteStringToGzFile (const std::string & filename, std::string_view content)
Definition at line 72 of file files.cc.
Referenced by ConvertOnnxToLeela().
Variable Documentation
ConvGuid
constexpr GUID lczero::ConvGuid constexpr
Initial value:
= {0x17804d6b,
                           0xebfe,
                           0x426f,
                           {0x88, 0xfc, 0xfe, 0xa7, 0x2e, 0x3f, 0x33, 0x56}}
Definition at line 95 of file MetaCommand.h.
Referenced by lczero::dx_backend::ConvMetaCommand::ConvMetaCommand().
GemmGuid
constexpr GUID lczero::GemmGuid constexpr
Initial value:
= {0x1e52ebab,
                           0x25ba,
                           0x463a,
                           {0xa2, 0x85, 0x0a, 0x78, 0x8e, 0xef, 0x5d, 0x01}}
Definition at line 49 of file MetaCommand.h.
Referenced by lczero::dx_backend::GemmMetaCommand::GemmMetaCommand().
kAllSquaresMask
auto lczero::kAllSquaresMask = std::numeric_limits<std::uint64_t>::max()
Definition at line 25 of file encoder_test.cc.
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().
kAttnPolicyMap
const short lczero::kAttnPolicyMap[]
Definition at line 24 of file attention_policy_map.h.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), lczero::OnednnNetwork::forwardEval(), and lczero::SyclNetwork< DataType >::SyclNetwork().
kAuxPlaneBase
constexpr int lczero::kAuxPlaneBase = kPlanesPerBoard * kMoveHistory constexpr
Definition at line 40 of file encoder.h.
Referenced by EncodePositionForNN(), and PopulateBoard().
kBishop
constexpr PieceType lczero::kBishop = PieceType::FromIdx(3)
Definition at line 55 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), DecodeMoveFromInput(), lczero::PieceType::Parse(), lczero::PgnReader::PieceToPieceType(), and lczero::ChessBoard::PutPiece().
kConvPolicyMap
const short lczero::kConvPolicyMap[]
Definition at line 24 of file policy_map.h.
Referenced by lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), lczero::dx_backend::DxNetwork::DxNetwork(), lczero::OnednnNetwork::forwardEval(), and lczero::SyclNetwork< DataType >::SyclNetwork().
kFileA
constexpr File lczero::kFileA = File::FromIdx(0) constexpr
Definition at line 80 of file types.h.
Referenced by lczero::ChessBoard::Castlings::as_string(), BoardToFen(), lczero::ChessBoard::ParseMove(), PopulateBoard(), and lczero::ChessBoard::SetFromFen().
kFileB
constexpr File lczero::kFileB = File::FromIdx(1)
Definition at line 80 of file types.h.
kFileC
constexpr File lczero::kFileC = File::FromIdx(2)
Definition at line 81 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), and lczero::ChessBoard::GeneratePseudolegalMoves().
kFileD
constexpr File lczero::kFileD = File::FromIdx(3)
Definition at line 81 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), and lczero::ChessBoard::GeneratePseudolegalMoves().
kFileE
constexpr File lczero::kFileE = File::FromIdx(4)
Definition at line 82 of file types.h.
kFileF
constexpr File lczero::kFileF = File::FromIdx(5)
Definition at line 82 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), and lczero::ChessBoard::GeneratePseudolegalMoves().
kFileG
constexpr File lczero::kFileG = File::FromIdx(6)
Definition at line 83 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), and lczero::ChessBoard::GeneratePseudolegalMoves().
kFileH
constexpr File lczero::kFileH = File::FromIdx(7)
Definition at line 83 of file types.h.
Referenced by lczero::ChessBoard::Castlings::as_string(), BoardToFen(), lczero::ChessBoard::ParseMove(), PopulateBoard(), and lczero::ChessBoard::SetFromFen().
kInputPlanes
const int lczero::kInputPlanes = 112
Definition at line 38 of file network.h.
Referenced by lczero::CudaNetworkComputation< DataType >::AddInput(), lczero::CudnnNetworkComputation< DataType >::AddInput(), lczero::dx_backend::DxNetworkComputation::AddInput(), lczero::OnednnNetworkComputation::AddInput(), lczero::onnx::OnnxComputation< DataType >::AddInput(), lczero::SyclNetworkComputation< DataType >::AddInput(), lczero::onnx::OnnxComputation< DataType >::ComputeBlocking(), lczero::CudaNetwork< DataType >::CudaNetwork(), lczero::CudnnNetwork< DataType >::CudnnNetwork(), lczero::dx_backend::DxNetwork::DxNetwork(), lczero::dx_backend::DxNetwork::Eval(), lczero::cudnn_backend::AttentionBody< DataType >::Eval(), lczero::sycldnn_backend::AttentionBody< DataType >::Eval(), lczero::dx_backend::ShaderWrapper::ExpandPlanes(), lczero::sycldnn_backend::expandPlanes_kernel_Fp16_NHWC(), lczero::SyclNetwork< DataType >::forwardEval(), lczero::OnednnNetwork::forwardEval(), lczero::CudaNetwork< DataType >::forwardEval(), lczero::CudnnNetwork< DataType >::forwardEval(), lczero::InputsOutputs::InputsOutputs(), lczero::sycldnn_backend::InputsOutputs::InputsOutputs(), lczero::onnx::InputsOutputs::InputsOutputs(), lczero::cudnn_backend::InputsOutputs< DataType >::InputsOutputs(), lczero::dx_backend::InputsOutputsDx::InputsOutputsDx(), lczero::OnednnNetwork::OnednnNetwork(), lczero::onnx::OnnxComputation< DataType >::PrepareInputs(), lczero::SyclNetwork< DataType >::SyclNetwork(), lczero::CudaNetwork< DataType >::UploadInputs(), and lczero::CudnnNetwork< DataType >::UploadInputs().
kKing
constexpr PieceType lczero::kKing = PieceType::FromIdx(5)
Definition at line 57 of file types.h.
Referenced by lczero::PieceType::Parse(), and lczero::ChessBoard::PutPiece().
kKnight
constexpr PieceType lczero::kKnight = PieceType::FromIdx(0) constexpr
Definition at line 52 of file types.h.
Referenced by DecodeMoveFromInput(), lczero::PieceType::Parse(), lczero::ChessBoard::ParseMove(), and lczero::PgnReader::PieceToPieceType().
kMoveHistory
constexpr int lczero::kMoveHistory = 8 constexpr
Definition at line 38 of file encoder.h.
Referenced by EncodePositionForNN().
kNumOutputPolicy
constexpr int lczero::kNumOutputPolicy = 1858 static constexpr
Definition at line 48 of file network_onednn.cc.
kNumPosEncodingChannels
constexpr int lczero::kNumPosEncodingChannels = 64 constexpr
Definition at line 384 of file attention_policy_map.h.
Referenced by lczero::cudnn_backend::AttentionBody< DataType >::AttentionBody(), lczero::sycldnn_backend::AttentionBody< DataType >::AttentionBody(), lczero::cudnn_backend::AttentionBody< DataType >::Eval(), and lczero::sycldnn_backend::AttentionBody< DataType >::Eval().
kPaths
constexpr auto lczero::kPaths = "syzygy" constexpr
Definition at line 37 of file syzygy_test.cc.
Referenced by TEST(), TEST(), TEST(), TEST(), and TEST().
kPawn
constexpr PieceType lczero::kPawn = PieceType::FromIdx(4)
Definition at line 56 of file types.h.
Referenced by lczero::PieceType::Parse(), lczero::ChessBoard::PutPiece(), and lczero::ChessBoard::SetFromFen().
kPlanesPerBoard
constexpr int lczero::kPlanesPerBoard = 13 constexpr
Definition at line 39 of file encoder.h.
Referenced by EncodePositionForNN(), and PopulateBoard().
kPosEncoding
const float lczero::kPosEncoding[64][kNumPosEncodingChannels]
Definition at line 386 of file attention_policy_map.h.
Referenced by lczero::cudnn_backend::AttentionBody< DataType >::AttentionBody(), and lczero::sycldnn_backend::AttentionBody< DataType >::AttentionBody().
kQueen
constexpr PieceType lczero::kQueen = PieceType::FromIdx(1)
Definition at line 53 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), DecodeMoveFromInput(), lczero::PieceType::Parse(), lczero::PgnReader::PieceToPieceType(), and lczero::ChessBoard::PutPiece().
kRank1
constexpr Rank lczero::kRank1 = Rank::FromIdx(0) constexpr
Definition at line 103 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), BoardToFen(), EncodePositionForNN(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::ChessBoard::ParseMove(), lczero::PgnReader::SanToMove(), and lczero::ChessBoard::SetFromFen().
kRank2
constexpr Rank lczero::kRank2 = Rank::FromIdx(1)
Definition at line 103 of file types.h.
kRank3
constexpr Rank lczero::kRank3 = Rank::FromIdx(2)
Definition at line 104 of file types.h.
Referenced by BoardToFen(), lczero::ChessBoard::GeneratePseudolegalMoves(), PopulateBoard(), lczero::PgnReader::SanToMove(), and lczero::ChessBoard::SetFromFen().
kRank4
constexpr Rank lczero::kRank4 = Rank::FromIdx(3)
Definition at line 104 of file types.h.
Referenced by lczero::ChessBoard::GeneratePseudolegalMoves().
kRank5
constexpr Rank lczero::kRank5 = Rank::FromIdx(4)
Definition at line 105 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), and lczero::ChessBoard::SetFromFen().
kRank6
constexpr Rank lczero::kRank6 = Rank::FromIdx(5)
Definition at line 105 of file types.h.
Referenced by BoardToFen(), lczero::ChessBoard::GeneratePseudolegalMoves(), PopulateBoard(), lczero::PgnReader::SanToMove(), and lczero::ChessBoard::SetFromFen().
kRank7
constexpr Rank lczero::kRank7 = Rank::FromIdx(6)
Definition at line 106 of file types.h.
kRank8
constexpr Rank lczero::kRank8 = Rank::FromIdx(7)
Definition at line 106 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), BoardToFen(), DecodeMoveFromInput(), EncodePositionForNN(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
kRook
constexpr PieceType lczero::kRook = PieceType::FromIdx(2)
Definition at line 54 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), DecodeMoveFromInput(), lczero::PieceType::Parse(), lczero::PgnReader::PieceToPieceType(), and lczero::ChessBoard::PutPiece().
kSquareA1
constexpr Square lczero::kSquareA1 = Square(kFileA, kRank1) constexpr
Definition at line 133 of file types.h.
kSquareC1
constexpr Square lczero::kSquareC1 = Square(kFileC, kRank1)
Definition at line 134 of file types.h.
Referenced by lczero::ChessBoard::ParseMove().
kSquareE1
constexpr Square lczero::kSquareE1 = Square(kFileE, kRank1)
Definition at line 135 of file types.h.
Referenced by lczero::ChessBoard::ParseMove().
kSquareG1
constexpr Square lczero::kSquareG1 = Square(kFileG, kRank1)
Definition at line 136 of file types.h.
Referenced by lczero::ChessBoard::ParseMove().
kSquareH1
constexpr Square lczero::kSquareH1 = Square(kFileH, kRank1)
Definition at line 137 of file types.h.
PACKED_STRUCT
struct lczero::V6TrainingData lczero::PACKED_STRUCT