Leela Chess Zero: lczero::sycldnn_backend::DeviceCapabilities Struct Reference
lczero::sycldnn_backend::DeviceCapabilities Struct Reference
Helper class to query and cache device capabilities.
#include <sycl_common.h>
Classes
struct DeviceInfo
Static Public Member Functions
static int Init (const sycl::queue &queue)
static int GetMaxWorkgroupSize (const sycl::queue &queue)
static void ClearCache ()
Static Private Attributes
static std::unordered_map< sycl::device, DeviceInfo > device_cache_ {}
static std::mutex cache_mutex_ {}
Detailed Description
Helper class to query and cache device capabilities.
Definition at line 63 of file sycl_common.h.
Member Function Documentation
ClearCache()
static void lczero::sycldnn_backend::DeviceCapabilities::ClearCache () inline static
Definition at line 93 of file sycl_common.h.
References cache_mutex_, and device_cache_.
GetMaxWorkgroupSize()
static int lczero::sycldnn_backend::DeviceCapabilities::GetMaxWorkgroupSize (const sycl::queue & queue) inline static
Definition at line 81 of file sycl_common.h.
References device_cache_, and Init().
Referenced by lczero::sycldnn_backend::addBiasBatched(), lczero::sycldnn_backend::addBiasBatched(), lczero::sycldnn_backend::applyInputGating(), and lczero::sycldnn_backend::inputPreprocessForAttentionBody().
Init()
static int lczero::sycldnn_backend::DeviceCapabilities::Init (const sycl::queue & queue) inline static
Definition at line 69 of file sycl_common.h.
References cache_mutex_, device_cache_, and lczero::sycldnn_backend::DeviceCapabilities::DeviceInfo::max_workgroup_size.
Referenced by GetMaxWorkgroupSize(), and lczero::SyclNetwork< DataType >::SyclNetwork().
Member Data Documentation
cache_mutex_
std::mutex lczero::sycldnn_backend::DeviceCapabilities::cache_mutex_ {} inline static private
Definition at line 100 of file sycl_common.h.
Referenced by ClearCache(), and Init().
device_cache_
std::unordered_map< sycl::device, DeviceCapabilities::DeviceInfo > lczero::sycldnn_backend::DeviceCapabilities::device_cache_ {} inline static private
Definition at line 99 of file sycl_common.h.
Referenced by ClearCache(), GetMaxWorkgroupSize(), and Init().
The documentation for this struct was generated from the following file:
neural/backends/sycl/sycl_common.h