Leela Chess Zero: lczero::PieceType Struct Reference
lczero::PieceType Struct Reference
#include <types.h>
Public Member Functions
std::string ToString (bool uppercase=false) const
bool CanPromoteInto () const
bool IsValid () const
bool operator== (const PieceType &other) const =default
bool operator!= (const PieceType &other) const =default
Static Public Member Functions
static constexpr PieceType FromIdx (uint8_t idx)
static PieceType Parse (char c)
Public Attributes
uint8_t idx
Private Member Functions
constexpr PieceType (uint8_t idx)
Detailed Description
Definition at line 36 of file types.h.
Constructor & Destructor Documentation
PieceType()
constexpr lczero::PieceType::PieceType (uint8_t idx) inline explicit constexpr private
Definition at line 49 of file types.h.
Member Function Documentation
CanPromoteInto()
bool lczero::PieceType::CanPromoteInto () const inline
Definition at line 43 of file types.h.
References idx.
Referenced by lczero::ChessBoard::ParseMove().
FromIdx()
static constexpr PieceType lczero::PieceType::FromIdx (uint8_t idx) inline static constexpr
Definition at line 38 of file types.h.
References idx.
Referenced by lczero::Move::promotion().
IsValid()
bool lczero::PieceType::IsValid () const inline
Definition at line 44 of file types.h.
References idx.
Referenced by lczero::ChessBoard::SetFromFen().
operator!=()
bool lczero::PieceType::operator!= (const PieceType & other) const default
operator==()
bool lczero::PieceType::operator== (const PieceType & other) const default
Parse()
PieceType lczero::PieceType::Parse (char c) inline static
Definition at line 212 of file types.h.
References lczero::kBishop, lczero::kKing, lczero::kKnight, lczero::kPawn, lczero::kQueen, and lczero::kRook.
Referenced by lczero::MoveFromNNIndex(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
ToString()
std::string lczero::PieceType::ToString (bool uppercase = false) const inline
Definition at line 40 of file types.h.
References idx.
Referenced by lczero::Move::ToString().
Member Data Documentation
idx
uint8_t lczero::PieceType::idx
Definition at line 37 of file types.h.
Referenced by lczero::ChessBoard::ApplyMove(), CanPromoteInto(), FromIdx(), IsValid(), ToString(), and lczero::Move::WhitePromotion().
The documentation for this struct was generated from the following file:
src/chess/types.h