Leela Chess Zero: lczero::Rank Struct Reference
lczero::Rank Struct Reference
#include <types.h>
Public Member Functions
constexpr bool IsValid () const
void Flip ()
std::string ToString () const
auto operator<=> (const Rank &other) const =default
void operator-- ()
void operator++ ()
void operator+= (int delta)
Rank operator+ (int delta) const
Rank operator- (int delta) const
Static Public Member Functions
static constexpr Rank FromIdx (uint8_t idx)
static constexpr Rank Parse (char c)
Public Attributes
uint8_t idx
Private Member Functions
constexpr Rank (uint8_t idx)
Detailed Description
Definition at line 85 of file types.h.
Constructor & Destructor Documentation
Rank()
constexpr lczero::Rank::Rank (uint8_t idx) inline explicit constexpr private
Definition at line 100 of file types.h.
Member Function Documentation
Flip()
void lczero::Rank::Flip () inline
Definition at line 90 of file types.h.
References idx.
Referenced by lczero::ChessBoard::ParseMove().
FromIdx()
static constexpr Rank lczero::Rank::FromIdx (uint8_t idx) inline static constexpr
Definition at line 88 of file types.h.
References idx.
Referenced by lczero::BitBoard::DebugString(), lczero::ChessBoard::GenerateKingAttackInfo(), lczero::PopulateBoard(), lczero::Square::rank(), and lczero::PgnReader::SanToMove().
IsValid()
constexpr bool lczero::Rank::IsValid () const inline constexpr
Definition at line 87 of file types.h.
References idx.
Referenced by lczero::BoardToFen(), lczero::ChessBoard::GeneratePseudolegalMoves(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
operator+()
Rank lczero::Rank::operator+ (int delta) const inline
Definition at line 96 of file types.h.
References idx.
operator++()
void lczero::Rank::operator++ () inline
Definition at line 94 of file types.h.
References idx.
operator+=()
void lczero::Rank::operator+= (int delta) inline
Definition at line 95 of file types.h.
References idx.
operator-()
Rank lczero::Rank::operator- (int delta) const inline
Definition at line 97 of file types.h.
References idx.
operator--()
void lczero::Rank::operator-- () inline
Definition at line 93 of file types.h.
References idx.
operator<=>()
auto lczero::Rank::operator<=> (const Rank & other) const default
Parse()
static constexpr Rank lczero::Rank::Parse (char c) inline static constexpr
Definition at line 89 of file types.h.
Referenced by lczero::Square::Parse(), lczero::ChessBoard::ParseMove(), and lczero::ChessBoard::SetFromFen().
ToString()
std::string lczero::Rank::ToString () const inline
Definition at line 91 of file types.h.
References idx.
Referenced by lczero::Move::ToString(), and lczero::Square::ToString().
Member Data Documentation
idx
uint8_t lczero::Rank::idx
Definition at line 86 of file types.h.
Referenced by Flip(), FromIdx(), lczero::ChessBoard::GenerateKingAttackInfo(), IsValid(), operator+(), operator++(), operator+=(), operator-(), lczero::operator-(), operator--(), and ToString().
The documentation for this struct was generated from the following file:
/home/contrad-namiseb/Desktop/Github/lc0-linux-binaries/src/chess/types.h