Leela Chess Zero: src/version.cc File Reference
version.cc File Reference
#include "version.h"
Functions
std::uint32_t GetVersionInt (int major, int minor, int patch)
std::string GetVersionStr (int major, int minor, int patch, const std::string &postfix, const std::string &build_id)
Function Documentation
GetVersionInt()
std::uint32_t GetVersionInt (int major, int minor, int patch)
Definition at line 29 of file version.cc.
GetVersionStr()
std::string GetVersionStr (int major, int minor, int patch, const std::string & postfix, const std::string & build_id)
Definition at line 33 of file version.cc.
Referenced by main(), lczero::OnnxBuilder::OnnxBuilder(), and lczero::StringUciResponder::SendId().